Dune::XT::Grid::DirichletBoundary Class Reference
Dune::XT::Grid::DirichletBoundary Class Reference
#include <dune/xt/grid/boundaryinfo/types.hh>
Public Member Functions
virtual bool operator== (const BoundaryType &other) const
virtual bool operator!= (const BoundaryType &other) const
Protected Member Functions
virtual std::string id () const overridefinal
Member Function Documentation
virtual std::string Dune::XT::Grid::DirichletBoundary::id () const inline final override protected virtual
Implements Dune::XT::Grid::BoundaryType.
virtual bool Dune::XT::Grid::BoundaryType::operator!= (const BoundaryType & other) const inline virtual inherited
References Dune::XT::Grid::BoundaryType::operator==().
virtual bool Dune::XT::Grid::BoundaryType::operator== (const BoundaryType & other) const inline virtual inherited
References Dune::XT::Grid::BoundaryType::id().
Referenced by Dune::XT::Grid::BoundaryType::operator!=().
The documentation for this class was generated from the following file:
types.hh