Dune::XT::Grid::BoundaryInfo< IntersectionImp > Class Template Reference
Dune::XT::Grid::BoundaryInfo< IntersectionImp > Class Template Reference abstract
#include <dune/xt/grid/boundaryinfo/interfaces.hh>
Public Types
typedef IntersectionImp IntersectionType
typedef IntersectionType::ctype DomainFieldType
typedef Common::FieldVector
< DomainFieldType, dimDomain > DomainType
typedef Common::FieldVector
< DomainFieldType, dimWorld > WorldType
Public Member Functions
virtual const BoundaryType & type (const IntersectionType &intersection) const =0
Static Public Member Functions
static std::string static_id ()
Static Public Attributes
static const size_t dimDomain = IntersectionType::dimension
static const size_t dimWorld = IntersectionType::dimensionworld
Member Typedef Documentation
template<class IntersectionImp> typedef IntersectionType::ctype Dune::XT::Grid::BoundaryInfo< IntersectionImp >::DomainFieldType
template<class IntersectionImp> typedef Common::FieldVector<DomainFieldType, dimDomain> Dune::XT::Grid::BoundaryInfo< IntersectionImp >::DomainType
template<class IntersectionImp> typedef IntersectionImp Dune::XT::Grid::BoundaryInfo< IntersectionImp >::IntersectionType
template<class IntersectionImp> typedef Common::FieldVector<DomainFieldType, dimWorld> Dune::XT::Grid::BoundaryInfo< IntersectionImp >::WorldType
Member Function Documentation
template<class IntersectionImp> static std::string Dune::XT::Grid::BoundaryInfo< IntersectionImp >::static_id () inline static
template<class IntersectionImp> virtual const BoundaryType& Dune::XT::Grid::BoundaryInfo< IntersectionImp >::type (const IntersectionType & intersection) const pure virtual
Implemented in Dune::XT::Grid::NormalBasedBoundaryInfo< IntersectionImp >, Dune::XT::Grid::AllDirichletBoundaryInfo< IntersectionImp >, and Dune::XT::Grid::AllNeumannBoundaryInfo< IntersectionImp >.
Referenced by Dune::XT::Grid::Functor::DirichletDetector< GridViewImp >::apply_local(), Dune::XT::Grid::ApplyOn::DirichletIntersections< GridViewImp >::apply_on(), and Dune::XT::Grid::ApplyOn::NeumannIntersections< GridViewImp >::apply_on().
Member Data Documentation
template<class IntersectionImp> const size_t Dune::XT::Grid::BoundaryInfo< IntersectionImp >::dimDomain = IntersectionType::dimension static
template<class IntersectionImp> const size_t Dune::XT::Grid::BoundaryInfo< IntersectionImp >::dimWorld = IntersectionType::dimensionworld static
Referenced by Dune::XT::Grid::NormalBasedBoundaryInfo< IntersectionImp >::getVectors().
The documentation for this class was generated from the following file:
interfaces.hh