Dune::XT::Grid::CubeGridProviderFactory< GridType > Class Template Reference
Dune::XT::Grid::CubeGridProviderFactory< GridType > Class Template Reference
#include <dune/xt/grid/gridprovider/cube.hh>
Static Public Member Functions
static std::string static_id ()
static Common::Configuration default_config ()
static GridProvider< GridType > create (const FieldVector< typename GridType::ctype, GridType::dimension > &lower_left, const FieldVector< typename GridType::ctype, GridType::dimension > &upper_right, const std::array< unsigned int, GridType::dimension > &num_elements, const unsigned int num_refinements, const std::array< unsigned int, GridType::dimension > &overlap_size)
TODO simplex grid overlap_size.
static GridProvider< GridType > create (const typename GridType::ctype &lower_left, const typename GridType::ctype &upper_right, const unsigned int num_elements=cube_gridprovider_default_config().template get< std::vector< unsigned int >>("num_elements")[0], const unsigned int num_refinements=cube_gridprovider_default_config().template get< unsigned int >("num_refinements"), const unsigned int overlap_size=cube_gridprovider_default_config().template get< std::vector< unsigned int >>("overlap_size")[0])
static GridProvider< GridType > create (const Common::Configuration &cfg=cube_gridprovider_default_config())
Static Public Attributes
static const bool available = true
Member Function Documentation
template<class GridType > static GridProvider<GridType> Dune::XT::Grid::CubeGridProviderFactory< GridType >::create (const FieldVector< typename GridType::ctype, GridType::dimension > & lower_left, const FieldVector< typename GridType::ctype, GridType::dimension > & upper_right, const std::array< unsigned int, GridType::dimension > & num_elements, const unsigned int num_refinements, const std::array< unsigned int, GridType::dimension > & overlap_size) inline static
TODO simplex grid overlap_size.
References Dune::XT::Grid::StructuredGridFactory< GridType >::createCubeGrid().
Referenced by Dune::XT::Grid::CubeGridProviderFactory< GridType >::create(), and Dune::XT::Grid::make_cube_grid().
template<class GridType > static GridProvider<GridType> Dune::XT::Grid::CubeGridProviderFactory< GridType >::create (const typename GridType::ctype & lower_left, const typename GridType::ctype & upper_right, const unsigned int num_elements = cube_gridprovider_default_config().template get<std::vector<unsigned int>>("num_elements")[0], const unsigned int num_refinements = cube_gridprovider_default_config().template get<unsigned int>("num_refinements"), const unsigned int overlap_size = cube_gridprovider_default_config().template get<std::vector<unsigned int>>("overlap_size")[0]) inline static
References Dune::XT::Grid::CubeGridProviderFactory< GridType >::create().
template<class GridType > static GridProvider<GridType> Dune::XT::Grid::CubeGridProviderFactory< GridType >::create (const Common::Configuration & cfg = cube_gridprovider_default_config()) inline static
References Dune::XT::Grid::CubeGridProviderFactory< GridType >::create(), and Dune::XT::Grid::cube_gridprovider_default_config().
template<class GridType > static Common::Configuration Dune::XT::Grid::CubeGridProviderFactory< GridType >::default_config () inline static
References Dune::XT::Grid::cube_gridprovider_default_config().
template<class GridType > static std::string Dune::XT::Grid::CubeGridProviderFactory< GridType >::static_id () inline static
References Dune::XT::Grid::cube_gridprovider_id().
Member Data Documentation
template<class GridType > const bool Dune::XT::Grid::CubeGridProviderFactory< GridType >::available = true static
The documentation for this class was generated from the following file:
cube.hh