Dune::XT::Grid::GmshGridProviderFactory< GridType > Class Template Reference
Dune::XT::Grid::GmshGridProviderFactory< GridType > Class Template Reference
#include <dune/xt/grid/gridprovider/gmsh.hh>
Static Public Member Functions
static std::string static_id ()
static Common::Configuration default_config ()
static GridProvider< GridType > create (const std::string &filename)
static GridProvider< GridType > create (const Common::Configuration &cfg=default_config())
Static Public Attributes
static const bool available = false
Member Function Documentation
template<class GridType > static GridProvider<GridType> Dune::XT::Grid::GmshGridProviderFactory< GridType >::create (const std::string & filename) inline static
Referenced by Dune::XT::Grid::GmshGridProviderFactory< GridType >::create().
template<class GridType > static GridProvider<GridType> Dune::XT::Grid::GmshGridProviderFactory< GridType >::create (const Common::Configuration & cfg = default_config()) inline static
References Dune::XT::Grid::GmshGridProviderFactory< GridType >::create(), and Dune::XT::Grid::GmshGridProviderFactory< GridType >::default_config().
template<class GridType > static Common::Configuration Dune::XT::Grid::GmshGridProviderFactory< GridType >::default_config () inline static
References Dune::XT::Grid::gmsh_gridprovider_default_config().
Referenced by Dune::XT::Grid::GmshGridProviderFactory< GridType >::create().
template<class GridType > static std::string Dune::XT::Grid::GmshGridProviderFactory< GridType >::static_id () inline static
References Dune::XT::Grid::gmsh_gridprovider_id().
Member Data Documentation
template<class GridType > const bool Dune::XT::Grid::GmshGridProviderFactory< GridType >::available = false static
The documentation for this class was generated from the following file:
gmsh.hh