Dune::XT::Grid::Functor::Codim0And1< GridViewImp > Class Template Reference
Dune::XT::Grid::Functor::Codim0And1< GridViewImp > Class Template Reference abstract
#include <dune/xt/grid/walker/functors.hh>
Public Types
typedef GridViewImp GridViewType
typedef XT::Grid::Entity
< GridViewType >::Type EntityType
typedef XT::Grid::Intersection
< GridViewType >::Type IntersectionType
Public Member Functions
virtual ~Codim0And1 ()
virtual void prepare ()
virtual void apply_local (const EntityType &entity)=0
virtual void apply_local (const IntersectionType &, const EntityType &, const EntityType &)=0
virtual void finalize ()
Member Typedef Documentation
template<class GridViewImp> typedef XT::Grid::Entity<GridViewType>::Type Dune::XT::Grid::Functor::Codim0And1< GridViewImp >::EntityType
template<class GridViewImp> typedef GridViewImp Dune::XT::Grid::Functor::Codim0And1< GridViewImp >::GridViewType
template<class GridViewImp> typedef XT::Grid::Intersection<GridViewType>::Type Dune::XT::Grid::Functor::Codim0And1< GridViewImp >::IntersectionType
Constructor & Destructor Documentation
template<class GridViewImp> virtual Dune::XT::Grid::Functor::Codim0And1< GridViewImp >::~Codim0And1 () inline virtual
Member Function Documentation
template<class GridViewImp> virtual void Dune::XT::Grid::Functor::Codim0And1< GridViewImp >::apply_local (const EntityType & entity) pure virtual
Implemented in Dune::XT::Grid::Walker< GridViewImp >.
Referenced by Dune::XT::Grid::Walker< GridViewImp >::apply_local().
template<class GridViewImp> virtual void Dune::XT::Grid::Functor::Codim0And1< GridViewImp >::apply_local (const IntersectionType & , const EntityType & , const EntityType &) pure virtual
Implemented in Dune::XT::Grid::Walker< GridViewImp >.
template<class GridViewImp> virtual void Dune::XT::Grid::Functor::Codim0And1< GridViewImp >::finalize () inline virtual
Reimplemented in Dune::XT::Grid::Walker< GridViewImp >.
Referenced by Dune::XT::Grid::Walker< GridViewImp >::finalize().
template<class GridViewImp> virtual void Dune::XT::Grid::Functor::Codim0And1< GridViewImp >::prepare () inline virtual
Reimplemented in Dune::XT::Grid::Walker< GridViewImp >.
Referenced by Dune::XT::Grid::Walker< GridViewImp >::prepare().
The documentation for this class was generated from the following file:
functors.hh