Dune::XT::Grid::Walker< GridViewImp > Class Template Reference
Dune::XT::Grid::Walker< GridViewImp > Class Template Reference
#include <dune/xt/grid/walker.hh>
Public Types
typedef GridViewImp GridViewType
typedef XT::Grid::Entity
< GridViewType >::Type EntityType
typedef XT::Grid::Intersection
< GridViewType >::Type IntersectionType
Public Member Functions
Walker (GridViewType grd_vw)
const GridViewType & grid_view () const
ThisType & add (std::function< void(const EntityType &)> lambda, const ApplyOn::WhichEntity< GridViewType > *where=new ApplyOn::AllEntities< GridViewType >())
ThisType & add (std::function< void(const IntersectionType &, const EntityType &, const EntityType &)> lambda, const ApplyOn::WhichIntersection< GridViewType > *where=new ApplyOn::AllIntersections< GridViewType >())
ThisType & add (Functor::Codim0< GridViewType > &functor, const ApplyOn::WhichEntity< GridViewType > *where=new ApplyOn::AllEntities< GridViewType >())
ThisType & add (Functor::Codim1< GridViewType > &functor, const ApplyOn::WhichIntersection< GridViewType > *where=new ApplyOn::AllIntersections< GridViewType >())
ThisType & add (Functor::Codim0And1< GridViewType > &functor, const ApplyOn::WhichEntity< GridViewType > *which_entities=new ApplyOn::AllEntities< GridViewType >(), const ApplyOn::WhichIntersection< GridViewType > *which_intersections=new ApplyOn::AllIntersections< GridViewType >())
ThisType & add (Functor::Codim0And1< GridViewType > &functor, const ApplyOn::WhichIntersection< GridViewType > *which_intersections, const ApplyOn::WhichEntity< GridViewType > *which_entities=new ApplyOn::AllEntities< GridViewType >())
ThisType & add (ThisType &other, const ApplyOn::WhichEntity< GridViewType > *which_entities=new ApplyOn::AllEntities< GridViewType >(), const ApplyOn::WhichIntersection< GridViewType > *which_intersections=new ApplyOn::AllIntersections< GridViewType >())
ThisType & add (ThisType &other, const ApplyOn::WhichIntersection< GridViewType > *which_intersections, const ApplyOn::WhichEntity< GridViewType > *which_entities=new ApplyOn::AllEntities< GridViewType >())
void clear ()
virtual void prepare ()
bool apply_on (const EntityType &entity) const
bool apply_on (const IntersectionType &intersection) const
virtual void apply_local (const EntityType &entity)
virtual void apply_local (const IntersectionType &intersection, const EntityType &inside_entity, const EntityType &outside_entity)
virtual void finalize ()
void walk (const bool use_tbb=false)
Protected Member Functions
template<class EntityRange >
void walk_range (const EntityRange &entity_range)
Protected Attributes
std::vector< std::unique_ptr
< internal::Codim0Object
< GridViewType > > > codim0_functors_
std::vector< std::unique_ptr
< internal::Codim1Object
< GridViewType > > > codim1_functors_
Private Types
typedef GridViewImp type
Private Member Functions
const type & real_grid_view () const
Private Attributes
const GridViewImp grid_view_
Member Typedef Documentation
template<class GridViewImp> typedef XT::Grid::Entity<GridViewType>::Type Dune::XT::Grid::Walker< GridViewImp >::EntityType
template<class GridViewImp> typedef GridViewImp Dune::XT::Grid::Walker< GridViewImp >::GridViewType
template<class GridViewImp> typedef XT::Grid::Intersection<GridViewType>::Type Dune::XT::Grid::Walker< GridViewImp >::IntersectionType
Constructor & Destructor Documentation
template<class GridViewImp> Dune::XT::Grid::Walker< GridViewImp >::Walker (GridViewType grd_vw) inline explicit
Member Function Documentation
template<class GridViewImp> ThisType& Dune::XT::Grid::Walker< GridViewImp >::add (std::function< void(const EntityType &)> lambda, const ApplyOn::WhichEntity< GridViewType > * where = new ApplyOn::AllEntities<GridViewType>()) inline
References Dune::XT::Grid::Walker< GridViewImp >::codim0_functors_.
Referenced by Dune::XT::Grid::Dimensions< GridViewType >::Dimensions(), Dune::XT::Grid::EnforceMaximumEntityVolume(), Dune::XT::Grid::PgfOutput< GridType >::refineseries(), and Dune::XT::Grid::PgfOutput< GridType >::stacked().
template<class GridViewImp> ThisType& Dune::XT::Grid::Walker< GridViewImp >::add (std::function< void(const IntersectionType &, const EntityType &, const EntityType &)> lambda, const ApplyOn::WhichIntersection< GridViewType > * where = new ApplyOn::AllIntersections<GridViewType>()) inline
References Dune::XT::Grid::Walker< GridViewImp >::codim1_functors_.
template<class GridViewImp> ThisType& Dune::XT::Grid::Walker< GridViewImp >::add (Functor::Codim0< GridViewType > & functor, const ApplyOn::WhichEntity< GridViewType > * where = new ApplyOn::AllEntities<GridViewType>()) inline
References Dune::XT::Grid::Walker< GridViewImp >::codim0_functors_.
template<class GridViewImp> ThisType& Dune::XT::Grid::Walker< GridViewImp >::add (Functor::Codim1< GridViewType > & functor, const ApplyOn::WhichIntersection< GridViewType > * where = new ApplyOn::AllIntersections<GridViewType>()) inline
References Dune::XT::Grid::Walker< GridViewImp >::codim1_functors_.
template<class GridViewImp> ThisType& Dune::XT::Grid::Walker< GridViewImp >::add (Functor::Codim0And1< GridViewType > & functor, const ApplyOn::WhichEntity< GridViewType > * which_entities = new ApplyOn::AllEntities<GridViewType>(), const ApplyOn::WhichIntersection< GridViewType > * which_intersections = new ApplyOn::AllIntersections<GridViewType>()) inline
References Dune::XT::Grid::Walker< GridViewImp >::codim0_functors_, and Dune::XT::Grid::Walker< GridViewImp >::codim1_functors_.
template<class GridViewImp> ThisType& Dune::XT::Grid::Walker< GridViewImp >::add (Functor::Codim0And1< GridViewType > & functor, const ApplyOn::WhichIntersection< GridViewType > * which_intersections, const ApplyOn::WhichEntity< GridViewType > * which_entities = new ApplyOn::AllEntities<GridViewType>()) inline
References Dune::XT::Grid::Walker< GridViewImp >::codim0_functors_, and Dune::XT::Grid::Walker< GridViewImp >::codim1_functors_.
template<class GridViewImp> ThisType& Dune::XT::Grid::Walker< GridViewImp >::add (ThisType & other, const ApplyOn::WhichEntity< GridViewType > * which_entities = new ApplyOn::AllEntities<GridViewType>(), const ApplyOn::WhichIntersection< GridViewType > * which_intersections = new ApplyOn::AllIntersections<GridViewType>()) inline
References Dune::XT::Grid::Walker< GridViewImp >::codim0_functors_, and Dune::XT::Grid::Walker< GridViewImp >::codim1_functors_.
template<class GridViewImp> ThisType& Dune::XT::Grid::Walker< GridViewImp >::add (ThisType & other, const ApplyOn::WhichIntersection< GridViewType > * which_intersections, const ApplyOn::WhichEntity< GridViewType > * which_entities = new ApplyOn::AllEntities<GridViewType>()) inline
References Dune::XT::Grid::Walker< GridViewImp >::codim0_functors_, and Dune::XT::Grid::Walker< GridViewImp >::codim1_functors_.
template<class GridViewImp> virtual void Dune::XT::Grid::Walker< GridViewImp >::apply_local (const EntityType & entity) inline virtual
Implements Dune::XT::Grid::Functor::Codim0And1< GridViewImp >.
References Dune::XT::Grid::Functor::Codim0And1< GridViewImp >::apply_local(), and Dune::XT::Grid::Walker< GridViewImp >::codim0_functors_.
Referenced by Dune::XT::Grid::Walker< GridViewImp >::walk_range().
template<class GridViewImp> virtual void Dune::XT::Grid::Walker< GridViewImp >::apply_local (const IntersectionType & intersection, const EntityType & inside_entity, const EntityType & outside_entity) inline virtual
Implements Dune::XT::Grid::Functor::Codim0And1< GridViewImp >.
References Dune::XT::Grid::Functor::Codim0And1< GridViewImp >::apply_local(), and Dune::XT::Grid::Walker< GridViewImp >::codim1_functors_.
template<class GridViewImp> bool Dune::XT::Grid::Walker< GridViewImp >::apply_on (const EntityType & entity) const inline
References Dune::XT::Grid::Walker< GridViewImp >::codim0_functors_.
template<class GridViewImp> bool Dune::XT::Grid::Walker< GridViewImp >::apply_on (const IntersectionType & intersection) const inline
References Dune::XT::Grid::Walker< GridViewImp >::codim1_functors_.
template<class GridViewImp> void Dune::XT::Grid::Walker< GridViewImp >::clear () inline
References Dune::XT::Grid::Walker< GridViewImp >::codim0_functors_, and Dune::XT::Grid::Walker< GridViewImp >::codim1_functors_.
Referenced by Dune::XT::Grid::Walker< GridViewImp >::walk().
template<class GridViewImp> virtual void Dune::XT::Grid::Walker< GridViewImp >::finalize () inline virtual
Reimplemented from Dune::XT::Grid::Functor::Codim0And1< GridViewImp >.
References Dune::XT::Grid::Walker< GridViewImp >::codim0_functors_, Dune::XT::Grid::Walker< GridViewImp >::codim1_functors_, and Dune::XT::Grid::Functor::Codim0And1< GridViewImp >::finalize().
Referenced by Dune::XT::Grid::Walker< GridViewImp >::walk().
template<class GridViewImp> const GridViewType& Dune::XT::Grid::Walker< GridViewImp >::grid_view () const inline
References Dune::XT::Grid::internal::GridPartViewHolder< GridViewImp >::grid_view_.
template<class GridViewImp> virtual void Dune::XT::Grid::Walker< GridViewImp >::prepare () inline virtual
Reimplemented from Dune::XT::Grid::Functor::Codim0And1< GridViewImp >.
References Dune::XT::Grid::Walker< GridViewImp >::codim0_functors_, Dune::XT::Grid::Walker< GridViewImp >::codim1_functors_, and Dune::XT::Grid::Functor::Codim0And1< GridViewImp >::prepare().
Referenced by Dune::XT::Grid::Walker< GridViewImp >::walk().
template<class GridViewImp> void Dune::XT::Grid::Walker< GridViewImp >::walk (const bool use_tbb = false) inline
References Dune::XT::Grid::Walker< GridViewImp >::clear(), Dune::XT::Grid::Walker< GridViewImp >::codim0_functors_, Dune::XT::Grid::Walker< GridViewImp >::codim1_functors_, Dune::XT::Grid::Walker< GridViewImp >::finalize(), Dune::XT::Grid::internal::GridPartViewHolder< GridViewImp >::grid_view_, Dune::XT::Grid::Walker< GridViewImp >::prepare(), Dune::XT::Grid::internal::GridPartViewHolder< GridViewImp >::real_grid_view(), and Dune::XT::Grid::Walker< GridViewImp >::walk_range().
Referenced by Dune::XT::Grid::Dimensions< GridViewType >::Dimensions(), Dune::XT::Grid::EnforceMaximumEntityVolume(), Dune::XT::Grid::PgfOutput< GridType >::refineseries(), and Dune::XT::Grid::PgfOutput< GridType >::stacked().
template<class GridViewImp> template<class EntityRange > void Dune::XT::Grid::Walker< GridViewImp >::walk_range (const EntityRange & entity_range) inline protected
References Dune::XT::Grid::Walker< GridViewImp >::apply_local(), Dune::XT::Grid::Walker< GridViewImp >::codim1_functors_, and Dune::XT::Grid::internal::GridPartViewHolder< GridViewImp >::grid_view_.
Referenced by Dune::XT::Grid::Walker< GridViewImp >::walk().
Member Data Documentation
template<class GridViewImp> std::vector<std::unique_ptr<internal::Codim0Object<GridViewType> > > Dune::XT::Grid::Walker< GridViewImp >::codim0_functors_ protected
Referenced by Dune::XT::Grid::Walker< GridViewImp >::add(), Dune::XT::Grid::Walker< GridViewImp >::apply_local(), Dune::XT::Grid::Walker< GridViewImp >::apply_on(), Dune::XT::Grid::Walker< GridViewImp >::clear(), Dune::XT::Grid::Walker< GridViewImp >::finalize(), Dune::XT::Grid::Walker< GridViewImp >::prepare(), and Dune::XT::Grid::Walker< GridViewImp >::walk().
template<class GridViewImp> std::vector<std::unique_ptr<internal::Codim1Object<GridViewType> > > Dune::XT::Grid::Walker< GridViewImp >::codim1_functors_ protected
Referenced by Dune::XT::Grid::Walker< GridViewImp >::add(), Dune::XT::Grid::Walker< GridViewImp >::apply_local(), Dune::XT::Grid::Walker< GridViewImp >::apply_on(), Dune::XT::Grid::Walker< GridViewImp >::clear(), Dune::XT::Grid::Walker< GridViewImp >::finalize(), Dune::XT::Grid::Walker< GridViewImp >::prepare(), Dune::XT::Grid::Walker< GridViewImp >::walk(), and Dune::XT::Grid::Walker< GridViewImp >::walk_range().
The documentation for this class was generated from the following file:
walker.hh