Dune::XT::Grid::internal::PeriodicGridViewImp< RealGridViewImp, use_less_memory > Class Template Reference
Dune::XT::Grid::internal::PeriodicGridViewImp< RealGridViewImp, use_less_memory > Class Template Reference
Actual Implementation of PeriodicGridView.
#include <dune/xt/grid/periodic_gridview.hh>
Classes
struct Codim
Public Types
typedef BaseType::Grid Grid
typedef PeriodicIndexSet
< BaseType, use_less_memory > IndexSet
typedef BaseType::template
Codim< 0 >::Entity EntityType
typedef
PeriodicIntersectionIterator
< BaseType > IntersectionIterator
typedef
IntersectionIterator::RealIntersectionType RealIntersectionType
typedef Traits::IndexSet::IndexType IndexType
typedef int IntersectionIndexType
typedef
RealIntersectionType::GlobalCoordinate DomainType
typedef PeriodicIntersection
< BaseType > Intersection
typedef std::map
< IntersectionIndexType,
std::pair< bool, EntityType > > IntersectionMapType
typedef std::map< IndexType,
IndexType > IndexMapType
Public Member Functions
PeriodicGridViewImp (const BaseType &real_grid_view, const std::bitset< dimDomain > periodic_directions)
int size (int codim) const
int size (const Dune::GeometryType &type) const
template<int cd>
Codim< cd >::Iterator begin () const
template<int cd>
Codim< cd >::Iterator end () const
template<int cd, PartitionIteratorType pitype>
Codim< cd >::template
Partition< pitype >::Iterator begin () const
template<int cd, PartitionIteratorType pitype>
Codim< cd >::template
Partition< pitype >::Iterator end () const
const IndexSet & indexSet () const
IntersectionIterator ibegin (const typename Codim< 0 >::Entity &entity) const
IntersectionIterator iend (const typename Codim< 0 >::Entity &entity) const
Static Public Attributes
static const size_t dimDomain = BaseType::dimension
Detailed Description
template<class RealGridViewImp, bool use_less_memory>
class Dune::XT::Grid::internal::PeriodicGridViewImp< RealGridViewImp, use_less_memory >
Actual Implementation of PeriodicGridView.
See Also
PeriodicGridView
Member Typedef Documentation
template<class RealGridViewImp , bool use_less_memory> typedef RealIntersectionType::GlobalCoordinate Dune::XT::Grid::internal::PeriodicGridViewImp< RealGridViewImp, use_less_memory >::DomainType
template<class RealGridViewImp , bool use_less_memory> typedef BaseType::template Codim<0>::Entity Dune::XT::Grid::internal::PeriodicGridViewImp< RealGridViewImp, use_less_memory >::EntityType
template<class RealGridViewImp , bool use_less_memory> typedef BaseType::Grid Dune::XT::Grid::internal::PeriodicGridViewImp< RealGridViewImp, use_less_memory >::Grid
template<class RealGridViewImp , bool use_less_memory> typedef std::map<IndexType, IndexType> Dune::XT::Grid::internal::PeriodicGridViewImp< RealGridViewImp, use_less_memory >::IndexMapType
template<class RealGridViewImp , bool use_less_memory> typedef PeriodicIndexSet<BaseType, use_less_memory> Dune::XT::Grid::internal::PeriodicGridViewImp< RealGridViewImp, use_less_memory >::IndexSet
template<class RealGridViewImp , bool use_less_memory> typedef Traits::IndexSet::IndexType Dune::XT::Grid::internal::PeriodicGridViewImp< RealGridViewImp, use_less_memory >::IndexType
template<class RealGridViewImp , bool use_less_memory> typedef PeriodicIntersection<BaseType> Dune::XT::Grid::internal::PeriodicGridViewImp< RealGridViewImp, use_less_memory >::Intersection
template<class RealGridViewImp , bool use_less_memory> typedef int Dune::XT::Grid::internal::PeriodicGridViewImp< RealGridViewImp, use_less_memory >::IntersectionIndexType
template<class RealGridViewImp , bool use_less_memory> typedef PeriodicIntersectionIterator<BaseType> Dune::XT::Grid::internal::PeriodicGridViewImp< RealGridViewImp, use_less_memory >::IntersectionIterator
template<class RealGridViewImp , bool use_less_memory> typedef std::map<IntersectionIndexType, std::pair<bool, EntityType> > Dune::XT::Grid::internal::PeriodicGridViewImp< RealGridViewImp, use_less_memory >::IntersectionMapType
template<class RealGridViewImp , bool use_less_memory> typedef IntersectionIterator::RealIntersectionType Dune::XT::Grid::internal::PeriodicGridViewImp< RealGridViewImp, use_less_memory >::RealIntersectionType
Constructor & Destructor Documentation
template<class RealGridViewImp , bool use_less_memory> Dune::XT::Grid::internal::PeriodicGridViewImp< RealGridViewImp, use_less_memory >::PeriodicGridViewImp (const BaseType & real_grid_view, const std::bitset< dimDomain > periodic_directions) inline
References Dune::XT::Grid::internal::PeriodicGridViewImp< RealGridViewImp, use_less_memory >::dimDomain.
Member Function Documentation
template<class RealGridViewImp , bool use_less_memory> template<int cd> Codim<cd>::Iterator Dune::XT::Grid::internal::PeriodicGridViewImp< RealGridViewImp, use_less_memory >::begin () const inline
template<class RealGridViewImp , bool use_less_memory> template<int cd, PartitionIteratorType pitype> Codim<cd>::template Partition<pitype>::Iterator Dune::XT::Grid::internal::PeriodicGridViewImp< RealGridViewImp, use_less_memory >::begin () const inline
template<class RealGridViewImp , bool use_less_memory> template<int cd> Codim<cd>::Iterator Dune::XT::Grid::internal::PeriodicGridViewImp< RealGridViewImp, use_less_memory >::end () const inline
template<class RealGridViewImp , bool use_less_memory> template<int cd, PartitionIteratorType pitype> Codim<cd>::template Partition<pitype>::Iterator Dune::XT::Grid::internal::PeriodicGridViewImp< RealGridViewImp, use_less_memory >::end () const inline
template<class RealGridViewImp , bool use_less_memory> IntersectionIterator Dune::XT::Grid::internal::PeriodicGridViewImp< RealGridViewImp, use_less_memory >::ibegin (const typename Codim< 0 >::Entity & entity) const inline
References Dune::XT::Grid::internal::PeriodicGridViewImp< RealGridViewImp, use_less_memory >::indexSet().
template<class RealGridViewImp , bool use_less_memory> IntersectionIterator Dune::XT::Grid::internal::PeriodicGridViewImp< RealGridViewImp, use_less_memory >::iend (const typename Codim< 0 >::Entity & entity) const inline
References Dune::XT::Grid::internal::PeriodicGridViewImp< RealGridViewImp, use_less_memory >::indexSet().
template<class RealGridViewImp , bool use_less_memory> const IndexSet& Dune::XT::Grid::internal::PeriodicGridViewImp< RealGridViewImp, use_less_memory >::indexSet () const inline
Referenced by Dune::XT::Grid::internal::PeriodicGridViewImp< RealGridViewImp, use_less_memory >::ibegin(), and Dune::XT::Grid::internal::PeriodicGridViewImp< RealGridViewImp, use_less_memory >::iend().
template<class RealGridViewImp , bool use_less_memory> int Dune::XT::Grid::internal::PeriodicGridViewImp< RealGridViewImp, use_less_memory >::size (int codim) const inline
template<class RealGridViewImp , bool use_less_memory> int Dune::XT::Grid::internal::PeriodicGridViewImp< RealGridViewImp, use_less_memory >::size (const Dune::GeometryType & type) const inline
Member Data Documentation
template<class RealGridViewImp , bool use_less_memory> const size_t Dune::XT::Grid::internal::PeriodicGridViewImp< RealGridViewImp, use_less_memory >::dimDomain = BaseType::dimension static
Referenced by Dune::XT::Grid::internal::PeriodicGridViewImp< RealGridViewImp, use_less_memory >::PeriodicGridViewImp().
The documentation for this class was generated from the following file:
periodic_gridview.hh