Dune::XT::Grid::NormalBasedBoundaryInfo< IntersectionImp > Class Template Reference
Dune::XT::Grid::NormalBasedBoundaryInfo< IntersectionImp > Class Template Reference
#include <dune/xt/grid/boundaryinfo/normalbased.hh>
Public Types
typedef IntersectionImp IntersectionType
typedef IntersectionType::ctype DomainFieldType
typedef Common::FieldVector
< DomainFieldType, dimDomain > DomainType
typedef Common::FieldVector
< DomainFieldType, dimWorld > WorldType
Public Member Functions
NormalBasedBoundaryInfo (const bool default_to_dirichlet=true, const std::vector< WorldType > dirichlet_normals=std::vector< WorldType >(), const std::vector< WorldType > neumann_normals=std::vector< WorldType >(), const DomainFieldType tol=1e-10)
virtual const BoundaryType & type (const IntersectionType &intersection) const overridefinal
Static Public Member Functions
static std::string static_id ()
static std::unique_ptr< ThisType > create (const Common::Configuration cfg=normalbased_boundaryinfo_default_config())
Static Public Attributes
static const size_t dimDomain = IntersectionType::dimension
static const size_t dimWorld = IntersectionType::dimensionworld
Protected Member Functions
bool contains (const WorldType &normal, const std::vector< WorldType > &vectors) const
Static Protected Member Functions
static std::vector< WorldType > getVectors (const Common::Configuration &config, const std::string key)
Protected Attributes
const bool default_to_dirichlet_
std::vector< WorldType > dirichlet_normals_
std::vector< WorldType > neumann_normals_
const DomainFieldType tol_
Static Protected Attributes
static constexpr NoBoundary no_boundary_ {}
static constexpr DirichletBoundary dirichlet_boundary_ {}
static constexpr NeumannBoundary neumann_boundary_ {}
Member Typedef Documentation
template<class IntersectionImp > typedef IntersectionType::ctype Dune::XT::Grid::BoundaryInfo< IntersectionImp >::DomainFieldType
template<class IntersectionImp > typedef Common::FieldVector<DomainFieldType, dimDomain> Dune::XT::Grid::BoundaryInfo< IntersectionImp >::DomainType
template<class IntersectionImp > typedef IntersectionImp Dune::XT::Grid::BoundaryInfo< IntersectionImp >::IntersectionType
template<class IntersectionImp > typedef Common::FieldVector<DomainFieldType, dimWorld> Dune::XT::Grid::BoundaryInfo< IntersectionImp >::WorldType
Constructor & Destructor Documentation
template<class IntersectionImp > Dune::XT::Grid::NormalBasedBoundaryInfo< IntersectionImp >::NormalBasedBoundaryInfo (const bool default_to_dirichlet = true, const std::vector< WorldType > dirichlet_normals = std::vector<WorldType>(), const std::vector< WorldType > neumann_normals = std::vector<WorldType>(), const DomainFieldType tol = 1e-10) inline
References Dune::XT::Grid::NormalBasedBoundaryInfo< IntersectionImp >::contains(), Dune::XT::Grid::NormalBasedBoundaryInfo< IntersectionImp >::dirichlet_normals_, and Dune::XT::Grid::NormalBasedBoundaryInfo< IntersectionImp >::neumann_normals_.
Member Function Documentation
template<class IntersectionImp > bool Dune::XT::Grid::NormalBasedBoundaryInfo< IntersectionImp >::contains (const WorldType & normal, const std::vector< WorldType > & vectors) const inline protected
References Dune::XT::Grid::NormalBasedBoundaryInfo< IntersectionImp >::tol_.
Referenced by Dune::XT::Grid::NormalBasedBoundaryInfo< IntersectionImp >::NormalBasedBoundaryInfo(), and Dune::XT::Grid::NormalBasedBoundaryInfo< IntersectionImp >::type().
template<class IntersectionImp > static std::unique_ptr<ThisType> Dune::XT::Grid::NormalBasedBoundaryInfo< IntersectionImp >::create (const Common::Configuration cfg = normalbased_boundaryinfo_default_config()) inline static
References Dune::XT::Grid::NormalBasedBoundaryInfo< IntersectionImp >::getVectors(), and Dune::XT::Grid::normalbased_boundaryinfo_default_config().
Referenced by Dune::XT::Grid::make_normalbased_boundaryinfo().
template<class IntersectionImp > static std::vector<WorldType> Dune::XT::Grid::NormalBasedBoundaryInfo< IntersectionImp >::getVectors (const Common::Configuration & config, const std::string key) inline static protected
References Dune::XT::Grid::BoundaryInfo< IntersectionImp >::dimWorld.
Referenced by Dune::XT::Grid::NormalBasedBoundaryInfo< IntersectionImp >::create().
template<class IntersectionImp > static std::string Dune::XT::Grid::NormalBasedBoundaryInfo< IntersectionImp >::static_id () inline static
References Dune::XT::Grid::normalbased_boundaryinfo_default_config().
Referenced by Dune::XT::Grid::BoundaryInfoFactory< I >::available().
template<class IntersectionImp > virtual const BoundaryType& Dune::XT::Grid::NormalBasedBoundaryInfo< IntersectionImp >::type (const IntersectionType & intersection) const inline final override virtual
Implements Dune::XT::Grid::BoundaryInfo< IntersectionImp >.
References Dune::XT::Grid::NormalBasedBoundaryInfo< IntersectionImp >::contains(), Dune::XT::Grid::NormalBasedBoundaryInfo< IntersectionImp >::dirichlet_boundary_, Dune::XT::Grid::NormalBasedBoundaryInfo< IntersectionImp >::dirichlet_normals_, Dune::XT::Grid::NormalBasedBoundaryInfo< IntersectionImp >::neumann_boundary_, Dune::XT::Grid::NormalBasedBoundaryInfo< IntersectionImp >::neumann_normals_, and Dune::XT::Grid::NormalBasedBoundaryInfo< IntersectionImp >::no_boundary_.
Member Data Documentation
template<class IntersectionImp > const bool Dune::XT::Grid::NormalBasedBoundaryInfo< IntersectionImp >::default_to_dirichlet_ protected
template<class IntersectionImp> const size_t Dune::XT::Grid::BoundaryInfo< IntersectionImp >::dimDomain = IntersectionType::dimension static inherited
template<class IntersectionImp> const size_t Dune::XT::Grid::BoundaryInfo< IntersectionImp >::dimWorld = IntersectionType::dimensionworld static inherited
Referenced by Dune::XT::Grid::NormalBasedBoundaryInfo< IntersectionImp >::getVectors().
template<class IntersectionImp > constexpr DirichletBoundary Dune::XT::Grid::NormalBasedBoundaryInfo< I >::dirichlet_boundary_ {} static protected
Referenced by Dune::XT::Grid::NormalBasedBoundaryInfo< IntersectionImp >::type().
template<class IntersectionImp > std::vector<WorldType> Dune::XT::Grid::NormalBasedBoundaryInfo< IntersectionImp >::dirichlet_normals_ protected
Referenced by Dune::XT::Grid::NormalBasedBoundaryInfo< IntersectionImp >::NormalBasedBoundaryInfo(), and Dune::XT::Grid::NormalBasedBoundaryInfo< IntersectionImp >::type().
template<class IntersectionImp > constexpr NeumannBoundary Dune::XT::Grid::NormalBasedBoundaryInfo< I >::neumann_boundary_ {} static protected
Referenced by Dune::XT::Grid::NormalBasedBoundaryInfo< IntersectionImp >::type().
template<class IntersectionImp > std::vector<WorldType> Dune::XT::Grid::NormalBasedBoundaryInfo< IntersectionImp >::neumann_normals_ protected
Referenced by Dune::XT::Grid::NormalBasedBoundaryInfo< IntersectionImp >::NormalBasedBoundaryInfo(), and Dune::XT::Grid::NormalBasedBoundaryInfo< IntersectionImp >::type().
template<class IntersectionImp > constexpr NoBoundary Dune::XT::Grid::NormalBasedBoundaryInfo< I >::no_boundary_ {} static protected
Referenced by Dune::XT::Grid::NormalBasedBoundaryInfo< IntersectionImp >::type().
template<class IntersectionImp > const DomainFieldType Dune::XT::Grid::NormalBasedBoundaryInfo< IntersectionImp >::tol_ protected
Referenced by Dune::XT::Grid::NormalBasedBoundaryInfo< IntersectionImp >::contains().
The documentation for this class was generated from the following file:
normalbased.hh