Dune::XT::Grid::GridProvider< GridImp > Class Template Reference
Dune::XT::Grid::GridProvider< GridImp > Class Template Reference
#include <dune/xt/grid/gridprovider/provider.hh>
Public Types
typedef GridProvider< GridImp > ThisType
typedef GridImp GridType
typedef GridType::ctype DomainFieldType
typedef FieldVector
< DomainFieldType, dimDomain > DomainType
typedef GridType::template
Codim< 0 >::Entity EntityType
typedef Layer< GridType,
Layers::level, Backends::view >
::type LevelGridViewType
typedef Layer< GridType,
Layers::leaf, Backends::view >
::type LeafGridViewType
Public Member Functions
GridProvider (GridType *grd_ptr)
GridProvider (std::unique_ptr< GridType > &&grd_ptr)
GridProvider (std::shared_ptr< GridType > grd_ptr)
GridProvider (const ThisType &other)=default
GridProvider (ThisType &&source)=default
ThisType & operator= (const ThisType &other)=delete
ThisType & operator= (ThisType &&source)=delete
const std::shared_ptr< GridType > & grid_ptr () const
std::shared_ptr< GridType > grid_ptr ()
const GridType & grid () const
GridType & grid ()
int max_level () const
template<Backends backend>
Layer< GridType, Layers::level,
backend >::type level (const int lvl=0) const
template<Backends backend>
Layer< GridType, Layers::leaf,
backend >::type leaf () const
template<Layers lr, Backends backend>
Layer< GridType, lr, backend >
::type layer (const int lvl=0) const
template<Layers lr>
Layer< GridType, lr,
Backends::part >::type layer (const int lvl=0)
LevelGridViewType level_view (const int lvl) const
LeafGridViewType leaf_view () const
void visualize (const std::string filename=static_id(), const Common::Configuration &boundary_info_cfg=Common::Configuration()) const
void visualize (const Common::Configuration &boundary_info_cfg) const
void visualize (const Common::Configuration &boundary_info_cfg, const std::string filename) const
void global_refine (size_t count)
Static Public Member Functions
static const std::string static_id ()
Static Public Attributes
static const size_t dimDomain = GridImp::dimension
Member Typedef Documentation
template<class GridImp > typedef GridType::ctype Dune::XT::Grid::GridProvider< GridImp >::DomainFieldType
template<class GridImp > typedef FieldVector<DomainFieldType, dimDomain> Dune::XT::Grid::GridProvider< GridImp >::DomainType
template<class GridImp > typedef GridType::template Codim<0>::Entity Dune::XT::Grid::GridProvider< GridImp >::EntityType
template<class GridImp > typedef GridImp Dune::XT::Grid::GridProvider< GridImp >::GridType
template<class GridImp > typedef Layer<GridType, Layers::leaf, Backends::view>::type Dune::XT::Grid::GridProvider< GridImp >::LeafGridViewType
template<class GridImp > typedef Layer<GridType, Layers::level, Backends::view>::type Dune::XT::Grid::GridProvider< GridImp >::LevelGridViewType
template<class GridImp > typedef GridProvider<GridImp> Dune::XT::Grid::GridProvider< GridImp >::ThisType
Constructor & Destructor Documentation
template<class GridImp > Dune::XT::Grid::GridProvider< GridImp >::GridProvider (GridType * grd_ptr) inline
Attention
Do not delete grd_ptr manually afterwards!
template<class GridImp > Dune::XT::Grid::GridProvider< GridImp >::GridProvider (std::unique_ptr< GridType > && grd_ptr) inline
template<class GridImp > Dune::XT::Grid::GridProvider< GridImp >::GridProvider (std::shared_ptr< GridType > grd_ptr) inline
template<class GridImp > Dune::XT::Grid::GridProvider< GridImp >::GridProvider (const ThisType & other) default
template<class GridImp > Dune::XT::Grid::GridProvider< GridImp >::GridProvider (ThisType && source) default
Member Function Documentation
template<class GridImp > void Dune::XT::Grid::GridProvider< GridImp >::global_refine (size_t count) inline
References Dune::XT::Grid::GridProvider< GridImp >::grid().
template<class GridImp > const GridType& Dune::XT::Grid::GridProvider< GridImp >::grid () const inline
Referenced by Dune::XT::Grid::GridProvider< GridImp >::global_refine().
template<class GridImp > GridType& Dune::XT::Grid::GridProvider< GridImp >::grid () inline
template<class GridImp > const std::shared_ptr<GridType>& Dune::XT::Grid::GridProvider< GridImp >::grid_ptr () const inline
template<class GridImp > std::shared_ptr<GridType> Dune::XT::Grid::GridProvider< GridImp >::grid_ptr () inline
template<class GridImp > template<Layers lr, Backends backend> Layer<GridType, lr, backend>::type Dune::XT::Grid::GridProvider< GridImp >::layer (const int lvl = 0) const inline
References Dune::XT::Grid::Layer< GridType, layer, backend >::create().
template<class GridImp > template<Layers lr> Layer<GridType, lr, Backends::part>::type Dune::XT::Grid::GridProvider< GridImp >::layer (const int lvl = 0) inline
References Dune::XT::Grid::Layer< GridType, layer, backend >::create().
template<class GridImp > template<Backends backend> Layer<GridType, Layers::leaf, backend>::type Dune::XT::Grid::GridProvider< GridImp >::leaf () const inline
References Dune::XT::Grid::Layer< GridType, layer, backend >::create().
template<class GridImp > LeafGridViewType Dune::XT::Grid::GridProvider< GridImp >::leaf_view () const inline
References Dune::XT::Grid::Layer< GridType, layer, backend >::create().
template<class GridImp > template<Backends backend> Layer<GridType, Layers::level, backend>::type Dune::XT::Grid::GridProvider< GridImp >::level (const int lvl = 0) const inline
References Dune::XT::Grid::Layer< GridType, layer, backend >::create().
template<class GridImp > LevelGridViewType Dune::XT::Grid::GridProvider< GridImp >::level_view (const int lvl) const inline
References Dune::XT::Grid::Layer< GridType, layer, backend >::create().
Referenced by Dune::XT::Grid::EOCGridProvider< GridImp >::reference_grid_view().
template<class GridImp > int Dune::XT::Grid::GridProvider< GridImp >::max_level () const inline
template<class GridImp > ThisType& Dune::XT::Grid::GridProvider< GridImp >::operator= (const ThisType & other) delete
template<class GridImp > ThisType& Dune::XT::Grid::GridProvider< GridImp >::operator= (ThisType && source) delete
template<class GridImp > static const std::string Dune::XT::Grid::GridProvider< GridImp >::static_id () inline static
Referenced by Dune::XT::Grid::GridProvider< GridImp >::visualize().
template<class GridImp > void Dune::XT::Grid::GridProvider< GridImp >::visualize (const std::string filename = static_id(), const Common::Configuration & boundary_info_cfg = Common::Configuration()) const inline
template<class GridImp > void Dune::XT::Grid::GridProvider< GridImp >::visualize (const Common::Configuration & boundary_info_cfg) const inline
References Dune::XT::Grid::GridProvider< GridImp >::static_id().
template<class GridImp > void Dune::XT::Grid::GridProvider< GridImp >::visualize (const Common::Configuration & boundary_info_cfg, const std::string filename) const inline
Member Data Documentation
template<class GridImp > const size_t Dune::XT::Grid::GridProvider< GridImp >::dimDomain = GridImp::dimension static
The documentation for this class was generated from the following file:
provider.hh