Dune::XT::Common::FallbackPerThreadValue< ValueImp > Class Template Reference
Dune::XT::Common::FallbackPerThreadValue< ValueImp > Class Template Reference
#include <dune/xt/common/parallel/threadstorage.hh>
Public Types
typedef ValueImp ValueType
typedef std::conditional
< std::is_const< ValueImp >
::value, ValueImp, const
ValueImp >::type ConstValueType
Public Member Functions
FallbackPerThreadValue (ConstValueType &value)
Initialization by copy construction of ValueType.
template<class... InitTypes>
FallbackPerThreadValue (InitTypes &&...ctor_args)
Initialization by in-place construction ValueType with.
ThisType & operator= (ConstValueType &&value)
operator ValueType () const
ValueType & operator* ()
ConstValueType & operator* () const
ValueType * operator-> ()
ConstValueType * operator-> () const
template<class BinaryOperation >
ValueType accumulate (ValueType init, BinaryOperation op) const
ValueType sum () const
Detailed Description
template<class ValueImp>
class Dune::XT::Common::FallbackPerThreadValue< ValueImp >
Automatic Storage of non-static, N thread-local values
Member Typedef Documentation
template<class ValueImp > typedef std::conditional<std::is_const<ValueImp>::value, ValueImp, const ValueImp>::type Dune::XT::Common::FallbackPerThreadValue< ValueImp >::ConstValueType
template<class ValueImp > typedef ValueImp Dune::XT::Common::FallbackPerThreadValue< ValueImp >::ValueType
Constructor & Destructor Documentation
template<class ValueImp > Dune::XT::Common::FallbackPerThreadValue< ValueImp >::FallbackPerThreadValue (ConstValueType & value) inline explicit
Initialization by copy construction of ValueType.
template<class ValueImp > template<class... InitTypes> Dune::XT::Common::FallbackPerThreadValue< ValueImp >::FallbackPerThreadValue (InitTypes &&... ctor_args) inline explicit
Initialization by in-place construction ValueType with.
Parameters
ctor_args
Member Function Documentation
template<class ValueImp > template<class BinaryOperation > ValueType Dune::XT::Common::FallbackPerThreadValue< ValueImp >::accumulate (ValueType init, BinaryOperation op) const inline
Referenced by Dune::XT::Common::FallbackPerThreadValue< ValueImp >::sum().
template<class ValueImp > Dune::XT::Common::FallbackPerThreadValue< ValueImp >::operator ValueType () const inline
References Dune::XT::Common::FallbackPerThreadValue< ValueImp >::operator*().
template<class ValueImp > ValueType& Dune::XT::Common::FallbackPerThreadValue< ValueImp >::operator* () inline
References Dune::XT::Common::ThreadManager::thread(), and Dune::XT::Common::threadManager().
Referenced by Dune::XT::Common::FallbackPerThreadValue< ValueImp >::operator ValueType().
template<class ValueImp > ConstValueType& Dune::XT::Common::FallbackPerThreadValue< ValueImp >::operator* () const inline
References Dune::XT::Common::ThreadManager::thread(), and Dune::XT::Common::threadManager().
template<class ValueImp > ValueType* Dune::XT::Common::FallbackPerThreadValue< ValueImp >::operator-> () inline
References Dune::XT::Common::ThreadManager::thread(), and Dune::XT::Common::threadManager().
template<class ValueImp > ConstValueType* Dune::XT::Common::FallbackPerThreadValue< ValueImp >::operator-> () const inline
References Dune::XT::Common::ThreadManager::thread(), and Dune::XT::Common::threadManager().
template<class ValueImp > ThisType& Dune::XT::Common::FallbackPerThreadValue< ValueImp >::operator= (ConstValueType && value) inline
template<class ValueImp > ValueType Dune::XT::Common::FallbackPerThreadValue< ValueImp >::sum () const inline
References Dune::XT::Common::FallbackPerThreadValue< ValueImp >::accumulate().
The documentation for this class was generated from the following file:
threadstorage.hh