Dune::XT::Common::MinMaxAvg< ElementType > Class Template Reference
Dune::XT::Common::MinMaxAvg< ElementType > Class Template Reference
a vector wrapper for continiously updating min,max,avg of some element type vector
#include <dune/xt/common/math.hh>
Public Member Functions
MinMaxAvg ()
template<class stl_container_type >
MinMaxAvg (const stl_container_type &elements)
std::size_t count () const
ElementType sum () const
ElementType min () const
ElementType max () const
ElementType average () const
void operator() (const ElementType &el)
void output (std::ostream &stream)
Protected Types
typedef MinMaxAvg< ElementType > ThisType
typedef
boost::accumulators::stats
< boost::accumulators::tag::max,
boost::accumulators::tag::min,
boost::accumulators::tag::mean,
boost::accumulators::tag::count,
boost::accumulators::tag::sum > StatsType
Protected Attributes
boost::accumulators::accumulator_set
< ElementType, StatsType > acc_
Detailed Description
template<class ElementType>
class Dune::XT::Common::MinMaxAvg< ElementType >
a vector wrapper for continiously updating min,max,avg of some element type vector
Member Typedef Documentation
template<class ElementType > typedef boost::accumulators::stats<boost::accumulators::tag::max, boost::accumulators::tag::min, boost::accumulators::tag::mean, boost::accumulators::tag::count, boost::accumulators::tag::sum> Dune::XT::Common::MinMaxAvg< ElementType >::StatsType protected
template<class ElementType > typedef MinMaxAvg<ElementType> Dune::XT::Common::MinMaxAvg< ElementType >::ThisType protected
Constructor & Destructor Documentation
template<class ElementType > Dune::XT::Common::MinMaxAvg< ElementType >::MinMaxAvg () inline
template<class ElementType > template<class stl_container_type > Dune::XT::Common::MinMaxAvg< ElementType >::MinMaxAvg (const stl_container_type & elements) inline
References Dune::XT::Common::MinMaxAvg< ElementType >::acc_.
Member Function Documentation
template<class ElementType > ElementType Dune::XT::Common::MinMaxAvg< ElementType >::average () const inline
References Dune::XT::Common::MinMaxAvg< ElementType >::acc_.
Referenced by Dune::XT::Common::MinMaxAvg< ElementType >::output().
template<class ElementType > std::size_t Dune::XT::Common::MinMaxAvg< ElementType >::count () const inline
References Dune::XT::Common::MinMaxAvg< ElementType >::acc_.
template<class ElementType > ElementType Dune::XT::Common::MinMaxAvg< ElementType >::max () const inline
References Dune::XT::Common::MinMaxAvg< ElementType >::acc_.
Referenced by Dune::XT::Common::MinMaxAvg< ElementType >::output().
template<class ElementType > ElementType Dune::XT::Common::MinMaxAvg< ElementType >::min () const inline
References Dune::XT::Common::MinMaxAvg< ElementType >::acc_.
Referenced by Dune::XT::Common::MinMaxAvg< ElementType >::output().
template<class ElementType > void Dune::XT::Common::MinMaxAvg< ElementType >::operator() (const ElementType & el) inline
References Dune::XT::Common::MinMaxAvg< ElementType >::acc_.
template<class ElementType > void Dune::XT::Common::MinMaxAvg< ElementType >::output (std::ostream & stream) inline
References Dune::XT::Common::MinMaxAvg< ElementType >::average(), Dune::XT::Common::MinMaxAvg< ElementType >::max(), and Dune::XT::Common::MinMaxAvg< ElementType >::min().
template<class ElementType > ElementType Dune::XT::Common::MinMaxAvg< ElementType >::sum () const inline
References Dune::XT::Common::MinMaxAvg< ElementType >::acc_.
Member Data Documentation
template<class ElementType > boost::accumulators::accumulator_set<ElementType, StatsType> Dune::XT::Common::MinMaxAvg< ElementType >::acc_ protected
Referenced by Dune::XT::Common::MinMaxAvg< ElementType >::average(), Dune::XT::Common::MinMaxAvg< ElementType >::count(), Dune::XT::Common::MinMaxAvg< ElementType >::max(), Dune::XT::Common::MinMaxAvg< ElementType >::min(), Dune::XT::Common::MinMaxAvg< ElementType >::MinMaxAvg(), Dune::XT::Common::MinMaxAvg< ElementType >::operator()(), and Dune::XT::Common::MinMaxAvg< ElementType >::sum().
The documentation for this class was generated from the following file:
math.hh