Dune::XT::Common::FixedMap< key_imp, T, nin > Class Template Reference
Dune::XT::Common::FixedMap< key_imp, T, nin > Class Template Reference
a std::map like container that prevents map size change
#include <dune/xt/common/fixed_map.hh>
Public Types
typedef std::pair< key_imp, T > value_type
typedef key_imp key_type
typedef T mapped_type
typedef FixedMapIterator
< ThisType > iterator
typedef ConstFixedMapIterator
< ThisType > const_iterator
Public Member Functions
FixedMap ()
FixedMap (const std::initializer_list< value_type > &list)
FixedMap (const MapType &map)
std::size_t get_idx (const key_type &key) const
const mapped_type & operator[] (const key_type &key) const
mapped_type & operator[] (const key_type &key)
const_iterator find (const key_type &key) const
iterator find (const key_type &key)
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
std::size_t size () const
void print (std::ostream &out) const
Static Public Attributes
static const std::size_t N = nin
Detailed Description
template<class key_imp, class T, std::size_t nin>
class Dune::XT::Common::FixedMap< key_imp, T, nin >
a std::map like container that prevents map size change
Member Typedef Documentation
template<class key_imp , class T , std::size_t nin> typedef ConstFixedMapIterator<ThisType> Dune::XT::Common::FixedMap< key_imp, T, nin >::const_iterator
template<class key_imp , class T , std::size_t nin> typedef FixedMapIterator<ThisType> Dune::XT::Common::FixedMap< key_imp, T, nin >::iterator
template<class key_imp , class T , std::size_t nin> typedef key_imp Dune::XT::Common::FixedMap< key_imp, T, nin >::key_type
template<class key_imp , class T , std::size_t nin> typedef T Dune::XT::Common::FixedMap< key_imp, T, nin >::mapped_type
template<class key_imp , class T , std::size_t nin> typedef std::pair<key_imp, T> Dune::XT::Common::FixedMap< key_imp, T, nin >::value_type
Constructor & Destructor Documentation
template<class key_imp , class T , std::size_t nin> Dune::XT::Common::FixedMap< key_imp, T, nin >::FixedMap () inline
template<class key_imp , class T , std::size_t nin> Dune::XT::Common::FixedMap< key_imp, T, nin >::FixedMap (const std::initializer_list< value_type > & list) inline
inserts key-value value pairs from initializer list if list.size() > N only the first N elements are considered if list.size() < N the Map is padded with default constructed elements
template<class key_imp , class T , std::size_t nin> Dune::XT::Common::FixedMap< key_imp, T, nin >::FixedMap (const MapType & map) inline
Member Function Documentation
template<class key_imp , class T , std::size_t nin> iterator Dune::XT::Common::FixedMap< key_imp, T, nin >::begin () inline
template<class key_imp , class T , std::size_t nin> const_iterator Dune::XT::Common::FixedMap< key_imp, T, nin >::begin () const inline
template<class key_imp , class T , std::size_t nin> iterator Dune::XT::Common::FixedMap< key_imp, T, nin >::end () inline
References Dune::XT::Common::FixedMap< key_imp, T, nin >::N.
template<class key_imp , class T , std::size_t nin> const_iterator Dune::XT::Common::FixedMap< key_imp, T, nin >::end () const inline
References Dune::XT::Common::FixedMap< key_imp, T, nin >::N.
template<class key_imp , class T , std::size_t nin> const_iterator Dune::XT::Common::FixedMap< key_imp, T, nin >::find (const key_type & key) const inline
References Dune::XT::Common::FixedMap< key_imp, T, nin >::get_idx().
template<class key_imp , class T , std::size_t nin> iterator Dune::XT::Common::FixedMap< key_imp, T, nin >::find (const key_type & key) inline
References Dune::XT::Common::FixedMap< key_imp, T, nin >::get_idx().
template<class key_imp , class T , std::size_t nin> std::size_t Dune::XT::Common::FixedMap< key_imp, T, nin >::get_idx (const key_type & key) const inline
References Dune::XT::Common::FixedMap< key_imp, T, nin >::N.
Referenced by Dune::XT::Common::FixedMap< key_imp, T, nin >::find(), and Dune::XT::Common::FixedMap< key_imp, T, nin >::operator[]().
template<class key_imp , class T , std::size_t nin> const mapped_type& Dune::XT::Common::FixedMap< key_imp, T, nin >::operator[] (const key_type & key) const inline
References DUNE_THROW, Dune::XT::Common::FixedMap< key_imp, T, nin >::get_idx(), and Dune::XT::Common::FixedMap< key_imp, T, nin >::N.
template<class key_imp , class T , std::size_t nin> mapped_type& Dune::XT::Common::FixedMap< key_imp, T, nin >::operator[] (const key_type & key) inline
References DUNE_THROW, Dune::XT::Common::FixedMap< key_imp, T, nin >::get_idx(), and Dune::XT::Common::FixedMap< key_imp, T, nin >::N.
template<class key_imp , class T , std::size_t nin> void Dune::XT::Common::FixedMap< key_imp, T, nin >::print (std::ostream & out) const inline
template<class key_imp , class T , std::size_t nin> std::size_t Dune::XT::Common::FixedMap< key_imp, T, nin >::size () const inline
References Dune::XT::Common::FixedMap< key_imp, T, nin >::N.
Member Data Documentation
template<class key_imp , class T , std::size_t nin> const std::size_t Dune::XT::Common::FixedMap< K, T, nin >::N = nin static
Referenced by Dune::XT::Common::FixedMap< key_imp, T, nin >::end(), Dune::XT::Common::FixedMap< key_imp, T, nin >::get_idx(), Dune::XT::Common::FixedMap< key_imp, T, nin >::operator[](), and Dune::XT::Common::FixedMap< key_imp, T, nin >::size().
The documentation for this class was generated from the following file:
fixed_map.hh