Dune::XT::Common::LogStream Class Reference
Dune::XT::Common::LogStream Class Reference
#include <dune/xt/common/logstreams.hh>
Public Types
typedef
SuspendableStrBuffer::PriorityType PriorityType
Public Member Functions
LogStream (SuspendableStrBuffer *&&buffer)
virtual ~LogStream ()
virtual LogStream & flush ()
dump buffer into file/stream and clear it
void suspend (PriorityType priority=default_suspend_priority)
forwards suspend to buffer the suspend_priority_ mechanism provides a way to silence streams from 'higher' modules no-op if already suspended
void resume (PriorityType priority=default_suspend_priority)
start accepting input into the buffer again no-op if not suspended
Static Public Attributes
static const PriorityType default_suspend_priority = SuspendableStrBuffer::default_suspend_priority
Member Typedef Documentation
typedef SuspendableStrBuffer::PriorityType Dune::XT::Common::LogStream::PriorityType
Constructor & Destructor Documentation
Dune::XT::Common::LogStream::LogStream (SuspendableStrBuffer *&& buffer) inline explicit
virtual Dune::XT::Common::LogStream::~LogStream () inline virtual
References flush().
Member Function Documentation
LogStream & Dune::XT::Common::LogStream::flush () virtual
dump buffer into file/stream and clear it
Referenced by ~LogStream().
void Dune::XT::Common::LogStream::resume (PriorityType priority = default_suspend_priority) inline
start accepting input into the buffer again no-op if not suspended
Referenced by Dune::XT::Common::meminfo().
void Dune::XT::Common::LogStream::suspend (PriorityType priority = default_suspend_priority) inline
forwards suspend to buffer the suspend_priority_ mechanism provides a way to silence streams from 'higher' modules no-op if already suspended
Member Data Documentation
const PriorityType Dune::XT::Common::LogStream::default_suspend_priority = SuspendableStrBuffer::default_suspend_priority static
The documentation for this class was generated from the following files:
logstreams.hh
logstreams.cc