Dune::XT::Common::FloatCmp::internal::Call< FirstType, SecondType, ToleranceType, style > Struct Template Reference
Dune::XT::Common::FloatCmp::internal::Call< FirstType, SecondType, ToleranceType, style > Struct Template Reference
#include <dune/xt/common/float_cmp_internal.hh>
Static Public Member Functions
static bool eq (const FirstType &first, const SecondType &second, const ToleranceType &rtol, const ToleranceType &)
static bool ne (const FirstType &first, const SecondType &second, const ToleranceType &rtol, const ToleranceType &)
static bool gt (const FirstType &first, const SecondType &second, const ToleranceType &rtol, const ToleranceType &)
static bool lt (const FirstType &first, const SecondType &second, const ToleranceType &rtol, const ToleranceType &)
static bool ge (const FirstType &first, const SecondType &second, const ToleranceType &rtol, const ToleranceType &)
static bool le (const FirstType &first, const SecondType &second, const ToleranceType &rtol, const ToleranceType &)
Member Function Documentation
template<class FirstType , class SecondType , class ToleranceType , Style style> static bool Dune::XT::Common::FloatCmp::internal::Call< FirstType, SecondType, ToleranceType, style >::eq (const FirstType & first, const SecondType & second, const ToleranceType & rtol, const ToleranceType &) inline static
template<class FirstType , class SecondType , class ToleranceType , Style style> static bool Dune::XT::Common::FloatCmp::internal::Call< FirstType, SecondType, ToleranceType, style >::ge (const FirstType & first, const SecondType & second, const ToleranceType & rtol, const ToleranceType &) inline static
References Dune::XT::Common::FloatCmp::internal::cmp_gt().
template<class FirstType , class SecondType , class ToleranceType , Style style> static bool Dune::XT::Common::FloatCmp::internal::Call< FirstType, SecondType, ToleranceType, style >::gt (const FirstType & first, const SecondType & second, const ToleranceType & rtol, const ToleranceType &) inline static
References Dune::XT::Common::FloatCmp::internal::cmp_gt().
template<class FirstType , class SecondType , class ToleranceType , Style style> static bool Dune::XT::Common::FloatCmp::internal::Call< FirstType, SecondType, ToleranceType, style >::le (const FirstType & first, const SecondType & second, const ToleranceType & rtol, const ToleranceType &) inline static
References Dune::XT::Common::FloatCmp::internal::cmp_lt().
template<class FirstType , class SecondType , class ToleranceType , Style style> static bool Dune::XT::Common::FloatCmp::internal::Call< FirstType, SecondType, ToleranceType, style >::lt (const FirstType & first, const SecondType & second, const ToleranceType & rtol, const ToleranceType &) inline static
References Dune::XT::Common::FloatCmp::internal::cmp_lt().
template<class FirstType , class SecondType , class ToleranceType , Style style> static bool Dune::XT::Common::FloatCmp::internal::Call< FirstType, SecondType, ToleranceType, style >::ne (const FirstType & first, const SecondType & second, const ToleranceType & rtol, const ToleranceType &) inline static
The documentation for this struct was generated from the following file:
float_cmp_internal.hh