Dune::XT::Common::LocalizationStudy Class Reference
Dune::XT::Common::LocalizationStudy Class Reference abstract
#include <dune/xt/common/localization-study.hh>
Public Member Functions
LocalizationStudy (const std::vector< std::string > only_these_indicators={})
virtual ~LocalizationStudy ()
virtual std::string identifier () const =0
virtual DynamicVector< double > compute_reference_indicators () const =0
virtual std::vector< std::string > provided_indicators () const =0
virtual DynamicVector< double > compute_indicators (const std::string type) const =0
std::vector< std::string > used_indicators () const
void run (std::ostream &out=std::cout)
Constructor & Destructor Documentation
Dune::XT::Common::LocalizationStudy::LocalizationStudy (const std::vector< std::string > only_these_indicators = {})
Dune::XT::Common::LocalizationStudy::~LocalizationStudy () virtual
Member Function Documentation
virtual DynamicVector<double> Dune::XT::Common::LocalizationStudy::compute_indicators (const std::string type) const pure virtual
Referenced by run().
virtual DynamicVector<double> Dune::XT::Common::LocalizationStudy::compute_reference_indicators () const pure virtual
Referenced by run().
virtual std::string Dune::XT::Common::LocalizationStudy::identifier () const pure virtual
Referenced by run().
virtual std::vector<std::string> Dune::XT::Common::LocalizationStudy::provided_indicators () const pure virtual
Referenced by run(), and used_indicators().
void Dune::XT::Common::LocalizationStudy::run (std::ostream & out = std::cout)
References compute_indicators(), compute_reference_indicators(), DUNE_THROW, identifier(), provided_indicators(), used_indicators(), and Dune::XT::Common::whitespaceify().
std::vector< std::string > Dune::XT::Common::LocalizationStudy::used_indicators () const
References provided_indicators().
Referenced by run().
The documentation for this class was generated from the following files:
localization-study.hh
localization-study.cc