Dune::XT::Common::Logging Class Reference
Dune::XT::Common::Logging Class Reference
handles all logging
#include <dune/xt/common/logging.hh>
Classes
struct ResumeLocal
struct SuspendLocal
Public Member Functions
~Logging ()
void create (int logflags=(LOG_FILE|LOG_CONSOLE|LOG_ERROR), const std::string logfile="dune_xt_common_log", const std::string datadir="data", const std::string _logdir=std::string("log"))
setup loglevel, logfilename
void set_prefix (std::string prefix)
void set_stream_flags (int streamID, int flags)
int get_stream_flags (int streamID) const
LogStream & get_stream (int streamId)
LogStream & error ()
LogStream & info ()
LogStream & debug ()
LogStream & devnull ()
void flush ()
flush all active streams
int add_stream (int flags)
creates a new LogStream with given id
void resume (LogStream::PriorityType prio=LogStream::default_suspend_priority)
re-enable all logging below given priority level
void suspend (LogStream::PriorityType prio=LogStream::default_suspend_priority)
(temporarily) disable all logging below given priority level
forwarded Log functions
template<class T >
void log (T c, int streamID)
Friends
Logging & Logger ()
global Logging instance
Detailed Description
handles all logging
Constructor & Destructor Documentation
Dune::XT::Common::Logging::~Logging ()
Member Function Documentation
int Dune::XT::Common::Logging::add_stream (int flags)
creates a new LogStream with given id
References Dune::XT::Common::LOG_NEXT.
void Dune::XT::Common::Logging::create (int logflags = (LOG_FILE | LOG_CONSOLE | LOG_ERROR), const std::string logfile = "dune_xt_common_log", const std::string datadir = "data", const std::string _logdir = std::string("log"))
setup loglevel, logfilename
Parameters
logflags any OR'd combination of flags
logfile filename for log, can contain paths, but creation will fail if dir is non-existant
References Dune::XT::Common::logflags_(), and Dune::XT::Common::test_create_directory().
Referenced by set_prefix().
LogStream& Dune::XT::Common::Logging::debug () inline
LogStream& Dune::XT::Common::Logging::devnull () inline
LogStream& Dune::XT::Common::Logging::error () inline
void Dune::XT::Common::Logging::flush ()
flush all active streams
Referenced by set_stream_flags().
LogStream & Dune::XT::Common::Logging::get_stream (int streamId)
References DUNE_THROW.
Referenced by log().
int Dune::XT::Common::Logging::get_stream_flags (int streamID) const
References DUNE_THROW.
LogStream& Dune::XT::Common::Logging::info () inline
template<class T > void Dune::XT::Common::Logging::log (T c, int streamID) inline
References get_stream().
void Dune::XT::Common::Logging::resume (LogStream::PriorityType prio = LogStream::default_suspend_priority)
re-enable all logging below given priority level
Referenced by Dune::XT::Common::Logging::ResumeLocal::ResumeLocal(), and Dune::XT::Common::Logging::SuspendLocal::~SuspendLocal().
void Dune::XT::Common::Logging::set_prefix (std::string prefix)
Attention
This will probably not do wht we want it to!
References create().
void Dune::XT::Common::Logging::set_stream_flags (int streamID, int flags)
References flush().
void Dune::XT::Common::Logging::suspend (LogStream::PriorityType prio = LogStream::default_suspend_priority)
(temporarily) disable all logging below given priority level
Referenced by Dune::XT::Common::Logging::SuspendLocal::SuspendLocal(), and Dune::XT::Common::Logging::ResumeLocal::~ResumeLocal().
Friends And Related Function Documentation
Logging& Logger () friend
global Logging instance
Referenced by Dune::XT::Common::Logging::ResumeLocal::ResumeLocal(), Dune::XT::Common::Logging::SuspendLocal::SuspendLocal(), Dune::XT::Common::Logging::ResumeLocal::~ResumeLocal(), and Dune::XT::Common::Logging::SuspendLocal::~SuspendLocal().
The documentation for this class was generated from the following files:
logging.hh
logging.cc