Dune::XT::Common::ConvergenceStudy Class Reference
Dune::XT::Common::ConvergenceStudy Class Reference abstract
#include <dune/xt/common/convergence-study.hh>
Public Member Functions
ConvergenceStudy (const std::vector< std::string > only_these_norms={})
virtual ~ConvergenceStudy ()
virtual std::string identifier () const =0
virtual size_t num_refinements () const =0
virtual std::vector< std::string > provided_norms () const =0
virtual size_t expected_rate (const std::string type) const =0
virtual double norm_reference_solution (const std::string type)=0
virtual size_t current_grid_size () const =0
virtual double current_grid_width () const =0
virtual double compute_on_current_refinement ()=0
virtual double current_error_norm (const std::string type)=0
virtual void refine ()=0
std::vector< std::string > used_norms () const
std::map< std::string,
std::vector< double > > run (const bool relative=false, std::ostream &out=DXTC_LOG_INFO_0, const bool print_timings=true)
virtual std::vector< double > expected_results (const std::string) const
Constructor & Destructor Documentation
Dune::XT::Common::ConvergenceStudy::ConvergenceStudy (const std::vector< std::string > only_these_norms = {})
virtual Dune::XT::Common::ConvergenceStudy::~ConvergenceStudy () inline virtual
Member Function Documentation
virtual double Dune::XT::Common::ConvergenceStudy::compute_on_current_refinement () pure virtual
Returns
The time it took to solve on this refinement.
Referenced by run().
virtual double Dune::XT::Common::ConvergenceStudy::current_error_norm (const std::string type) pure virtual
Referenced by run().
virtual size_t Dune::XT::Common::ConvergenceStudy::current_grid_size () const pure virtual
Referenced by run().
virtual double Dune::XT::Common::ConvergenceStudy::current_grid_width () const pure virtual
Referenced by run().
virtual size_t Dune::XT::Common::ConvergenceStudy::expected_rate (const std::string type) const pure virtual
Referenced by run().
std::vector< double > Dune::XT::Common::ConvergenceStudy::expected_results (const std::string) const virtual
References DUNE_THROW.
virtual std::string Dune::XT::Common::ConvergenceStudy::identifier () const pure virtual
Referenced by run().
virtual double Dune::XT::Common::ConvergenceStudy::norm_reference_solution (const std::string type) pure virtual
Referenced by run().
virtual size_t Dune::XT::Common::ConvergenceStudy::num_refinements () const pure virtual
Referenced by run().
virtual std::vector<std::string> Dune::XT::Common::ConvergenceStudy::provided_norms () const pure virtual
Referenced by run(), and used_norms().
virtual void Dune::XT::Common::ConvergenceStudy::refine () pure virtual
Referenced by run().
std::map< std::string, std::vector< double > > Dune::XT::Common::ConvergenceStudy::run (const bool relative = false, std::ostream & out = DXTC_LOG_INFO_0, const bool print_timings = true)
References Dune::XT::Common::Colors::brown, Dune::XT::Common::color_string(), compute_on_current_refinement(), current_error_norm(), current_grid_size(), current_grid_width(), DUNE_THROW, expected_rate(), Dune::XT::Common::Colors::green, identifier(), norm_reference_solution(), num_refinements(), provided_norms(), Dune::XT::Common::Colors::red, refine(), used_norms(), and Dune::XT::Common::whitespaceify().
std::vector< std::string > Dune::XT::Common::ConvergenceStudy::used_norms () const
References provided_norms().
Referenced by run().
The documentation for this class was generated from the following files:
convergence-study.hh
convergence-study.cc