Dune::XT::Common::ValidatorInterface< T, Derived > Class Template Reference
Dune::XT::Common::ValidatorInterface< T, Derived > Class Template Reference
Base class for all Validators the idea is from dune-fem, only our class is an actual interface.
#include <dune/xt/common/validation.hh>
Public Member Functions
bool operator() (const T &value) const
std::string msg () const
void print (std::ostream &out) const
Protected Member Functions
const Derived & as_imp () const
Derived & as_imp ()
Detailed Description
template<class T, class Derived>
class Dune::XT::Common::ValidatorInterface< T, Derived >
Base class for all Validators the idea is from dune-fem, only our class is an actual interface.
Member Function Documentation
template<class T, class Derived> const Derived& Dune::XT::Common::ValidatorInterface< T, Derived >::as_imp () const inline protected
Referenced by Dune::XT::Common::ValidatorInterface< T, ValidateInList< T, ListImp > >::msg(), Dune::XT::Common::ValidatorInterface< T, ValidateInList< T, ListImp > >::operator()(), and Dune::XT::Common::ValidatorInterface< T, ValidateInList< T, ListImp > >::print().
template<class T, class Derived> Derived& Dune::XT::Common::ValidatorInterface< T, Derived >::as_imp () inline protected
template<class T, class Derived> std::string Dune::XT::Common::ValidatorInterface< T, Derived >::msg () const inline
template<class T, class Derived> bool Dune::XT::Common::ValidatorInterface< T, Derived >::operator() (const T & value) const inline
template<class T, class Derived> void Dune::XT::Common::ValidatorInterface< T, Derived >::print (std::ostream & out) const inline
The documentation for this class was generated from the following file:
validation.hh