Dune::XT::Common::ThreadManager Struct Reference
Dune::XT::Common::ThreadManager Struct Reference
#include <dune/xt/common/parallel/threadmanager.hh>
Public Member Functions
size_t max_threads ()
return maximal number of threads possbile in the current run
size_t current_threads ()
return number of current threads
size_t thread ()
return thread number
void set_max_threads (const size_t count)
set maximal number of threads available during run
~ThreadManager ()=default
Static Public Member Functions
static size_t default_max_threads ()
Friends
ThreadManager & threadManager ()
global singleton ThreadManager
Detailed Description
abstractions of threading functionality currently controls tbb and forwards to dune-fem if possible, falls back to single-thread dummy imp
Constructor & Destructor Documentation
Dune::XT::Common::ThreadManager::~ThreadManager () default
Member Function Documentation
size_t Dune::XT::Common::ThreadManager::current_threads ()
return number of current threads
size_t Dune::XT::Common::ThreadManager::default_max_threads () static
size_t Dune::XT::Common::ThreadManager::max_threads ()
return maximal number of threads possbile in the current run
Referenced by Dune::XT::Common::Timings::output_all_measures().
void Dune::XT::Common::ThreadManager::set_max_threads (const size_t count)
set maximal number of threads available during run
References DUNE_THROW.
size_t Dune::XT::Common::ThreadManager::thread ()
return thread number
Referenced by Dune::XT::Common::FallbackPerThreadValue< ValueImp >::operator*(), and Dune::XT::Common::FallbackPerThreadValue< ValueImp >::operator->().
Friends And Related Function Documentation
ThreadManager& threadManager () friend
global singleton ThreadManager
The documentation for this struct was generated from the following files:
threadmanager.hh
threadmanager.cc