Dune::XT::Common::ScopedTiming Class Reference
Dune::XT::Common::ScopedTiming Class Reference
#include <dune/xt/common/timings.hh>
Public Member Functions
ScopedTiming (const std::string &section_name)
~ScopedTiming ()
Protected Attributes
const std::string section_name_
Constructor & Destructor Documentation
Dune::XT::Common::ScopedTiming::ScopedTiming (const std::string & section_name) inline
References section_name_, Dune::XT::Common::Timings::start(), and Dune::XT::Common::timings().
Dune::XT::Common::ScopedTiming::~ScopedTiming () inline
References section_name_, Dune::XT::Common::Timings::stop(), and Dune::XT::Common::timings().
Member Data Documentation
const std::string Dune::XT::Common::ScopedTiming::section_name_ protected
Referenced by ScopedTiming(), Dune::XT::Common::OutputScopedTiming::~OutputScopedTiming(), and ~ScopedTiming().
The documentation for this class was generated from the following file:
timings.hh