Dune::XT::Common::Timings Class Reference
Dune::XT::Common::Timings Class Reference
simple inline timing class
#include <dune/xt/common/timings.hh>
Public Member Functions
void stop ()
void start (const std::string section_name)
set this to begin a named section
long stop (const std::string section_name)
stop named section's counter
void reset (const std::string section_name)
set elapsed time back to 0 for section_name
TimingData::TimeType walltime (const std::string section_name) const
get runtime of section in milliseconds
TimingData::DeltaType delta (const std::string section_name) const
get the full delta array
void output_per_rank (const std::string csv_base) const
void output_simple (std::ostream &out=std::cout) const
outputs walltime only w/o MPI-rank averaging
void output_all_measures (std::ostream &out=std::cout, MPIHelper::MPICommunicator mpi_comm=Dune::MPIHelper::getCommunicator()) const
void reset ()
stops and resets all timers and data
void set_outputdir (const std::string dir)
Friends
Timings & timings ()
XT::Profiler global instance.
Detailed Description
simple inline timing class
User can set as many (even nested) named sections whose total (=system+user) time will be computed across all program instances.
Provides csv-conform output of process-averaged runtimes.
Member Function Documentation
TimingData::DeltaType Dune::XT::Common::Timings::delta (const std::string section_name) const
get the full delta array
References DUNE_THROW.
Referenced by stop(), and walltime().
void Dune::XT::Common::Timings::output_all_measures (std::ostream & out = std::cout, MPIHelper::MPICommunicator mpi_comm = Dune::MPIHelper::getCommunicator()) const
output all recorded measures
Note
outputs average, min, max over all MPI processes associated to mpi_comm
References Dune::XT::Common::ThreadManager::max_threads(), Dune::XT::Common::threadManager(), and timings.
Referenced by output_per_rank().
void Dune::XT::Common::Timings::output_per_rank (const std::string csv_base) const
creates one file local to each MPI-rank (no global averaging) one single rank-0 file with all combined/averaged measures
References output_all_measures().
void Dune::XT::Common::Timings::output_simple (std::ostream & out = std::cout) const
outputs walltime only w/o MPI-rank averaging
void Dune::XT::Common::Timings::reset (const std::string section_name)
set elapsed time back to 0 for section_name
References stop().
void Dune::XT::Common::Timings::reset ()
stops and resets all timers and data
References stop().
void Dune::XT::Common::Timings::set_outputdir (const std::string dir)
References Dune::XT::Common::test_create_directory().
void Dune::XT::Common::Timings::start (const std::string section_name)
set this to begin a named section
References DXTC_LIKWID_BEGIN_SECTION.
Referenced by Dune::XT::Common::ScopedTiming::ScopedTiming().
void Dune::XT::Common::Timings::stop ()
Referenced by reset(), Dune::XT::Common::OutputScopedTiming::~OutputScopedTiming(), and Dune::XT::Common::ScopedTiming::~ScopedTiming().
long Dune::XT::Common::Timings::stop (const std::string section_name)
stop named section's counter
References Dune::XT::Common::TimingData::delta(), delta(), DUNE_THROW, DXTC_LIKWID_END_SECTION, Dune::XT::Common::TimingData::stop(), and Dune::XT::Common::value_range().
TimingData::TimeType Dune::XT::Common::Timings::walltime (const std::string section_name) const
get runtime of section in milliseconds
References delta().
Friends And Related Function Documentation
Timings& timings () friend
XT::Profiler global instance.
global profiler object
Referenced by output_all_measures().
The documentation for this class was generated from the following files:
timings.hh
timings.cc