´´These methods allow to set key: value pairs.``
´´These methods allow to set key: value pairs.``
Functions
template<class T >
void Dune::XT::Common::Configuration::set (std::string key, const T &value, const bool overwrite=false)
set value to key in Configuration
void Dune::XT::Common::Configuration::set (const std::string &key, const char *value, const bool overwrite=false)
Detailed Description
Function Documentation
template<class T > void Dune::XT::Common::Configuration::set (std::string key, const T & value, const bool overwrite = false) inline
set value to key in Configuration
References DUNE_THROW, Dune::XT::Common::Configuration::has_key(), Dune::XT::Common::Configuration::report_string(), and Dune::XT::Common::to_string().
Referenced by Dune::XT::Common::Configuration::Configuration(), and Dune::XT::Common::Configuration::set().
void Dune::XT::Common::Configuration::set (const std::string & key, const char * value, const bool overwrite = false)
References Dune::XT::Common::Configuration::set().