´´These methods replace or override those from Dune::ParameterTree.``
´´These methods replace or override those from Dune::ParameterTree.``
Functions
bool Dune::XT::Common::Configuration::has_key (const std::string &key) const
check if key is existing in tree_
bool Dune::XT::Common::Configuration::has_sub (const std::string subTreeName) const
check if sub is existing in tree_
void Dune::XT::Common::Configuration::report (std::ostream &out=std::cout, const std::string &prefix="") const
print the ParameterTree
Configuration Dune::XT::Common::Configuration::sub (const std::string sub_id) const
Detailed Description
Function Documentation
bool Dune::XT::Common::Configuration::has_key (const std::string & key) const
check if key is existing in tree_
Referenced by Dune::XT::Common::Configuration::get(), and Dune::XT::Common::Configuration::set().
bool Dune::XT::Common::Configuration::has_sub (const std::string subTreeName) const
check if sub is existing in tree_
Referenced by Dune::XT::Common::Configuration::sub().
void Dune::XT::Common::Configuration::report (std::ostream & out = std::cout, const std::string & prefix = "") const
print the ParameterTree
Parameters
out output stream
prefix to be prepended to each line
References Dune::XT::Common::Configuration::empty(), and Dune::XT::Common::Configuration::sub().
Referenced by Dune::XT::Common::operator<<(), Dune::XT::Common::Configuration::report_string(), and Dune::XT::Common::Configuration::~Configuration().
Configuration Dune::XT::Common::Configuration::sub (const std::string sub_id) const
Attention
Please note the difference to Dune::ParameterTree::sub (return: value vs. reference)!
References Dune::XT::Common::Configuration::Configuration(), DUNE_THROW, Dune::XT::Common::Configuration::empty(), Dune::XT::Common::Configuration::has_sub(), and Dune::XT::Common::Configuration::report_string().
Referenced by Dune::XT::Common::Configuration::flatten(), and Dune::XT::Common::Configuration::report().