Dune::XT::Common Namespace Reference
Dune::XT::Common Namespace Reference
Namespaces
Exceptions
FloatCmp
internal
TupleProduct
Classes
struct Colors
namespace to define color constants that can be used to print colored text in an output stream.
struct StreamModifiers
class Configuration
class ConvergenceStudy
class FixedMapIterator
custom iterator for FixedMap
class ConstFixedMapIterator
custom const iterator for FixedMap
class FixedMap
a std::map like container that prevents map size change
struct VectorAbstraction
Traits to statically extract information of a (mathematical) vector.
struct is_vector
logically and structurally this belongs in type_utils.hh, but the dependent implementation prohibits that
class FieldMatrix
class FieldMatrix< K, 1, 1 >
class FieldVector
class ValueInitFieldVector
struct VectorAbstraction< Dune::XT::Common::FieldVector< K, SIZE > >
Specialization of VectorAbstraction for Dune::XT::Common::FieldVector.
class LocalizationStudy
class Logging
handles all logging
class SuspendableStrBuffer
class FileBuffer
class EmptyBuffer
class TimedPrefixedStreamBuffer
A stream buffer to be used in TimedPrefixedLogStream.
class LogStream
class TimedPrefixedLogStream
A std::ostream compatible stream that begins every line by printing elapsed time and prefix.
class FileLogStream
ostream compatible class wrapping file and console output
class EmptyLogStream
/dev/null
struct Epsilon
struct Epsilon< T, true >
struct Epsilon< T, false >
struct Epsilon< std::string, false >
struct AbsoluteValue
struct AbsoluteValue< T, true >
struct Absretval
struct Absretval< T, true >
class MinMaxAvg
a vector wrapper for continiously updating min,max,avg of some element type vector
class numeric_limits
class numeric_limits< T, typename std::enable_if< std::numeric_limits< T >::is_specialized >::type >
struct MatrixAbstraction
Traits to statically extract the information of a (mathematical) matrix.
struct MatrixAbstraction< Dune::DynamicMatrix< K > >
struct MatrixAbstraction< Dune::FieldMatrix< K, N, M > >
struct MatrixAbstraction< Dune::XT::Common::FieldMatrix< K, N, M > >
struct is_matrix
struct WraparoundArray
struct remove_const_reference
struct IndexSetPartitioner
Partition that assigns each codim-0 entity in a IndexSet a unique partition number, its index in the set.
struct ThreadManager
class FallbackPerThreadValue
class PrefixOutputIterator
struct UniformDistributionSelector
Helper class to abstract away selecting an integer or real valued distribution.
struct UniformDistributionSelector< T, true >
struct UniformDistributionSelector< T, false >
struct RNG
struct RNG< std::complex< T >, DistributionImp, EngineImp >
class RandomStrings
RNG that represents strings of given length.
class DefaultRNG
defaultrng with choice of uniform distribution and stl's default random engine based on T and its numeric_limits
class DefaultRNG< std::complex< T > >
class DefaultRNG< std::string >
struct HexToString
helper struct for lexical cast
class TimedLogManager
A logging manager that provides info, debug and warning streams.
class TimedLogging
A logger that provides colored and prefixed streams.
struct TimingData
wraps name, start- and end time for one timing section
class Timings
simple inline timing class
class ScopedTiming
struct OutputScopedTiming
struct TupleSerializer
split our function wrapper into sep pointers for Datawriter input
struct FullTuple
struct Typename
an extensible mechanism to assign "cleartext" names to types
struct is_smart_ptr
struct is_smart_ptr< T, typename std::enable_if< std::is_same< std::unique_ptr< typename T::element_type >, T >::value >::type >
struct is_smart_ptr< T, typename std::enable_if< std::is_same< std::shared_ptr< typename T::element_type >, T >::value >::type >
struct is_smart_ptr< T, typename std::enable_if< std::is_same< std::weak_ptr< typename T::element_type >, T >::value >::type >
struct PtrCaller
struct PtrCaller< T, typename std::enable_if< is_smart_ptr< T >::value||std::is_pointer< T >::value >::type >
struct underlying_type
struct is_hashable
gcc < 4.8 fires a static-assert if std::hash< T > () isn't implemented
class ValidatorInterface
Base class for all Validators the idea is from dune-fem, only our class is an actual interface.
class ValidateAny
a class usable as a default validator
class ValidateInList
validates arg iff in given list
class ValidateLess
validate arg iff less than value, obviously
class ValidateGreater
validate arg iff greater than value, obviously
class ValidateInverse
validate iff not Validator(arg)
class ValidateInterval
validate arg iff arg [min,max]
struct Typename< ValidateAny< T > >
example partial specialisation
struct VectorAbstraction< std::vector< T > >
struct VectorAbstraction< Dune::DynamicVector< K > >
struct VectorAbstraction< Dune::FieldVector< K, SIZE > >
struct VectorAbstraction< std::complex< T > >
Typedefs
template<typename T >
using PerThreadValue = FallbackPerThreadValue< T >
typedef void handler_type (int)
type of handler functions
Enumerations
enum LogFlags {
LOG_NONE = 1, LOG_ERROR = 2, LOG_INFO = 4, LOG_DEBUG = 8,
LOG_CONSOLE = 16, LOG_FILE = 32, LOG_NEXT = 64
}
Functions
template<class InputIt , class OutputIt , class UnaryPredicate >
OutputIt move_if (InputIt first, InputIt last, OutputIt d_first, UnaryPredicate pred)
same as std::copy_if, but with move
template<class InputIt , class SequenceType = std::vector<std::string>>
SequenceType make_string_sequence (InputIt first, InputIt last)
std::string color (size_t i)
Chooses a color from a 256 color map for a foreground color.
std::map< std::string,
std::string > & color_map ()
std::string color (const std::string id)
std::string backcolor (size_t i)
Chooses a color from a 256 color map for a background color.
size_t template_color_chooser (size_t i)
bool terminal_supports_color ()
std::string highlight_template (std::string str, size_t maxlevel=10000)
Highlights templates depending on the "template"-level.
std::string highlight_string (std::string str, size_t colornr=0)
A simple function highlighting a whole string in a specified foreground color.
std::string highlight_search_string (std::string str, std::string substr, size_t colornr=0)
Highlights a substring of another string in a specified color.
std::string color_string (const std::string str, const std::string clr)
std::string color_string_red (const std::string str)
void load_into_fem_parameter (const Dune::ParameterTree &tree, const std::string pref="")
Load all key-value pairs from tree into fem parameter database.
std::ostream & operator<< (std::ostream &out, const Configuration &config)
bool operator== (const Configuration &left, const Configuration &right)
bool operator!= (const Configuration &left, const Configuration &right)
Configuration & Config ()
global Configuration instance
std::string directory_only (std::string _path)
strip filename from if present, return empty string if only filename present
std::string filename_only (const std::string &_path)
return everything after the last slash
void test_create_directory (const std::string _path)
may include filename, will be stripped
bool touch (const std::string &_path)
pure c++ emulation of system's touch binary
std::unique_ptr
< boost::filesystem::ofstream > make_ofstream (const boost::filesystem::path &path, const std::ios_base::openmode mode)
std::unique_ptr
< boost::filesystem::ifstream > make_ifstream (const boost::filesystem::path &path, const std::ios_base::openmode mode)
void file_to_stream_filtered (std::ostream &stream, std::string filename, std::string filter)
read a file and output all lines containing filter string to a stream
void meminfo (LogStream &stream)
output programs mem usage stats by reading from /proc
logflags_ (LOG_NONE)
emptyLogStream_ (logflags_)
Logging & Logger ()
global Logging instance
template<class T >
Absretval< T >::type abs (const T &val)
template<typename T >
T clamp (const T var, const T min, const T max)
template<typename T >
int signum (T val)
template<class T >
bool isnan (T val)
forward to std::isnan for general types, overload for complex below
template<class T >
bool isnan (std::complex< T > val)
override isnan for complex here so it doesn't bleed into the std namespace
template<class T >
bool isinf (T val)
forward to std::isinf for general types, overload for complex below
template<class T >
bool isinf (std::complex< T > val)
override isinf for complex here so it doesn't bleed into the std namespace
template<class MatrixType >
std::enable_if< is_matrix
< MatrixType >::value,
MatrixType >::type create (const size_t sz, const typename MatrixAbstraction< MatrixType >::S &val)
void dump_environment (boost::filesystem::ofstream &file, std::string csv_sep=",")
writes process environment to file
template<class StlSequence >
int get_idx (const StlSequence &ct, const typename StlSequence::value_type &val)
element-index-in-container search
template<class T , size_t N>
size_t array_length (T(&)[N])
type safe (this will not compile for degraded-to-pointer arrays) way of getting array length
template<class T , size_t N>
std::array< T, N > make_array (const T &v)
get a non-zero initialised array
template<class T , size_t N>
std::array< T, N > make_array (const std::vector< T > &v)
template<typename Key , typename T , typename MapType >
std::pair< typename
MapType::iterator, bool > map_emplace (MapType &map_in, Key key, T value)
template<typename K , typename V , typename MapType >
std::pair< typename
MapType::iterator, bool > map_emplace (MapType &map_in, std::piecewise_construct_t pcw, K &&keys, V &&values)
ThreadManager & threadManager ()
global singleton ThreadManager
template<class V >
std::enable_if< is_vector< V >
::value, void >::type print (const V &vec, const std::string name, std::ostream &out, const std::string prefix="")
template<class M >
std::enable_if< is_matrix< M >
::value, void >::type print (const M &mat, const std::string name, std::ostream &out, const std::string prefix="")
template<class Matrix >
void matrix_to_gnuplot_stream (const Matrix &matrix, std::ostream &stream)
useful for visualizing sparsity patterns of matrices
std::string dim_to_axis_name (const size_t dim, const bool capitalize=false)
maps 1,2,3 to x,y,z / X,Y,Z
template<class T , class sequence = std::vector<T>>
std::enable_if<!std::is_enum
< T >::value, sequence >::type value_range (const T start, const T end, const T increment=Epsilon< T >::value)
get a vector with values in [start : increment : end)
template<class T , class sequence = std::vector<typename Absretval<T>::type>>
std::enable_if< std::is_enum
< T >::value, sequence >::type value_range (const T start, const T end, const typename Absretval< T >::type increment=Epsilon< typename Absretval< T >::type >::value)
signature for enumeration Types T
template<class T , class sequence = std::vector<T>>
std::enable_if<!std::is_enum
< T >::value, sequence >::type value_range (const T end)
get a vector with values in [0 : Epsilon<T> : end)
template<class T , class sequence = std::vector<typename Absretval<T>::type>>
std::enable_if< std::is_enum
< T >::value, sequence >::type value_range (const T end)
get a vector with values in [0 : Epsilon<T> : end)
void reset_signal (int signal)
reset given signal to default handler
void handle_interrupt (int signal)
example signal handler
void install_signal_handler (int signal, handler_type handler)
calling this from your main() will install handler as callback when signal is received
template<class T = std::string>
std::vector< T > tokenize (const std::string &msg, const std::string &separators, const boost::algorithm::token_compress_mode_type mode=boost::algorithm::token_compress_off)
convenience wrapper around boost::algorithm::split to split one string into a vector of strings
template<class T >
static T from_string (std::string ss, const size_t size=0, const size_t cols=0)
Reads an object from a string.
template<class T >
static std::string to_string (const T &ss, const size_t precision=default_to_string_precision)
Converts an object to string.
template<class T >
std::string whitespaceify (const T &t, const char whitespace= ' ')
Returns a string of lengths t' whitespace (or whitespace chars).
template<>
std::vector< std::string > tokenize (const std::string &msg, const std::string &separators, const boost::algorithm::token_compress_mode_type mode)
std::string stringFromTime (time_t cur_time=time(NULL))
returns string with local time in current locale's format
static char ** vector_to_main_args (const std::vector< std::string > &args)
TimedLogging & TimedLogger ()
Global instance of the timed logger.
Timings & timings ()
XT::Profiler global instance.
std::string demangle_typename (const std::string &mangled_name)
template<class T >
std::string demangled_type_id (T &obj)
demangles typeid
template<class T >
void real_type_id (T &obj, std::string name="", size_t maxlevel=10000)
create output for demangled typeid
template<class T >
std::string get_typename (const T &)
INVERSE_VALIDATE (ValidateNone, ValidateAny)
INVERSE_VALIDATE (ValidateGreaterOrEqual, ValidateLess)
INVERSE_VALIDATE (ValidateNotLess, ValidateLess)
template<class VectorType >
std::enable_if< is_vector
< VectorType >::value,
VectorType >::type create (const size_t sz, const typename VectorAbstraction< VectorType >::S &val=typename VectorAbstraction< VectorType >::S(0))
template<class T , class SR >
std::enable_if< is_complex< T >
::value, T >::type create (const size_t, const SR &val=typename VectorAbstraction< T >::R(0))
template<class VectorType >
std::enable_if
< std::is_arithmetic
< VectorType >::value,
VectorType >::type create (const size_t, const typename VectorAbstraction< VectorType >::S &val=typename VectorAbstraction< VectorType >::S(0))
Variables
static constexpr const std::size_t default_to_string_precision = 6u
Typedef Documentation
typedef void Dune::XT::Common::handler_type(int)
type of handler functions
template<typename T > using Dune::XT::Common::PerThreadValue = typedef FallbackPerThreadValue<T>
Enumeration Type Documentation
enum Dune::XT::Common::LogFlags
Enumerator
LOG_NONE
LOG_ERROR
LOG_INFO
LOG_DEBUG
LOG_CONSOLE
LOG_FILE
LOG_NEXT
Function Documentation
template<class T > Absretval<T>::type Dune::XT::Common::abs (const T & val)
References Dune::XT::Common::AbsoluteValue< T, isUnsigned >::result().
Referenced by Dune::XT::Common::FloatCmp::internal::float_cmp_eq(), Dune::XT::Common::AbsoluteValue< T, isUnsigned >::result(), and value_range().
template<class T , size_t N> size_t Dune::XT::Common::array_length (T(&) [N])
type safe (this will not compile for degraded-to-pointer arrays) way of getting array length
std::string Dune::XT::Common::backcolor (size_t i)
Chooses a color from a 256 color map for a background color.
Parameters
i The color number between 0 and 255.
Returns
A string describing a color code.
References to_string().
template<typename T > T Dune::XT::Common::clamp (const T var, const T min, const T max)
Returns
var bounded in [min, max]
std::string Dune::XT::Common::color (size_t i)
Chooses a color from a 256 color map for a foreground color.
Parameters
i The color number between 0 and 255.
Returns
A string describing a color code.
References to_string().
std::string Dune::XT::Common::color (const std::string id)
References color_map().
std::map< std::string, std::string > & Dune::XT::Common::color_map ()
References Dune::XT::Common::Colors::black, Dune::XT::Common::Colors::blue, Dune::XT::Common::Colors::brown, Dune::XT::Common::Colors::cyan, Dune::XT::Common::Colors::darkgray, Dune::XT::Common::Colors::green, Dune::XT::Common::Colors::lightblue, Dune::XT::Common::Colors::lightcyan, Dune::XT::Common::Colors::lightgray, Dune::XT::Common::Colors::lightgreen, Dune::XT::Common::Colors::lightpurple, Dune::XT::Common::Colors::lightred, Dune::XT::Common::Colors::purple, Dune::XT::Common::Colors::red, Dune::XT::Common::Colors::white, and Dune::XT::Common::Colors::yellow.
Referenced by color().
std::string Dune::XT::Common::color_string (const std::string str, const std::string clr)
References Dune::XT::Common::StreamModifiers::normal, and terminal_supports_color().
Referenced by color_string_red(), and Dune::XT::Common::ConvergenceStudy::run().
std::string Dune::XT::Common::color_string_red (const std::string str)
References color_string(), and Dune::XT::Common::Colors::red.
Configuration& Dune::XT::Common::Config () inline
global Configuration instance
template<class VectorType > std::enable_if<is_vector<VectorType>::value, VectorType>::type Dune::XT::Common::create (const size_t sz, const typename VectorAbstraction< VectorType >::S & val = typename VectorAbstraction<VectorType>::S(0))
References Dune::XT::Common::VectorAbstraction< VecType >::create().
template<class T , class SR > std::enable_if<is_complex<T>::value, T>::type Dune::XT::Common::create (const size_t , const SR & val = typename VectorAbstraction<T>::R(0))
References Dune::XT::Common::VectorAbstraction< VecType >::create().
template<class VectorType > std::enable_if<std::is_arithmetic<VectorType>::value, VectorType>::type Dune::XT::Common::create (const size_t , const typename VectorAbstraction< VectorType >::S & val = typename VectorAbstraction<VectorType>::S(0))
template<class MatrixType > std::enable_if<is_matrix<MatrixType>::value, MatrixType>::type Dune::XT::Common::create (const size_t sz, const typename MatrixAbstraction< MatrixType >::S & val)
References Dune::XT::Common::MatrixAbstraction< MatType >::create().
std::string Dune::XT::Common::demangle_typename (const std::string & mangled_name) inline
Referenced by demangled_type_id(), and Dune::XT::Common::Typename< T >::value().
template<class T > std::string Dune::XT::Common::demangled_type_id (T & obj)
demangles typeid
References demangle_typename().
Referenced by real_type_id().
std::string Dune::XT::Common::dim_to_axis_name (const size_t dim, const bool capitalize = false) inline
maps 1,2,3 to x,y,z / X,Y,Z
std::string Dune::XT::Common::directory_only (std::string _path)
strip filename from if present, return empty string if only filename present
Referenced by Dune::XT::Common::Configuration::set_log_on_exit(), Dune::XT::Common::Configuration::set_logfile(), test_create_directory(), and Dune::XT::Common::Configuration::~Configuration().
void Dune::XT::Common::dump_environment (boost::filesystem::ofstream & file, std::string csv_sep)
writes process environment to file
References environ, and tokenize().
Dune::XT::Common::emptyLogStream_ (logflags_)
References logflags_().
void Dune::XT::Common::file_to_stream_filtered (std::ostream & stream, std::string filename, std::string filter)
read a file and output all lines containing filter string to a stream
Referenced by meminfo().
std::string Dune::XT::Common::filename_only (const std::string & _path)
return everything after the last slash
template<class T > static T Dune::XT::Common::from_string (std::string ss, const size_t size = 0, const size_t cols = 0) inline static
Reads an object from a string.
See Also
internal::from_string for implementations
Parameters
ss string to read from
size Determines the size of the returning container (size if T is a vector type, rows if T is a matrix type, ignored if T is a scalar type; 0 means automatic).
cols Determines the number of columns of the returning matrix if T is a matrix type (0 means automatic; ignored if T is a vector or scalar type).
template<class StlSequence > int Dune::XT::Common::get_idx (const StlSequence & ct, const typename StlSequence::value_type & val) inline
element-index-in-container search
template<class T > std::string Dune::XT::Common::get_typename (const T &)
References Dune::XT::Common::Typename< T >::value().
Referenced by make_array().
void Dune::XT::Common::handle_interrupt (int signal)
example signal handler
References DXTC_LOG_INFO, reset_signal(), and stringFromTime().
std::string Dune::XT::Common::highlight_search_string (std::string str, std::string substr, size_t colornr = 0)
Highlights a substring of another string in a specified color.
Parameters
str The string where you want to highlight substrings.
substr The sub string you want to highlight in str.
colornr A color number from a 256 color map between 0 and 255.
Returns
The highlighted string.
References to_string().
std::string Dune::XT::Common::highlight_string (std::string str, size_t colornr = 0)
A simple function highlighting a whole string in a specified foreground color.
Parameters
str The string you want to highlight.
colornr A color number from a 256 color map between 0 and 255.
Returns
The highlighted string.
References to_string().
std::string Dune::XT::Common::highlight_template (std::string str, size_t maxlevel = 10000)
Highlights templates depending on the "template"-level.
Parameters
str The string containing the template string
maxlevel The maximal template-level the string is reduced to.
Returns
A colored template string.
References template_color_chooser(), and to_string().
Referenced by real_type_id().
void Dune::XT::Common::install_signal_handler (int signal, handler_type handler)
calling this from your main() will install handler as callback when signal is received
Dune::XT::Common::INVERSE_VALIDATE (ValidateNone , ValidateAny)
Dune::XT::Common::INVERSE_VALIDATE (ValidateGreaterOrEqual , ValidateLess)
Dune::XT::Common::INVERSE_VALIDATE (ValidateNotLess , ValidateLess)
template<class T > bool Dune::XT::Common::isinf (T val)
forward to std::isinf for general types, overload for complex below
References isinf().
Referenced by isinf().
template<class T > bool Dune::XT::Common::isinf (std::complex< T > val)
override isinf for complex here so it doesn't bleed into the std namespace
References isinf().
Referenced by isinf().
template<class T > bool Dune::XT::Common::isnan (T val)
forward to std::isnan for general types, overload for complex below
References isnan().
Referenced by isnan().
template<class T > bool Dune::XT::Common::isnan (std::complex< T > val)
override isnan for complex here so it doesn't bleed into the std namespace
References isnan().
Referenced by isnan().
void Dune::XT::Common::load_into_fem_parameter (const Dune::ParameterTree & tree, const std::string pref = "")
Load all key-value pairs from tree into fem parameter database.
Parameters
tree ParameterTree to get values from.
pref Prefix that is added to each key and subkey (like this: pref.key), default is "".
Referenced by Dune::XT::Common::Configuration::read_command_line().
Dune::XT::Common::logflags_ (LOG_NONE)
Referenced by Dune::XT::Common::Logging::create(), and emptyLogStream_().
Logging & Dune::XT::Common::Logger () inline
global Logging instance
template<class T , size_t N> std::array<T, N> Dune::XT::Common::make_array (const T & v)
get a non-zero initialised array
template<class T , size_t N> std::array<T, N> Dune::XT::Common::make_array (const std::vector< T > & v)
References DUNE_THROW, and get_typename().
std::unique_ptr< boost::filesystem::ifstream > Dune::XT::Common::make_ifstream (const boost::filesystem::path & path, const std::ios_base::openmode mode)
References test_create_directory().
std::unique_ptr< boost::filesystem::ofstream > Dune::XT::Common::make_ofstream (const boost::filesystem::path & path, const std::ios_base::openmode mode)
References test_create_directory().
Referenced by Dune::XT::Common::Configuration::~Configuration().
template<class InputIt , class SequenceType = std::vector<std::string>> SequenceType Dune::XT::Common::make_string_sequence (InputIt first, InputIt last)
References to_string().
template<typename Key , typename T , typename MapType > std::pair<typename MapType::iterator, bool> Dune::XT::Common::map_emplace (MapType & map_in, Key key, T value)
abstraction for stdlibs w/o map.emplace This isn't covering the full emplace spec, and the piecewise case potentially improper, but we only need this in an Intel MIC setup with weird lib versioning. Normally we'd depend on the full gcc 4.8 stack atm and do not use the insert fallback
References DXTC_LOG_DEBUG_0.
template<typename K , typename V , typename MapType > std::pair<typename MapType::iterator, bool> Dune::XT::Common::map_emplace (MapType & map_in, std::piecewise_construct_t pcw, K && keys, V && values)
References DXTC_LOG_DEBUG_0.
template<class Matrix > void Dune::XT::Common::matrix_to_gnuplot_stream (const Matrix & matrix, std::ostream & stream)
useful for visualizing sparsity patterns of matrices
References value_range().
void Dune::XT::Common::meminfo (LogStream & stream)
output programs mem usage stats by reading from /proc
References file_to_stream_filtered(), and Dune::XT::Common::LogStream::resume().
template<class InputIt , class OutputIt , class UnaryPredicate > OutputIt Dune::XT::Common::move_if (InputIt first, InputIt last, OutputIt d_first, UnaryPredicate pred)
same as std::copy_if, but with move
bool Dune::XT::Common::operator!= (const Configuration & left, const Configuration & right)
std::ostream & Dune::XT::Common::operator<< (std::ostream & out, const Configuration & config)
References Dune::XT::Common::Configuration::report().
bool Dune::XT::Common::operator== (const Configuration & left, const Configuration & right)
References Dune::XT::Common::Configuration::flatten().
template<class V > std::enable_if<is_vector<V>::value, void>::type Dune::XT::Common::print (const V & vec, const std::string name, std::ostream & out, const std::string prefix = "")
template<class M > std::enable_if<is_matrix<M>::value, void>::type Dune::XT::Common::print (const M & mat, const std::string name, std::ostream & out, const std::string prefix = "")
template<class T > void Dune::XT::Common::real_type_id (T & obj, std::string name = "", size_t maxlevel = 10000)
create output for demangled typeid
References demangled_type_id(), and highlight_template().
void Dune::XT::Common::reset_signal (int signal)
reset given signal to default handler
POSIX signal management utils.
reset given signal to default handler
Referenced by handle_interrupt().
template<typename T > int Dune::XT::Common::signum (T val)
Returns
: -1 iff val < 0 0 iff val == 0 1 iff val > 0
Referenced by Dune::XT::Common::internal::to_string().
std::string Dune::XT::Common::stringFromTime (time_t cur_time = time(NULL)) inline
returns string with local time in current locale's format
Referenced by handle_interrupt().
size_t Dune::XT::Common::template_color_chooser (size_t i)
Referenced by highlight_template().
bool Dune::XT::Common::terminal_supports_color ()
This is taken from gtest-all.cc!
Referenced by color_string(), and Dune::XT::Common::TimedLogging::create().
void Dune::XT::Common::test_create_directory (const std::string _path)
may include filename, will be stripped
References directory_only().
Referenced by Dune::XT::Common::Logging::create(), make_ifstream(), make_ofstream(), Dune::XT::Common::Configuration::set_log_on_exit(), Dune::XT::Common::Configuration::set_logfile(), Dune::XT::Common::Timings::set_outputdir(), and Dune::XT::Common::Configuration::~Configuration().
ThreadManager & Dune::XT::Common::threadManager () inline
global singleton ThreadManager
Referenced by Dune::XT::Common::FallbackPerThreadValue< ValueImp >::operator*(), Dune::XT::Common::FallbackPerThreadValue< ValueImp >::operator->(), and Dune::XT::Common::Timings::output_all_measures().
TimedLogging & Dune::XT::Common::TimedLogger ()
Global instance of the timed logger.
This global logger instance is intended to be used in two ways:
Many classes or functions use this instance to log info, debug or warning messages. You can do so in your code by calling the TimedLogging::get() method, providing an identifier that should resemble the current scope:
void user_function()
{
  TimedLogger().get("user_function").info() << "some information" << std::endl;
  for (size_t ii = 0; ii < 100; ++ii)
    TimedLogger().get("user_function").debug() << "debug output number " << ii << std::endl;
}
You can also hold a TimedLogManager object within the current scope or class, if wished:
class UserClass
{
public:
  UserClass()
    : logger_(TimedLogger().get("UserClass"))
  {}
  void some_method()
  {
    logger_.warn() << "something is severly wrong!" << std::endl;
  }
private:
  TimedLogManager logger_;
}
Each time a new TimedLogManager is created using TimedLogging::get() the loglevel is increased, each time such a logger goes out of scope the loglevel is decreased.
You can use this instance to control the level (and style) of logging you want to have enabled in your application. You should call TimedLogging::create() as soon as possible (and only once!), until then all logging (execpt warnings) is disabled:
void silent_function()
{
  auto logger = TimedLogger().get("silent_function");
  logger.info() << "This will never show!" << std::endl;
  const bool all_is_well = false;
  if (!all_is_well)
    logger.warn() << "But this warning will!" << std::endl;
}
int main()
{
  TimedLogger().create(0,   // max info level (only the first)
                       -1,  // max debug level (disabled)
                       true // warnings are enabled
                       );
  auto logger = TimedLogger().get("main");
  logger.info()  << "Welcome to my application!" << std::endl;
  logger.debug() << "This will never show!" << std::endl;
  silent_function();
}
In addition you can enable coloring of the streams (see TimedPrefixedLogStream) and give their respective colors, if wished (see the implementation of color_map() or the foreground colors of Colors for available colors):
int main()
{
  TimedLogger().create(10,          // max info level
                       2,           // max debug level
                       true,        // warnings are enabled (the default)
                       true,        // colors are enabled (the default)
                       "white",     // info color (the default)
                       "lightgrey", // debug color (the default)
                       "red"        // warning color (the default)
                      );
  auto logger = TimedLogger().get("main");
  logger.info() << "<- The 'main' prefix left of this should be white!" << std::endl;
  logger.warn() << "<- The 'warn' prefix left of this should be red!"   << std::endl;
}
Note
Debug logging is only enabled if NDEBUG is not defined but you might still want to guard calls to logger.debug() for performance reasons.
Timings & Dune::XT::Common::timings () inline
XT::Profiler global instance.
global profiler object
Referenced by Dune::XT::Common::ScopedTiming::ScopedTiming(), Dune::XT::Common::OutputScopedTiming::~OutputScopedTiming(), and Dune::XT::Common::ScopedTiming::~ScopedTiming().
template<class T > static std::string Dune::XT::Common::to_string (const T & ss, const size_t precision = default_to_string_precision) inline static
Converts an object to string.
See Also
internal::to_string for implementations
References Dune::XT::Common::internal::to_string().
Referenced by backcolor(), color(), Dune::XT::Common::Configuration::get_list(), highlight_search_string(), highlight_string(), highlight_template(), make_string_sequence(), Dune::XT::Common::ValidateLess< T >::msg(), Dune::XT::Common::ValidateGreater< T >::msg(), Dune::XT::Common::Configuration::set(), and whitespaceify().
template<class T = std::string> std::vector< T > Dune::XT::Common::tokenize (const std::string & msg, const std::string & separators, const boost::algorithm::token_compress_mode_type mode = boost::algorithm::token_compress_off) inline
convenience wrapper around boost::algorithm::split to split one string into a vector of strings
Parameters
msg the spring to be split
separators a list of separators, duh
mode token_compress_off –> potentially empty strings in return, token_compress_on –> empty tokens are discarded
Returns
all tokens in a vector, if msg contains no separators, this'll contain msg as its only element
Referenced by dump_environment(), and Dune::XT::Common::TimedPrefixedStreamBuffer::sync().
template<> std::vector<std::string> Dune::XT::Common::tokenize (const std::string & msg, const std::string & separators, const boost::algorithm::token_compress_mode_type mode) inline
bool Dune::XT::Common::touch (const std::string & _path)
pure c++ emulation of system's touch binary
template<class T , class sequence = std::vector<T>> std::enable_if<!std::is_enum<T>::value, sequence>::type Dune::XT::Common::value_range (const T start, const T end, const T increment = Epsilon<T>::value)
get a vector with values in [start : increment : end)
References abs().
Referenced by matrix_to_gnuplot_stream(), Dune::XT::Common::Timings::stop(), Dune::XT::Common::internal::to_string(), value_range(), vector_to_main_args(), and whitespaceify().
template<class T , class sequence = std::vector<typename Absretval<T>::type>> std::enable_if<std::is_enum<T>::value, sequence>::type Dune::XT::Common::value_range (const T start, const T end, const typename Absretval< T >::type increment = Epsilon<typename Absretval<T>::type>::value)
signature for enumeration Types T
References value_range().
template<class T , class sequence = std::vector<T>> std::enable_if<!std::is_enum<T>::value, sequence>::type Dune::XT::Common::value_range (const T end)
get a vector with values in [0 : Epsilon<T> : end)
References value_range().
template<class T , class sequence = std::vector<typename Absretval<T>::type>> std::enable_if<std::is_enum<T>::value, sequence>::type Dune::XT::Common::value_range (const T end)
get a vector with values in [0 : Epsilon<T> : end)
References value_range().
static char** Dune::XT::Common::vector_to_main_args (const std::vector< std::string > & args) inline static
References value_range().
template<class T > std::string Dune::XT::Common::whitespaceify (const T & t, const char whitespace = ' ')
Returns a string of lengths t' whitespace (or whitespace chars).
Parameters
[in] t defines the length of the return string (after conversion to string)
[in] whitespace char, optional argument, defines entries of return string
Returns
A string of lengths t' whitespace (or whitespace chars).
References DXTC_UNUSED, to_string(), and value_range().
Referenced by Dune::XT::Common::LocalizationStudy::run(), and Dune::XT::Common::ConvergenceStudy::run().
Variable Documentation
constexpr const std::size_t Dune::XT::Common::default_to_string_precision = 6u static