´´These methods allow to merge trees.``
´´These methods allow to merge trees.``
Functions
Configuration & Dune::XT::Common::Configuration::add (const Configuration &other, const std::string sub_id="", const bool overwrite=false)
add another Configuration to this (merge tree_s and requests_map_s)
Configuration & Dune::XT::Common::Configuration::add (const ParameterTree &other, const std::string sub_id="", const bool overwrite=false)
add a Dune::ParameterTree paramtree to this (merge tree_ and paramtree)
Configuration & Dune::XT::Common::Configuration::operator+= (Configuration &other)
add another Configuration to this (merge tree_s and requests_map_s)
Configuration Dune::XT::Common::Configuration::operator+ (Configuration &other)
add this and another Configuration (merge tree_s and requests_map_s)
Detailed Description
Function Documentation
Configuration & Dune::XT::Common::Configuration::add (const Configuration & other, const std::string sub_id = "", const bool overwrite = false)
add another Configuration to this (merge tree_s and requests_map_s)
Parameters
other Configuration to add
sub_id if not empty, other.tree_ is merged in as a sub "sub_id" of tree_
overwrite if true, existing values are overwritten by other's values to the same key
Referenced by Dune::XT::Common::Configuration::Configuration(), and Dune::XT::Common::Configuration::operator+=().
Configuration & Dune::XT::Common::Configuration::add (const ParameterTree & other, const std::string sub_id = "", const bool overwrite = false)
add a Dune::ParameterTree paramtree to this (merge tree_ and paramtree)
Parameters
paramtree ParameterTree to add
sub_id if not empty, paramtree is merged in as a sub "sub_id" of tree_
overwrite if true, existing values are overwritten by paramtree's values to the same key
Configuration Dune::XT::Common::Configuration::operator+ (Configuration & other)
add this and another Configuration (merge tree_s and requests_map_s)
Configuration & Dune::XT::Common::Configuration::operator+= (Configuration & other)
add another Configuration to this (merge tree_s and requests_map_s)
References Dune::XT::Common::Configuration::add().