Dune::XT::Common::internal Namespace Reference
Dune::XT::Common::internal Namespace Reference
Classes
struct Typer
struct Helper
struct Helper< bool, anything >
Functions
static std::string trim_copy_safely (std::string str_in)
template<class T >
static T convert_safely (std::string ss)
template<class T >
static std::enable_if
<!is_vector< T >::value
&&!is_matrix< T >::value
&&!is_complex< T >::value, T >
::type from_string (std::string ss, const size_t DXTC_DEBUG_ONLY(rows)=0, const size_t DXTC_DEBUG_ONLY(cols)=0)
template<class V >
static std::enable_if
< is_complex< V >::value, V >
::type from_string (std::string ss, const size_t=0, const size_t=0)
template<class VectorType >
static std::enable_if
< is_vector< VectorType >
::value, VectorType >::type from_string (std::string ss, const size_t size, const size_t DXTC_DEBUG_ONLY(cols)=0)
template<class MatrixType >
static std::enable_if
< is_matrix< MatrixType >
::value, MatrixType >::type from_string (std::string matrix_str, const size_t rows, const size_t cols)
template<class T >
static std::enable_if
<!is_vector< T >::value
&&!is_matrix< T >::value,
std::string >::type to_string (const T &ss, const std::size_t precision)
template<typename T >
static std::string to_string (const std::complex< T > &val, const std::size_t precision)
template<int size>
static std::string to_string (const Dune::bigunsignedint< size > &ss, const std::size_t)
std::string to_string (const char *ss, const std::size_t)
std::string to_string (char ss, const std::size_t)
std::string to_string (const std::string ss, const std::size_t)
template<class V >
static std::enable_if
< is_vector< V >::value,
std::string >::type to_string (const V &vec, const std::size_t precision)
template<class M >
static std::enable_if
< is_matrix< M >::value,
std::string >::type to_string (const M &mat, const std::size_t precision)
Variables
static const bool configuration_record_defaults = false
static const bool configuration_warn_on_default_access = false
static const bool configuration_log_on_exit = false
static const std::string configuration_logfile = "data/log/dxtc_parameter.log"
Function Documentation
template<class T > static T Dune::XT::Common::internal::convert_safely (std::string ss) inline static
References DUNE_THROW.
template<class T > static std::enable_if<!is_vector<T>::value && !is_matrix<T>::value && !is_complex<T>::value, T>::type Dune::XT::Common::internal::from_string (std::string ss, const size_t DXTC_DEBUG_ONLYrows = 0, const size_t DXTC_DEBUG_ONLYcols = 0) inline static
References Dune::XT::Common::internal::Helper< T, anything >::from_string().
template<class V > static std::enable_if<is_complex<V>::value, V>::type Dune::XT::Common::internal::from_string (std::string ss, const size_t = 0, const size_t = 0) inline static
References DUNE_THROW.
template<class VectorType > static std::enable_if<is_vector<VectorType>::value, VectorType>::type Dune::XT::Common::internal::from_string (std::string ss, const size_t size, const size_t DXTC_DEBUG_ONLYcols = 0) inline static
References Dune::XT::Common::VectorAbstraction< VecType >::create(), DUNE_THROW, and trim_copy_safely().
template<class MatrixType > static std::enable_if<is_matrix<MatrixType>::value, MatrixType>::type Dune::XT::Common::internal::from_string (std::string matrix_str, const size_t rows, const size_t cols) inline static
References Dune::XT::Common::MatrixAbstraction< MatType >::create(), DUNE_THROW, and trim_copy_safely().
template<class T > static std::enable_if<!is_vector<T>::value && !is_matrix<T>::value, std::string>::type Dune::XT::Common::internal::to_string (const T & ss, const std::size_t precision) inline static
Referenced by Dune::XT::Common::to_string(), and to_string().
template<typename T > static std::string Dune::XT::Common::internal::to_string (const std::complex< T > & val, const std::size_t precision) inline static
References Dune::XT::Common::signum(), and to_string().
template<int size> static std::string Dune::XT::Common::internal::to_string (const Dune::bigunsignedint< size > & ss, const std::size_t) inline static
std::string Dune::XT::Common::internal::to_string (const char * ss, const std::size_t) inline
std::string Dune::XT::Common::internal::to_string (char ss, const std::size_t) inline
std::string Dune::XT::Common::internal::to_string (const std::string ss, const std::size_t) inline
template<class V > static std::enable_if<is_vector<V>::value, std::string>::type Dune::XT::Common::internal::to_string (const V & vec, const std::size_t precision) inline static
References to_string(), and Dune::XT::Common::value_range().
template<class M > static std::enable_if<is_matrix<M>::value, std::string>::type Dune::XT::Common::internal::to_string (const M & mat, const std::size_t precision) inline static
References to_string(), and Dune::XT::Common::value_range().
static std::string Dune::XT::Common::internal::trim_copy_safely (std::string str_in) inline static
References DUNE_THROW.
Referenced by from_string().
Variable Documentation
const bool Dune::XT::Common::internal::configuration_log_on_exit = false static
const std::string Dune::XT::Common::internal::configuration_logfile = "data/log/dxtc_parameter.log" static
const bool Dune::XT::Common::internal::configuration_record_defaults = false static
const bool Dune::XT::Common::internal::configuration_warn_on_default_access = false static