Dune::XT::Common::FloatCmp::internal Namespace Reference
Dune::XT::Common::FloatCmp::internal Namespace Reference
Classes
struct Call
struct Call< FirstType, SecondType, ToleranceType, Style::numpy >
struct cmp_type_check
struct ConvertStyle
struct ConvertStyle< Style::relativeWeak >
struct ConvertStyle< Style::relativeStrong >
struct ConvertStyle< Style::absolute >
Functions
template<class T >
std::enable_if
< std::is_arithmetic< T >
::value, bool >::type float_cmp_eq (const T &xx, const T &yy, const T &rtol, const T &atol)
template<class T >
std::enable_if< is_complex< T >
::value, bool >::type float_cmp_eq (const T &xx, const T &yy, const T &rtol, const T &atol)
template<class XType , class YType , class TolType >
std::enable_if< is_vector
< XType >::value &&is_vector
< YType >::value
&&std::is_same< typename
VectorAbstraction< XType >::S,
TolType >::value
&&std::is_same< typename
VectorAbstraction< YType >::S,
TolType >::value, bool >::type float_cmp_eq (const XType &xx, const YType &yy, const TolType &rtol, const TolType &atol)
template<Dune::FloatCmp::CmpStyle style, class T >
std::enable_if
< std::is_arithmetic< T >
::value, bool >::type dune_float_cmp_eq (const T &xx, const T &yy, const T &eps)
template<Dune::FloatCmp::CmpStyle style, class T >
std::enable_if< is_complex< T >
::value, bool >::type dune_float_cmp_eq (const T &xx, const T &yy, const T &eps)
template<Dune::FloatCmp::CmpStyle style, class XType , class YType , class EpsType >
std::enable_if< is_vector
< XType >::value &&is_vector
< YType >::value
&&std::is_same< typename
VectorAbstraction< XType >::S,
EpsType >::value
&&std::is_same< typename
VectorAbstraction< YType >::S,
EpsType >::value, bool >::type dune_float_cmp_eq (const XType &xx, const YType &yy, const EpsType &eps)
template<class T >
std::enable_if
< std::is_arithmetic< T >
::value, bool >::type cmp_gt (const T &xx, const T &yy)
template<class T >
bool cmp_gt (const std::complex< T > &xx, const std::complex< T > &yy)
template<class XType , class YType >
std::enable_if< is_vector
< XType >::value &&is_vector
< YType >::value
&&std::is_same< typename
VectorAbstraction< XType >::S,
typename VectorAbstraction
< YType >::S >::value, bool >
::type cmp_gt (const XType &xx, const YType &yy)
template<class T >
std::enable_if
< std::is_arithmetic< T >
::value, bool >::type cmp_lt (const T &xx, const T &yy)
template<class T >
bool cmp_lt (const std::complex< T > &xx, const std::complex< T > &yy)
template<class XType , class YType >
std::enable_if< is_vector
< XType >::value &&is_vector
< YType >::value
&&std::is_same< typename
VectorAbstraction< XType >::S,
typename VectorAbstraction
< YType >::S >::value, bool >
::type cmp_lt (const XType &xx, const YType &yy)
Function Documentation
template<class T > std::enable_if<std::is_arithmetic<T>::value, bool>::type Dune::XT::Common::FloatCmp::internal::cmp_gt (const T & xx, const T & yy)
Referenced by cmp_gt(), Dune::XT::Common::FloatCmp::internal::Call< FirstType, SecondType, ToleranceType, style >::ge(), Dune::XT::Common::FloatCmp::internal::Call< FirstType, SecondType, ToleranceType, Style::numpy >::ge(), Dune::XT::Common::FloatCmp::internal::Call< FirstType, SecondType, ToleranceType, style >::gt(), and Dune::XT::Common::FloatCmp::internal::Call< FirstType, SecondType, ToleranceType, Style::numpy >::gt().
template<class T > bool Dune::XT::Common::FloatCmp::internal::cmp_gt (const std::complex< T > & xx, const std::complex< T > & yy)
References cmp_gt().
template<class XType , class YType > std::enable_if<is_vector<XType>::value && is_vector<YType>::value && std::is_same<typename VectorAbstraction<XType>::S, typename VectorAbstraction<YType>::S>::value, bool>::type Dune::XT::Common::FloatCmp::internal::cmp_gt (const XType & xx, const YType & yy)
References cmp_gt().
template<class T > std::enable_if<std::is_arithmetic<T>::value, bool>::type Dune::XT::Common::FloatCmp::internal::cmp_lt (const T & xx, const T & yy)
Referenced by cmp_lt(), Dune::XT::Common::FloatCmp::internal::Call< FirstType, SecondType, ToleranceType, style >::le(), Dune::XT::Common::FloatCmp::internal::Call< FirstType, SecondType, ToleranceType, Style::numpy >::le(), Dune::XT::Common::FloatCmp::internal::Call< FirstType, SecondType, ToleranceType, style >::lt(), and Dune::XT::Common::FloatCmp::internal::Call< FirstType, SecondType, ToleranceType, Style::numpy >::lt().
template<class T > bool Dune::XT::Common::FloatCmp::internal::cmp_lt (const std::complex< T > & xx, const std::complex< T > & yy)
References cmp_lt().
template<class XType , class YType > std::enable_if<is_vector<XType>::value && is_vector<YType>::value && std::is_same<typename VectorAbstraction<XType>::S, typename VectorAbstraction<YType>::S>::value, bool>::type Dune::XT::Common::FloatCmp::internal::cmp_lt (const XType & xx, const YType & yy)
References cmp_lt().
template<Dune::FloatCmp::CmpStyle style, class T > std::enable_if<std::is_arithmetic<T>::value, bool>::type Dune::XT::Common::FloatCmp::internal::dune_float_cmp_eq (const T & xx, const T & yy, const T & eps)
template<Dune::FloatCmp::CmpStyle style, class T > std::enable_if<is_complex<T>::value, bool>::type Dune::XT::Common::FloatCmp::internal::dune_float_cmp_eq (const T & xx, const T & yy, const T & eps)
template<Dune::FloatCmp::CmpStyle style, class XType , class YType , class EpsType > std::enable_if<is_vector<XType>::value && is_vector<YType>::value && std::is_same<typename VectorAbstraction<XType>::S, EpsType>::value && std::is_same<typename VectorAbstraction<YType>::S, EpsType>::value, bool>::type Dune::XT::Common::FloatCmp::internal::dune_float_cmp_eq (const XType & xx, const YType & yy, const EpsType & eps)
template<class T > std::enable_if<std::is_arithmetic<T>::value, bool>::type Dune::XT::Common::FloatCmp::internal::float_cmp_eq (const T & xx, const T & yy, const T & rtol, const T & atol)
Taken from http://docs.pymor.org/en/latest/_modules/pymor/tools/floatcmp.html#float_cmp, https://github.com/numpy/numpy/blob/v1.9.1/numpy/core/numeric.py#L2238
References Dune::XT::Common::abs().
Referenced by Dune::XT::Common::FloatCmp::internal::Call< FirstType, SecondType, ToleranceType, Style::numpy >::eq(), float_cmp_eq(), Dune::XT::Common::FloatCmp::internal::Call< FirstType, SecondType, ToleranceType, Style::numpy >::ge(), Dune::XT::Common::FloatCmp::internal::Call< FirstType, SecondType, ToleranceType, Style::numpy >::gt(), Dune::XT::Common::FloatCmp::internal::Call< FirstType, SecondType, ToleranceType, Style::numpy >::le(), Dune::XT::Common::FloatCmp::internal::Call< FirstType, SecondType, ToleranceType, Style::numpy >::lt(), and Dune::XT::Common::FloatCmp::internal::Call< FirstType, SecondType, ToleranceType, Style::numpy >::ne().
template<class T > std::enable_if<is_complex<T>::value, bool>::type Dune::XT::Common::FloatCmp::internal::float_cmp_eq (const T & xx, const T & yy, const T & rtol, const T & atol)
References float_cmp_eq().
template<class XType , class YType , class TolType > std::enable_if<is_vector<XType>::value && is_vector<YType>::value && std::is_same<typename VectorAbstraction<XType>::S, TolType>::value && std::is_same<typename VectorAbstraction<YType>::S, TolType>::value, bool>::type Dune::XT::Common::FloatCmp::internal::float_cmp_eq (const XType & xx, const YType & yy, const TolType & rtol, const TolType & atol)
References float_cmp_eq().