Dune::XT::Functions::ReinterpretFunction< SourceType, GridViewType > Class Template Reference
Dune::XT::Functions::ReinterpretFunction< SourceType, GridViewType > Class Template Reference abstract
Allows to reinterpret a given LocalizableFunctionInterface, associated with a given grid view, on a different grid view.
#include <dune/xt/functions/reinterpret.hh>
Public Types
typedef EntityImp EntityType
typedef DomainFieldImp DomainFieldType
typedef RangeFieldImp RangeFieldType
typedef LocalfunctionInterface
< EntityType, DomainFieldType,
dimDomain, RangeFieldType,
dimRange, dimRangeCols > LocalfunctionType
typedef
LocalfunctionType::DomainType DomainType
typedef
LocalfunctionType::RangeType RangeType
typedef
LocalfunctionType::JacobianRangeType JacobianRangeType
typedef
Functions::DifferenceFunction
< ThisType, ThisType > DifferenceType
typedef Functions::SumFunction
< ThisType, ThisType > SumType
typedef
Functions::DivergenceFunction
< ThisType > DivergenceType
Public Member Functions
ReinterpretFunction (const SourceType &source, const GridViewType &source_grid_view)
virtual ~ReinterpretFunction ()=default
virtual std::unique_ptr
< LocalfunctionType > local_function (const EntityType &entity) const
virtual std::string type () const
virtual std::string name () const
virtual std::unique_ptr
< LocalfunctionType > local_function (const EntityType &) const =0
DifferenceType operator- (const ThisType &other) const
SumType operator+ (const ThisType &other) const
std::enable_if
< is_localizable_function
< OtherType >::value,
Functions::ProductFunction
< ThisType, OtherType >
>::type operator* (const OtherType &other) const
DivergenceType divergence () const
void visualize (const GridViewType &grid_view, const std::string path, const bool subsampling=true, const VTK::OutputType vtk_output_type=VTK::appendedraw) const
virtual void report (std::ostream &out, const std::string prefix="") const
Static Public Member Functions
static std::string static_id ()
Static Public Attributes
static const size_t dimDomain
static const size_t dimRange
static const size_t dimRangeCols
static const bool available
Detailed Description
template<class SourceType, class GridViewType>
class Dune::XT::Functions::ReinterpretFunction< SourceType, GridViewType >
Allows to reinterpret a given LocalizableFunctionInterface, associated with a given grid view, on a different grid view.
Therefore, we search for the correct entity in the original grid view and use the corresponding local_function to provide an evaluation for a point on the new grid view. The physical domain covered by the new grid view should thus be contained in the physical domain of the original grid view. This is mainly used in the context of prolongation.
Note
The current implementation is not thread safe (due to the entity search).
There is no way to reliably obtain the local polynomial order of the source, and we thus use the order of the local_function corresponding to the first entity.
Member Typedef Documentation
typedef Functions::DifferenceFunction<ThisType, ThisType> Dune::XT::Functions::LocalizableFunctionInterface< XT::Grid::Entity< GridViewType >::type , GridViewType::ctype , domainDim, SourceType::RangeFieldType , rangeDim, rangeDimCols >::DifferenceType inherited
typedef Functions::DivergenceFunction<ThisType> Dune::XT::Functions::LocalizableFunctionInterface< XT::Grid::Entity< GridViewType >::type , GridViewType::ctype , domainDim, SourceType::RangeFieldType , rangeDim, rangeDimCols >::DivergenceType inherited
template<class SourceType , class GridViewType > typedef DomainFieldImp Dune::XT::Functions::LocalizableFunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::DomainFieldType
typedef LocalfunctionType::DomainType Dune::XT::Functions::LocalizableFunctionInterface< XT::Grid::Entity< GridViewType >::type , GridViewType::ctype , domainDim, SourceType::RangeFieldType , rangeDim, rangeDimCols >::DomainType inherited
template<class SourceType , class GridViewType > typedef EntityImp Dune::XT::Functions::LocalizableFunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::EntityType
typedef LocalfunctionType::JacobianRangeType Dune::XT::Functions::LocalizableFunctionInterface< XT::Grid::Entity< GridViewType >::type , GridViewType::ctype , domainDim, SourceType::RangeFieldType , rangeDim, rangeDimCols >::JacobianRangeType inherited
template<class SourceType , class GridViewType > typedef LocalfunctionInterface<EntityType, DomainFieldType, dimDomain, RangeFieldType, dimRange, dimRangeCols> Dune::XT::Functions::LocalizableFunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::LocalfunctionType
template<class SourceType , class GridViewType > typedef RangeFieldImp Dune::XT::Functions::LocalizableFunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::RangeFieldType
typedef LocalfunctionType::RangeType Dune::XT::Functions::LocalizableFunctionInterface< XT::Grid::Entity< GridViewType >::type , GridViewType::ctype , domainDim, SourceType::RangeFieldType , rangeDim, rangeDimCols >::RangeType inherited
typedef Functions::SumFunction<ThisType, ThisType> Dune::XT::Functions::LocalizableFunctionInterface< XT::Grid::Entity< GridViewType >::type , GridViewType::ctype , domainDim, SourceType::RangeFieldType , rangeDim, rangeDimCols >::SumType inherited
Constructor & Destructor Documentation
template<class SourceType , class GridViewType > Dune::XT::Functions::ReinterpretFunction< SourceType, GridViewType >::ReinterpretFunction (const SourceType & source, const GridViewType & source_grid_view) inline
template<class SourceType , class GridViewType > virtual Dune::XT::Functions::ReinterpretFunction< SourceType, GridViewType >::~ReinterpretFunction () virtual default
Member Function Documentation
DivergenceType Dune::XT::Functions::LocalizableFunctionInterface< XT::Grid::Entity< GridViewType >::type , GridViewType::ctype , domainDim, SourceType::RangeFieldType , rangeDim, rangeDimCols >::divergence () const inline inherited
template<class SourceType , class GridViewType > virtual std::unique_ptr<LocalfunctionType> Dune::XT::Functions::ReinterpretFunction< SourceType, GridViewType >::local_function (const EntityType & entity) const inline virtual
virtual std::unique_ptr<LocalfunctionType> Dune::XT::Functions::LocalizableFunctionInterface< XT::Grid::Entity< GridViewType >::type , GridViewType::ctype , domainDim, SourceType::RangeFieldType , rangeDim, rangeDimCols >::local_function (const EntityType &) const pure virtual inherited
template<class SourceType , class GridViewType > virtual std::string Dune::XT::Functions::ReinterpretFunction< SourceType, GridViewType >::name () const inline virtual
Reimplemented from Dune::XT::Functions::LocalizableFunctionInterface< XT::Grid::Entity< GridViewType >::type, GridViewType::ctype, GridViewType::dimension, SourceType::RangeFieldType, SourceType::dimRange, SourceType::dimRangeCols >.
std::enable_if<is_localizable_function<OtherType>::value, Functions::ProductFunction<ThisType, OtherType> >::type Dune::XT::Functions::LocalizableFunctionInterface< XT::Grid::Entity< GridViewType >::type , GridViewType::ctype , domainDim, SourceType::RangeFieldType , rangeDim, rangeDimCols >::operator* (const OtherType & other) const inline inherited
SumType Dune::XT::Functions::LocalizableFunctionInterface< XT::Grid::Entity< GridViewType >::type , GridViewType::ctype , domainDim, SourceType::RangeFieldType , rangeDim, rangeDimCols >::operator+ (const ThisType & other) const inline inherited
DifferenceType Dune::XT::Functions::LocalizableFunctionInterface< XT::Grid::Entity< GridViewType >::type , GridViewType::ctype , domainDim, SourceType::RangeFieldType , rangeDim, rangeDimCols >::operator- (const ThisType & other) const inline inherited
virtual void Dune::XT::Functions::LocalizableFunctionInterface< XT::Grid::Entity< GridViewType >::type , GridViewType::ctype , domainDim, SourceType::RangeFieldType , rangeDim, rangeDimCols >::report (std::ostream & out, const std::string prefix = "") const inline virtual inherited
template<class SourceType , class GridViewType > static std::string Dune::XT::Functions::ReinterpretFunction< SourceType, GridViewType >::static_id () inline static
References Dune::XT::Functions::LocalizableFunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::static_id().
Referenced by Dune::XT::Functions::ReinterpretFunction< SourceType, GridViewType >::type().
template<class SourceType , class GridViewType > virtual std::string Dune::XT::Functions::ReinterpretFunction< SourceType, GridViewType >::type () const inline virtual
Reimplemented from Dune::XT::Functions::LocalizableFunctionInterface< XT::Grid::Entity< GridViewType >::type, GridViewType::ctype, GridViewType::dimension, SourceType::RangeFieldType, SourceType::dimRange, SourceType::dimRangeCols >.
References Dune::XT::Functions::ReinterpretFunction< SourceType, GridViewType >::static_id().
void Dune::XT::Functions::LocalizableFunctionInterface< XT::Grid::Entity< GridViewType >::type , GridViewType::ctype , domainDim, SourceType::RangeFieldType , rangeDim, rangeDimCols >::visualize (const GridViewType & grid_view, const std::string path, const bool subsampling = true, const VTK::OutputType vtk_output_type = VTK::appendedraw) const inline inherited
Note
We use the SubsamplingVTKWriter (which is better for higher orders) by default. This means that the grid you see in the visualization is a refinement of the actual grid!
Member Data Documentation
const bool Dune::XT::Functions::LocalizableFunctionInterface< XT::Grid::Entity< GridViewType >::type , GridViewType::ctype , domainDim, SourceType::RangeFieldType , rangeDim, rangeDimCols >::available static inherited
const size_t Dune::XT::Functions::LocalizableFunctionInterface< XT::Grid::Entity< GridViewType >::type , GridViewType::ctype , domainDim, SourceType::RangeFieldType , rangeDim, rangeDimCols >::dimDomain static inherited
const size_t Dune::XT::Functions::LocalizableFunctionInterface< XT::Grid::Entity< GridViewType >::type , GridViewType::ctype , domainDim, SourceType::RangeFieldType , rangeDim, rangeDimCols >::dimRange static inherited
const size_t Dune::XT::Functions::LocalizableFunctionInterface< XT::Grid::Entity< GridViewType >::type , GridViewType::ctype , domainDim, SourceType::RangeFieldType , rangeDim, rangeDimCols >::dimRangeCols static inherited
The documentation for this class was generated from the following file:
reinterpret.hh