Dune::XT::Functions::FunctionsFactory< E, D, d, R, r, rC > Class Template Reference
Dune::XT::Functions::FunctionsFactory< E, D, d, R, r, rC > Class Template Reference
#include <dune/xt/functions.hh>
Public Types
typedef
LocalizableFunctionInterface
< E, D, d, R, r, rC > InterfaceType
Static Public Member Functions
static std::vector< std::string > available ()
static Common::Configuration default_config (const std::string type, const std::string sub_name="")
static std::unique_ptr
< InterfaceType > create (const std::string type=available()[0], const Common::Configuration cfg=Common::Configuration())
static std::unique_ptr
< InterfaceType > create (const Common::Configuration &cfg)
Detailed Description
template<class E, class D, size_t d, class R, size_t r, size_t rC = 1>
class Dune::XT::Functions::FunctionsFactory< E, D, d, R, r, rC >
Note
If you want to add a new function FooBar, do the following: provide a definition that is available for all template arguments, like:
template< class E, class D, size_t d, class R, size_t r, size_t rC = 1 >
class FooBar
  : public LocalizableFunctionInterface< E, D, d, R, r, rC >
{
  FooBar() { static_assert(AlwaysFalse< E >::value, "Not available for these dimensions!"); }
};
Every specialization that can be provided by the provider then has to define:
static const bool available = true;
In addition you have to add the appropriate include in this file (of course) and the appropriate type below (just like the rest, should be obvious).
Member Typedef Documentation
template<class E , class D , size_t d, class R , size_t r, size_t rC = 1> typedef LocalizableFunctionInterface<E, D, d, R, r, rC> Dune::XT::Functions::FunctionsFactory< E, D, d, R, r, rC >::InterfaceType
Member Function Documentation
template<class E , class D , size_t d, class R , size_t r, size_t rC = 1> static std::vector<std::string> Dune::XT::Functions::FunctionsFactory< E, D, d, R, r, rC >::available () inline static
Referenced by Dune::XT::Functions::FunctionsFactory< E, D, d, R, r, rC >::create(), and Dune::XT::Functions::FunctionsFactory< E, D, d, R, r, rC >::default_config().
template<class E , class D , size_t d, class R , size_t r, size_t rC = 1> static std::unique_ptr<InterfaceType> Dune::XT::Functions::FunctionsFactory< E, D, d, R, r, rC >::create (const std::string type = available()[0], const Common::Configuration cfg = Common::Configuration()) inline static
References Dune::XT::Functions::FunctionsFactory< E, D, d, R, r, rC >::available(), and Dune::XT::Functions::LocalizableFunctionInterface< E, D, d, R, r, rC >::static_id().
Referenced by Dune::XT::Functions::FunctionsFactory< E, D, d, R, r, rC >::create().
template<class E , class D , size_t d, class R , size_t r, size_t rC = 1> static std::unique_ptr<InterfaceType> Dune::XT::Functions::FunctionsFactory< E, D, d, R, r, rC >::create (const Common::Configuration & cfg) inline static
References Dune::XT::Functions::FunctionsFactory< E, D, d, R, r, rC >::create().
template<class E , class D , size_t d, class R , size_t r, size_t rC = 1> static Common::Configuration Dune::XT::Functions::FunctionsFactory< E, D, d, R, r, rC >::default_config (const std::string type, const std::string sub_name = "") inline static
References Dune::XT::Functions::FunctionsFactory< E, D, d, R, r, rC >::available(), and Dune::XT::Functions::LocalizableFunctionInterface< E, D, d, R, r, rC >::static_id().
The documentation for this class was generated from the following file:
functions.hh