Dune::XT::Functions::internal::DerivedLocalFunction< FunctionType, derivative > Class Template Reference
Dune::XT::Functions::internal::DerivedLocalFunction< FunctionType, derivative > Class Template Reference abstract
#include <dune/xt/functions/derived.hh>
Public Types
typedef BaseType::EntityType EntityType
typedef BaseType::DomainType DomainType
typedef BaseType::RangeType RangeType
typedef BaseType::JacobianRangeType JacobianRangeType
typedef BaseType::DomainFieldType DomainFieldType
typedef SelectDerived
< FunctionType, derivative >
::R RangeFieldType
Public Member Functions
DerivedLocalFunction (const FunctionType &func, const EntityType &ent)
virtual size_t order () const overridefinal
virtual void evaluate (const DomainType &xx, RangeType &ret) const overridefinal
virtual void jacobian (const DomainType &xx, JacobianRangeType &ret) const overridefinal
virtual void evaluate (const DomainType &, RangeType &) const =0
virtual void evaluate (const DomainType &xx, std::vector< RangeType > &ret) const overridefinal
RangeType evaluate (const DomainType &xx) const
void evaluate (const Dune::QuadratureRule< DomainFieldType, dimDomain > &quadrature, std::vector< RangeType > &ret)
evaluate at N quadrature points into vector of size >= N
virtual void jacobian (const DomainType &, JacobianRangeType &) const =0
virtual void jacobian (const DomainType &xx, std::vector< JacobianRangeType > &ret) const overridefinal
JacobianRangeType jacobian (const DomainType &xx) const
void jacobian (const Dune::QuadratureRule< DomainFieldType, dimDomain > &quadrature, std::vector< JacobianRangeType > &ret)
jacobian at N quadrature points into vector of size >= N
virtual size_t size () const overridefinal
virtual const EntityType & entity () const
Static Public Attributes
static const size_t dimDomain
static const size_t dimRange
static const size_t dimRangeCols
Protected Member Functions
bool is_a_valid_point (const DomainType &xx) const
Protected Attributes
const EntityType & entity_
Member Typedef Documentation
typedef BaseType::DomainFieldType Dune::XT::Functions::LocalfunctionInterface< SelectDerived< FunctionType, derivative >::E , SelectDerived< FunctionType, derivative >::D , domainDim, SelectDerived< FunctionType, derivative >::R , rangeDim, rangeDimCols >::DomainFieldType inherited
template<class FunctionType , Derivative derivative> typedef BaseType::DomainType Dune::XT::Functions::internal::DerivedLocalFunction< FunctionType, derivative >::DomainType
template<class FunctionType , Derivative derivative> typedef BaseType::EntityType Dune::XT::Functions::internal::DerivedLocalFunction< FunctionType, derivative >::EntityType
template<class FunctionType , Derivative derivative> typedef BaseType::JacobianRangeType Dune::XT::Functions::internal::DerivedLocalFunction< FunctionType, derivative >::JacobianRangeType
typedef SelectDerived< FunctionType, derivative >::R Dune::XT::Functions::LocalfunctionSetInterface< SelectDerived< FunctionType, derivative >::E , SelectDerived< FunctionType, derivative >::D , domainDim, SelectDerived< FunctionType, derivative >::R , rangeDim, rangeDimCols >::RangeFieldType inherited
template<class FunctionType , Derivative derivative> typedef BaseType::RangeType Dune::XT::Functions::internal::DerivedLocalFunction< FunctionType, derivative >::RangeType
Constructor & Destructor Documentation
template<class FunctionType , Derivative derivative> Dune::XT::Functions::internal::DerivedLocalFunction< FunctionType, derivative >::DerivedLocalFunction (const FunctionType & func, const EntityType & ent) inline
Member Function Documentation
virtual const EntityType& Dune::XT::Functions::LocalfunctionSetInterface< SelectDerived< FunctionType, derivative >::E , SelectDerived< FunctionType, derivative >::D , domainDim, SelectDerived< FunctionType, derivative >::R , rangeDim, rangeDimCols >::entity () const inline virtual inherited
template<class FunctionType , Derivative derivative> virtual void Dune::XT::Functions::internal::DerivedLocalFunction< FunctionType, derivative >::evaluate (const DomainType & xx, RangeType & ret) const inline final override virtual
References Dune::XT::Functions::internal::SelectDerived< FunctionType, derivative >::evaluate().
virtual void Dune::XT::Functions::LocalfunctionInterface< SelectDerived< FunctionType, derivative >::E , SelectDerived< FunctionType, derivative >::D , domainDim, SelectDerived< FunctionType, derivative >::R , rangeDim, rangeDimCols >::evaluate (const DomainType & , RangeType &) const pure virtual inherited
virtual void Dune::XT::Functions::LocalfunctionInterface< SelectDerived< FunctionType, derivative >::E , SelectDerived< FunctionType, derivative >::D , domainDim, SelectDerived< FunctionType, derivative >::R , rangeDim, rangeDimCols >::evaluate (const DomainType & xx, std::vector< RangeType > & ret) const inline final override virtual inherited
Implements Dune::XT::Functions::LocalfunctionSetInterface< SelectDerived< FunctionType, derivative >::E, SelectDerived< FunctionType, derivative >::D, domainDim, SelectDerived< FunctionType, derivative >::R, rangeDim, rangeDimCols >.
RangeType Dune::XT::Functions::LocalfunctionInterface< SelectDerived< FunctionType, derivative >::E , SelectDerived< FunctionType, derivative >::D , domainDim, SelectDerived< FunctionType, derivative >::R , rangeDim, rangeDimCols >::evaluate (const DomainType & xx) const inline inherited
void Dune::XT::Functions::LocalfunctionInterface< SelectDerived< FunctionType, derivative >::E , SelectDerived< FunctionType, derivative >::D , domainDim, SelectDerived< FunctionType, derivative >::R , rangeDim, rangeDimCols >::evaluate (const Dune::QuadratureRule< DomainFieldType, dimDomain > & quadrature, std::vector< RangeType > & ret) inline inherited
evaluate at N quadrature points into vector of size >= N
bool Dune::XT::Functions::LocalfunctionSetInterface< SelectDerived< FunctionType, derivative >::E , SelectDerived< FunctionType, derivative >::D , domainDim, SelectDerived< FunctionType, derivative >::R , rangeDim, rangeDimCols >::is_a_valid_point (const DomainType & xx) const inline protected inherited
template<class FunctionType , Derivative derivative> virtual void Dune::XT::Functions::internal::DerivedLocalFunction< FunctionType, derivative >::jacobian (const DomainType & xx, JacobianRangeType & ret) const inline final override virtual
References Dune::XT::Functions::internal::SelectDerived< FunctionType, derivative >::jacobian().
virtual void Dune::XT::Functions::LocalfunctionInterface< SelectDerived< FunctionType, derivative >::E , SelectDerived< FunctionType, derivative >::D , domainDim, SelectDerived< FunctionType, derivative >::R , rangeDim, rangeDimCols >::jacobian (const DomainType & , JacobianRangeType &) const pure virtual inherited
virtual void Dune::XT::Functions::LocalfunctionInterface< SelectDerived< FunctionType, derivative >::E , SelectDerived< FunctionType, derivative >::D , domainDim, SelectDerived< FunctionType, derivative >::R , rangeDim, rangeDimCols >::jacobian (const DomainType & xx, std::vector< JacobianRangeType > & ret) const inline final override virtual inherited
Implements Dune::XT::Functions::LocalfunctionSetInterface< SelectDerived< FunctionType, derivative >::E, SelectDerived< FunctionType, derivative >::D, domainDim, SelectDerived< FunctionType, derivative >::R, rangeDim, rangeDimCols >.
JacobianRangeType Dune::XT::Functions::LocalfunctionInterface< SelectDerived< FunctionType, derivative >::E , SelectDerived< FunctionType, derivative >::D , domainDim, SelectDerived< FunctionType, derivative >::R , rangeDim, rangeDimCols >::jacobian (const DomainType & xx) const inline inherited
void Dune::XT::Functions::LocalfunctionInterface< SelectDerived< FunctionType, derivative >::E , SelectDerived< FunctionType, derivative >::D , domainDim, SelectDerived< FunctionType, derivative >::R , rangeDim, rangeDimCols >::jacobian (const Dune::QuadratureRule< DomainFieldType, dimDomain > & quadrature, std::vector< JacobianRangeType > & ret) inline inherited
jacobian at N quadrature points into vector of size >= N
template<class FunctionType , Derivative derivative> virtual size_t Dune::XT::Functions::internal::DerivedLocalFunction< FunctionType, derivative >::order () const inline final override virtual
Implements Dune::XT::Functions::LocalfunctionSetInterface< SelectDerived< FunctionType, derivative >::E, SelectDerived< FunctionType, derivative >::D, domainDim, SelectDerived< FunctionType, derivative >::R, rangeDim, rangeDimCols >.
References Dune::XT::Functions::internal::SelectDerived< FunctionType, derivative >::order().
virtual size_t Dune::XT::Functions::LocalfunctionInterface< SelectDerived< FunctionType, derivative >::E , SelectDerived< FunctionType, derivative >::D , domainDim, SelectDerived< FunctionType, derivative >::R , rangeDim, rangeDimCols >::size () const inline final override virtual inherited
Implements Dune::XT::Functions::LocalfunctionSetInterface< SelectDerived< FunctionType, derivative >::E, SelectDerived< FunctionType, derivative >::D, domainDim, SelectDerived< FunctionType, derivative >::R, rangeDim, rangeDimCols >.
Member Data Documentation
const size_t Dune::XT::Functions::LocalfunctionInterface< SelectDerived< FunctionType, derivative >::E , SelectDerived< FunctionType, derivative >::D , domainDim, SelectDerived< FunctionType, derivative >::R , rangeDim, rangeDimCols >::dimDomain static inherited
const size_t Dune::XT::Functions::LocalfunctionSetInterface< SelectDerived< FunctionType, derivative >::E , SelectDerived< FunctionType, derivative >::D , domainDim, SelectDerived< FunctionType, derivative >::R , rangeDim, rangeDimCols >::dimRange static inherited
const size_t Dune::XT::Functions::LocalfunctionSetInterface< SelectDerived< FunctionType, derivative >::E , SelectDerived< FunctionType, derivative >::D , domainDim, SelectDerived< FunctionType, derivative >::R , rangeDim, rangeDimCols >::dimRangeCols static inherited
const EntityType& Dune::XT::Functions::LocalfunctionSetInterface< SelectDerived< FunctionType, derivative >::E , SelectDerived< FunctionType, derivative >::D , domainDim, SelectDerived< FunctionType, derivative >::R , rangeDim, rangeDimCols >::entity_ protected inherited
The documentation for this class was generated from the following file:
derived.hh