´´These methods have to be implemented.''
´´These methods have to be implemented.''
Functions
virtual size_t Dune::XT::Functions::LocalfunctionSetInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::size () const =0
virtual size_t Dune::XT::Functions::LocalfunctionSetInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::order () const =0
virtual void Dune::XT::Functions::LocalfunctionSetInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::evaluate (const DomainType &, std::vector< RangeType > &) const =0
virtual void Dune::XT::Functions::LocalfunctionSetInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::jacobian (const DomainType &, std::vector< JacobianRangeType > &) const =0
virtual void Dune::XT::Functions::LocalfunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::evaluate (const DomainType &, RangeType &) const =0
virtual void Dune::XT::Functions::LocalfunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::jacobian (const DomainType &, JacobianRangeType &) const =0
virtual std::unique_ptr
< LocalfunctionType > Dune::XT::Functions::LocalizableFunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::local_function (const EntityType &) const =0
virtual std::unique_ptr
< TimeIndependentFunctionType > Dune::XT::Functions::TimeDependentFunctionInterface< TimeIndependentFunctionImp, TimeFieldImp >::evaluate_at_time (const TimeFieldType t) const =0
Detailed Description
Function Documentation
template<class EntityImp, class DomainFieldImp, size_t domainDim, class RangeFieldImp, size_t rangeDim, size_t rangeDimCols = 1> virtual void Dune::XT::Functions::LocalfunctionSetInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::evaluate (const DomainType & , std::vector< RangeType > &) const pure virtual
Implemented in Dune::XT::Functions::LocalfunctionInterface< SelectCombined< LeftType, RightType, type >::E, SelectCombined< LeftType, RightType, type >::D, SelectCombined< LeftType, RightType, type >::d, SelectCombined< LeftType, RightType, type >::R, SelectCombined< LeftType, RightType, type >::r, SelectCombined< LeftType, RightType, type >::rC >, Dune::XT::Functions::LocalfunctionInterface< SelectDerived< FunctionType, derivative >::E, SelectDerived< FunctionType, derivative >::D, SelectDerived< FunctionType, derivative >::d, SelectDerived< FunctionType, derivative >::R, SelectDerived< FunctionType, derivative >::r, SelectDerived< FunctionType, derivative >::rC >, Dune::XT::Functions::LocalfunctionInterface< EntityType, DomainFieldType, dimDomain, RangeFieldType, dimRange, dimRangeCols >, Dune::XT::Functions::LocalfunctionInterface< E, D, d, R, 1 >, and Dune::XT::Functions::LocalfunctionInterface< E_, D_, d_, R_, 1, 1 >.
Referenced by Dune::XT::Functions::LocalfunctionSetInterface< E_, D_, domainDim, R_, rangeDim, rangeDimCols >::evaluate().
template<class EntityImp, class DomainFieldImp, size_t domainDim, class RangeFieldImp, size_t rangeDim, size_t rangeDimCols = 1> virtual void Dune::XT::Functions::LocalfunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::evaluate (const DomainType & , RangeType &) const pure virtual
Implemented in Dune::XT::Functions::internal::LocalfunctionForGlobalChooser< InnerType, OuterType, OuterGridViewType >::Localfunction, and Dune::XT::Functions::internal::GeneralLocalfunctionChooser< InnerType, OuterType, OuterGridViewType >::Localfunction.
Referenced by Dune::XT::Functions::LocalfunctionInterface< E_, D_, d_, R_, 1, 1 >::evaluate().
template<class TimeIndependentFunctionImp, class TimeFieldImp = double> virtual std::unique_ptr<TimeIndependentFunctionType> Dune::XT::Functions::TimeDependentFunctionInterface< TimeIndependentFunctionImp, TimeFieldImp >::evaluate_at_time (const TimeFieldType t) const pure virtual
Implemented in Dune::XT::Functions::TimeDependentExpressionFunction< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols, TimeFieldImp >.
template<class EntityImp, class DomainFieldImp, size_t domainDim, class RangeFieldImp, size_t rangeDim, size_t rangeDimCols = 1> virtual void Dune::XT::Functions::LocalfunctionSetInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::jacobian (const DomainType & , std::vector< JacobianRangeType > &) const pure virtual
Implemented in Dune::XT::Functions::LocalfunctionInterface< SelectCombined< LeftType, RightType, type >::E, SelectCombined< LeftType, RightType, type >::D, SelectCombined< LeftType, RightType, type >::d, SelectCombined< LeftType, RightType, type >::R, SelectCombined< LeftType, RightType, type >::r, SelectCombined< LeftType, RightType, type >::rC >, Dune::XT::Functions::LocalfunctionInterface< SelectDerived< FunctionType, derivative >::E, SelectDerived< FunctionType, derivative >::D, SelectDerived< FunctionType, derivative >::d, SelectDerived< FunctionType, derivative >::R, SelectDerived< FunctionType, derivative >::r, SelectDerived< FunctionType, derivative >::rC >, Dune::XT::Functions::LocalfunctionInterface< EntityType, DomainFieldType, dimDomain, RangeFieldType, dimRange, dimRangeCols >, Dune::XT::Functions::LocalfunctionInterface< E, D, d, R, 1 >, and Dune::XT::Functions::LocalfunctionInterface< E_, D_, d_, R_, 1, 1 >.
Referenced by Dune::XT::Functions::LocalfunctionSetInterface< E_, D_, domainDim, R_, rangeDim, rangeDimCols >::jacobian().
template<class EntityImp, class DomainFieldImp, size_t domainDim, class RangeFieldImp, size_t rangeDim, size_t rangeDimCols = 1> virtual void Dune::XT::Functions::LocalfunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::jacobian (const DomainType & , JacobianRangeType &) const pure virtual
Implemented in Dune::XT::Functions::internal::LocalfunctionForGlobalChooser< InnerType, OuterType, OuterGridViewType >::Localfunction, and Dune::XT::Functions::internal::GeneralLocalfunctionChooser< InnerType, OuterType, OuterGridViewType >::Localfunction.
Referenced by Dune::XT::Functions::LocalfunctionInterface< E_, D_, d_, R_, 1, 1 >::jacobian().
template<class EntityImp, class DomainFieldImp, size_t domainDim, class RangeFieldImp, size_t rangeDim, size_t rangeDimCols = 1> virtual std::unique_ptr<LocalfunctionType> Dune::XT::Functions::LocalizableFunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::local_function (const EntityType &) const pure virtual
Implemented in Dune::XT::Functions::GlobalFunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, 1 >, Dune::XT::Functions::GlobalFunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >, Dune::XT::Functions::GlobalFunctionInterface< OtherEntityImp, GlobalFunctionImp::DomainFieldType, GlobalFunctionImp::dimDomain, GlobalFunctionImp::RangeFieldType, GlobalFunctionImp::dimRange, GlobalFunctionImp::dimRangeCols >, Dune::XT::Functions::GlobalFunctionInterface< EntityImp, DomainFieldImp, 2, RangeFieldImp, 1 >, Dune::XT::Functions::GlobalFunctionInterface< E, D, d, R, 1, 1 >, Dune::XT::Functions::GlobalFunctionInterface< EntityImp, DomainFieldImp, dim_domain, RangeFieldImp, r, rC >, Dune::XT::Functions::GlobalFunctionInterface< EntityImp, DomainFieldImp, 2, RangeFieldImp, 1, 1 >, Dune::XT::Functions::RandomEllipsoidsFunction< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >, Dune::XT::Functions::CheckerboardFunction< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >, and Dune::XT::Functions::CheckerboardFunction< EntityImp, DomainFieldImp, 2, RangeFieldImp, r, rC >.
Referenced by Dune::XT::Functions::VisualizationAdapterFunction< GridViewType, dimRange, dimRangeCols >::evaluate().
template<class EntityImp, class DomainFieldImp, size_t domainDim, class RangeFieldImp, size_t rangeDim, size_t rangeDimCols = 1> virtual size_t Dune::XT::Functions::LocalfunctionSetInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::order () const pure virtual
Implemented in Dune::XT::Functions::internal::CombinedLocalFunction< LeftType, RightType, type >, Dune::XT::Functions::internal::DerivedLocalFunction< FunctionType, derivative >, Dune::XT::Functions::internal::LocalfunctionForGlobalChooser< InnerType, OuterType, OuterGridViewType >::Localfunction, Dune::XT::Functions::RandomEllipsoidsFunction< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::Localfunction, and Dune::XT::Functions::internal::GeneralLocalfunctionChooser< InnerType, OuterType, OuterGridViewType >::Localfunction.
template<class EntityImp, class DomainFieldImp, size_t domainDim, class RangeFieldImp, size_t rangeDim, size_t rangeDimCols = 1> virtual size_t Dune::XT::Functions::LocalfunctionSetInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::size () const pure virtual
Implemented in Dune::XT::Functions::LocalfunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >, Dune::XT::Functions::LocalfunctionInterface< SelectCombined< LeftType, RightType, type >::E, SelectCombined< LeftType, RightType, type >::D, SelectCombined< LeftType, RightType, type >::d, SelectCombined< LeftType, RightType, type >::R, SelectCombined< LeftType, RightType, type >::r, SelectCombined< LeftType, RightType, type >::rC >, Dune::XT::Functions::LocalfunctionInterface< SelectDerived< FunctionType, derivative >::E, SelectDerived< FunctionType, derivative >::D, SelectDerived< FunctionType, derivative >::d, SelectDerived< FunctionType, derivative >::R, SelectDerived< FunctionType, derivative >::r, SelectDerived< FunctionType, derivative >::rC >, Dune::XT::Functions::LocalfunctionInterface< EntityType, DomainFieldType, dimDomain, RangeFieldType, dimRange, dimRangeCols >, Dune::XT::Functions::LocalfunctionInterface< E, D, d, R, 1 >, and Dune::XT::Functions::LocalfunctionInterface< E_, D_, d_, R_, 1, 1 >.
Referenced by Dune::XT::Functions::LocalfunctionSetInterface< E_, D_, domainDim, R_, rangeDim, rangeDimCols >::evaluate(), and Dune::XT::Functions::LocalfunctionSetInterface< E_, D_, domainDim, R_, rangeDim, rangeDimCols >::jacobian().