´´These methods should be implemented in order to identify the function.''
´´These methods should be implemented in order to identify the function.''
Functions
virtual std::string Dune::XT::Functions::LocalizableFunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::type () const
virtual std::string Dune::XT::Functions::LocalizableFunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::name () const
virtual std::string Dune::XT::Functions::TimeDependentFunctionInterface< TimeIndependentFunctionImp, TimeFieldImp >::type () const
virtual std::string Dune::XT::Functions::TimeDependentFunctionInterface< TimeIndependentFunctionImp, TimeFieldImp >::name () const
Detailed Description
Function Documentation
template<class EntityImp, class DomainFieldImp, size_t domainDim, class RangeFieldImp, size_t rangeDim, size_t rangeDimCols = 1> virtual std::string Dune::XT::Functions::LocalizableFunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::name () const inline virtual
Reimplemented in Dune::XT::Functions::GlobalFunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, 1 >, Dune::XT::Functions::ESV2007::CutoffFunction< DiffusionFactorType, DiffusionTensorType >, Dune::XT::Functions::GlobalFunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >, Dune::XT::Functions::GlobalFunctionInterface< OtherEntityImp, GlobalFunctionImp::DomainFieldType, GlobalFunctionImp::dimDomain, GlobalFunctionImp::RangeFieldType, GlobalFunctionImp::dimRange, GlobalFunctionImp::dimRangeCols >, Dune::XT::Functions::GlobalFunctionInterface< EntityImp, DomainFieldImp, 2, RangeFieldImp, 1 >, Dune::XT::Functions::GlobalFunctionInterface< E, D, d, R, 1, 1 >, Dune::XT::Functions::GlobalFunctionInterface< EntityImp, DomainFieldImp, dim_domain, RangeFieldImp, r, rC >, Dune::XT::Functions::GlobalFunctionInterface< EntityImp, DomainFieldImp, 2, RangeFieldImp, 1, 1 >, Dune::XT::Functions::internal::Combined< LeftType, RightType, comb >, Dune::XT::Functions::internal::Combined< MinuendType, SubtrahendType, internal::Combination::difference >, Dune::XT::Functions::internal::Combined< LeftSummandType, RightSummandType, internal::Combination::product >, Dune::XT::Functions::internal::Combined< LeftSummandType, RightSummandType, internal::Combination::sum >, Dune::XT::Functions::ESV2007::CutoffFunction< DiffusionType, void >, Dune::XT::Functions::CompositionFunction< InnerType, OuterType, OuterGridViewType >, Dune::XT::Functions::internal::Derived< FunctionType, derivative >, Dune::XT::Functions::internal::Derived< FunctionType, internal::Derivative::divergence >, Dune::XT::Functions::RandomEllipsoidsFunction< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >, Dune::XT::Functions::ConstantFunction< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >, Dune::XT::Functions::ExpressionFunction< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >, Dune::XT::Functions::ESV2007::Testcase1ExactSolution< EntityImp, DomainFieldImp, 2, RangeFieldImp, 1, 1 >, Dune::XT::Functions::CheckerboardFunction< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >, Dune::XT::Functions::CheckerboardFunction< EntityImp, DomainFieldImp, 2, RangeFieldImp, r, rC >, Dune::XT::Functions::IndicatorFunction< E, D, d, R, 1 >, Dune::XT::Functions::ReinterpretFunction< SourceType, GridViewType >, Dune::XT::Functions::FlatTopFunction< E, D, d, R, 1, 1 >, Dune::XT::Functions::ESV2007::Testcase1Force< EntityImp, DomainFieldImp, 2, RangeFieldImp, 1, 1 >, and Dune::XT::Functions::GlobalLambdaFunction< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >.
Referenced by Dune::XT::Functions::VisualizationAdapterFunction< GridViewType, dimRange, dimRangeCols >::name(), and Dune::XT::Functions::LocalizableFunctionInterface< DiffusionFactorType::EntityType, DiffusionFactorType::DomainFieldType, DiffusionFactorType::dimDomain, DiffusionFactorType::RangeFieldType, 1, 1 >::report().
template<class TimeIndependentFunctionImp, class TimeFieldImp = double> virtual std::string Dune::XT::Functions::TimeDependentFunctionInterface< TimeIndependentFunctionImp, TimeFieldImp >::name () const inline virtual
Reimplemented in Dune::XT::Functions::TimeDependentExpressionFunction< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols, TimeFieldImp >.
template<class EntityImp, class DomainFieldImp, size_t domainDim, class RangeFieldImp, size_t rangeDim, size_t rangeDimCols = 1> virtual std::string Dune::XT::Functions::LocalizableFunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::type () const inline virtual
Reimplemented in Dune::XT::Functions::GlobalFunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, 1 >, Dune::XT::Functions::GlobalFunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >, Dune::XT::Functions::GlobalFunctionInterface< OtherEntityImp, GlobalFunctionImp::DomainFieldType, GlobalFunctionImp::dimDomain, GlobalFunctionImp::RangeFieldType, GlobalFunctionImp::dimRange, GlobalFunctionImp::dimRangeCols >, Dune::XT::Functions::GlobalFunctionInterface< EntityImp, DomainFieldImp, 2, RangeFieldImp, 1 >, Dune::XT::Functions::GlobalFunctionInterface< E, D, d, R, 1, 1 >, Dune::XT::Functions::GlobalFunctionInterface< EntityImp, DomainFieldImp, dim_domain, RangeFieldImp, r, rC >, Dune::XT::Functions::GlobalFunctionInterface< EntityImp, DomainFieldImp, 2, RangeFieldImp, 1, 1 >, Dune::XT::Functions::internal::Combined< LeftType, RightType, comb >, Dune::XT::Functions::internal::Combined< MinuendType, SubtrahendType, internal::Combination::difference >, Dune::XT::Functions::internal::Combined< LeftSummandType, RightSummandType, internal::Combination::product >, Dune::XT::Functions::internal::Combined< LeftSummandType, RightSummandType, internal::Combination::sum >, Dune::XT::Functions::CompositionFunction< InnerType, OuterType, OuterGridViewType >, Dune::XT::Functions::internal::Derived< FunctionType, derivative >, Dune::XT::Functions::internal::Derived< FunctionType, internal::Derivative::divergence >, Dune::XT::Functions::RandomEllipsoidsFunction< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >, Dune::XT::Functions::ConstantFunction< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >, Dune::XT::Functions::ExpressionFunction< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >, Dune::XT::Functions::ESV2007::Testcase1ExactSolution< EntityImp, DomainFieldImp, 2, RangeFieldImp, 1, 1 >, Dune::XT::Functions::CheckerboardFunction< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >, Dune::XT::Functions::CheckerboardFunction< EntityImp, DomainFieldImp, 2, RangeFieldImp, r, rC >, Dune::XT::Functions::ReinterpretFunction< SourceType, GridViewType >, Dune::XT::Functions::FlatTopFunction< E, D, d, R, 1, 1 >, Dune::XT::Functions::ESV2007::Testcase1Force< EntityImp, DomainFieldImp, 2, RangeFieldImp, 1, 1 >, and Dune::XT::Functions::GlobalLambdaFunction< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >.
Referenced by Dune::XT::Functions::LocalizableFunctionInterface< DiffusionFactorType::EntityType, DiffusionFactorType::DomainFieldType, DiffusionFactorType::dimDomain, DiffusionFactorType::RangeFieldType, 1, 1 >::report().
template<class TimeIndependentFunctionImp, class TimeFieldImp = double> virtual std::string Dune::XT::Functions::TimeDependentFunctionInterface< TimeIndependentFunctionImp, TimeFieldImp >::type () const inline virtual