mathexpr.cc File Reference
mathexpr.cc File Reference
#include "mathexpr.hh"
Functions
char * MidStr (const char *s, int i1, int i2)
char * CopyStr (const char *s)
void InsStr (char *&s, int n, char c)
signed char EqStr (const char *s, const char *s2)
signed char CompStr (const char *s, int n, const char *s2)
void DelStr (char *&s, int n)
int operator== (const ROperation &op, const double v)
int operator== (const ROperation &op1, const ROperation &op2)
int operator!= (const ROperation &op1, const ROperation &op2)
ROperation operator, (const ROperation &op1, const ROperation &op2)
ROperation operator+ (const ROperation &op1, const ROperation &op2)
ROperation operator- (const ROperation &op1, const ROperation &op2)
ROperation operator* (const ROperation &op1, const ROperation &op2)
ROperation operator/ (const ROperation &op1, const ROperation &op2)
ROperation operator^ (const ROperation &op1, const ROperation &op2)
ROperation sqrt (const ROperation &op)
ROperation abs (const ROperation &op)
ROperation sin (const ROperation &op)
ROperation cos (const ROperation &op)
ROperation tan (const ROperation &op)
ROperation log (const ROperation &op)
ROperation exp (const ROperation &op)
ROperation acos (const ROperation &op)
ROperation asin (const ROperation &op)
ROperation atan (const ROperation &op)
ROperation ApplyOperator (int n, ROperation **pops, ROperation(*func)(const ROperation &, const ROperation &))
void SupprSpaces (char *&s)
signed char IsNumeric (char c)
signed char IsTNumeric (char *s)
int SearchCorOpenbracket (char *s, int n)
int SearchCorClosebracket (char *s, int n)
int SearchOperator (char *s, ROperator op)
void SimplifyStr (char *&s)
int max (int a, int b)
int IsVar (const char *s, int n, int nvar, PRVar *ppvar)
int IsFunction (const char *s, int n)
int IsFunction (const char *s, int n, int nfunc, PRFunction *ppfunc)
signed char IsFunction (ROperator op)
void IsolateVars (char *&s, int nvar, PRVar *ppvar, int nfunc, PRFunction *ppfunc)
void IsolateNumbers (char *&s, int nvar, RVar **ppvar, int nfunc, RFunction **ppfunc)
int operator== (const RVar &var1, const RVar &var2)
int operator== (const RFunction &f1, const RFunction &f2)
char * ValToStr (double x)
void Addition (double *&p)
void Soustraction (double *&p)
void Multiplication (double *&p)
void Division (double *&p)
void Puissance (double *&p)
void RacineN (double *&p)
void Puiss10 (double *&p)
void ArcTangente2 (double *&p)
void NextVal (double *&)
void RFunc (double *&)
void JuxtF (double *&)
void Absolu (double *&p)
void Oppose (double *&p)
void ArcSinus (double *&p)
void ArcCosinus (double *&p)
void ArcTangente (double *&p)
void Logarithme (double *&p)
void Exponentielle (double *&p)
void Sinus (double *&p)
void Tangente (double *&p)
void Cosinus (double *&p)
void Racine (double *&p)
void FonctionError (double *&p)
void ApplyRFunc (PRFunction rf, double *&p)
void BCDouble (pfoncld *&pf, pfoncld *pf1, pfoncld *pf2, double **&pv, double **pv1, double **pv2, double *&pp, double *pp1, double *pp2, RFunction **&prf, RFunction **prf1, RFunction **prf2, pfoncld f)
void BCSimple (pfoncld *&pf, pfoncld *pf1, double **&pv, double **pv1, double *&pp, double *pp1, RFunction **&prf, RFunction **prf1, pfoncld f)
void BCFun (pfoncld *&pf, pfoncld *pf1, double **&pv, double **pv1, double *&pp, double *pp1, RFunction **&prf, RFunction **prf1, PRFunction rf)
Variables
const double sqrtmaxfloat =sqrt(DBL_MAX)
const double sqrtminfloat =sqrt(DBL_MIN)
const double inveps =.1/DBL_EPSILON
Function Documentation
ROperation abs (const ROperation & op)
References Abs, ROperation::mmb2, and ROperation::op.
Referenced by Dune::XT::Functions::ExpressionFunction< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::evaluate().
void Absolu (double *& p)
References ErrVal, and fabsl.
ROperation acos (const ROperation & op)
References Acos, ROperation::mmb2, and ROperation::op.
void Addition (double *& p)
References ErrVal, fabsl, and sqrtmaxfloat.
ROperation ApplyOperator (int n, ROperation ** pops, ROperation(*)(const ROperation &, const ROperation &) func)
References ErrVal.
void ApplyRFunc (PRFunction rf, double *& p) inline
References RFunction::nvars, and RFunction::Val().
Referenced by ROperation::Val().
void ArcCosinus (double *& p)
References acosl, ErrVal, and fabsl.
void ArcSinus (double *& p)
References asinl, ErrVal, and fabsl.
void ArcTangente (double *& p)
References atanl, and ErrVal.
void ArcTangente2 (double *& p)
References ErrVal, fabsl, and inveps.
ROperation asin (const ROperation & op)
References Asin, ROperation::mmb2, and ROperation::op.
ROperation atan (const ROperation & op)
References Atan, ROperation::mmb2, and ROperation::op.
void BCDouble (pfoncld *& pf, pfoncld * pf1, pfoncld * pf2, double **& pv, double ** pv1, double ** pv2, double *& pp, double * pp1, double * pp2, RFunction **& prf, RFunction ** prf1, RFunction ** prf2, pfoncld f)
References ErrVal.
void BCFun (pfoncld *& pf, pfoncld * pf1, double **& pv, double ** pv1, double *& pp, double * pp1, RFunction **& prf, RFunction ** prf1, PRFunction rf)
References ErrVal, and RFunc().
void BCSimple (pfoncld *& pf, pfoncld * pf1, double **& pv, double ** pv1, double *& pp, double * pp1, RFunction **& prf, RFunction ** prf1, pfoncld f)
References ErrVal.
signed char CompStr (const char * s, int n, const char * s2)
Referenced by IsFunction(), IsolateVars(), IsVar(), and ROperation::ROperation().
char* CopyStr (const char * s)
Referenced by ROperation::Expr(), RFunction::operator=(), RFunction::RFunction(), ROperation::ROperation(), RVar::RVar(), RFunction::SetName(), and SimplifyStr().
ROperation cos (const ROperation & op)
References Cos, ROperation::mmb2, and ROperation::op.
Referenced by Dune::XT::Functions::ESV2007::Testcase1Force< EntityImp, DomainFieldImp, 2, RangeFieldImp, 1, 1 >::evaluate(), Dune::XT::Functions::ESV2007::Testcase1ExactSolution< EntityImp, DomainFieldImp, 2, RangeFieldImp, 1, 1 >::evaluate(), Dune::XT::Functions::ESV2007::Testcase1Force< EntityImp, DomainFieldImp, 2, RangeFieldImp, 1, 1 >::jacobian(), and Dune::XT::Functions::ESV2007::Testcase1ExactSolution< EntityImp, DomainFieldImp, 2, RangeFieldImp, 1, 1 >::jacobian().
void Cosinus (double *& p)
References cosl, ErrVal, fabsl, and inveps.
void DelStr (char *& s, int n)
Referenced by SupprSpaces().
void Division (double *& p)
References ErrVal, fabsl, sqrtmaxfloat, and sqrtminfloat.
signed char EqStr (const char * s, const char * s2)
Referenced by ROperation::ContainVar(), operator==(), and ROperation::ROperation().
ROperation exp (const ROperation & op)
References Exp, ROperation::mmb2, and ROperation::op.
void Exponentielle (double *& p)
References ErrVal, and expl.
void FonctionError (double *& p)
References ErrVal.
void InsStr (char *& s, int n, char c)
Referenced by IsolateNumbers(), IsolateVars(), and ROperation::ROperation().
int IsFunction (const char * s, int n)
References CompStr().
Referenced by ROperation::Expr(), IsFunction(), IsolateNumbers(), IsolateVars(), and ROperation::ROperation().
int IsFunction (const char * s, int n, int nfunc, PRFunction * ppfunc)
References CompStr(), IsFunction(), and max().
signed char IsFunction (ROperator op)
References Abs, Acos, Asin, Atan, Cos, Exp, Ln, Opp, Sin, Sqrt, and Tg.
signed char IsNumeric (char c)
Referenced by IsolateNumbers(), and IsTNumeric().
void IsolateNumbers (char *& s, int nvar, RVar ** ppvar, int nfunc, RFunction ** ppfunc)
References InsStr(), IsFunction(), IsNumeric(), IsVar(), max(), and SearchCorOpenbracket().
Referenced by ROperation::ROperation().
void IsolateVars (char *& s, int nvar, PRVar * ppvar, int nfunc, PRFunction * ppfunc)
References CompStr(), InsStr(), IsFunction(), IsVar(), and SearchCorOpenbracket().
Referenced by ROperation::ROperation().
signed char IsTNumeric (char * s)
References IsNumeric().
Referenced by ROperation::ROperation().
int IsVar (const char * s, int n, int nvar, PRVar * ppvar)
References CompStr(), and max().
Referenced by IsolateNumbers(), IsolateVars(), and ROperation::ROperation().
void JuxtF (double *&)
ROperation log (const ROperation & op)
References Ln, ROperation::mmb2, and ROperation::op.
void Logarithme (double *& p)
References ErrVal, and logl.
int max (int a, int b)
Referenced by Dune::XT::Functions::ExpressionFunction< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::evaluate(), IsFunction(), IsolateNumbers(), and IsVar().
char* MidStr (const char * s, int i1, int i2)
Referenced by ROperation::ROperation().
void Multiplication (double *& p)
References ErrVal, fabsl, sqrtmaxfloat, and sqrtminfloat.
void NextVal (double *&)
Referenced by ROperation::Val().
int operator!= (const ROperation & op1, const ROperation & op2)
References Fun, ROperation::mmb1, ROperation::mmb2, Num, ROperation::op, ROperation::pfunc, ROperation::pvar, ROperation::ValC, and Var.
ROperation operator* (const ROperation & op1, const ROperation & op2)
References ROperation::mmb1, ROperation::mmb2, Mult, Num, ROperation::op, Opp, and ROperation::ValC.
ROperation operator+ (const ROperation & op1, const ROperation & op2)
References Add, ROperation::mmb2, Num, ROperation::op, Opp, and ROperation::ValC.
ROperation operator, (const ROperation & op1, const ROperation & op2)
References Juxt, ROperation::mmb1, ROperation::mmb2, and ROperation::op.
ROperation operator- (const ROperation & op1, const ROperation & op2)
References ROperation::mmb2, Num, ROperation::op, Opp, Sub, and ROperation::ValC.
ROperation operator/ (const ROperation & op1, const ROperation & op2)
References Div, ErrVal, ROperation::mmb1, ROperation::mmb2, Num, ROperation::op, Opp, and ROperation::ValC.
int operator== (const ROperation & op, const double v)
References Num, ROperation::op, and ROperation::ValC.
int operator== (const ROperation & op1, const ROperation & op2)
References Fun, ROperation::mmb1, ROperation::mmb2, Num, ROperation::op, ROperation::pfunc, ROperation::pvar, ROperation::ValC, and Var.
int operator== (const RVar & var1, const RVar & var2)
References EqStr(), RVar::name, and RVar::pval.
int operator== (const RFunction & f1, const RFunction & f2)
References EqStr(), RFunction::name, RFunction::nvars, RFunction::op, RFunction::ppvar, and RFunction::type.
ROperation operator^ (const ROperation & op1, const ROperation & op2)
References ROperation::mmb1, ROperation::mmb2, ROperation::op, and Pow.
void Oppose (double *& p)
References ErrVal.
void Puiss10 (double *& p)
References ErrVal, fabsl, pow10l, and sqrtmaxfloat.
void Puissance (double *& p)
References ErrVal, fabsl, fmodl, logl, and powl.
void Racine (double *& p)
References ErrVal, and sqrtl.
void RacineN (double *& p)
References ErrVal, fabsl, fmodl, logl, and powl.
void RFunc (double *&)
Referenced by BCFun(), and ROperation::Val().
int SearchCorClosebracket (char * s, int n)
Referenced by SearchOperator().
int SearchCorOpenbracket (char * s, int n)
Referenced by IsolateNumbers(), IsolateVars(), ROperation::ROperation(), and SimplifyStr().
int SearchOperator (char * s, ROperator op)
References Add, Div, E10, ErrOp, Juxt, Mult, NthRoot, Num, Pow, SearchCorClosebracket(), Sub, and Var.
Referenced by ROperation::ROperation().
void SimplifyStr (char *& s)
References CopyStr(), and SearchCorOpenbracket().
Referenced by ROperation::ROperation().
ROperation sin (const ROperation & op)
References ROperation::mmb2, ROperation::op, and Sin.
Referenced by Dune::XT::Functions::ESV2007::Testcase1Force< EntityImp, DomainFieldImp, 2, RangeFieldImp, 1, 1 >::jacobian(), and Dune::XT::Functions::ESV2007::Testcase1ExactSolution< EntityImp, DomainFieldImp, 2, RangeFieldImp, 1, 1 >::jacobian().
void Sinus (double *& p)
References ErrVal, fabsl, inveps, and sinl.
void Soustraction (double *& p)
References ErrVal, fabsl, and sqrtmaxfloat.
ROperation sqrt (const ROperation & op)
References ROperation::mmb2, ROperation::op, and Sqrt.
void SupprSpaces (char *& s)
References DelStr().
Referenced by ROperation::ROperation().
ROperation tan (const ROperation & op)
References ROperation::mmb2, ROperation::op, and Tg.
void Tangente (double *& p)
References ErrVal, fabsl, inveps, and tanl.
char* ValToStr (double x)
Referenced by ROperation::Expr().
Variable Documentation
const double inveps =.1/DBL_EPSILON
Referenced by ArcTangente2(), Cosinus(), Sinus(), and Tangente().
const double sqrtmaxfloat =sqrt(DBL_MAX)
Referenced by Addition(), Division(), Multiplication(), Puiss10(), and Soustraction().
const double sqrtminfloat =sqrt(DBL_MIN)
Referenced by Division(), and Multiplication().