ROperation Class Reference
ROperation Class Reference
#include <dune/xt/functions/expression/mathexpr.hh>
Public Member Functions
ROperation ()
ROperation (const ROperation &)
ROperation (double)
ROperation (const RVar &)
ROperation (const char *sp, int nvarp=0, PRVar *ppvarp=NULL, int nfuncp=0, PRFunction *ppfuncp=NULL)
~ROperation ()
double Val () const
signed char ContainVar (const RVar &) const
signed char ContainFunc (const RFunction &) const
signed char ContainFuncNoRec (const RFunction &) const
ROperation NthMember (int) const
int NMembers () const
signed char HasError (const ROperation *=NULL) const
ROperation & operator= (const ROperation &)
ROperation operator+ () const
ROperation operator- () const
ROperation Diff (const RVar &) const
char * Expr () const
ROperation Substitute (const RVar &, const ROperation &) const
Public Attributes
ROperator op
PROperation mmb1
PROperation mmb2
double ValC
const RVar * pvar
double * pvarval
RFunction * pfunc
Friends
int operator== (const ROperation &, const double)
int operator== (const ROperation &, const ROperation &)
int operator!= (const ROperation &, const ROperation &)
ROperation operator, (const ROperation &, const ROperation &)
ROperation operator+ (const ROperation &, const ROperation &)
ROperation operator- (const ROperation &, const ROperation &)
ROperation operator* (const ROperation &, const ROperation &)
ROperation operator/ (const ROperation &, const ROperation &)
ROperation operator^ (const ROperation &, const ROperation &)
ROperation sqrt (const ROperation &)
ROperation abs (const ROperation &)
ROperation sin (const ROperation &)
ROperation cos (const ROperation &)
ROperation tan (const ROperation &)
ROperation log (const ROperation &)
ROperation exp (const ROperation &)
ROperation acos (const ROperation &)
ROperation asin (const ROperation &)
ROperation atan (const ROperation &)
ROperation ApplyOperator (int, ROperation **, ROperation(*)(const ROperation &, const ROperation &))
Constructor & Destructor Documentation
ROperation::ROperation ()
References ErrOp, ErrVal, mmb1, mmb2, op, pfunc, pvar, pvarval, and ValC.
Referenced by Diff(), operator-(), operator=(), and ROperation().
ROperation::ROperation (const ROperation & ROp)
References mmb1, mmb2, op, pfunc, pvar, pvarval, ROperation(), and ValC.
ROperation::ROperation (double x)
References ErrOp, ErrVal, mmb1, mmb2, Num, op, Opp, pfunc, pvar, pvarval, ROperation(), and ValC.
ROperation::ROperation (const RVar & varp)
References ErrVal, mmb1, mmb2, op, pfunc, RVar::pval, pvar, pvarval, ValC, and Var.
ROperation::ROperation (const char * sp, int nvarp = 0, PRVar * ppvarp = NULL, int nfuncp = 0, PRFunction * ppfuncp = NULL)
References Abs, Acos, Add, Asin, Atan, CompStr(), CopyStr(), Cos, Div, E10, EqStr(), ErrOp, ErrVal, Exp, Fun, InsStr(), IsFunction(), IsolateNumbers(), IsolateVars(), IsTNumeric(), IsVar(), Juxt, Ln, MidStr(), mmb1, mmb2, Mult, NMembers(), NthRoot, Num, RFunction::nvars, op, Opp, pfunc, Pow, RVar::pval, pvar, pvarval, ROperation(), SearchCorOpenbracket(), SearchOperator(), SimplifyStr(), Sin, Sqrt, Sub, SupprSpaces(), Tg, ValC, and Var.
ROperation::~ROperation ()
Member Function Documentation
signed char ROperation::ContainFunc (const RFunction & func) const
References Fun.
signed char ROperation::ContainFuncNoRec (const RFunction & func) const
References Fun.
signed char ROperation::ContainVar (const RVar & varp) const
References ContainVar(), EqStr(), mmb1, mmb2, RVar::name, op, RVar::pval, pvar, and Var.
Referenced by ContainVar(), and Diff().
ROperation ROperation::Diff (const RVar & var) const
References Abs, Acos, Add, ApplyOperator, Asin, Atan, ContainVar(), Cos, cos, Diff(), Div, E10, ErrVal, Exp, Fun, Juxt, Ln, log, mmb1, mmb2, Mult, NMembers(), NthMember(), NthRoot, RFunction::nvars, op, RFunction::op, Opp, pfunc, Pow, RFunction::ppvar, ROperation(), Sin, sin, Sqrt, sqrt, Sub, Substitute(), Tg, RFunction::type, and Var.
Referenced by Diff().
char * ROperation::Expr () const
References Abs, Acos, Add, Asin, Atan, CopyStr(), Cos, Div, E10, Exp, Expr(), Fun, IsFunction(), Juxt, Ln, mmb1, mmb2, Mult, RVar::name, RFunction::name, NthRoot, Num, op, Opp, pfunc, Pow, pvar, Sin, Sqrt, Sub, Tg, ValC, ValToStr(), and Var.
Referenced by Expr().
signed char ROperation::HasError (const ROperation * pop = NULL) const
References ErrOp, Fun, HasError(), mmb1, mmb2, op, RFunction::op, pfunc, and RFunction::type.
Referenced by HasError().
int ROperation::NMembers () const
References Fun, Juxt, mmb2, NMembers(), op, RFunction::op, pfunc, and RFunction::type.
Referenced by Diff(), NMembers(), NthMember(), and ROperation().
ROperation ROperation::NthMember (int n) const
References ErrVal, Fun, Juxt, mmb1, mmb2, RFunction::name, NMembers(), NthMember(), RFunction::nvars, op, RFunction::op, pfunc, RFunction::ppvar, RFunction::SetName(), and RFunction::type.
Referenced by Diff(), and NthMember().
ROperation ROperation::operator+ () const
ROperation ROperation::operator- () const
References mmb2, Num, op, Opp, ROperation(), and ValC.
ROperation & ROperation::operator= (const ROperation & ROp)
References mmb1, mmb2, op, pfunc, pvar, pvarval, ROperation(), and ValC.
ROperation ROperation::Substitute (const RVar & var, const ROperation & rop) const
References mmb1, mmb2, op, pfunc, pvar, pvarval, ValC, and Var.
Referenced by Diff().
double ROperation::Val () const
References ApplyRFunc(), NextVal(), and RFunc().
Referenced by RFunction::Val().
Friends And Related Function Documentation
ROperation abs (const ROperation & op) friend
ROperation acos (const ROperation & op) friend
ROperation ApplyOperator (int n, ROperation ** pops, ROperation(*)(const ROperation &, const ROperation &) func) friend
Referenced by Diff().
ROperation asin (const ROperation & op) friend
ROperation atan (const ROperation & op) friend
ROperation cos (const ROperation & op) friend
Referenced by Diff().
ROperation exp (const ROperation & op) friend
ROperation log (const ROperation & op) friend
Referenced by Diff().
int operator!= (const ROperation & op1, const ROperation & op2) friend
ROperation operator* (const ROperation & op1, const ROperation & op2) friend
ROperation operator+ (const ROperation & op1, const ROperation & op2) friend
ROperation operator, (const ROperation & op1, const ROperation & op2) friend
ROperation operator- (const ROperation & op1, const ROperation & op2) friend
ROperation operator/ (const ROperation & op1, const ROperation & op2) friend
int operator== (const ROperation & op, const double v) friend
int operator== (const ROperation & op1, const ROperation & op2) friend
ROperation operator^ (const ROperation & op1, const ROperation & op2) friend
ROperation sin (const ROperation & op) friend
Referenced by Diff().
ROperation sqrt (const ROperation & op) friend
Referenced by Diff().
ROperation tan (const ROperation & op) friend
Member Data Documentation
PROperation ROperation::mmb1
Referenced by ContainVar(), Diff(), Expr(), HasError(), NthMember(), operator!=(), operator*(), operator,(), operator/(), operator=(), operator==(), operator^(), ROperation(), and Substitute().
PROperation ROperation::mmb2
Referenced by abs(), acos(), asin(), atan(), ContainVar(), cos(), Diff(), exp(), Expr(), HasError(), log(), NMembers(), NthMember(), operator!=(), RFunction::operator()(), operator*(), operator+(), operator,(), operator-(), operator-(), operator/(), operator=(), operator==(), operator^(), ROperation(), sin(), sqrt(), Substitute(), and tan().
ROperator ROperation::op
Referenced by abs(), acos(), asin(), atan(), ContainVar(), cos(), Diff(), exp(), Expr(), HasError(), log(), NMembers(), NthMember(), operator!=(), RFunction::operator()(), operator*(), operator+(), operator,(), operator-(), operator-(), operator/(), operator=(), operator==(), operator^(), ROperation(), sin(), sqrt(), Substitute(), and tan().
RFunction* ROperation::pfunc
Referenced by Diff(), Expr(), HasError(), NMembers(), NthMember(), operator!=(), RFunction::operator()(), operator=(), operator==(), ROperation(), and Substitute().
const RVar* ROperation::pvar
Referenced by ContainVar(), Expr(), operator!=(), operator=(), operator==(), ROperation(), and Substitute().
double* ROperation::pvarval
Referenced by operator=(), ROperation(), and Substitute().
double ROperation::ValC
Referenced by Expr(), operator!=(), operator*(), operator+(), operator-(), operator-(), operator/(), operator=(), operator==(), ROperation(), and Substitute().
The documentation for this class was generated from the following files:
mathexpr.hh
mathexpr.cc