Dune::GDT::DefaultProductMapper< GridViewImp, MapperTypes > Class Template Reference
Dune::GDT::DefaultProductMapper< GridViewImp, MapperTypes > Class Template Reference
#include <dune/gdt/spaces/mapper/product.hh>
Public Types
typedef
internal::DefaultProductMapperTraits
< GridViewImp, MapperTypes...> Traits
typedef Traits::GridViewType GridViewType
typedef Traits::EntityType EntityType
typedef
internal::DefaultProductMapperTraits
< GridViewImp, MapperTypes...>
::derived_type derived_type
typedef
internal::DefaultProductMapperTraits
< GridViewImp, MapperTypes...>
::BackendType BackendType
Public Member Functions
DefaultProductMapper (const GridViewType &grid_view, const MapperTypes &...mappers)
DefaultProductMapper (const GridViewType &grid_view, const std::tuple< MapperTypes...> &mappers)
template<class... SpaceTypes>
DefaultProductMapper (const std::tuple< SpaceTypes...> &spaces)
size_t numDofs (const size_t factor_index, const EntityType &entity) const
size_t maxNumDofs (const size_t factor_index) const
void globalIndices (const size_t factor_index, const EntityType &entity, Dune::DynamicVector< size_t > &ret) const
size_t mapToGlobal (const size_t factor_index, const EntityType &entity, const size_t &local_index_in_factor) const
size_t mapToLocal (const size_t factor_index, const EntityType &entity, const size_t &local_index_in_factor) const
const BackendType & backend () const
size_t size (const size_t factor_index) const
size_t size () const
size_t numDofs (const EntityType &entity) const
size_t maxNumDofs () const
void globalIndices (const EntityType &entity, Dune::DynamicVector< size_t > &ret) const
size_t mapToGlobal (const EntityType &entity, const size_t &localIndex) const
Dune::DynamicVector< size_t > globalIndices (const size_t factor_index, const EntityType &entity) const
Dune::DynamicVector< size_t > globalIndices (const typename internal::DefaultProductMapperTraits< GridViewImp, MapperTypes...>::EntityType &entity) const
Static Public Attributes
static const size_t dimRange = Traits::dimRange
Member Typedef Documentation
typedef internal::DefaultProductMapperTraits< GridViewImp, MapperTypes...> ::BackendType Dune::GDT::MapperInterface< internal::DefaultProductMapperTraits< GridViewImp, MapperTypes...> >::BackendType inherited
typedef internal::DefaultProductMapperTraits< GridViewImp, MapperTypes...> ::derived_type Dune::GDT::MapperInterface< internal::DefaultProductMapperTraits< GridViewImp, MapperTypes...> >::derived_type inherited
template<class GridViewImp , class... MapperTypes> typedef Traits::EntityType Dune::GDT::MapperInterface< Traits >::EntityType
template<class GridViewImp , class... MapperTypes> typedef Traits::GridViewType Dune::GDT::DefaultProductMapper< GridViewImp, MapperTypes >::GridViewType
template<class GridViewImp , class... MapperTypes> typedef internal::DefaultProductMapperTraits<GridViewImp, MapperTypes...> Dune::GDT::DefaultProductMapper< GridViewImp, MapperTypes >::Traits
Constructor & Destructor Documentation
template<class GridViewImp , class... MapperTypes> Dune::GDT::DefaultProductMapper< GridViewImp, MapperTypes >::DefaultProductMapper (const GridViewType & grid_view, const MapperTypes &... mappers) inline
template<class GridViewImp , class... MapperTypes> Dune::GDT::DefaultProductMapper< GridViewImp, MapperTypes >::DefaultProductMapper (const GridViewType & grid_view, const std::tuple< MapperTypes...> & mappers) inline
template<class GridViewImp , class... MapperTypes> template<class... SpaceTypes> Dune::GDT::DefaultProductMapper< GridViewImp, MapperTypes >::DefaultProductMapper (const std::tuple< SpaceTypes...> & spaces) inline
Member Function Documentation
template<class GridViewImp , class... MapperTypes> const BackendType& Dune::GDT::DefaultProductMapper< GridViewImp, MapperTypes >::backend () const inline
Dune::DynamicVector<size_t> Dune::GDT::MapperInterface< internal::DefaultProductMapperTraits< GridViewImp, MapperTypes...> >::globalIndices (const typename internal::DefaultProductMapperTraits< GridViewImp, MapperTypes...> ::EntityType & entity) const inline inherited
Dune::DynamicVector<size_t> Dune::GDT::ProductMapperInterface< internal::DefaultProductMapperTraits< GridViewImp, MapperTypes...> >::globalIndices (const size_t factor_index, const EntityType & entity) const inline inherited
template<class GridViewImp , class... MapperTypes> void Dune::GDT::DefaultProductMapper< GridViewImp, MapperTypes >::globalIndices (const size_t factor_index, const EntityType & entity, Dune::DynamicVector< size_t > & ret) const inline
References Dune::GDT::DefaultProductMapper< GridViewImp, MapperTypes >::mapToGlobal(), and Dune::GDT::DefaultProductMapper< GridViewImp, MapperTypes >::numDofs().
template<class GridViewImp , class... MapperTypes> void Dune::GDT::DefaultProductMapper< GridViewImp, MapperTypes >::globalIndices (const EntityType & entity, Dune::DynamicVector< size_t > & ret) const inline
References Dune::GDT::DefaultProductMapper< GridViewImp, MapperTypes >::mapToGlobal(), and Dune::GDT::DefaultProductMapper< GridViewImp, MapperTypes >::numDofs().
template<class GridViewImp , class... MapperTypes> size_t Dune::GDT::DefaultProductMapper< GridViewImp, MapperTypes >::mapToGlobal (const size_t factor_index, const EntityType & entity, const size_t & local_index_in_factor) const inline
References Dune::GDT::DefaultProductMapper< GridViewImp, MapperTypes >::size().
Referenced by Dune::GDT::DefaultProductMapper< GridViewImp, MapperTypes >::globalIndices(), and Dune::GDT::DefaultProductMapper< GridViewImp, MapperTypes >::mapToGlobal().
template<class GridViewImp , class... MapperTypes> size_t Dune::GDT::DefaultProductMapper< GridViewImp, MapperTypes >::mapToGlobal (const EntityType & entity, const size_t & localIndex) const inline
References Dune::GDT::DefaultProductMapper< GridViewImp, MapperTypes >::mapToGlobal(), and Dune::GDT::DefaultProductMapper< GridViewImp, MapperTypes >::numDofs().
template<class GridViewImp , class... MapperTypes> size_t Dune::GDT::DefaultProductMapper< GridViewImp, MapperTypes >::mapToLocal (const size_t factor_index, const EntityType & entity, const size_t & local_index_in_factor) const inline
References Dune::GDT::DefaultProductMapper< GridViewImp, MapperTypes >::numDofs().
template<class GridViewImp , class... MapperTypes> size_t Dune::GDT::DefaultProductMapper< GridViewImp, MapperTypes >::maxNumDofs (const size_t factor_index) const inline
template<class GridViewImp , class... MapperTypes> size_t Dune::GDT::DefaultProductMapper< GridViewImp, MapperTypes >::maxNumDofs () const inline
References Dune::GDT::DefaultProductMapper< GridViewImp, MapperTypes >::numDofs().
template<class GridViewImp , class... MapperTypes> size_t Dune::GDT::DefaultProductMapper< GridViewImp, MapperTypes >::numDofs (const size_t factor_index, const EntityType & entity) const inline
References Dune::GDT::internal::DynamicTupleGetter< I >::numDofs().
Referenced by Dune::GDT::DefaultProductMapper< GridViewImp, MapperTypes >::globalIndices(), Dune::GDT::DefaultProductMapper< GridViewImp, MapperTypes >::mapToGlobal(), Dune::GDT::DefaultProductMapper< GridViewImp, MapperTypes >::mapToLocal(), Dune::GDT::DefaultProductMapper< GridViewImp, MapperTypes >::maxNumDofs(), and Dune::GDT::DefaultProductMapper< GridViewImp, MapperTypes >::numDofs().
template<class GridViewImp , class... MapperTypes> size_t Dune::GDT::DefaultProductMapper< GridViewImp, MapperTypes >::numDofs (const EntityType & entity) const inline
References Dune::GDT::DefaultProductMapper< GridViewImp, MapperTypes >::numDofs().
template<class GridViewImp , class... MapperTypes> size_t Dune::GDT::DefaultProductMapper< GridViewImp, MapperTypes >::size (const size_t factor_index) const inline
template<class GridViewImp , class... MapperTypes> size_t Dune::GDT::DefaultProductMapper< GridViewImp, MapperTypes >::size () const inline
Referenced by Dune::GDT::DefaultProductMapper< GridViewImp, MapperTypes >::mapToGlobal().
Member Data Documentation
template<class GridViewImp , class... MapperTypes> const size_t Dune::GDT::DefaultProductMapper< GridViewImp, MapperTypes >::dimRange = Traits::dimRange static
The documentation for this class was generated from the following file:
spaces/mapper/product.hh