Dune::GDT::DiffusiveFluxReconstructionOperator< GridViewType, DiffusionFactorType, DiffusionTensorType > Class Template Reference
Dune::GDT::DiffusiveFluxReconstructionOperator< GridViewType, DiffusionFactorType, DiffusionTensorType > Class Template Reference
#include <dune/gdt/operators/fluxreconstruction.hh>
Public Types
typedef GridViewType::template
Codim< 0 >::Entity EntityType
typedef GridViewType::ctype DomainFieldType
typedef
DiffusionFactorType::RangeFieldType FieldType
typedef
DiffusionFactorType::DomainType DomainType
Public Member Functions
DiffusiveFluxReconstructionOperator (const GridViewType &grid_view, const DiffusionFactorType &diffusion_factor, const DiffusionTensorType &diffusion_tensor, const size_t over_integrate=0)
template<class GV , class V >
void apply (const Stuff::LocalizableFunctionInterface< EntityType, DomainFieldType, dimDomain, FieldType, 1 > &source, DiscreteFunction< DunePdelabRtSpaceWrapper< GV, 0, FieldType, dimDomain >, V > &range) const
Static Public Attributes
static const size_t dimDomain = GridViewType::dimension
Member Typedef Documentation
template<class GridViewType, class DiffusionFactorType, class DiffusionTensorType = void> typedef GridViewType::ctype Dune::GDT::DiffusiveFluxReconstructionOperator< GridViewType, DiffusionFactorType, DiffusionTensorType >::DomainFieldType
template<class GridViewType, class DiffusionFactorType, class DiffusionTensorType = void> typedef DiffusionFactorType::DomainType Dune::GDT::DiffusiveFluxReconstructionOperator< GridViewType, DiffusionFactorType, DiffusionTensorType >::DomainType
template<class GridViewType, class DiffusionFactorType, class DiffusionTensorType = void> typedef GridViewType::template Codim<0>::Entity Dune::GDT::DiffusiveFluxReconstructionOperator< GridViewType, DiffusionFactorType, DiffusionTensorType >::EntityType
template<class GridViewType, class DiffusionFactorType, class DiffusionTensorType = void> typedef DiffusionFactorType::RangeFieldType Dune::GDT::DiffusiveFluxReconstructionOperator< GridViewType, DiffusionFactorType, DiffusionTensorType >::FieldType
Constructor & Destructor Documentation
template<class GridViewType, class DiffusionFactorType, class DiffusionTensorType = void> Dune::GDT::DiffusiveFluxReconstructionOperator< GridViewType, DiffusionFactorType, DiffusionTensorType >::DiffusiveFluxReconstructionOperator (const GridViewType & grid_view, const DiffusionFactorType & diffusion_factor, const DiffusionTensorType & diffusion_tensor, const size_t over_integrate = 0) inline
Member Function Documentation
template<class GridViewType, class DiffusionFactorType, class DiffusionTensorType = void> template<class GV , class V > void Dune::GDT::DiffusiveFluxReconstructionOperator< GridViewType, DiffusionFactorType, DiffusionTensorType >::apply (const Stuff::LocalizableFunctionInterface< EntityType, DomainFieldType, dimDomain, FieldType, 1 > & source, DiscreteFunction< DunePdelabRtSpaceWrapper< GV, 0, FieldType, dimDomain >, V > & range) const inline
References Dune::GDT::LocalEllipticIpdgIntegrands::Inner< DiffusionFactorImp, DiffusionTensorImp, method >::evaluate(), Dune::GDT::LocalEllipticIpdgIntegrands::BoundaryLHS< DiffusionFactorImp, DiffusionTensorImp, method >::evaluate(), Dune::GDT::LocalEllipticIpdgIntegrands::Inner< DiffusionFactorImp, DiffusionTensorImp, method >::order(), and Dune::GDT::LocalEllipticIpdgIntegrands::BoundaryLHS< DiffusionFactorImp, DiffusionTensorImp, method >::order().
Member Data Documentation
template<class GridViewType, class DiffusionFactorType, class DiffusionTensorType = void> const size_t Dune::GDT::DiffusiveFluxReconstructionOperator< GridViewType, DiffusionFactorType, DiffusionTensorType >::dimDomain = GridViewType::dimension static
The documentation for this class was generated from the following file:
fluxreconstruction.hh