Dune::GDT::ContainerBasedStationaryDiscretizationInterface< Traits > Class Template Reference
Dune::GDT::ContainerBasedStationaryDiscretizationInterface< Traits > Class Template Reference
#include <dune/gdt/discretizations/interfaces.hh>
Public Types
typedef Traits::MatrixType MatrixType
typedef Traits::VectorType VectorType
typedef Traits::ProblemType ProblemType
typedef Traits::AnsatzSpaceType AnsatzSpaceType
typedef Traits::TestSpaceType TestSpaceType
Public Member Functions
const VectorType & dirichlet_shift () const
Returns the Dirichlet shift.
Have to be implemented by any derived class.
const MatrixType & system_matrix () const
const VectorType & rhs_vector () const
bool has_dirichlet_shift () const
Provided by the interface for convenience.
std::vector< std::string > solver_types () const
Stuff::Common::Configuration solver_options (const std::string type="") const
void solve (VectorType &solution, const Stuff::Common::Configuration &options) const
Have to be implemented by any derived class.
const ProblemType & problem () const
const AnsatzSpaceType & ansatz_space () const
const TestSpaceType & test_space () const
Provided by the interface for convenience.
void solve (VectorType &solution, const std::string &type) const
void solve (VectorType &solution) const
VectorType solve (const Stuff::Common::Configuration &options) const
VectorType solve (const std::string &type) const
VectorType solve () const
VectorType create_vector () const
void visualize (const VectorType &vector, const std::string filename, const std::string name) const
Member Typedef Documentation
template<class Traits> typedef Traits::AnsatzSpaceType Dune::GDT::StationaryDiscretizationInterface< Traits >::AnsatzSpaceType inherited
template<class Traits> typedef Traits::MatrixType Dune::GDT::ContainerBasedStationaryDiscretizationInterface< Traits >::MatrixType
template<class Traits> typedef Traits::ProblemType Dune::GDT::StationaryDiscretizationInterface< Traits >::ProblemType inherited
template<class Traits> typedef Traits::TestSpaceType Dune::GDT::StationaryDiscretizationInterface< Traits >::TestSpaceType inherited
template<class Traits> typedef Traits::VectorType Dune::GDT::StationaryDiscretizationInterface< Traits >::VectorType
Member Function Documentation
template<class Traits> const AnsatzSpaceType& Dune::GDT::StationaryDiscretizationInterface< Traits >::ansatz_space () const inline inherited
Referenced by Dune::GDT::StationaryDiscretizationInterface< internal::StationaryContainerBasedDefaultDiscretizationTraits< ProblemImp, AnsatzSpaceImp, MatrixImp, VectorImp, TestSpaceImp > >::ansatz_space(), Dune::GDT::StationaryDiscretizationInterface< internal::StationaryContainerBasedDefaultDiscretizationTraits< ProblemImp, AnsatzSpaceImp, MatrixImp, VectorImp, TestSpaceImp > >::create_vector(), and Dune::GDT::StationaryDiscretizationInterface< internal::StationaryContainerBasedDefaultDiscretizationTraits< ProblemImp, AnsatzSpaceImp, MatrixImp, VectorImp, TestSpaceImp > >::visualize().
template<class Traits> VectorType Dune::GDT::StationaryDiscretizationInterface< Traits >::create_vector () const inline inherited
Referenced by Dune::GDT::StationaryDiscretizationInterface< internal::StationaryContainerBasedDefaultDiscretizationTraits< ProblemImp, AnsatzSpaceImp, MatrixImp, VectorImp, TestSpaceImp > >::solve().
template<class Traits> const VectorType& Dune::GDT::ContainerBasedStationaryDiscretizationInterface< Traits >::dirichlet_shift () const inline
Returns the Dirichlet shift.
Note
This method has to be implemented, if has_dirichlet_shift() returns false!
Referenced by Dune::GDT::ContainerBasedStationaryDiscretizationInterface< internal::StationaryContainerBasedDefaultDiscretizationTraits< ProblemImp, AnsatzSpaceImp, MatrixImp, VectorImp, TestSpaceImp > >::dirichlet_shift(), and Dune::GDT::ContainerBasedStationaryDiscretizationInterface< internal::StationaryContainerBasedDefaultDiscretizationTraits< ProblemImp, AnsatzSpaceImp, MatrixImp, VectorImp, TestSpaceImp > >::solve().
template<class Traits> bool Dune::GDT::ContainerBasedStationaryDiscretizationInterface< Traits >::has_dirichlet_shift () const inline
Referenced by Dune::GDT::ContainerBasedStationaryDiscretizationInterface< internal::StationaryContainerBasedDefaultDiscretizationTraits< ProblemImp, AnsatzSpaceImp, MatrixImp, VectorImp, TestSpaceImp > >::dirichlet_shift(), Dune::GDT::ContainerBasedStationaryDiscretizationInterface< internal::StationaryContainerBasedDefaultDiscretizationTraits< ProblemImp, AnsatzSpaceImp, MatrixImp, VectorImp, TestSpaceImp > >::has_dirichlet_shift(), and Dune::GDT::ContainerBasedStationaryDiscretizationInterface< internal::StationaryContainerBasedDefaultDiscretizationTraits< ProblemImp, AnsatzSpaceImp, MatrixImp, VectorImp, TestSpaceImp > >::solve().
template<class Traits> const ProblemType& Dune::GDT::StationaryDiscretizationInterface< Traits >::problem () const inline inherited
Referenced by Dune::GDT::StationaryDiscretizationInterface< internal::StationaryContainerBasedDefaultDiscretizationTraits< ProblemImp, AnsatzSpaceImp, MatrixImp, VectorImp, TestSpaceImp > >::problem().
template<class Traits> const VectorType& Dune::GDT::ContainerBasedStationaryDiscretizationInterface< Traits >::rhs_vector () const inline
Referenced by Dune::GDT::ContainerBasedStationaryDiscretizationInterface< internal::StationaryContainerBasedDefaultDiscretizationTraits< ProblemImp, AnsatzSpaceImp, MatrixImp, VectorImp, TestSpaceImp > >::rhs_vector(), and Dune::GDT::ContainerBasedStationaryDiscretizationInterface< internal::StationaryContainerBasedDefaultDiscretizationTraits< ProblemImp, AnsatzSpaceImp, MatrixImp, VectorImp, TestSpaceImp > >::solve().
template<class Traits> void Dune::GDT::StationaryDiscretizationInterface< Traits >::solve (VectorType & solution, const std::string & type) const inline inherited
template<class Traits> void Dune::GDT::StationaryDiscretizationInterface< Traits >::solve (VectorType & solution) const inline inherited
template<class Traits> VectorType Dune::GDT::StationaryDiscretizationInterface< Traits >::solve (const Stuff::Common::Configuration & options) const inline inherited
template<class Traits> VectorType Dune::GDT::StationaryDiscretizationInterface< Traits >::solve (const std::string & type) const inline inherited
template<class Traits> VectorType Dune::GDT::StationaryDiscretizationInterface< Traits >::solve () const inline inherited
Referenced by Dune::GDT::StationaryDiscretizationInterface< internal::StationaryContainerBasedDefaultDiscretizationTraits< ProblemImp, AnsatzSpaceImp, MatrixImp, VectorImp, TestSpaceImp > >::solve().
template<class Traits> void Dune::GDT::ContainerBasedStationaryDiscretizationInterface< Traits >::solve (VectorType & solution, const Stuff::Common::Configuration & options) const inline
template<class Traits> Stuff::Common::Configuration Dune::GDT::ContainerBasedStationaryDiscretizationInterface< Traits >::solver_options (const std::string type = "") const inline
template<class Traits> std::vector<std::string> Dune::GDT::ContainerBasedStationaryDiscretizationInterface< Traits >::solver_types () const inline
template<class Traits> const MatrixType& Dune::GDT::ContainerBasedStationaryDiscretizationInterface< Traits >::system_matrix () const inline
Referenced by Dune::GDT::ContainerBasedStationaryDiscretizationInterface< internal::StationaryContainerBasedDefaultDiscretizationTraits< ProblemImp, AnsatzSpaceImp, MatrixImp, VectorImp, TestSpaceImp > >::solve(), and Dune::GDT::ContainerBasedStationaryDiscretizationInterface< internal::StationaryContainerBasedDefaultDiscretizationTraits< ProblemImp, AnsatzSpaceImp, MatrixImp, VectorImp, TestSpaceImp > >::system_matrix().
template<class Traits> const TestSpaceType& Dune::GDT::StationaryDiscretizationInterface< Traits >::test_space () const inline inherited
Referenced by Dune::GDT::StationaryDiscretizationInterface< internal::StationaryContainerBasedDefaultDiscretizationTraits< ProblemImp, AnsatzSpaceImp, MatrixImp, VectorImp, TestSpaceImp > >::test_space().
template<class Traits> void Dune::GDT::StationaryDiscretizationInterface< Traits >::visualize (const VectorType & vector, const std::string filename, const std::string name) const inline inherited
The documentation for this class was generated from the following file:
discretizations/interfaces.hh