Dune::GDT::ConstDiscreteFunction< SpaceImp, VectorImp > Class Template Reference
Dune::GDT::ConstDiscreteFunction< SpaceImp, VectorImp > Class Template Reference
#include <dune/gdt/discretefunction/default.hh>
Public Types
typedef SpaceImp SpaceType
typedef SpaceType::Traits SpaceTraits
typedef VectorImp VectorType
typedef
ConstLocalDiscreteFunction
< SpaceType, VectorType > ConstLocalDiscreteFunctionType
Public Member Functions
ConstDiscreteFunction (const SpaceType &sp, const VectorType &vec, const std::string nm="gdt.constdiscretefunction")
ConstDiscreteFunction (const ThisType &other)
ConstDiscreteFunction (ThisType &&source)
virtual ~ConstDiscreteFunction ()
ThisType & operator= (const ThisType &other)=delete
virtual std::string name () const override
const SpaceType & space () const
const VectorType & vector () const
std::unique_ptr
< ConstLocalDiscreteFunctionType > local_discrete_function (const EntityType &entity) const
virtual std::unique_ptr
< LocalfunctionType > local_function (const EntityType &entity) const override
void visualize (const std::string filename, const bool subsampling=(SpaceType::polOrder > 1), const VTK::OutputType vtk_output_type=VTK::appendedraw) const
Visualizes the function using Dune::Stuff::LocalizableFunctionInterface::visualize on the grid view associated with the space.
void visualize (const std::string filename_prefix, const std::string filename_suffix, const bool subsampling=(SpaceType::polOrder > 1), const VTK::OutputType vtk_output_type=VTK::appendedraw) const
template<size_t ii>
void visualize_factor (const std::string filename_prefix, const std::string filename_suffix="", const bool subsampling=(SpaceType::polOrder > 1), const VTK::OutputType vtk_output_type=VTK::appendedraw) const
bool dofs_valid () const
Protected Member Functions
void redirect_visualize (const std::string filename_prefix, const std::string filename_suffix, const bool subsampling, const VTK::OutputType vtk_output_type, const internal::ChooseVisualize< false > &) const
void redirect_visualize (const std::string filename_prefix, const std::string filename_suffix, const bool subsampling, const VTK::OutputType vtk_output_type, const internal::ChooseVisualize< true > &) const
Protected Attributes
const DS::PerThreadValue
< SpaceType > space_
Member Typedef Documentation
template<class SpaceImp, class VectorImp> typedef ConstLocalDiscreteFunction<SpaceType, VectorType> Dune::GDT::ConstDiscreteFunction< SpaceImp, VectorImp >::ConstLocalDiscreteFunctionType
template<class SpaceImp, class VectorImp> typedef SpaceType::Traits Dune::GDT::ConstDiscreteFunction< SpaceImp, VectorImp >::SpaceTraits
template<class SpaceImp, class VectorImp> typedef SpaceImp Dune::GDT::ConstDiscreteFunction< SpaceImp, VectorImp >::SpaceType
template<class SpaceImp, class VectorImp> typedef VectorImp Dune::GDT::ConstDiscreteFunction< SpaceImp, VectorImp >::VectorType
Constructor & Destructor Documentation
template<class SpaceImp, class VectorImp> Dune::GDT::ConstDiscreteFunction< SpaceImp, VectorImp >::ConstDiscreteFunction (const SpaceType & sp, const VectorType & vec, const std::string nm = "gdt.constdiscretefunction") inline
References Dune::GDT::ConstDiscreteFunction< SpaceImp, VectorImp >::space_.
template<class SpaceImp, class VectorImp> Dune::GDT::ConstDiscreteFunction< SpaceImp, VectorImp >::ConstDiscreteFunction (const ThisType & other) inline
template<class SpaceImp, class VectorImp> Dune::GDT::ConstDiscreteFunction< SpaceImp, VectorImp >::ConstDiscreteFunction (ThisType && source) inline
template<class SpaceImp, class VectorImp> virtual Dune::GDT::ConstDiscreteFunction< SpaceImp, VectorImp >::~ConstDiscreteFunction () inline virtual
Member Function Documentation
template<class SpaceImp, class VectorImp> bool Dune::GDT::ConstDiscreteFunction< SpaceImp, VectorImp >::dofs_valid () const inline
References Dune::GDT::ConstDiscreteFunction< SpaceImp, VectorImp >::vector().
template<class SpaceImp, class VectorImp> std::unique_ptr<ConstLocalDiscreteFunctionType> Dune::GDT::ConstDiscreteFunction< SpaceImp, VectorImp >::local_discrete_function (const EntityType & entity) const inline
References Dune::GDT::ConstDiscreteFunction< SpaceImp, VectorImp >::space_.
Referenced by Dune::GDT::ConstDiscreteFunction< SpaceImp, VectorImp >::local_function().
template<class SpaceImp, class VectorImp> virtual std::unique_ptr<LocalfunctionType> Dune::GDT::ConstDiscreteFunction< SpaceImp, VectorImp >::local_function (const EntityType & entity) const inline override virtual
References Dune::GDT::ConstDiscreteFunction< SpaceImp, VectorImp >::local_discrete_function().
template<class SpaceImp, class VectorImp> virtual std::string Dune::GDT::ConstDiscreteFunction< SpaceImp, VectorImp >::name () const inline override virtual
template<class SpaceImp, class VectorImp> ThisType& Dune::GDT::ConstDiscreteFunction< SpaceImp, VectorImp >::operator= (const ThisType & other) delete
template<class SpaceImp, class VectorImp> void Dune::GDT::ConstDiscreteFunction< SpaceImp, VectorImp >::redirect_visualize (const std::string filename_prefix, const std::string filename_suffix, const bool subsampling, const VTK::OutputType vtk_output_type, const internal::ChooseVisualize< false > &) const inline protected
References Dune::GDT::ConstDiscreteFunction< SpaceImp, VectorImp >::space().
Referenced by Dune::GDT::ConstDiscreteFunction< SpaceImp, VectorImp >::visualize().
template<class SpaceImp, class VectorImp> void Dune::GDT::ConstDiscreteFunction< SpaceImp, VectorImp >::redirect_visualize (const std::string filename_prefix, const std::string filename_suffix, const bool subsampling, const VTK::OutputType vtk_output_type, const internal::ChooseVisualize< true > &) const inline protected
References Dune::GDT::ConstDiscreteFunction< SpaceImp, VectorImp >::visualize().
template<class SpaceImp, class VectorImp> const SpaceType& Dune::GDT::ConstDiscreteFunction< SpaceImp, VectorImp >::space () const inline
References Dune::GDT::ConstDiscreteFunction< SpaceImp, VectorImp >::space_.
Referenced by Dune::GDT::DarcyOperator< GridViewImp, FunctionImp >::apply(), Dune::GDT::WeightedL2Operator< WeightFunctionType, GridView, Field >::apply(), Dune::GDT::LaplaceOperator< GridView, Field >::apply(), Dune::GDT::L2Operator< GridView, Field >::apply(), Dune::GDT::EllipticOperator< DiffusionFactorType, DiffusionTensorType, GridView, Field >::apply(), Dune::GDT::make_global_l2_projection_localizable_operator(), Dune::GDT::make_global_l2_prolongation_localizable_operator(), Dune::GDT::make_l2_projection_localizable_operator(), Dune::GDT::make_l2_prolongation_localizable_operator(), Dune::GDT::make_lagrange_projection_localizable_operator(), Dune::GDT::make_lagrange_prolongation_localizable_operator(), Dune::GDT::make_local_l2_projection_localizable_operator(), Dune::GDT::make_local_l2_prolongation_localizable_operator(), Dune::GDT::project_l2(), Dune::GDT::project_lagrange(), Dune::GDT::prolong_l2(), Dune::GDT::prolong_lagrange(), and Dune::GDT::ConstDiscreteFunction< SpaceImp, VectorImp >::redirect_visualize().
template<class SpaceImp, class VectorImp> const VectorType& Dune::GDT::ConstDiscreteFunction< SpaceImp, VectorImp >::vector () const inline
Referenced by Dune::GDT::VectorFunctionalBase< Vector, Space, GridView, Field >::apply(), Dune::GDT::MatrixOperatorBase< Matrix, RangeSpace, GridView, SourceSpace, Field, ChoosePattern::volume >::apply(), Dune::GDT::MatrixOperatorBase< Matrix, RangeSpace, GridView, SourceSpace, Field, ChoosePattern::volume >::apply2(), Dune::GDT::MatrixOperatorBase< Matrix, RangeSpace, GridView, SourceSpace, Field, ChoosePattern::volume >::apply_inverse(), and Dune::GDT::ConstDiscreteFunction< SpaceImp, VectorImp >::dofs_valid().
template<class SpaceImp, class VectorImp> void Dune::GDT::ConstDiscreteFunction< SpaceImp, VectorImp >::visualize (const std::string filename, const bool subsampling = (SpaceType::polOrder > 1), const VTK::OutputType vtk_output_type = VTK::appendedraw) const inline
Visualizes the function using Dune::Stuff::LocalizableFunctionInterface::visualize on the grid view associated with the space.
See Also
Dune::Stuff::LocalizableFunctionInterface::visualize
Note
Subsampling is enabled by default for functions of order greater than one.
Referenced by Dune::GDT::ConstDiscreteFunction< SpaceImp, VectorImp >::redirect_visualize().
template<class SpaceImp, class VectorImp> void Dune::GDT::ConstDiscreteFunction< SpaceImp, VectorImp >::visualize (const std::string filename_prefix, const std::string filename_suffix, const bool subsampling = (SpaceType::polOrder > 1), const VTK::OutputType vtk_output_type = VTK::appendedraw) const inline
References Dune::GDT::ConstDiscreteFunction< SpaceImp, VectorImp >::redirect_visualize().
template<class SpaceImp, class VectorImp> template<size_t ii> void Dune::GDT::ConstDiscreteFunction< SpaceImp, VectorImp >::visualize_factor (const std::string filename_prefix, const std::string filename_suffix = "", const bool subsampling = (SpaceType::polOrder > 1), const VTK::OutputType vtk_output_type = VTK::appendedraw) const inline
Member Data Documentation
template<class SpaceImp, class VectorImp> const DS::PerThreadValue<SpaceType> Dune::GDT::ConstDiscreteFunction< SpaceImp, VectorImp >::space_ protected
Referenced by Dune::GDT::ConstDiscreteFunction< SpaceImp, VectorImp >::ConstDiscreteFunction(), Dune::GDT::ConstDiscreteFunction< SpaceImp, VectorImp >::local_discrete_function(), Dune::GDT::DiscreteFunction< SpaceImp, VectorImp >::local_discrete_function(), and Dune::GDT::ConstDiscreteFunction< SpaceImp, VectorImp >::space().
The documentation for this class was generated from the following file:
discretefunction/default.hh