Dune::GDT::AdvectionLocalizableDefault< AnalyticalFluxImp, NumericalCouplingFluxImp, NumericalBoundaryFluxImp, BoundaryValueFunctionImp, SourceImp, RangeImp > Class Template Reference
Dune::GDT::AdvectionLocalizableDefault< AnalyticalFluxImp, NumericalCouplingFluxImp, NumericalBoundaryFluxImp, BoundaryValueFunctionImp, SourceImp, RangeImp > Class Template Reference
#include <dune/gdt/operators/fv.hh>
Public Types
typedef AnalyticalFluxImp AnalyticalFluxType
typedef NumericalCouplingFluxImp NumericalCouplingFluxType
typedef NumericalBoundaryFluxImp NumericalBoundaryFluxType
typedef BoundaryValueFunctionImp BoundaryValueFunctionType
typedef SourceImp SourceType
typedef RangeImp RangeType
typedef SourceType::RangeFieldType RangeFieldType
typedef
RangeType::SpaceType::GridViewType GridViewType
typedef
Dune::GDT::LocalCouplingFvOperator
< NumericalCouplingFluxType > LocalCouplingOperatorType
typedef
Dune::GDT::LocalBoundaryFvOperator
< NumericalBoundaryFluxType > LocalBoundaryOperatorType
Public Member Functions
template<class... LocalOperatorArgTypes>
AdvectionLocalizableDefault (const AnalyticalFluxType &analytical_flux, const BoundaryValueFunctionType &boundary_values, const SourceType &source, RangeType &range, LocalOperatorArgTypes &&...local_operator_args)
const SourceType & source () const
const RangeType & range () const
RangeType & range ()
void add (const LocalOperatorInterface< L > &local_operator, const DSG::ApplyOn::WhichEntity< GridViewType > *where=new DSG::ApplyOn::AllEntities< GridViewType >())
void add (const LocalCouplingOperatorInterface< T > &local_operator, const DSG::ApplyOn::WhichIntersection< GridViewType > *where=new DSG::ApplyOn::InnerIntersections< GridViewType >())
void add (const LocalBoundaryOperatorInterface< T > &local_operator, const DSG::ApplyOn::WhichIntersection< GridViewType > *where=new DSG::ApplyOn::BoundaryIntersections< GridViewType >())
void apply ()
Static Public Attributes
static const size_t dimDomain = GridViewType::dimension
Protected Attributes
const SourceType & source_
RangeType & range_
std::vector< std::unique_ptr
< DSG::internal::Codim0Object
< GridViewType > > > local_operators_codim_0
std::vector< std::unique_ptr
< DSG::internal::Codim1Object
< GridViewType > > > local_operators_codim_1
bool walked_
Member Typedef Documentation
template<class AnalyticalFluxImp , class NumericalCouplingFluxImp , class NumericalBoundaryFluxImp , class BoundaryValueFunctionImp , class SourceImp , class RangeImp > typedef AnalyticalFluxImp Dune::GDT::AdvectionLocalizableDefault< AnalyticalFluxImp, NumericalCouplingFluxImp, NumericalBoundaryFluxImp, BoundaryValueFunctionImp, SourceImp, RangeImp >::AnalyticalFluxType
template<class AnalyticalFluxImp , class NumericalCouplingFluxImp , class NumericalBoundaryFluxImp , class BoundaryValueFunctionImp , class SourceImp , class RangeImp > typedef BoundaryValueFunctionImp Dune::GDT::AdvectionLocalizableDefault< AnalyticalFluxImp, NumericalCouplingFluxImp, NumericalBoundaryFluxImp, BoundaryValueFunctionImp, SourceImp, RangeImp >::BoundaryValueFunctionType
template<class AnalyticalFluxImp , class NumericalCouplingFluxImp , class NumericalBoundaryFluxImp , class BoundaryValueFunctionImp , class SourceImp , class RangeImp > typedef RangeType::SpaceType::GridViewType Dune::GDT::AdvectionLocalizableDefault< AnalyticalFluxImp, NumericalCouplingFluxImp, NumericalBoundaryFluxImp, BoundaryValueFunctionImp, SourceImp, RangeImp >::GridViewType
template<class AnalyticalFluxImp , class NumericalCouplingFluxImp , class NumericalBoundaryFluxImp , class BoundaryValueFunctionImp , class SourceImp , class RangeImp > typedef Dune::GDT::LocalBoundaryFvOperator<NumericalBoundaryFluxType> Dune::GDT::AdvectionLocalizableDefault< AnalyticalFluxImp, NumericalCouplingFluxImp, NumericalBoundaryFluxImp, BoundaryValueFunctionImp, SourceImp, RangeImp >::LocalBoundaryOperatorType
template<class AnalyticalFluxImp , class NumericalCouplingFluxImp , class NumericalBoundaryFluxImp , class BoundaryValueFunctionImp , class SourceImp , class RangeImp > typedef Dune::GDT::LocalCouplingFvOperator<NumericalCouplingFluxType> Dune::GDT::AdvectionLocalizableDefault< AnalyticalFluxImp, NumericalCouplingFluxImp, NumericalBoundaryFluxImp, BoundaryValueFunctionImp, SourceImp, RangeImp >::LocalCouplingOperatorType
template<class AnalyticalFluxImp , class NumericalCouplingFluxImp , class NumericalBoundaryFluxImp , class BoundaryValueFunctionImp , class SourceImp , class RangeImp > typedef NumericalBoundaryFluxImp Dune::GDT::AdvectionLocalizableDefault< AnalyticalFluxImp, NumericalCouplingFluxImp, NumericalBoundaryFluxImp, BoundaryValueFunctionImp, SourceImp, RangeImp >::NumericalBoundaryFluxType
template<class AnalyticalFluxImp , class NumericalCouplingFluxImp , class NumericalBoundaryFluxImp , class BoundaryValueFunctionImp , class SourceImp , class RangeImp > typedef NumericalCouplingFluxImp Dune::GDT::AdvectionLocalizableDefault< AnalyticalFluxImp, NumericalCouplingFluxImp, NumericalBoundaryFluxImp, BoundaryValueFunctionImp, SourceImp, RangeImp >::NumericalCouplingFluxType
template<class AnalyticalFluxImp , class NumericalCouplingFluxImp , class NumericalBoundaryFluxImp , class BoundaryValueFunctionImp , class SourceImp , class RangeImp > typedef SourceType::RangeFieldType Dune::GDT::AdvectionLocalizableDefault< AnalyticalFluxImp, NumericalCouplingFluxImp, NumericalBoundaryFluxImp, BoundaryValueFunctionImp, SourceImp, RangeImp >::RangeFieldType
template<class AnalyticalFluxImp , class NumericalCouplingFluxImp , class NumericalBoundaryFluxImp , class BoundaryValueFunctionImp , class SourceImp , class RangeImp > typedef RangeImp Dune::GDT::AdvectionLocalizableDefault< AnalyticalFluxImp, NumericalCouplingFluxImp, NumericalBoundaryFluxImp, BoundaryValueFunctionImp, SourceImp, RangeImp >::RangeType
template<class AnalyticalFluxImp , class NumericalCouplingFluxImp , class NumericalBoundaryFluxImp , class BoundaryValueFunctionImp , class SourceImp , class RangeImp > typedef SourceImp Dune::GDT::AdvectionLocalizableDefault< AnalyticalFluxImp, NumericalCouplingFluxImp, NumericalBoundaryFluxImp, BoundaryValueFunctionImp, SourceImp, RangeImp >::SourceType
Constructor & Destructor Documentation
template<class AnalyticalFluxImp , class NumericalCouplingFluxImp , class NumericalBoundaryFluxImp , class BoundaryValueFunctionImp , class SourceImp , class RangeImp > template<class... LocalOperatorArgTypes> Dune::GDT::AdvectionLocalizableDefault< AnalyticalFluxImp, NumericalCouplingFluxImp, NumericalBoundaryFluxImp, BoundaryValueFunctionImp, SourceImp, RangeImp >::AdvectionLocalizableDefault (const AnalyticalFluxType & analytical_flux, const BoundaryValueFunctionType & boundary_values, const SourceType & source, RangeType & range, LocalOperatorArgTypes &&... local_operator_args) inline
References Dune::GDT::LocalizableOperatorBase< RangeImp::SpaceType::GridViewType, SourceImp, RangeImp >::add().
Member Function Documentation
void Dune::GDT::LocalizableOperatorBase< RangeImp::SpaceType::GridViewType , SourceImp, RangeImp >::add (const LocalOperatorInterface< L > & local_operator, const DSG::ApplyOn::WhichEntity< GridViewType > * where = new DSG::ApplyOn::AllEntities<GridViewType>()) inline inherited
Referenced by Dune::GDT::AdvectionLocalizableDefault< AnalyticalFluxImp, NumericalCouplingFluxImp, NumericalBoundaryFluxImp, BoundaryValueFunctionImp, SourceImp, RangeImp >::AdvectionLocalizableDefault(), and Dune::GDT::LinearReconstructionLocalizable< SourceImp, RangeImp, BoundaryValueFunctionImp, MatrixImp, slope_limiter >::LinearReconstructionLocalizable().
void Dune::GDT::LocalizableOperatorBase< RangeImp::SpaceType::GridViewType , SourceImp, RangeImp >::add (const LocalCouplingOperatorInterface< T > & local_operator, const DSG::ApplyOn::WhichIntersection< GridViewType > * where = new DSG::ApplyOn::InnerIntersections<GridViewType>()) inline inherited
void Dune::GDT::LocalizableOperatorBase< RangeImp::SpaceType::GridViewType , SourceImp, RangeImp >::add (const LocalBoundaryOperatorInterface< T > & local_operator, const DSG::ApplyOn::WhichIntersection< GridViewType > * where = new DSG::ApplyOn::BoundaryIntersections<GridViewType>()) inline inherited
void Dune::GDT::LocalizableOperatorBase< RangeImp::SpaceType::GridViewType , SourceImp, RangeImp >::apply () inline inherited
const RangeType& Dune::GDT::LocalizableOperatorBase< RangeImp::SpaceType::GridViewType , SourceImp, RangeImp >::range () const inline inherited
RangeType& Dune::GDT::LocalizableOperatorBase< RangeImp::SpaceType::GridViewType , SourceImp, RangeImp >::range () inline inherited
const SourceType& Dune::GDT::LocalizableOperatorBase< RangeImp::SpaceType::GridViewType , SourceImp, RangeImp >::source () const inline inherited
Member Data Documentation
template<class AnalyticalFluxImp , class NumericalCouplingFluxImp , class NumericalBoundaryFluxImp , class BoundaryValueFunctionImp , class SourceImp , class RangeImp > const size_t Dune::GDT::AdvectionLocalizableDefault< AnalyticalFluxImp, NumericalCouplingFluxImp, NumericalBoundaryFluxImp, BoundaryValueFunctionImp, SourceImp, RangeImp >::dimDomain = GridViewType::dimension static
std::vector<std::unique_ptr<DSG::internal::Codim0Object<GridViewType> > > Dune::GDT::LocalizableOperatorBase< RangeImp::SpaceType::GridViewType , SourceImp, RangeImp >::local_operators_codim_0 protected inherited
std::vector<std::unique_ptr<DSG::internal::Codim1Object<GridViewType> > > Dune::GDT::LocalizableOperatorBase< RangeImp::SpaceType::GridViewType , SourceImp, RangeImp >::local_operators_codim_1 protected inherited
RangeType& Dune::GDT::LocalizableOperatorBase< RangeImp::SpaceType::GridViewType , SourceImp, RangeImp >::range_ protected inherited
const SourceType& Dune::GDT::LocalizableOperatorBase< RangeImp::SpaceType::GridViewType , SourceImp, RangeImp >::source_ protected inherited
bool Dune::GDT::LocalizableOperatorBase< RangeImp::SpaceType::GridViewType , SourceImp, RangeImp >::walked_ protected inherited
The documentation for this class was generated from the following file:
operators/fv.hh