Dune::GDT::LocalEllipticIpdgIntegrands::BoundaryRHS< DirichletImp, DiffusionFactorImp, DiffusionTensorImp, method > Class Template Reference
Dune::GDT::LocalEllipticIpdgIntegrands::BoundaryRHS< DirichletImp, DiffusionFactorImp, DiffusionTensorImp, method > Class Template Reference
#include <dune/gdt/local/integrands/elliptic-ipdg.hh>
Public Types
typedef
internal::BoundaryRHSTraits
< DirichletImp,
DiffusionFactorImp,
DiffusionTensorImp, method > Traits
typedef Traits::DirichletType DirichletType
typedef Traits::DiffusionFactorType DiffusionFactorType
typedef Traits::DiffusionTensorType DiffusionTensorType
typedef
Traits::LocalfunctionTupleType LocalfunctionTupleType
typedef Traits::EntityType EntityType
typedef Traits::DomainFieldType DomainFieldType
Public Member Functions
BoundaryRHS (const DirichletType &dirichlet, const DiffusionFactorType &diffusion_factor, const DiffusionTensorType &diffusion_tensor, const double beta=LocalSipdgIntegrands::internal::default_beta(dimDomain))
BoundaryRHS (const DirichletType &dirichlet, const DiffusionFactorType &diffusion_factor, const double beta=LocalSipdgIntegrands::internal::default_beta(dimDomain))
template<typename DiffusionType , typename = typename std::enable_if<(std::is_same<DiffusionType, DiffusionTensorType>::value) && (dimDomain > 1>
BoundaryRHS (const DirichletType &dirichlet, const DiffusionType &diffusion, const double beta=LocalSipdgIntegrands::internal::default_beta(dimDomain))
BoundaryRHS (const ThisType &other)=default
BoundaryRHS (ThisType &&source)=default
Required by LocalFaceIntegrandInterface< ..., 1 >.
LocalfunctionTupleType localFunctions (const EntityType &entity) const
template<class R , size_t r, size_t rC>
size_t order (const LocalfunctionTupleType &local_functions, const Stuff::LocalfunctionSetInterface< EntityType, DomainFieldType, dimDomain, R, r, rC > &test_base) const
extracts the local functions and calls the correct order() method
template<class IntersectionType , class R , size_t r, size_t rC>
void evaluate (const LocalfunctionTupleType &local_functions, const Stuff::LocalfunctionSetInterface< EntityType, DomainFieldType, dimDomain, R, r, rC > &test_base, const IntersectionType &intersection, const Dune::FieldVector< DomainFieldType, dimDomain-1 > &local_point, Dune::DynamicVector< R > &ret) const
extracts the local functions and calls the correct evaluate() method
Actual implementation of order.
template<class R , size_t rDF, size_t rCDF, size_t rDT, size_t rCDT, size_t rLR, size_t rCLR, size_t rT, size_t rCT>
size_t order (const Stuff::LocalfunctionInterface< EntityType, DomainFieldType, dimDomain, R, rLR, rCLR > &local_dirichlet, const Stuff::LocalfunctionInterface< EntityType, DomainFieldType, dimDomain, R, rDF, rCDF > &local_diffusion_factor, const Stuff::LocalfunctionInterface< EntityType, DomainFieldType, dimDomain, R, rDT, rCDT > &local_diffusion_tensor, const Stuff::LocalfunctionSetInterface< EntityType, DomainFieldType, dimDomain, R, rT, rCT > &test_base) const
Actual implementation of evaluate.
template<class R , class IntersectionType >
void evaluate (const Stuff::LocalfunctionInterface< EntityType, DomainFieldType, dimDomain, R, 1, 1 > &local_dirichlet, const Stuff::LocalfunctionInterface< EntityType, DomainFieldType, dimDomain, R, 1, 1 > &local_diffusion_factor, const Stuff::LocalfunctionInterface< EntityType, DomainFieldType, dimDomain, R, dimDomain, dimDomain > &local_diffusion_tensor, const Stuff::LocalfunctionSetInterface< EntityType, DomainFieldType, dimDomain, R, 1, 1 > &test_base, const IntersectionType &intersection, const Dune::FieldVector< DomainFieldType, dimDomain-1 > &local_point, Dune::DynamicVector< R > &ret) const
Public Attributes
const DirichletType & dirichlet_
const EllipticType elliptic_
const double beta_
Static Public Attributes
static const size_t dimDomain = Traits::dimDomain
Member Typedef Documentation
template<class DirichletImp , class DiffusionFactorImp , class DiffusionTensorImp = void, Method method = default_method> typedef Traits::DiffusionFactorType Dune::GDT::LocalEllipticIpdgIntegrands::BoundaryRHS< DirichletImp, DiffusionFactorImp, DiffusionTensorImp, method >::DiffusionFactorType
template<class DirichletImp , class DiffusionFactorImp , class DiffusionTensorImp = void, Method method = default_method> typedef Traits::DiffusionTensorType Dune::GDT::LocalEllipticIpdgIntegrands::BoundaryRHS< DirichletImp, DiffusionFactorImp, DiffusionTensorImp, method >::DiffusionTensorType
template<class DirichletImp , class DiffusionFactorImp , class DiffusionTensorImp = void, Method method = default_method> typedef Traits::DirichletType Dune::GDT::LocalEllipticIpdgIntegrands::BoundaryRHS< DirichletImp, DiffusionFactorImp, DiffusionTensorImp, method >::DirichletType
template<class DirichletImp , class DiffusionFactorImp , class DiffusionTensorImp = void, Method method = default_method> typedef Traits::DomainFieldType Dune::GDT::LocalEllipticIpdgIntegrands::BoundaryRHS< DirichletImp, DiffusionFactorImp, DiffusionTensorImp, method >::DomainFieldType
template<class DirichletImp , class DiffusionFactorImp , class DiffusionTensorImp = void, Method method = default_method> typedef Traits::EntityType Dune::GDT::LocalEllipticIpdgIntegrands::BoundaryRHS< DirichletImp, DiffusionFactorImp, DiffusionTensorImp, method >::EntityType
template<class DirichletImp , class DiffusionFactorImp , class DiffusionTensorImp = void, Method method = default_method> typedef Traits::LocalfunctionTupleType Dune::GDT::LocalEllipticIpdgIntegrands::BoundaryRHS< DirichletImp, DiffusionFactorImp, DiffusionTensorImp, method >::LocalfunctionTupleType
template<class DirichletImp , class DiffusionFactorImp , class DiffusionTensorImp = void, Method method = default_method> typedef internal::BoundaryRHSTraits<DirichletImp, DiffusionFactorImp, DiffusionTensorImp, method> Dune::GDT::LocalEllipticIpdgIntegrands::BoundaryRHS< DirichletImp, DiffusionFactorImp, DiffusionTensorImp, method >::Traits
Constructor & Destructor Documentation
template<class DirichletImp , class DiffusionFactorImp , class DiffusionTensorImp = void, Method method = default_method> Dune::GDT::LocalEllipticIpdgIntegrands::BoundaryRHS< DirichletImp, DiffusionFactorImp, DiffusionTensorImp, method >::BoundaryRHS (const DirichletType & dirichlet, const DiffusionFactorType & diffusion_factor, const DiffusionTensorType & diffusion_tensor, const double beta = LocalSipdgIntegrands::internal::default_beta(dimDomain)) inline
template<class DirichletImp , class DiffusionFactorImp , class DiffusionTensorImp = void, Method method = default_method> Dune::GDT::LocalEllipticIpdgIntegrands::BoundaryRHS< DirichletImp, DiffusionFactorImp, DiffusionTensorImp, method >::BoundaryRHS (const DirichletType & dirichlet, const DiffusionFactorType & diffusion_factor, const double beta = LocalSipdgIntegrands::internal::default_beta(dimDomain)) inline
template<class DirichletImp , class DiffusionFactorImp , class DiffusionTensorImp = void, Method method = default_method> template<typename DiffusionType , typename = typename std::enable_if<(std::is_same<DiffusionType, DiffusionTensorType>::value) && (dimDomain > 1> Dune::GDT::LocalEllipticIpdgIntegrands::BoundaryRHS< DirichletImp, DiffusionFactorImp, DiffusionTensorImp, method >::BoundaryRHS (const DirichletType & dirichlet, const DiffusionType & diffusion, const double beta = LocalSipdgIntegrands::internal::default_beta(dimDomain)) inline
template<class DirichletImp , class DiffusionFactorImp , class DiffusionTensorImp = void, Method method = default_method> Dune::GDT::LocalEllipticIpdgIntegrands::BoundaryRHS< DirichletImp, DiffusionFactorImp, DiffusionTensorImp, method >::BoundaryRHS (const ThisType & other) default
template<class DirichletImp , class DiffusionFactorImp , class DiffusionTensorImp = void, Method method = default_method> Dune::GDT::LocalEllipticIpdgIntegrands::BoundaryRHS< DirichletImp, DiffusionFactorImp, DiffusionTensorImp, method >::BoundaryRHS (ThisType && source) default
Member Function Documentation
template<class DirichletImp , class DiffusionFactorImp , class DiffusionTensorImp = void, Method method = default_method> template<class IntersectionType , class R , size_t r, size_t rC> void Dune::GDT::LocalEllipticIpdgIntegrands::BoundaryRHS< DirichletImp, DiffusionFactorImp, DiffusionTensorImp, method >::evaluate (const LocalfunctionTupleType & local_functions, const Stuff::LocalfunctionSetInterface< EntityType, DomainFieldType, dimDomain, R, r, rC > & test_base, const IntersectionType & intersection, const Dune::FieldVector< DomainFieldType, dimDomain-1 > & local_point, Dune::DynamicVector< R > & ret) const inline
extracts the local functions and calls the correct evaluate() method
template<class DirichletImp , class DiffusionFactorImp , class DiffusionTensorImp = void, Method method = default_method> template<class R , class IntersectionType > void Dune::GDT::LocalEllipticIpdgIntegrands::BoundaryRHS< DirichletImp, DiffusionFactorImp, DiffusionTensorImp, method >::evaluate (const Stuff::LocalfunctionInterface< EntityType, DomainFieldType, dimDomain, R, 1, 1 > & local_dirichlet, const Stuff::LocalfunctionInterface< EntityType, DomainFieldType, dimDomain, R, 1, 1 > & local_diffusion_factor, const Stuff::LocalfunctionInterface< EntityType, DomainFieldType, dimDomain, R, dimDomain, dimDomain > & local_diffusion_tensor, const Stuff::LocalfunctionSetInterface< EntityType, DomainFieldType, dimDomain, R, 1, 1 > & test_base, const IntersectionType & intersection, const Dune::FieldVector< DomainFieldType, dimDomain-1 > & local_point, Dune::DynamicVector< R > & ret) const inline
References Dune::GDT::LocalEllipticIpdgIntegrands::BoundaryRHS< DirichletImp, DiffusionFactorImp, DiffusionTensorImp, method >::beta_, and Dune::GDT::LocalSipdgIntegrands::internal::boundary_sigma().
template<class DirichletImp , class DiffusionFactorImp , class DiffusionTensorImp = void, Method method = default_method> LocalfunctionTupleType Dune::GDT::LocalEllipticIpdgIntegrands::BoundaryRHS< DirichletImp, DiffusionFactorImp, DiffusionTensorImp, method >::localFunctions (const EntityType & entity) const inline
References Dune::GDT::LocalEllipticIntegrand< DiffusionFactorImp, DiffusionTensorImp >::diffusion_factor(), Dune::GDT::LocalEllipticIntegrand< DiffusionFactorImp, DiffusionTensorImp >::diffusion_tensor(), Dune::GDT::LocalEllipticIpdgIntegrands::BoundaryRHS< DirichletImp, DiffusionFactorImp, DiffusionTensorImp, method >::dirichlet_, and Dune::GDT::LocalEllipticIpdgIntegrands::BoundaryRHS< DirichletImp, DiffusionFactorImp, DiffusionTensorImp, method >::elliptic_.
template<class DirichletImp , class DiffusionFactorImp , class DiffusionTensorImp = void, Method method = default_method> template<class R , size_t r, size_t rC> size_t Dune::GDT::LocalEllipticIpdgIntegrands::BoundaryRHS< DirichletImp, DiffusionFactorImp, DiffusionTensorImp, method >::order (const LocalfunctionTupleType & local_functions, const Stuff::LocalfunctionSetInterface< EntityType, DomainFieldType, dimDomain, R, r, rC > & test_base) const inline
extracts the local functions and calls the correct order() method
template<class DirichletImp , class DiffusionFactorImp , class DiffusionTensorImp = void, Method method = default_method> template<class R , size_t rDF, size_t rCDF, size_t rDT, size_t rCDT, size_t rLR, size_t rCLR, size_t rT, size_t rCT> size_t Dune::GDT::LocalEllipticIpdgIntegrands::BoundaryRHS< DirichletImp, DiffusionFactorImp, DiffusionTensorImp, method >::order (const Stuff::LocalfunctionInterface< EntityType, DomainFieldType, dimDomain, R, rLR, rCLR > & local_dirichlet, const Stuff::LocalfunctionInterface< EntityType, DomainFieldType, dimDomain, R, rDF, rCDF > & local_diffusion_factor, const Stuff::LocalfunctionInterface< EntityType, DomainFieldType, dimDomain, R, rDT, rCDT > & local_diffusion_tensor, const Stuff::LocalfunctionSetInterface< EntityType, DomainFieldType, dimDomain, R, rT, rCT > & test_base) const inline
Member Data Documentation
template<class DirichletImp , class DiffusionFactorImp , class DiffusionTensorImp = void, Method method = default_method> const double Dune::GDT::LocalEllipticIpdgIntegrands::BoundaryRHS< DirichletImp, DiffusionFactorImp, DiffusionTensorImp, method >::beta_
Referenced by Dune::GDT::LocalEllipticIpdgIntegrands::BoundaryRHS< DirichletImp, DiffusionFactorImp, DiffusionTensorImp, method >::evaluate().
template<class DirichletImp , class DiffusionFactorImp , class DiffusionTensorImp = void, Method method = default_method> const size_t Dune::GDT::LocalEllipticIpdgIntegrands::BoundaryRHS< DirichletImp, DiffusionFactorImp, DiffusionTensorImp, method >::dimDomain = Traits::dimDomain static
template<class DirichletImp , class DiffusionFactorImp , class DiffusionTensorImp = void, Method method = default_method> const DirichletType& Dune::GDT::LocalEllipticIpdgIntegrands::BoundaryRHS< DirichletImp, DiffusionFactorImp, DiffusionTensorImp, method >::dirichlet_
Referenced by Dune::GDT::LocalEllipticIpdgIntegrands::BoundaryRHS< DirichletImp, DiffusionFactorImp, DiffusionTensorImp, method >::localFunctions().
template<class DirichletImp , class DiffusionFactorImp , class DiffusionTensorImp = void, Method method = default_method> const EllipticType Dune::GDT::LocalEllipticIpdgIntegrands::BoundaryRHS< DirichletImp, DiffusionFactorImp, DiffusionTensorImp, method >::elliptic_
Referenced by Dune::GDT::LocalEllipticIpdgIntegrands::BoundaryRHS< DirichletImp, DiffusionFactorImp, DiffusionTensorImp, method >::localFunctions().
The documentation for this class was generated from the following file:
local/integrands/elliptic-ipdg.hh