Dune::GDT::DiffusiveFluxReconstructionOperator< GridViewType, LocalizableFunctionType, void > Class Template Reference
Dune::GDT::DiffusiveFluxReconstructionOperator< GridViewType, LocalizableFunctionType, void > Class Template Reference
#include <dune/gdt/operators/fluxreconstruction.hh>
Public Types
typedef GridViewType::template
Codim< 0 >::Entity EntityType
typedef GridViewType::ctype DomainFieldType
typedef
LocalizableFunctionType::RangeFieldType FieldType
typedef
LocalizableFunctionType::DomainType DomainType
Public Member Functions
DiffusiveFluxReconstructionOperator (const GridViewType &grid_view, const LocalizableFunctionType &diffusion, const size_t over_integrate=0)
template<class GV , class V >
void apply (const Stuff::LocalizableFunctionInterface< EntityType, DomainFieldType, dimDomain, FieldType, 1 > &source, DiscreteFunction< DunePdelabRtSpaceWrapper< GV, 0, FieldType, dimDomain >, V > &range) const
Static Public Attributes
static const size_t dimDomain = GridViewType::dimension
Detailed Description
template<class GridViewType, class LocalizableFunctionType>
class Dune::GDT::DiffusiveFluxReconstructionOperator< GridViewType, LocalizableFunctionType, void >
Todo:
Add more static checks that GridViewType and LocalizableFunctionType match.
Derive from operator interfaces.
Member Typedef Documentation
template<class GridViewType , class LocalizableFunctionType > typedef GridViewType::ctype Dune::GDT::DiffusiveFluxReconstructionOperator< GridViewType, LocalizableFunctionType, void >::DomainFieldType
template<class GridViewType , class LocalizableFunctionType > typedef LocalizableFunctionType::DomainType Dune::GDT::DiffusiveFluxReconstructionOperator< GridViewType, LocalizableFunctionType, void >::DomainType
template<class GridViewType , class LocalizableFunctionType > typedef GridViewType::template Codim<0>::Entity Dune::GDT::DiffusiveFluxReconstructionOperator< GridViewType, LocalizableFunctionType, void >::EntityType
template<class GridViewType , class LocalizableFunctionType > typedef LocalizableFunctionType::RangeFieldType Dune::GDT::DiffusiveFluxReconstructionOperator< GridViewType, LocalizableFunctionType, void >::FieldType
Constructor & Destructor Documentation
template<class GridViewType , class LocalizableFunctionType > Dune::GDT::DiffusiveFluxReconstructionOperator< GridViewType, LocalizableFunctionType, void >::DiffusiveFluxReconstructionOperator (const GridViewType & grid_view, const LocalizableFunctionType & diffusion, const size_t over_integrate = 0) inline
Member Function Documentation
template<class GridViewType , class LocalizableFunctionType > template<class GV , class V > void Dune::GDT::DiffusiveFluxReconstructionOperator< GridViewType, LocalizableFunctionType, void >::apply (const Stuff::LocalizableFunctionInterface< EntityType, DomainFieldType, dimDomain, FieldType, 1 > & source, DiscreteFunction< DunePdelabRtSpaceWrapper< GV, 0, FieldType, dimDomain >, V > & range) const inline
References Dune::GDT::LocalEllipticIpdgIntegrands::Inner< DiffusionFactorImp, DiffusionTensorImp, method >::evaluate(), Dune::GDT::LocalEllipticIpdgIntegrands::BoundaryLHS< DiffusionFactorImp, DiffusionTensorImp, method >::evaluate(), Dune::GDT::LocalEllipticIpdgIntegrands::Inner< DiffusionFactorImp, DiffusionTensorImp, method >::order(), and Dune::GDT::LocalEllipticIpdgIntegrands::BoundaryLHS< DiffusionFactorImp, DiffusionTensorImp, method >::order().
Member Data Documentation
template<class GridViewType , class LocalizableFunctionType > const size_t Dune::GDT::DiffusiveFluxReconstructionOperator< GridViewType, LocalizableFunctionType, void >::dimDomain = GridViewType::dimension static
The documentation for this class was generated from the following file:
fluxreconstruction.hh