Dune::GDT::FractionalTimeStepper< FirstStepperImp, SecondStepperImp > Class Template Reference
Dune::GDT::FractionalTimeStepper< FirstStepperImp, SecondStepperImp > Class Template Reference abstract
#include <dune/gdt/timestepper/fractional-step.hh>
Public Types
typedef FirstStepperImp FirstStepperType
typedef SecondStepperImp SecondStepperType
typedef DiscreteFunctionImp DiscreteFunctionType
typedef TimeFieldImp TimeFieldType
typedef
DiscreteFunctionType::DomainFieldType DomainFieldType
typedef
DiscreteFunctionType::RangeFieldType RangeFieldType
typedef std::map
< TimeFieldType,
DiscreteFunctionType, typename
internal::FloatCmpLt > SolutionType
typedef SolutionType::value_type TimeAndDiscreteFunctionPairType
Public Member Functions
FractionalTimeStepper (FirstStepperType &first_stepper, SecondStepperType &second_stepper)
TimeFieldType step (const TimeFieldType dt, const TimeFieldType max_dt) overridefinal
virtual TimeFieldType step (const TimeFieldType dt, const TimeFieldType max_dt)=0
Perform one time step and return the estimated optimal time step length for the next time step.
const TimeFieldType & current_time () const
TimeFieldType & current_time ()
const DiscreteFunctionType & current_solution () const
DiscreteFunctionType & current_solution ()
void set_current_solution_pointer (DiscreteFunctionType &discrete_function)
const SolutionType & solution () const
SolutionType & solution ()
void set_solution_pointer (SolutionType &solution_ref)
virtual TimeFieldType solve (const TimeFieldType t_end, const TimeFieldType initial_dt, const size_t num_save_steps, const bool save_solution, const bool output_progress, const bool visualize, const std::string filename_prefix, SolutionType &sol)
solve Applies time stepping scheme up to time t_end
virtual TimeFieldType solve (const TimeFieldType t_end, const TimeFieldType initial_dt=1e-4, const size_t num_save_steps=-1, const bool save_solution=true, const bool output_progress=false, const bool visualize=false, const std::string filename_prefix="solution")
virtual TimeFieldType solve (const TimeFieldType t_end, const TimeFieldType initial_dt, const size_t num_save_steps, SolutionType &sol)
virtual const
TimeAndDiscreteFunctionPairType & solution_closest_to_time (const TimeFieldType t) const
Find discrete solution for time point that is closest to t.
virtual const
DiscreteFunctionType & solution_at_time (const TimeFieldType t) const
void visualize_factor_of_solution (const std::string prefix="") const
virtual void visualize_solution (const std::string prefix="") const
Detailed Description
template<class FirstStepperImp, class SecondStepperImp>
class Dune::GDT::FractionalTimeStepper< FirstStepperImp, SecondStepperImp >
Takes two time steppers and performs a simple fractional step scheme (see e.g. LeVeque, "Finite Volume Methods for Hyperbolic Problems", 2002, Section 17.1. In each time step t, the first stepper is applied up to time t+dt and the result is taken as input for the second time stepper, which is also applied up to time t+dt. Initial values and time are taken from the first time stepper.
Member Typedef Documentation
template<class FirstStepperImp , class SecondStepperImp > typedef DiscreteFunctionImp Dune::GDT::TimeStepperInterface< DiscreteFunctionImp, TimeFieldImp >::DiscreteFunctionType
template<class FirstStepperImp , class SecondStepperImp > typedef DiscreteFunctionType::DomainFieldType Dune::GDT::TimeStepperInterface< DiscreteFunctionImp, TimeFieldImp >::DomainFieldType
template<class FirstStepperImp , class SecondStepperImp > typedef FirstStepperImp Dune::GDT::FractionalTimeStepper< FirstStepperImp, SecondStepperImp >::FirstStepperType
template<class FirstStepperImp , class SecondStepperImp > typedef DiscreteFunctionType::RangeFieldType Dune::GDT::TimeStepperInterface< DiscreteFunctionImp, TimeFieldImp >::RangeFieldType
template<class FirstStepperImp , class SecondStepperImp > typedef SecondStepperImp Dune::GDT::FractionalTimeStepper< FirstStepperImp, SecondStepperImp >::SecondStepperType
template<class FirstStepperImp , class SecondStepperImp > typedef std::map<TimeFieldType, DiscreteFunctionType, typename internal::FloatCmpLt> Dune::GDT::TimeStepperInterface< DiscreteFunctionImp, TimeFieldImp >::SolutionType
typedef SolutionType::value_type Dune::GDT::TimeStepperInterface< FirstStepperImp::DiscreteFunctionType , FirstStepperImp::TimeFieldType >::TimeAndDiscreteFunctionPairType inherited
template<class FirstStepperImp , class SecondStepperImp > typedef TimeFieldImp Dune::GDT::TimeStepperInterface< DiscreteFunctionImp, TimeFieldImp >::TimeFieldType
Constructor & Destructor Documentation
template<class FirstStepperImp , class SecondStepperImp > Dune::GDT::FractionalTimeStepper< FirstStepperImp, SecondStepperImp >::FractionalTimeStepper (FirstStepperType & first_stepper, SecondStepperType & second_stepper) inline
References Dune::GDT::TimeStepperInterface< FirstStepperImp::DiscreteFunctionType, FirstStepperImp::TimeFieldType >::current_solution(), and Dune::GDT::TimeStepperInterface< FirstStepperImp::DiscreteFunctionType, FirstStepperImp::TimeFieldType >::solution().
Member Function Documentation
const DiscreteFunctionType& Dune::GDT::TimeStepperInterface< FirstStepperImp::DiscreteFunctionType , FirstStepperImp::TimeFieldType >::current_solution () const inline inherited
Referenced by Dune::GDT::FractionalTimeStepper< FirstStepperImp, SecondStepperImp >::FractionalTimeStepper().
DiscreteFunctionType& Dune::GDT::TimeStepperInterface< FirstStepperImp::DiscreteFunctionType , FirstStepperImp::TimeFieldType >::current_solution () inline inherited
const TimeFieldType& Dune::GDT::TimeStepperInterface< FirstStepperImp::DiscreteFunctionType , FirstStepperImp::TimeFieldType >::current_time () const inline inherited
Referenced by Dune::GDT::FractionalTimeStepper< FirstStepperImp, SecondStepperImp >::step().
TimeFieldType& Dune::GDT::TimeStepperInterface< FirstStepperImp::DiscreteFunctionType , FirstStepperImp::TimeFieldType >::current_time () inline inherited
void Dune::GDT::TimeStepperInterface< FirstStepperImp::DiscreteFunctionType , FirstStepperImp::TimeFieldType >::set_current_solution_pointer (DiscreteFunctionType & discrete_function) inline inherited
void Dune::GDT::TimeStepperInterface< FirstStepperImp::DiscreteFunctionType , FirstStepperImp::TimeFieldType >::set_solution_pointer (SolutionType & solution_ref) inline inherited
const SolutionType& Dune::GDT::TimeStepperInterface< FirstStepperImp::DiscreteFunctionType , FirstStepperImp::TimeFieldType >::solution () const inline inherited
Referenced by Dune::GDT::FractionalTimeStepper< FirstStepperImp, SecondStepperImp >::FractionalTimeStepper().
SolutionType& Dune::GDT::TimeStepperInterface< FirstStepperImp::DiscreteFunctionType , FirstStepperImp::TimeFieldType >::solution () inline inherited
virtual const DiscreteFunctionType& Dune::GDT::TimeStepperInterface< FirstStepperImp::DiscreteFunctionType , FirstStepperImp::TimeFieldType >::solution_at_time (const TimeFieldType t) const inline virtual inherited
References Dune::GDT::end(), and Dune::GDT::TimeStepperInterface< DiscreteFunctionImp, TimeFieldImp >::solution().
virtual const TimeAndDiscreteFunctionPairType& Dune::GDT::TimeStepperInterface< FirstStepperImp::DiscreteFunctionType , FirstStepperImp::TimeFieldType >::solution_closest_to_time (const TimeFieldType t) const inline virtual inherited
Find discrete solution for time point that is closest to t.
The timestepper only stores the solution at discrete time points. This function returns the discrete solution for the stored time point that is closest to the query time t.
Parameters
t Time
Returns
std::pair with pair.second the discrete solution at time pair.first
References Dune::GDT::TimeStepperInterface< DiscreteFunctionImp, TimeFieldImp >::solution().
virtual TimeFieldType Dune::GDT::TimeStepperInterface< FirstStepperImp::DiscreteFunctionType , FirstStepperImp::TimeFieldType >::solve (const TimeFieldType t_end, const TimeFieldType initial_dt, const size_t num_save_steps, const bool save_solution, const bool output_progress, const bool visualize, const std::string filename_prefix, SolutionType & sol) inline virtual inherited
solve Applies time stepping scheme up to time t_end
Parameters
initial_dt Initial time step length. Non-adaptive schemes will use this dt for all time steps. Adaptive schemes will use initial_dt as a first guess for the time step length.
num_save_steps Number of time points that will be stored in solution if save_solution is true and/or visualized if visualize_solution is true. Default is size_t(-1), which will store all time steps.
save_solution If true, the discrete solution at num_save_steps equidistant time points will be stored in solution.
output_progress If true, the current time and current time step length will be written to std::cout at num_save_steps equidistant time points
visualize If true, solution will be written to .vtp/.vtu files at num_save_steps equidistant time points
filename_prefix Prefix of .vtp/.vtu files for visualization
sol Optional object that solution will be appended to instead of storing it in the time stepper.
Returns
estimated optimal time step length for next step
Note
If num_save_steps is specified (i.e. if it is not size_t(-1), the solution will be stored/visualized at exactly num_save_steps + 1 equidistant time points (including the initial time and t_end), even if the time step length has to be reduced to hit these time points.
References Dune::GDT::TimeStepperInterface< DiscreteFunctionImp, TimeFieldImp >::current_solution(), Dune::GDT::TimeStepperInterface< DiscreteFunctionImp, TimeFieldImp >::current_time(), and Dune::GDT::TimeStepperInterface< DiscreteFunctionImp, TimeFieldImp >::step().
virtual TimeFieldType Dune::GDT::TimeStepperInterface< FirstStepperImp::DiscreteFunctionType , FirstStepperImp::TimeFieldType >::solve (const TimeFieldType t_end, const TimeFieldType initial_dt = 1e-4, const size_t num_save_steps = -1, const bool save_solution = true, const bool output_progress = false, const bool visualize = false, const std::string filename_prefix = "solution") inline virtual inherited
References Dune::GDT::TimeStepperInterface< DiscreteFunctionImp, TimeFieldImp >::solve().
virtual TimeFieldType Dune::GDT::TimeStepperInterface< FirstStepperImp::DiscreteFunctionType , FirstStepperImp::TimeFieldType >::solve (const TimeFieldType t_end, const TimeFieldType initial_dt, const size_t num_save_steps, SolutionType & sol) inline virtual inherited
References Dune::GDT::TimeStepperInterface< DiscreteFunctionImp, TimeFieldImp >::solve().
template<class FirstStepperImp , class SecondStepperImp > TimeFieldType Dune::GDT::FractionalTimeStepper< FirstStepperImp, SecondStepperImp >::step (const TimeFieldType dt, const TimeFieldType max_dt) inline final override
References Dune::GDT::TimeStepperInterface< FirstStepperImp::DiscreteFunctionType, FirstStepperImp::TimeFieldType >::current_time().
virtual TimeFieldType Dune::GDT::TimeStepperInterface< FirstStepperImp::DiscreteFunctionType , FirstStepperImp::TimeFieldType >::step (const TimeFieldType dt, const TimeFieldType max_dt) pure virtual inherited
Perform one time step and return the estimated optimal time step length for the next time step.
Parameters
dt Time step length.
max_dt Maximal allowed time step length in this time step.
Returns
Estimated optimal time step length for the next time step.
Note
For adaptive methods or if max_dt < dt, dt is just the initial time step length, the actual time step taken may be shorter. To get the actual time step length you need to compare current_time() before and after calling step().
This method has to increase the current time by the actual time step length taken, otherwise solve will never finish execution (if current_time is not increased) or give wrong results (if current time is increased by a wrong dt).
void Dune::GDT::TimeStepperInterface< FirstStepperImp::DiscreteFunctionType , FirstStepperImp::TimeFieldType >::visualize_factor_of_solution (const std::string prefix = "") const inline inherited
References Dune::GDT::TimeStepperInterface< DiscreteFunctionImp, TimeFieldImp >::solution().
virtual void Dune::GDT::TimeStepperInterface< FirstStepperImp::DiscreteFunctionType , FirstStepperImp::TimeFieldType >::visualize_solution (const std::string prefix = "") const inline virtual inherited
References Dune::GDT::TimeStepperInterface< DiscreteFunctionImp, TimeFieldImp >::solution().
The documentation for this class was generated from the following file:
fractional-step.hh