Dune::GDT::HyperbolicFVDefaultDiscretization< ProblemImp, FVSpaceImp, numerical_flux, time_stepper_method, rhs_time_stepper_method > Class Template Reference
Dune::GDT::HyperbolicFVDefaultDiscretization< ProblemImp, FVSpaceImp, numerical_flux, time_stepper_method, rhs_time_stepper_method > Class Template Reference
#include <dune/gdt/discretizations/default.hh>
Public Types
typedef TestCaseImp TestCaseType
typedef Traits::SpaceType SpaceType
typedef Traits::ProblemType ProblemType
typedef
Traits::DiscreteSolutionType DiscreteSolutionType
typedef Traits::VectorType VectorType
typedef DiscreteFunction
< SpaceType, VectorType > DiscreteFunctionType
Public Member Functions
HyperbolicFVDefaultDiscretization (const TestCaseImp &tst_cs, const std::shared_ptr< const SpaceType > fv_space_ptr)
void visualize (const DiscreteSolutionType &solution, const std::string filename) const
Required by FVDiscretizationInterface.
const ProblemType & problem () const
const SpaceType & space () const
void solve (DiscreteSolutionType &solution) const
Have to be implemented by any derived class.
void solve (DiscreteSolutionType &solution) const
Provided by the interface for convenience.
DiscreteSolutionType solve () const
Member Typedef Documentation
template<class ProblemImp , class FVSpaceImp , NumericalFluxes numerical_flux, TimeStepperMethods time_stepper_method, TimeStepperMethods rhs_time_stepper_method> typedef DiscreteFunction<SpaceType, VectorType> Dune::GDT::FVDiscretizationInterface< Traits >::DiscreteFunctionType
template<class ProblemImp , class FVSpaceImp , NumericalFluxes numerical_flux, TimeStepperMethods time_stepper_method, TimeStepperMethods rhs_time_stepper_method> typedef Traits::DiscreteSolutionType Dune::GDT::FVDiscretizationInterface< Traits >::DiscreteSolutionType
template<class ProblemImp , class FVSpaceImp , NumericalFluxes numerical_flux, TimeStepperMethods time_stepper_method, TimeStepperMethods rhs_time_stepper_method> typedef Traits::ProblemType Dune::GDT::FVDiscretizationInterface< Traits >::ProblemType
template<class ProblemImp , class FVSpaceImp , NumericalFluxes numerical_flux, TimeStepperMethods time_stepper_method, TimeStepperMethods rhs_time_stepper_method> typedef Traits::SpaceType Dune::GDT::FVDiscretizationInterface< Traits >::SpaceType
template<class ProblemImp , class FVSpaceImp , NumericalFluxes numerical_flux, TimeStepperMethods time_stepper_method, TimeStepperMethods rhs_time_stepper_method> typedef TestCaseImp Dune::GDT::HyperbolicFVDefaultDiscretization< ProblemImp, FVSpaceImp, numerical_flux, time_stepper_method, rhs_time_stepper_method >::TestCaseType
template<class ProblemImp , class FVSpaceImp , NumericalFluxes numerical_flux, TimeStepperMethods time_stepper_method, TimeStepperMethods rhs_time_stepper_method> typedef Traits::VectorType Dune::GDT::FVDiscretizationInterface< Traits >::VectorType
Constructor & Destructor Documentation
template<class ProblemImp , class FVSpaceImp , NumericalFluxes numerical_flux, TimeStepperMethods time_stepper_method, TimeStepperMethods rhs_time_stepper_method> Dune::GDT::HyperbolicFVDefaultDiscretization< ProblemImp, FVSpaceImp, numerical_flux, time_stepper_method, rhs_time_stepper_method >::HyperbolicFVDefaultDiscretization (const TestCaseImp & tst_cs, const std::shared_ptr< const SpaceType > fv_space_ptr) inline
Member Function Documentation
template<class ProblemImp , class FVSpaceImp , NumericalFluxes numerical_flux, TimeStepperMethods time_stepper_method, TimeStepperMethods rhs_time_stepper_method> const ProblemType& Dune::GDT::HyperbolicFVDefaultDiscretization< ProblemImp, FVSpaceImp, numerical_flux, time_stepper_method, rhs_time_stepper_method >::problem () const inline
Referenced by Dune::GDT::HyperbolicFVDefaultDiscretization< ProblemImp, FVSpaceImp, numerical_flux, time_stepper_method, rhs_time_stepper_method >::solve().
void Dune::GDT::FVDiscretizationInterface< internal::HyperbolicFVDefaultDiscretizationTraits< TestCaseImp, FVSpaceImp, numerical_flux, time_stepper_method, rhs_time_stepper_method > >::solve (DiscreteSolutionType & solution) const inline inherited
References Dune::GDT::FVDiscretizationInterface< Traits >::solve().
DiscreteSolutionType Dune::GDT::FVDiscretizationInterface< internal::HyperbolicFVDefaultDiscretizationTraits< TestCaseImp, FVSpaceImp, numerical_flux, time_stepper_method, rhs_time_stepper_method > >::solve () const inline inherited
References Dune::GDT::FVDiscretizationInterface< Traits >::solve().
template<class ProblemImp , class FVSpaceImp , NumericalFluxes numerical_flux, TimeStepperMethods time_stepper_method, TimeStepperMethods rhs_time_stepper_method> void Dune::GDT::HyperbolicFVDefaultDiscretization< ProblemImp, FVSpaceImp, numerical_flux, time_stepper_method, rhs_time_stepper_method >::solve (DiscreteSolutionType & solution) const inline
References Dune::GDT::internal::AdvectionOperatorCreator< OperatorType, numerical_flux >::create(), Dune::GDT::HyperbolicFVDefaultDiscretization< ProblemImp, FVSpaceImp, numerical_flux, time_stepper_method, rhs_time_stepper_method >::problem(), Dune::GDT::project(), and Dune::GDT::TimeStepperInterface< DiscreteFunctionImp, TimeFieldImp >::solve().
template<class ProblemImp , class FVSpaceImp , NumericalFluxes numerical_flux, TimeStepperMethods time_stepper_method, TimeStepperMethods rhs_time_stepper_method> const SpaceType& Dune::GDT::HyperbolicFVDefaultDiscretization< ProblemImp, FVSpaceImp, numerical_flux, time_stepper_method, rhs_time_stepper_method >::space () const inline
template<class ProblemImp , class FVSpaceImp , NumericalFluxes numerical_flux, TimeStepperMethods time_stepper_method, TimeStepperMethods rhs_time_stepper_method> void Dune::GDT::HyperbolicFVDefaultDiscretization< ProblemImp, FVSpaceImp, numerical_flux, time_stepper_method, rhs_time_stepper_method >::visualize (const DiscreteSolutionType & solution, const std::string filename) const inline
The documentation for this class was generated from the following file:
discretizations/default.hh