Dune::GDT::LocalEllipticIpdgIntegrands::Inner< DiffusionFactorImp, DiffusionTensorImp, method > Class Template Reference
Dune::GDT::LocalEllipticIpdgIntegrands::Inner< DiffusionFactorImp, DiffusionTensorImp, method > Class Template Reference
#include <dune/gdt/local/integrands/elliptic-ipdg.hh>
Public Types
typedef internal::InnerTraits
< DiffusionFactorImp,
DiffusionTensorImp, method > Traits
typedef Traits::DiffusionFactorType DiffusionFactorType
typedef Traits::DiffusionTensorType DiffusionTensorType
typedef
Traits::LocalfunctionTupleType LocalfunctionTupleType
typedef Traits::EntityType EntityType
typedef Traits::DomainFieldType DomainFieldType
Public Member Functions
Inner (const DiffusionFactorType &diffusion_factor, const DiffusionTensorType &diffusion_tensor, const double beta=LocalSipdgIntegrands::internal::default_beta(dimDomain))
Inner (const DiffusionFactorType &diffusion_factor, const double beta=LocalSipdgIntegrands::internal::default_beta(dimDomain))
template<typename DiffusionType , typename = typename std::enable_if<(std::is_same<DiffusionType, DiffusionTensorType>::value) && (dimDomain > 1>
Inner (const DiffusionType &diffusion, const double beta=LocalSipdgIntegrands::internal::default_beta(dimDomain))
Inner (const ThisType &other)=default
Inner (ThisType &&source)=default
Required by LocalFaceIntegrandInterface< ..., 4 >.
LocalfunctionTupleType localFunctions (const EntityType &entity) const
template<class R , size_t rT, size_t rCT, size_t rA, size_t rCA>
size_t order (const LocalfunctionTupleType &local_functions_en, const LocalfunctionTupleType &local_functions_ne, const Stuff::LocalfunctionSetInterface< EntityType, DomainFieldType, dimDomain, R, rT, rCT > &test_base_en, const Stuff::LocalfunctionSetInterface< EntityType, DomainFieldType, dimDomain, R, rA, rCA > &ansatz_base_en, const Stuff::LocalfunctionSetInterface< EntityType, DomainFieldType, dimDomain, R, rT, rCT > &test_base_ne, const Stuff::LocalfunctionSetInterface< EntityType, DomainFieldType, dimDomain, R, rA, rCA > &ansatz_base_ne) const
extracts the local functions and calls the correct order() method
template<class IntersectionType , class R , size_t rT, size_t rCT, size_t rA, size_t rCA>
void evaluate (const LocalfunctionTupleType &local_functions_en, const LocalfunctionTupleType &local_functions_ne, const Stuff::LocalfunctionSetInterface< EntityType, DomainFieldType, dimDomain, R, rT, rCT > &test_base_en, const Stuff::LocalfunctionSetInterface< EntityType, DomainFieldType, dimDomain, R, rA, rCA > &ansatz_base_en, const Stuff::LocalfunctionSetInterface< EntityType, DomainFieldType, dimDomain, R, rT, rCT > &test_base_ne, const Stuff::LocalfunctionSetInterface< EntityType, DomainFieldType, dimDomain, R, rA, rCA > &ansatz_base_ne, const IntersectionType &intersection, const Dune::FieldVector< DomainFieldType, dimDomain-1 > &local_point, Dune::DynamicMatrix< R > &ret_en_en, Dune::DynamicMatrix< R > &ret_ne_ne, Dune::DynamicMatrix< R > &ret_en_ne, Dune::DynamicMatrix< R > &ret_ne_en) const
extracts the local functions and calls the correct evaluate() method
Redirects for single diffusion (either factor or tensor, but not both).
template<class R , size_t rD, size_t rCD, size_t rT, size_t rCT, size_t rA, size_t rCA>
size_t order (const Stuff::LocalfunctionInterface< EntityType, DomainFieldType, dimDomain, R, rD, rCD > &local_diffusion_en, const Stuff::LocalfunctionInterface< EntityType, DomainFieldType, dimDomain, R, rD, rCD > &local_diffusion_ne, const Stuff::LocalfunctionSetInterface< EntityType, DomainFieldType, dimDomain, R, rT, rCT > &test_base_en, const Stuff::LocalfunctionSetInterface< EntityType, DomainFieldType, dimDomain, R, rA, rCA > &ansatz_base_en, const Stuff::LocalfunctionSetInterface< EntityType, DomainFieldType, dimDomain, R, rT, rCT > &test_base_ne, const Stuff::LocalfunctionSetInterface< EntityType, DomainFieldType, dimDomain, R, rA, rCA > &ansatz_base_ne) const
template<class R , size_t rD, size_t rCD, size_t rT, size_t rCT, size_t rA, size_t rCA, class IntersectionType >
void evaluate (const Stuff::LocalfunctionInterface< EntityType, DomainFieldType, dimDomain, R, rD, rCD > &local_diffusion_en, const Stuff::LocalfunctionInterface< EntityType, DomainFieldType, dimDomain, R, rD, rCD > &local_diffusion_ne, const Stuff::LocalfunctionSetInterface< EntityType, DomainFieldType, dimDomain, R, rT, rCT > &test_base_en, const Stuff::LocalfunctionSetInterface< EntityType, DomainFieldType, dimDomain, R, rA, rCA > &ansatz_base_en, const Stuff::LocalfunctionSetInterface< EntityType, DomainFieldType, dimDomain, R, rT, rCT > &test_base_ne, const Stuff::LocalfunctionSetInterface< EntityType, DomainFieldType, dimDomain, R, rA, rCA > &ansatz_base_ne, const IntersectionType &intersection, const Dune::FieldVector< DomainFieldType, dimDomain-1 > &local_point, Dune::DynamicMatrix< R > &ret_en_en, Dune::DynamicMatrix< R > &ret_ne_ne, Dune::DynamicMatrix< R > &ret_en_ne, Dune::DynamicMatrix< R > &ret_ne_en) const
Actual Implementation of order.
template<class R , size_t rDF, size_t rCDF, size_t rDT, size_t rCDT, size_t rT, size_t rCT, size_t rA, size_t rCA>
size_t order (const Stuff::LocalfunctionInterface< EntityType, DomainFieldType, dimDomain, R, rDF, rCDF > &local_diffusion_factor_en, const Stuff::LocalfunctionInterface< EntityType, DomainFieldType, dimDomain, R, rDT, rCDT > &local_diffusion_tensor_en, const Stuff::LocalfunctionInterface< EntityType, DomainFieldType, dimDomain, R, rDF, rCDF > &local_diffusion_factor_ne, const Stuff::LocalfunctionInterface< EntityType, DomainFieldType, dimDomain, R, rDT, rCDT > &local_diffusion_tensor_ne, const Stuff::LocalfunctionSetInterface< EntityType, DomainFieldType, dimDomain, R, rT, rCT > &test_base_en, const Stuff::LocalfunctionSetInterface< EntityType, DomainFieldType, dimDomain, R, rA, rCA > &ansatz_base_en, const Stuff::LocalfunctionSetInterface< EntityType, DomainFieldType, dimDomain, R, rT, rCT > &test_base_ne, const Stuff::LocalfunctionSetInterface< EntityType, DomainFieldType, dimDomain, R, rA, rCA > &ansatz_base_ne) const
Actual Implementation of evaluate.
template<class R , class IntersectionType >
void evaluate (const Stuff::LocalfunctionInterface< EntityType, DomainFieldType, dimDomain, R, 1, 1 > &local_diffusion_factor_en, const Stuff::LocalfunctionInterface< EntityType, DomainFieldType, dimDomain, R, dimDomain, dimDomain > &local_diffusion_tensor_en, const Stuff::LocalfunctionInterface< EntityType, DomainFieldType, dimDomain, R, 1, 1 > &local_diffusion_factor_ne, const Stuff::LocalfunctionInterface< EntityType, DomainFieldType, dimDomain, R, dimDomain, dimDomain > &local_diffusion_tensor_ne, const Stuff::LocalfunctionSetInterface< EntityType, DomainFieldType, dimDomain, R, 1, 1 > &test_base_en, const Stuff::LocalfunctionSetInterface< EntityType, DomainFieldType, dimDomain, R, 1, 1 > &ansatz_base_en, const Stuff::LocalfunctionSetInterface< EntityType, DomainFieldType, dimDomain, R, 1, 1 > &test_base_ne, const Stuff::LocalfunctionSetInterface< EntityType, DomainFieldType, dimDomain, R, 1, 1 > &ansatz_base_ne, const IntersectionType &intersection, const Dune::FieldVector< DomainFieldType, dimDomain-1 > &local_point, Dune::DynamicMatrix< R > &ret_en_en, Dune::DynamicMatrix< R > &ret_ne_ne, Dune::DynamicMatrix< R > &ret_en_ne, Dune::DynamicMatrix< R > &ret_ne_en) const
Static Public Attributes
static const size_t dimDomain = Traits::dimDomain
Detailed Description
template<class DiffusionFactorImp, class DiffusionTensorImp = void, Method method = default_method>
class Dune::GDT::LocalEllipticIpdgIntegrands::Inner< DiffusionFactorImp, DiffusionTensorImp, method >
see Epshteyn, Riviere, 2007 for the meaning of beta
Note
The FieldVector< R, dimDomain - 1 > type for the intersection will probably fail for dimDomain 1
Member Typedef Documentation
template<class DiffusionFactorImp, class DiffusionTensorImp = void, Method method = default_method> typedef Traits::DiffusionFactorType Dune::GDT::LocalEllipticIpdgIntegrands::Inner< DiffusionFactorImp, DiffusionTensorImp, method >::DiffusionFactorType
template<class DiffusionFactorImp, class DiffusionTensorImp = void, Method method = default_method> typedef Traits::DiffusionTensorType Dune::GDT::LocalEllipticIpdgIntegrands::Inner< DiffusionFactorImp, DiffusionTensorImp, method >::DiffusionTensorType
template<class DiffusionFactorImp, class DiffusionTensorImp = void, Method method = default_method> typedef Traits::DomainFieldType Dune::GDT::LocalEllipticIpdgIntegrands::Inner< DiffusionFactorImp, DiffusionTensorImp, method >::DomainFieldType
template<class DiffusionFactorImp, class DiffusionTensorImp = void, Method method = default_method> typedef Traits::EntityType Dune::GDT::LocalEllipticIpdgIntegrands::Inner< DiffusionFactorImp, DiffusionTensorImp, method >::EntityType
template<class DiffusionFactorImp, class DiffusionTensorImp = void, Method method = default_method> typedef Traits::LocalfunctionTupleType Dune::GDT::LocalEllipticIpdgIntegrands::Inner< DiffusionFactorImp, DiffusionTensorImp, method >::LocalfunctionTupleType
template<class DiffusionFactorImp, class DiffusionTensorImp = void, Method method = default_method> typedef internal::InnerTraits<DiffusionFactorImp, DiffusionTensorImp, method> Dune::GDT::LocalEllipticIpdgIntegrands::Inner< DiffusionFactorImp, DiffusionTensorImp, method >::Traits
Constructor & Destructor Documentation
template<class DiffusionFactorImp, class DiffusionTensorImp = void, Method method = default_method> Dune::GDT::LocalEllipticIpdgIntegrands::Inner< DiffusionFactorImp, DiffusionTensorImp, method >::Inner (const DiffusionFactorType & diffusion_factor, const DiffusionTensorType & diffusion_tensor, const double beta = LocalSipdgIntegrands::internal::default_beta(dimDomain)) inline
template<class DiffusionFactorImp, class DiffusionTensorImp = void, Method method = default_method> Dune::GDT::LocalEllipticIpdgIntegrands::Inner< DiffusionFactorImp, DiffusionTensorImp, method >::Inner (const DiffusionFactorType & diffusion_factor, const double beta = LocalSipdgIntegrands::internal::default_beta(dimDomain)) inline
template<class DiffusionFactorImp, class DiffusionTensorImp = void, Method method = default_method> template<typename DiffusionType , typename = typename std::enable_if<(std::is_same<DiffusionType, DiffusionTensorType>::value) && (dimDomain > 1> Dune::GDT::LocalEllipticIpdgIntegrands::Inner< DiffusionFactorImp, DiffusionTensorImp, method >::Inner (const DiffusionType & diffusion, const double beta = LocalSipdgIntegrands::internal::default_beta(dimDomain)) inline
template<class DiffusionFactorImp, class DiffusionTensorImp = void, Method method = default_method> Dune::GDT::LocalEllipticIpdgIntegrands::Inner< DiffusionFactorImp, DiffusionTensorImp, method >::Inner (const ThisType & other) default
template<class DiffusionFactorImp, class DiffusionTensorImp = void, Method method = default_method> Dune::GDT::LocalEllipticIpdgIntegrands::Inner< DiffusionFactorImp, DiffusionTensorImp, method >::Inner (ThisType && source) default
Member Function Documentation
template<class DiffusionFactorImp, class DiffusionTensorImp = void, Method method = default_method> template<class IntersectionType , class R , size_t rT, size_t rCT, size_t rA, size_t rCA> void Dune::GDT::LocalEllipticIpdgIntegrands::Inner< DiffusionFactorImp, DiffusionTensorImp, method >::evaluate (const LocalfunctionTupleType & local_functions_en, const LocalfunctionTupleType & local_functions_ne, const Stuff::LocalfunctionSetInterface< EntityType, DomainFieldType, dimDomain, R, rT, rCT > & test_base_en, const Stuff::LocalfunctionSetInterface< EntityType, DomainFieldType, dimDomain, R, rA, rCA > & ansatz_base_en, const Stuff::LocalfunctionSetInterface< EntityType, DomainFieldType, dimDomain, R, rT, rCT > & test_base_ne, const Stuff::LocalfunctionSetInterface< EntityType, DomainFieldType, dimDomain, R, rA, rCA > & ansatz_base_ne, const IntersectionType & intersection, const Dune::FieldVector< DomainFieldType, dimDomain-1 > & local_point, Dune::DynamicMatrix< R > & ret_en_en, Dune::DynamicMatrix< R > & ret_ne_ne, Dune::DynamicMatrix< R > & ret_en_ne, Dune::DynamicMatrix< R > & ret_ne_en) const inline
extracts the local functions and calls the correct evaluate() method
Referenced by Dune::GDT::DiffusiveFluxReconstructionOperator< GridViewType, DiffusionFactorType, DiffusionTensorType >::apply(), Dune::GDT::DiffusiveFluxReconstructionOperator< GridViewType, LocalizableFunctionType, void >::apply(), and Dune::GDT::LocalEllipticIpdgIntegrands::Inner< DiffusionFactorImp, DiffusionTensorImp, method >::evaluate().
template<class DiffusionFactorImp, class DiffusionTensorImp = void, Method method = default_method> template<class R , size_t rD, size_t rCD, size_t rT, size_t rCT, size_t rA, size_t rCA, class IntersectionType > void Dune::GDT::LocalEllipticIpdgIntegrands::Inner< DiffusionFactorImp, DiffusionTensorImp, method >::evaluate (const Stuff::LocalfunctionInterface< EntityType, DomainFieldType, dimDomain, R, rD, rCD > & local_diffusion_en, const Stuff::LocalfunctionInterface< EntityType, DomainFieldType, dimDomain, R, rD, rCD > & local_diffusion_ne, const Stuff::LocalfunctionSetInterface< EntityType, DomainFieldType, dimDomain, R, rT, rCT > & test_base_en, const Stuff::LocalfunctionSetInterface< EntityType, DomainFieldType, dimDomain, R, rA, rCA > & ansatz_base_en, const Stuff::LocalfunctionSetInterface< EntityType, DomainFieldType, dimDomain, R, rT, rCT > & test_base_ne, const Stuff::LocalfunctionSetInterface< EntityType, DomainFieldType, dimDomain, R, rA, rCA > & ansatz_base_ne, const IntersectionType & intersection, const Dune::FieldVector< DomainFieldType, dimDomain-1 > & local_point, Dune::DynamicMatrix< R > & ret_en_en, Dune::DynamicMatrix< R > & ret_ne_ne, Dune::DynamicMatrix< R > & ret_en_ne, Dune::DynamicMatrix< R > & ret_ne_en) const inline
References Dune::GDT::LocalEllipticIpdgIntegrands::Inner< DiffusionFactorImp, DiffusionTensorImp, method >::evaluate().
template<class DiffusionFactorImp, class DiffusionTensorImp = void, Method method = default_method> template<class R , class IntersectionType > void Dune::GDT::LocalEllipticIpdgIntegrands::Inner< DiffusionFactorImp, DiffusionTensorImp, method >::evaluate (const Stuff::LocalfunctionInterface< EntityType, DomainFieldType, dimDomain, R, 1, 1 > & local_diffusion_factor_en, const Stuff::LocalfunctionInterface< EntityType, DomainFieldType, dimDomain, R, dimDomain, dimDomain > & local_diffusion_tensor_en, const Stuff::LocalfunctionInterface< EntityType, DomainFieldType, dimDomain, R, 1, 1 > & local_diffusion_factor_ne, const Stuff::LocalfunctionInterface< EntityType, DomainFieldType, dimDomain, R, dimDomain, dimDomain > & local_diffusion_tensor_ne, const Stuff::LocalfunctionSetInterface< EntityType, DomainFieldType, dimDomain, R, 1, 1 > & test_base_en, const Stuff::LocalfunctionSetInterface< EntityType, DomainFieldType, dimDomain, R, 1, 1 > & ansatz_base_en, const Stuff::LocalfunctionSetInterface< EntityType, DomainFieldType, dimDomain, R, 1, 1 > & test_base_ne, const Stuff::LocalfunctionSetInterface< EntityType, DomainFieldType, dimDomain, R, 1, 1 > & ansatz_base_ne, const IntersectionType & intersection, const Dune::FieldVector< DomainFieldType, dimDomain-1 > & local_point, Dune::DynamicMatrix< R > & ret_en_en, Dune::DynamicMatrix< R > & ret_ne_ne, Dune::DynamicMatrix< R > & ret_en_ne, Dune::DynamicMatrix< R > & ret_ne_en) const inline
References Dune::GDT::LocalSipdgIntegrands::internal::inner_sigma().
template<class DiffusionFactorImp, class DiffusionTensorImp = void, Method method = default_method> LocalfunctionTupleType Dune::GDT::LocalEllipticIpdgIntegrands::Inner< DiffusionFactorImp, DiffusionTensorImp, method >::localFunctions (const EntityType & entity) const inline
References Dune::GDT::LocalEllipticIntegrand< DiffusionFactorImp, DiffusionTensorImp >::diffusion_factor(), and Dune::GDT::LocalEllipticIntegrand< DiffusionFactorImp, DiffusionTensorImp >::diffusion_tensor().
template<class DiffusionFactorImp, class DiffusionTensorImp = void, Method method = default_method> template<class R , size_t rT, size_t rCT, size_t rA, size_t rCA> size_t Dune::GDT::LocalEllipticIpdgIntegrands::Inner< DiffusionFactorImp, DiffusionTensorImp, method >::order (const LocalfunctionTupleType & local_functions_en, const LocalfunctionTupleType & local_functions_ne, const Stuff::LocalfunctionSetInterface< EntityType, DomainFieldType, dimDomain, R, rT, rCT > & test_base_en, const Stuff::LocalfunctionSetInterface< EntityType, DomainFieldType, dimDomain, R, rA, rCA > & ansatz_base_en, const Stuff::LocalfunctionSetInterface< EntityType, DomainFieldType, dimDomain, R, rT, rCT > & test_base_ne, const Stuff::LocalfunctionSetInterface< EntityType, DomainFieldType, dimDomain, R, rA, rCA > & ansatz_base_ne) const inline
extracts the local functions and calls the correct order() method
Referenced by Dune::GDT::DiffusiveFluxReconstructionOperator< GridViewType, DiffusionFactorType, DiffusionTensorType >::apply(), Dune::GDT::DiffusiveFluxReconstructionOperator< GridViewType, LocalizableFunctionType, void >::apply(), and Dune::GDT::LocalEllipticIpdgIntegrands::Inner< DiffusionFactorImp, DiffusionTensorImp, method >::order().
template<class DiffusionFactorImp, class DiffusionTensorImp = void, Method method = default_method> template<class R , size_t rD, size_t rCD, size_t rT, size_t rCT, size_t rA, size_t rCA> size_t Dune::GDT::LocalEllipticIpdgIntegrands::Inner< DiffusionFactorImp, DiffusionTensorImp, method >::order (const Stuff::LocalfunctionInterface< EntityType, DomainFieldType, dimDomain, R, rD, rCD > & local_diffusion_en, const Stuff::LocalfunctionInterface< EntityType, DomainFieldType, dimDomain, R, rD, rCD > & local_diffusion_ne, const Stuff::LocalfunctionSetInterface< EntityType, DomainFieldType, dimDomain, R, rT, rCT > & test_base_en, const Stuff::LocalfunctionSetInterface< EntityType, DomainFieldType, dimDomain, R, rA, rCA > & ansatz_base_en, const Stuff::LocalfunctionSetInterface< EntityType, DomainFieldType, dimDomain, R, rT, rCT > & test_base_ne, const Stuff::LocalfunctionSetInterface< EntityType, DomainFieldType, dimDomain, R, rA, rCA > & ansatz_base_ne) const inline
References Dune::GDT::LocalEllipticIpdgIntegrands::Inner< DiffusionFactorImp, DiffusionTensorImp, method >::order().
template<class DiffusionFactorImp, class DiffusionTensorImp = void, Method method = default_method> template<class R , size_t rDF, size_t rCDF, size_t rDT, size_t rCDT, size_t rT, size_t rCT, size_t rA, size_t rCA> size_t Dune::GDT::LocalEllipticIpdgIntegrands::Inner< DiffusionFactorImp, DiffusionTensorImp, method >::order (const Stuff::LocalfunctionInterface< EntityType, DomainFieldType, dimDomain, R, rDF, rCDF > & local_diffusion_factor_en, const Stuff::LocalfunctionInterface< EntityType, DomainFieldType, dimDomain, R, rDT, rCDT > & local_diffusion_tensor_en, const Stuff::LocalfunctionInterface< EntityType, DomainFieldType, dimDomain, R, rDF, rCDF > & local_diffusion_factor_ne, const Stuff::LocalfunctionInterface< EntityType, DomainFieldType, dimDomain, R, rDT, rCDT > & local_diffusion_tensor_ne, const Stuff::LocalfunctionSetInterface< EntityType, DomainFieldType, dimDomain, R, rT, rCT > & test_base_en, const Stuff::LocalfunctionSetInterface< EntityType, DomainFieldType, dimDomain, R, rA, rCA > & ansatz_base_en, const Stuff::LocalfunctionSetInterface< EntityType, DomainFieldType, dimDomain, R, rT, rCT > & test_base_ne, const Stuff::LocalfunctionSetInterface< EntityType, DomainFieldType, dimDomain, R, rA, rCA > & ansatz_base_ne) const inline
Member Data Documentation
template<class DiffusionFactorImp, class DiffusionTensorImp = void, Method method = default_method> const size_t Dune::GDT::LocalEllipticIpdgIntegrands::Inner< DiffusionFactorImp, DiffusionTensorImp, method >::dimDomain = Traits::dimDomain static
The documentation for this class was generated from the following file:
local/integrands/elliptic-ipdg.hh