Dune::GDT::FVDiscretizationInterface< Traits > Class Template Reference
Dune::GDT::FVDiscretizationInterface< Traits > Class Template Reference
#include <dune/gdt/discretizations/interfaces.hh>
Public Types
typedef Traits::ProblemType ProblemType
typedef Traits::SpaceType SpaceType
typedef Traits::VectorType VectorType
typedef
Traits::DiscreteSolutionType DiscreteSolutionType
typedef DiscreteFunction
< SpaceType, VectorType > DiscreteFunctionType
Public Member Functions
Have to be implemented by any derived class.
const ProblemType & problem () const
const SpaceType & space () const
void solve (DiscreteSolutionType &solution) const
Provided by the interface for convenience.
DiscreteSolutionType solve () const
Member Typedef Documentation
template<class Traits> typedef DiscreteFunction<SpaceType, VectorType> Dune::GDT::FVDiscretizationInterface< Traits >::DiscreteFunctionType
template<class Traits> typedef Traits::DiscreteSolutionType Dune::GDT::FVDiscretizationInterface< Traits >::DiscreteSolutionType
template<class Traits> typedef Traits::ProblemType Dune::GDT::FVDiscretizationInterface< Traits >::ProblemType
template<class Traits> typedef Traits::SpaceType Dune::GDT::FVDiscretizationInterface< Traits >::SpaceType
template<class Traits> typedef Traits::VectorType Dune::GDT::FVDiscretizationInterface< Traits >::VectorType
Member Function Documentation
template<class Traits> const ProblemType& Dune::GDT::FVDiscretizationInterface< Traits >::problem () const inline
Referenced by Dune::GDT::FVDiscretizationInterface< internal::HyperbolicFVDefaultDiscretizationTraits< TestCaseImp, FVSpaceImp, numerical_flux, time_stepper_method, rhs_time_stepper_method > >::problem().
template<class Traits> void Dune::GDT::FVDiscretizationInterface< Traits >::solve (DiscreteSolutionType & solution) const inline
template<class Traits> DiscreteSolutionType Dune::GDT::FVDiscretizationInterface< Traits >::solve () const inline
Referenced by Dune::GDT::FVDiscretizationInterface< internal::HyperbolicFVDefaultDiscretizationTraits< TestCaseImp, FVSpaceImp, numerical_flux, time_stepper_method, rhs_time_stepper_method > >::solve().
template<class Traits> const SpaceType& Dune::GDT::FVDiscretizationInterface< Traits >::space () const inline
Referenced by Dune::GDT::FVDiscretizationInterface< internal::HyperbolicFVDefaultDiscretizationTraits< TestCaseImp, FVSpaceImp, numerical_flux, time_stepper_method, rhs_time_stepper_method > >::space().
The documentation for this class was generated from the following file:
discretizations/interfaces.hh