Dune::GDT::EllipticOperator< DiffusionFactorType, DiffusionTensorType, GridView, Field > Class Template Reference
Dune::GDT::EllipticOperator< DiffusionFactorType, DiffusionTensorType, GridView, Field > Class Template Reference
#include <dune/gdt/operators/elliptic.hh>
Public Types
typedef Traits::FieldType FieldType
typedef
internal::EllipticOperatorTraits
< DiffusionFactorType,
DiffusionTensorType,
GridViewType, Field >
::derived_type derived_type
Public Member Functions
template<class... Args>
EllipticOperator (const size_t over_integrate, GridViewType grid_view, Args &&...args)
template<class... Args>
EllipticOperator (GridViewType grid_view, Args &&...args)
template<class SourceSpaceType , class VectorType , class RangeSpaceType >
void apply (const DiscreteFunction< SourceSpaceType, VectorType > &source, DiscreteFunction< RangeSpaceType, VectorType > &range) const
template<class E , class D , size_t d, class R , size_t r, size_t rC>
FieldType apply2 (const Stuff::LocalizableFunctionInterface< E, D, d, R, r, rC > &range, const Stuff::LocalizableFunctionInterface< E, D, d, R, r, rC > &source) const
template<class RangeType , class SourceType >
void apply_inverse (const RangeType &, SourceType &, const Stuff::Common::Configuration &) const
std::vector< std::string > invert_options () const
Stuff::Common::Configuration invert_options (const std::string &) const
Methods that have to be implemented by any derived class
void apply (const SourceType &source, RangeType &range) const
FieldType apply2 (const RangeType &range, const SourceType &source) const
Provided by the interface for convenience
void apply_inverse (const RangeType &range, SourceType &source, const std::string &type) const
void apply_inverse (const RangeType &range, SourceType &source) const
FieldType induced_norm (const RangeType &range) const
Member Typedef Documentation
typedef internal::EllipticOperatorTraits< DiffusionFactorType, DiffusionTensorType, GridViewType, Field > ::derived_type Dune::GDT::OperatorInterface< internal::EllipticOperatorTraits< DiffusionFactorType, DiffusionTensorType, GridViewType, Field > >::derived_type inherited
template<class DiffusionFactorType , typename DiffusionTensorType , class GridView , class Field = typename DiffusionFactorType::RangeFieldType> typedef Traits::FieldType Dune::GDT::OperatorInterface< Traits >::FieldType
Constructor & Destructor Documentation
template<class DiffusionFactorType , typename DiffusionTensorType , class GridView , class Field = typename DiffusionFactorType::RangeFieldType> template<class... Args> Dune::GDT::EllipticOperator< DiffusionFactorType, DiffusionTensorType, GridView, Field >::EllipticOperator (const size_t over_integrate, GridViewType grid_view, Args &&... args) inline
template<class DiffusionFactorType , typename DiffusionTensorType , class GridView , class Field = typename DiffusionFactorType::RangeFieldType> template<class... Args> Dune::GDT::EllipticOperator< DiffusionFactorType, DiffusionTensorType, GridView, Field >::EllipticOperator (GridViewType grid_view, Args &&... args) inline
Member Function Documentation
void Dune::GDT::OperatorInterface< internal::EllipticOperatorTraits< DiffusionFactorType, DiffusionTensorType, GridViewType, Field > >::apply (const SourceType & source, RangeType & range) const inline inherited
template<class DiffusionFactorType , typename DiffusionTensorType , class GridView , class Field = typename DiffusionFactorType::RangeFieldType> template<class SourceSpaceType , class VectorType , class RangeSpaceType > void Dune::GDT::EllipticOperator< DiffusionFactorType, DiffusionTensorType, GridView, Field >::apply (const DiscreteFunction< SourceSpaceType, VectorType > & source, DiscreteFunction< RangeSpaceType, VectorType > & range) const inline
References Dune::GDT::LocalEllipticIntegrand< DiffusionFactorImp, DiffusionTensorImp >::diffusion_factor(), Dune::GDT::LocalEllipticIntegrand< DiffusionFactorImp, DiffusionTensorImp >::diffusion_tensor(), and Dune::GDT::ConstDiscreteFunction< SpaceImp, VectorImp >::space().
FieldType Dune::GDT::OperatorInterface< internal::EllipticOperatorTraits< DiffusionFactorType, DiffusionTensorType, GridViewType, Field > >::apply2 (const RangeType & range, const SourceType & source) const inline inherited
template<class DiffusionFactorType , typename DiffusionTensorType , class GridView , class Field = typename DiffusionFactorType::RangeFieldType> template<class E , class D , size_t d, class R , size_t r, size_t rC> FieldType Dune::GDT::EllipticOperator< DiffusionFactorType, DiffusionTensorType, GridView, Field >::apply2 (const Stuff::LocalizableFunctionInterface< E, D, d, R, r, rC > & range, const Stuff::LocalizableFunctionInterface< E, D, d, R, r, rC > & source) const inline
References Dune::GDT::LocalEllipticIntegrand< DiffusionFactorImp, DiffusionTensorImp >::diffusion_factor(), Dune::GDT::LocalEllipticIntegrand< DiffusionFactorImp, DiffusionTensorImp >::diffusion_tensor(), and Dune::GDT::make_elliptic_localizable_product().
void Dune::GDT::OperatorInterface< internal::EllipticOperatorTraits< DiffusionFactorType, DiffusionTensorType, GridViewType, Field > >::apply_inverse (const RangeType & range, SourceType & source, const std::string & type) const inline inherited
void Dune::GDT::OperatorInterface< internal::EllipticOperatorTraits< DiffusionFactorType, DiffusionTensorType, GridViewType, Field > >::apply_inverse (const RangeType & range, SourceType & source) const inline inherited
template<class DiffusionFactorType , typename DiffusionTensorType , class GridView , class Field = typename DiffusionFactorType::RangeFieldType> template<class RangeType , class SourceType > void Dune::GDT::EllipticOperator< DiffusionFactorType, DiffusionTensorType, GridView, Field >::apply_inverse (const RangeType & , SourceType & , const Stuff::Common::Configuration &) const inline
FieldType Dune::GDT::OperatorInterface< internal::EllipticOperatorTraits< DiffusionFactorType, DiffusionTensorType, GridViewType, Field > >::induced_norm (const RangeType & range) const inline inherited
template<class DiffusionFactorType , typename DiffusionTensorType , class GridView , class Field = typename DiffusionFactorType::RangeFieldType> std::vector<std::string> Dune::GDT::EllipticOperator< DiffusionFactorType, DiffusionTensorType, GridView, Field >::invert_options () const inline
template<class DiffusionFactorType , typename DiffusionTensorType , class GridView , class Field = typename DiffusionFactorType::RangeFieldType> Stuff::Common::Configuration Dune::GDT::EllipticOperator< DiffusionFactorType, DiffusionTensorType, GridView, Field >::invert_options (const std::string &) const inline
The documentation for this class was generated from the following file:
operators/elliptic.hh