Dune::GDT::LocalDiscreteFunction< SpaceImp, VectorImp > Class Template Reference
Dune::GDT::LocalDiscreteFunction< SpaceImp, VectorImp > Class Template Reference
#include <dune/gdt/local/discretefunction.hh>
Public Types
typedef BaseType::SpaceType SpaceType
typedef BaseType::VectorType VectorType
typedef BaseType::EntityType EntityType
typedef BaseType::DomainFieldType DomainFieldType
typedef BaseType::DomainType DomainType
typedef BaseType::RangeFieldType RangeFieldType
typedef BaseType::RangeType RangeType
typedef BaseType::JacobianRangeType JacobianRangeType
typedef LocalDoFVector
< VectorType > LocalDoFVectorType
typedef ConstLocalDoFVector
< VectorType > ConstLocalDoFVectorType
Public Member Functions
LocalDiscreteFunction (const SpaceType &sp, VectorType &globalVector, const EntityType &ent)
LocalDiscreteFunction (ThisType &&source)=default
previous comment questioned validity, defaulting this doesn't touch that question
LocalDiscreteFunction (const ThisType &other)=delete
ThisType & operator= (const ThisType &other)=delete
virtual ~LocalDiscreteFunction ()
LocalDoFVectorType & vector ()
const SpaceType & space () const
const BaseFunctionSetType & basis () const
const ConstLocalDoFVectorType & vector () const
virtual size_t order () const override
void evaluate (const DomainType &xx, RangeType &ret) const overridefinal
virtual void jacobian (const DomainType &xx, JacobianRangeType &ret) const overridefinal
Static Public Attributes
static const size_t dimDomain = BaseType::dimDomain
static const size_t dimRangeRows = BaseType::dimRangeCols
static const size_t dimRangeCols = BaseType::dimRangeCols
Protected Attributes
const SpaceType & space_
std::unique_ptr< const
BaseFunctionSetType > base_
Member Typedef Documentation
template<class SpaceImp , class VectorImp > typedef ConstLocalDoFVector<VectorType> Dune::GDT::ConstLocalDiscreteFunction< SpaceImp, VectorImp >::ConstLocalDoFVectorType inherited
template<class SpaceImp, class VectorImp> typedef BaseType::DomainFieldType Dune::GDT::LocalDiscreteFunction< SpaceImp, VectorImp >::DomainFieldType
template<class SpaceImp, class VectorImp> typedef BaseType::DomainType Dune::GDT::LocalDiscreteFunction< SpaceImp, VectorImp >::DomainType
template<class SpaceImp, class VectorImp> typedef BaseType::EntityType Dune::GDT::LocalDiscreteFunction< SpaceImp, VectorImp >::EntityType
template<class SpaceImp, class VectorImp> typedef BaseType::JacobianRangeType Dune::GDT::LocalDiscreteFunction< SpaceImp, VectorImp >::JacobianRangeType
template<class SpaceImp, class VectorImp> typedef LocalDoFVector<VectorType> Dune::GDT::LocalDiscreteFunction< SpaceImp, VectorImp >::LocalDoFVectorType
template<class SpaceImp, class VectorImp> typedef BaseType::RangeFieldType Dune::GDT::LocalDiscreteFunction< SpaceImp, VectorImp >::RangeFieldType
template<class SpaceImp, class VectorImp> typedef BaseType::RangeType Dune::GDT::LocalDiscreteFunction< SpaceImp, VectorImp >::RangeType
template<class SpaceImp, class VectorImp> typedef BaseType::SpaceType Dune::GDT::LocalDiscreteFunction< SpaceImp, VectorImp >::SpaceType
template<class SpaceImp, class VectorImp> typedef BaseType::VectorType Dune::GDT::LocalDiscreteFunction< SpaceImp, VectorImp >::VectorType
Constructor & Destructor Documentation
template<class SpaceImp, class VectorImp> Dune::GDT::LocalDiscreteFunction< SpaceImp, VectorImp >::LocalDiscreteFunction (const SpaceType & sp, VectorType & globalVector, const EntityType & ent) inline
References Dune::GDT::ConstLocalDiscreteFunction< SpaceImp, VectorImp >::base_.
template<class SpaceImp, class VectorImp> Dune::GDT::LocalDiscreteFunction< SpaceImp, VectorImp >::LocalDiscreteFunction (ThisType && source) default
previous comment questioned validity, defaulting this doesn't touch that question
template<class SpaceImp, class VectorImp> Dune::GDT::LocalDiscreteFunction< SpaceImp, VectorImp >::LocalDiscreteFunction (const ThisType & other) delete
template<class SpaceImp, class VectorImp> virtual Dune::GDT::LocalDiscreteFunction< SpaceImp, VectorImp >::~LocalDiscreteFunction () inline virtual
Member Function Documentation
template<class SpaceImp , class VectorImp > const BaseFunctionSetType& Dune::GDT::ConstLocalDiscreteFunction< SpaceImp, VectorImp >::basis () const inline inherited
References Dune::GDT::ConstLocalDiscreteFunction< SpaceImp, VectorImp >::base_.
Referenced by Dune::GDT::LocalL2ProjectionOperator::apply().
template<class SpaceImp , class VectorImp > void Dune::GDT::ConstLocalDiscreteFunction< SpaceImp, VectorImp >::evaluate (const DomainType & xx, RangeType & ret) const inline final override inherited
References Dune::GDT::ConstLocalDiscreteFunction< SpaceImp, VectorImp >::base_, and Dune::GDT::ConstLocalDiscreteFunction< SpaceImp, VectorImp >::localVector_.
Referenced by Dune::GDT::LocalRhsFvOperator< RHSEvaluationImp >::apply().
template<class SpaceImp , class VectorImp > virtual void Dune::GDT::ConstLocalDiscreteFunction< SpaceImp, VectorImp >::jacobian (const DomainType & xx, JacobianRangeType & ret) const inline final override virtual inherited
References Dune::GDT::ConstLocalDiscreteFunction< SpaceImp, VectorImp >::base_, and Dune::GDT::ConstLocalDiscreteFunction< SpaceImp, VectorImp >::localVector_.
template<class SpaceImp, class VectorImp> ThisType& Dune::GDT::LocalDiscreteFunction< SpaceImp, VectorImp >::operator= (const ThisType & other) delete
template<class SpaceImp , class VectorImp > virtual size_t Dune::GDT::ConstLocalDiscreteFunction< SpaceImp, VectorImp >::order () const inline override virtual inherited
References Dune::GDT::ConstLocalDiscreteFunction< SpaceImp, VectorImp >::base_.
template<class SpaceImp , class VectorImp > const SpaceType& Dune::GDT::ConstLocalDiscreteFunction< SpaceImp, VectorImp >::space () const inline inherited
References Dune::GDT::ConstLocalDiscreteFunction< SpaceImp, VectorImp >::space_.
Referenced by Dune::GDT::LocalDirichletProjectionOperator< BoundaryInfoType >::apply(), Dune::GDT::LocalLagrangeProjectionOperator::apply(), and Dune::GDT::LocalReconstructionFvOperator< MatrixImp, BoundaryValueFunctionImp, slope_limiter >::apply().
template<class SpaceImp , class VectorImp > const ConstLocalDoFVectorType& Dune::GDT::ConstLocalDiscreteFunction< SpaceImp, VectorImp >::vector () const inline inherited
References Dune::GDT::ConstLocalDiscreteFunction< SpaceImp, VectorImp >::localVector_.
template<class SpaceImp, class VectorImp> LocalDoFVectorType& Dune::GDT::LocalDiscreteFunction< SpaceImp, VectorImp >::vector () inline
Referenced by Dune::GDT::LocalDirichletProjectionOperator< BoundaryInfoType >::apply(), Dune::GDT::LocalLagrangeProjectionOperator::apply(), Dune::GDT::LocalL2ProjectionOperator::apply(), Dune::GDT::LocalCouplingFvOperator< NumericalFluxType >::apply(), Dune::GDT::LocalBoundaryFvOperator< NumericalFluxType >::apply(), Dune::GDT::LocalRhsFvOperator< RHSEvaluationImp >::apply(), and Dune::GDT::LocalReconstructionFvOperator< MatrixImp, BoundaryValueFunctionImp, slope_limiter >::apply().
Member Data Documentation
template<class SpaceImp , class VectorImp > std::unique_ptr<const BaseFunctionSetType> Dune::GDT::ConstLocalDiscreteFunction< SpaceImp, VectorImp >::base_ protected inherited
Referenced by Dune::GDT::ConstLocalDiscreteFunction< SpaceImp, VectorImp >::basis(), Dune::GDT::ConstLocalDiscreteFunction< SpaceImp, VectorImp >::ConstLocalDiscreteFunction(), Dune::GDT::ConstLocalDiscreteFunction< SpaceImp, VectorImp >::evaluate(), Dune::GDT::ConstLocalDiscreteFunction< SpaceImp, VectorImp >::jacobian(), Dune::GDT::LocalDiscreteFunction< SpaceImp, VectorImp >::LocalDiscreteFunction(), and Dune::GDT::ConstLocalDiscreteFunction< SpaceImp, VectorImp >::order().
template<class SpaceImp, class VectorImp> const size_t Dune::GDT::LocalDiscreteFunction< SpaceImp, VectorImp >::dimDomain = BaseType::dimDomain static
template<class SpaceImp, class VectorImp> const size_t Dune::GDT::LocalDiscreteFunction< SpaceImp, VectorImp >::dimRangeCols = BaseType::dimRangeCols static
template<class SpaceImp, class VectorImp> const size_t Dune::GDT::LocalDiscreteFunction< SpaceImp, VectorImp >::dimRangeRows = BaseType::dimRangeCols static
template<class SpaceImp , class VectorImp > const SpaceType& Dune::GDT::ConstLocalDiscreteFunction< SpaceImp, VectorImp >::space_ protected inherited
Referenced by Dune::GDT::ConstLocalDiscreteFunction< SpaceImp, VectorImp >::space().
The documentation for this class was generated from the following file:
discretefunction.hh