Dune::GDT::LaplaceMatrixOperator< RangeSpace, Matrix, GridView, SourceSpace, Field > Class Template Reference
Dune::GDT::LaplaceMatrixOperator< RangeSpace, Matrix, GridView, SourceSpace, Field > Class Template Reference
#include <dune/gdt/operators/laplace.hh>
Public Types
typedef
internal::MatrixOperatorBaseTraits
< MatrixImp, RangeSpaceImp,
GridViewImp, SourceSpaceImp,
FieldImp, pt > Traits
typedef
BaseAssemblerType::TestSpaceType RangeSpaceType
typedef
BaseAssemblerType::AnsatzSpaceType SourceSpaceType
typedef
Stuff::LA::SparsityPatternDefault PatternType
typedef MatrixImp MatrixType
typedef Traits::FieldType FieldType
typedef Traits::derived_type derived_type
typedef BaseType::GridViewType GridViewType
typedef RangeSpaceImp TestSpaceType
typedef SourceSpaceImp AnsatzSpaceType
typedef
TestSpaceType::RangeFieldType RangeFieldType
typedef BaseType::EntityType EntityType
typedef BaseType::IntersectionType IntersectionType
typedef
DSG::ApplyOn::WhichEntity
< GridViewType > ApplyOnWhichEntity
typedef
DSG::ApplyOn::WhichIntersection
< GridViewType > ApplyOnWhichIntersection
Public Member Functions
template<typename possibly_int_t , class... Args, typename std::enable_if<!std::is_same< possibly_int_t, tag< true >>::value &&!std::is_same< possibly_int_t, tag< false >>::value, int >::type = 0>
LaplaceMatrixOperator (possibly_int_t &&possibly_over_integrate, Args &&...args)
Creates a matrix-based Laplace operator.
const MatrixType & matrix () const
MatrixType & matrix ()
const SourceSpaceType & source_space () const
const RangeSpaceType & range_space () const
void add (const LocalVolumeTwoFormInterface< V > &local_volume_twoform, const DSG::ApplyOn::WhichEntity< GridViewType > *where=new DSG::ApplyOn::AllEntities< GridViewType >())
void add (const LocalCouplingTwoFormInterface< C > &local_coupling_twoform, const DSG::ApplyOn::WhichIntersection< GridViewType > *where=new DSG::ApplyOn::InnerIntersectionsPrimally< GridViewType >())
void add (const LocalBoundaryTwoFormInterface< B > &local_boundary_twoform, const DSG::ApplyOn::WhichIntersection< GridViewType > *where=new DSG::ApplyOn::InnerIntersectionsPrimally< GridViewType >())
void add (ConstraintsInterface< C > &constraints, const ApplyOnWhichEntity *where=new DSG::ApplyOn::AllEntities< GridViewType >())
void add (const LocalVolumeTwoFormAssembler< V > &local_assembler, Stuff::LA::MatrixInterface< M, RangeFieldType > &matrix, const ApplyOnWhichEntity *where=new DSG::ApplyOn::AllEntities< GridViewType >())
void add (const LocalCouplingTwoFormAssembler< V > &local_assembler, Stuff::LA::MatrixInterface< M, RangeFieldType > &matrix, const ApplyOnWhichIntersection *where=new DSG::ApplyOn::AllIntersections< GridViewType >())
void add (const LocalBoundaryTwoFormAssembler< V > &local_assembler, Stuff::LA::MatrixInterface< M, RangeFieldType > &matrix, const ApplyOnWhichIntersection *where=new DSG::ApplyOn::AllIntersections< GridViewType >())
void add (const LocalVolumeFunctionalAssembler< L > &local_assembler, Stuff::LA::VectorInterface< V, RangeFieldType > &vector, const ApplyOnWhichEntity *where=new DSG::ApplyOn::AllEntities< GridViewType >())
void add (const LocalFaceFunctionalAssembler< L > &local_assembler, Stuff::LA::VectorInterface< V, RangeFieldType > &vector, const ApplyOnWhichIntersection *where=new DSG::ApplyOn::AllIntersections< GridViewType >())
void apply (const Stuff::LA::VectorInterface< S > &source, Stuff::LA::VectorInterface< R > &range) const
void apply (const ConstDiscreteFunction< SourceSpaceType, S > &source, DiscreteFunction< RangeSpaceType, R > &range) const
FieldType apply2 (const Stuff::LA::VectorInterface< R > &range, const Stuff::LA::VectorInterface< S > &source) const
FieldType apply2 (const ConstDiscreteFunction< RangeSpaceType, R > &range, const ConstDiscreteFunction< SourceSpaceType, S > &source) const
void apply_inverse (const Stuff::LA::VectorInterface< R > &range, Stuff::LA::VectorInterface< S > &source, const Stuff::Common::Configuration &opts) const
void apply_inverse (const ConstDiscreteFunction< SourceSpaceType, R > &range, ConstDiscreteFunction< RangeSpaceType, S > &source, const Stuff::Common::Configuration &opts) const
std::vector< std::string > invert_options () const
Stuff::Common::Configuration invert_options (const std::string &type) const
const TestSpaceType & test_space () const
const AnsatzSpaceType & ansatz_space () const
void assemble (const bool use_tbb=false)
void assemble (const Partitioning &partitioning)
Methods that have to be implemented by any derived class
void apply (const SourceType &source, RangeType &range) const
FieldType apply2 (const RangeType &range, const SourceType &source) const
void apply_inverse (const RangeType &range, SourceType &source, const Stuff::Common::Configuration &opts) const
Provided by the interface for convenience
void apply_inverse (const RangeType &range, SourceType &source, const std::string &type) const
void apply_inverse (const RangeType &range, SourceType &source) const
FieldType induced_norm (const RangeType &range) const
Static Public Member Functions
static PatternType pattern (const RangeSpaceType &rng_spc, const SourceSpaceType &src_spc, const GridViewType &grd_vw)
static PatternType pattern (const RangeSpaceType &rng_spc)
static PatternType pattern (const RangeSpaceType &rng_spc, const SourceSpaceType &src_spc)
static PatternType pattern (const RangeSpaceType &rng_spc, const GridViewType &grd_vw)
Protected Attributes
const DS::PerThreadValue
< const TestSpaceType > test_space_
const DS::PerThreadValue
< const AnsatzSpaceType > ansatz_space_
Member Typedef Documentation
typedef SourceSpaceImp Dune::GDT::SystemAssembler< RangeSpaceImp , GridViewImp, SourceSpaceImp >::AnsatzSpaceType inherited
typedef DSG::ApplyOn::WhichEntity<GridViewType> Dune::GDT::SystemAssembler< RangeSpaceImp , GridViewImp, SourceSpaceImp >::ApplyOnWhichEntity inherited
typedef DSG::ApplyOn::WhichIntersection<GridViewType> Dune::GDT::SystemAssembler< RangeSpaceImp , GridViewImp, SourceSpaceImp >::ApplyOnWhichIntersection inherited
typedef Traits::derived_type Dune::GDT::OperatorInterface< Traits >::derived_type inherited
typedef BaseType::EntityType Dune::GDT::SystemAssembler< RangeSpaceImp , GridViewImp, SourceSpaceImp >::EntityType inherited
typedef Traits::FieldType Dune::GDT::OperatorInterface< Traits >::FieldType inherited
typedef BaseType::GridViewType Dune::GDT::SystemAssembler< TestSpaceImp, GridViewImp, AnsatzSpaceImp >::GridViewType inherited
typedef BaseType::IntersectionType Dune::GDT::SystemAssembler< RangeSpaceImp , GridViewImp, SourceSpaceImp >::IntersectionType inherited
typedef MatrixImp Dune::GDT::MatrixOperatorBase< Matrix , RangeSpace , GridView , SourceSpace , Field , pt >::MatrixType inherited
typedef Stuff::LA::SparsityPatternDefault Dune::GDT::MatrixOperatorBase< Matrix , RangeSpace , GridView , SourceSpace , Field , pt >::PatternType inherited
typedef TestSpaceType::RangeFieldType Dune::GDT::SystemAssembler< RangeSpaceImp , GridViewImp, SourceSpaceImp >::RangeFieldType inherited
typedef BaseAssemblerType::TestSpaceType Dune::GDT::MatrixOperatorBase< Matrix , RangeSpace , GridView , SourceSpace , Field , pt >::RangeSpaceType inherited
typedef BaseAssemblerType::AnsatzSpaceType Dune::GDT::MatrixOperatorBase< Matrix , RangeSpace , GridView , SourceSpace , Field , pt >::SourceSpaceType inherited
typedef RangeSpaceImp Dune::GDT::SystemAssembler< RangeSpaceImp , GridViewImp, SourceSpaceImp >::TestSpaceType inherited
typedef internal::MatrixOperatorBaseTraits<MatrixImp, RangeSpaceImp, GridViewImp, SourceSpaceImp, FieldImp, pt> Dune::GDT::MatrixOperatorBase< Matrix , RangeSpace , GridView , SourceSpace , Field , pt >::Traits inherited
Constructor & Destructor Documentation
template<class RangeSpace , class Matrix = typename Stuff::LA::Container<typename RangeSpace::RangeFieldType>::MatrixType, class GridView = typename RangeSpace::GridViewType, class SourceSpace = RangeSpace, class Field = typename RangeSpace::RangeFieldType> template<typename possibly_int_t , class... Args, typename std::enable_if<!std::is_same< possibly_int_t, tag< true >>::value &&!std::is_same< possibly_int_t, tag< false >>::value, int >::type = 0> Dune::GDT::LaplaceMatrixOperator< RangeSpace, Matrix, GridView, SourceSpace, Field >::LaplaceMatrixOperator (possibly_int_t && possibly_over_integrate, Args &&... args) inline explicit
Creates a matrix-based Laplace operator.
We suffer from the same problems as L2LocalizableProduct, see also the documentation of
See Also
L2LocalizableProduct::L2LocalizableProduct(). This ctor can be used as follows, where over_integrate is a non-negative integer and ...args are the arguments for MatrixOperatorBase (i.e., possibly a matrix, a range space, possibly a grid_view and possibly a source space):
LaplaceLocalizableProduct(over_integrate, ...args);
LaplaceLocalizableProduct(...args);
If no matrix is ´´These methods are provided by the interface for convenience.'', an appropriate matrix of given MatrixType will be created and is accessible via matrix().
Member Function Documentation
void Dune::GDT::SystemAssembler< RangeSpaceImp , GridViewImp, SourceSpaceImp >::add (ConstraintsInterface< C > & constraints, const ApplyOnWhichEntity * where = new DSG::ApplyOn::AllEntities<GridViewType>()) inline inherited
void Dune::GDT::SystemAssembler< RangeSpaceImp , GridViewImp, SourceSpaceImp >::add (const LocalVolumeTwoFormAssembler< V > & local_assembler, Stuff::LA::MatrixInterface< M, RangeFieldType > & matrix, const ApplyOnWhichEntity * where = new DSG::ApplyOn::AllEntities<GridViewType>()) inline inherited
void Dune::GDT::SystemAssembler< RangeSpaceImp , GridViewImp, SourceSpaceImp >::add (const LocalCouplingTwoFormAssembler< V > & local_assembler, Stuff::LA::MatrixInterface< M, RangeFieldType > & matrix, const ApplyOnWhichIntersection * where = new DSG::ApplyOn::AllIntersections<GridViewType>()) inline inherited
void Dune::GDT::SystemAssembler< RangeSpaceImp , GridViewImp, SourceSpaceImp >::add (const LocalBoundaryTwoFormAssembler< V > & local_assembler, Stuff::LA::MatrixInterface< M, RangeFieldType > & matrix, const ApplyOnWhichIntersection * where = new DSG::ApplyOn::AllIntersections<GridViewType>()) inline inherited
void Dune::GDT::SystemAssembler< RangeSpaceImp , GridViewImp, SourceSpaceImp >::add (const LocalVolumeFunctionalAssembler< L > & local_assembler, Stuff::LA::VectorInterface< V, RangeFieldType > & vector, const ApplyOnWhichEntity * where = new DSG::ApplyOn::AllEntities<GridViewType>()) inline inherited
void Dune::GDT::SystemAssembler< RangeSpaceImp , GridViewImp, SourceSpaceImp >::add (const LocalFaceFunctionalAssembler< L > & local_assembler, Stuff::LA::VectorInterface< V, RangeFieldType > & vector, const ApplyOnWhichIntersection * where = new DSG::ApplyOn::AllIntersections<GridViewType>()) inline inherited
void Dune::GDT::MatrixOperatorBase< Matrix , RangeSpace , GridView , SourceSpace , Field , pt >::add (const LocalVolumeTwoFormInterface< V > & local_volume_twoform, const DSG::ApplyOn::WhichEntity< GridViewType > * where = new DSG::ApplyOn::AllEntities<GridViewType>()) inline inherited
References Dune::GDT::SystemAssembler< RangeSpaceImp, GridViewImp, SourceSpaceImp >::ansatz_space_, and Dune::GDT::SystemAssembler< RangeSpaceImp, GridViewImp, SourceSpaceImp >::test_space_.
Referenced by Dune::GDT::EllipticMatrixOperator< Stuff::Functions::Constant< Stuff::Grid::Entity< GridView >::type, GridView::ctype, GridView::dimension, Field, 1 >, void, RangeSpace, Matrix, GridView, SourceSpace, Field >::EllipticMatrixOperator(), and Dune::GDT::WeightedL2MatrixOperator< Stuff::Functions::Constant< Stuff::Grid::Entity< GridView >::type, GridView::ctype, GridView::dimension, Field, 1 >, RangeSpace, Matrix, GridView, SourceSpace, Field >::WeightedL2MatrixOperator().
void Dune::GDT::MatrixOperatorBase< Matrix , RangeSpace , GridView , SourceSpace , Field , pt >::add (const LocalCouplingTwoFormInterface< C > & local_coupling_twoform, const DSG::ApplyOn::WhichIntersection< GridViewType > * where = new DSG::ApplyOn::InnerIntersectionsPrimally<GridViewType>()) inline inherited
References Dune::GDT::SystemAssembler< RangeSpaceImp, GridViewImp, SourceSpaceImp >::ansatz_space_, and Dune::GDT::SystemAssembler< RangeSpaceImp, GridViewImp, SourceSpaceImp >::test_space_.
void Dune::GDT::MatrixOperatorBase< Matrix , RangeSpace , GridView , SourceSpace , Field , pt >::add (const LocalBoundaryTwoFormInterface< B > & local_boundary_twoform, const DSG::ApplyOn::WhichIntersection< GridViewType > * where = new DSG::ApplyOn::InnerIntersectionsPrimally<GridViewType>()) inline inherited
References Dune::GDT::SystemAssembler< RangeSpaceImp, GridViewImp, SourceSpaceImp >::ansatz_space_, and Dune::GDT::SystemAssembler< RangeSpaceImp, GridViewImp, SourceSpaceImp >::test_space_.
const AnsatzSpaceType& Dune::GDT::SystemAssembler< RangeSpaceImp , GridViewImp, SourceSpaceImp >::ansatz_space () const inline inherited
Referenced by Dune::GDT::MatrixOperatorBase< Matrix, RangeSpace, GridView, SourceSpace, Field, ChoosePattern::volume >::source_space().
void Dune::GDT::OperatorInterface< internal::MatrixOperatorBaseTraits< MatrixImp, RangeSpaceImp, GridViewImp, SourceSpaceImp, FieldImp, pt > >::apply (const SourceType & source, RangeType & range) const inline inherited
void Dune::GDT::MatrixOperatorBase< Matrix , RangeSpace , GridView , SourceSpace , Field , pt >::apply (const Stuff::LA::VectorInterface< S > & source, Stuff::LA::VectorInterface< R > & range) const inline inherited
References Dune::GDT::SystemAssembler< TestSpaceImp, GridViewImp, AnsatzSpaceImp >::assemble(), and Dune::GDT::MatrixOperatorBase< M, RS, GV, SS, F, pt >::matrix().
void Dune::GDT::MatrixOperatorBase< Matrix , RangeSpace , GridView , SourceSpace , Field , pt >::apply (const ConstDiscreteFunction< SourceSpaceType, S > & source, DiscreteFunction< RangeSpaceType, R > & range) const inline inherited
References Dune::GDT::MatrixOperatorBase< M, RS, GV, SS, F, pt >::apply(), Dune::GDT::ConstDiscreteFunction< SpaceImp, VectorImp >::vector(), and Dune::GDT::DiscreteFunction< SpaceImp, VectorImp >::vector().
FieldType Dune::GDT::OperatorInterface< internal::MatrixOperatorBaseTraits< MatrixImp, RangeSpaceImp, GridViewImp, SourceSpaceImp, FieldImp, pt > >::apply2 (const RangeType & range, const SourceType & source) const inline inherited
FieldType Dune::GDT::MatrixOperatorBase< Matrix , RangeSpace , GridView , SourceSpace , Field , pt >::apply2 (const Stuff::LA::VectorInterface< R > & range, const Stuff::LA::VectorInterface< S > & source) const inline inherited
References Dune::GDT::SystemAssembler< TestSpaceImp, GridViewImp, AnsatzSpaceImp >::assemble(), and Dune::GDT::MatrixOperatorBase< M, RS, GV, SS, F, pt >::matrix().
FieldType Dune::GDT::MatrixOperatorBase< Matrix , RangeSpace , GridView , SourceSpace , Field , pt >::apply2 (const ConstDiscreteFunction< RangeSpaceType, R > & range, const ConstDiscreteFunction< SourceSpaceType, S > & source) const inline inherited
References Dune::GDT::MatrixOperatorBase< M, RS, GV, SS, F, pt >::apply2(), and Dune::GDT::ConstDiscreteFunction< SpaceImp, VectorImp >::vector().
void Dune::GDT::OperatorInterface< internal::MatrixOperatorBaseTraits< MatrixImp, RangeSpaceImp, GridViewImp, SourceSpaceImp, FieldImp, pt > >::apply_inverse (const RangeType & range, SourceType & source, const Stuff::Common::Configuration & opts) const inline inherited
void Dune::GDT::OperatorInterface< internal::MatrixOperatorBaseTraits< MatrixImp, RangeSpaceImp, GridViewImp, SourceSpaceImp, FieldImp, pt > >::apply_inverse (const RangeType & range, SourceType & source, const std::string & type) const inline inherited
void Dune::GDT::OperatorInterface< internal::MatrixOperatorBaseTraits< MatrixImp, RangeSpaceImp, GridViewImp, SourceSpaceImp, FieldImp, pt > >::apply_inverse (const RangeType & range, SourceType & source) const inline inherited
void Dune::GDT::MatrixOperatorBase< Matrix , RangeSpace , GridView , SourceSpace , Field , pt >::apply_inverse (const Stuff::LA::VectorInterface< R > & range, Stuff::LA::VectorInterface< S > & source, const Stuff::Common::Configuration & opts) const inline inherited
References Dune::GDT::SystemAssembler< RangeSpaceImp, GridViewImp, SourceSpaceImp >::assemble(), Dune::GDT::MatrixOperatorBase< M, RS, GV, SS, F, pt >::matrix(), and Dune::GDT::MatrixOperatorBase< M, RS, GV, SS, F, pt >::source_space().
void Dune::GDT::MatrixOperatorBase< Matrix , RangeSpace , GridView , SourceSpace , Field , pt >::apply_inverse (const ConstDiscreteFunction< SourceSpaceType, R > & range, ConstDiscreteFunction< RangeSpaceType, S > & source, const Stuff::Common::Configuration & opts) const inline inherited
References Dune::GDT::MatrixOperatorBase< M, RS, GV, SS, F, pt >::apply_inverse(), and Dune::GDT::ConstDiscreteFunction< SpaceImp, VectorImp >::vector().
void Dune::GDT::SystemAssembler< RangeSpaceImp , GridViewImp, SourceSpaceImp >::assemble (const bool use_tbb = false) inline inherited
Referenced by Dune::GDT::MatrixOperatorBase< Matrix, RangeSpace, GridView, SourceSpace, Field, ChoosePattern::volume >::apply_inverse().
void Dune::GDT::SystemAssembler< RangeSpaceImp , GridViewImp, SourceSpaceImp >::assemble (const Partitioning & partitioning) inline inherited
FieldType Dune::GDT::OperatorInterface< internal::MatrixOperatorBaseTraits< MatrixImp, RangeSpaceImp, GridViewImp, SourceSpaceImp, FieldImp, pt > >::induced_norm (const RangeType & range) const inline inherited
std::vector<std::string> Dune::GDT::MatrixOperatorBase< Matrix , RangeSpace , GridView , SourceSpace , Field , pt >::invert_options () const inline inherited
Stuff::Common::Configuration Dune::GDT::MatrixOperatorBase< Matrix , RangeSpace , GridView , SourceSpace , Field , pt >::invert_options (const std::string & type) const inline inherited
const MatrixType& Dune::GDT::MatrixOperatorBase< Matrix , RangeSpace , GridView , SourceSpace , Field , pt >::matrix () const inline inherited
MatrixType& Dune::GDT::MatrixOperatorBase< Matrix , RangeSpace , GridView , SourceSpace , Field , pt >::matrix () inline inherited
static PatternType Dune::GDT::MatrixOperatorBase< Matrix , RangeSpace , GridView , SourceSpace , Field , pt >::pattern (const RangeSpaceType & rng_spc, const SourceSpaceType & src_spc, const GridViewType & grd_vw) inline static inherited
static PatternType Dune::GDT::MatrixOperatorBase< Matrix , RangeSpace , GridView , SourceSpace , Field , pt >::pattern (const RangeSpaceType & rng_spc) inline static inherited
References Dune::GDT::MatrixOperatorBase< M, RS, GV, SS, F, pt >::pattern().
static PatternType Dune::GDT::MatrixOperatorBase< Matrix , RangeSpace , GridView , SourceSpace , Field , pt >::pattern (const RangeSpaceType & rng_spc, const SourceSpaceType & src_spc) inline static inherited
References Dune::GDT::MatrixOperatorBase< M, RS, GV, SS, F, pt >::pattern().
static PatternType Dune::GDT::MatrixOperatorBase< Matrix , RangeSpace , GridView , SourceSpace , Field , pt >::pattern (const RangeSpaceType & rng_spc, const GridViewType & grd_vw) inline static inherited
References Dune::GDT::MatrixOperatorBase< M, RS, GV, SS, F, pt >::pattern().
const RangeSpaceType& Dune::GDT::MatrixOperatorBase< Matrix , RangeSpace , GridView , SourceSpace , Field , pt >::range_space () const inline inherited
References Dune::GDT::SystemAssembler< RangeSpaceImp, GridViewImp, SourceSpaceImp >::test_space().
const SourceSpaceType& Dune::GDT::MatrixOperatorBase< Matrix , RangeSpace , GridView , SourceSpace , Field , pt >::source_space () const inline inherited
References Dune::GDT::SystemAssembler< RangeSpaceImp, GridViewImp, SourceSpaceImp >::ansatz_space().
const TestSpaceType& Dune::GDT::SystemAssembler< RangeSpaceImp , GridViewImp, SourceSpaceImp >::test_space () const inline inherited
Referenced by Dune::GDT::MatrixOperatorBase< Matrix, RangeSpace, GridView, SourceSpace, Field, ChoosePattern::volume >::range_space().
Member Data Documentation
const DS::PerThreadValue<const AnsatzSpaceType> Dune::GDT::SystemAssembler< RangeSpaceImp , GridViewImp, SourceSpaceImp >::ansatz_space_ protected inherited
Referenced by Dune::GDT::MatrixOperatorBase< Matrix, RangeSpace, GridView, SourceSpace, Field, ChoosePattern::volume >::add().
const DS::PerThreadValue<const TestSpaceType> Dune::GDT::SystemAssembler< RangeSpaceImp , GridViewImp, SourceSpaceImp >::test_space_ protected inherited
Referenced by Dune::GDT::MatrixOperatorBase< Matrix, RangeSpace, GridView, SourceSpace, Field, ChoosePattern::volume >::add().
The documentation for this class was generated from the following file:
laplace.hh