Dune::GDT::L2ProjectionLocalizableOperator< GridViewImp, SourceImp, RangeImp > Class Template Reference
Dune::GDT::L2ProjectionLocalizableOperator< GridViewImp, SourceImp, RangeImp > Class Template Reference
#include <dune/gdt/projections/l2.hh>
Public Types
typedef RangeType::VectorType VectorType
typedef Stuff::LA::Container
< typename
RangeType::RangeFieldType,
VectorType::sparse_matrix_type >
::MatrixType MatrixType
typedef SourceImp SourceType
typedef RangeImp RangeType
Public Member Functions
template<class... Args>
L2ProjectionLocalizableOperator (Args &&...args)
void apply ()
const SourceType & source () const
const RangeType & range () const
RangeType & range ()
template<class L >
void add (const LocalOperatorInterface< L > &local_operator, const DSG::ApplyOn::WhichEntity< GridViewType > *where=new DSG::ApplyOn::AllEntities< GridViewType >())
template<class T >
void add (const LocalCouplingOperatorInterface< T > &local_operator, const DSG::ApplyOn::WhichIntersection< GridViewType > *where=new DSG::ApplyOn::InnerIntersections< GridViewType >())
template<class T >
void add (const LocalBoundaryOperatorInterface< T > &local_operator, const DSG::ApplyOn::WhichIntersection< GridViewType > *where=new DSG::ApplyOn::BoundaryIntersections< GridViewType >())
Protected Attributes
const SourceType & source_
RangeType & range_
std::vector< std::unique_ptr
< DSG::internal::Codim0Object
< GridViewType > > > local_operators_codim_0
std::vector< std::unique_ptr
< DSG::internal::Codim1Object
< GridViewType > > > local_operators_codim_1
bool walked_
Member Typedef Documentation
template<class GridViewImp, class SourceImp, class RangeImp> typedef Stuff::LA::Container<typename RangeType::RangeFieldType, VectorType::sparse_matrix_type>::MatrixType Dune::GDT::L2GlobalProjectionLocalizableOperator< GridViewImp, SourceImp, RangeImp >::MatrixType inherited
template<class GridViewImp, class SourceImp, class RangeImp> typedef RangeImp Dune::GDT::LocalizableOperatorBase< GridViewImp, SourceImp, RangeImp >::RangeType inherited
template<class GridViewImp, class SourceImp, class RangeImp> typedef SourceImp Dune::GDT::LocalizableOperatorBase< GridViewImp, SourceImp, RangeImp >::SourceType inherited
template<class GridViewImp, class SourceImp, class RangeImp> typedef RangeType::VectorType Dune::GDT::L2GlobalProjectionLocalizableOperator< GridViewImp, SourceImp, RangeImp >::VectorType inherited
Constructor & Destructor Documentation
template<class GridViewImp , class SourceImp , class RangeImp > template<class... Args> Dune::GDT::L2ProjectionLocalizableOperator< GridViewImp, SourceImp, RangeImp >::L2ProjectionLocalizableOperator (Args &&... args) inline explicit
Member Function Documentation
template<class GridViewImp, class SourceImp, class RangeImp> template<class L > void Dune::GDT::LocalizableOperatorBase< GridViewImp, SourceImp, RangeImp >::add (const LocalOperatorInterface< L > & local_operator, const DSG::ApplyOn::WhichEntity< GridViewType > * where = new DSG::ApplyOn::AllEntities<GridViewType>()) inline inherited
Referenced by Dune::GDT::AdvectionRHSOperator< RHSEvaluationImp >::apply(), Dune::GDT::DirichletProjectionLocalizableOperator< GridViewImp, SourceImp, RangeImp, FieldImp >::DirichletProjectionLocalizableOperator(), Dune::GDT::L2GlobalProjectionLocalizableOperator< GridViewImp, ReinterpretDiscreteFunction< SourceImp >, RangeImp >::L2GlobalProjectionLocalizableOperator(), Dune::GDT::L2LocalProjectionLocalizableOperator< GridViewImp, ReinterpretDiscreteFunction< SourceImp >, RangeImp >::L2LocalProjectionLocalizableOperator(), and Dune::GDT::LagrangeProjectionLocalizableOperator< GridViewImp, ReinterpretDiscreteFunction< SourceImp >, RangeImp >::LagrangeProjectionLocalizableOperator().
template<class GridViewImp, class SourceImp, class RangeImp> template<class T > void Dune::GDT::LocalizableOperatorBase< GridViewImp, SourceImp, RangeImp >::add (const LocalCouplingOperatorInterface< T > & local_operator, const DSG::ApplyOn::WhichIntersection< GridViewType > * where = new DSG::ApplyOn::InnerIntersections<GridViewType>()) inline inherited
template<class GridViewImp, class SourceImp, class RangeImp> template<class T > void Dune::GDT::LocalizableOperatorBase< GridViewImp, SourceImp, RangeImp >::add (const LocalBoundaryOperatorInterface< T > & local_operator, const DSG::ApplyOn::WhichIntersection< GridViewType > * where = new DSG::ApplyOn::BoundaryIntersections<GridViewType>()) inline inherited
template<class GridViewImp, class SourceImp, class RangeImp> void Dune::GDT::L2GlobalProjectionLocalizableOperator< GridViewImp, SourceImp, RangeImp >::apply () inline inherited
Referenced by Dune::GDT::L2GlobalProjectionLocalizableOperator< GridViewImp, ReinterpretDiscreteFunction< SourceImp >, RangeImp >::apply(), and Dune::GDT::L2GlobalProjectionOperator< GridViewImp, FieldImp >::apply().
template<class GridViewImp, class SourceImp, class RangeImp> const RangeType& Dune::GDT::LocalizableOperatorBase< GridViewImp, SourceImp, RangeImp >::range () const inline inherited
Referenced by Dune::GDT::DirichletProjectionLocalizableOperator< GridViewImp, SourceImp, RangeImp, FieldImp >::DirichletProjectionLocalizableOperator(), Dune::GDT::L2GlobalProjectionLocalizableOperator< GridViewImp, ReinterpretDiscreteFunction< SourceImp >, RangeImp >::L2GlobalProjectionLocalizableOperator(), and Dune::GDT::L2LocalProjectionLocalizableOperator< GridViewImp, ReinterpretDiscreteFunction< SourceImp >, RangeImp >::L2LocalProjectionLocalizableOperator().
template<class GridViewImp, class SourceImp, class RangeImp> RangeType& Dune::GDT::LocalizableOperatorBase< GridViewImp, SourceImp, RangeImp >::range () inline inherited
template<class GridViewImp, class SourceImp, class RangeImp> const SourceType& Dune::GDT::LocalizableOperatorBase< GridViewImp, SourceImp, RangeImp >::source () const inline inherited
Member Data Documentation
template<class GridViewImp, class SourceImp, class RangeImp> std::vector<std::unique_ptr<DSG::internal::Codim0Object<GridViewType> > > Dune::GDT::LocalizableOperatorBase< GridViewImp, SourceImp, RangeImp >::local_operators_codim_0 protected inherited
Referenced by Dune::GDT::LocalizableOperatorBase< GridViewImp, ReinterpretDiscreteFunction< SourceImp >, RangeImp >::add().
template<class GridViewImp, class SourceImp, class RangeImp> std::vector<std::unique_ptr<DSG::internal::Codim1Object<GridViewType> > > Dune::GDT::LocalizableOperatorBase< GridViewImp, SourceImp, RangeImp >::local_operators_codim_1 protected inherited
Referenced by Dune::GDT::LocalizableOperatorBase< GridViewImp, ReinterpretDiscreteFunction< SourceImp >, RangeImp >::add().
template<class GridViewImp, class SourceImp, class RangeImp> RangeType& Dune::GDT::LocalizableOperatorBase< GridViewImp, SourceImp, RangeImp >::range_ protected inherited
Referenced by Dune::GDT::LocalizableOperatorBase< GridViewImp, ReinterpretDiscreteFunction< SourceImp >, RangeImp >::add(), Dune::GDT::L2GlobalProjectionLocalizableOperator< GridViewImp, ReinterpretDiscreteFunction< SourceImp >, RangeImp >::apply(), and Dune::GDT::LocalizableOperatorBase< GridViewImp, ReinterpretDiscreteFunction< SourceImp >, RangeImp >::range().
template<class GridViewImp, class SourceImp, class RangeImp> const SourceType& Dune::GDT::LocalizableOperatorBase< GridViewImp, SourceImp, RangeImp >::source_ protected inherited
Referenced by Dune::GDT::LocalizableOperatorBase< GridViewImp, ReinterpretDiscreteFunction< SourceImp >, RangeImp >::add(), and Dune::GDT::LocalizableOperatorBase< GridViewImp, ReinterpretDiscreteFunction< SourceImp >, RangeImp >::source().
template<class GridViewImp, class SourceImp, class RangeImp> bool Dune::GDT::LocalizableOperatorBase< GridViewImp, SourceImp, RangeImp >::walked_ protected inherited
Referenced by Dune::GDT::LocalizableOperatorBase< GridViewImp, ReinterpretDiscreteFunction< SourceImp >, RangeImp >::apply().
The documentation for this class was generated from the following file:
projections/l2.hh