Dune::GDT::L2VolumeVectorFunctional< FunctionType, Space, Vector, GridView, Field > Class Template Reference
Dune::GDT::L2VolumeVectorFunctional< FunctionType, Space, Vector, GridView, Field > Class Template Reference
#include <dune/gdt/functionals/l2.hh>
Public Types
typedef
internal::VectorFunctionalBaseTraits
< VectorImp, SpaceImp,
GridViewImp, FieldImp > Traits
typedef
BaseAssemblerType::AnsatzSpaceType SpaceType
typedef VectorImp VectorType
typedef BaseType::GridViewType GridViewType
typedef Traits::FieldType FieldType
typedef Traits::derived_type derived_type
typedef SpaceImp TestSpaceType
typedef SpaceImp AnsatzSpaceType
typedef
TestSpaceType::RangeFieldType RangeFieldType
typedef BaseType::EntityType EntityType
typedef BaseType::IntersectionType IntersectionType
typedef
DSG::ApplyOn::WhichEntity
< GridViewType > ApplyOnWhichEntity
typedef
DSG::ApplyOn::WhichIntersection
< GridViewType > ApplyOnWhichIntersection
Public Member Functions
template<class... Args>
L2VolumeVectorFunctional (const FunctionType &function, Args &&...args)
template<class... Args>
L2VolumeVectorFunctional (const size_t over_integrate, const FunctionType &function, Args &&...args)
const VectorType & vector () const
VectorType & vector ()
const SpaceType & space () const
void add (const LocalVolumeFunctionalInterface< Field > &local_volume_functional, const DSG::ApplyOn::WhichEntity< GridViewType > *where=new DSG::ApplyOn::AllEntities< GridViewType >())
void add (const LocalFaceFunctionalInterface< Field > &local_face_functional, const DSG::ApplyOn::WhichIntersection< GridViewType > *where=new DSG::ApplyOn::AllIntersections< GridViewType >())
void add (ConstraintsInterface< C > &constraints, const ApplyOnWhichEntity *where=new DSG::ApplyOn::AllEntities< GridViewType >())
void add (const LocalVolumeTwoFormAssembler< V > &local_assembler, Stuff::LA::MatrixInterface< M, RangeFieldType > &matrix, const ApplyOnWhichEntity *where=new DSG::ApplyOn::AllEntities< GridViewType >())
void add (const LocalCouplingTwoFormAssembler< V > &local_assembler, Stuff::LA::MatrixInterface< M, RangeFieldType > &matrix, const ApplyOnWhichIntersection *where=new DSG::ApplyOn::AllIntersections< GridViewType >())
void add (const LocalBoundaryTwoFormAssembler< V > &local_assembler, Stuff::LA::MatrixInterface< M, RangeFieldType > &matrix, const ApplyOnWhichIntersection *where=new DSG::ApplyOn::AllIntersections< GridViewType >())
void add (const LocalVolumeFunctionalAssembler< L > &local_assembler, Stuff::LA::VectorInterface< V, RangeFieldType > &vector, const ApplyOnWhichEntity *where=new DSG::ApplyOn::AllEntities< GridViewType >())
void add (const LocalFaceFunctionalAssembler< L > &local_assembler, Stuff::LA::VectorInterface< V, RangeFieldType > &vector, const ApplyOnWhichIntersection *where=new DSG::ApplyOn::AllIntersections< GridViewType >())
FieldType apply (const Stuff::LA::VectorInterface< Space > &source) const
FieldType apply (const ConstDiscreteFunction< SpaceType, Space > &source) const
FieldType apply (const SourceType &source) const
const TestSpaceType & test_space () const
const AnsatzSpaceType & ansatz_space () const
void assemble (const bool use_tbb=false)
void assemble (const Partitioning &partitioning)
Protected Attributes
const DS::PerThreadValue
< const TestSpaceType > test_space_
const DS::PerThreadValue
< const AnsatzSpaceType > ansatz_space_
Detailed Description
template<class FunctionType, class Space, class Vector = typename Stuff::LA::Container<typename Space::RangeFieldType>::VectorType, class GridView = typename Space::GridViewType, class Field = typename Space::RangeFieldType>
class Dune::GDT::L2VolumeVectorFunctional< FunctionType, Space, Vector, GridView, Field >
Todo:
Unit tests are missing for this class.
Note
We could add additional ctors which accept Stuff::Grid::ApplyOn::WhichEntity, analogously to L2FaceVectorFunctional (see below), but we did not need this until now.
Member Typedef Documentation
typedef SpaceImp Dune::GDT::SystemAssembler< SpaceImp , GridViewImp, SpaceImp >::AnsatzSpaceType inherited
typedef DSG::ApplyOn::WhichEntity<GridViewType> Dune::GDT::SystemAssembler< SpaceImp , GridViewImp, SpaceImp >::ApplyOnWhichEntity inherited
typedef DSG::ApplyOn::WhichIntersection<GridViewType> Dune::GDT::SystemAssembler< SpaceImp , GridViewImp, SpaceImp >::ApplyOnWhichIntersection inherited
typedef Traits::derived_type Dune::GDT::FunctionalInterface< Traits >::derived_type inherited
typedef BaseType::EntityType Dune::GDT::SystemAssembler< SpaceImp , GridViewImp, SpaceImp >::EntityType inherited
typedef Traits::FieldType Dune::GDT::FunctionalInterface< Traits >::FieldType inherited
typedef BaseType::GridViewType Dune::GDT::SystemAssembler< TestSpaceImp, GridViewImp, AnsatzSpaceImp >::GridViewType inherited
typedef BaseType::IntersectionType Dune::GDT::SystemAssembler< SpaceImp , GridViewImp, SpaceImp >::IntersectionType inherited
typedef TestSpaceType::RangeFieldType Dune::GDT::SystemAssembler< SpaceImp , GridViewImp, SpaceImp >::RangeFieldType inherited
typedef BaseAssemblerType::AnsatzSpaceType Dune::GDT::VectorFunctionalBase< Vector , Space , GridView , Field >::SpaceType inherited
typedef SpaceImp Dune::GDT::SystemAssembler< SpaceImp , GridViewImp, SpaceImp >::TestSpaceType inherited
typedef internal::VectorFunctionalBaseTraits<VectorImp, SpaceImp, GridViewImp, FieldImp> Dune::GDT::VectorFunctionalBase< Vector , Space , GridView , Field >::Traits inherited
typedef VectorImp Dune::GDT::VectorFunctionalBase< Vector , Space , GridView , Field >::VectorType inherited
Constructor & Destructor Documentation
template<class FunctionType, class Space, class Vector = typename Stuff::LA::Container<typename Space::RangeFieldType>::VectorType, class GridView = typename Space::GridViewType, class Field = typename Space::RangeFieldType> template<class... Args> Dune::GDT::L2VolumeVectorFunctional< FunctionType, Space, Vector, GridView, Field >::L2VolumeVectorFunctional (const FunctionType & function, Args &&... args) inline explicit
template<class FunctionType, class Space, class Vector = typename Stuff::LA::Container<typename Space::RangeFieldType>::VectorType, class GridView = typename Space::GridViewType, class Field = typename Space::RangeFieldType> template<class... Args> Dune::GDT::L2VolumeVectorFunctional< FunctionType, Space, Vector, GridView, Field >::L2VolumeVectorFunctional (const size_t over_integrate, const FunctionType & function, Args &&... args) inline explicit
Member Function Documentation
void Dune::GDT::SystemAssembler< SpaceImp , GridViewImp, SpaceImp >::add (ConstraintsInterface< C > & constraints, const ApplyOnWhichEntity * where = new DSG::ApplyOn::AllEntities<GridViewType>()) inline inherited
References Dune::GDT::SystemAssembler< TestSpaceImp, GridViewImp, AnsatzSpaceImp >::ansatz_space_, and Dune::GDT::SystemAssembler< TestSpaceImp, GridViewImp, AnsatzSpaceImp >::test_space_.
void Dune::GDT::SystemAssembler< SpaceImp , GridViewImp, SpaceImp >::add (const LocalVolumeTwoFormAssembler< V > & local_assembler, Stuff::LA::MatrixInterface< M, RangeFieldType > & matrix, const ApplyOnWhichEntity * where = new DSG::ApplyOn::AllEntities<GridViewType>()) inline inherited
References Dune::GDT::SystemAssembler< TestSpaceImp, GridViewImp, AnsatzSpaceImp >::ansatz_space_, and Dune::GDT::SystemAssembler< TestSpaceImp, GridViewImp, AnsatzSpaceImp >::test_space_.
void Dune::GDT::VectorFunctionalBase< Vector , Space , GridView , Field >::add (const LocalVolumeFunctionalInterface< Field > & local_volume_functional, const DSG::ApplyOn::WhichEntity< GridViewType > * where = new DSG::ApplyOn::AllEntities<GridViewType>()) inline inherited
References Dune::GDT::SystemAssembler< SpaceImp, GridViewImp >::test_space_.
Referenced by Dune::GDT::EllipticIpdgDirichletVectorFunctional< DirichletType, DiffusionFactorType, DiffusionTensorType, Space, method, Vector, GridView, Field >::EllipticIpdgDirichletVectorFunctional(), Dune::GDT::L2FaceVectorFunctional< FunctionType, Space, Vector, GridView, Field >::L2FaceVectorFunctional(), and Dune::GDT::L2VolumeVectorFunctional< SourceType, SpaceType, VectorType, GridViewType >::L2VolumeVectorFunctional().
void Dune::GDT::SystemAssembler< SpaceImp , GridViewImp, SpaceImp >::add (const LocalCouplingTwoFormAssembler< V > & local_assembler, Stuff::LA::MatrixInterface< M, RangeFieldType > & matrix, const ApplyOnWhichIntersection * where = new DSG::ApplyOn::AllIntersections<GridViewType>()) inline inherited
References Dune::GDT::SystemAssembler< TestSpaceImp, GridViewImp, AnsatzSpaceImp >::ansatz_space_, and Dune::GDT::SystemAssembler< TestSpaceImp, GridViewImp, AnsatzSpaceImp >::test_space_.
void Dune::GDT::VectorFunctionalBase< Vector , Space , GridView , Field >::add (const LocalFaceFunctionalInterface< Field > & local_face_functional, const DSG::ApplyOn::WhichIntersection< GridViewType > * where = new DSG::ApplyOn::AllIntersections<GridViewType>()) inline inherited
References Dune::GDT::SystemAssembler< SpaceImp, GridViewImp >::test_space_.
void Dune::GDT::SystemAssembler< SpaceImp , GridViewImp, SpaceImp >::add (const LocalBoundaryTwoFormAssembler< V > & local_assembler, Stuff::LA::MatrixInterface< M, RangeFieldType > & matrix, const ApplyOnWhichIntersection * where = new DSG::ApplyOn::AllIntersections<GridViewType>()) inline inherited
References Dune::GDT::SystemAssembler< TestSpaceImp, GridViewImp, AnsatzSpaceImp >::ansatz_space_, and Dune::GDT::SystemAssembler< TestSpaceImp, GridViewImp, AnsatzSpaceImp >::test_space_.
void Dune::GDT::SystemAssembler< SpaceImp , GridViewImp, SpaceImp >::add (const LocalVolumeFunctionalAssembler< L > & local_assembler, Stuff::LA::VectorInterface< V, RangeFieldType > & vector, const ApplyOnWhichEntity * where = new DSG::ApplyOn::AllEntities<GridViewType>()) inline inherited
References Dune::GDT::SystemAssembler< TestSpaceImp, GridViewImp, AnsatzSpaceImp >::test_space_.
void Dune::GDT::SystemAssembler< SpaceImp , GridViewImp, SpaceImp >::add (const LocalFaceFunctionalAssembler< L > & local_assembler, Stuff::LA::VectorInterface< V, RangeFieldType > & vector, const ApplyOnWhichIntersection * where = new DSG::ApplyOn::AllIntersections<GridViewType>()) inline inherited
References Dune::GDT::SystemAssembler< TestSpaceImp, GridViewImp, AnsatzSpaceImp >::test_space_.
const AnsatzSpaceType& Dune::GDT::SystemAssembler< SpaceImp , GridViewImp, SpaceImp >::ansatz_space () const inline inherited
References Dune::GDT::SystemAssembler< TestSpaceImp, GridViewImp, AnsatzSpaceImp >::ansatz_space_.
Referenced by Dune::GDT::VectorFunctionalBase< Vector, Space, GridView, Field >::space().
FieldType Dune::GDT::FunctionalInterface< internal::VectorFunctionalBaseTraits< VectorImp, SpaceImp, GridViewImp, FieldImp > >::apply (const SourceType & source) const inline inherited
References Dune::GDT::FunctionalInterface< Traits >::apply().
FieldType Dune::GDT::VectorFunctionalBase< Vector , Space , GridView , Field >::apply (const Stuff::LA::VectorInterface< Space > & source) const inline inherited
References Dune::GDT::SystemAssembler< TestSpaceImp, GridViewImp, AnsatzSpaceImp >::assemble(), and Dune::GDT::VectorFunctionalBase< V, S, GV, F >::vector().
FieldType Dune::GDT::VectorFunctionalBase< Vector , Space , GridView , Field >::apply (const ConstDiscreteFunction< SpaceType, Space > & source) const inline inherited
References Dune::GDT::VectorFunctionalBase< V, S, GV, F >::apply(), and Dune::GDT::ConstDiscreteFunction< SpaceImp, VectorImp >::vector().
void Dune::GDT::SystemAssembler< SpaceImp , GridViewImp, SpaceImp >::assemble (const bool use_tbb = false) inline inherited
void Dune::GDT::SystemAssembler< SpaceImp , GridViewImp, SpaceImp >::assemble (const Partitioning & partitioning) inline inherited
const SpaceType& Dune::GDT::VectorFunctionalBase< Vector , Space , GridView , Field >::space () const inline inherited
References Dune::GDT::SystemAssembler< SpaceImp, GridViewImp >::ansatz_space().
const TestSpaceType& Dune::GDT::SystemAssembler< SpaceImp , GridViewImp, SpaceImp >::test_space () const inline inherited
References Dune::GDT::SystemAssembler< TestSpaceImp, GridViewImp, AnsatzSpaceImp >::test_space_.
Referenced by Dune::GDT::VectorFunctionalBase< Vector, Space, GridView, Field >::VectorFunctionalBase().
const VectorType& Dune::GDT::VectorFunctionalBase< Vector , Space , GridView , Field >::vector () const inline inherited
VectorType& Dune::GDT::VectorFunctionalBase< Vector , Space , GridView , Field >::vector () inline inherited
Member Data Documentation
const DS::PerThreadValue<const AnsatzSpaceType> Dune::GDT::SystemAssembler< SpaceImp , GridViewImp, SpaceImp >::ansatz_space_ protected inherited
const DS::PerThreadValue<const TestSpaceType> Dune::GDT::SystemAssembler< SpaceImp , GridViewImp, SpaceImp >::test_space_ protected inherited
Referenced by Dune::GDT::VectorFunctionalBase< Vector, Space, GridView, Field >::add().
The documentation for this class was generated from the following file:
functionals/l2.hh