Dune::GDT::LinearReconstructionLocalizable< SourceImp, RangeImp, BoundaryValueFunctionImp, MatrixImp, slope_limiter > Class Template Reference
Dune::GDT::LinearReconstructionLocalizable< SourceImp, RangeImp, BoundaryValueFunctionImp, MatrixImp, slope_limiter > Class Template Reference
#include <dune/gdt/operators/fv.hh>
Public Types
typedef SourceImp SourceType
typedef RangeImp RangeType
typedef BoundaryValueFunctionImp BoundaryValueFunctionType
typedef MatrixImp MatrixType
typedef SourceType::RangeFieldType RangeFieldType
typedef
RangeType::SpaceType::GridViewType GridViewType
typedef
Dune::GDT::LocalReconstructionFvOperator
< MatrixType,
BoundaryValueFunctionType,
slope_limiter > LocalOperatorType
Public Member Functions
LinearReconstructionLocalizable (const SourceType &source, RangeType &range, const MatrixType &eigenvectors, const MatrixType &eigenvectors_inverse, const BoundaryValueFunctionType &boundary_values)
const SourceType & source () const
const RangeType & range () const
RangeType & range ()
void add (const LocalOperatorInterface< L > &local_operator, const DSG::ApplyOn::WhichEntity< GridViewType > *where=new DSG::ApplyOn::AllEntities< GridViewType >())
void add (const LocalCouplingOperatorInterface< T > &local_operator, const DSG::ApplyOn::WhichIntersection< GridViewType > *where=new DSG::ApplyOn::InnerIntersections< GridViewType >())
void add (const LocalBoundaryOperatorInterface< T > &local_operator, const DSG::ApplyOn::WhichIntersection< GridViewType > *where=new DSG::ApplyOn::BoundaryIntersections< GridViewType >())
void apply ()
Static Public Attributes
static const size_t dimDomain = GridViewType::dimension
Protected Attributes
std::vector< std::unique_ptr
< DSG::internal::Codim0Object
< GridViewType > > > local_operators_codim_0
std::vector< std::unique_ptr
< DSG::internal::Codim1Object
< GridViewType > > > local_operators_codim_1
bool walked_
Member Typedef Documentation
template<class SourceImp , class RangeImp , class BoundaryValueFunctionImp , class MatrixImp , SlopeLimiters slope_limiter> typedef BoundaryValueFunctionImp Dune::GDT::LinearReconstructionLocalizable< SourceImp, RangeImp, BoundaryValueFunctionImp, MatrixImp, slope_limiter >::BoundaryValueFunctionType
template<class SourceImp , class RangeImp , class BoundaryValueFunctionImp , class MatrixImp , SlopeLimiters slope_limiter> typedef RangeType::SpaceType::GridViewType Dune::GDT::LinearReconstructionLocalizable< SourceImp, RangeImp, BoundaryValueFunctionImp, MatrixImp, slope_limiter >::GridViewType
template<class SourceImp , class RangeImp , class BoundaryValueFunctionImp , class MatrixImp , SlopeLimiters slope_limiter> typedef Dune::GDT::LocalReconstructionFvOperator<MatrixType, BoundaryValueFunctionType, slope_limiter> Dune::GDT::LinearReconstructionLocalizable< SourceImp, RangeImp, BoundaryValueFunctionImp, MatrixImp, slope_limiter >::LocalOperatorType
template<class SourceImp , class RangeImp , class BoundaryValueFunctionImp , class MatrixImp , SlopeLimiters slope_limiter> typedef MatrixImp Dune::GDT::LinearReconstructionLocalizable< SourceImp, RangeImp, BoundaryValueFunctionImp, MatrixImp, slope_limiter >::MatrixType
template<class SourceImp , class RangeImp , class BoundaryValueFunctionImp , class MatrixImp , SlopeLimiters slope_limiter> typedef SourceType::RangeFieldType Dune::GDT::LinearReconstructionLocalizable< SourceImp, RangeImp, BoundaryValueFunctionImp, MatrixImp, slope_limiter >::RangeFieldType
template<class SourceImp , class RangeImp , class BoundaryValueFunctionImp , class MatrixImp , SlopeLimiters slope_limiter> typedef RangeImp Dune::GDT::LinearReconstructionLocalizable< SourceImp, RangeImp, BoundaryValueFunctionImp, MatrixImp, slope_limiter >::RangeType
template<class SourceImp , class RangeImp , class BoundaryValueFunctionImp , class MatrixImp , SlopeLimiters slope_limiter> typedef SourceImp Dune::GDT::LinearReconstructionLocalizable< SourceImp, RangeImp, BoundaryValueFunctionImp, MatrixImp, slope_limiter >::SourceType
Constructor & Destructor Documentation
template<class SourceImp , class RangeImp , class BoundaryValueFunctionImp , class MatrixImp , SlopeLimiters slope_limiter> Dune::GDT::LinearReconstructionLocalizable< SourceImp, RangeImp, BoundaryValueFunctionImp, MatrixImp, slope_limiter >::LinearReconstructionLocalizable (const SourceType & source, RangeType & range, const MatrixType & eigenvectors, const MatrixType & eigenvectors_inverse, const BoundaryValueFunctionType & boundary_values) inline
References Dune::GDT::LocalizableOperatorBase< RangeImp::SpaceType::GridViewType, SourceImp, RangeImp >::add().
Member Function Documentation
void Dune::GDT::LocalizableOperatorBase< RangeImp::SpaceType::GridViewType , SourceImp, RangeImp >::add (const LocalOperatorInterface< L > & local_operator, const DSG::ApplyOn::WhichEntity< GridViewType > * where = new DSG::ApplyOn::AllEntities<GridViewType>()) inline inherited
Referenced by Dune::GDT::AdvectionLocalizableDefault< AnalyticalFluxImp, NumericalCouplingFluxImp, NumericalBoundaryFluxImp, BoundaryValueFunctionImp, SourceImp, RangeImp >::AdvectionLocalizableDefault(), and Dune::GDT::LinearReconstructionLocalizable< SourceImp, RangeImp, BoundaryValueFunctionImp, MatrixImp, slope_limiter >::LinearReconstructionLocalizable().
void Dune::GDT::LocalizableOperatorBase< RangeImp::SpaceType::GridViewType , SourceImp, RangeImp >::add (const LocalCouplingOperatorInterface< T > & local_operator, const DSG::ApplyOn::WhichIntersection< GridViewType > * where = new DSG::ApplyOn::InnerIntersections<GridViewType>()) inline inherited
void Dune::GDT::LocalizableOperatorBase< RangeImp::SpaceType::GridViewType , SourceImp, RangeImp >::add (const LocalBoundaryOperatorInterface< T > & local_operator, const DSG::ApplyOn::WhichIntersection< GridViewType > * where = new DSG::ApplyOn::BoundaryIntersections<GridViewType>()) inline inherited
void Dune::GDT::LocalizableOperatorBase< RangeImp::SpaceType::GridViewType , SourceImp, RangeImp >::apply () inline inherited
const RangeType& Dune::GDT::LocalizableOperatorBase< RangeImp::SpaceType::GridViewType , SourceImp, RangeImp >::range () const inline inherited
RangeType& Dune::GDT::LocalizableOperatorBase< RangeImp::SpaceType::GridViewType , SourceImp, RangeImp >::range () inline inherited
const SourceType& Dune::GDT::LocalizableOperatorBase< RangeImp::SpaceType::GridViewType , SourceImp, RangeImp >::source () const inline inherited
Member Data Documentation
template<class SourceImp , class RangeImp , class BoundaryValueFunctionImp , class MatrixImp , SlopeLimiters slope_limiter> const size_t Dune::GDT::LinearReconstructionLocalizable< SourceImp, RangeImp, BoundaryValueFunctionImp, MatrixImp, slope_limiter >::dimDomain = GridViewType::dimension static
std::vector<std::unique_ptr<DSG::internal::Codim0Object<GridViewType> > > Dune::GDT::LocalizableOperatorBase< RangeImp::SpaceType::GridViewType , SourceImp, RangeImp >::local_operators_codim_0 protected inherited
std::vector<std::unique_ptr<DSG::internal::Codim1Object<GridViewType> > > Dune::GDT::LocalizableOperatorBase< RangeImp::SpaceType::GridViewType , SourceImp, RangeImp >::local_operators_codim_1 protected inherited
bool Dune::GDT::LocalizableOperatorBase< RangeImp::SpaceType::GridViewType , SourceImp, RangeImp >::walked_ protected inherited
The documentation for this class was generated from the following file:
operators/fv.hh