Dune::GDT::LocalLagrangeProjectionOperator Class Reference
Dune::GDT::LocalLagrangeProjectionOperator Class Reference
#include <dune/gdt/local/operators/lagrange-projection.hh>
Public Types
typedef
internal::LocalLagrangeProjectionOperatorTraits Traits
typedef
internal::LocalLagrangeProjectionOperatorTraits::derived_type derived_type
Public Member Functions
template<class E , class D , size_t d, class R , class RangeSpaceType , class VectorType >
std::enable_if< StaticCheck< E,
D, d, R, 1, 1, RangeSpaceType,
VectorType >::value, void >
::type apply (const Stuff::LocalizableFunctionInterface< E, D, d, R, 1, 1 > &source, LocalDiscreteFunction< RangeSpaceType, VectorType > &local_range) const
Applies the Lagrange projection locally.
template<class E , class D , size_t d, class R , size_t r, class RangeSpaceType , class VectorType >
std::enable_if< StaticCheck< E,
D, d, R, r, 1, RangeSpaceType,
VectorType >::value, void >
::type apply (const Stuff::LocalizableFunctionInterface< E, D, d, R, r, 1 > &source, LocalDiscreteFunction< RangeSpaceType, VectorType > &local_range) const
Applies the Lagrange projection locally (for vector-valued functions)
void apply (const SourceType &source, LocalDiscreteFunction< RangeSpaceType, VectorType > &local_range) const
Applies the local operator.
Member Typedef Documentation
typedef internal::LocalLagrangeProjectionOperatorTraits ::derived_type Dune::GDT::LocalOperatorInterface< internal::LocalLagrangeProjectionOperatorTraits >::derived_type inherited
typedef internal::LocalLagrangeProjectionOperatorTraits Dune::GDT::LocalLagrangeProjectionOperator::Traits
Member Function Documentation
template<class E , class D , size_t d, class R , class RangeSpaceType , class VectorType > std::enable_if<StaticCheck<E, D, d, R, 1, 1, RangeSpaceType, VectorType>::value, void>::type Dune::GDT::LocalLagrangeProjectionOperator::apply (const Stuff::LocalizableFunctionInterface< E, D, d, R, 1, 1 > & source, LocalDiscreteFunction< RangeSpaceType, VectorType > & local_range) const inline
Applies the Lagrange projection locally.
References Dune::GDT::ConstLocalDiscreteFunction< SpaceImp, VectorImp >::space(), and Dune::GDT::LocalDiscreteFunction< SpaceImp, VectorImp >::vector().
void Dune::GDT::LocalOperatorInterface< internal::LocalLagrangeProjectionOperatorTraits >::apply (const SourceType & source, LocalDiscreteFunction< RangeSpaceType, VectorType > & local_range) const inline inherited
Applies the local operator.
Parameters
source Should be a Stuff::LocalizableFunctionInterface or a ConstDiscreteFunction.
template<class E , class D , size_t d, class R , size_t r, class RangeSpaceType , class VectorType > std::enable_if<StaticCheck<E, D, d, R, r, 1, RangeSpaceType, VectorType>::value, void>::type Dune::GDT::LocalLagrangeProjectionOperator::apply (const Stuff::LocalizableFunctionInterface< E, D, d, R, r, 1 > & source, LocalDiscreteFunction< RangeSpaceType, VectorType > & local_range) const inline
Applies the Lagrange projection locally (for vector-valued functions)
Attention
This is the old implementation which will throw a NotImplemented error. If you need this, test and correct the implementation!
References Dune::GDT::ConstLocalDiscreteFunction< SpaceImp, VectorImp >::space(), and Dune::GDT::LocalDiscreteFunction< SpaceImp, VectorImp >::vector().
The documentation for this class was generated from the following file:
lagrange-projection.hh