Dune::GDT::LagrangeProjectionOperator< GridViewImp, FieldImp > Class Template Reference
Dune::GDT::LagrangeProjectionOperator< GridViewImp, FieldImp > Class Template Reference
#include <dune/gdt/projections/lagrange.hh>
Public Types
typedef
internal::LagrangeProjectionOperatorTraits
< GridViewImp, FieldImp > Traits
typedef GridViewImp GridViewType
typedef Traits::FieldType FieldType
typedef
internal::LagrangeProjectionOperatorTraits
< GridViewImp, FieldImp >
::derived_type derived_type
Public Member Functions
LagrangeProjectionOperator (GridViewType grid_view)
template<class R , size_t r, size_t rC, class S , class V >
void apply (const Stuff::LocalizableFunctionInterface< E, D, d, R, r, rC > &source, DiscreteFunction< S, V > &range) const
template<class RangeType , class SourceType >
FieldType apply2 (const RangeType &, const SourceType &) const
template<class RangeType , class SourceType >
void apply_inverse (const RangeType &, SourceType &, const Stuff::Common::Configuration &) const
std::vector< std::string > invert_options () const
Stuff::Common::Configuration invert_options (const std::string &) const
Methods that have to be implemented by any derived class
void apply (const SourceType &source, RangeType &range) const
Provided by the interface for convenience
void apply_inverse (const RangeType &range, SourceType &source, const std::string &type) const
void apply_inverse (const RangeType &range, SourceType &source) const
FieldType induced_norm (const RangeType &range) const
Member Typedef Documentation
typedef internal::LagrangeProjectionOperatorTraits< GridViewImp, FieldImp > ::derived_type Dune::GDT::OperatorInterface< internal::LagrangeProjectionOperatorTraits< GridViewImp, FieldImp > >::derived_type inherited
template<class GridViewImp , class FieldImp = double> typedef Traits::FieldType Dune::GDT::OperatorInterface< Traits >::FieldType
template<class GridViewImp , class FieldImp = double> typedef GridViewImp Dune::GDT::LagrangeProjectionOperator< GridViewImp, FieldImp >::GridViewType
template<class GridViewImp , class FieldImp = double> typedef internal::LagrangeProjectionOperatorTraits<GridViewImp, FieldImp> Dune::GDT::LagrangeProjectionOperator< GridViewImp, FieldImp >::Traits
Constructor & Destructor Documentation
template<class GridViewImp , class FieldImp = double> Dune::GDT::LagrangeProjectionOperator< GridViewImp, FieldImp >::LagrangeProjectionOperator (GridViewType grid_view) inline
Member Function Documentation
void Dune::GDT::OperatorInterface< internal::LagrangeProjectionOperatorTraits< GridViewImp, FieldImp > >::apply (const SourceType & source, RangeType & range) const inline inherited
References Dune::GDT::OperatorInterface< Traits >::apply().
template<class GridViewImp , class FieldImp = double> template<class R , size_t r, size_t rC, class S , class V > void Dune::GDT::LagrangeProjectionOperator< GridViewImp, FieldImp >::apply (const Stuff::LocalizableFunctionInterface< E, D, d, R, r, rC > & source, DiscreteFunction< S, V > & range) const inline
References Dune::GDT::make_lagrange_projection_localizable_operator().
template<class GridViewImp , class FieldImp = double> template<class RangeType , class SourceType > FieldType Dune::GDT::LagrangeProjectionOperator< GridViewImp, FieldImp >::apply2 (const RangeType & , const SourceType &) const inline
void Dune::GDT::OperatorInterface< internal::LagrangeProjectionOperatorTraits< GridViewImp, FieldImp > >::apply_inverse (const RangeType & range, SourceType & source, const std::string & type) const inline inherited
References Dune::GDT::OperatorInterface< Traits >::apply_inverse(), and Dune::GDT::OperatorInterface< Traits >::invert_options().
void Dune::GDT::OperatorInterface< internal::LagrangeProjectionOperatorTraits< GridViewImp, FieldImp > >::apply_inverse (const RangeType & range, SourceType & source) const inline inherited
References Dune::GDT::OperatorInterface< Traits >::apply_inverse(), and Dune::GDT::OperatorInterface< Traits >::invert_options().
template<class GridViewImp , class FieldImp = double> template<class RangeType , class SourceType > void Dune::GDT::LagrangeProjectionOperator< GridViewImp, FieldImp >::apply_inverse (const RangeType & , SourceType & , const Stuff::Common::Configuration &) const inline
FieldType Dune::GDT::OperatorInterface< internal::LagrangeProjectionOperatorTraits< GridViewImp, FieldImp > >::induced_norm (const RangeType & range) const inline inherited
References Dune::GDT::OperatorInterface< Traits >::apply2().
template<class GridViewImp , class FieldImp = double> std::vector<std::string> Dune::GDT::LagrangeProjectionOperator< GridViewImp, FieldImp >::invert_options () const inline
template<class GridViewImp , class FieldImp = double> Stuff::Common::Configuration Dune::GDT::LagrangeProjectionOperator< GridViewImp, FieldImp >::invert_options (const std::string &) const inline
The documentation for this class was generated from the following file:
projections/lagrange.hh