Dune::GDT::LocalEllipticIntegrand< DiffusionFactorImp, DiffusionTensorImp > Class Template Reference
Dune::GDT::LocalEllipticIntegrand< DiffusionFactorImp, DiffusionTensorImp > Class Template Reference
Computes an elliptic evaluation.
#include <dune/gdt/local/integrands/elliptic.hh>
Public Types
typedef
internal::LocalEllipticIntegrandTraits
< DiffusionFactorImp,
DiffusionTensorImp > Traits
typedef Traits::DiffusionFactorType DiffusionFactorType
typedef Traits::DiffusionTensorType DiffusionTensorType
typedef
Traits::LocalfunctionTupleType LocalfunctionTupleType
typedef Traits::EntityType EntityType
typedef Traits::DomainFieldType DomainFieldType
Public Member Functions
LocalEllipticIntegrand (const DiffusionFactorType &diffusion_factor, const DiffusionTensorType &diffusion_tensor)
LocalEllipticIntegrand (const DiffusionFactorType &diffusion_factor)
template<typename DiffusionType , typename = typename std::enable_if<(std::is_same<DiffusionType, DiffusionTensorType>::value) && (dimDomain > 1>
LocalEllipticIntegrand (const DiffusionType &diffusion)
LocalEllipticIntegrand (const ThisType &other)=default
LocalEllipticIntegrand (ThisType &&source)=default
Required by LocalVolumeIntegrandInterface< ..., 2 >
LocalfunctionTupleType localFunctions (const EntityType &entity) const
template<class R , size_t rT, size_t rCT, size_t rA, size_t rCA>
size_t order (const LocalfunctionTupleType &local_functions_tuple, const Stuff::LocalfunctionSetInterface< E, D, d, R, rT, rCT > &test_base, const Stuff::LocalfunctionSetInterface< E, D, d, R, rA, rCA > &ansatz_base) const
extracts the local functions and calls the correct order() method
template<class R , size_t rT, size_t rCT, size_t rA, size_t rCA>
void evaluate (const LocalfunctionTupleType &local_functions_tuple, const Stuff::LocalfunctionSetInterface< E, D, d, R, rT, rCT > &test_base, const Stuff::LocalfunctionSetInterface< E, D, d, R, rA, rCA > &ansatz_base, const Dune::FieldVector< D, d > &localPoint, Dune::DynamicMatrix< R > &ret) const
extracts the local functions and calls the correct evaluate() method
Actual implementations of order
template<class R , size_t rDF, size_t rCDF, size_t rDT, size_t rCDT, size_t rT, size_t rCT, size_t rA, size_t rCA>
size_t order (const Stuff::LocalfunctionInterface< E, D, d, R, rDF, rCDF > &local_diffusion_factor, const Stuff::LocalfunctionInterface< E, D, d, R, rDT, rCDT > &local_diffusion_tensor, const Stuff::LocalfunctionSetInterface< E, D, d, R, rT, rCT > &test_base, const Stuff::LocalfunctionSetInterface< E, D, d, R, rA, rCA > &ansatz_base) const
Actual implementations of evaluate
template<class R , size_t r>
void evaluate (const Stuff::LocalfunctionInterface< E, D, d, R, 1, 1 > &local_diffusion_factor, const Stuff::LocalfunctionInterface< E, D, d, R, d, d > &local_diffusion_tensor, const Stuff::LocalfunctionSetInterface< E, D, d, R, r, 1 > &test_base, const Stuff::LocalfunctionSetInterface< E, D, d, R, r, 1 > &ansatz_base, const Dune::FieldVector< D, d > &localPoint, Dune::DynamicMatrix< R > &ret) const
Access to data functions (allows the evaluation to be used as traits handling multiple szenarios).
const DiffusionFactorType & diffusion_factor () const
const DiffusionTensorType & diffusion_tensor () const
Static Public Attributes
static const size_t dimDomain = Traits::dimDomain
Detailed Description
template<class DiffusionFactorImp, class DiffusionTensorImp = void>
class Dune::GDT::LocalEllipticIntegrand< DiffusionFactorImp, DiffusionTensorImp >
Computes an elliptic evaluation.
Member Typedef Documentation
template<class DiffusionFactorImp , class DiffusionTensorImp = void> typedef Traits::DiffusionFactorType Dune::GDT::LocalEllipticIntegrand< DiffusionFactorImp, DiffusionTensorImp >::DiffusionFactorType
template<class DiffusionFactorImp , class DiffusionTensorImp = void> typedef Traits::DiffusionTensorType Dune::GDT::LocalEllipticIntegrand< DiffusionFactorImp, DiffusionTensorImp >::DiffusionTensorType
template<class DiffusionFactorImp , class DiffusionTensorImp = void> typedef Traits::DomainFieldType Dune::GDT::LocalEllipticIntegrand< DiffusionFactorImp, DiffusionTensorImp >::DomainFieldType
template<class DiffusionFactorImp , class DiffusionTensorImp = void> typedef Traits::EntityType Dune::GDT::LocalEllipticIntegrand< DiffusionFactorImp, DiffusionTensorImp >::EntityType
template<class DiffusionFactorImp , class DiffusionTensorImp = void> typedef Traits::LocalfunctionTupleType Dune::GDT::LocalEllipticIntegrand< DiffusionFactorImp, DiffusionTensorImp >::LocalfunctionTupleType
template<class DiffusionFactorImp , class DiffusionTensorImp = void> typedef internal::LocalEllipticIntegrandTraits<DiffusionFactorImp, DiffusionTensorImp> Dune::GDT::LocalEllipticIntegrand< DiffusionFactorImp, DiffusionTensorImp >::Traits
Constructor & Destructor Documentation
template<class DiffusionFactorImp , class DiffusionTensorImp = void> Dune::GDT::LocalEllipticIntegrand< DiffusionFactorImp, DiffusionTensorImp >::LocalEllipticIntegrand (const DiffusionFactorType & diffusion_factor, const DiffusionTensorType & diffusion_tensor) inline
template<class DiffusionFactorImp , class DiffusionTensorImp = void> Dune::GDT::LocalEllipticIntegrand< DiffusionFactorImp, DiffusionTensorImp >::LocalEllipticIntegrand (const DiffusionFactorType & diffusion_factor) inline
template<class DiffusionFactorImp , class DiffusionTensorImp = void> template<typename DiffusionType , typename = typename std::enable_if<(std::is_same<DiffusionType, DiffusionTensorType>::value) && (dimDomain > 1> Dune::GDT::LocalEllipticIntegrand< DiffusionFactorImp, DiffusionTensorImp >::LocalEllipticIntegrand (const DiffusionType & diffusion) inline
template<class DiffusionFactorImp , class DiffusionTensorImp = void> Dune::GDT::LocalEllipticIntegrand< DiffusionFactorImp, DiffusionTensorImp >::LocalEllipticIntegrand (const ThisType & other) default
template<class DiffusionFactorImp , class DiffusionTensorImp = void> Dune::GDT::LocalEllipticIntegrand< DiffusionFactorImp, DiffusionTensorImp >::LocalEllipticIntegrand (ThisType && source) default
Member Function Documentation
template<class DiffusionFactorImp , class DiffusionTensorImp = void> const DiffusionFactorType& Dune::GDT::LocalEllipticIntegrand< DiffusionFactorImp, DiffusionTensorImp >::diffusion_factor () const inline
Referenced by Dune::GDT::EllipticOperator< DiffusionFactorType, DiffusionTensorType, GridView, Field >::apply(), Dune::GDT::EllipticOperator< DiffusionFactorType, DiffusionTensorType, GridView, Field >::apply2(), Dune::GDT::LocalEllipticIpdgIntegrands::Inner< DiffusionFactorImp, DiffusionTensorImp, method >::localFunctions(), Dune::GDT::LocalEllipticIpdgIntegrands::BoundaryLHS< DiffusionFactorImp, DiffusionTensorImp, method >::localFunctions(), and Dune::GDT::LocalEllipticIpdgIntegrands::BoundaryRHS< DirichletImp, DiffusionFactorImp, DiffusionTensorImp, method >::localFunctions().
template<class DiffusionFactorImp , class DiffusionTensorImp = void> const DiffusionTensorType& Dune::GDT::LocalEllipticIntegrand< DiffusionFactorImp, DiffusionTensorImp >::diffusion_tensor () const inline
Referenced by Dune::GDT::EllipticOperator< DiffusionFactorType, DiffusionTensorType, GridView, Field >::apply(), Dune::GDT::EllipticOperator< DiffusionFactorType, DiffusionTensorType, GridView, Field >::apply2(), Dune::GDT::LocalEllipticIpdgIntegrands::Inner< DiffusionFactorImp, DiffusionTensorImp, method >::localFunctions(), Dune::GDT::LocalEllipticIpdgIntegrands::BoundaryLHS< DiffusionFactorImp, DiffusionTensorImp, method >::localFunctions(), and Dune::GDT::LocalEllipticIpdgIntegrands::BoundaryRHS< DirichletImp, DiffusionFactorImp, DiffusionTensorImp, method >::localFunctions().
template<class DiffusionFactorImp , class DiffusionTensorImp = void> template<class R , size_t rT, size_t rCT, size_t rA, size_t rCA> void Dune::GDT::LocalEllipticIntegrand< DiffusionFactorImp, DiffusionTensorImp >::evaluate (const LocalfunctionTupleType & local_functions_tuple, const Stuff::LocalfunctionSetInterface< E, D, d, R, rT, rCT > & test_base, const Stuff::LocalfunctionSetInterface< E, D, d, R, rA, rCA > & ansatz_base, const Dune::FieldVector< D, d > & localPoint, Dune::DynamicMatrix< R > & ret) const inline
extracts the local functions and calls the correct evaluate() method
template<class DiffusionFactorImp , class DiffusionTensorImp = void> template<class R , size_t r> void Dune::GDT::LocalEllipticIntegrand< DiffusionFactorImp, DiffusionTensorImp >::evaluate (const Stuff::LocalfunctionInterface< E, D, d, R, 1, 1 > & local_diffusion_factor, const Stuff::LocalfunctionInterface< E, D, d, R, d, d > & local_diffusion_tensor, const Stuff::LocalfunctionSetInterface< E, D, d, R, r, 1 > & test_base, const Stuff::LocalfunctionSetInterface< E, D, d, R, r, 1 > & ansatz_base, const Dune::FieldVector< D, d > & localPoint, Dune::DynamicMatrix< R > & ret) const inline
template<class DiffusionFactorImp , class DiffusionTensorImp = void> LocalfunctionTupleType Dune::GDT::LocalEllipticIntegrand< DiffusionFactorImp, DiffusionTensorImp >::localFunctions (const EntityType & entity) const inline
template<class DiffusionFactorImp , class DiffusionTensorImp = void> template<class R , size_t rT, size_t rCT, size_t rA, size_t rCA> size_t Dune::GDT::LocalEllipticIntegrand< DiffusionFactorImp, DiffusionTensorImp >::order (const LocalfunctionTupleType & local_functions_tuple, const Stuff::LocalfunctionSetInterface< E, D, d, R, rT, rCT > & test_base, const Stuff::LocalfunctionSetInterface< E, D, d, R, rA, rCA > & ansatz_base) const inline
extracts the local functions and calls the correct order() method
template<class DiffusionFactorImp , class DiffusionTensorImp = void> template<class R , size_t rDF, size_t rCDF, size_t rDT, size_t rCDT, size_t rT, size_t rCT, size_t rA, size_t rCA> size_t Dune::GDT::LocalEllipticIntegrand< DiffusionFactorImp, DiffusionTensorImp >::order (const Stuff::LocalfunctionInterface< E, D, d, R, rDF, rCDF > & local_diffusion_factor, const Stuff::LocalfunctionInterface< E, D, d, R, rDT, rCDT > & local_diffusion_tensor, const Stuff::LocalfunctionSetInterface< E, D, d, R, rT, rCT > & test_base, const Stuff::LocalfunctionSetInterface< E, D, d, R, rA, rCA > & ansatz_base) const inline
Member Data Documentation
template<class DiffusionFactorImp , class DiffusionTensorImp = void> const size_t Dune::GDT::LocalEllipticIntegrand< DiffusionFactorImp, DiffusionTensorImp >::dimDomain = Traits::dimDomain static
The documentation for this class was generated from the following file:
local/integrands/elliptic.hh