Dune::GDT::LocalVolumeIntegralOperator< BinaryEvaluationType > Class Template Reference
Dune::GDT::LocalVolumeIntegralOperator< BinaryEvaluationType > Class Template Reference
#include <dune/gdt/local/operators/integrals.hh>
Public Types
typedef
internal::LocalVolumeIntegralOperatorTraits
< BinaryEvaluationType > Traits
typedef
internal::LocalVolumeIntegralOperatorTraits
< BinaryEvaluationType >
::derived_type derived_type
Public Member Functions
template<class... Args>
LocalVolumeIntegralOperator (Args &&...args)
template<class... Args>
LocalVolumeIntegralOperator (const int over_integrate, Args &&...args)
template<class... Args>
LocalVolumeIntegralOperator (const size_t over_integrate, Args &&...args)
LocalVolumeIntegralOperator (const ThisType &other)=default
LocalVolumeIntegralOperator (ThisType &&source)=default
template<class E , class D , size_t d, class R , size_t rT, size_t rCT, size_t rA, size_t rCA>
void apply2 (const Stuff::LocalfunctionSetInterface< E, D, d, R, rT, rCT > &test_base, const Stuff::LocalfunctionSetInterface< E, D, d, R, rA, rCA > &ansatz_base, Dune::DynamicMatrix< R > &ret) const
void apply2 (const Stuff::LocalfunctionSetInterface< T, D, d, R, rT, rCT > &test_base, const Stuff::LocalfunctionSetInterface< A, D, d, R, rA, rCA > &ansatz_base, Dune::DynamicMatrix< R > &ret) const
Applies the local operator as a two-form.
Dune::DynamicMatrix< R > apply2 (const Stuff::LocalfunctionSetInterface< T, D, d, R, rT, rCT > &test_base, const Stuff::LocalfunctionSetInterface< A, D, d, R, rA, rCA > &ansatz_base) const
Member Typedef Documentation
typedef internal::LocalVolumeIntegralOperatorTraits< BinaryEvaluationType > ::derived_type Dune::GDT::LocalVolumeTwoFormInterface< internal::LocalVolumeIntegralOperatorTraits< BinaryEvaluationType > >::derived_type inherited
template<class BinaryEvaluationType> typedef internal::LocalVolumeIntegralOperatorTraits<BinaryEvaluationType> Dune::GDT::LocalVolumeIntegralOperator< BinaryEvaluationType >::Traits
Constructor & Destructor Documentation
template<class BinaryEvaluationType> template<class... Args> Dune::GDT::LocalVolumeIntegralOperator< BinaryEvaluationType >::LocalVolumeIntegralOperator (Args &&... args) inline explicit
template<class BinaryEvaluationType> template<class... Args> Dune::GDT::LocalVolumeIntegralOperator< BinaryEvaluationType >::LocalVolumeIntegralOperator (const int over_integrate, Args &&... args) inline explicit
template<class BinaryEvaluationType> template<class... Args> Dune::GDT::LocalVolumeIntegralOperator< BinaryEvaluationType >::LocalVolumeIntegralOperator (const size_t over_integrate, Args &&... args) inline explicit
template<class BinaryEvaluationType> Dune::GDT::LocalVolumeIntegralOperator< BinaryEvaluationType >::LocalVolumeIntegralOperator (const ThisType & other) default
template<class BinaryEvaluationType> Dune::GDT::LocalVolumeIntegralOperator< BinaryEvaluationType >::LocalVolumeIntegralOperator (ThisType && source) default
Member Function Documentation
template<class BinaryEvaluationType> template<class E , class D , size_t d, class R , size_t rT, size_t rCT, size_t rA, size_t rCA> void Dune::GDT::LocalVolumeIntegralOperator< BinaryEvaluationType >::apply2 (const Stuff::LocalfunctionSetInterface< E, D, d, R, rT, rCT > & test_base, const Stuff::LocalfunctionSetInterface< E, D, d, R, rA, rCA > & ansatz_base, Dune::DynamicMatrix< R > & ret) const inline
Referenced by Dune::GDT::LocalL2ProjectionOperator::apply().
void Dune::GDT::LocalVolumeTwoFormInterface< internal::LocalVolumeIntegralOperatorTraits< BinaryEvaluationType > >::apply2 (const Stuff::LocalfunctionSetInterface< T, D, d, R, rT, rCT > & test_base, const Stuff::LocalfunctionSetInterface< A, D, d, R, rA, rCA > & ansatz_base, Dune::DynamicMatrix< R > & ret) const inline inherited
Applies the local operator as a two-form.
Template Parameters
T Traits of the test Stuff::LocalfunctionSetInterface implementation
A Traits of the ansatz Stuff::LocalfunctionSetInterface implementation
D DomainFieldType
d dimDomain
R RangeFieldType
r{T,A} dimRange of the of the {test_base,ansatz_base}
rC{T,a} dimRangeCols of the {test_base,ansatz_base}
References Dune::GDT::LocalVolumeTwoFormInterface< Traits >::apply2().
Dune::DynamicMatrix<R> Dune::GDT::LocalVolumeTwoFormInterface< internal::LocalVolumeIntegralOperatorTraits< BinaryEvaluationType > >::apply2 (const Stuff::LocalfunctionSetInterface< T, D, d, R, rT, rCT > & test_base, const Stuff::LocalfunctionSetInterface< A, D, d, R, rA, rCA > & ansatz_base) const inline inherited
See Also
apply2
References Dune::GDT::LocalVolumeTwoFormInterface< Traits >::apply2().
The documentation for this class was generated from the following file:
operators/integrals.hh