Dune::GDT::LocalReconstructionFvOperator< MatrixImp, BoundaryValueFunctionImp, slope_limiter > Class Template Reference
Dune::GDT::LocalReconstructionFvOperator< MatrixImp, BoundaryValueFunctionImp, slope_limiter > Class Template Reference
#include <dune/gdt/local/operators/fv.hh>
Public Types
typedef Traits::MatrixType MatrixType
typedef
Traits::BoundaryValueFunctionType BoundaryValueFunctionType
typedef
internal::LocalReconstructionFvOperatorTraits
< MatrixImp,
BoundaryValueFunctionImp,
slope_limiter >::derived_type derived_type
Public Member Functions
LocalReconstructionFvOperator (const MatrixType &eigenvectors, const MatrixType &eigenvectors_inverse, const BoundaryValueFunctionType &boundary_values)
template<class SourceType , class RangeSpaceType , class VectorType >
void apply (const SourceType &source, LocalDiscreteFunction< RangeSpaceType, VectorType > &local_range) const
Member Typedef Documentation
template<class MatrixImp , class BoundaryValueFunctionImp , SlopeLimiters slope_limiter> typedef Traits::BoundaryValueFunctionType Dune::GDT::LocalReconstructionFvOperator< MatrixImp, BoundaryValueFunctionImp, slope_limiter >::BoundaryValueFunctionType
typedef internal::LocalReconstructionFvOperatorTraits< MatrixImp, BoundaryValueFunctionImp, slope_limiter > ::derived_type Dune::GDT::LocalOperatorInterface< internal::LocalReconstructionFvOperatorTraits< MatrixImp, BoundaryValueFunctionImp, slope_limiter > >::derived_type inherited
template<class MatrixImp , class BoundaryValueFunctionImp , SlopeLimiters slope_limiter> typedef Traits::MatrixType Dune::GDT::LocalReconstructionFvOperator< MatrixImp, BoundaryValueFunctionImp, slope_limiter >::MatrixType
Constructor & Destructor Documentation
template<class MatrixImp , class BoundaryValueFunctionImp , SlopeLimiters slope_limiter> Dune::GDT::LocalReconstructionFvOperator< MatrixImp, BoundaryValueFunctionImp, slope_limiter >::LocalReconstructionFvOperator (const MatrixType & eigenvectors, const MatrixType & eigenvectors_inverse, const BoundaryValueFunctionType & boundary_values) inline explicit
Member Function Documentation
template<class MatrixImp , class BoundaryValueFunctionImp , SlopeLimiters slope_limiter> template<class SourceType , class RangeSpaceType , class VectorType > void Dune::GDT::LocalReconstructionFvOperator< MatrixImp, BoundaryValueFunctionImp, slope_limiter >::apply (const SourceType & source, LocalDiscreteFunction< RangeSpaceType, VectorType > & local_range) const inline
References Dune::GDT::internal::ChooseLimiter< slope_limiter, VectorType >::limit(), Dune::GDT::ConstLocalDiscreteFunction< SpaceImp, VectorImp >::space(), and Dune::GDT::LocalDiscreteFunction< SpaceImp, VectorImp >::vector().
The documentation for this class was generated from the following file:
local/operators/fv.hh