Dune::GDT::LocalProductIntegrand< LocalizableFunctionImp > Class Template Reference
Dune::GDT::LocalProductIntegrand< LocalizableFunctionImp > Class Template Reference
Computes a product evaluation.
#include <dune/gdt/local/integrands/product.hh>
Public Types
typedef
internal::LocalProductIntegrandTraits
< LocalizableFunctionImp > Traits
typedef
Traits::LocalizableFunctionType LocalizableFunctionType
typedef
Traits::LocalfunctionTupleType LocalfunctionTupleType
typedef Traits::EntityType EntityType
typedef Traits::DomainFieldType DomainFieldType
Public Member Functions
LocalProductIntegrand (const LocalizableFunctionType &inducingFunction)
Required by all variants of LocalVolumeIntegrandInterface
LocalfunctionTupleType localFunctions (const EntityType &entity) const
Required by LocalVolumeIntegrandInterface< ..., 1 >
template<class R , size_t rT, size_t rCT>
size_t order (const LocalfunctionTupleType &localFuncs, const Stuff::LocalfunctionSetInterface< EntityType, DomainFieldType, dimDomain, R, rT, rCT > &testBase) const
extracts the local function and calls the correct order() method
template<class R , size_t rT, size_t rCT>
void evaluate (const LocalfunctionTupleType &localFuncs, const Stuff::LocalfunctionSetInterface< EntityType, DomainFieldType, dimDomain, R, rT, rCT > &testBase, const Dune::FieldVector< DomainFieldType, dimDomain > &localPoint, Dune::DynamicVector< R > &ret) const
extracts the local function and calls the correct evaluate() method
Required by LocalFaceIntegrandInterface< ..., 1 >
template<class IntersectionType , class R , size_t r, size_t rC>
void evaluate (const LocalfunctionTupleType &localFuncs, const Stuff::LocalfunctionSetInterface< EntityType, DomainFieldType, dimDomain, R, r, rC > &testBase, const IntersectionType &intersection, const Dune::FieldVector< DomainFieldType, dimDomain-1 > &localPoint, Dune::DynamicVector< R > &ret) const
extracts the local function and calls the correct evaluate() method
Required by LocalVolumeIntegrandInterface< ..., 2 >
template<class R , size_t rT, size_t rCT, size_t rA, size_t rCA>
void evaluate (const LocalfunctionTupleType &localFuncs, const Stuff::LocalfunctionSetInterface< EntityType, DomainFieldType, dimDomain, R, rT, rCT > &testBase, const Stuff::LocalfunctionSetInterface< EntityType, DomainFieldType, dimDomain, R, rA, rCA > &ansatzBase, const Dune::FieldVector< DomainFieldType, dimDomain > &localPoint, Dune::DynamicMatrix< R > &ret) const
extracts the local function and calls the correct evaluate() method
Required by LocalFaceIntegrandInterface< ..., 2 >
template<class IntersectionType , class R , size_t rT, size_t rCT, size_t rA, size_t rCA>
void evaluate (const LocalfunctionTupleType &localFunctions_in, const Stuff::LocalfunctionSetInterface< EntityType, DomainFieldType, dimDomain, R, rT, rCT > &testBase, const Stuff::LocalfunctionSetInterface< EntityType, DomainFieldType, dimDomain, R, rA, rCA > &ansatzBase, const IntersectionType &intersection, const Dune::FieldVector< DomainFieldType, dimDomain-1 > &localPoint, Dune::DynamicMatrix< R > &ret) const
extracts the local function and calls the correct evaluate() method
Required by LocalVolumeIntegrandInterface< ..., 2 > and LocalFaceIntegrandInterface< ..., 2 >
template<class R , size_t rT, size_t rCT, size_t rA, size_t rCA>
size_t order (const LocalfunctionTupleType &localFuncs, const Stuff::LocalfunctionSetInterface< EntityType, DomainFieldType, dimDomain, R, rT, rCT > &testBase, const Stuff::LocalfunctionSetInterface< EntityType, DomainFieldType, dimDomain, R, rA, rCA > &ansatzBase) const
extracts the local function and calls the correct order() method
Actual implementations of order
template<class R , size_t rL, size_t rCL, size_t rT, size_t rCT>
size_t order (const Stuff::LocalfunctionInterface< EntityType, DomainFieldType, dimDomain, R, rL, rCL > &localFunction, const Stuff::LocalfunctionSetInterface< EntityType, DomainFieldType, dimDomain, R, rT, rCT > &testBase) const
template<class R , size_t rL, size_t rCL, size_t rT, size_t rCT, size_t rA, size_t rCA>
size_t order (const Stuff::LocalfunctionInterface< EntityType, DomainFieldType, dimDomain, R, rL, rCL > &localFunction, const Stuff::LocalfunctionSetInterface< EntityType, DomainFieldType, dimDomain, R, rT, rCT > &testBase, const Stuff::LocalfunctionSetInterface< EntityType, DomainFieldType, dimDomain, R, rA, rCA > &ansatzBase) const
Actual implementations of evaluate
template<class R , size_t r>
void evaluate (const Stuff::LocalfunctionInterface< EntityType, DomainFieldType, dimDomain, R, r, 1 > &localFunction, const Stuff::LocalfunctionSetInterface< EntityType, DomainFieldType, dimDomain, R, r, 1 > &testBase, const Dune::FieldVector< DomainFieldType, dimDomain > &localPoint, Dune::DynamicVector< R > &ret) const
template<class R , size_t r>
void evaluate (const Stuff::LocalfunctionInterface< EntityType, DomainFieldType, dimDomain, R, 1, 1 > &localFunction, const Stuff::LocalfunctionSetInterface< EntityType, DomainFieldType, dimDomain, R, r, 1 > &testBase, const Stuff::LocalfunctionSetInterface< EntityType, DomainFieldType, dimDomain, R, r, 1 > &ansatzBase, const Dune::FieldVector< DomainFieldType, dimDomain > &localPoint, Dune::DynamicMatrix< R > &ret) const
Computes a product evaluation for a scalar local function and scalar or vector valued basefunctionsets.
template<class IntersectionType , class R , size_t r>
void evaluate (const Stuff::LocalfunctionInterface< EntityType, DomainFieldType, dimDomain, R, r, 1 > &localFunction, const Stuff::LocalfunctionSetInterface< EntityType, DomainFieldType, dimDomain, R, r, 1 > &testBase, const IntersectionType &intersection, const Dune::FieldVector< DomainFieldType, dimDomain-1 > &localPoint, Dune::DynamicVector< R > &ret) const
template<class IntersectionType , class R , size_t r>
void evaluate (const Stuff::LocalfunctionInterface< EntityType, DomainFieldType, dimDomain, R, 1, 1 > &localFunction, const Stuff::LocalfunctionSetInterface< EntityType, DomainFieldType, dimDomain, R, r, 1 > &testBase, const Stuff::LocalfunctionSetInterface< EntityType, DomainFieldType, dimDomain, R, r, 1 > &ansatzBase, const IntersectionType &intersection, const Dune::FieldVector< DomainFieldType, dimDomain-1 > &localPoint, Dune::DynamicMatrix< R > &ret) const
Computes a product evaluation for a scalar local function and scalar or vector valued basefunctionsets.
Static Public Attributes
static const size_t dimDomain = Traits::dimDomain
Detailed Description
template<class LocalizableFunctionImp>
class Dune::GDT::LocalProductIntegrand< LocalizableFunctionImp >
Computes a product evaluation.
Member Typedef Documentation
template<class LocalizableFunctionImp > typedef Traits::DomainFieldType Dune::GDT::LocalProductIntegrand< LocalizableFunctionImp >::DomainFieldType
template<class LocalizableFunctionImp > typedef Traits::EntityType Dune::GDT::LocalProductIntegrand< LocalizableFunctionImp >::EntityType
template<class LocalizableFunctionImp > typedef Traits::LocalfunctionTupleType Dune::GDT::LocalProductIntegrand< LocalizableFunctionImp >::LocalfunctionTupleType
template<class LocalizableFunctionImp > typedef Traits::LocalizableFunctionType Dune::GDT::LocalProductIntegrand< LocalizableFunctionImp >::LocalizableFunctionType
template<class LocalizableFunctionImp > typedef internal::LocalProductIntegrandTraits<LocalizableFunctionImp> Dune::GDT::LocalProductIntegrand< LocalizableFunctionImp >::Traits
Constructor & Destructor Documentation
template<class LocalizableFunctionImp > Dune::GDT::LocalProductIntegrand< LocalizableFunctionImp >::LocalProductIntegrand (const LocalizableFunctionType & inducingFunction) inline
Member Function Documentation
template<class LocalizableFunctionImp > template<class R , size_t rT, size_t rCT> void Dune::GDT::LocalProductIntegrand< LocalizableFunctionImp >::evaluate (const LocalfunctionTupleType & localFuncs, const Stuff::LocalfunctionSetInterface< EntityType, DomainFieldType, dimDomain, R, rT, rCT > & testBase, const Dune::FieldVector< DomainFieldType, dimDomain > & localPoint, Dune::DynamicVector< R > & ret) const inline
extracts the local function and calls the correct evaluate() method
Referenced by Dune::GDT::LocalProductIntegrand< LocalizableFunctionImp >::evaluate().
template<class LocalizableFunctionImp > template<class IntersectionType , class R , size_t r, size_t rC> void Dune::GDT::LocalProductIntegrand< LocalizableFunctionImp >::evaluate (const LocalfunctionTupleType & localFuncs, const Stuff::LocalfunctionSetInterface< EntityType, DomainFieldType, dimDomain, R, r, rC > & testBase, const IntersectionType & intersection, const Dune::FieldVector< DomainFieldType, dimDomain-1 > & localPoint, Dune::DynamicVector< R > & ret) const inline
extracts the local function and calls the correct evaluate() method
References Dune::GDT::LocalProductIntegrand< LocalizableFunctionImp >::evaluate().
template<class LocalizableFunctionImp > template<class R , size_t rT, size_t rCT, size_t rA, size_t rCA> void Dune::GDT::LocalProductIntegrand< LocalizableFunctionImp >::evaluate (const LocalfunctionTupleType & localFuncs, const Stuff::LocalfunctionSetInterface< EntityType, DomainFieldType, dimDomain, R, rT, rCT > & testBase, const Stuff::LocalfunctionSetInterface< EntityType, DomainFieldType, dimDomain, R, rA, rCA > & ansatzBase, const Dune::FieldVector< DomainFieldType, dimDomain > & localPoint, Dune::DynamicMatrix< R > & ret) const inline
extracts the local function and calls the correct evaluate() method
References Dune::GDT::LocalProductIntegrand< LocalizableFunctionImp >::evaluate().
template<class LocalizableFunctionImp > template<class IntersectionType , class R , size_t rT, size_t rCT, size_t rA, size_t rCA> void Dune::GDT::LocalProductIntegrand< LocalizableFunctionImp >::evaluate (const LocalfunctionTupleType & localFunctions_in, const Stuff::LocalfunctionSetInterface< EntityType, DomainFieldType, dimDomain, R, rT, rCT > & testBase, const Stuff::LocalfunctionSetInterface< EntityType, DomainFieldType, dimDomain, R, rA, rCA > & ansatzBase, const IntersectionType & intersection, const Dune::FieldVector< DomainFieldType, dimDomain-1 > & localPoint, Dune::DynamicMatrix< R > & ret) const inline
extracts the local function and calls the correct evaluate() method
References Dune::GDT::LocalProductIntegrand< LocalizableFunctionImp >::evaluate().
template<class LocalizableFunctionImp > template<class R , size_t r> void Dune::GDT::LocalProductIntegrand< LocalizableFunctionImp >::evaluate (const Stuff::LocalfunctionInterface< EntityType, DomainFieldType, dimDomain, R, r, 1 > & localFunction, const Stuff::LocalfunctionSetInterface< EntityType, DomainFieldType, dimDomain, R, r, 1 > & testBase, const Dune::FieldVector< DomainFieldType, dimDomain > & localPoint, Dune::DynamicVector< R > & ret) const inline
Note
for LocalVolumeIntegrandInterface< ..., 1 >
template<class LocalizableFunctionImp > template<class R , size_t r> void Dune::GDT::LocalProductIntegrand< LocalizableFunctionImp >::evaluate (const Stuff::LocalfunctionInterface< EntityType, DomainFieldType, dimDomain, R, 1, 1 > & localFunction, const Stuff::LocalfunctionSetInterface< EntityType, DomainFieldType, dimDomain, R, r, 1 > & testBase, const Stuff::LocalfunctionSetInterface< EntityType, DomainFieldType, dimDomain, R, r, 1 > & ansatzBase, const Dune::FieldVector< DomainFieldType, dimDomain > & localPoint, Dune::DynamicMatrix< R > & ret) const inline
Computes a product evaluation for a scalar local function and scalar or vector valued basefunctionsets.
Note
for LocalVolumeIntegrandInterface< ..., 2 >
template<class LocalizableFunctionImp > template<class IntersectionType , class R , size_t r> void Dune::GDT::LocalProductIntegrand< LocalizableFunctionImp >::evaluate (const Stuff::LocalfunctionInterface< EntityType, DomainFieldType, dimDomain, R, r, 1 > & localFunction, const Stuff::LocalfunctionSetInterface< EntityType, DomainFieldType, dimDomain, R, r, 1 > & testBase, const IntersectionType & intersection, const Dune::FieldVector< DomainFieldType, dimDomain-1 > & localPoint, Dune::DynamicVector< R > & ret) const inline
Note
for LocalFaceIntegrandInterface< ..., 1 >
template<class LocalizableFunctionImp > template<class IntersectionType , class R , size_t r> void Dune::GDT::LocalProductIntegrand< LocalizableFunctionImp >::evaluate (const Stuff::LocalfunctionInterface< EntityType, DomainFieldType, dimDomain, R, 1, 1 > & localFunction, const Stuff::LocalfunctionSetInterface< EntityType, DomainFieldType, dimDomain, R, r, 1 > & testBase, const Stuff::LocalfunctionSetInterface< EntityType, DomainFieldType, dimDomain, R, r, 1 > & ansatzBase, const IntersectionType & intersection, const Dune::FieldVector< DomainFieldType, dimDomain-1 > & localPoint, Dune::DynamicMatrix< R > & ret) const inline
Computes a product evaluation for a scalar local function and scalar or vector valued basefunctionsets.
Note
for LocalFaceIntegrandInterface< ..., 2 >
template<class LocalizableFunctionImp > LocalfunctionTupleType Dune::GDT::LocalProductIntegrand< LocalizableFunctionImp >::localFunctions (const EntityType & entity) const inline
template<class LocalizableFunctionImp > template<class R , size_t rT, size_t rCT> size_t Dune::GDT::LocalProductIntegrand< LocalizableFunctionImp >::order (const LocalfunctionTupleType & localFuncs, const Stuff::LocalfunctionSetInterface< EntityType, DomainFieldType, dimDomain, R, rT, rCT > & testBase) const inline
extracts the local function and calls the correct order() method
Referenced by Dune::GDT::LocalProductIntegrand< LocalizableFunctionImp >::order().
template<class LocalizableFunctionImp > template<class R , size_t rT, size_t rCT, size_t rA, size_t rCA> size_t Dune::GDT::LocalProductIntegrand< LocalizableFunctionImp >::order (const LocalfunctionTupleType & localFuncs, const Stuff::LocalfunctionSetInterface< EntityType, DomainFieldType, dimDomain, R, rT, rCT > & testBase, const Stuff::LocalfunctionSetInterface< EntityType, DomainFieldType, dimDomain, R, rA, rCA > & ansatzBase) const inline
extracts the local function and calls the correct order() method
References Dune::GDT::LocalProductIntegrand< LocalizableFunctionImp >::order().
template<class LocalizableFunctionImp > template<class R , size_t rL, size_t rCL, size_t rT, size_t rCT> size_t Dune::GDT::LocalProductIntegrand< LocalizableFunctionImp >::order (const Stuff::LocalfunctionInterface< EntityType, DomainFieldType, dimDomain, R, rL, rCL > & localFunction, const Stuff::LocalfunctionSetInterface< EntityType, DomainFieldType, dimDomain, R, rT, rCT > & testBase) const inline
Note
for LocalVolumeIntegrandInterface< ..., 1 >
Returns
localFunction.order() + testBase.order()
template<class LocalizableFunctionImp > template<class R , size_t rL, size_t rCL, size_t rT, size_t rCT, size_t rA, size_t rCA> size_t Dune::GDT::LocalProductIntegrand< LocalizableFunctionImp >::order (const Stuff::LocalfunctionInterface< EntityType, DomainFieldType, dimDomain, R, rL, rCL > & localFunction, const Stuff::LocalfunctionSetInterface< EntityType, DomainFieldType, dimDomain, R, rT, rCT > & testBase, const Stuff::LocalfunctionSetInterface< EntityType, DomainFieldType, dimDomain, R, rA, rCA > & ansatzBase) const inline
Note
for
LocalVolumeIntegrandInterface< ..., 2 >
LocalFaceIntegrandInterface< ..., 2 >
Returns
localFunction.order() + testBase.order() + ansatzBase.order()
Member Data Documentation
template<class LocalizableFunctionImp > const size_t Dune::GDT::LocalProductIntegrand< LocalizableFunctionImp >::dimDomain = Traits::dimDomain static
The documentation for this class was generated from the following file:
local/integrands/product.hh