Dune::GDT::StationaryDiscretizationInterface< Traits > Class Template Reference
Dune::GDT::StationaryDiscretizationInterface< Traits > Class Template Reference
#include <dune/gdt/discretizations/interfaces.hh>
Public Types
typedef Traits::ProblemType ProblemType
typedef Traits::AnsatzSpaceType AnsatzSpaceType
typedef Traits::TestSpaceType TestSpaceType
typedef Traits::VectorType VectorType
Public Member Functions
Have to be implemented by any derived class.
const ProblemType & problem () const
const AnsatzSpaceType & ansatz_space () const
const TestSpaceType & test_space () const
std::vector< std::string > solver_types () const
Stuff::Common::Configuration solver_options (const std::string type="") const
void solve (VectorType &solution, const Stuff::Common::Configuration &options) const
Provided by the interface for convenience.
VectorType create_vector () const
void solve (VectorType &solution, const std::string &type) const
void solve (VectorType &solution) const
VectorType solve (const Stuff::Common::Configuration &options) const
VectorType solve (const std::string &type) const
VectorType solve () const
void visualize (const VectorType &vector, const std::string filename, const std::string name) const
Member Typedef Documentation
template<class Traits> typedef Traits::AnsatzSpaceType Dune::GDT::StationaryDiscretizationInterface< Traits >::AnsatzSpaceType
template<class Traits> typedef Traits::ProblemType Dune::GDT::StationaryDiscretizationInterface< Traits >::ProblemType
template<class Traits> typedef Traits::TestSpaceType Dune::GDT::StationaryDiscretizationInterface< Traits >::TestSpaceType
template<class Traits> typedef Traits::VectorType Dune::GDT::StationaryDiscretizationInterface< Traits >::VectorType
Member Function Documentation
template<class Traits> const AnsatzSpaceType& Dune::GDT::StationaryDiscretizationInterface< Traits >::ansatz_space () const inline
Referenced by Dune::GDT::StationaryDiscretizationInterface< internal::StationaryContainerBasedDefaultDiscretizationTraits< ProblemImp, AnsatzSpaceImp, MatrixImp, VectorImp, TestSpaceImp > >::ansatz_space(), Dune::GDT::StationaryDiscretizationInterface< internal::StationaryContainerBasedDefaultDiscretizationTraits< ProblemImp, AnsatzSpaceImp, MatrixImp, VectorImp, TestSpaceImp > >::create_vector(), and Dune::GDT::StationaryDiscretizationInterface< internal::StationaryContainerBasedDefaultDiscretizationTraits< ProblemImp, AnsatzSpaceImp, MatrixImp, VectorImp, TestSpaceImp > >::visualize().
template<class Traits> VectorType Dune::GDT::StationaryDiscretizationInterface< Traits >::create_vector () const inline
Referenced by Dune::GDT::StationaryDiscretizationInterface< internal::StationaryContainerBasedDefaultDiscretizationTraits< ProblemImp, AnsatzSpaceImp, MatrixImp, VectorImp, TestSpaceImp > >::solve().
template<class Traits> const ProblemType& Dune::GDT::StationaryDiscretizationInterface< Traits >::problem () const inline
Referenced by Dune::GDT::StationaryDiscretizationInterface< internal::StationaryContainerBasedDefaultDiscretizationTraits< ProblemImp, AnsatzSpaceImp, MatrixImp, VectorImp, TestSpaceImp > >::problem().
template<class Traits> void Dune::GDT::StationaryDiscretizationInterface< Traits >::solve (VectorType & solution, const Stuff::Common::Configuration & options) const inline
template<class Traits> void Dune::GDT::StationaryDiscretizationInterface< Traits >::solve (VectorType & solution, const std::string & type) const inline
template<class Traits> void Dune::GDT::StationaryDiscretizationInterface< Traits >::solve (VectorType & solution) const inline
template<class Traits> VectorType Dune::GDT::StationaryDiscretizationInterface< Traits >::solve (const Stuff::Common::Configuration & options) const inline
template<class Traits> VectorType Dune::GDT::StationaryDiscretizationInterface< Traits >::solve (const std::string & type) const inline
template<class Traits> VectorType Dune::GDT::StationaryDiscretizationInterface< Traits >::solve () const inline
Referenced by Dune::GDT::StationaryDiscretizationInterface< internal::StationaryContainerBasedDefaultDiscretizationTraits< ProblemImp, AnsatzSpaceImp, MatrixImp, VectorImp, TestSpaceImp > >::solve().
template<class Traits> Stuff::Common::Configuration Dune::GDT::StationaryDiscretizationInterface< Traits >::solver_options (const std::string type = "") const inline
Referenced by Dune::GDT::StationaryDiscretizationInterface< internal::StationaryContainerBasedDefaultDiscretizationTraits< ProblemImp, AnsatzSpaceImp, MatrixImp, VectorImp, TestSpaceImp > >::solve(), and Dune::GDT::StationaryDiscretizationInterface< internal::StationaryContainerBasedDefaultDiscretizationTraits< ProblemImp, AnsatzSpaceImp, MatrixImp, VectorImp, TestSpaceImp > >::solver_options().
template<class Traits> std::vector<std::string> Dune::GDT::StationaryDiscretizationInterface< Traits >::solver_types () const inline
Referenced by Dune::GDT::StationaryDiscretizationInterface< internal::StationaryContainerBasedDefaultDiscretizationTraits< ProblemImp, AnsatzSpaceImp, MatrixImp, VectorImp, TestSpaceImp > >::solve(), and Dune::GDT::StationaryDiscretizationInterface< internal::StationaryContainerBasedDefaultDiscretizationTraits< ProblemImp, AnsatzSpaceImp, MatrixImp, VectorImp, TestSpaceImp > >::solver_types().
template<class Traits> const TestSpaceType& Dune::GDT::StationaryDiscretizationInterface< Traits >::test_space () const inline
Referenced by Dune::GDT::StationaryDiscretizationInterface< internal::StationaryContainerBasedDefaultDiscretizationTraits< ProblemImp, AnsatzSpaceImp, MatrixImp, VectorImp, TestSpaceImp > >::test_space().
template<class Traits> void Dune::GDT::StationaryDiscretizationInterface< Traits >::visualize (const VectorType & vector, const std::string filename, const std::string name) const inline
The documentation for this class was generated from the following file:
discretizations/interfaces.hh