Dune::GDT::RtSpaceInterface< ImpTraits, domainDim, rangeDim, rangeDimCols > Class Template Reference
Dune::GDT::RtSpaceInterface< ImpTraits, domainDim, rangeDim, rangeDimCols > Class Template Reference
#include <dune/gdt/spaces/rt/interface.hh>
Public Types
typedef ImpTraits Traits
typedef GridViewType::ctype DomainFieldType
typedef FieldVector
< DomainFieldType, dimDomain > DomainType
typedef GridViewType::template
Codim< 0 >::Entity EntityType
typedef Traits::BaseFunctionSetType BaseFunctionSetType
typedef
Dune::Stuff::LA::SparsityPatternDefault PatternType
typedef ImpTraits::derived_type derived_type
typedef ImpTraits::BackendType BackendType
typedef ImpTraits::MapperType MapperType
typedef ImpTraits::CommunicatorType CommunicatorType
typedef ImpTraits::GridViewType GridViewType
typedef ImpTraits::RangeFieldType RangeFieldType
typedef GridViewType::Intersection IntersectionType
typedef
Stuff::Grid::BoundaryInfoInterface
< IntersectionType > BoundaryInfoType
Public Member Functions
std::vector< size_t > local_DoF_indices (const EntityType &entity) const
Computes a vector 'indices' of length entity.count< 1 >(), where 'indices[intersection.indexInInside()]' is the index of the basis function (aka the local DoF index) corresponding to the intersection.
std::vector< size_t > local_DoF_indices_2dsimplex_order0 (const EntityType &entity) const
template<class G , class S , size_t d, size_t r, size_t rC>
PatternType compute_pattern (const GridView< G > &local_grid_view, const SpaceInterface< S, d, r, rC > &ansatz_space) const
template<class S , size_t d, size_t r, size_t rC, class C , class R >
void local_constraints (const SpaceInterface< S, d, r, rC > &, const EntityType &, ConstraintsInterface< C > &) const
const GridViewType & grid_view () const
const BackendType & backend () const
const MapperType & mapper () const
BaseFunctionSetType base_function_set (const EntityType &entity) const
CommunicatorType & communicator () const
void local_constraints (const EntityType &entity, ConstraintsInterface< C > &ret) const
PatternType compute_pattern () const
PatternType compute_pattern (const SpaceInterface< S, d, r, rC > &ansatz_space) const
PatternType compute_pattern (const GridView< G > &local_grid_view) const
PatternType compute_volume_pattern () const
PatternType compute_volume_pattern (const SpaceInterface< S, d, r, rC > &ansatz_space) const
PatternType compute_volume_pattern (const GridView< G > &local_grid_view) const
PatternType compute_volume_pattern (const GridView< G > &local_grid_view, const SpaceInterface< S, d, r, rC > &ansatz_space) const
computes a sparsity pattern, where this space is the test space (rows/outer) and the other space is the ansatz space (cols/inner)
PatternType compute_face_and_volume_pattern () const
PatternType compute_face_and_volume_pattern (const GridView< G > &local_grid_view) const
PatternType compute_face_and_volume_pattern (const SpaceInterface< S, d, r, rC > &ansatz_space) const
PatternType compute_face_and_volume_pattern (const GridView< G > &local_grid_view, const SpaceInterface< S, d, r, rC > &ansatz_space) const
computes a DG sparsity pattern, where this space is the test space (rows/outer) and the other space is the ansatz space (cols/inner)
PatternType compute_face_pattern () const
PatternType compute_face_pattern (const GridView< G > &local_grid_view) const
PatternType compute_face_pattern (const SpaceInterface< S, d, r, rC > &ansatz_space) const
PatternType compute_face_pattern (const G &local_grid_view, const SpaceInterface< S, d, r, rC > &ansatz_space) const
void visualize (const std::string filename_prefix="") const
Static Public Attributes
static const int polOrder
static const bool continuous
static const size_t dimDomain
static const size_t dimRange
static const size_t dimRangeCols
static const
Stuff::Grid::ChoosePartView part_view_type
static const bool needs_grid_view
Member Typedef Documentation
typedef ImpTraits ::BackendType Dune::GDT::SpaceInterface< ImpTraits , domainDim, rangeDim, rangeDimCols >::BackendType inherited
template<class ImpTraits , size_t domainDim, size_t rangeDim, size_t rangeDimCols = 1> typedef Traits::BaseFunctionSetType Dune::GDT::SpaceInterface< Traits, domainDim, rangeDim, rangeDimCols >::BaseFunctionSetType
typedef Stuff::Grid::BoundaryInfoInterface<IntersectionType> Dune::GDT::SpaceInterface< ImpTraits , domainDim, rangeDim, rangeDimCols >::BoundaryInfoType inherited
typedef ImpTraits ::CommunicatorType Dune::GDT::SpaceInterface< ImpTraits , domainDim, rangeDim, rangeDimCols >::CommunicatorType inherited
typedef ImpTraits ::derived_type Dune::GDT::SpaceInterface< ImpTraits , domainDim, rangeDim, rangeDimCols >::derived_type inherited
template<class ImpTraits , size_t domainDim, size_t rangeDim, size_t rangeDimCols = 1> typedef GridViewType::ctype Dune::GDT::SpaceInterface< Traits, domainDim, rangeDim, rangeDimCols >::DomainFieldType
template<class ImpTraits , size_t domainDim, size_t rangeDim, size_t rangeDimCols = 1> typedef FieldVector<DomainFieldType, dimDomain> Dune::GDT::SpaceInterface< Traits, domainDim, rangeDim, rangeDimCols >::DomainType
template<class ImpTraits , size_t domainDim, size_t rangeDim, size_t rangeDimCols = 1> typedef GridViewType::template Codim<0>::Entity Dune::GDT::SpaceInterface< Traits, domainDim, rangeDim, rangeDimCols >::EntityType
typedef ImpTraits ::GridViewType Dune::GDT::SpaceInterface< ImpTraits , domainDim, rangeDim, rangeDimCols >::GridViewType inherited
typedef GridViewType::Intersection Dune::GDT::SpaceInterface< ImpTraits , domainDim, rangeDim, rangeDimCols >::IntersectionType inherited
typedef ImpTraits ::MapperType Dune::GDT::SpaceInterface< ImpTraits , domainDim, rangeDim, rangeDimCols >::MapperType inherited
template<class ImpTraits , size_t domainDim, size_t rangeDim, size_t rangeDimCols = 1> typedef Dune::Stuff::LA::SparsityPatternDefault Dune::GDT::SpaceInterface< Traits, domainDim, rangeDim, rangeDimCols >::PatternType
typedef ImpTraits ::RangeFieldType Dune::GDT::SpaceInterface< ImpTraits , domainDim, rangeDim, rangeDimCols >::RangeFieldType inherited
template<class ImpTraits , size_t domainDim, size_t rangeDim, size_t rangeDimCols = 1> typedef ImpTraits Dune::GDT::RtSpaceInterface< ImpTraits, domainDim, rangeDim, rangeDimCols >::Traits
Member Function Documentation
const BackendType& Dune::GDT::SpaceInterface< ImpTraits , domainDim, rangeDim, rangeDimCols >::backend () const inline inherited
BaseFunctionSetType Dune::GDT::SpaceInterface< ImpTraits , domainDim, rangeDim, rangeDimCols >::base_function_set (const EntityType & entity) const inline inherited
Referenced by Dune::GDT::CgSpaceInterface< ImpTraits, domainDim, rangeDim, rangeDimCols >::lagrange_points_order_1(), Dune::GDT::CgSpaceInterface< ImpTraits, domainDim, rangeDim, rangeDimCols >::local_dirichlet_DoFs_order_1(), Dune::GDT::CgSpaceInterface< ImpTraits, domainDim, rangeDim, rangeDimCols >::local_dirichlet_DoFs_simplicial_lagrange_elements(), and Dune::GDT::RtSpaceInterface< ImpTraits, domainDim, rangeDim, rangeDimCols >::local_DoF_indices_2dsimplex_order0().
CommunicatorType& Dune::GDT::SpaceInterface< ImpTraits , domainDim, rangeDim, rangeDimCols >::communicator () const inline inherited
PatternType Dune::GDT::SpaceInterface< ImpTraits , domainDim, rangeDim, rangeDimCols >::compute_face_and_volume_pattern () const inline inherited
Referenced by Dune::GDT::DgSpaceInterface< ImpTraits, domainDim, rangeDim, rangeDimCols >::compute_pattern(), and Dune::GDT::RtSpaceInterface< ImpTraits, domainDim, rangeDim, rangeDimCols >::compute_pattern().
PatternType Dune::GDT::SpaceInterface< ImpTraits , domainDim, rangeDim, rangeDimCols >::compute_face_and_volume_pattern (const GridView< G > & local_grid_view) const inline inherited
PatternType Dune::GDT::SpaceInterface< ImpTraits , domainDim, rangeDim, rangeDimCols >::compute_face_and_volume_pattern (const SpaceInterface< S, d, r, rC > & ansatz_space) const inline inherited
PatternType Dune::GDT::SpaceInterface< ImpTraits , domainDim, rangeDim, rangeDimCols >::compute_face_and_volume_pattern (const GridView< G > & local_grid_view, const SpaceInterface< S, d, r, rC > & ansatz_space) const inline inherited
computes a DG sparsity pattern, where this space is the test space (rows/outer) and the other space is the ansatz space (cols/inner)
PatternType Dune::GDT::SpaceInterface< ImpTraits , domainDim, rangeDim, rangeDimCols >::compute_face_pattern () const inline inherited
PatternType Dune::GDT::SpaceInterface< ImpTraits , domainDim, rangeDim, rangeDimCols >::compute_face_pattern (const GridView< G > & local_grid_view) const inline inherited
PatternType Dune::GDT::SpaceInterface< ImpTraits , domainDim, rangeDim, rangeDimCols >::compute_face_pattern (const SpaceInterface< S, d, r, rC > & ansatz_space) const inline inherited
PatternType Dune::GDT::SpaceInterface< ImpTraits , domainDim, rangeDim, rangeDimCols >::compute_face_pattern (const G & local_grid_view, const SpaceInterface< S, d, r, rC > & ansatz_space) const inline inherited
PatternType Dune::GDT::SpaceInterface< ImpTraits , domainDim, rangeDim, rangeDimCols >::compute_pattern () const inline inherited
PatternType Dune::GDT::SpaceInterface< ImpTraits , domainDim, rangeDim, rangeDimCols >::compute_pattern (const SpaceInterface< S, d, r, rC > & ansatz_space) const inline inherited
PatternType Dune::GDT::SpaceInterface< ImpTraits , domainDim, rangeDim, rangeDimCols >::compute_pattern (const GridView< G > & local_grid_view) const inline inherited
PatternType Dune::GDT::SpaceInterface< ImpTraits , domainDim, rangeDim, rangeDimCols >::compute_volume_pattern () const inline inherited
Referenced by Dune::GDT::CgSpaceInterface< ImpTraits, domainDim, rangeDim, rangeDimCols >::compute_pattern().
PatternType Dune::GDT::SpaceInterface< ImpTraits , domainDim, rangeDim, rangeDimCols >::compute_volume_pattern (const SpaceInterface< S, d, r, rC > & ansatz_space) const inline inherited
PatternType Dune::GDT::SpaceInterface< ImpTraits , domainDim, rangeDim, rangeDimCols >::compute_volume_pattern (const GridView< G > & local_grid_view) const inline inherited
PatternType Dune::GDT::SpaceInterface< ImpTraits , domainDim, rangeDim, rangeDimCols >::compute_volume_pattern (const GridView< G > & local_grid_view, const SpaceInterface< S, d, r, rC > & ansatz_space) const inline inherited
computes a sparsity pattern, where this space is the test space (rows/outer) and the other space is the ansatz space (cols/inner)
const GridViewType& Dune::GDT::SpaceInterface< ImpTraits , domainDim, rangeDim, rangeDimCols >::grid_view () const inline inherited
Referenced by Dune::GDT::CgSpaceInterface< ImpTraits, domainDim, rangeDim, rangeDimCols >::lagrange_points_order_1(), Dune::GDT::CgSpaceInterface< ImpTraits, domainDim, rangeDim, rangeDimCols >::local_dirichlet_DoFs_order_1(), Dune::GDT::CgSpaceInterface< ImpTraits, domainDim, rangeDim, rangeDimCols >::local_dirichlet_DoFs_simplicial_lagrange_elements(), and Dune::GDT::RtSpaceInterface< ImpTraits, domainDim, rangeDim, rangeDimCols >::local_DoF_indices_2dsimplex_order0().
void Dune::GDT::SpaceInterface< ImpTraits , domainDim, rangeDim, rangeDimCols >::local_constraints (const EntityType & entity, ConstraintsInterface< C > & ret) const inline inherited
const MapperType& Dune::GDT::SpaceInterface< ImpTraits , domainDim, rangeDim, rangeDimCols >::mapper () const inline inherited
Referenced by Dune::GDT::CgSpaceInterface< ImpTraits, domainDim, rangeDim, rangeDimCols >::local_constraints().
void Dune::GDT::SpaceInterface< ImpTraits , domainDim, rangeDim, rangeDimCols >::visualize (const std::string filename_prefix = "") const inline inherited
Member Data Documentation
const bool Dune::GDT::SpaceInterface< ImpTraits , domainDim, rangeDim, rangeDimCols >::continuous static inherited
const size_t Dune::GDT::SpaceInterface< ImpTraits , domainDim, rangeDim, rangeDimCols >::dimDomain static inherited
Referenced by Dune::GDT::CgSpaceInterface< ImpTraits, domainDim, rangeDim, rangeDimCols >::lagrange_points_order_1(), and Dune::GDT::RtSpaceInterface< ImpTraits, domainDim, rangeDim, rangeDimCols >::local_DoF_indices_2dsimplex_order0().
const size_t Dune::GDT::SpaceInterface< ImpTraits , domainDim, rangeDim, rangeDimCols >::dimRange static inherited
Referenced by Dune::GDT::CgSpaceInterface< ImpTraits, domainDim, rangeDim, rangeDimCols >::lagrange_points_order_1(), Dune::GDT::CgSpaceInterface< ImpTraits, domainDim, rangeDim, rangeDimCols >::local_dirichlet_DoFs_order_1(), and Dune::GDT::CgSpaceInterface< ImpTraits, domainDim, rangeDim, rangeDimCols >::local_dirichlet_DoFs_simplicial_lagrange_elements().
const size_t Dune::GDT::SpaceInterface< ImpTraits , domainDim, rangeDim, rangeDimCols >::dimRangeCols static inherited
const bool Dune::GDT::SpaceInterface< ImpTraits , domainDim, rangeDim, rangeDimCols >::needs_grid_view static inherited
const Stuff::Grid::ChoosePartView Dune::GDT::SpaceInterface< ImpTraits , domainDim, rangeDim, rangeDimCols >::part_view_type static inherited
const int Dune::GDT::SpaceInterface< ImpTraits , domainDim, rangeDim, rangeDimCols >::polOrder static inherited
Referenced by Dune::GDT::CgSpaceInterface< ImpTraits, domainDim, rangeDim, rangeDimCols >::lagrange_points_order_1(), Dune::GDT::CgSpaceInterface< ImpTraits, domainDim, rangeDim, rangeDimCols >::local_dirichlet_DoFs_order_1(), Dune::GDT::CgSpaceInterface< ImpTraits, domainDim, rangeDim, rangeDimCols >::local_dirichlet_DoFs_simplicial_lagrange_elements(), and Dune::GDT::RtSpaceInterface< ImpTraits, domainDim, rangeDim, rangeDimCols >::local_DoF_indices_2dsimplex_order0().
The documentation for this class was generated from the following file:
spaces/rt/interface.hh