Dune::GDT::SystemAssembler< TestSpaceImp, GridViewImp, AnsatzSpaceImp > Class Template Reference
Dune::GDT::SystemAssembler< TestSpaceImp, GridViewImp, AnsatzSpaceImp > Class Template Reference
#include <dune/gdt/assembler/system.hh>
Public Types
typedef TestSpaceImp TestSpaceType
typedef AnsatzSpaceImp AnsatzSpaceType
typedef
TestSpaceType::RangeFieldType RangeFieldType
typedef BaseType::GridViewType GridViewType
typedef BaseType::EntityType EntityType
typedef BaseType::IntersectionType IntersectionType
typedef
DSG::ApplyOn::WhichEntity
< GridViewType > ApplyOnWhichEntity
typedef
DSG::ApplyOn::WhichIntersection
< GridViewType > ApplyOnWhichIntersection
Public Member Functions
SystemAssembler (TestSpaceType test, AnsatzSpaceType ansatz, GridViewType grd_vw)
SystemAssembler (TestSpaceType test, AnsatzSpaceType ansatz)
SystemAssembler (TestSpaceType test)
SystemAssembler (TestSpaceType test, GridViewType grd_vw)
SystemAssembler (ThisType &&source)=default
const TestSpaceType & test_space () const
const AnsatzSpaceType & ansatz_space () const
template<class C >
void add (ConstraintsInterface< C > &constraints, const ApplyOnWhichEntity *where=new DSG::ApplyOn::AllEntities< GridViewType >())
template<class V , class M >
void add (const LocalVolumeTwoFormAssembler< V > &local_assembler, Stuff::LA::MatrixInterface< M, RangeFieldType > &matrix, const ApplyOnWhichEntity *where=new DSG::ApplyOn::AllEntities< GridViewType >())
template<class V , class M >
void add (const LocalCouplingTwoFormAssembler< V > &local_assembler, Stuff::LA::MatrixInterface< M, RangeFieldType > &matrix, const ApplyOnWhichIntersection *where=new DSG::ApplyOn::AllIntersections< GridViewType >())
template<class V , class M >
void add (const LocalBoundaryTwoFormAssembler< V > &local_assembler, Stuff::LA::MatrixInterface< M, RangeFieldType > &matrix, const ApplyOnWhichIntersection *where=new DSG::ApplyOn::AllIntersections< GridViewType >())
template<class L , class V >
void add (const LocalVolumeFunctionalAssembler< L > &local_assembler, Stuff::LA::VectorInterface< V, RangeFieldType > &vector, const ApplyOnWhichEntity *where=new DSG::ApplyOn::AllEntities< GridViewType >())
template<class L , class V >
void add (const LocalFaceFunctionalAssembler< L > &local_assembler, Stuff::LA::VectorInterface< V, RangeFieldType > &vector, const ApplyOnWhichIntersection *where=new DSG::ApplyOn::AllIntersections< GridViewType >())
void assemble (const bool use_tbb=false)
template<class Partitioning >
void assemble (const Partitioning &partitioning)
Protected Attributes
const DS::PerThreadValue
< const TestSpaceType > test_space_
const DS::PerThreadValue
< const AnsatzSpaceType > ansatz_space_
Member Typedef Documentation
template<class TestSpaceImp, class GridViewImp = typename TestSpaceImp::GridViewType, class AnsatzSpaceImp = TestSpaceImp> typedef AnsatzSpaceImp Dune::GDT::SystemAssembler< TestSpaceImp, GridViewImp, AnsatzSpaceImp >::AnsatzSpaceType
template<class TestSpaceImp, class GridViewImp = typename TestSpaceImp::GridViewType, class AnsatzSpaceImp = TestSpaceImp> typedef DSG::ApplyOn::WhichEntity<GridViewType> Dune::GDT::SystemAssembler< TestSpaceImp, GridViewImp, AnsatzSpaceImp >::ApplyOnWhichEntity
template<class TestSpaceImp, class GridViewImp = typename TestSpaceImp::GridViewType, class AnsatzSpaceImp = TestSpaceImp> typedef DSG::ApplyOn::WhichIntersection<GridViewType> Dune::GDT::SystemAssembler< TestSpaceImp, GridViewImp, AnsatzSpaceImp >::ApplyOnWhichIntersection
template<class TestSpaceImp, class GridViewImp = typename TestSpaceImp::GridViewType, class AnsatzSpaceImp = TestSpaceImp> typedef BaseType::EntityType Dune::GDT::SystemAssembler< TestSpaceImp, GridViewImp, AnsatzSpaceImp >::EntityType
template<class TestSpaceImp, class GridViewImp = typename TestSpaceImp::GridViewType, class AnsatzSpaceImp = TestSpaceImp> typedef BaseType::GridViewType Dune::GDT::SystemAssembler< TestSpaceImp, GridViewImp, AnsatzSpaceImp >::GridViewType
template<class TestSpaceImp, class GridViewImp = typename TestSpaceImp::GridViewType, class AnsatzSpaceImp = TestSpaceImp> typedef BaseType::IntersectionType Dune::GDT::SystemAssembler< TestSpaceImp, GridViewImp, AnsatzSpaceImp >::IntersectionType
template<class TestSpaceImp, class GridViewImp = typename TestSpaceImp::GridViewType, class AnsatzSpaceImp = TestSpaceImp> typedef TestSpaceType::RangeFieldType Dune::GDT::SystemAssembler< TestSpaceImp, GridViewImp, AnsatzSpaceImp >::RangeFieldType
template<class TestSpaceImp, class GridViewImp = typename TestSpaceImp::GridViewType, class AnsatzSpaceImp = TestSpaceImp> typedef TestSpaceImp Dune::GDT::SystemAssembler< TestSpaceImp, GridViewImp, AnsatzSpaceImp >::TestSpaceType
Constructor & Destructor Documentation
template<class TestSpaceImp, class GridViewImp = typename TestSpaceImp::GridViewType, class AnsatzSpaceImp = TestSpaceImp> Dune::GDT::SystemAssembler< TestSpaceImp, GridViewImp, AnsatzSpaceImp >::SystemAssembler (TestSpaceType test, AnsatzSpaceType ansatz, GridViewType grd_vw) inline
template<class TestSpaceImp, class GridViewImp = typename TestSpaceImp::GridViewType, class AnsatzSpaceImp = TestSpaceImp> Dune::GDT::SystemAssembler< TestSpaceImp, GridViewImp, AnsatzSpaceImp >::SystemAssembler (TestSpaceType test, AnsatzSpaceType ansatz) inline
template<class TestSpaceImp, class GridViewImp = typename TestSpaceImp::GridViewType, class AnsatzSpaceImp = TestSpaceImp> Dune::GDT::SystemAssembler< TestSpaceImp, GridViewImp, AnsatzSpaceImp >::SystemAssembler (TestSpaceType test) inline explicit
template<class TestSpaceImp, class GridViewImp = typename TestSpaceImp::GridViewType, class AnsatzSpaceImp = TestSpaceImp> Dune::GDT::SystemAssembler< TestSpaceImp, GridViewImp, AnsatzSpaceImp >::SystemAssembler (TestSpaceType test, GridViewType grd_vw) inline
template<class TestSpaceImp, class GridViewImp = typename TestSpaceImp::GridViewType, class AnsatzSpaceImp = TestSpaceImp> Dune::GDT::SystemAssembler< TestSpaceImp, GridViewImp, AnsatzSpaceImp >::SystemAssembler (ThisType && source) default
Member Function Documentation
template<class TestSpaceImp, class GridViewImp = typename TestSpaceImp::GridViewType, class AnsatzSpaceImp = TestSpaceImp> template<class C > void Dune::GDT::SystemAssembler< TestSpaceImp, GridViewImp, AnsatzSpaceImp >::add (ConstraintsInterface< C > & constraints, const ApplyOnWhichEntity * where = new DSG::ApplyOn::AllEntities<GridViewType>()) inline
template<class TestSpaceImp, class GridViewImp = typename TestSpaceImp::GridViewType, class AnsatzSpaceImp = TestSpaceImp> template<class V , class M > void Dune::GDT::SystemAssembler< TestSpaceImp, GridViewImp, AnsatzSpaceImp >::add (const LocalVolumeTwoFormAssembler< V > & local_assembler, Stuff::LA::MatrixInterface< M, RangeFieldType > & matrix, const ApplyOnWhichEntity * where = new DSG::ApplyOn::AllEntities<GridViewType>()) inline
template<class TestSpaceImp, class GridViewImp = typename TestSpaceImp::GridViewType, class AnsatzSpaceImp = TestSpaceImp> template<class V , class M > void Dune::GDT::SystemAssembler< TestSpaceImp, GridViewImp, AnsatzSpaceImp >::add (const LocalCouplingTwoFormAssembler< V > & local_assembler, Stuff::LA::MatrixInterface< M, RangeFieldType > & matrix, const ApplyOnWhichIntersection * where = new DSG::ApplyOn::AllIntersections<GridViewType>()) inline
template<class TestSpaceImp, class GridViewImp = typename TestSpaceImp::GridViewType, class AnsatzSpaceImp = TestSpaceImp> template<class V , class M > void Dune::GDT::SystemAssembler< TestSpaceImp, GridViewImp, AnsatzSpaceImp >::add (const LocalBoundaryTwoFormAssembler< V > & local_assembler, Stuff::LA::MatrixInterface< M, RangeFieldType > & matrix, const ApplyOnWhichIntersection * where = new DSG::ApplyOn::AllIntersections<GridViewType>()) inline
template<class TestSpaceImp, class GridViewImp = typename TestSpaceImp::GridViewType, class AnsatzSpaceImp = TestSpaceImp> template<class L , class V > void Dune::GDT::SystemAssembler< TestSpaceImp, GridViewImp, AnsatzSpaceImp >::add (const LocalVolumeFunctionalAssembler< L > & local_assembler, Stuff::LA::VectorInterface< V, RangeFieldType > & vector, const ApplyOnWhichEntity * where = new DSG::ApplyOn::AllEntities<GridViewType>()) inline
template<class TestSpaceImp, class GridViewImp = typename TestSpaceImp::GridViewType, class AnsatzSpaceImp = TestSpaceImp> template<class L , class V > void Dune::GDT::SystemAssembler< TestSpaceImp, GridViewImp, AnsatzSpaceImp >::add (const LocalFaceFunctionalAssembler< L > & local_assembler, Stuff::LA::VectorInterface< V, RangeFieldType > & vector, const ApplyOnWhichIntersection * where = new DSG::ApplyOn::AllIntersections<GridViewType>()) inline
template<class TestSpaceImp, class GridViewImp = typename TestSpaceImp::GridViewType, class AnsatzSpaceImp = TestSpaceImp> const AnsatzSpaceType& Dune::GDT::SystemAssembler< TestSpaceImp, GridViewImp, AnsatzSpaceImp >::ansatz_space () const inline
template<class TestSpaceImp, class GridViewImp = typename TestSpaceImp::GridViewType, class AnsatzSpaceImp = TestSpaceImp> void Dune::GDT::SystemAssembler< TestSpaceImp, GridViewImp, AnsatzSpaceImp >::assemble (const bool use_tbb = false) inline
Referenced by Dune::GDT::VectorFunctionalBase< Vector, Space, GridView, Field >::apply(), Dune::GDT::MatrixOperatorBase< Matrix, RangeSpace, GridView, SourceSpace, Field, ChoosePattern::volume >::apply(), and Dune::GDT::MatrixOperatorBase< Matrix, RangeSpace, GridView, SourceSpace, Field, ChoosePattern::volume >::apply2().
template<class TestSpaceImp, class GridViewImp = typename TestSpaceImp::GridViewType, class AnsatzSpaceImp = TestSpaceImp> template<class Partitioning > void Dune::GDT::SystemAssembler< TestSpaceImp, GridViewImp, AnsatzSpaceImp >::assemble (const Partitioning & partitioning) inline
template<class TestSpaceImp, class GridViewImp = typename TestSpaceImp::GridViewType, class AnsatzSpaceImp = TestSpaceImp> const TestSpaceType& Dune::GDT::SystemAssembler< TestSpaceImp, GridViewImp, AnsatzSpaceImp >::test_space () const inline
Member Data Documentation
template<class TestSpaceImp, class GridViewImp = typename TestSpaceImp::GridViewType, class AnsatzSpaceImp = TestSpaceImp> const DS::PerThreadValue<const AnsatzSpaceType> Dune::GDT::SystemAssembler< TestSpaceImp, GridViewImp, AnsatzSpaceImp >::ansatz_space_ protected
Referenced by Dune::GDT::SystemAssembler< SpaceImp, GridViewImp >::add(), and Dune::GDT::SystemAssembler< SpaceImp, GridViewImp >::ansatz_space().
template<class TestSpaceImp, class GridViewImp = typename TestSpaceImp::GridViewType, class AnsatzSpaceImp = TestSpaceImp> const DS::PerThreadValue<const TestSpaceType> Dune::GDT::SystemAssembler< TestSpaceImp, GridViewImp, AnsatzSpaceImp >::test_space_ protected
Referenced by Dune::GDT::SystemAssembler< SpaceImp, GridViewImp >::add(), and Dune::GDT::SystemAssembler< SpaceImp, GridViewImp >::test_space().
The documentation for this class was generated from the following file:
system.hh