Dune::GDT::StationaryContainerBasedDefaultDiscretization< ProblemType, AnsatzSpaceType, MatrixType, VectorType, TestSpaceType > Class Template Reference
Dune::GDT::StationaryContainerBasedDefaultDiscretization< ProblemType, AnsatzSpaceType, MatrixType, VectorType, TestSpaceType > Class Template Reference
#include <dune/gdt/discretizations/default.hh>
Public Types
typedef Traits::MatrixType MatrixType
typedef
internal::StationaryContainerBasedDefaultDiscretizationTraits
< ProblemImp, AnsatzSpaceImp,
MatrixImp, VectorImp,
TestSpaceImp >::VectorType VectorType
typedef
internal::StationaryContainerBasedDefaultDiscretizationTraits
< ProblemImp, AnsatzSpaceImp,
MatrixImp, VectorImp,
TestSpaceImp >::ProblemType ProblemType
typedef
internal::StationaryContainerBasedDefaultDiscretizationTraits
< ProblemImp, AnsatzSpaceImp,
MatrixImp, VectorImp,
TestSpaceImp >
::AnsatzSpaceType AnsatzSpaceType
typedef
internal::StationaryContainerBasedDefaultDiscretizationTraits
< ProblemImp, AnsatzSpaceImp,
MatrixImp, VectorImp,
TestSpaceImp >::TestSpaceType TestSpaceType
Public Member Functions
StationaryContainerBasedDefaultDiscretization (const ProblemType &prblm, AnsatzSpaceType ansatz_sp, TestSpaceType test_sp, MatrixType system_mtrx, VectorType rhs_vec, VectorType dirichlet)
StationaryContainerBasedDefaultDiscretization (const ProblemType &prblm, AnsatzSpaceType ansatz_sp, MatrixType system_mtrx, VectorType rhs_vec, VectorType dirichlet)
StationaryContainerBasedDefaultDiscretization (const ProblemType &prblm, AnsatzSpaceType ansatz_sp, TestSpaceType test_sp, MatrixType system_mtrx, VectorType rhs_vec)
StationaryContainerBasedDefaultDiscretization (const ProblemType &prblm, AnsatzSpaceType ansatz_sp, MatrixType system_mtrx, VectorType rhs_vec)
StationaryContainerBasedDefaultDiscretization (ThisType &&)=default
Required by StationaryDiscretizationInterface.
const ProblemType & problem () const
const AnsatzSpaceType & ansatz_space () const
const TestSpaceType & test_space () const
Required by ContainerBasedStationaryDiscretizationInterface.
const MatrixType & system_matrix () const
const VectorType & rhs_vector () const
bool has_dirichlet_shift () const
const VectorType & dirichlet_shift () const
Provided by the interface for convenience.
std::vector< std::string > solver_types () const
Stuff::Common::Configuration solver_options (const std::string type="") const
void solve (VectorType &solution, const Stuff::Common::Configuration &options) const
Provided by the interface for convenience.
void solve (VectorType &solution, const std::string &type) const
void solve (VectorType &solution) const
VectorType solve (const Stuff::Common::Configuration &options) const
VectorType solve (const std::string &type) const
VectorType solve () const
VectorType create_vector () const
void visualize (const VectorType &vector, const std::string filename, const std::string name) const
Member Typedef Documentation
typedef internal::StationaryContainerBasedDefaultDiscretizationTraits< ProblemImp, AnsatzSpaceImp, MatrixImp, VectorImp, TestSpaceImp > ::AnsatzSpaceType Dune::GDT::StationaryDiscretizationInterface< internal::StationaryContainerBasedDefaultDiscretizationTraits< ProblemImp, AnsatzSpaceImp, MatrixImp, VectorImp, TestSpaceImp > >::AnsatzSpaceType inherited
template<class ProblemType , class AnsatzSpaceType , class MatrixType , class VectorType , class TestSpaceType = AnsatzSpaceType> typedef Traits::MatrixType Dune::GDT::ContainerBasedStationaryDiscretizationInterface< Traits >::MatrixType
typedef internal::StationaryContainerBasedDefaultDiscretizationTraits< ProblemImp, AnsatzSpaceImp, MatrixImp, VectorImp, TestSpaceImp > ::ProblemType Dune::GDT::StationaryDiscretizationInterface< internal::StationaryContainerBasedDefaultDiscretizationTraits< ProblemImp, AnsatzSpaceImp, MatrixImp, VectorImp, TestSpaceImp > >::ProblemType inherited
typedef internal::StationaryContainerBasedDefaultDiscretizationTraits< ProblemImp, AnsatzSpaceImp, MatrixImp, VectorImp, TestSpaceImp > ::TestSpaceType Dune::GDT::StationaryDiscretizationInterface< internal::StationaryContainerBasedDefaultDiscretizationTraits< ProblemImp, AnsatzSpaceImp, MatrixImp, VectorImp, TestSpaceImp > >::TestSpaceType inherited
typedef internal::StationaryContainerBasedDefaultDiscretizationTraits< ProblemImp, AnsatzSpaceImp, MatrixImp, VectorImp, TestSpaceImp > ::VectorType Dune::GDT::StationaryDiscretizationInterface< internal::StationaryContainerBasedDefaultDiscretizationTraits< ProblemImp, AnsatzSpaceImp, MatrixImp, VectorImp, TestSpaceImp > >::VectorType inherited
Constructor & Destructor Documentation
template<class ProblemType , class AnsatzSpaceType , class MatrixType , class VectorType , class TestSpaceType = AnsatzSpaceType> Dune::GDT::StationaryContainerBasedDefaultDiscretization< ProblemType, AnsatzSpaceType, MatrixType, VectorType, TestSpaceType >::StationaryContainerBasedDefaultDiscretization (const ProblemType & prblm, AnsatzSpaceType ansatz_sp, TestSpaceType test_sp, MatrixType system_mtrx, VectorType rhs_vec, VectorType dirichlet) inline
template<class ProblemType , class AnsatzSpaceType , class MatrixType , class VectorType , class TestSpaceType = AnsatzSpaceType> Dune::GDT::StationaryContainerBasedDefaultDiscretization< ProblemType, AnsatzSpaceType, MatrixType, VectorType, TestSpaceType >::StationaryContainerBasedDefaultDiscretization (const ProblemType & prblm, AnsatzSpaceType ansatz_sp, MatrixType system_mtrx, VectorType rhs_vec, VectorType dirichlet) inline
template<class ProblemType , class AnsatzSpaceType , class MatrixType , class VectorType , class TestSpaceType = AnsatzSpaceType> Dune::GDT::StationaryContainerBasedDefaultDiscretization< ProblemType, AnsatzSpaceType, MatrixType, VectorType, TestSpaceType >::StationaryContainerBasedDefaultDiscretization (const ProblemType & prblm, AnsatzSpaceType ansatz_sp, TestSpaceType test_sp, MatrixType system_mtrx, VectorType rhs_vec) inline
template<class ProblemType , class AnsatzSpaceType , class MatrixType , class VectorType , class TestSpaceType = AnsatzSpaceType> Dune::GDT::StationaryContainerBasedDefaultDiscretization< ProblemType, AnsatzSpaceType, MatrixType, VectorType, TestSpaceType >::StationaryContainerBasedDefaultDiscretization (const ProblemType & prblm, AnsatzSpaceType ansatz_sp, MatrixType system_mtrx, VectorType rhs_vec) inline
template<class ProblemType , class AnsatzSpaceType , class MatrixType , class VectorType , class TestSpaceType = AnsatzSpaceType> Dune::GDT::StationaryContainerBasedDefaultDiscretization< ProblemType, AnsatzSpaceType, MatrixType, VectorType, TestSpaceType >::StationaryContainerBasedDefaultDiscretization (ThisType &&) default
Member Function Documentation
template<class ProblemType , class AnsatzSpaceType , class MatrixType , class VectorType , class TestSpaceType = AnsatzSpaceType> const AnsatzSpaceType& Dune::GDT::StationaryContainerBasedDefaultDiscretization< ProblemType, AnsatzSpaceType, MatrixType, VectorType, TestSpaceType >::ansatz_space () const inline
VectorType Dune::GDT::StationaryDiscretizationInterface< internal::StationaryContainerBasedDefaultDiscretizationTraits< ProblemImp, AnsatzSpaceImp, MatrixImp, VectorImp, TestSpaceImp > >::create_vector () const inline inherited
References Dune::GDT::StationaryDiscretizationInterface< Traits >::ansatz_space().
template<class ProblemType , class AnsatzSpaceType , class MatrixType , class VectorType , class TestSpaceType = AnsatzSpaceType> const VectorType& Dune::GDT::StationaryContainerBasedDefaultDiscretization< ProblemType, AnsatzSpaceType, MatrixType, VectorType, TestSpaceType >::dirichlet_shift () const inline
template<class ProblemType , class AnsatzSpaceType , class MatrixType , class VectorType , class TestSpaceType = AnsatzSpaceType> bool Dune::GDT::StationaryContainerBasedDefaultDiscretization< ProblemType, AnsatzSpaceType, MatrixType, VectorType, TestSpaceType >::has_dirichlet_shift () const inline
template<class ProblemType , class AnsatzSpaceType , class MatrixType , class VectorType , class TestSpaceType = AnsatzSpaceType> const ProblemType& Dune::GDT::StationaryContainerBasedDefaultDiscretization< ProblemType, AnsatzSpaceType, MatrixType, VectorType, TestSpaceType >::problem () const inline
template<class ProblemType , class AnsatzSpaceType , class MatrixType , class VectorType , class TestSpaceType = AnsatzSpaceType> const VectorType& Dune::GDT::StationaryContainerBasedDefaultDiscretization< ProblemType, AnsatzSpaceType, MatrixType, VectorType, TestSpaceType >::rhs_vector () const inline
void Dune::GDT::StationaryDiscretizationInterface< internal::StationaryContainerBasedDefaultDiscretizationTraits< ProblemImp, AnsatzSpaceImp, MatrixImp, VectorImp, TestSpaceImp > >::solve (VectorType & solution, const std::string & type) const inline inherited
References Dune::GDT::StationaryDiscretizationInterface< Traits >::solve(), and Dune::GDT::StationaryDiscretizationInterface< Traits >::solver_options().
void Dune::GDT::StationaryDiscretizationInterface< internal::StationaryContainerBasedDefaultDiscretizationTraits< ProblemImp, AnsatzSpaceImp, MatrixImp, VectorImp, TestSpaceImp > >::solve (VectorType & solution) const inline inherited
References Dune::GDT::StationaryDiscretizationInterface< Traits >::solve(), Dune::GDT::StationaryDiscretizationInterface< Traits >::solver_options(), and Dune::GDT::StationaryDiscretizationInterface< Traits >::solver_types().
VectorType Dune::GDT::StationaryDiscretizationInterface< internal::StationaryContainerBasedDefaultDiscretizationTraits< ProblemImp, AnsatzSpaceImp, MatrixImp, VectorImp, TestSpaceImp > >::solve (const Stuff::Common::Configuration & options) const inline inherited
References Dune::GDT::StationaryDiscretizationInterface< Traits >::create_vector(), and Dune::GDT::StationaryDiscretizationInterface< Traits >::solve().
VectorType Dune::GDT::StationaryDiscretizationInterface< internal::StationaryContainerBasedDefaultDiscretizationTraits< ProblemImp, AnsatzSpaceImp, MatrixImp, VectorImp, TestSpaceImp > >::solve (const std::string & type) const inline inherited
References Dune::GDT::StationaryDiscretizationInterface< Traits >::create_vector(), and Dune::GDT::StationaryDiscretizationInterface< Traits >::solve().
VectorType Dune::GDT::StationaryDiscretizationInterface< internal::StationaryContainerBasedDefaultDiscretizationTraits< ProblemImp, AnsatzSpaceImp, MatrixImp, VectorImp, TestSpaceImp > >::solve () const inline inherited
References Dune::GDT::StationaryDiscretizationInterface< Traits >::create_vector(), and Dune::GDT::StationaryDiscretizationInterface< Traits >::solve().
void Dune::GDT::ContainerBasedStationaryDiscretizationInterface< internal::StationaryContainerBasedDefaultDiscretizationTraits< ProblemImp, AnsatzSpaceImp, MatrixImp, VectorImp, TestSpaceImp > >::solve (VectorType & solution, const Stuff::Common::Configuration & options) const inline inherited
References Dune::GDT::ContainerBasedStationaryDiscretizationInterface< Traits >::dirichlet_shift(), Dune::GDT::ContainerBasedStationaryDiscretizationInterface< Traits >::has_dirichlet_shift(), Dune::GDT::ContainerBasedStationaryDiscretizationInterface< Traits >::rhs_vector(), and Dune::GDT::ContainerBasedStationaryDiscretizationInterface< Traits >::system_matrix().
Stuff::Common::Configuration Dune::GDT::ContainerBasedStationaryDiscretizationInterface< internal::StationaryContainerBasedDefaultDiscretizationTraits< ProblemImp, AnsatzSpaceImp, MatrixImp, VectorImp, TestSpaceImp > >::solver_options (const std::string type = "") const inline inherited
std::vector<std::string> Dune::GDT::ContainerBasedStationaryDiscretizationInterface< internal::StationaryContainerBasedDefaultDiscretizationTraits< ProblemImp, AnsatzSpaceImp, MatrixImp, VectorImp, TestSpaceImp > >::solver_types () const inline inherited
template<class ProblemType , class AnsatzSpaceType , class MatrixType , class VectorType , class TestSpaceType = AnsatzSpaceType> const MatrixType& Dune::GDT::StationaryContainerBasedDefaultDiscretization< ProblemType, AnsatzSpaceType, MatrixType, VectorType, TestSpaceType >::system_matrix () const inline
template<class ProblemType , class AnsatzSpaceType , class MatrixType , class VectorType , class TestSpaceType = AnsatzSpaceType> const TestSpaceType& Dune::GDT::StationaryContainerBasedDefaultDiscretization< ProblemType, AnsatzSpaceType, MatrixType, VectorType, TestSpaceType >::test_space () const inline
void Dune::GDT::StationaryDiscretizationInterface< internal::StationaryContainerBasedDefaultDiscretizationTraits< ProblemImp, AnsatzSpaceImp, MatrixImp, VectorImp, TestSpaceImp > >::visualize (const VectorType & vector, const std::string filename, const std::string name) const inline inherited
References Dune::GDT::StationaryDiscretizationInterface< Traits >::ansatz_space(), and Dune::GDT::make_const_discrete_function().
The documentation for this class was generated from the following file:
discretizations/default.hh