Dune::GDT Namespace Reference
Dune::GDT Namespace Reference
Namespaces
BaseFunctionSet
internal
LocalEllipticIpdgIntegrands
Contains local integrands for the symmetric weighted interior penalty discontinuous Galerkin (SWIPDG) discretization.
LocalSipdgIntegrands
Contains local evaluations for the symmetric interior penalty discontinuous Galerkin (SIPDG) discretization.
Mapper
SpaceTools
Classes
class SystemAssembler
class ConstDiscreteFunction
class DiscreteFunction
struct is_const_discrete_function
struct is_const_discrete_function< D, false >
struct is_discrete_function
struct is_discrete_function< D, false >
class ReinterpretDiscreteFunction
class StationaryContainerBasedDefaultDiscretization
class HyperbolicFVDefaultDiscretization
class StationaryDiscretizationInterface
class ContainerBasedStationaryDiscretizationInterface
class FVDiscretizationInterface
struct is_stationary_discretization
struct is_stationary_discretization< D, false >
class operator_error
class prolongation_error
class projection_error
class VectorFunctionalBase
class EllipticIpdgDirichletVectorFunctional
class FunctionalInterface
class L2VolumeVectorFunctional
class L2FaceVectorFunctional
class LocalVolumeTwoFormAssembler
class LocalVolumeTwoFormAccumulator
class LocalOperatorApplicator
class LocalCouplingTwoFormAssembler
class LocalCouplingOperatorApplicator
class LocalBoundaryTwoFormAssembler
class LocalBoundaryOperatorApplicator
class LocalVolumeFunctionalAssembler
class LocalFaceFunctionalAssembler
class ConstLocalDiscreteFunction
class LocalDiscreteFunction
class ConstLocalDoFVector
class LocalDoFVector
class GlobalFunctionBasedAnalyticalFlux
class LocalGodunovNumericalCouplingFlux
class LocalGodunovNumericalBoundaryFlux
class LocalNumericalCouplingFluxInterface
class LocalNumericalBoundaryFluxInterface
class AnalyticalFluxInterface
class AnalyticalFluxInterface< E, D, d, R, r, rC, true >
class AutonomousAnalyticalFluxInterface
class RhsEvaluationFluxInterface
struct is_local_numerical_coupling_flux
struct is_local_numerical_boundary_flux
struct is_analytical_flux
struct is_rhs_evaluation
class LocalLaxFriedrichsNumericalCouplingFlux
class LocalLaxFriedrichsDirichletNumericalBoundaryFlux
class LocalLaxFriedrichsAbsorbingNumericalBoundaryFlux
class CheckerboardBasedRhsEvaluationFlux
class LocalVolumeIntegralFunctional
class LocalFaceIntegralFunctional
class LocalVolumeFunctionalInterface
class LocalFaceFunctionalInterface
struct is_local_volume_functional
struct is_local_volume_functional< T, false >
class LocalEllipticIntegrand
Computes an elliptic evaluation.
class LocalDiffusiveFluxEstimateESV2007Integrand
class LocalDiffusiveFluxEstimateESV2007Integrand< DiffusionType, DiffusiveFluxType, void >
class LocalVolumeIntegrandInterface
Interface for local evaluations that depend on a codim 0 entity.
class LocalVolumeIntegrandInterface< Traits, 1 >
Interface for unary codim 0 evaluations.
class LocalVolumeIntegrandInterface< Traits, 2 >
Interface for binary codim 0 evaluations.
class LocalFaceIntegrandInterface
Interface for local evaluations that depend on an intersection.
class LocalFaceIntegrandInterface< Traits, 1 >
Interface for unary codim 1 evaluations.
class LocalFaceIntegrandInterface< Traits, 2 >
Interface for binary codim 1 evaluations.
class LocalFaceIntegrandInterface< Traits, 4 >
Interface for quaternary codim 1 evaluations.
class LocalProductIntegrand
Computes a product evaluation.
class LocalDirichletProjectionOperator
class LocalCouplingFvOperator
class LocalBoundaryFvOperator
class LocalRhsFvOperator
class LocalReconstructionFvOperator
class LocalVolumeIntegralOperator
class LocalCouplingIntegralOperator
class LocalBoundaryIntegralOperator
class LocalOperatorInterface
class LocalCouplingOperatorInterface
class LocalBoundaryOperatorInterface
class LocalVolumeTwoFormInterface
class LocalCouplingTwoFormInterface
class LocalBoundaryTwoFormInterface
struct is_local_operator
struct is_local_coupling_operator
struct is_local_boundary_operator
struct is_local_volume_twoform
struct is_local_coupling_twoform
struct is_local_boundary_twoform
class LocalL2ProjectionOperator
class LocalLagrangeProjectionOperator
class MatrixOperatorBase
class LocalizableProductBase
class LocalizableOperatorBase
class DarcyOperator
class EllipticIpdgMatrixOperator
class EllipticLocalizableProduct
class EllipticMatrixOperator
class EllipticOperator
class DiffusiveFluxReconstructionOperator
class DiffusiveFluxReconstructionOperator< GridViewType, LocalizableFunctionType, void >
class AdvectionLaxFriedrichsOperator
class AdvectionGodunovOperator
class AdvectionRHSOperator
class AdvectionLocalizableDefault
class LinearReconstructionLocalizable
class OperatorInterface
struct is_operator
struct is_operator<T, false >
class L2LocalizableProduct
class L2MatrixOperator
class L2Operator
class LaplaceLocalizableProduct
class LaplaceMatrixOperator
class LaplaceOperator
class OswaldInterpolationOperator
class WeightedL2LocalizableProduct
class WeightedL2MatrixOperator
class WeightedL2Operator
class LocalDiffusiveFluxEstimateStarOS2014Integrand
class BlockSpace
class DuneFemLocalfunctionsCgSpaceWrapper
class DuneFemLocalfunctionsDgSpaceWrapper
class DunePdelabDgSpaceWrapper
class BlockMapper
class ProductDgMapper
class ProductDgMapper< PdelabSpaceImp, rangeDim, 1 >
class RosenbrockTimeStepper
Time stepper using Rosenbrock-type methods.
class DirichletProjectionLocalizableOperator
class L2GlobalProjectionOperator
class L2GlobalProjectionLocalizableOperator
class L2LocalProjectionOperator
class L2LocalProjectionLocalizableOperator
class L2ProjectionOperator
class L2ProjectionLocalizableOperator
class LagrangeProjectionLocalizableOperator
class LagrangeProjectionOperator
class L2GlobalProlongationOperator
class L2GlobalProlongationLocalizableOperator
class L2LocalProlongationOperator
class L2LocalProlongationLocalizableOperator
Carries out a prolongation (in a localized manner) using a local L2 projection.
class L2ProlongationOperator
class L2ProlongationLocalizableOperator
class LagrangeProlongationOperator
class LagrangeProlongationLocalizableOperator
Carries out a prolongation (in a localized manner) using a lagrange projection.
class BaseFunctionSetInterface
The purpose of this interface is just to be used for template matching and to allow for access to the backend. All other functionality is enforced by Stuff::LocalfunctionSetInterface.
class DuneFemCgSpaceWrapper
class DunePdelabCgSpaceWrapper
class CgSpaceInterface
struct is_cg_space
struct is_cg_space< S, false >
class CgSpaceProvider
class ConstraintsInterface
CRTP interface for all implementations of constraints.
class DirichletConstraints
class DuneFemDgSpaceWrapper
class DgSpaceInterface
struct is_dg_space
struct is_dg_space< S, false >
class DgSpaceProvider
class FvSpace
class FvSpace< GridViewImp, RangeFieldImp, rangeDim, 1 >
class FvSpaceInterface
struct is_fv_space
struct is_fv_space< S, false >
class FvProductSpace
class FvProductSpace< GridViewImp, RangeFieldImp, rangeDim, 1 >
struct ChooseGridPartView
struct ChooseGridPartView< ChooseSpaceBackend::gdt >
struct ChooseGridPartView< ChooseSpaceBackend::pdelab >
struct ChooseGridPartView< ChooseSpaceBackend::fem >
class SpaceInterface
class ProductSpaceInterface
struct is_space
struct is_space< S, false >
struct is_product_space
struct is_product_space< S, false >
class DunePdelabCgMapperWrapper
class DunePdelabDgMapperWrapper
class FvMapper
class FvProductMapper
class FvMapper< GridViewImp, rangeDim, 1 >
class FvMapper< GridViewImp, 1, 1 >
class FvProductMapper< GridViewImp, rangeDim, 1 >
class MapperInterface
class IsProductMapper
class ProductMapperInterface
class DefaultProductMapper
struct DefaultProductMapperFromTuple
struct DefaultProductMapperFromTuple< GridViewImp, std::tuple< MapperTypes...> >
struct CommunicationChooser
struct CommunicationChooser< ViewImp, true >
class DefaultProductSpace
class DunePdelabRtSpaceWrapper
class RtSpaceInterface
struct is_rt_space
struct is_rt_space< S, false >
class DunePdelabTaylorHoodSpaceWrapper
class AdaptiveRungeKuttaTimeStepper
Time stepper using adaptive Runge Kutta methods.
class ExplicitRungeKuttaTimeStepper
Time stepper using Runge Kutta methods.
struct TimeStepperFactory
class FractionalTimeStepper
class TimeStepperInterface
struct is_unary_volume_integrand
struct is_unary_volume_integrand< T, false >
struct is_binary_volume_integrand
struct is_binary_volume_integrand< T, false >
struct is_unary_face_integrand
struct is_unary_face_integrand< T, false >
struct is_binary_face_integrand
struct is_binary_face_integrand< T, false >
struct is_quaternary_face_integrand
struct is_quaternary_face_integrand< T, false >
Enumerations
enum SlopeLimiters { SlopeLimiters::minmod, SlopeLimiters::mc, SlopeLimiters::superbee, SlopeLimiters::no_slope }
enum NumericalFluxes {
NumericalFluxes::godunov, NumericalFluxes::godunov_with_reconstruction, NumericalFluxes::laxfriedrichs, NumericalFluxes::laxfriedrichs_with_reconstruction,
NumericalFluxes::local_laxfriedrichs, NumericalFluxes::local_laxfriedrichs_with_reconstruction
}
enum RosenbrockTimeStepperMethods { RosenbrockTimeStepperMethods::GRK4A, RosenbrockTimeStepperMethods::GRK4T, RosenbrockTimeStepperMethods::other }
enum ChooseSpaceBackend { ChooseSpaceBackend::gdt, ChooseSpaceBackend::pdelab, ChooseSpaceBackend::fem }
enum ChoosePattern { ChoosePattern::volume, ChoosePattern::face, ChoosePattern::face_and_volume }
enum TimeStepperMethods {
TimeStepperMethods::bogacki_shampine, TimeStepperMethods::dormand_prince, TimeStepperMethods::adaptive_rungekutta_other, TimeStepperMethods::explicit_euler,
TimeStepperMethods::explicit_rungekutta_second_order_ssp, TimeStepperMethods::explicit_rungekutta_third_order_ssp, TimeStepperMethods::explicit_rungekutta_classic_fourth_order, TimeStepperMethods::explicit_rungekutta_other
}
Functions
template<class SpaceType , class VectorType >
ConstDiscreteFunction
< SpaceType, VectorType > make_const_discrete_function (const SpaceType &space, const VectorType &vector, const std::string nm="gdt.constdiscretefunction")
template<class SpaceType , class VectorType >
std::enable_if< is_space
< SpaceType >::value
&&Stuff::LA::is_vector
< VectorType >::value,
DiscreteFunction< SpaceType,
VectorType > >::type make_discrete_function (const SpaceType &space, VectorType &vector, const std::string nm="gdt.discretefunction")
template<class VectorType , class SpaceType >
DiscreteFunction< SpaceType,
VectorType > make_discrete_function (const SpaceType &space, const std::string nm="gdt.discretefunction")
template<class VectorType , LocalEllipticIpdgIntegrands::Method method, class DirichletType , class DiffusionFactorType , class DiffusionTensorType , class SpaceType >
std::enable_if
< Stuff::LA::is_vector
< VectorType >::value
&&Stuff::is_localizable_function
< DirichletType >::value
&&Stuff::is_localizable_function
< DiffusionFactorType >::value
&&Stuff::is_localizable_function
< DiffusionTensorType >::value
&&is_space< SpaceType >::value,
std::unique_ptr
< EllipticIpdgDirichletVectorFunctional
< DirichletType,
DiffusionFactorType,
DiffusionTensorType, SpaceType,
method, VectorType > > >::type make_elliptic_ipdg_dirichlet_vector_functional (const DirichletType &dirichlet, const DiffusionFactorType &diffusion_factor, const DiffusionTensorType &diffusion_tensor, const Stuff::Grid::BoundaryInfoInterface< typename SpaceType::GridViewType::Intersection > &boundary_info, const SpaceType &space, const size_t over_integrate=0)
template<class VectorType , class DirichletType , class DiffusionFactorType , class DiffusionTensorType , class SpaceType >
std::enable_if
< Stuff::LA::is_vector
< VectorType >::value
&&Stuff::is_localizable_function
< DirichletType >::value
&&Stuff::is_localizable_function
< DiffusionFactorType >::value
&&Stuff::is_localizable_function
< DiffusionTensorType >::value
&&is_space< SpaceType >::value,
std::unique_ptr
< EllipticIpdgDirichletVectorFunctional
< DirichletType,
DiffusionFactorType,
DiffusionTensorType, SpaceType,
LocalEllipticIpdgIntegrands::default_method,
VectorType > > >::type make_elliptic_ipdg_dirichlet_vector_functional (const DirichletType &dirichlet, const DiffusionFactorType &diffusion_factor, const DiffusionTensorType &diffusion_tensor, const Stuff::Grid::BoundaryInfoInterface< typename SpaceType::GridViewType::Intersection > &boundary_info, const SpaceType &space, const size_t over_integrate=0)
template<LocalEllipticIpdgIntegrands::Method method, class DirichletType , class DiffusionFactorType , class DiffusionTensorType , class VectorType , class SpaceType >
std::enable_if
< Stuff::is_localizable_function
< DirichletType >::value
&&Stuff::is_localizable_function
< DiffusionFactorType >::value
&&Stuff::is_localizable_function
< DiffusionTensorType >::value
&&Stuff::LA::is_vector
< VectorType >::value
&&is_space< SpaceType >::value,
std::unique_ptr
< EllipticIpdgDirichletVectorFunctional
< DirichletType,
DiffusionFactorType,
DiffusionTensorType, SpaceType,
method, VectorType > > >::type make_elliptic_ipdg_dirichlet_vector_functional (const DirichletType &dirichlet, const DiffusionFactorType &diffusion_factor, const DiffusionTensorType &diffusion_tensor, const Stuff::Grid::BoundaryInfoInterface< typename SpaceType::GridViewType::Intersection > &boundary_info, VectorType &vector, const SpaceType &space, const size_t over_integrate=0)
template<class VectorType , class FunctionType , class SpaceType >
std::enable_if
< Stuff::LA::is_vector
< VectorType >::value
&&Stuff::is_localizable_function
< FunctionType >::value
&&is_space< SpaceType >::value,
std::unique_ptr
< L2VolumeVectorFunctional
< FunctionType, SpaceType,
VectorType > > >::type make_l2_volume_vector_functional (const FunctionType &function, const SpaceType &space, const size_t over_integrate=0)
template<class VectorType , class FunctionType , class SpaceType , class GridViewType >
std::enable_if
< Stuff::LA::is_vector
< VectorType >::value
&&Stuff::is_localizable_function
< FunctionType >::value
&&is_space< SpaceType >::value
&&Stuff::Grid::is_grid_layer
< GridViewType >::value,
std::unique_ptr
< L2VolumeVectorFunctional
< FunctionType, SpaceType,
VectorType, GridViewType >
> >::type make_l2_volume_vector_functional (const FunctionType &function, const SpaceType &space, const GridViewType &grid_view, const size_t over_integrate=0)
template<class FunctionType , class VectorType , class SpaceType >
std::enable_if
< Stuff::is_localizable_function
< FunctionType >::value
&&Stuff::LA::is_vector
< VectorType >::value
&&is_space< SpaceType >::value,
std::unique_ptr
< L2VolumeVectorFunctional
< FunctionType, SpaceType,
VectorType > > >::type make_l2_volume_vector_functional (const FunctionType &function, VectorType &vector, const SpaceType &space, const size_t over_integrate=0)
template<class FunctionType , class VectorType , class SpaceType , class GridViewType >
std::enable_if
< Stuff::is_localizable_function
< FunctionType >::value
&&Stuff::LA::is_vector
< VectorType >::value
&&is_space< SpaceType >::value
&&Stuff::Grid::is_grid_layer
< GridViewType >::value,
std::unique_ptr
< L2VolumeVectorFunctional
< FunctionType, SpaceType,
VectorType, GridViewType >
> >::type make_l2_volume_vector_functional (const FunctionType &function, VectorType &vector, const SpaceType &space, const GridViewType &grid_view, const size_t over_integrate=0)
template<class VectorType , class FunctionType , class SpaceType >
std::enable_if
< Stuff::LA::is_vector
< VectorType >::value
&&Stuff::is_localizable_function
< FunctionType >::value
&&is_space< SpaceType >::value,
std::unique_ptr
< L2FaceVectorFunctional
< FunctionType, SpaceType,
VectorType > > >::type make_l2_face_vector_functional (const FunctionType &function, const SpaceType &space, const size_t over_integrate=0)
template<class VectorType , class FunctionType , class SpaceType >
std::enable_if
< Stuff::LA::is_vector
< VectorType >::value
&&Stuff::is_localizable_function
< FunctionType >::value
&&is_space< SpaceType >::value,
std::unique_ptr
< L2FaceVectorFunctional
< FunctionType, SpaceType,
VectorType > > >::type make_l2_face_vector_functional (const FunctionType &function, const SpaceType &space, const Stuff::Grid::ApplyOn::WhichIntersection< typename SpaceType::GridViewType > *where)
template<class VectorType , class FunctionType , class SpaceType >
std::enable_if
< Stuff::LA::is_vector
< VectorType >::value
&&Stuff::is_localizable_function
< FunctionType >::value
&&is_space< SpaceType >::value,
std::unique_ptr
< L2FaceVectorFunctional
< FunctionType, SpaceType,
VectorType > > >::type make_l2_face_vector_functional (const FunctionType &function, const SpaceType &space, const size_t over_integrate, const Stuff::Grid::ApplyOn::WhichIntersection< typename SpaceType::GridViewType > *where)
template<class VectorType , class FunctionType , class SpaceType , class GridViewType >
std::enable_if
< Stuff::LA::is_vector
< VectorType >::value
&&Stuff::is_localizable_function
< FunctionType >::value
&&is_space< SpaceType >::value
&&Stuff::Grid::is_grid_layer
< GridViewType >::value,
std::unique_ptr
< L2FaceVectorFunctional
< FunctionType, SpaceType,
VectorType, GridViewType >
> >::type make_l2_face_vector_functional (const FunctionType &function, const SpaceType &space, const GridViewType &grid_view, const size_t over_integrate=0)
template<class VectorType , class FunctionType , class SpaceType , class GridViewType >
std::enable_if
< Stuff::LA::is_vector
< VectorType >::value
&&Stuff::is_localizable_function
< FunctionType >::value
&&is_space< SpaceType >::value
&&Stuff::Grid::is_grid_layer
< GridViewType >::value,
std::unique_ptr
< L2FaceVectorFunctional
< FunctionType, SpaceType,
VectorType, GridViewType >
> >::type make_l2_face_vector_functional (const FunctionType &function, const SpaceType &space, const GridViewType &grid_view, const Stuff::Grid::ApplyOn::WhichIntersection< typename SpaceType::GridViewType > *where)
template<class VectorType , class FunctionType , class SpaceType , class GridViewType >
std::enable_if
< Stuff::LA::is_vector
< VectorType >::value
&&Stuff::is_localizable_function
< FunctionType >::value
&&is_space< SpaceType >::value
&&Stuff::Grid::is_grid_layer
< GridViewType >::value,
std::unique_ptr
< L2FaceVectorFunctional
< FunctionType, SpaceType,
VectorType, GridViewType >
> >::type make_l2_face_vector_functional (const FunctionType &function, const SpaceType &space, const GridViewType &grid_view, const size_t over_integrate, const Stuff::Grid::ApplyOn::WhichIntersection< typename SpaceType::GridViewType > *where)
template<class FunctionType , class VectorType , class SpaceType >
std::enable_if
< Stuff::is_localizable_function
< FunctionType >::value
&&Stuff::LA::is_vector
< VectorType >::value
&&is_space< SpaceType >::value,
std::unique_ptr
< L2FaceVectorFunctional
< FunctionType, SpaceType,
VectorType > > >::type make_l2_face_vector_functional (const FunctionType &function, VectorType &vector, const SpaceType &space, const size_t over_integrate=0)
template<class FunctionType , class VectorType , class SpaceType >
std::enable_if
< Stuff::is_localizable_function
< FunctionType >::value
&&Stuff::LA::is_vector
< VectorType >::value
&&is_space< SpaceType >::value,
std::unique_ptr
< L2FaceVectorFunctional
< FunctionType, SpaceType,
VectorType > > >::type make_l2_face_vector_functional (const FunctionType &function, VectorType &vector, const SpaceType &space, const Stuff::Grid::ApplyOn::WhichIntersection< typename SpaceType::GridViewType > *where)
template<class FunctionType , class VectorType , class SpaceType >
std::enable_if
< Stuff::is_localizable_function
< FunctionType >::value
&&Stuff::LA::is_vector
< VectorType >::value
&&is_space< SpaceType >::value,
std::unique_ptr
< L2FaceVectorFunctional
< FunctionType, SpaceType,
VectorType > > >::type make_l2_face_vector_functional (const FunctionType &function, VectorType &vector, const SpaceType &space, const size_t over_integrate, const Stuff::Grid::ApplyOn::WhichIntersection< typename SpaceType::GridViewType > *where)
template<class FunctionType , class VectorType , class SpaceType , class GridViewType >
std::enable_if
< Stuff::is_localizable_function
< FunctionType >::value
&&Stuff::LA::is_vector
< VectorType >::value
&&is_space< SpaceType >::value
&&Stuff::Grid::is_grid_layer
< GridViewType >::value,
std::unique_ptr
< L2FaceVectorFunctional
< FunctionType, SpaceType,
VectorType, GridViewType >
> >::type make_l2_face_vector_functional (const FunctionType &function, VectorType &vector, const SpaceType &space, const GridViewType &grid_view, const size_t over_integrate=0)
template<class FunctionType , class VectorType , class SpaceType , class GridViewType >
std::enable_if
< Stuff::is_localizable_function
< FunctionType >::value
&&Stuff::LA::is_vector
< VectorType >::value
&&is_space< SpaceType >::value
&&Stuff::Grid::is_grid_layer
< GridViewType >::value,
std::unique_ptr
< L2FaceVectorFunctional
< FunctionType, SpaceType,
VectorType, GridViewType >
> >::type make_l2_face_vector_functional (const FunctionType &function, VectorType &vector, const SpaceType &space, const GridViewType &grid_view, const Stuff::Grid::ApplyOn::WhichIntersection< typename SpaceType::GridViewType > *where)
template<class FunctionType , class VectorType , class SpaceType , class GridViewType >
std::enable_if
< Stuff::is_localizable_function
< FunctionType >::value
&&Stuff::LA::is_vector
< VectorType >::value
&&is_space< SpaceType >::value
&&Stuff::Grid::is_grid_layer
< GridViewType >::value,
std::unique_ptr
< L2FaceVectorFunctional
< FunctionType, SpaceType,
VectorType, GridViewType >
> >::type make_l2_face_vector_functional (const FunctionType &function, VectorType &vector, const SpaceType &space, const GridViewType &grid_view, const size_t over_integrate, const Stuff::Grid::ApplyOn::WhichIntersection< typename SpaceType::GridViewType > *where)
template<class V >
std::ostream & operator<< (std::ostream &out, const ConstLocalDoFVector< V > &vector)
template<class G , class F >
std::unique_ptr< DarcyOperator
< G, F > > make_darcy (const G &grid_view, const F &function)
template<class MatrixType , class DiffusionFactorType , class DiffusionTensorType , class SpaceType >
std::enable_if
< Stuff::LA::is_matrix
< MatrixType >::value
&&Stuff::is_localizable_function
< DiffusionFactorType >::value
&&Stuff::is_localizable_function
< DiffusionTensorType >::value
&&is_space< SpaceType >::value,
std::unique_ptr
< EllipticIpdgMatrixOperator
< DiffusionFactorType,
DiffusionTensorType, SpaceType,
LocalEllipticIpdgIntegrands::default_method,
MatrixType > > >::type make_elliptic_ipdg_matrix_operator (const DiffusionFactorType &diffusion_factor, const DiffusionTensorType &diffusion_tensor, const Stuff::Grid::BoundaryInfoInterface< typename SpaceType::GridViewType::Intersection > &boundary_info, const SpaceType &space, const size_t over_integrate=0)
Creates an elliptic matrix IPDG operator (MatrixType has to be supllied, a matrix is created automatically, default IPDG method is used, source and range space are given by space, grid_view of the space is used).
template<class MatrixType , LocalEllipticIpdgIntegrands::Method method, class DiffusionFactorType , class DiffusionTensorType , class SpaceType >
std::enable_if
< Stuff::LA::is_matrix
< MatrixType >::value
&&Stuff::is_localizable_function
< DiffusionFactorType >::value
&&Stuff::is_localizable_function
< DiffusionTensorType >::value
&&is_space< SpaceType >::value,
std::unique_ptr
< EllipticIpdgMatrixOperator
< DiffusionFactorType,
DiffusionTensorType, SpaceType,
method, MatrixType > > >::type make_elliptic_ipdg_matrix_operator (const DiffusionFactorType &diffusion_factor, const DiffusionTensorType &diffusion_tensor, const Stuff::Grid::BoundaryInfoInterface< typename SpaceType::GridViewType::Intersection > &boundary_info, const SpaceType &space, const size_t over_integrate=0)
Creates an elliptic matrix IPDG operator (MatrixType has to be supllied, a matrix is created automatically, IPDG method has to be supplied, source and range space are given by space, grid_view of the space is used).
template<class MatrixType , class DiffusionFactorType , class DiffusionTensorType , class SpaceType , class GridViewType >
std::enable_if
< Stuff::LA::is_matrix
< MatrixType >::value
&&Stuff::is_localizable_function
< DiffusionFactorType >::value
&&Stuff::is_localizable_function
< DiffusionTensorType >::value
&&is_space< SpaceType >::value
&&Stuff::Grid::is_grid_layer
< GridViewType >::value,
std::unique_ptr
< EllipticIpdgMatrixOperator
< DiffusionFactorType,
DiffusionTensorType, SpaceType,
LocalEllipticIpdgIntegrands::default_method,
MatrixType, GridViewType >
> >::type make_elliptic_ipdg_matrix_operator (const DiffusionFactorType &diffusion_factor, const DiffusionTensorType &diffusion_tensor, const Stuff::Grid::BoundaryInfoInterface< typename GridViewType::Intersection > &boundary_info, const SpaceType &space, const GridViewType &grid_view, const size_t over_integrate=0)
Creates an elliptic matrix IPDG operator (MatrixType has to be supllied, a matrix is created automatically, default IPDG method is used, source and range space are given by space).
template<class MatrixType , LocalEllipticIpdgIntegrands::Method method, class DiffusionFactorType , class DiffusionTensorType , class SpaceType , class GridViewType >
std::enable_if
< Stuff::LA::is_matrix
< MatrixType >::value
&&Stuff::is_localizable_function
< DiffusionFactorType >::value
&&Stuff::is_localizable_function
< DiffusionTensorType >::value
&&is_space< SpaceType >::value
&&Stuff::Grid::is_grid_layer
< GridViewType >::value,
std::unique_ptr
< EllipticIpdgMatrixOperator
< DiffusionFactorType,
DiffusionTensorType, SpaceType,
method, MatrixType,
GridViewType > > >::type make_elliptic_ipdg_matrix_operator (const DiffusionFactorType &diffusion_factor, const DiffusionTensorType &diffusion_tensor, const Stuff::Grid::BoundaryInfoInterface< typename GridViewType::Intersection > &boundary_info, const SpaceType &space, const GridViewType &grid_view, const size_t over_integrate=0)
Creates an elliptic matrix IPDG operator (MatrixType has to be supllied, a matrix is created automatically, IPDG method has to be supplied, source and range space are given by space).
template<class MatrixType , class DiffusionFactorType , class DiffusionTensorType , class RangeSpaceType , class SourceSpaceType , class GridViewType >
std::enable_if
< Stuff::LA::is_matrix
< MatrixType >::value
&&Stuff::is_localizable_function
< DiffusionFactorType >::value
&&Stuff::is_localizable_function
< DiffusionTensorType >::value
&&is_space< RangeSpaceType >
::value &&is_space
< SourceSpaceType >::value
&&Stuff::Grid::is_grid_layer
< GridViewType >::value,
std::unique_ptr
< EllipticIpdgMatrixOperator
< DiffusionFactorType,
DiffusionTensorType,
RangeSpaceType,
LocalEllipticIpdgIntegrands::default_method,
MatrixType, GridViewType,
SourceSpaceType > > >::type make_elliptic_ipdg_matrix_operator (const DiffusionFactorType &diffusion_factor, const DiffusionTensorType &diffusion_tensor, const Stuff::Grid::BoundaryInfoInterface< typename GridViewType::Intersection > &boundary_info, const RangeSpaceType &range_space, const SourceSpaceType &source_space, const GridViewType &grid_view, const size_t over_integrate=0)
Creates an elliptic matrix IPDG operator (MatrixType has to be supllied, a matrix is created automatically, default IPDG method is used).
template<class MatrixType , LocalEllipticIpdgIntegrands::Method method, class DiffusionFactorType , class DiffusionTensorType , class RangeSpaceType , class SourceSpaceType , class GridViewType >
std::enable_if
< Stuff::LA::is_matrix
< MatrixType >::value
&&Stuff::is_localizable_function
< DiffusionFactorType >::value
&&Stuff::is_localizable_function
< DiffusionTensorType >::value
&&is_space< RangeSpaceType >
::value &&is_space
< SourceSpaceType >::value
&&Stuff::Grid::is_grid_layer
< GridViewType >::value,
std::unique_ptr
< EllipticIpdgMatrixOperator
< DiffusionFactorType,
DiffusionTensorType,
RangeSpaceType, method,
MatrixType, GridViewType,
SourceSpaceType > > >::type make_elliptic_ipdg_matrix_operator (const DiffusionFactorType &diffusion_factor, const DiffusionTensorType &diffusion_tensor, const Stuff::Grid::BoundaryInfoInterface< typename GridViewType::Intersection > &boundary_info, const RangeSpaceType &range_space, const SourceSpaceType &source_space, const GridViewType &grid_view, const size_t over_integrate=0)
Creates an elliptic matrix IPDG operator (MatrixType has to be supllied, a matrix is created automatically, IPDG method has to be supplied).
template<class DiffusionFactorType , class DiffusionTensorType , class MatrixType , class SpaceType >
std::enable_if
< Stuff::is_localizable_function
< DiffusionFactorType >::value
&&Stuff::is_localizable_function
< DiffusionTensorType >::value
&&Stuff::LA::is_matrix
< MatrixType >::value
&&is_space< SpaceType >::value,
std::unique_ptr
< EllipticIpdgMatrixOperator
< DiffusionFactorType,
DiffusionTensorType, SpaceType,
LocalEllipticIpdgIntegrands::default_method,
MatrixType > > >::type make_elliptic_ipdg_matrix_operator (const DiffusionFactorType &diffusion_factor, const DiffusionTensorType &diffusion_tensor, const Stuff::Grid::BoundaryInfoInterface< typename SpaceType::GridViewType::Intersection > &boundary_info, MatrixType &matrix, const SpaceType &space, const size_t over_integrate=0)
Creates an elliptic matrix IPDG operator (default IPDG method is used, source and range space are given by space, grid_view of the space is used).
template<LocalEllipticIpdgIntegrands::Method method, class DiffusionFactorType , class DiffusionTensorType , class MatrixType , class SpaceType >
std::enable_if
< Stuff::is_localizable_function
< DiffusionFactorType >::value
&&Stuff::is_localizable_function
< DiffusionTensorType >::value
&&Stuff::LA::is_matrix
< MatrixType >::value
&&is_space< SpaceType >::value,
std::unique_ptr
< EllipticIpdgMatrixOperator
< DiffusionFactorType,
DiffusionTensorType, SpaceType,
method, MatrixType > > >::type make_elliptic_ipdg_matrix_operator (const DiffusionFactorType &diffusion_factor, const DiffusionTensorType &diffusion_tensor, const Stuff::Grid::BoundaryInfoInterface< typename SpaceType::GridViewType::Intersection > &boundary_info, MatrixType &matrix, const SpaceType &space, const size_t over_integrate=0)
Creates an elliptic matrix IPDG operator (IPDG method has to be supplied, source and range space are given by space, grid_view of the space is used).
template<class DiffusionFactorType , class DiffusionTensorType , class MatrixType , class SpaceType , class GridViewType >
std::enable_if
< Stuff::is_localizable_function
< DiffusionFactorType >::value
&&Stuff::is_localizable_function
< DiffusionTensorType >::value
&&Stuff::LA::is_matrix
< MatrixType >::value
&&is_space< SpaceType >::value
&&Stuff::Grid::is_grid_layer
< GridViewType >::value,
std::unique_ptr
< EllipticIpdgMatrixOperator
< DiffusionFactorType,
DiffusionTensorType, SpaceType,
LocalEllipticIpdgIntegrands::default_method,
MatrixType, GridViewType >
> >::type make_elliptic_ipdg_matrix_operator (const DiffusionFactorType &diffusion_factor, const DiffusionTensorType &diffusion_tensor, const Stuff::Grid::BoundaryInfoInterface< typename GridViewType::Intersection > &boundary_info, MatrixType &matrix, const SpaceType &space, const GridViewType &grid_view, const size_t over_integrate=0)
Creates an elliptic matrix IPDG operator (default IPDG method is used, source and range space are given by space).
template<LocalEllipticIpdgIntegrands::Method method, class DiffusionFactorType , class DiffusionTensorType , class MatrixType , class SpaceType , class GridViewType >
std::enable_if
< Stuff::is_localizable_function
< DiffusionFactorType >::value
&&Stuff::is_localizable_function
< DiffusionTensorType >::value
&&Stuff::LA::is_matrix
< MatrixType >::value
&&is_space< SpaceType >::value
&&Stuff::Grid::is_grid_layer
< GridViewType >::value,
std::unique_ptr
< EllipticIpdgMatrixOperator
< DiffusionFactorType,
DiffusionTensorType, SpaceType,
method, MatrixType,
GridViewType > > >::type make_elliptic_ipdg_matrix_operator (const DiffusionFactorType &diffusion_factor, const DiffusionTensorType &diffusion_tensor, const Stuff::Grid::BoundaryInfoInterface< typename GridViewType::Intersection > &boundary_info, MatrixType &matrix, const SpaceType &space, const GridViewType &grid_view, const size_t over_integrate=0)
Creates an elliptic matrix IPDG operator (IPDG method has to be supplied, source and range space are given by space).
template<class DiffusionFactorType , class DiffusionTensorType , class MatrixType , class RangeSpaceType , class SourceSpaceType , class GridViewType >
std::enable_if
< Stuff::is_localizable_function
< DiffusionFactorType >::value
&&Stuff::is_localizable_function
< DiffusionTensorType >::value
&&Stuff::LA::is_matrix
< MatrixType >::value
&&is_space< RangeSpaceType >
::value &&is_space
< SourceSpaceType >::value
&&Stuff::Grid::is_grid_layer
< GridViewType >::value,
std::unique_ptr
< EllipticIpdgMatrixOperator
< DiffusionFactorType,
DiffusionTensorType,
RangeSpaceType,
LocalEllipticIpdgIntegrands::default_method,
MatrixType, GridViewType,
SourceSpaceType > > >::type make_elliptic_ipdg_matrix_operator (const DiffusionFactorType &diffusion_factor, const DiffusionTensorType &diffusion_tensor, const Stuff::Grid::BoundaryInfoInterface< typename GridViewType::Intersection > &boundary_info, MatrixType &matrix, const RangeSpaceType &range_space, const SourceSpaceType &source_space, const GridViewType &grid_view, const size_t over_integrate=0)
Creates an elliptic matrix IPDG operator (default IPDG method is used).
template<LocalEllipticIpdgIntegrands::Method method, class DiffusionFactorType , class DiffusionTensorType , class MatrixType , class RangeSpaceType , class SourceSpaceType , class GridViewType >
std::enable_if
< Stuff::is_localizable_function
< DiffusionFactorType >::value
&&Stuff::is_localizable_function
< DiffusionTensorType >::value
&&Stuff::LA::is_matrix
< MatrixType >::value
&&is_space< RangeSpaceType >
::value &&is_space
< SourceSpaceType >::value
&&Stuff::Grid::is_grid_layer
< GridViewType >::value,
std::unique_ptr
< EllipticIpdgMatrixOperator
< DiffusionFactorType,
DiffusionTensorType,
RangeSpaceType, method,
MatrixType, GridViewType,
SourceSpaceType > > >::type make_elliptic_ipdg_matrix_operator (const DiffusionFactorType &diffusion_factor, const DiffusionTensorType &diffusion_tensor, const Stuff::Grid::BoundaryInfoInterface< typename GridViewType::Intersection > &boundary_info, MatrixType &matrix, const RangeSpaceType &range_space, const SourceSpaceType &source_space, const GridViewType &grid_view, const size_t over_integrate=0)
Creates an elliptic matrix IPDG operator (IPDG method has to be supplied).
template<class DiffusionType , class GridViewType , class RangeType , class SourceType >
std::enable_if
< Stuff::is_localizable_function
< DiffusionType >::value
&&Stuff::Grid::is_grid_layer
< GridViewType >::value
&&Stuff::is_localizable_function
< RangeType >::value
&&Stuff::is_localizable_function
< SourceType >::value,
std::unique_ptr
< EllipticLocalizableProduct
< DiffusionType, void,
GridViewType, RangeType,
SourceType > > >::type make_elliptic_localizable_product (const DiffusionType &diffusion, const GridViewType &grid_view, const RangeType &range, const SourceType &source, const size_t over_integrate=0)
template<class DiffusionFactorType , class DiffusionTensorType , class GridViewType , class RangeType , class SourceType >
std::enable_if
< Stuff::is_localizable_function
< DiffusionFactorType >::value
&&Stuff::is_localizable_function
< DiffusionTensorType >::value
&&Stuff::Grid::is_grid_layer
< GridViewType >::value
&&Stuff::is_localizable_function
< RangeType >::value
&&Stuff::is_localizable_function
< SourceType >::value,
std::unique_ptr
< EllipticLocalizableProduct
< DiffusionFactorType,
DiffusionTensorType,
GridViewType, RangeType,
SourceType > > >::type make_elliptic_localizable_product (const DiffusionFactorType &diffusion_factor, const DiffusionTensorType &diffusion_tensor, const GridViewType &grid_view, const RangeType &range, const SourceType &source, const size_t over_integrate=0)
template<class MatrixType , class DiffusionFactorType , class DiffusionTensorType , class SpaceType >
std::enable_if
< Stuff::LA::is_matrix
< MatrixType >::value
&&Stuff::is_localizable_function
< DiffusionFactorType >::value
&&Stuff::is_localizable_function
< DiffusionTensorType >::value
&&is_space< SpaceType >::value,
std::unique_ptr
< EllipticMatrixOperator
< DiffusionFactorType,
DiffusionTensorType, SpaceType,
MatrixType > > >::type make_elliptic_matrix_operator (const DiffusionFactorType &diffusion_factor, const DiffusionTensorType &diffusion_tensor, const SpaceType &space, const size_t over_integrate=0)
Creates an elliptic matrix operator (MatrixType has to be supllied, a matrix is created automatically, source and range space are given by space, grid_view of the space is used).
template<class MatrixType , class DiffusionFactorType , class DiffusionTensorType , class SpaceType , class GridViewType >
std::enable_if
< Stuff::LA::is_matrix
< MatrixType >::value
&&Stuff::is_localizable_function
< DiffusionFactorType >::value
&&Stuff::is_localizable_function
< DiffusionTensorType >::value
&&is_space< SpaceType >::value
&&Stuff::Grid::is_grid_layer
< GridViewType >::value,
std::unique_ptr
< EllipticMatrixOperator
< DiffusionFactorType,
DiffusionTensorType, SpaceType,
MatrixType, GridViewType >
> >::type make_elliptic_matrix_operator (const DiffusionFactorType &diffusion_factor, const DiffusionTensorType &diffusion_tensor, const SpaceType &space, const GridViewType &grid_view, const size_t over_integrate=0)
Creates an elliptic matrix operator (MatrixType has to be supllied, a matrix is created automatically, source and range space are given by space).
template<class MatrixType , class DiffusionFactorType , class DiffusionTensorType , class RangeSpaceType , class SourceSpaceType , class GridViewType >
std::enable_if
< Stuff::LA::is_matrix
< MatrixType >::value
&&Stuff::is_localizable_function
< DiffusionFactorType >::value
&&Stuff::is_localizable_function
< DiffusionTensorType >::value
&&is_space< RangeSpaceType >
::value &&is_space
< SourceSpaceType >::value
&&Stuff::Grid::is_grid_layer
< GridViewType >::value,
std::unique_ptr
< EllipticMatrixOperator
< DiffusionFactorType,
DiffusionTensorType,
RangeSpaceType, MatrixType,
GridViewType, SourceSpaceType >
> >::type make_elliptic_matrix_operator (const DiffusionFactorType &diffusion_factor, const DiffusionTensorType &diffusion_tensor, const RangeSpaceType &range_space, const SourceSpaceType &source_space, const GridViewType &grid_view, const size_t over_integrate=0)
Creates an elliptic matrix operator (MatrixType has to be supllied, a matrix is created automatically).
template<class DiffusionFactorType , class DiffusionTensorType , class MatrixType , class SpaceType >
std::enable_if
< Stuff::is_localizable_function
< DiffusionFactorType >::value
&&Stuff::is_localizable_function
< DiffusionTensorType >::value
&&Stuff::LA::is_matrix
< MatrixType >::value
&&is_space< SpaceType >::value,
std::unique_ptr
< EllipticMatrixOperator
< DiffusionFactorType,
DiffusionTensorType, SpaceType,
MatrixType > > >::type make_elliptic_matrix_operator (const DiffusionFactorType &diffusion_factor, const DiffusionTensorType &diffusion_tensor, MatrixType &matrix, const SpaceType &space, const size_t over_integrate=0)
Creates an elliptic matrix operator (source and range space are given by space, grid_view of the space is used).
template<class DiffusionFactorType , class DiffusionTensorType , class MatrixType , class SpaceType , class GridViewType >
std::enable_if
< Stuff::is_localizable_function
< DiffusionFactorType >::value
&&Stuff::is_localizable_function
< DiffusionTensorType >::value
&&Stuff::LA::is_matrix
< MatrixType >::value
&&is_space< SpaceType >::value
&&Stuff::Grid::is_grid_layer
< GridViewType >::value,
std::unique_ptr
< EllipticMatrixOperator
< DiffusionFactorType,
DiffusionTensorType, SpaceType,
MatrixType, GridViewType >
> >::type make_elliptic_matrix_operator (const DiffusionFactorType &diffusion_factor, const DiffusionTensorType &diffusion_tensor, MatrixType &matrix, const SpaceType &space, const GridViewType &grid_view, const size_t over_integrate=0)
Creates an elliptic matrix operator (source and range space are given by space).
template<class DiffusionFactorType , class DiffusionTensorType , class MatrixType , class RangeSpaceType , class SourceSpaceType , class GridViewType >
std::enable_if
< Stuff::is_localizable_function
< DiffusionFactorType >::value
&&Stuff::is_localizable_function
< DiffusionTensorType >::value
&&Stuff::LA::is_matrix
< MatrixType >::value
&&is_space< RangeSpaceType >
::value &&is_space
< SourceSpaceType >::value
&&Stuff::Grid::is_grid_layer
< GridViewType >::value,
std::unique_ptr
< EllipticMatrixOperator
< DiffusionFactorType,
DiffusionTensorType,
RangeSpaceType, MatrixType,
GridViewType, SourceSpaceType >
> >::type make_elliptic_matrix_operator (const DiffusionFactorType &diffusion_factor, const DiffusionTensorType &diffusion_tensor, MatrixType &matrix, const RangeSpaceType &range_space, const SourceSpaceType &source_space, const GridViewType &grid_view, const size_t over_integrate=0)
Creates an elliptic matrix operator.
template<class MatrixType , class DiffusionType , class SpaceType >
std::enable_if
< Stuff::LA::is_matrix
< MatrixType >::value
&&Stuff::is_localizable_function
< DiffusionType >::value
&&is_space< SpaceType >::value,
std::unique_ptr
< EllipticMatrixOperator
< DiffusionType, void,
SpaceType, MatrixType >
> >::type make_elliptic_matrix_operator (const DiffusionType &diffusion, const SpaceType &space, const size_t over_integrate=0)
Creates an elliptic matrix operator (single diffusion given, MatrixType has to be supllied, a matrix is created automatically, source and range space are given by space, grid_view of the space is used).
template<class MatrixType , class DiffusionType , class SpaceType , class GridViewType >
std::enable_if
< Stuff::LA::is_matrix
< MatrixType >::value
&&Stuff::is_localizable_function
< DiffusionType >::value
&&is_space< SpaceType >::value
&&Stuff::Grid::is_grid_layer
< GridViewType >::value,
std::unique_ptr
< EllipticMatrixOperator
< DiffusionType, void,
SpaceType, MatrixType,
GridViewType > > >::type make_elliptic_matrix_operator (const DiffusionType &diffusion, const SpaceType &space, const GridViewType &grid_view, const size_t over_integrate=0)
Creates an elliptic matrix operator (single diffusion given, MatrixType has to be supllied, a matrix is created automatically, source and range space are given by space).
template<class MatrixType , class DiffusionType , class RangeSpaceType , class SourceSpaceType , class GridViewType >
std::enable_if
< Stuff::LA::is_matrix
< MatrixType >::value
&&Stuff::is_localizable_function
< DiffusionType >::value
&&is_space< RangeSpaceType >
::value &&is_space
< SourceSpaceType >::value
&&Stuff::Grid::is_grid_layer
< GridViewType >::value,
std::unique_ptr
< EllipticMatrixOperator
< DiffusionType, void,
RangeSpaceType, MatrixType,
GridViewType, SourceSpaceType >
> >::type make_elliptic_matrix_operator (const DiffusionType &diffusion, const RangeSpaceType &range_space, const SourceSpaceType &source_space, const GridViewType &grid_view, const size_t over_integrate=0)
Creates an elliptic matrix operator (single diffusion given, MatrixType has to be supllied, a matrix is created automatically).
template<class DiffusionType , class MatrixType , class SpaceType >
std::enable_if
< Stuff::is_localizable_function
< DiffusionType >::value
&&Stuff::LA::is_matrix
< MatrixType >::value
&&is_space< SpaceType >::value,
std::unique_ptr
< EllipticMatrixOperator
< DiffusionType, void,
SpaceType, MatrixType >
> >::type make_elliptic_matrix_operator (const DiffusionType &diffusion, MatrixType &matrix, const SpaceType &space, const size_t over_integrate=0)
Creates an elliptic matrix operator (single diffusion given, source and range space are given by space, grid_view of the space is used).
template<class DiffusionType , class MatrixType , class SpaceType , class GridViewType >
std::enable_if
< Stuff::is_localizable_function
< DiffusionType >::value
&&Stuff::LA::is_matrix
< MatrixType >::value
&&is_space< SpaceType >::value
&&Stuff::Grid::is_grid_layer
< GridViewType >::value,
std::unique_ptr
< EllipticMatrixOperator
< DiffusionType, void,
SpaceType, MatrixType,
GridViewType > > >::type make_elliptic_matrix_operator (const DiffusionType &diffusion, MatrixType &matrix, const SpaceType &space, const GridViewType &grid_view, const size_t over_integrate=0)
Creates an elliptic matrix operator (single diffusion given, source and range space are given by space).
template<class DiffusionType , class MatrixType , class RangeSpaceType , class SourceSpaceType , class GridViewType >
std::enable_if
< Stuff::is_localizable_function
< DiffusionType >::value
&&Stuff::LA::is_matrix
< MatrixType >::value
&&is_space< RangeSpaceType >
::value &&is_space
< SourceSpaceType >::value
&&Stuff::Grid::is_grid_layer
< GridViewType >::value,
std::unique_ptr
< EllipticMatrixOperator
< DiffusionType, void,
RangeSpaceType, MatrixType,
GridViewType, SourceSpaceType >
> >::type make_elliptic_matrix_operator (const DiffusionType &diffusion, MatrixType &matrix, const RangeSpaceType &range_space, const SourceSpaceType &source_space, const GridViewType &grid_view, const size_t over_integrate=0)
Creates an elliptic matrix operator (single diffusion given).
template<class GridViewType , class DiffusionType >
std::enable_if
< Stuff::Grid::is_grid_layer
< GridViewType >::value
&&Stuff::is_localizable_function
< DiffusionType >::value,
std::unique_ptr
< EllipticOperator
< DiffusionType, void,
GridViewType, typename
DiffusionType::RangeFieldType >
> >::type make_elliptic_operator (const GridViewType &grid_view, const DiffusionType &diffusion, const size_t over_integrate=0)
template<class GridViewType , class DiffusionFactorType , class DiffusionTensorType >
std::enable_if
< Stuff::Grid::is_grid_layer
< GridViewType >::value
&&Stuff::is_localizable_function
< DiffusionFactorType >::value
&&Stuff::is_localizable_function
< DiffusionTensorType >::value,
std::unique_ptr
< EllipticOperator
< DiffusionFactorType,
DiffusionTensorType,
GridViewType, typename
DiffusionFactorType::RangeFieldType >
> >::type make_elliptic_operator (const GridViewType &grid_view, const DiffusionFactorType &diffusion_factor, const DiffusionTensorType &diffusion_tensor, const size_t over_integrate=0)
template<class GV , class DF , class DT >
DiffusiveFluxReconstructionOperator
< GV, DF, DT > make_diffusive_flux_reconstruction_operator (const GV &grid_view, const DF &diffusion_factor, const DT &diffusion_tensor, const size_t over_integrate=0)
template<class GridViewType , class RangeType , class SourceType >
std::enable_if
< Stuff::Grid::is_grid_layer
< GridViewType >::value
&&Stuff::is_localizable_function
< RangeType >::value
&&Stuff::is_localizable_function
< SourceType >::value,
std::unique_ptr
< L2LocalizableProduct
< GridViewType, RangeType,
SourceType > > >::type make_l2_localizable_product (const GridViewType &grid_view, const RangeType &range, const SourceType &source, const size_t over_integrate=0)
template<class MatrixType , class SpaceType >
std::enable_if
< Stuff::LA::is_matrix
< MatrixType >::value
&&is_space< SpaceType >::value,
std::unique_ptr
< L2MatrixOperator< SpaceType,
MatrixType > > >::type make_l2_matrix_operator (const SpaceType &space, const size_t over_integrate=0)
Creates an L2 matrix operator (MatrixType has to be supllied, a matrix is created automatically, source and range space are given by space, grid_view of the space is used).
template<class MatrixType , class SpaceType , class GridViewType >
std::enable_if
< Stuff::LA::is_matrix
< MatrixType >::value
&&is_space< SpaceType >::value
&&Stuff::Grid::is_grid_layer
< GridViewType >::value,
std::unique_ptr
< L2MatrixOperator< SpaceType,
MatrixType, GridViewType >
> >::type make_l2_matrix_operator (const SpaceType &space, const GridViewType &grid_view, const size_t over_integrate=0)
Creates an L2 matrix operator (MatrixType has to be supllied, a matrix is created automatically, source and range space are given by space).
template<class MatrixType , class RangeSpaceType , class SourceSpaceType , class GridViewType >
std::enable_if
< Stuff::LA::is_matrix
< MatrixType >::value
&&is_space< RangeSpaceType >
::value &&is_space
< SourceSpaceType >::value
&&Stuff::Grid::is_grid_layer
< GridViewType >::value,
std::unique_ptr
< L2MatrixOperator
< RangeSpaceType, MatrixType,
GridViewType, SourceSpaceType >
> >::type make_l2_matrix_operator (const RangeSpaceType &range_space, const SourceSpaceType &source_space, const GridViewType &grid_view, const size_t over_integrate=0)
Creates an L2 matrix operator (MatrixType has to be supllied, a matrix is created automatically).
template<class MatrixType , class SpaceType >
std::enable_if
< Stuff::LA::is_matrix
< MatrixType >::value
&&is_space< SpaceType >::value,
std::unique_ptr
< L2MatrixOperator< SpaceType,
MatrixType > > >::type make_l2_matrix_operator (MatrixType &matrix, const SpaceType &space, const size_t over_integrate=0)
Creates an L2 matrix operator (source and range space are given by space, grid_view of the space is used).
template<class MatrixType , class SpaceType , class GridViewType >
std::enable_if
< Stuff::LA::is_matrix
< MatrixType >::value
&&is_space< SpaceType >::value
&&Stuff::Grid::is_grid_layer
< GridViewType >::value,
std::unique_ptr
< L2MatrixOperator< SpaceType,
MatrixType, GridViewType >
> >::type make_l2_matrix_operator (MatrixType &matrix, const SpaceType &space, const GridViewType &grid_view, const size_t over_integrate=0)
Creates an L2 matrix operator (source and range space are given by space).
template<class MatrixType , class RangeSpaceType , class SourceSpaceType , class GridViewType >
std::enable_if
< Stuff::LA::is_matrix
< MatrixType >::value
&&is_space< RangeSpaceType >
::value &&is_space
< SourceSpaceType >::value
&&Stuff::Grid::is_grid_layer
< GridViewType >::value,
std::unique_ptr
< L2MatrixOperator
< RangeSpaceType, MatrixType,
GridViewType, SourceSpaceType >
> >::type make_l2_matrix_operator (MatrixType &matrix, const RangeSpaceType &range_space, const SourceSpaceType &source_space, const GridViewType &grid_view, const size_t over_integrate=0)
Creates an L2 matrix operator.
template<class GridViewType >
std::enable_if
< Stuff::Grid::is_grid_layer
< GridViewType >::value,
std::unique_ptr< L2Operator
< GridViewType > > >::type make_l2_operator (const GridViewType &grid_view, const size_t over_integrate=0)
template<class GridViewType , class RangeType , class SourceType >
std::enable_if
< Stuff::Grid::is_grid_layer
< GridViewType >::value
&&Stuff::is_localizable_function
< RangeType >::value
&&Stuff::is_localizable_function
< SourceType >::value,
std::unique_ptr
< LaplaceLocalizableProduct
< GridViewType, RangeType,
SourceType > > >::type make_laplace_localizable_product (const GridViewType &grid_view, const RangeType &range, const SourceType &source, const size_t over_integrate=0)
template<class MatrixType , class SpaceType >
std::enable_if
< Stuff::LA::is_matrix
< MatrixType >::value
&&is_space< SpaceType >::value,
std::unique_ptr
< LaplaceMatrixOperator
< SpaceType, MatrixType >
> >::type make_laplace_matrix_operator (const SpaceType &space, const size_t over_integrate=0)
Creates a Laplace matrix operator (MatrixType has to be supllied, a matrix is created automatically, source and range space are given by space, grid_view of the space is used).
template<class MatrixType , class SpaceType , class GridViewType >
std::enable_if
< Stuff::LA::is_matrix
< MatrixType >::value
&&is_space< SpaceType >::value
&&Stuff::Grid::is_grid_layer
< GridViewType >::value,
std::unique_ptr
< LaplaceMatrixOperator
< SpaceType, MatrixType,
GridViewType > > >::type make_laplace_matrix_operator (const SpaceType &space, const GridViewType &grid_view, const size_t over_integrate=0)
Creates a Laplace matrix operator (MatrixType has to be supllied, a matrix is created automatically, source and range space are given by space).
template<class MatrixType , class RangeSpaceType , class SourceSpaceType , class GridViewType >
std::enable_if
< Stuff::LA::is_matrix
< MatrixType >::value
&&is_space< RangeSpaceType >
::value &&is_space
< SourceSpaceType >::value
&&Stuff::Grid::is_grid_layer
< GridViewType >::value,
std::unique_ptr
< LaplaceMatrixOperator
< RangeSpaceType, MatrixType,
GridViewType, SourceSpaceType >
> >::type make_laplace_matrix_operator (const RangeSpaceType &range_space, const SourceSpaceType &source_space, const GridViewType &grid_view, const size_t over_integrate=0)
Creates a Laplace matrix operator (MatrixType has to be supllied, a matrix is created automatically).
template<class MatrixType , class SpaceType >
std::enable_if
< Stuff::LA::is_matrix
< MatrixType >::value
&&is_space< SpaceType >::value,
std::unique_ptr
< LaplaceMatrixOperator
< SpaceType, MatrixType >
> >::type make_laplace_matrix_operator (MatrixType &matrix, const SpaceType &space, const size_t over_integrate=0)
Creates a Laplace matrix operator (source and range space are given by space, grid_view of the space is used).
template<class MatrixType , class SpaceType , class GridViewType >
std::enable_if
< Stuff::LA::is_matrix
< MatrixType >::value
&&is_space< SpaceType >::value
&&Stuff::Grid::is_grid_layer
< GridViewType >::value,
std::unique_ptr
< LaplaceMatrixOperator
< SpaceType, MatrixType,
GridViewType > > >::type make_laplace_matrix_operator (MatrixType &matrix, const SpaceType &space, const GridViewType &grid_view, const size_t over_integrate=0)
Creates a Laplace matrix operator (source and range space are given by space).
template<class MatrixType , class RangeSpaceType , class SourceSpaceType , class GridViewType >
std::enable_if
< Stuff::LA::is_matrix
< MatrixType >::value
&&is_space< RangeSpaceType >
::value &&is_space
< SourceSpaceType >::value
&&Stuff::Grid::is_grid_layer
< GridViewType >::value,
std::unique_ptr
< LaplaceMatrixOperator
< RangeSpaceType, MatrixType,
GridViewType, SourceSpaceType >
> >::type make_laplace_matrix_operator (MatrixType &matrix, const RangeSpaceType &range_space, const SourceSpaceType &source_space, const GridViewType &grid_view, const size_t over_integrate=0)
Creates a Laplace matrix operator.
template<class GridViewType >
std::enable_if
< Stuff::Grid::is_grid_layer
< GridViewType >::value,
std::unique_ptr
< LaplaceOperator
< GridViewType > > >::type make_laplace_operator (const GridViewType &grid_view, const size_t over_integrate=0)
template<class WeightFunctionType , class GridViewType , class RangeType , class SourceType >
std::enable_if
< Stuff::is_localizable_function
< WeightFunctionType >::value
&&Stuff::Grid::is_grid_layer
< GridViewType >::value
&&Stuff::is_localizable_function
< RangeType >::value
&&Stuff::is_localizable_function
< SourceType >::value,
std::unique_ptr
< WeightedL2LocalizableProduct
< WeightFunctionType,
GridViewType, RangeType,
SourceType > > >::type make_weighted_l2_localizable_product (const WeightFunctionType &weight, const GridViewType &grid_view, const RangeType &range, const SourceType &source, const size_t over_integrate=0)
template<class MatrixType , class WeightFunctionType , class SpaceType >
std::enable_if
< Stuff::LA::is_matrix
< MatrixType >::value
&&Stuff::is_localizable_function
< WeightFunctionType >::value
&&is_space< SpaceType >::value,
std::unique_ptr
< WeightedL2MatrixOperator
< WeightFunctionType,
SpaceType, MatrixType >
> >::type make_weighted_l2_matrix_operator (const WeightFunctionType &weight, const SpaceType &space, const size_t over_integrate=0)
Creates a weighted L2 matrix operator (MatrixType has to be supllied, a matrix is created automatically, source and range space are given by space, grid_view of the space is used).
template<class MatrixType , class WeightFunctionType , class SpaceType , class GridViewType >
std::enable_if
< Stuff::LA::is_matrix
< MatrixType >::value
&&Stuff::is_localizable_function
< WeightFunctionType >::value
&&is_space< SpaceType >::value
&&Stuff::Grid::is_grid_layer
< GridViewType >::value,
std::unique_ptr
< WeightedL2MatrixOperator
< WeightFunctionType,
SpaceType, MatrixType,
GridViewType > > >::type make_weighted_l2_matrix_operator (const WeightFunctionType &weight, const SpaceType &space, const GridViewType &grid_view, const size_t over_integrate=0)
Creates a weighted L2 matrix operator (MatrixType has to be supllied, a matrix is created automatically, source and range space are given by space).
template<class MatrixType , class WeightFunctionType , class RangeSpaceType , class SourceSpaceType , class GridViewType >
std::enable_if
< Stuff::LA::is_matrix
< MatrixType >::value
&&Stuff::is_localizable_function
< WeightFunctionType >::value
&&is_space< RangeSpaceType >
::value &&is_space
< SourceSpaceType >::value
&&Stuff::Grid::is_grid_layer
< GridViewType >::value,
std::unique_ptr
< WeightedL2MatrixOperator
< WeightFunctionType,
RangeSpaceType, MatrixType,
GridViewType, SourceSpaceType >
> >::type make_weighted_l2_matrix_operator (const WeightFunctionType &weight, const RangeSpaceType &range_space, const SourceSpaceType &source_space, const GridViewType &grid_view, const size_t over_integrate=0)
Creates a weighted L2 matrix operator (MatrixType has to be supllied, a matrix is created automatically).
template<class WeightFunctionType , class MatrixType , class SpaceType >
std::enable_if
< Stuff::is_localizable_function
< WeightFunctionType >::value
&&Stuff::LA::is_matrix
< MatrixType >::value
&&is_space< SpaceType >::value,
std::unique_ptr
< WeightedL2MatrixOperator
< WeightFunctionType,
SpaceType, MatrixType >
> >::type make_weighted_l2_matrix_operator (const WeightFunctionType &weight, MatrixType &matrix, const SpaceType &space, const size_t over_integrate=0)
Creates a weighted L2 matrix operator (source and range space are given by space, grid_view of the space is used).
template<class WeightFunctionType , class MatrixType , class SpaceType , class GridViewType >
std::enable_if
< Stuff::is_localizable_function
< WeightFunctionType >::value
&&Stuff::LA::is_matrix
< MatrixType >::value
&&is_space< SpaceType >::value
&&Stuff::Grid::is_grid_layer
< GridViewType >::value,
std::unique_ptr
< WeightedL2MatrixOperator
< WeightFunctionType,
SpaceType, MatrixType,
GridViewType > > >::type make_weighted_l2_matrix_operator (const WeightFunctionType &weight, MatrixType &matrix, const SpaceType &space, const GridViewType &grid_view, const size_t over_integrate=0)
Creates a weighted L2 matrix operator (source and range space are given by space).
template<class WeightFunctionType , class MatrixType , class RangeSpaceType , class SourceSpaceType , class GridViewType >
std::enable_if
< Stuff::is_localizable_function
< WeightFunctionType >::value
&&Stuff::LA::is_matrix
< MatrixType >::value
&&is_space< RangeSpaceType >
::value &&is_space
< SourceSpaceType >::value
&&Stuff::Grid::is_grid_layer
< GridViewType >::value,
std::unique_ptr
< WeightedL2MatrixOperator
< WeightFunctionType,
RangeSpaceType, MatrixType,
GridViewType, SourceSpaceType >
> >::type make_weighted_l2_matrix_operator (const WeightFunctionType &weight, MatrixType &matrix, const RangeSpaceType &range_space, const SourceSpaceType &source_space, const GridViewType &grid_view, const size_t over_integrate=0)
Creates a weighted L2 matrix operator.
template<class GridViewType , class WeightFunctionType >
std::enable_if
< Stuff::is_localizable_function
< WeightFunctionType >::value
&&Stuff::Grid::is_grid_layer
< GridViewType >::value,
std::unique_ptr
< WeightedL2Operator
< WeightFunctionType,
GridViewType, typename
WeightFunctionType::RangeFieldType >
> >::type make_weighted_l2_operator (const GridViewType &grid_view, const WeightFunctionType &weight, const size_t over_integrate=0)
template<class GridViewType , class SourceType , class RangeType >
std::unique_ptr
< DirichletProjectionLocalizableOperator
< GridViewType, SourceType,
RangeType > > make_localizable_dirichlet_projection_operator (const GridViewType &grid_view, const Stuff::Grid::BoundaryInfoInterface< typename Stuff::Grid::Intersection< GridViewType >::Type > &boundary_info, const SourceType &source, RangeType &range)
template<class GridViewType , class SourceType , class SpaceType , class VectorType >
std::enable_if
< Stuff::Grid::is_grid_layer
< GridViewType >::value
&&Stuff::is_localizable_function
< SourceType >::value
&&is_space< SpaceType >::value
&&Stuff::LA::is_vector
< VectorType >::value,
std::unique_ptr
< L2GlobalProjectionLocalizableOperator
< GridViewType, SourceType,
DiscreteFunction< SpaceType,
VectorType > > > >::type make_global_l2_projection_localizable_operator (const GridViewType &grid_view, const SourceType &source, DiscreteFunction< SpaceType, VectorType > &range, const size_t over_integrate=0)
template<class SourceType , class SpaceType , class VectorType >
std::enable_if
< Stuff::is_localizable_function
< SourceType >::value
&&is_space< SpaceType >::value
&&Stuff::LA::is_vector
< VectorType >::value,
std::unique_ptr
< L2GlobalProjectionLocalizableOperator
< typename
SpaceType::GridViewType,
SourceType, DiscreteFunction
< SpaceType, VectorType >
> > >::type make_global_l2_projection_localizable_operator (const SourceType &source, DiscreteFunction< SpaceType, VectorType > &range, const size_t over_integrate=0)
template<class GridViewType >
std::enable_if
< Stuff::Grid::is_grid_layer
< GridViewType >::value,
std::unique_ptr
< L2GlobalProjectionOperator
< GridViewType > > >::type make_global_l2_projection_operator (const GridViewType &grid_view, const size_t over_integrate=0)
template<class GridViewType , class SourceType , class SpaceType , class VectorType >
std::enable_if
< Stuff::Grid::is_grid_layer
< GridViewType >::value
&&Stuff::is_localizable_function
< SourceType >::value
&&is_space< SpaceType >::value
&&Stuff::LA::is_vector
< VectorType >::value,
std::unique_ptr
< L2LocalProjectionLocalizableOperator
< GridViewType, SourceType,
DiscreteFunction< SpaceType,
VectorType > > > >::type make_local_l2_projection_localizable_operator (const GridViewType &grid_view, const SourceType &source, DiscreteFunction< SpaceType, VectorType > &range, const size_t over_integrate=0)
template<class SourceType , class SpaceType , class VectorType >
std::enable_if
< Stuff::is_localizable_function
< SourceType >::value
&&is_space< SpaceType >::value
&&Stuff::LA::is_vector
< VectorType >::value,
std::unique_ptr
< L2LocalProjectionLocalizableOperator
< typename
SpaceType::GridViewType,
SourceType, DiscreteFunction
< SpaceType, VectorType >
> > >::type make_local_l2_projection_localizable_operator (const SourceType &source, DiscreteFunction< SpaceType, VectorType > &range, const size_t over_integrate=0)
template<class GridViewType >
std::enable_if
< Stuff::Grid::is_grid_layer
< GridViewType >::value,
std::unique_ptr
< L2LocalProjectionOperator
< GridViewType > > >::type make_local_l2_projection_operator (const GridViewType &grid_view, const size_t over_integrate=0)
template<class GridViewType , class SourceType , class SpaceType , class VectorType >
std::enable_if
< Stuff::Grid::is_grid_layer
< GridViewType >::value
&&Stuff::is_localizable_function
< SourceType >::value
&&is_space< SpaceType >::value
&&Stuff::LA::is_vector
< VectorType >::value,
std::unique_ptr
< L2ProjectionLocalizableOperator
< GridViewType, SourceType,
DiscreteFunction< SpaceType,
VectorType > > > >::type make_l2_projection_localizable_operator (const GridViewType &grid_view, const SourceType &source, DiscreteFunction< SpaceType, VectorType > &range, const size_t over_integrate=0)
template<class SourceType , class SpaceType , class VectorType >
std::enable_if
< Stuff::is_localizable_function
< SourceType >::value
&&is_space< SpaceType >::value
&&Stuff::LA::is_vector
< VectorType >::value,
std::unique_ptr
< L2ProjectionLocalizableOperator
< typename
SpaceType::GridViewType,
SourceType, DiscreteFunction
< SpaceType, VectorType >
> > >::type make_l2_projection_localizable_operator (const SourceType &source, DiscreteFunction< SpaceType, VectorType > &range, const size_t over_integrate=0)
template<class GridViewType >
std::enable_if
< Stuff::Grid::is_grid_layer
< GridViewType >::value,
std::unique_ptr
< L2ProjectionOperator
< GridViewType > > >::type make_l2_projection_operator (const GridViewType &grid_view, const size_t over_integrate=0)
template<class GridViewType , class SourceType , class SpaceType , class VectorType >
std::enable_if
< Stuff::Grid::is_grid_layer
< GridViewType >::value
&&Stuff::is_localizable_function
< SourceType >::value
&&is_space< SpaceType >::value
&&Stuff::LA::is_vector
< VectorType >::value, void >
::type project_l2 (const GridViewType &grid_view, const SourceType &source, DiscreteFunction< SpaceType, VectorType > &range, const size_t over_integrate=0)
template<class SourceType , class SpaceType , class VectorType >
std::enable_if
< Stuff::is_localizable_function
< SourceType >::value
&&is_space< SpaceType >::value
&&Stuff::LA::is_vector
< VectorType >::value, void >
::type project_l2 (const SourceType &source, DiscreteFunction< SpaceType, VectorType > &range, const size_t over_integrate=0)
template<class GridViewType , class SourceType , class SpaceType , class VectorType >
std::enable_if
< Stuff::Grid::is_grid_layer
< GridViewType >::value
&&Stuff::is_localizable_function
< SourceType >::value
&&is_space< SpaceType >::value
&&Stuff::LA::is_vector
< VectorType >::value,
std::unique_ptr
< LagrangeProjectionLocalizableOperator
< GridViewType, SourceType,
DiscreteFunction< SpaceType,
VectorType > > > >::type make_lagrange_projection_localizable_operator (const GridViewType &grid_view, const SourceType &source, DiscreteFunction< SpaceType, VectorType > &range)
template<class SourceType , class SpaceType , class VectorType >
std::enable_if
< Stuff::is_localizable_function
< SourceType >::value
&&is_space< SpaceType >::value
&&Stuff::LA::is_vector
< VectorType >::value,
std::unique_ptr
< LagrangeProjectionLocalizableOperator
< typename
SpaceType::GridViewType,
SourceType, DiscreteFunction
< SpaceType, VectorType >
> > >::type make_lagrange_projection_localizable_operator (const SourceType &source, DiscreteFunction< SpaceType, VectorType > &range)
template<class GridViewType >
std::enable_if
< Stuff::Grid::is_grid_layer
< GridViewType >::value,
std::unique_ptr
< LagrangeProjectionOperator
< GridViewType > > >::type make_lagrange_projection_operator (const GridViewType &grid_view)
template<class GridViewType , class SourceType , class SpaceType , class VectorType >
std::enable_if
< Stuff::Grid::is_grid_layer
< GridViewType >::value
&&Stuff::is_localizable_function
< SourceType >::value
&&is_space< SpaceType >::value
&&Stuff::LA::is_vector
< VectorType >::value, void >
::type project_lagrange (const GridViewType &grid_view, const SourceType &source, DiscreteFunction< SpaceType, VectorType > &range)
template<class SourceType , class SpaceType , class VectorType >
std::enable_if
< Stuff::is_localizable_function
< SourceType >::value
&&is_space< SpaceType >::value
&&Stuff::LA::is_vector
< VectorType >::value, void >
::type project_lagrange (const SourceType &source, DiscreteFunction< SpaceType, VectorType > &range)
template<class GridViewType , class SourceType , class SpaceType , class VectorType >
std::enable_if
< Stuff::Grid::is_grid_layer
< GridViewType >::value
&&Stuff::is_localizable_function
< SourceType >::value
&&is_cg_space< SpaceType >
::value &&Stuff::LA::is_vector
< VectorType >::value, void >
::type project (const GridViewType &grid_view, const SourceType &source, DiscreteFunction< SpaceType, VectorType > &range, const size_t=0)
template<class GridViewType , class SourceType , class SpaceType , class VectorType >
std::enable_if
< Stuff::Grid::is_grid_layer
< GridViewType >::value
&&Stuff::is_localizable_function
< SourceType >::value
&&!is_cg_space< SpaceType >
::value &&Stuff::LA::is_vector
< VectorType >::value, void >
::type project (const GridViewType &grid_view, const SourceType &source, DiscreteFunction< SpaceType, VectorType > &range, const size_t over_integrate=0)
template<class SourceType , class SpaceType , class VectorType >
std::enable_if
< Stuff::is_localizable_function
< SourceType >::value
&&is_cg_space< SpaceType >
::value &&Stuff::LA::is_vector
< VectorType >::value, void >
::type project (const SourceType &source, DiscreteFunction< SpaceType, VectorType > &range, const size_t=0)
template<class SourceType , class SpaceType , class VectorType >
std::enable_if
< Stuff::is_localizable_function
< SourceType >::value
&&!is_cg_space< SpaceType >
::value &&Stuff::LA::is_vector
< VectorType >::value, void >
::type project (const SourceType &source, DiscreteFunction< SpaceType, VectorType > &range, const size_t over_integrate=0)
template<class GridViewType , class SourceSpaceType , class SourceVectorType , class RangeSpaceType , class RangeVectorType >
std::enable_if
< Stuff::Grid::is_grid_layer
< GridViewType >::value
&&is_space< SourceSpaceType >
::value &&Stuff::LA::is_vector
< SourceVectorType >::value
&&is_space< RangeSpaceType >
::value &&Stuff::LA::is_vector
< RangeVectorType >::value,
std::unique_ptr
< L2GlobalProlongationLocalizableOperator
< GridViewType,
ConstDiscreteFunction
< SourceSpaceType,
SourceVectorType >
, DiscreteFunction
< RangeSpaceType,
RangeVectorType > > > >::type make_global_l2_prolongation_localizable_operator (const GridViewType &grid_view, const ConstDiscreteFunction< SourceSpaceType, SourceVectorType > &source, DiscreteFunction< RangeSpaceType, RangeVectorType > &range, const size_t over_integrate=0)
template<class SourceSpaceType , class SourceVectorType , class RangeSpaceType , class RangeVectorType >
std::enable_if< is_space
< SourceSpaceType >::value
&&Stuff::LA::is_vector
< SourceVectorType >::value
&&is_space< RangeSpaceType >
::value &&Stuff::LA::is_vector
< RangeVectorType >::value,
std::unique_ptr
< L2GlobalProlongationLocalizableOperator
< typename
RangeSpaceType::GridViewType,
ConstDiscreteFunction
< SourceSpaceType,
SourceVectorType >
, DiscreteFunction
< RangeSpaceType,
RangeVectorType > > > >::type make_global_l2_prolongation_localizable_operator (const ConstDiscreteFunction< SourceSpaceType, SourceVectorType > &source, DiscreteFunction< RangeSpaceType, RangeVectorType > &range, const size_t over_integrate=0)
template<class GridViewType >
std::enable_if
< Stuff::Grid::is_grid_layer
< GridViewType >::value,
std::unique_ptr
< L2GlobalProlongationOperator
< GridViewType > > >::type make_global_l2_prolongation_operator (const GridViewType &grid_view, const size_t over_integrate=0)
template<class GridViewType , class SourceSpaceType , class SourceVectorType , class RangeSpaceType , class RangeVectorType >
std::enable_if
< Stuff::Grid::is_grid_layer
< GridViewType >::value
&&is_space< SourceSpaceType >
::value &&Stuff::LA::is_vector
< SourceVectorType >::value
&&is_space< RangeSpaceType >
::value &&Stuff::LA::is_vector
< RangeVectorType >::value,
std::unique_ptr
< L2LocalProlongationLocalizableOperator
< GridViewType,
ConstDiscreteFunction
< SourceSpaceType,
SourceVectorType >
, DiscreteFunction
< RangeSpaceType,
RangeVectorType > > > >::type make_local_l2_prolongation_localizable_operator (const GridViewType &grid_view, const ConstDiscreteFunction< SourceSpaceType, SourceVectorType > &source, DiscreteFunction< RangeSpaceType, RangeVectorType > &range, const size_t over_integrate=0)
template<class SourceSpaceType , class SourceVectorType , class RangeSpaceType , class RangeVectorType >
std::enable_if< is_space
< SourceSpaceType >::value
&&Stuff::LA::is_vector
< SourceVectorType >::value
&&is_space< RangeSpaceType >
::value &&Stuff::LA::is_vector
< RangeVectorType >::value,
std::unique_ptr
< L2LocalProlongationLocalizableOperator
< typename
RangeSpaceType::GridViewType,
ConstDiscreteFunction
< SourceSpaceType,
SourceVectorType >
, DiscreteFunction
< RangeSpaceType,
RangeVectorType > > > >::type make_local_l2_prolongation_localizable_operator (const ConstDiscreteFunction< SourceSpaceType, SourceVectorType > &source, DiscreteFunction< RangeSpaceType, RangeVectorType > &range, const size_t over_integrate=0)
template<class GridViewType >
std::enable_if
< Stuff::Grid::is_grid_layer
< GridViewType >::value,
std::unique_ptr
< L2LocalProlongationOperator
< GridViewType > > >::type make_local_l2_prolongation_operator (const GridViewType &grid_view, const size_t over_integrate=0)
template<class GridViewType , class SS , class SV , class RS , class RV >
std::enable_if
< Stuff::Grid::is_grid_layer
< GridViewType >::value,
std::unique_ptr
< L2ProlongationLocalizableOperator
< GridViewType,
ConstDiscreteFunction< SS, SV >
, DiscreteFunction< RS, RV >
> > >::type make_l2_prolongation_localizable_operator (const GridViewType &grid_view, const ConstDiscreteFunction< SS, SV > &source, DiscreteFunction< RS, RV > &range, const size_t over_integrate=0)
template<class SS , class SV , class RS , class RV >
std::unique_ptr
< L2ProlongationLocalizableOperator
< typename RS::GridViewType,
ConstDiscreteFunction< SS, SV >
, DiscreteFunction< RS, RV > > > make_l2_prolongation_localizable_operator (const ConstDiscreteFunction< SS, SV > &source, DiscreteFunction< RS, RV > &range, const size_t over_integrate=0)
template<class GridViewType >
std::enable_if
< Stuff::Grid::is_grid_layer
< GridViewType >::value,
std::unique_ptr
< L2ProlongationOperator
< GridViewType > > >::type make_l2_prolongation_operator (const GridViewType &grid_view, const size_t over_integrate=0)
template<class GridViewType , class SS , class SV , class RS , class RV >
std::enable_if
< Stuff::Grid::is_grid_layer
< GridViewType >::value, void >
::type prolong_l2 (const GridViewType &grid_view, const ConstDiscreteFunction< SS, SV > &source, DiscreteFunction< RS, RV > &range, const size_t over_integrate=0)
template<class SS , class SV , class RS , class RV >
void prolong_l2 (const ConstDiscreteFunction< SS, SV > &source, DiscreteFunction< RS, RV > &range, const size_t over_integrate=0)
template<class GridViewType , class SourceSpaceType , class SourceVectorType , class RangeSpaceType , class RangeVectorType >
std::enable_if
< Stuff::Grid::is_grid_layer
< GridViewType >::value,
std::unique_ptr
< LagrangeProlongationLocalizableOperator
< GridViewType,
ConstDiscreteFunction
< SourceSpaceType,
SourceVectorType >
, DiscreteFunction
< RangeSpaceType,
RangeVectorType > > > >::type make_lagrange_prolongation_localizable_operator (const GridViewType &grid_view, const ConstDiscreteFunction< SourceSpaceType, SourceVectorType > &source, DiscreteFunction< RangeSpaceType, RangeVectorType > &range)
template<class SourceSpaceType , class SourceVectorType , class RangeSpaceType , class RangeVectorType >
std::unique_ptr
< LagrangeProlongationLocalizableOperator
< typename
RangeSpaceType::GridViewType,
ConstDiscreteFunction
< SourceSpaceType,
SourceVectorType >
, DiscreteFunction
< RangeSpaceType,
RangeVectorType > > > make_lagrange_prolongation_localizable_operator (const ConstDiscreteFunction< SourceSpaceType, SourceVectorType > &source, DiscreteFunction< RangeSpaceType, RangeVectorType > &range)
template<class GridViewType >
std::enable_if
< Stuff::Grid::is_grid_layer
< GridViewType >::value,
std::unique_ptr
< LagrangeProlongationOperator
< GridViewType > > >::type make_lagrange_prolongation_operator (const GridViewType &grid_view)
template<class GridViewType , class SS , class SV , class RS , class RV >
std::enable_if
< Stuff::Grid::is_grid_layer
< GridViewType >::value, void >
::type prolong_lagrange (const GridViewType &grid_view, const ConstDiscreteFunction< SS, SV > &source, DiscreteFunction< RS, RV > &range)
template<class SS , class SV , class RS , class RV >
void prolong_lagrange (const ConstDiscreteFunction< SS, SV > &source, DiscreteFunction< RS, RV > &range)
template<class GridViewType , class SourceSpaceType , class SourceVectorType , class RangeSpaceType , class RangeVectorType >
std::enable_if
< Stuff::Grid::is_grid_layer
< GridViewType >::value
&&is_cg_space< RangeSpaceType >
::value, void >::type prolong (const GridViewType &grid_view, const ConstDiscreteFunction< SourceSpaceType, SourceVectorType > &source, DiscreteFunction< RangeSpaceType, RangeVectorType > &range, const size_t=0)
template<class GridViewType , class SourceSpaceType , class SourceVectorType , class RangeSpaceType , class RangeVectorType >
std::enable_if
< Stuff::Grid::is_grid_layer
< GridViewType >::value
&&!is_cg_space< RangeSpaceType >
::value, void >::type prolong (const GridViewType &grid_view, const ConstDiscreteFunction< SourceSpaceType, SourceVectorType > &source, DiscreteFunction< RangeSpaceType, RangeVectorType > &range, const size_t over_integrate=0)
template<class SourceSpaceType , class SourceVectorType , class RangeSpaceType , class RangeVectorType >
std::enable_if< is_cg_space
< RangeSpaceType >::value,
void >::type prolong (const ConstDiscreteFunction< SourceSpaceType, SourceVectorType > &source, DiscreteFunction< RangeSpaceType, RangeVectorType > &range, const size_t=0)
template<class SourceSpaceType , class SourceVectorType , class RangeSpaceType , class RangeVectorType >
std::enable_if<!is_cg_space
< RangeSpaceType >::value,
void >::type prolong (const ConstDiscreteFunction< SourceSpaceType, SourceVectorType > &source, DiscreteFunction< RangeSpaceType, RangeVectorType > &range, const size_t over_integrate=0)
template<class R , size_t r, size_t rC, class GV >
FvSpace< GV, R, r, rC > make_fv_space (const GV &grid_view)
template<class R , size_t r, class GV >
FvSpace< GV, R, r, 1 > make_fv_space (const GV &grid_view)
template<class Traits , size_t d, size_t r, size_t rC, size_t codim = 0>
Traits::GridViewType::template
Codim< codim >::Iterator begin (const Dune::GDT::SpaceInterface< Traits, d, r, rC > &space)
template<class Traits , size_t d, size_t r, size_t rC, size_t codim = 0>
Traits::GridViewType::template
Codim< codim >::Iterator end (const Dune::GDT::SpaceInterface< Traits, d, r, rC > &space)
Variables
static constexpr ChooseSpaceBackend default_cg_backend = default_space_backend
static constexpr ChooseSpaceBackend default_dg_backend = default_space_backend
static constexpr ChooseSpaceBackend default_space_backend
Enumeration Type Documentation
enum Dune::GDT::ChoosePattern strong
Enumerator
volume
face
face_and_volume
enum Dune::GDT::ChooseSpaceBackend strong
Enumerator
gdt
pdelab
fem
enum Dune::GDT::NumericalFluxes strong
Enumerator
godunov
godunov_with_reconstruction
laxfriedrichs
laxfriedrichs_with_reconstruction
local_laxfriedrichs
local_laxfriedrichs_with_reconstruction
enum Dune::GDT::RosenbrockTimeStepperMethods strong
Enumerator
GRK4A
GRK4T
other
enum Dune::GDT::SlopeLimiters strong
Enumerator
minmod
mc
superbee
no_slope
enum Dune::GDT::TimeStepperMethods strong
Enumerator
bogacki_shampine
dormand_prince
adaptive_rungekutta_other
explicit_euler
explicit_rungekutta_second_order_ssp
explicit_rungekutta_third_order_ssp
explicit_rungekutta_classic_fourth_order
explicit_rungekutta_other
Function Documentation
template<class Traits , size_t d, size_t r, size_t rC, size_t codim = 0> Traits::GridViewType::template Codim<codim>::Iterator Dune::GDT::begin (const Dune::GDT::SpaceInterface< Traits, d, r, rC > & space)
References Dune::GDT::SpaceInterface< Traits, domainDim, rangeDim, rangeDimCols >::grid_view().
template<class Traits , size_t d, size_t r, size_t rC, size_t codim = 0> Traits::GridViewType::template Codim<codim>::Iterator Dune::GDT::end (const Dune::GDT::SpaceInterface< Traits, d, r, rC > & space)
References Dune::GDT::SpaceInterface< Traits, domainDim, rangeDim, rangeDimCols >::grid_view().
Referenced by Dune::GDT::TimeStepperInterface< FirstStepperImp::DiscreteFunctionType, FirstStepperImp::TimeFieldType >::solution_at_time().
template<class SpaceType , class VectorType > ConstDiscreteFunction<SpaceType, VectorType> Dune::GDT::make_const_discrete_function (const SpaceType & space, const VectorType & vector, const std::string nm = "gdt.constdiscretefunction")
Referenced by Dune::GDT::StationaryDiscretizationInterface< internal::StationaryContainerBasedDefaultDiscretizationTraits< ProblemImp, AnsatzSpaceImp, MatrixImp, VectorImp, TestSpaceImp > >::visualize().
template<class G , class F > std::unique_ptr<DarcyOperator<G, F> > Dune::GDT::make_darcy (const G & grid_view, const F & function)
template<class GV , class DF , class DT > DiffusiveFluxReconstructionOperator<GV, DF, DT> Dune::GDT::make_diffusive_flux_reconstruction_operator (const GV & grid_view, const DF & diffusion_factor, const DT & diffusion_tensor, const size_t over_integrate = 0)
template<class SpaceType , class VectorType > std::enable_if<is_space<SpaceType>::value && Stuff::LA::is_vector<VectorType>::value, DiscreteFunction<SpaceType, VectorType> >::type Dune::GDT::make_discrete_function (const SpaceType & space, VectorType & vector, const std::string nm = "gdt.discretefunction")
template<class VectorType , class SpaceType > DiscreteFunction<SpaceType, VectorType> Dune::GDT::make_discrete_function (const SpaceType & space, const std::string nm = "gdt.discretefunction")
This can be used like
auto discrete_function = make_discrete_function< VectorType >(space);
template<class VectorType , LocalEllipticIpdgIntegrands::Method method, class DirichletType , class DiffusionFactorType , class DiffusionTensorType , class SpaceType > std::enable_if<Stuff::LA::is_vector<VectorType>::value && Stuff::is_localizable_function<DirichletType>::value && Stuff::is_localizable_function<DiffusionFactorType>::value && Stuff::is_localizable_function<DiffusionTensorType>::value && is_space<SpaceType>::value, std::unique_ptr<EllipticIpdgDirichletVectorFunctional<DirichletType, DiffusionFactorType, DiffusionTensorType, SpaceType, method, VectorType> > >::type Dune::GDT::make_elliptic_ipdg_dirichlet_vector_functional (const DirichletType & dirichlet, const DiffusionFactorType & diffusion_factor, const DiffusionTensorType & diffusion_tensor, const Stuff::Grid::BoundaryInfoInterface< typename SpaceType::GridViewType::Intersection > & boundary_info, const SpaceType & space, const size_t over_integrate = 0)
template<class VectorType , class DirichletType , class DiffusionFactorType , class DiffusionTensorType , class SpaceType > std:: enable_if<Stuff::LA::is_vector<VectorType>::value && Stuff::is_localizable_function<DirichletType>::value && Stuff::is_localizable_function<DiffusionFactorType>::value && Stuff::is_localizable_function<DiffusionTensorType>::value && is_space<SpaceType>::value, std::unique_ptr<EllipticIpdgDirichletVectorFunctional<DirichletType, DiffusionFactorType, DiffusionTensorType, SpaceType, LocalEllipticIpdgIntegrands::default_method, VectorType> > >::type Dune::GDT::make_elliptic_ipdg_dirichlet_vector_functional (const DirichletType & dirichlet, const DiffusionFactorType & diffusion_factor, const DiffusionTensorType & diffusion_tensor, const Stuff::Grid::BoundaryInfoInterface< typename SpaceType::GridViewType::Intersection > & boundary_info, const SpaceType & space, const size_t over_integrate = 0)
template<LocalEllipticIpdgIntegrands::Method method, class DirichletType , class DiffusionFactorType , class DiffusionTensorType , class VectorType , class SpaceType > std::enable_if<Stuff::is_localizable_function<DirichletType>::value && Stuff::is_localizable_function<DiffusionFactorType>::value && Stuff::is_localizable_function<DiffusionTensorType>::value && Stuff::LA::is_vector<VectorType>::value && is_space<SpaceType>::value, std::unique_ptr<EllipticIpdgDirichletVectorFunctional<DirichletType, DiffusionFactorType, DiffusionTensorType, SpaceType, method, VectorType> > >::type Dune::GDT::make_elliptic_ipdg_dirichlet_vector_functional (const DirichletType & dirichlet, const DiffusionFactorType & diffusion_factor, const DiffusionTensorType & diffusion_tensor, const Stuff::Grid::BoundaryInfoInterface< typename SpaceType::GridViewType::Intersection > & boundary_info, VectorType & vector, const SpaceType & space, const size_t over_integrate = 0)
template<class MatrixType , class DiffusionFactorType , class DiffusionTensorType , class SpaceType > std::enable_if<Stuff::LA::is_matrix<MatrixType>::value && Stuff::is_localizable_function<DiffusionFactorType>::value && Stuff::is_localizable_function<DiffusionTensorType>::value && is_space<SpaceType>::value, std::unique_ptr<EllipticIpdgMatrixOperator<DiffusionFactorType, DiffusionTensorType, SpaceType, LocalEllipticIpdgIntegrands::default_method, MatrixType> > >::type Dune::GDT::make_elliptic_ipdg_matrix_operator (const DiffusionFactorType & diffusion_factor, const DiffusionTensorType & diffusion_tensor, const Stuff::Grid::BoundaryInfoInterface< typename SpaceType::GridViewType::Intersection > & boundary_info, const SpaceType & space, const size_t over_integrate = 0)
Creates an elliptic matrix IPDG operator (MatrixType has to be supllied, a matrix is created automatically, default IPDG method is used, source and range space are given by space, grid_view of the space is used).
Note
MatrixType has to be supplied, i.e., use like
auto op = make_elliptic_ipdg_matrix_operator< MatrixType >(factor, tensor, boundary_info, space);
References Dune::GDT::LocalEllipticIpdgIntegrands::default_method.
template<class MatrixType , LocalEllipticIpdgIntegrands::Method method, class DiffusionFactorType , class DiffusionTensorType , class SpaceType > std::enable_if<Stuff::LA::is_matrix<MatrixType>::value && Stuff::is_localizable_function<DiffusionFactorType>::value && Stuff::is_localizable_function<DiffusionTensorType>::value && is_space<SpaceType>::value, std::unique_ptr<EllipticIpdgMatrixOperator<DiffusionFactorType, DiffusionTensorType, SpaceType, method, MatrixType> > >::type Dune::GDT::make_elliptic_ipdg_matrix_operator (const DiffusionFactorType & diffusion_factor, const DiffusionTensorType & diffusion_tensor, const Stuff::Grid::BoundaryInfoInterface< typename SpaceType::GridViewType::Intersection > & boundary_info, const SpaceType & space, const size_t over_integrate = 0)
Creates an elliptic matrix IPDG operator (MatrixType has to be supllied, a matrix is created automatically, IPDG method has to be supplied, source and range space are given by space, grid_view of the space is used).
Note
MatrixType and IPDG method have to be supplied, i.e., use like
auto op = make_elliptic_ipdg_matrix_operator< MatrixType, LocalEllipticIpdgIntegrands::swipdg >(factor, tensor,
boundary_info, space);
template<class MatrixType , class DiffusionFactorType , class DiffusionTensorType , class SpaceType , class GridViewType > std::enable_if<Stuff::LA::is_matrix<MatrixType>::value && Stuff::is_localizable_function<DiffusionFactorType>::value && Stuff::is_localizable_function<DiffusionTensorType>::value && is_space<SpaceType>::value && Stuff::Grid::is_grid_layer<GridViewType>::value, std::unique_ptr<EllipticIpdgMatrixOperator<DiffusionFactorType, DiffusionTensorType, SpaceType, LocalEllipticIpdgIntegrands::default_method, MatrixType, GridViewType> > >::type Dune::GDT::make_elliptic_ipdg_matrix_operator (const DiffusionFactorType & diffusion_factor, const DiffusionTensorType & diffusion_tensor, const Stuff::Grid::BoundaryInfoInterface< typename GridViewType::Intersection > & boundary_info, const SpaceType & space, const GridViewType & grid_view, const size_t over_integrate = 0)
Creates an elliptic matrix IPDG operator (MatrixType has to be supllied, a matrix is created automatically, default IPDG method is used, source and range space are given by space).
Note
MatrixType has to be supplied, i.e., use like
auto op = make_elliptic_ipdg_matrix_operator< MatrixType >(factor, tensor, boundary_info, space, grid_view);
References Dune::GDT::LocalEllipticIpdgIntegrands::default_method.
template<class MatrixType , LocalEllipticIpdgIntegrands::Method method, class DiffusionFactorType , class DiffusionTensorType , class SpaceType , class GridViewType > std::enable_if<Stuff::LA::is_matrix<MatrixType>::value && Stuff::is_localizable_function<DiffusionFactorType>::value && Stuff::is_localizable_function<DiffusionTensorType>::value && is_space<SpaceType>::value && Stuff::Grid::is_grid_layer<GridViewType>::value, std::unique_ptr<EllipticIpdgMatrixOperator<DiffusionFactorType, DiffusionTensorType, SpaceType, method, MatrixType, GridViewType> > >::type Dune::GDT::make_elliptic_ipdg_matrix_operator (const DiffusionFactorType & diffusion_factor, const DiffusionTensorType & diffusion_tensor, const Stuff::Grid::BoundaryInfoInterface< typename GridViewType::Intersection > & boundary_info, const SpaceType & space, const GridViewType & grid_view, const size_t over_integrate = 0)
Creates an elliptic matrix IPDG operator (MatrixType has to be supllied, a matrix is created automatically, IPDG method has to be supplied, source and range space are given by space).
Note
MatrixType and IPDG method have to be supplied, i.e., use like
auto op = make_elliptic_ipdg_matrix_operator< MatrixType, LocalEllipticIpdgIntegrands::swipdg >(factor, tensor,
boundary_info, space, grid_view);
template<class MatrixType , class DiffusionFactorType , class DiffusionTensorType , class RangeSpaceType , class SourceSpaceType , class GridViewType > std:: enable_if<Stuff::LA::is_matrix<MatrixType>::value && Stuff::is_localizable_function<DiffusionFactorType>::value && Stuff::is_localizable_function<DiffusionTensorType>::value && is_space<RangeSpaceType>::value && is_space<SourceSpaceType>::value && Stuff::Grid::is_grid_layer<GridViewType>::value, std::unique_ptr<EllipticIpdgMatrixOperator<DiffusionFactorType, DiffusionTensorType, RangeSpaceType, LocalEllipticIpdgIntegrands::default_method, MatrixType, GridViewType, SourceSpaceType> > >::type Dune::GDT::make_elliptic_ipdg_matrix_operator (const DiffusionFactorType & diffusion_factor, const DiffusionTensorType & diffusion_tensor, const Stuff::Grid::BoundaryInfoInterface< typename GridViewType::Intersection > & boundary_info, const RangeSpaceType & range_space, const SourceSpaceType & source_space, const GridViewType & grid_view, const size_t over_integrate = 0)
Creates an elliptic matrix IPDG operator (MatrixType has to be supllied, a matrix is created automatically, default IPDG method is used).
Note
MatrixType has to be supplied, i.e., use like
auto op = make_elliptic_ipdg_matrix_operator< MatrixType >(factor, tensor, boundary_info, range_space, source_space,
grid_view);
References Dune::GDT::LocalEllipticIpdgIntegrands::default_method.
template<class MatrixType , LocalEllipticIpdgIntegrands::Method method, class DiffusionFactorType , class DiffusionTensorType , class RangeSpaceType , class SourceSpaceType , class GridViewType > std:: enable_if<Stuff::LA::is_matrix<MatrixType>::value && Stuff::is_localizable_function<DiffusionFactorType>::value && Stuff::is_localizable_function<DiffusionTensorType>::value && is_space<RangeSpaceType>::value && is_space<SourceSpaceType>::value && Stuff::Grid::is_grid_layer<GridViewType>::value, std::unique_ptr<EllipticIpdgMatrixOperator<DiffusionFactorType, DiffusionTensorType, RangeSpaceType, method, MatrixType, GridViewType, SourceSpaceType> > >::type Dune::GDT::make_elliptic_ipdg_matrix_operator (const DiffusionFactorType & diffusion_factor, const DiffusionTensorType & diffusion_tensor, const Stuff::Grid::BoundaryInfoInterface< typename GridViewType::Intersection > & boundary_info, const RangeSpaceType & range_space, const SourceSpaceType & source_space, const GridViewType & grid_view, const size_t over_integrate = 0)
Creates an elliptic matrix IPDG operator (MatrixType has to be supllied, a matrix is created automatically, IPDG method has to be supplied).
Note
MatrixType and IPDG method have to be supplied, i.e., use like
auto op = make_elliptic_ipdg_matrix_operator< MatrixType, LocalEllipticIpdgIntegrands::swipdg >(factor, tensor,
boundary_info, range_space, source_space, grid_view);
template<class DiffusionFactorType , class DiffusionTensorType , class MatrixType , class SpaceType > std::enable_if<Stuff::is_localizable_function<DiffusionFactorType>::value && Stuff::is_localizable_function<DiffusionTensorType>::value && Stuff::LA::is_matrix<MatrixType>::value && is_space<SpaceType>::value, std::unique_ptr<EllipticIpdgMatrixOperator<DiffusionFactorType, DiffusionTensorType, SpaceType, LocalEllipticIpdgIntegrands::default_method, MatrixType> > >::type Dune::GDT::make_elliptic_ipdg_matrix_operator (const DiffusionFactorType & diffusion_factor, const DiffusionTensorType & diffusion_tensor, const Stuff::Grid::BoundaryInfoInterface< typename SpaceType::GridViewType::Intersection > & boundary_info, MatrixType & matrix, const SpaceType & space, const size_t over_integrate = 0)
Creates an elliptic matrix IPDG operator (default IPDG method is used, source and range space are given by space, grid_view of the space is used).
References Dune::GDT::LocalEllipticIpdgIntegrands::default_method.
template<LocalEllipticIpdgIntegrands::Method method, class DiffusionFactorType , class DiffusionTensorType , class MatrixType , class SpaceType > std::enable_if<Stuff::is_localizable_function<DiffusionFactorType>::value && Stuff::is_localizable_function<DiffusionTensorType>::value && Stuff::LA::is_matrix<MatrixType>::value && is_space<SpaceType>::value, std::unique_ptr<EllipticIpdgMatrixOperator<DiffusionFactorType, DiffusionTensorType, SpaceType, method, MatrixType> > >::type Dune::GDT::make_elliptic_ipdg_matrix_operator (const DiffusionFactorType & diffusion_factor, const DiffusionTensorType & diffusion_tensor, const Stuff::Grid::BoundaryInfoInterface< typename SpaceType::GridViewType::Intersection > & boundary_info, MatrixType & matrix, const SpaceType & space, const size_t over_integrate = 0)
Creates an elliptic matrix IPDG operator (IPDG method has to be supplied, source and range space are given by space, grid_view of the space is used).
Note
IPDG method has to be supplied, i.e., use like
auto op = make_elliptic_ipdg_matrix_operator< LocalEllipticIpdgIntegrands::swipdg >(factor, tensor, boundary_info,
matrix, space);
template<class DiffusionFactorType , class DiffusionTensorType , class MatrixType , class SpaceType , class GridViewType > std::enable_if<Stuff::is_localizable_function<DiffusionFactorType>::value && Stuff::is_localizable_function<DiffusionTensorType>::value && Stuff::LA::is_matrix<MatrixType>::value && is_space<SpaceType>::value && Stuff::Grid::is_grid_layer<GridViewType>::value, std::unique_ptr<EllipticIpdgMatrixOperator<DiffusionFactorType, DiffusionTensorType, SpaceType, LocalEllipticIpdgIntegrands::default_method, MatrixType, GridViewType> > >::type Dune::GDT::make_elliptic_ipdg_matrix_operator (const DiffusionFactorType & diffusion_factor, const DiffusionTensorType & diffusion_tensor, const Stuff::Grid::BoundaryInfoInterface< typename GridViewType::Intersection > & boundary_info, MatrixType & matrix, const SpaceType & space, const GridViewType & grid_view, const size_t over_integrate = 0)
Creates an elliptic matrix IPDG operator (default IPDG method is used, source and range space are given by space).
References Dune::GDT::LocalEllipticIpdgIntegrands::default_method.
template<LocalEllipticIpdgIntegrands::Method method, class DiffusionFactorType , class DiffusionTensorType , class MatrixType , class SpaceType , class GridViewType > std::enable_if<Stuff::is_localizable_function<DiffusionFactorType>::value && Stuff::is_localizable_function<DiffusionTensorType>::value && Stuff::LA::is_matrix<MatrixType>::value && is_space<SpaceType>::value && Stuff::Grid::is_grid_layer<GridViewType>::value, std::unique_ptr<EllipticIpdgMatrixOperator<DiffusionFactorType, DiffusionTensorType, SpaceType, method, MatrixType, GridViewType> > >::type Dune::GDT::make_elliptic_ipdg_matrix_operator (const DiffusionFactorType & diffusion_factor, const DiffusionTensorType & diffusion_tensor, const Stuff::Grid::BoundaryInfoInterface< typename GridViewType::Intersection > & boundary_info, MatrixType & matrix, const SpaceType & space, const GridViewType & grid_view, const size_t over_integrate = 0)
Creates an elliptic matrix IPDG operator (IPDG method has to be supplied, source and range space are given by space).
Note
IPDG method has to be supplied, i.e., use like
auto op = make_elliptic_ipdg_matrix_operator< LocalEllipticIpdgIntegrands::swipdg >(factor, tensor, boundary_info,
matrix, space, grid_view);
template<class DiffusionFactorType , class DiffusionTensorType , class MatrixType , class RangeSpaceType , class SourceSpaceType , class GridViewType > std:: enable_if<Stuff::is_localizable_function<DiffusionFactorType>::value && Stuff::is_localizable_function<DiffusionTensorType>::value && Stuff::LA::is_matrix<MatrixType>::value && is_space<RangeSpaceType>::value && is_space<SourceSpaceType>::value && Stuff::Grid::is_grid_layer<GridViewType>::value, std::unique_ptr<EllipticIpdgMatrixOperator<DiffusionFactorType, DiffusionTensorType, RangeSpaceType, LocalEllipticIpdgIntegrands::default_method, MatrixType, GridViewType, SourceSpaceType> > >::type Dune::GDT::make_elliptic_ipdg_matrix_operator (const DiffusionFactorType & diffusion_factor, const DiffusionTensorType & diffusion_tensor, const Stuff::Grid::BoundaryInfoInterface< typename GridViewType::Intersection > & boundary_info, MatrixType & matrix, const RangeSpaceType & range_space, const SourceSpaceType & source_space, const GridViewType & grid_view, const size_t over_integrate = 0)
Creates an elliptic matrix IPDG operator (default IPDG method is used).
References Dune::GDT::LocalEllipticIpdgIntegrands::default_method.
template<LocalEllipticIpdgIntegrands::Method method, class DiffusionFactorType , class DiffusionTensorType , class MatrixType , class RangeSpaceType , class SourceSpaceType , class GridViewType > std:: enable_if<Stuff::is_localizable_function<DiffusionFactorType>::value && Stuff::is_localizable_function<DiffusionTensorType>::value && Stuff::LA::is_matrix<MatrixType>::value && is_space<RangeSpaceType>::value && is_space<SourceSpaceType>::value && Stuff::Grid::is_grid_layer<GridViewType>::value, std::unique_ptr<EllipticIpdgMatrixOperator<DiffusionFactorType, DiffusionTensorType, RangeSpaceType, method, MatrixType, GridViewType, SourceSpaceType> > >::type Dune::GDT::make_elliptic_ipdg_matrix_operator (const DiffusionFactorType & diffusion_factor, const DiffusionTensorType & diffusion_tensor, const Stuff::Grid::BoundaryInfoInterface< typename GridViewType::Intersection > & boundary_info, MatrixType & matrix, const RangeSpaceType & range_space, const SourceSpaceType & source_space, const GridViewType & grid_view, const size_t over_integrate = 0)
Creates an elliptic matrix IPDG operator (IPDG method has to be supplied).
Note
IPDG method has to be supplied, i.e., use like
auto op = make_elliptic_ipdg_matrix_operator< LocalEllipticIpdgIntegrands::swipdg >(factor, tensor, boundary_info,
matrix, range_space, source_space, grid_view);
template<class DiffusionType , class GridViewType , class RangeType , class SourceType > std::enable_if<Stuff::is_localizable_function<DiffusionType>::value && Stuff::Grid::is_grid_layer<GridViewType>::value && Stuff::is_localizable_function<RangeType>::value && Stuff::is_localizable_function<SourceType>::value, std::unique_ptr<EllipticLocalizableProduct<DiffusionType, void, GridViewType, RangeType, SourceType> > >::type Dune::GDT::make_elliptic_localizable_product (const DiffusionType & diffusion, const GridViewType & grid_view, const RangeType & range, const SourceType & source, const size_t over_integrate = 0)
See Also
EllipticLocalizableProduct, especially for the role of diffusion.
Referenced by Dune::GDT::EllipticOperator< DiffusionFactorType, DiffusionTensorType, GridView, Field >::apply2().
template<class DiffusionFactorType , class DiffusionTensorType , class GridViewType , class RangeType , class SourceType > std::enable_if<Stuff::is_localizable_function<DiffusionFactorType>::value && Stuff::is_localizable_function<DiffusionTensorType>::value && Stuff::Grid::is_grid_layer<GridViewType>::value && Stuff::is_localizable_function<RangeType>::value && Stuff::is_localizable_function<SourceType>::value, std::unique_ptr<EllipticLocalizableProduct<DiffusionFactorType, DiffusionTensorType, GridViewType, RangeType, SourceType> > >::type Dune::GDT::make_elliptic_localizable_product (const DiffusionFactorType & diffusion_factor, const DiffusionTensorType & diffusion_tensor, const GridViewType & grid_view, const RangeType & range, const SourceType & source, const size_t over_integrate = 0)
See Also
EllipticLocalizableProduct, especially for the role of diffusion_factor and diffusion_tensor.
template<class MatrixType , class DiffusionFactorType , class DiffusionTensorType , class SpaceType > std::enable_if<Stuff::LA::is_matrix<MatrixType>::value && Stuff::is_localizable_function<DiffusionFactorType>::value && Stuff::is_localizable_function<DiffusionTensorType>::value && is_space<SpaceType>::value, std::unique_ptr<EllipticMatrixOperator<DiffusionFactorType, DiffusionTensorType, SpaceType, MatrixType> > >::type Dune::GDT::make_elliptic_matrix_operator (const DiffusionFactorType & diffusion_factor, const DiffusionTensorType & diffusion_tensor, const SpaceType & space, const size_t over_integrate = 0)
Creates an elliptic matrix operator (MatrixType has to be supllied, a matrix is created automatically, source and range space are given by space, grid_view of the space is used).
Note
MatrixType has to be supplied, i.e., use like
auto op = make_elliptic_matrix_operator< MatrixType >(factor, tensor, space);
template<class MatrixType , class DiffusionFactorType , class DiffusionTensorType , class SpaceType , class GridViewType > std::enable_if<Stuff::LA::is_matrix<MatrixType>::value && Stuff::is_localizable_function<DiffusionFactorType>::value && Stuff::is_localizable_function<DiffusionTensorType>::value && is_space<SpaceType>::value && Stuff::Grid::is_grid_layer<GridViewType>::value, std::unique_ptr<EllipticMatrixOperator<DiffusionFactorType, DiffusionTensorType, SpaceType, MatrixType, GridViewType> > >::type Dune::GDT::make_elliptic_matrix_operator (const DiffusionFactorType & diffusion_factor, const DiffusionTensorType & diffusion_tensor, const SpaceType & space, const GridViewType & grid_view, const size_t over_integrate = 0)
Creates an elliptic matrix operator (MatrixType has to be supllied, a matrix is created automatically, source and range space are given by space).
Note
MatrixType has to be supplied, i.e., use like
auto op = make_elliptic_matrix_operator< MatrixType >(factor, tensor, space, grid_view);
template<class MatrixType , class DiffusionFactorType , class DiffusionTensorType , class RangeSpaceType , class SourceSpaceType , class GridViewType > std::enable_if<Stuff::LA::is_matrix<MatrixType>::value && Stuff::is_localizable_function<DiffusionFactorType>::value && Stuff::is_localizable_function<DiffusionTensorType>::value && is_space<RangeSpaceType>::value && is_space<SourceSpaceType>::value && Stuff::Grid::is_grid_layer<GridViewType>::value, std::unique_ptr<EllipticMatrixOperator<DiffusionFactorType, DiffusionTensorType, RangeSpaceType, MatrixType, GridViewType, SourceSpaceType> > >::type Dune::GDT::make_elliptic_matrix_operator (const DiffusionFactorType & diffusion_factor, const DiffusionTensorType & diffusion_tensor, const RangeSpaceType & range_space, const SourceSpaceType & source_space, const GridViewType & grid_view, const size_t over_integrate = 0)
Creates an elliptic matrix operator (MatrixType has to be supllied, a matrix is created automatically).
Note
MatrixType has to be supplied, i.e., use like
auto op = make_elliptic_matrix_operator< MatrixType >(factor, tensor, range_space, source_space, grid_view);
template<class DiffusionFactorType , class DiffusionTensorType , class MatrixType , class SpaceType > std::enable_if<Stuff::is_localizable_function<DiffusionFactorType>::value && Stuff::is_localizable_function<DiffusionTensorType>::value && Stuff::LA::is_matrix<MatrixType>::value && is_space<SpaceType>::value, std::unique_ptr<EllipticMatrixOperator<DiffusionFactorType, DiffusionTensorType, SpaceType, MatrixType> > >::type Dune::GDT::make_elliptic_matrix_operator (const DiffusionFactorType & diffusion_factor, const DiffusionTensorType & diffusion_tensor, MatrixType & matrix, const SpaceType & space, const size_t over_integrate = 0)
Creates an elliptic matrix operator (source and range space are given by space, grid_view of the space is used).
template<class DiffusionFactorType , class DiffusionTensorType , class MatrixType , class SpaceType , class GridViewType > std::enable_if<Stuff::is_localizable_function<DiffusionFactorType>::value && Stuff::is_localizable_function<DiffusionTensorType>::value && Stuff::LA::is_matrix<MatrixType>::value && is_space<SpaceType>::value && Stuff::Grid::is_grid_layer<GridViewType>::value, std::unique_ptr<EllipticMatrixOperator<DiffusionFactorType, DiffusionTensorType, SpaceType, MatrixType, GridViewType> > >::type Dune::GDT::make_elliptic_matrix_operator (const DiffusionFactorType & diffusion_factor, const DiffusionTensorType & diffusion_tensor, MatrixType & matrix, const SpaceType & space, const GridViewType & grid_view, const size_t over_integrate = 0)
Creates an elliptic matrix operator (source and range space are given by space).
template<class DiffusionFactorType , class DiffusionTensorType , class MatrixType , class RangeSpaceType , class SourceSpaceType , class GridViewType > std::enable_if<Stuff::is_localizable_function<DiffusionFactorType>::value && Stuff::is_localizable_function<DiffusionTensorType>::value && Stuff::LA::is_matrix<MatrixType>::value && is_space<RangeSpaceType>::value && is_space<SourceSpaceType>::value && Stuff::Grid::is_grid_layer<GridViewType>::value, std::unique_ptr<EllipticMatrixOperator<DiffusionFactorType, DiffusionTensorType, RangeSpaceType, MatrixType, GridViewType, SourceSpaceType> > >::type Dune::GDT::make_elliptic_matrix_operator (const DiffusionFactorType & diffusion_factor, const DiffusionTensorType & diffusion_tensor, MatrixType & matrix, const RangeSpaceType & range_space, const SourceSpaceType & source_space, const GridViewType & grid_view, const size_t over_integrate = 0)
Creates an elliptic matrix operator.
template<class MatrixType , class DiffusionType , class SpaceType > std::enable_if<Stuff::LA::is_matrix<MatrixType>::value && Stuff::is_localizable_function<DiffusionType>::value && is_space<SpaceType>::value, std::unique_ptr<EllipticMatrixOperator<DiffusionType, void, SpaceType, MatrixType> > >::type Dune::GDT::make_elliptic_matrix_operator (const DiffusionType & diffusion, const SpaceType & space, const size_t over_integrate = 0)
Creates an elliptic matrix operator (single diffusion given, MatrixType has to be supllied, a matrix is created automatically, source and range space are given by space, grid_view of the space is used).
Note
MatrixType has to be supplied, i.e., use like
auto op = make_elliptic_matrix_operator< MatrixType >(diffusion, space);
template<class MatrixType , class DiffusionType , class SpaceType , class GridViewType > std:: enable_if<Stuff::LA::is_matrix<MatrixType>::value && Stuff::is_localizable_function<DiffusionType>::value && is_space<SpaceType>::value && Stuff::Grid::is_grid_layer<GridViewType>::value, std::unique_ptr<EllipticMatrixOperator<DiffusionType, void, SpaceType, MatrixType, GridViewType> > >::type Dune::GDT::make_elliptic_matrix_operator (const DiffusionType & diffusion, const SpaceType & space, const GridViewType & grid_view, const size_t over_integrate = 0)
Creates an elliptic matrix operator (single diffusion given, MatrixType has to be supllied, a matrix is created automatically, source and range space are given by space).
Note
MatrixType has to be supplied, i.e., use like
auto op = make_elliptic_matrix_operator< MatrixType >(diffusion, space, grid_view);
template<class MatrixType , class DiffusionType , class RangeSpaceType , class SourceSpaceType , class GridViewType > std::enable_if<Stuff::LA::is_matrix<MatrixType>::value && Stuff::is_localizable_function<DiffusionType>::value && is_space<RangeSpaceType>::value && is_space<SourceSpaceType>::value && Stuff::Grid::is_grid_layer<GridViewType>::value, std::unique_ptr<EllipticMatrixOperator<DiffusionType, void, RangeSpaceType, MatrixType, GridViewType, SourceSpaceType> > >::type Dune::GDT::make_elliptic_matrix_operator (const DiffusionType & diffusion, const RangeSpaceType & range_space, const SourceSpaceType & source_space, const GridViewType & grid_view, const size_t over_integrate = 0)
Creates an elliptic matrix operator (single diffusion given, MatrixType has to be supllied, a matrix is created automatically).
Note
MatrixType has to be supplied, i.e., use like
auto op = make_elliptic_matrix_operator< MatrixType >(diffusion, range_space, source_space, grid_view);
template<class DiffusionType , class MatrixType , class SpaceType > std::enable_if<Stuff::is_localizable_function<DiffusionType>::value && Stuff::LA::is_matrix<MatrixType>::value && is_space<SpaceType>::value, std::unique_ptr<EllipticMatrixOperator<DiffusionType, void, SpaceType, MatrixType> > >::type Dune::GDT::make_elliptic_matrix_operator (const DiffusionType & diffusion, MatrixType & matrix, const SpaceType & space, const size_t over_integrate = 0)
Creates an elliptic matrix operator (single diffusion given, source and range space are given by space, grid_view of the space is used).
template<class DiffusionType , class MatrixType , class SpaceType , class GridViewType > std:: enable_if<Stuff::is_localizable_function<DiffusionType>::value && Stuff::LA::is_matrix<MatrixType>::value && is_space<SpaceType>::value && Stuff::Grid::is_grid_layer<GridViewType>::value, std::unique_ptr<EllipticMatrixOperator<DiffusionType, void, SpaceType, MatrixType, GridViewType> > >::type Dune::GDT::make_elliptic_matrix_operator (const DiffusionType & diffusion, MatrixType & matrix, const SpaceType & space, const GridViewType & grid_view, const size_t over_integrate = 0)
Creates an elliptic matrix operator (single diffusion given, source and range space are given by space).
template<class DiffusionType , class MatrixType , class RangeSpaceType , class SourceSpaceType , class GridViewType > std::enable_if<Stuff::is_localizable_function<DiffusionType>::value && Stuff::LA::is_matrix<MatrixType>::value && is_space<RangeSpaceType>::value && is_space<SourceSpaceType>::value && Stuff::Grid::is_grid_layer<GridViewType>::value, std::unique_ptr<EllipticMatrixOperator<DiffusionType, void, RangeSpaceType, MatrixType, GridViewType, SourceSpaceType> > >::type Dune::GDT::make_elliptic_matrix_operator (const DiffusionType & diffusion, MatrixType & matrix, const RangeSpaceType & range_space, const SourceSpaceType & source_space, const GridViewType & grid_view, const size_t over_integrate = 0)
Creates an elliptic matrix operator (single diffusion given).
template<class GridViewType , class DiffusionType > std::enable_if<Stuff::Grid::is_grid_layer<GridViewType>::value && Stuff::is_localizable_function<DiffusionType>::value, std::unique_ptr<EllipticOperator<DiffusionType, void, GridViewType, typename DiffusionType::RangeFieldType> > >::type Dune::GDT::make_elliptic_operator (const GridViewType & grid_view, const DiffusionType & diffusion, const size_t over_integrate = 0)
template<class GridViewType , class DiffusionFactorType , class DiffusionTensorType > std::enable_if<Stuff::Grid::is_grid_layer<GridViewType>::value && Stuff::is_localizable_function<DiffusionFactorType>::value && Stuff::is_localizable_function<DiffusionTensorType>::value, std::unique_ptr<EllipticOperator<DiffusionFactorType, DiffusionTensorType, GridViewType, typename DiffusionFactorType::RangeFieldType> > >::type Dune::GDT::make_elliptic_operator (const GridViewType & grid_view, const DiffusionFactorType & diffusion_factor, const DiffusionTensorType & diffusion_tensor, const size_t over_integrate = 0)
template<class R , size_t r, size_t rC, class GV > FvSpace<GV, R, r, rC> Dune::GDT::make_fv_space (const GV & grid_view)
template<class R , size_t r, class GV > FvSpace<GV, R, r, 1> Dune::GDT::make_fv_space (const GV & grid_view)
template<class GridViewType , class SourceType , class SpaceType , class VectorType > std:: enable_if<Stuff::Grid::is_grid_layer<GridViewType>::value && Stuff::is_localizable_function<SourceType>::value && is_space<SpaceType>::value && Stuff::LA::is_vector<VectorType>::value, std::unique_ptr<L2GlobalProjectionLocalizableOperator<GridViewType, SourceType, DiscreteFunction<SpaceType, VectorType> > > >::type Dune::GDT::make_global_l2_projection_localizable_operator (const GridViewType & grid_view, const SourceType & source, DiscreteFunction< SpaceType, VectorType > & range, const size_t over_integrate = 0)
template<class SourceType , class SpaceType , class VectorType > std:: enable_if<Stuff::is_localizable_function<SourceType>::value && is_space<SpaceType>::value && Stuff::LA::is_vector<VectorType>::value, std::unique_ptr<L2GlobalProjectionLocalizableOperator<typename SpaceType::GridViewType, SourceType, DiscreteFunction<SpaceType, VectorType> > > >::type Dune::GDT::make_global_l2_projection_localizable_operator (const SourceType & source, DiscreteFunction< SpaceType, VectorType > & range, const size_t over_integrate = 0)
References Dune::GDT::ConstDiscreteFunction< SpaceImp, VectorImp >::space().
template<class GridViewType > std::enable_if<Stuff::Grid::is_grid_layer<GridViewType>::value, std::unique_ptr<L2GlobalProjectionOperator<GridViewType> > >::type Dune::GDT::make_global_l2_projection_operator (const GridViewType & grid_view, const size_t over_integrate = 0)
template<class GridViewType , class SourceSpaceType , class SourceVectorType , class RangeSpaceType , class RangeVectorType > std::enable_if<Stuff::Grid::is_grid_layer<GridViewType>::value && is_space<SourceSpaceType>::value && Stuff::LA::is_vector<SourceVectorType>::value && is_space<RangeSpaceType>::value && Stuff::LA::is_vector<RangeVectorType>::value, std::unique_ptr<L2GlobalProlongationLocalizableOperator<GridViewType, ConstDiscreteFunction<SourceSpaceType, SourceVectorType>, DiscreteFunction<RangeSpaceType, RangeVectorType> > > >:: type Dune::GDT::make_global_l2_prolongation_localizable_operator (const GridViewType & grid_view, const ConstDiscreteFunction< SourceSpaceType, SourceVectorType > & source, DiscreteFunction< RangeSpaceType, RangeVectorType > & range, const size_t over_integrate = 0)
template<class SourceSpaceType , class SourceVectorType , class RangeSpaceType , class RangeVectorType > std::enable_if<is_space<SourceSpaceType>::value && Stuff::LA::is_vector<SourceVectorType>::value && is_space<RangeSpaceType>::value && Stuff::LA::is_vector<RangeVectorType>::value, std::unique_ptr<L2GlobalProlongationLocalizableOperator< typename RangeSpaceType::GridViewType, ConstDiscreteFunction<SourceSpaceType, SourceVectorType>, DiscreteFunction<RangeSpaceType, RangeVectorType> > > >::type Dune::GDT::make_global_l2_prolongation_localizable_operator (const ConstDiscreteFunction< SourceSpaceType, SourceVectorType > & source, DiscreteFunction< RangeSpaceType, RangeVectorType > & range, const size_t over_integrate = 0)
References Dune::GDT::ConstDiscreteFunction< SpaceImp, VectorImp >::space().
template<class GridViewType > std::enable_if<Stuff::Grid::is_grid_layer<GridViewType>::value, std::unique_ptr<L2GlobalProlongationOperator<GridViewType> > >::type Dune::GDT::make_global_l2_prolongation_operator (const GridViewType & grid_view, const size_t over_integrate = 0)
template<class VectorType , class FunctionType , class SpaceType > std::enable_if<Stuff::LA::is_vector<VectorType>::value && Stuff::is_localizable_function<FunctionType>::value && is_space<SpaceType>::value, std::unique_ptr<L2FaceVectorFunctional<FunctionType, SpaceType, VectorType> > >::type Dune::GDT::make_l2_face_vector_functional (const FunctionType & function, const SpaceType & space, const size_t over_integrate = 0)
template<class VectorType , class FunctionType , class SpaceType > std::enable_if<Stuff::LA::is_vector<VectorType>::value && Stuff::is_localizable_function<FunctionType>::value && is_space<SpaceType>::value, std::unique_ptr<L2FaceVectorFunctional<FunctionType, SpaceType, VectorType> > >::type Dune::GDT::make_l2_face_vector_functional (const FunctionType & function, const SpaceType & space, const Stuff::Grid::ApplyOn::WhichIntersection< typename SpaceType::GridViewType > * where)
template<class VectorType , class FunctionType , class SpaceType > std::enable_if<Stuff::LA::is_vector<VectorType>::value && Stuff::is_localizable_function<FunctionType>::value && is_space<SpaceType>::value, std::unique_ptr<L2FaceVectorFunctional<FunctionType, SpaceType, VectorType> > >::type Dune::GDT::make_l2_face_vector_functional (const FunctionType & function, const SpaceType & space, const size_t over_integrate, const Stuff::Grid::ApplyOn::WhichIntersection< typename SpaceType::GridViewType > * where)
template<class VectorType , class FunctionType , class SpaceType , class GridViewType > std::enable_if<Stuff::LA::is_vector<VectorType>::value && Stuff::is_localizable_function<FunctionType>::value && is_space<SpaceType>::value && Stuff::Grid::is_grid_layer<GridViewType>::value, std::unique_ptr<L2FaceVectorFunctional<FunctionType, SpaceType, VectorType, GridViewType> > >:: type Dune::GDT::make_l2_face_vector_functional (const FunctionType & function, const SpaceType & space, const GridViewType & grid_view, const size_t over_integrate = 0)
template<class VectorType , class FunctionType , class SpaceType , class GridViewType > std::enable_if<Stuff::LA::is_vector<VectorType>::value && Stuff::is_localizable_function<FunctionType>::value && is_space<SpaceType>::value && Stuff::Grid::is_grid_layer<GridViewType>::value, std::unique_ptr<L2FaceVectorFunctional<FunctionType, SpaceType, VectorType, GridViewType> > >::type Dune::GDT::make_l2_face_vector_functional (const FunctionType & function, const SpaceType & space, const GridViewType & grid_view, const Stuff::Grid::ApplyOn::WhichIntersection< typename SpaceType::GridViewType > * where)
template<class VectorType , class FunctionType , class SpaceType , class GridViewType > std::enable_if<Stuff::LA::is_vector<VectorType>::value && Stuff::is_localizable_function<FunctionType>::value && is_space<SpaceType>::value && Stuff::Grid::is_grid_layer<GridViewType>::value, std::unique_ptr<L2FaceVectorFunctional<FunctionType, SpaceType, VectorType, GridViewType> > >::type Dune::GDT::make_l2_face_vector_functional (const FunctionType & function, const SpaceType & space, const GridViewType & grid_view, const size_t over_integrate, const Stuff::Grid::ApplyOn::WhichIntersection< typename SpaceType::GridViewType > * where)
template<class FunctionType , class VectorType , class SpaceType > std::enable_if<Stuff::is_localizable_function<FunctionType>::value && Stuff::LA::is_vector<VectorType>::value && is_space<SpaceType>::value, std::unique_ptr<L2FaceVectorFunctional<FunctionType, SpaceType, VectorType> > >::type Dune::GDT::make_l2_face_vector_functional (const FunctionType & function, VectorType & vector, const SpaceType & space, const size_t over_integrate = 0)
template<class FunctionType , class VectorType , class SpaceType > std::enable_if<Stuff::is_localizable_function<FunctionType>::value && Stuff::LA::is_vector<VectorType>::value && is_space<SpaceType>::value, std::unique_ptr<L2FaceVectorFunctional<FunctionType, SpaceType, VectorType> > >::type Dune::GDT::make_l2_face_vector_functional (const FunctionType & function, VectorType & vector, const SpaceType & space, const Stuff::Grid::ApplyOn::WhichIntersection< typename SpaceType::GridViewType > * where)
template<class FunctionType , class VectorType , class SpaceType > std::enable_if<Stuff::is_localizable_function<FunctionType>::value && Stuff::LA::is_vector<VectorType>::value && is_space<SpaceType>::value, std::unique_ptr<L2FaceVectorFunctional<FunctionType, SpaceType, VectorType> > >::type Dune::GDT::make_l2_face_vector_functional (const FunctionType & function, VectorType & vector, const SpaceType & space, const size_t over_integrate, const Stuff::Grid::ApplyOn::WhichIntersection< typename SpaceType::GridViewType > * where)
template<class FunctionType , class VectorType , class SpaceType , class GridViewType > std::enable_if<Stuff::is_localizable_function<FunctionType>::value && Stuff::LA::is_vector<VectorType>::value && is_space<SpaceType>::value && Stuff::Grid::is_grid_layer<GridViewType>::value, std::unique_ptr<L2FaceVectorFunctional<FunctionType, SpaceType, VectorType, GridViewType> > >:: type Dune::GDT::make_l2_face_vector_functional (const FunctionType & function, VectorType & vector, const SpaceType & space, const GridViewType & grid_view, const size_t over_integrate = 0)
template<class FunctionType , class VectorType , class SpaceType , class GridViewType > std::enable_if<Stuff::is_localizable_function<FunctionType>::value && Stuff::LA::is_vector<VectorType>::value && is_space<SpaceType>::value && Stuff::Grid::is_grid_layer<GridViewType>::value, std::unique_ptr<L2FaceVectorFunctional<FunctionType, SpaceType, VectorType, GridViewType> > >:: type Dune::GDT::make_l2_face_vector_functional (const FunctionType & function, VectorType & vector, const SpaceType & space, const GridViewType & grid_view, const Stuff::Grid::ApplyOn::WhichIntersection< typename SpaceType::GridViewType > * where)
template<class FunctionType , class VectorType , class SpaceType , class GridViewType > std::enable_if<Stuff::is_localizable_function<FunctionType>::value && Stuff::LA::is_vector<VectorType>::value && is_space<SpaceType>::value && Stuff::Grid::is_grid_layer<GridViewType>::value, std::unique_ptr<L2FaceVectorFunctional<FunctionType, SpaceType, VectorType, GridViewType> > >::type Dune::GDT::make_l2_face_vector_functional (const FunctionType & function, VectorType & vector, const SpaceType & space, const GridViewType & grid_view, const size_t over_integrate, const Stuff::Grid::ApplyOn::WhichIntersection< typename SpaceType::GridViewType > * where)
template<class GridViewType , class RangeType , class SourceType > std::enable_if<Stuff::Grid::is_grid_layer<GridViewType>::value && Stuff::is_localizable_function<RangeType>::value && Stuff::is_localizable_function<SourceType>::value, std::unique_ptr<L2LocalizableProduct<GridViewType, RangeType, SourceType> > >::type Dune::GDT::make_l2_localizable_product (const GridViewType & grid_view, const RangeType & range, const SourceType & source, const size_t over_integrate = 0)
See Also
L2LocalizableProduct
Referenced by Dune::GDT::L2Operator< GridView, Field >::apply2().
template<class MatrixType , class SpaceType > std::enable_if<Stuff::LA::is_matrix<MatrixType>::value && is_space<SpaceType>::value, std::unique_ptr<L2MatrixOperator<SpaceType, MatrixType> > >::type Dune::GDT::make_l2_matrix_operator (const SpaceType & space, const size_t over_integrate = 0)
Creates an L2 matrix operator (MatrixType has to be supllied, a matrix is created automatically, source and range space are given by space, grid_view of the space is used).
Note
MatrixType has to be supplied, i.e., use like
auto op = make_l2_matrix_operator< MatrixType >(space);
template<class MatrixType , class SpaceType , class GridViewType > std::enable_if<Stuff::LA::is_matrix<MatrixType>::value && is_space<SpaceType>::value && Stuff::Grid::is_grid_layer<GridViewType>::value, std::unique_ptr<L2MatrixOperator<SpaceType, MatrixType, GridViewType> > >::type Dune::GDT::make_l2_matrix_operator (const SpaceType & space, const GridViewType & grid_view, const size_t over_integrate = 0)
Creates an L2 matrix operator (MatrixType has to be supllied, a matrix is created automatically, source and range space are given by space).
Note
MatrixType has to be supplied, i.e., use like
auto op = make_l2_matrix_operator< MatrixType >(space, grid_view);
template<class MatrixType , class RangeSpaceType , class SourceSpaceType , class GridViewType > std::enable_if<Stuff::LA::is_matrix<MatrixType>::value && is_space<RangeSpaceType>::value && is_space<SourceSpaceType>::value && Stuff::Grid::is_grid_layer<GridViewType>::value, std::unique_ptr<L2MatrixOperator<RangeSpaceType, MatrixType, GridViewType, SourceSpaceType> > >:: type Dune::GDT::make_l2_matrix_operator (const RangeSpaceType & range_space, const SourceSpaceType & source_space, const GridViewType & grid_view, const size_t over_integrate = 0)
Creates an L2 matrix operator (MatrixType has to be supllied, a matrix is created automatically).
Note
MatrixType has to be supplied, i.e., use like
auto op = make_l2_matrix_operator< MatrixType >(range_space, source_space, grid_view);
template<class MatrixType , class SpaceType > std::enable_if<Stuff::LA::is_matrix<MatrixType>::value && is_space<SpaceType>::value, std::unique_ptr<L2MatrixOperator<SpaceType, MatrixType> > >::type Dune::GDT::make_l2_matrix_operator (MatrixType & matrix, const SpaceType & space, const size_t over_integrate = 0)
Creates an L2 matrix operator (source and range space are given by space, grid_view of the space is used).
template<class MatrixType , class SpaceType , class GridViewType > std::enable_if<Stuff::LA::is_matrix<MatrixType>::value && is_space<SpaceType>::value && Stuff::Grid::is_grid_layer<GridViewType>::value, std::unique_ptr<L2MatrixOperator<SpaceType, MatrixType, GridViewType> > >::type Dune::GDT::make_l2_matrix_operator (MatrixType & matrix, const SpaceType & space, const GridViewType & grid_view, const size_t over_integrate = 0)
Creates an L2 matrix operator (source and range space are given by space).
template<class MatrixType , class RangeSpaceType , class SourceSpaceType , class GridViewType > std::enable_if<Stuff::LA::is_matrix<MatrixType>::value && is_space<RangeSpaceType>::value && is_space<SourceSpaceType>::value && Stuff::Grid::is_grid_layer<GridViewType>::value, std::unique_ptr<L2MatrixOperator<RangeSpaceType, MatrixType, GridViewType, SourceSpaceType> > >:: type Dune::GDT::make_l2_matrix_operator (MatrixType & matrix, const RangeSpaceType & range_space, const SourceSpaceType & source_space, const GridViewType & grid_view, const size_t over_integrate = 0)
Creates an L2 matrix operator.
template<class GridViewType > std::enable_if<Stuff::Grid::is_grid_layer<GridViewType>::value, std::unique_ptr<L2Operator<GridViewType> > >::type Dune::GDT::make_l2_operator (const GridViewType & grid_view, const size_t over_integrate = 0)
template<class GridViewType , class SourceType , class SpaceType , class VectorType > std::enable_if<Stuff::Grid::is_grid_layer<GridViewType>::value && Stuff::is_localizable_function<SourceType>::value && is_space<SpaceType>::value && Stuff::LA::is_vector<VectorType>::value, std::unique_ptr<L2ProjectionLocalizableOperator<GridViewType, SourceType, DiscreteFunction<SpaceType, VectorType> > > >::type Dune::GDT::make_l2_projection_localizable_operator (const GridViewType & grid_view, const SourceType & source, DiscreteFunction< SpaceType, VectorType > & range, const size_t over_integrate = 0)
template<class SourceType , class SpaceType , class VectorType > std::enable_if<Stuff::is_localizable_function<SourceType>::value && is_space<SpaceType>::value && Stuff::LA::is_vector<VectorType>::value, std::unique_ptr<L2ProjectionLocalizableOperator<typename SpaceType::GridViewType, SourceType, DiscreteFunction<SpaceType, VectorType> > > >::type Dune::GDT::make_l2_projection_localizable_operator (const SourceType & source, DiscreteFunction< SpaceType, VectorType > & range, const size_t over_integrate = 0)
References Dune::GDT::ConstDiscreteFunction< SpaceImp, VectorImp >::space().
template<class GridViewType > std::enable_if<Stuff::Grid::is_grid_layer<GridViewType>::value, std::unique_ptr<L2ProjectionOperator<GridViewType> > >::type Dune::GDT::make_l2_projection_operator (const GridViewType & grid_view, const size_t over_integrate = 0)
Referenced by project_l2().
template<class GridViewType , class SS , class SV , class RS , class RV > std::enable_if<Stuff::Grid::is_grid_layer<GridViewType>::value, std::unique_ptr<L2ProlongationLocalizableOperator<GridViewType, ConstDiscreteFunction<SS, SV>, DiscreteFunction<RS, RV> > > >::type Dune::GDT::make_l2_prolongation_localizable_operator (const GridViewType & grid_view, const ConstDiscreteFunction< SS, SV > & source, DiscreteFunction< RS, RV > & range, const size_t over_integrate = 0)
template<class SS , class SV , class RS , class RV > std::unique_ptr<L2ProlongationLocalizableOperator<typename RS::GridViewType, ConstDiscreteFunction<SS, SV>, DiscreteFunction<RS, RV> > > Dune::GDT::make_l2_prolongation_localizable_operator (const ConstDiscreteFunction< SS, SV > & source, DiscreteFunction< RS, RV > & range, const size_t over_integrate = 0)
References Dune::GDT::ConstDiscreteFunction< SpaceImp, VectorImp >::space().
template<class GridViewType > std::enable_if<Stuff::Grid::is_grid_layer<GridViewType>::value, std::unique_ptr<L2ProlongationOperator<GridViewType> > >::type Dune::GDT::make_l2_prolongation_operator (const GridViewType & grid_view, const size_t over_integrate = 0)
Referenced by prolong_l2().
template<class VectorType , class FunctionType , class SpaceType > std::enable_if<Stuff::LA::is_vector<VectorType>::value && Stuff::is_localizable_function<FunctionType>::value && is_space<SpaceType>::value, std::unique_ptr<L2VolumeVectorFunctional<FunctionType, SpaceType, VectorType> > >::type Dune::GDT::make_l2_volume_vector_functional (const FunctionType & function, const SpaceType & space, const size_t over_integrate = 0)
template<class VectorType , class FunctionType , class SpaceType , class GridViewType > std::enable_if<Stuff::LA::is_vector<VectorType>::value && Stuff::is_localizable_function<FunctionType>::value && is_space<SpaceType>::value && Stuff::Grid::is_grid_layer<GridViewType>::value, std::unique_ptr<L2VolumeVectorFunctional<FunctionType, SpaceType, VectorType, GridViewType> > >:: type Dune::GDT::make_l2_volume_vector_functional (const FunctionType & function, const SpaceType & space, const GridViewType & grid_view, const size_t over_integrate = 0)
template<class FunctionType , class VectorType , class SpaceType > std::enable_if<Stuff::is_localizable_function<FunctionType>::value && Stuff::LA::is_vector<VectorType>::value && is_space<SpaceType>::value, std::unique_ptr<L2VolumeVectorFunctional<FunctionType, SpaceType, VectorType> > >::type Dune::GDT::make_l2_volume_vector_functional (const FunctionType & function, VectorType & vector, const SpaceType & space, const size_t over_integrate = 0)
template<class FunctionType , class VectorType , class SpaceType , class GridViewType > std::enable_if<Stuff::is_localizable_function<FunctionType>::value && Stuff::LA::is_vector<VectorType>::value && is_space<SpaceType>::value && Stuff::Grid::is_grid_layer<GridViewType>::value, std::unique_ptr<L2VolumeVectorFunctional<FunctionType, SpaceType, VectorType, GridViewType> > >:: type Dune::GDT::make_l2_volume_vector_functional (const FunctionType & function, VectorType & vector, const SpaceType & space, const GridViewType & grid_view, const size_t over_integrate = 0)
template<class GridViewType , class SourceType , class SpaceType , class VectorType > std:: enable_if<Stuff::Grid::is_grid_layer<GridViewType>::value && Stuff::is_localizable_function<SourceType>::value && is_space<SpaceType>::value && Stuff::LA::is_vector<VectorType>::value, std::unique_ptr<LagrangeProjectionLocalizableOperator<GridViewType, SourceType, DiscreteFunction<SpaceType, VectorType> > > >::type Dune::GDT::make_lagrange_projection_localizable_operator (const GridViewType & grid_view, const SourceType & source, DiscreteFunction< SpaceType, VectorType > & range)
Referenced by Dune::GDT::LagrangeProjectionOperator< GridViewImp, FieldImp >::apply().
template<class SourceType , class SpaceType , class VectorType > std:: enable_if<Stuff::is_localizable_function<SourceType>::value && is_space<SpaceType>::value && Stuff::LA::is_vector<VectorType>::value, std::unique_ptr<LagrangeProjectionLocalizableOperator<typename SpaceType::GridViewType, SourceType, DiscreteFunction<SpaceType, VectorType> > > >::type Dune::GDT::make_lagrange_projection_localizable_operator (const SourceType & source, DiscreteFunction< SpaceType, VectorType > & range)
References Dune::GDT::ConstDiscreteFunction< SpaceImp, VectorImp >::space().
template<class GridViewType > std::enable_if<Stuff::Grid::is_grid_layer<GridViewType>::value, std::unique_ptr<LagrangeProjectionOperator<GridViewType> > >::type Dune::GDT::make_lagrange_projection_operator (const GridViewType & grid_view)
Referenced by project_lagrange().
template<class GridViewType , class SourceSpaceType , class SourceVectorType , class RangeSpaceType , class RangeVectorType > std::enable_if<Stuff::Grid::is_grid_layer<GridViewType>::value, std::unique_ptr<LagrangeProlongationLocalizableOperator<GridViewType, ConstDiscreteFunction<SourceSpaceType, SourceVectorType>, DiscreteFunction<RangeSpaceType, RangeVectorType> > > >:: type Dune::GDT::make_lagrange_prolongation_localizable_operator (const GridViewType & grid_view, const ConstDiscreteFunction< SourceSpaceType, SourceVectorType > & source, DiscreteFunction< RangeSpaceType, RangeVectorType > & range)
template<class SourceSpaceType , class SourceVectorType , class RangeSpaceType , class RangeVectorType > std::unique_ptr<LagrangeProlongationLocalizableOperator<typename RangeSpaceType::GridViewType, ConstDiscreteFunction<SourceSpaceType, SourceVectorType>, DiscreteFunction<RangeSpaceType, RangeVectorType> > > Dune::GDT::make_lagrange_prolongation_localizable_operator (const ConstDiscreteFunction< SourceSpaceType, SourceVectorType > & source, DiscreteFunction< RangeSpaceType, RangeVectorType > & range)
References Dune::GDT::ConstDiscreteFunction< SpaceImp, VectorImp >::space().
template<class GridViewType > std::enable_if<Stuff::Grid::is_grid_layer<GridViewType>::value, std::unique_ptr<LagrangeProlongationOperator<GridViewType> > >::type Dune::GDT::make_lagrange_prolongation_operator (const GridViewType & grid_view)
Referenced by prolong_lagrange().
template<class GridViewType , class RangeType , class SourceType > std::enable_if<Stuff::Grid::is_grid_layer<GridViewType>::value && Stuff::is_localizable_function<RangeType>::value && Stuff::is_localizable_function<SourceType>::value, std::unique_ptr<LaplaceLocalizableProduct<GridViewType, RangeType, SourceType> > >::type Dune::GDT::make_laplace_localizable_product (const GridViewType & grid_view, const RangeType & range, const SourceType & source, const size_t over_integrate = 0)
See Also
LaplaceLocalizableProduct
Referenced by Dune::GDT::LaplaceOperator< GridView, Field >::apply2().
template<class MatrixType , class SpaceType > std::enable_if<Stuff::LA::is_matrix<MatrixType>::value && is_space<SpaceType>::value, std::unique_ptr<LaplaceMatrixOperator<SpaceType, MatrixType> > >::type Dune::GDT::make_laplace_matrix_operator (const SpaceType & space, const size_t over_integrate = 0)
Creates a Laplace matrix operator (MatrixType has to be supllied, a matrix is created automatically, source and range space are given by space, grid_view of the space is used).
Note
MatrixType has to be supplied, i.e., use like
auto op = make_laplace_matrix_operator< MatrixType >(space);
template<class MatrixType , class SpaceType , class GridViewType > std::enable_if<Stuff::LA::is_matrix<MatrixType>::value && is_space<SpaceType>::value && Stuff::Grid::is_grid_layer<GridViewType>::value, std::unique_ptr<LaplaceMatrixOperator<SpaceType, MatrixType, GridViewType> > >::type Dune::GDT::make_laplace_matrix_operator (const SpaceType & space, const GridViewType & grid_view, const size_t over_integrate = 0)
Creates a Laplace matrix operator (MatrixType has to be supllied, a matrix is created automatically, source and range space are given by space).
Note
MatrixType has to be supplied, i.e., use like
auto op = make_laplace_matrix_operator< MatrixType >(space, grid_view);
template<class MatrixType , class RangeSpaceType , class SourceSpaceType , class GridViewType > std:: enable_if<Stuff::LA::is_matrix<MatrixType>::value && is_space<RangeSpaceType>::value && is_space<SourceSpaceType>::value && Stuff::Grid::is_grid_layer<GridViewType>::value, std::unique_ptr<LaplaceMatrixOperator<RangeSpaceType, MatrixType, GridViewType, SourceSpaceType> > >::type Dune::GDT::make_laplace_matrix_operator (const RangeSpaceType & range_space, const SourceSpaceType & source_space, const GridViewType & grid_view, const size_t over_integrate = 0)
Creates a Laplace matrix operator (MatrixType has to be supllied, a matrix is created automatically).
Note
MatrixType has to be supplied, i.e., use like
auto op = make_laplace_matrix_operator< MatrixType >(range_space, source_space, grid_view);
template<class MatrixType , class SpaceType > std::enable_if<Stuff::LA::is_matrix<MatrixType>::value && is_space<SpaceType>::value, std::unique_ptr<LaplaceMatrixOperator<SpaceType, MatrixType> > >::type Dune::GDT::make_laplace_matrix_operator (MatrixType & matrix, const SpaceType & space, const size_t over_integrate = 0)
Creates a Laplace matrix operator (source and range space are given by space, grid_view of the space is used).
template<class MatrixType , class SpaceType , class GridViewType > std::enable_if<Stuff::LA::is_matrix<MatrixType>::value && is_space<SpaceType>::value && Stuff::Grid::is_grid_layer<GridViewType>::value, std::unique_ptr<LaplaceMatrixOperator<SpaceType, MatrixType, GridViewType> > >::type Dune::GDT::make_laplace_matrix_operator (MatrixType & matrix, const SpaceType & space, const GridViewType & grid_view, const size_t over_integrate = 0)
Creates a Laplace matrix operator (source and range space are given by space).
template<class MatrixType , class RangeSpaceType , class SourceSpaceType , class GridViewType > std:: enable_if<Stuff::LA::is_matrix<MatrixType>::value && is_space<RangeSpaceType>::value && is_space<SourceSpaceType>::value && Stuff::Grid::is_grid_layer<GridViewType>::value, std::unique_ptr<LaplaceMatrixOperator<RangeSpaceType, MatrixType, GridViewType, SourceSpaceType> > >::type Dune::GDT::make_laplace_matrix_operator (MatrixType & matrix, const RangeSpaceType & range_space, const SourceSpaceType & source_space, const GridViewType & grid_view, const size_t over_integrate = 0)
Creates a Laplace matrix operator.
template<class GridViewType > std::enable_if<Stuff::Grid::is_grid_layer<GridViewType>::value, std::unique_ptr<LaplaceOperator<GridViewType> > >::type Dune::GDT::make_laplace_operator (const GridViewType & grid_view, const size_t over_integrate = 0)
template<class GridViewType , class SourceType , class SpaceType , class VectorType > std:: enable_if<Stuff::Grid::is_grid_layer<GridViewType>::value && Stuff::is_localizable_function<SourceType>::value && is_space<SpaceType>::value && Stuff::LA::is_vector<VectorType>::value, std::unique_ptr<L2LocalProjectionLocalizableOperator<GridViewType, SourceType, DiscreteFunction<SpaceType, VectorType> > > >::type Dune::GDT::make_local_l2_projection_localizable_operator (const GridViewType & grid_view, const SourceType & source, DiscreteFunction< SpaceType, VectorType > & range, const size_t over_integrate = 0)
template<class SourceType , class SpaceType , class VectorType > std:: enable_if<Stuff::is_localizable_function<SourceType>::value && is_space<SpaceType>::value && Stuff::LA::is_vector<VectorType>::value, std::unique_ptr<L2LocalProjectionLocalizableOperator<typename SpaceType::GridViewType, SourceType, DiscreteFunction<SpaceType, VectorType> > > >::type Dune::GDT::make_local_l2_projection_localizable_operator (const SourceType & source, DiscreteFunction< SpaceType, VectorType > & range, const size_t over_integrate = 0)
References Dune::GDT::ConstDiscreteFunction< SpaceImp, VectorImp >::space().
template<class GridViewType > std::enable_if<Stuff::Grid::is_grid_layer<GridViewType>::value, std::unique_ptr<L2LocalProjectionOperator<GridViewType> > >::type Dune::GDT::make_local_l2_projection_operator (const GridViewType & grid_view, const size_t over_integrate = 0)
template<class GridViewType , class SourceSpaceType , class SourceVectorType , class RangeSpaceType , class RangeVectorType > std::enable_if<Stuff::Grid::is_grid_layer<GridViewType>::value && is_space<SourceSpaceType>::value && Stuff::LA::is_vector<SourceVectorType>::value && is_space<RangeSpaceType>::value && Stuff::LA::is_vector<RangeVectorType>::value, std::unique_ptr<L2LocalProlongationLocalizableOperator<GridViewType, ConstDiscreteFunction<SourceSpaceType, SourceVectorType>, DiscreteFunction<RangeSpaceType, RangeVectorType> > > >:: type Dune::GDT::make_local_l2_prolongation_localizable_operator (const GridViewType & grid_view, const ConstDiscreteFunction< SourceSpaceType, SourceVectorType > & source, DiscreteFunction< RangeSpaceType, RangeVectorType > & range, const size_t over_integrate = 0)
template<class SourceSpaceType , class SourceVectorType , class RangeSpaceType , class RangeVectorType > std::enable_if<is_space<SourceSpaceType>::value && Stuff::LA::is_vector<SourceVectorType>::value && is_space<RangeSpaceType>::value && Stuff::LA::is_vector<RangeVectorType>::value, std::unique_ptr<L2LocalProlongationLocalizableOperator< typename RangeSpaceType::GridViewType, ConstDiscreteFunction<SourceSpaceType, SourceVectorType>, DiscreteFunction<RangeSpaceType, RangeVectorType> > > >::type Dune::GDT::make_local_l2_prolongation_localizable_operator (const ConstDiscreteFunction< SourceSpaceType, SourceVectorType > & source, DiscreteFunction< RangeSpaceType, RangeVectorType > & range, const size_t over_integrate = 0)
References Dune::GDT::ConstDiscreteFunction< SpaceImp, VectorImp >::space().
template<class GridViewType > std::enable_if<Stuff::Grid::is_grid_layer<GridViewType>::value, std::unique_ptr<L2LocalProlongationOperator<GridViewType> > >::type Dune::GDT::make_local_l2_prolongation_operator (const GridViewType & grid_view, const size_t over_integrate = 0)
template<class GridViewType , class SourceType , class RangeType > std::unique_ptr<DirichletProjectionLocalizableOperator<GridViewType, SourceType, RangeType> > Dune::GDT::make_localizable_dirichlet_projection_operator (const GridViewType & grid_view, const Stuff::Grid::BoundaryInfoInterface< typename Stuff::Grid::Intersection< GridViewType >::Type > & boundary_info, const SourceType & source, RangeType & range)
template<class WeightFunctionType , class GridViewType , class RangeType , class SourceType > std::enable_if<Stuff::is_localizable_function<WeightFunctionType>::value && Stuff::Grid::is_grid_layer<GridViewType>::value && Stuff::is_localizable_function<RangeType>::value && Stuff::is_localizable_function<SourceType>::value, std::unique_ptr<WeightedL2LocalizableProduct<WeightFunctionType, GridViewType, RangeType, SourceType> > >::type Dune::GDT::make_weighted_l2_localizable_product (const WeightFunctionType & weight, const GridViewType & grid_view, const RangeType & range, const SourceType & source, const size_t over_integrate = 0)
See Also
WeightedL2LocalizableProduct
Referenced by Dune::GDT::WeightedL2Operator< WeightFunctionType, GridView, Field >::apply2().
template<class MatrixType , class WeightFunctionType , class SpaceType > std::enable_if<Stuff::LA::is_matrix<MatrixType>::value && Stuff::is_localizable_function<WeightFunctionType>::value && is_space<SpaceType>::value, std::unique_ptr<WeightedL2MatrixOperator<WeightFunctionType, SpaceType, MatrixType> > >::type Dune::GDT::make_weighted_l2_matrix_operator (const WeightFunctionType & weight, const SpaceType & space, const size_t over_integrate = 0)
Creates a weighted L2 matrix operator (MatrixType has to be supllied, a matrix is created automatically, source and range space are given by space, grid_view of the space is used).
Note
MatrixType has to be supplied, i.e., use like
auto op = make_weighted_l2_matrix_operator< MatrixType >(weight, space);
template<class MatrixType , class WeightFunctionType , class SpaceType , class GridViewType > std:: enable_if<Stuff::LA::is_matrix<MatrixType>::value && Stuff::is_localizable_function<WeightFunctionType>::value && is_space<SpaceType>::value && Stuff::Grid::is_grid_layer<GridViewType>::value, std::unique_ptr<WeightedL2MatrixOperator<WeightFunctionType, SpaceType, MatrixType, GridViewType> > >::type Dune::GDT::make_weighted_l2_matrix_operator (const WeightFunctionType & weight, const SpaceType & space, const GridViewType & grid_view, const size_t over_integrate = 0)
Creates a weighted L2 matrix operator (MatrixType has to be supllied, a matrix is created automatically, source and range space are given by space).
Note
MatrixType has to be supplied, i.e., use like
auto op = make_weighted_l2_matrix_operator< MatrixType >(weight, space, grid_view);
template<class MatrixType , class WeightFunctionType , class RangeSpaceType , class SourceSpaceType , class GridViewType > std::enable_if<Stuff::LA::is_matrix<MatrixType>::value && Stuff::is_localizable_function<WeightFunctionType>::value && is_space<RangeSpaceType>::value && is_space<SourceSpaceType>::value && Stuff::Grid::is_grid_layer<GridViewType>::value, std::unique_ptr<WeightedL2MatrixOperator<WeightFunctionType, RangeSpaceType, MatrixType, GridViewType, SourceSpaceType> > >::type Dune::GDT::make_weighted_l2_matrix_operator (const WeightFunctionType & weight, const RangeSpaceType & range_space, const SourceSpaceType & source_space, const GridViewType & grid_view, const size_t over_integrate = 0)
Creates a weighted L2 matrix operator (MatrixType has to be supllied, a matrix is created automatically).
Note
MatrixType has to be supplied, i.e., use like
auto op = make_weighted_l2_matrix_operator< MatrixType >(weight, range_space, source_space, grid_view);
template<class WeightFunctionType , class MatrixType , class SpaceType > std::enable_if<Stuff::is_localizable_function<WeightFunctionType>::value && Stuff::LA::is_matrix<MatrixType>::value && is_space<SpaceType>::value, std::unique_ptr<WeightedL2MatrixOperator<WeightFunctionType, SpaceType, MatrixType> > >::type Dune::GDT::make_weighted_l2_matrix_operator (const WeightFunctionType & weight, MatrixType & matrix, const SpaceType & space, const size_t over_integrate = 0)
Creates a weighted L2 matrix operator (source and range space are given by space, grid_view of the space is used).
template<class WeightFunctionType , class MatrixType , class SpaceType , class GridViewType > std:: enable_if<Stuff::is_localizable_function<WeightFunctionType>::value && Stuff::LA::is_matrix<MatrixType>::value && is_space<SpaceType>::value && Stuff::Grid::is_grid_layer<GridViewType>::value, std::unique_ptr<WeightedL2MatrixOperator<WeightFunctionType, SpaceType, MatrixType, GridViewType> > >::type Dune::GDT::make_weighted_l2_matrix_operator (const WeightFunctionType & weight, MatrixType & matrix, const SpaceType & space, const GridViewType & grid_view, const size_t over_integrate = 0)
Creates a weighted L2 matrix operator (source and range space are given by space).
template<class WeightFunctionType , class MatrixType , class RangeSpaceType , class SourceSpaceType , class GridViewType > std::enable_if<Stuff::is_localizable_function<WeightFunctionType>::value && Stuff::LA::is_matrix<MatrixType>::value && is_space<RangeSpaceType>::value && is_space<SourceSpaceType>::value && Stuff::Grid::is_grid_layer<GridViewType>::value, std::unique_ptr<WeightedL2MatrixOperator<WeightFunctionType, RangeSpaceType, MatrixType, GridViewType, SourceSpaceType> > >::type Dune::GDT::make_weighted_l2_matrix_operator (const WeightFunctionType & weight, MatrixType & matrix, const RangeSpaceType & range_space, const SourceSpaceType & source_space, const GridViewType & grid_view, const size_t over_integrate = 0)
Creates a weighted L2 matrix operator.
template<class GridViewType , class WeightFunctionType > std::enable_if<Stuff::is_localizable_function<WeightFunctionType>::value && Stuff::Grid::is_grid_layer<GridViewType>::value, std::unique_ptr<WeightedL2Operator<WeightFunctionType, GridViewType, typename WeightFunctionType::RangeFieldType> > >::type Dune::GDT::make_weighted_l2_operator (const GridViewType & grid_view, const WeightFunctionType & weight, const size_t over_integrate = 0)
template<class V > std::ostream& Dune::GDT::operator<< (std::ostream & out, const ConstLocalDoFVector< V > & vector)
template<class GridViewType , class SourceType , class SpaceType , class VectorType > std::enable_if<Stuff::Grid::is_grid_layer<GridViewType>::value && Stuff::is_localizable_function<SourceType>::value && is_cg_space<SpaceType>::value && Stuff::LA::is_vector<VectorType>::value, void>::type Dune::GDT::project (const GridViewType & grid_view, const SourceType & source, DiscreteFunction< SpaceType, VectorType > & range, const size_t = 0)
References project_lagrange().
Referenced by Dune::GDT::HyperbolicFVDefaultDiscretization< ProblemImp, FVSpaceImp, numerical_flux, time_stepper_method, rhs_time_stepper_method >::solve().
template<class GridViewType , class SourceType , class SpaceType , class VectorType > std::enable_if<Stuff::Grid::is_grid_layer<GridViewType>::value && Stuff::is_localizable_function<SourceType>::value && !is_cg_space<SpaceType>::value && Stuff::LA::is_vector<VectorType>::value, void>::type Dune::GDT::project (const GridViewType & grid_view, const SourceType & source, DiscreteFunction< SpaceType, VectorType > & range, const size_t over_integrate = 0)
References project_l2().
template<class SourceType , class SpaceType , class VectorType > std::enable_if<Stuff::is_localizable_function<SourceType>::value && is_cg_space<SpaceType>::value && Stuff::LA::is_vector<VectorType>::value, void>::type Dune::GDT::project (const SourceType & source, DiscreteFunction< SpaceType, VectorType > & range, const size_t = 0)
References project_lagrange().
template<class SourceType , class SpaceType , class VectorType > std::enable_if<Stuff::is_localizable_function<SourceType>::value && !is_cg_space<SpaceType>::value && Stuff::LA::is_vector<VectorType>::value, void>::type Dune::GDT::project (const SourceType & source, DiscreteFunction< SpaceType, VectorType > & range, const size_t over_integrate = 0)
References project_l2().
template<class GridViewType , class SourceType , class SpaceType , class VectorType > std::enable_if<Stuff::Grid::is_grid_layer<GridViewType>::value && Stuff::is_localizable_function<SourceType>::value && is_space<SpaceType>::value && Stuff::LA::is_vector<VectorType>::value, void>::type Dune::GDT::project_l2 (const GridViewType & grid_view, const SourceType & source, DiscreteFunction< SpaceType, VectorType > & range, const size_t over_integrate = 0)
References make_l2_projection_operator().
Referenced by project().
template<class SourceType , class SpaceType , class VectorType > std::enable_if<Stuff::is_localizable_function<SourceType>::value && is_space<SpaceType>::value && Stuff::LA::is_vector<VectorType>::value, void>::type Dune::GDT::project_l2 (const SourceType & source, DiscreteFunction< SpaceType, VectorType > & range, const size_t over_integrate = 0)
References make_l2_projection_operator(), and Dune::GDT::ConstDiscreteFunction< SpaceImp, VectorImp >::space().
template<class GridViewType , class SourceType , class SpaceType , class VectorType > std::enable_if<Stuff::Grid::is_grid_layer<GridViewType>::value && Stuff::is_localizable_function<SourceType>::value && is_space<SpaceType>::value && Stuff::LA::is_vector<VectorType>::value, void>::type Dune::GDT::project_lagrange (const GridViewType & grid_view, const SourceType & source, DiscreteFunction< SpaceType, VectorType > & range)
References make_lagrange_projection_operator().
Referenced by project().
template<class SourceType , class SpaceType , class VectorType > std::enable_if<Stuff::is_localizable_function<SourceType>::value && is_space<SpaceType>::value && Stuff::LA::is_vector<VectorType>::value, void>::type Dune::GDT::project_lagrange (const SourceType & source, DiscreteFunction< SpaceType, VectorType > & range)
References make_lagrange_projection_operator(), and Dune::GDT::ConstDiscreteFunction< SpaceImp, VectorImp >::space().
template<class GridViewType , class SourceSpaceType , class SourceVectorType , class RangeSpaceType , class RangeVectorType > std::enable_if<Stuff::Grid::is_grid_layer<GridViewType>::value && is_cg_space<RangeSpaceType>::value, void>::type Dune::GDT::prolong (const GridViewType & grid_view, const ConstDiscreteFunction< SourceSpaceType, SourceVectorType > & source, DiscreteFunction< RangeSpaceType, RangeVectorType > & range, const size_t = 0)
References prolong_lagrange().
template<class GridViewType , class SourceSpaceType , class SourceVectorType , class RangeSpaceType , class RangeVectorType > std::enable_if<Stuff::Grid::is_grid_layer<GridViewType>::value && !is_cg_space<RangeSpaceType>::value, void>::type Dune::GDT::prolong (const GridViewType & grid_view, const ConstDiscreteFunction< SourceSpaceType, SourceVectorType > & source, DiscreteFunction< RangeSpaceType, RangeVectorType > & range, const size_t over_integrate = 0)
References prolong_l2().
template<class SourceSpaceType , class SourceVectorType , class RangeSpaceType , class RangeVectorType > std::enable_if<is_cg_space<RangeSpaceType>::value, void>::type Dune::GDT::prolong (const ConstDiscreteFunction< SourceSpaceType, SourceVectorType > & source, DiscreteFunction< RangeSpaceType, RangeVectorType > & range, const size_t = 0)
References prolong_lagrange().
template<class SourceSpaceType , class SourceVectorType , class RangeSpaceType , class RangeVectorType > std::enable_if<!is_cg_space<RangeSpaceType>::value, void>::type Dune::GDT::prolong (const ConstDiscreteFunction< SourceSpaceType, SourceVectorType > & source, DiscreteFunction< RangeSpaceType, RangeVectorType > & range, const size_t over_integrate = 0)
References prolong_l2().
template<class GridViewType , class SS , class SV , class RS , class RV > std::enable_if<Stuff::Grid::is_grid_layer<GridViewType>::value, void>::type Dune::GDT::prolong_l2 (const GridViewType & grid_view, const ConstDiscreteFunction< SS, SV > & source, DiscreteFunction< RS, RV > & range, const size_t over_integrate = 0)
References make_l2_prolongation_operator().
Referenced by prolong().
template<class SS , class SV , class RS , class RV > void Dune::GDT::prolong_l2 (const ConstDiscreteFunction< SS, SV > & source, DiscreteFunction< RS, RV > & range, const size_t over_integrate = 0)
References make_l2_prolongation_operator(), and Dune::GDT::ConstDiscreteFunction< SpaceImp, VectorImp >::space().
template<class GridViewType , class SS , class SV , class RS , class RV > std::enable_if<Stuff::Grid::is_grid_layer<GridViewType>::value, void>::type Dune::GDT::prolong_lagrange (const GridViewType & grid_view, const ConstDiscreteFunction< SS, SV > & source, DiscreteFunction< RS, RV > & range)
References make_lagrange_prolongation_operator().
Referenced by prolong().
template<class SS , class SV , class RS , class RV > void Dune::GDT::prolong_lagrange (const ConstDiscreteFunction< SS, SV > & source, DiscreteFunction< RS, RV > & range)
References make_lagrange_prolongation_operator(), and Dune::GDT::ConstDiscreteFunction< SpaceImp, VectorImp >::space().
Variable Documentation
constexpr ChooseSpaceBackend Dune::GDT::default_cg_backend = default_space_backend static
constexpr ChooseSpaceBackend Dune::GDT::default_dg_backend = default_space_backend static
constexpr ChooseSpaceBackend Dune::GDT::default_space_backend static
Initial value:
=
    ChooseSpaceBackend::gdt