´´These methods are provided by the interface for convenience.''
´´These methods are provided by the interface for convenience.''
´´These methods have to be implemented!''
Functions
std::vector< DomainType > Dune::GDT::CgSpaceInterface< ImpTraits, domainDim, rangeDim, rangeDimCols >::lagrange_points_order_1 (const EntityType &entity) const
std::set< size_t > Dune::GDT::CgSpaceInterface< ImpTraits, domainDim, rangeDim, rangeDimCols >::local_dirichlet_DoFs_order_1 (const EntityType &entity, const BoundaryInfoType &boundaryInfo) const
std::set< size_t > Dune::GDT::CgSpaceInterface< ImpTraits, domainDim, rangeDim, rangeDimCols >::local_dirichlet_DoFs_simplicial_lagrange_elements (const EntityType &entity, const BoundaryInfoType &boundaryInfo) const
template<class G , class S , size_t d, size_t r, size_t rC>
PatternType Dune::GDT::CgSpaceInterface< ImpTraits, domainDim, rangeDim, rangeDimCols >::compute_pattern (const GridView< G > &local_grid_view, const SpaceInterface< S, d, r, rC > &ansatz_space) const
template<class S , size_t d, size_t r, size_t rC, class ConstraintsType >
void Dune::GDT::CgSpaceInterface< ImpTraits, domainDim, rangeDim, rangeDimCols >::local_constraints (const SpaceInterface< S, d, r, rC > &, const EntityType &, ConstraintsType &) const
template<class S , size_t d, size_t r, size_t rC>
void Dune::GDT::CgSpaceInterface< ImpTraits, domainDim, rangeDim, rangeDimCols >::local_constraints (const SpaceInterface< S, d, r, rC > &, const EntityType &entity, DirichletConstraints< IntersectionType > &ret) const
PatternType Dune::GDT::SpaceInterface< Traits, domainDim, rangeDim, rangeDimCols >::compute_pattern () const
template<class S , size_t d, size_t r, size_t rC>
PatternType Dune::GDT::SpaceInterface< Traits, domainDim, rangeDim, rangeDimCols >::compute_pattern (const SpaceInterface< S, d, r, rC > &ansatz_space) const
template<class G >
PatternType Dune::GDT::SpaceInterface< Traits, domainDim, rangeDim, rangeDimCols >::compute_pattern (const GridView< G > &local_grid_view) const
PatternType Dune::GDT::SpaceInterface< Traits, domainDim, rangeDim, rangeDimCols >::compute_volume_pattern () const
template<class S , size_t d, size_t r, size_t rC>
PatternType Dune::GDT::SpaceInterface< Traits, domainDim, rangeDim, rangeDimCols >::compute_volume_pattern (const SpaceInterface< S, d, r, rC > &ansatz_space) const
template<class G >
PatternType Dune::GDT::SpaceInterface< Traits, domainDim, rangeDim, rangeDimCols >::compute_volume_pattern (const GridView< G > &local_grid_view) const
template<class G , class S , size_t d, size_t r, size_t rC>
PatternType Dune::GDT::SpaceInterface< Traits, domainDim, rangeDim, rangeDimCols >::compute_volume_pattern (const GridView< G > &local_grid_view, const SpaceInterface< S, d, r, rC > &ansatz_space) const
computes a sparsity pattern, where this space is the test space (rows/outer) and the other space is the ansatz space (cols/inner)
PatternType Dune::GDT::SpaceInterface< Traits, domainDim, rangeDim, rangeDimCols >::compute_face_and_volume_pattern () const
template<class G >
PatternType Dune::GDT::SpaceInterface< Traits, domainDim, rangeDim, rangeDimCols >::compute_face_and_volume_pattern (const GridView< G > &local_grid_view) const
template<class S , size_t d, size_t r, size_t rC>
PatternType Dune::GDT::SpaceInterface< Traits, domainDim, rangeDim, rangeDimCols >::compute_face_and_volume_pattern (const SpaceInterface< S, d, r, rC > &ansatz_space) const
template<class G , class S , size_t d, size_t r, size_t rC>
PatternType Dune::GDT::SpaceInterface< Traits, domainDim, rangeDim, rangeDimCols >::compute_face_and_volume_pattern (const GridView< G > &local_grid_view, const SpaceInterface< S, d, r, rC > &ansatz_space) const
computes a DG sparsity pattern, where this space is the test space (rows/outer) and the other space is the ansatz space (cols/inner)
PatternType Dune::GDT::SpaceInterface< Traits, domainDim, rangeDim, rangeDimCols >::compute_face_pattern () const
template<class G >
PatternType Dune::GDT::SpaceInterface< Traits, domainDim, rangeDim, rangeDimCols >::compute_face_pattern (const GridView< G > &local_grid_view) const
template<class S , size_t d, size_t r, size_t rC>
PatternType Dune::GDT::SpaceInterface< Traits, domainDim, rangeDim, rangeDimCols >::compute_face_pattern (const SpaceInterface< S, d, r, rC > &ansatz_space) const
template<class G , class S , size_t d, size_t r, size_t rC>
PatternType Dune::GDT::SpaceInterface< Traits, domainDim, rangeDim, rangeDimCols >::compute_face_pattern (const G &local_grid_view, const SpaceInterface< S, d, r, rC > &ansatz_space) const
void Dune::GDT::SpaceInterface< Traits, domainDim, rangeDim, rangeDimCols >::visualize (const std::string filename_prefix="") const
std::vector< size_t > Dune::GDT::RtSpaceInterface< ImpTraits, domainDim, rangeDim, rangeDimCols >::local_DoF_indices_2dsimplex_order0 (const EntityType &entity) const
template<class G , class S , size_t d, size_t r, size_t rC>
PatternType Dune::GDT::RtSpaceInterface< ImpTraits, domainDim, rangeDim, rangeDimCols >::compute_pattern (const GridView< G > &local_grid_view, const SpaceInterface< S, d, r, rC > &ansatz_space) const
template<class S , size_t d, size_t r, size_t rC, class C , class R >
void Dune::GDT::RtSpaceInterface< ImpTraits, domainDim, rangeDim, rangeDimCols >::local_constraints (const SpaceInterface< S, d, r, rC > &, const EntityType &, ConstraintsInterface< C > &) const
Detailed Description
Function Documentation
template<class Traits, size_t domainDim, size_t rangeDim, size_t rangeDimCols = 1> PatternType Dune::GDT::SpaceInterface< Traits, domainDim, rangeDim, rangeDimCols >::compute_face_and_volume_pattern () const inline
Referenced by Dune::GDT::SpaceInterface< internal::DefaultProductSpaceTraits< SpaceImps...>, std::tuple_element< 0, std::tuple< SpaceImps...> >::type::dimDomain, GDT::BaseFunctionSet::internal::SumDimRange< SpaceImps...>::dimRange, 1 >::compute_face_and_volume_pattern(), and Dune::GDT::FvSpaceInterface< internal::FvProductSpaceTraits< GridViewImp, RangeFieldImp, rangeDim, 1 >, GridViewImp::dimension, rangeDim, 1 >::compute_pattern().
template<class Traits, size_t domainDim, size_t rangeDim, size_t rangeDimCols = 1> template<class G > PatternType Dune::GDT::SpaceInterface< Traits, domainDim, rangeDim, rangeDimCols >::compute_face_and_volume_pattern (const GridView< G > & local_grid_view) const inline
template<class Traits, size_t domainDim, size_t rangeDim, size_t rangeDimCols = 1> template<class S , size_t d, size_t r, size_t rC> PatternType Dune::GDT::SpaceInterface< Traits, domainDim, rangeDim, rangeDimCols >::compute_face_and_volume_pattern (const SpaceInterface< S, d, r, rC > & ansatz_space) const inline
template<class Traits, size_t domainDim, size_t rangeDim, size_t rangeDimCols = 1> template<class G , class S , size_t d, size_t r, size_t rC> PatternType Dune::GDT::SpaceInterface< Traits, domainDim, rangeDim, rangeDimCols >::compute_face_and_volume_pattern (const GridView< G > & local_grid_view, const SpaceInterface< S, d, r, rC > & ansatz_space) const inline
computes a DG sparsity pattern, where this space is the test space (rows/outer) and the other space is the ansatz space (cols/inner)
template<class Traits, size_t domainDim, size_t rangeDim, size_t rangeDimCols = 1> PatternType Dune::GDT::SpaceInterface< Traits, domainDim, rangeDim, rangeDimCols >::compute_face_pattern () const inline
Referenced by Dune::GDT::SpaceInterface< internal::DefaultProductSpaceTraits< SpaceImps...>, std::tuple_element< 0, std::tuple< SpaceImps...> >::type::dimDomain, GDT::BaseFunctionSet::internal::SumDimRange< SpaceImps...>::dimRange, 1 >::compute_face_pattern().
template<class Traits, size_t domainDim, size_t rangeDim, size_t rangeDimCols = 1> template<class G > PatternType Dune::GDT::SpaceInterface< Traits, domainDim, rangeDim, rangeDimCols >::compute_face_pattern (const GridView< G > & local_grid_view) const inline
template<class Traits, size_t domainDim, size_t rangeDim, size_t rangeDimCols = 1> template<class S , size_t d, size_t r, size_t rC> PatternType Dune::GDT::SpaceInterface< Traits, domainDim, rangeDim, rangeDimCols >::compute_face_pattern (const SpaceInterface< S, d, r, rC > & ansatz_space) const inline
template<class Traits, size_t domainDim, size_t rangeDim, size_t rangeDimCols = 1> template<class G , class S , size_t d, size_t r, size_t rC> PatternType Dune::GDT::SpaceInterface< Traits, domainDim, rangeDim, rangeDimCols >::compute_face_pattern (const G & local_grid_view, const SpaceInterface< S, d, r, rC > & ansatz_space) const inline
template<class ImpTraits , size_t domainDim, size_t rangeDim, size_t rangeDimCols = 1> template<class G , class S , size_t d, size_t r, size_t rC> PatternType Dune::GDT::RtSpaceInterface< ImpTraits, domainDim, rangeDim, rangeDimCols >::compute_pattern (const GridView< G > & local_grid_view, const SpaceInterface< S, d, r, rC > & ansatz_space) const inline
References Dune::GDT::SpaceInterface< ImpTraits, domainDim, rangeDim, rangeDimCols >::compute_face_and_volume_pattern().
template<class Traits, size_t domainDim, size_t rangeDim, size_t rangeDimCols = 1> PatternType Dune::GDT::SpaceInterface< Traits, domainDim, rangeDim, rangeDimCols >::compute_pattern () const inline
Referenced by Dune::GDT::SpaceInterface< internal::DefaultProductSpaceTraits< SpaceImps...>, std::tuple_element< 0, std::tuple< SpaceImps...> >::type::dimDomain, GDT::BaseFunctionSet::internal::SumDimRange< SpaceImps...>::dimRange, 1 >::compute_pattern().
template<class Traits, size_t domainDim, size_t rangeDim, size_t rangeDimCols = 1> template<class S , size_t d, size_t r, size_t rC> PatternType Dune::GDT::SpaceInterface< Traits, domainDim, rangeDim, rangeDimCols >::compute_pattern (const SpaceInterface< S, d, r, rC > & ansatz_space) const inline
template<class Traits, size_t domainDim, size_t rangeDim, size_t rangeDimCols = 1> template<class G > PatternType Dune::GDT::SpaceInterface< Traits, domainDim, rangeDim, rangeDimCols >::compute_pattern (const GridView< G > & local_grid_view) const inline
template<class ImpTraits , size_t domainDim, size_t rangeDim, size_t rangeDimCols = 1> template<class G , class S , size_t d, size_t r, size_t rC> PatternType Dune::GDT::CgSpaceInterface< ImpTraits, domainDim, rangeDim, rangeDimCols >::compute_pattern (const GridView< G > & local_grid_view, const SpaceInterface< S, d, r, rC > & ansatz_space) const inline
References Dune::GDT::SpaceInterface< ImpTraits, domainDim, rangeDim, rangeDimCols >::compute_volume_pattern().
template<class Traits, size_t domainDim, size_t rangeDim, size_t rangeDimCols = 1> PatternType Dune::GDT::SpaceInterface< Traits, domainDim, rangeDim, rangeDimCols >::compute_volume_pattern () const inline
Referenced by Dune::GDT::SpaceInterface< internal::DefaultProductSpaceTraits< SpaceImps...>, std::tuple_element< 0, std::tuple< SpaceImps...> >::type::dimDomain, GDT::BaseFunctionSet::internal::SumDimRange< SpaceImps...>::dimRange, 1 >::compute_volume_pattern().
template<class Traits, size_t domainDim, size_t rangeDim, size_t rangeDimCols = 1> template<class S , size_t d, size_t r, size_t rC> PatternType Dune::GDT::SpaceInterface< Traits, domainDim, rangeDim, rangeDimCols >::compute_volume_pattern (const SpaceInterface< S, d, r, rC > & ansatz_space) const inline
template<class Traits, size_t domainDim, size_t rangeDim, size_t rangeDimCols = 1> template<class G > PatternType Dune::GDT::SpaceInterface< Traits, domainDim, rangeDim, rangeDimCols >::compute_volume_pattern (const GridView< G > & local_grid_view) const inline
template<class Traits, size_t domainDim, size_t rangeDim, size_t rangeDimCols = 1> template<class G , class S , size_t d, size_t r, size_t rC> PatternType Dune::GDT::SpaceInterface< Traits, domainDim, rangeDim, rangeDimCols >::compute_volume_pattern (const GridView< G > & local_grid_view, const SpaceInterface< S, d, r, rC > & ansatz_space) const inline
computes a sparsity pattern, where this space is the test space (rows/outer) and the other space is the ansatz space (cols/inner)
template<class ImpTraits , size_t domainDim, size_t rangeDim, size_t rangeDimCols = 1> std::vector<DomainType> Dune::GDT::CgSpaceInterface< ImpTraits, domainDim, rangeDim, rangeDimCols >::lagrange_points_order_1 (const EntityType & entity) const inline
References Dune::GDT::SpaceInterface< ImpTraits, domainDim, rangeDim, rangeDimCols >::base_function_set(), Dune::GDT::SpaceInterface< ImpTraits, domainDim, rangeDim, rangeDimCols >::dimDomain, Dune::GDT::SpaceInterface< ImpTraits, domainDim, rangeDim, rangeDimCols >::dimRange, Dune::GDT::SpaceInterface< ImpTraits, domainDim, rangeDim, rangeDimCols >::grid_view(), and Dune::GDT::SpaceInterface< ImpTraits, domainDim, rangeDim, rangeDimCols >::polOrder.
template<class ImpTraits , size_t domainDim, size_t rangeDim, size_t rangeDimCols = 1> template<class S , size_t d, size_t r, size_t rC, class C , class R > void Dune::GDT::RtSpaceInterface< ImpTraits, domainDim, rangeDim, rangeDimCols >::local_constraints (const SpaceInterface< S, d, r, rC > & , const EntityType & , ConstraintsInterface< C > &) const inline
template<class ImpTraits , size_t domainDim, size_t rangeDim, size_t rangeDimCols = 1> template<class S , size_t d, size_t r, size_t rC, class ConstraintsType > void Dune::GDT::CgSpaceInterface< ImpTraits, domainDim, rangeDim, rangeDimCols >::local_constraints (const SpaceInterface< S, d, r, rC > & , const EntityType & , ConstraintsType &) const inline
template<class ImpTraits , size_t domainDim, size_t rangeDim, size_t rangeDimCols = 1> template<class S , size_t d, size_t r, size_t rC> void Dune::GDT::CgSpaceInterface< ImpTraits, domainDim, rangeDim, rangeDimCols >::local_constraints (const SpaceInterface< S, d, r, rC > & , const EntityType & entity, DirichletConstraints< IntersectionType > & ret) const inline
References Dune::GDT::DirichletConstraints< IntersectionType >::boundary_info(), Dune::GDT::DirichletConstraints< IntersectionType >::insert(), Dune::GDT::CgSpaceInterface< ImpTraits, domainDim, rangeDim, rangeDimCols >::local_dirichlet_DoFs(), and Dune::GDT::SpaceInterface< ImpTraits, domainDim, rangeDim, rangeDimCols >::mapper().
template<class ImpTraits , size_t domainDim, size_t rangeDim, size_t rangeDimCols = 1> std::set<size_t> Dune::GDT::CgSpaceInterface< ImpTraits, domainDim, rangeDim, rangeDimCols >::local_dirichlet_DoFs_order_1 (const EntityType & entity, const BoundaryInfoType & boundaryInfo) const inline
References Dune::GDT::SpaceInterface< ImpTraits, domainDim, rangeDim, rangeDimCols >::base_function_set(), Dune::GDT::SpaceInterface< ImpTraits, domainDim, rangeDim, rangeDimCols >::dimRange, Dune::GDT::SpaceInterface< ImpTraits, domainDim, rangeDim, rangeDimCols >::grid_view(), and Dune::GDT::SpaceInterface< ImpTraits, domainDim, rangeDim, rangeDimCols >::polOrder.
template<class ImpTraits , size_t domainDim, size_t rangeDim, size_t rangeDimCols = 1> std::set<size_t> Dune::GDT::CgSpaceInterface< ImpTraits, domainDim, rangeDim, rangeDimCols >::local_dirichlet_DoFs_simplicial_lagrange_elements (const EntityType & entity, const BoundaryInfoType & boundaryInfo) const inline
References Dune::GDT::SpaceInterface< ImpTraits, domainDim, rangeDim, rangeDimCols >::base_function_set(), Dune::GDT::SpaceInterface< ImpTraits, domainDim, rangeDim, rangeDimCols >::dimRange, Dune::GDT::SpaceInterface< ImpTraits, domainDim, rangeDim, rangeDimCols >::grid_view(), and Dune::GDT::SpaceInterface< ImpTraits, domainDim, rangeDim, rangeDimCols >::polOrder.
template<class ImpTraits , size_t domainDim, size_t rangeDim, size_t rangeDimCols = 1> std::vector<size_t> Dune::GDT::RtSpaceInterface< ImpTraits, domainDim, rangeDim, rangeDimCols >::local_DoF_indices_2dsimplex_order0 (const EntityType & entity) const inline
References Dune::GDT::SpaceInterface< ImpTraits, domainDim, rangeDim, rangeDimCols >::base_function_set(), Dune::GDT::SpaceInterface< ImpTraits, domainDim, rangeDim, rangeDimCols >::dimDomain, Dune::GDT::SpaceInterface< ImpTraits, domainDim, rangeDim, rangeDimCols >::grid_view(), and Dune::GDT::SpaceInterface< ImpTraits, domainDim, rangeDim, rangeDimCols >::polOrder.
template<class Traits, size_t domainDim, size_t rangeDim, size_t rangeDimCols = 1> void Dune::GDT::SpaceInterface< Traits, domainDim, rangeDim, rangeDimCols >::visualize (const std::string filename_prefix = "") const inline