´´These methods have to be implemented!''
´´These methods have to be implemented!''
Modules
´´These methods are provided by the interface for convenience.''
Classes
struct Dune::GDT::internal::is_space_helper< S >
struct Dune::GDT::internal::is_rt_space_helper< S >
Functions
std::vector< DomainType > Dune::GDT::CgSpaceInterface< ImpTraits, domainDim, rangeDim, rangeDimCols >::lagrange_points (const EntityType &entity) const
std::set< size_t > Dune::GDT::CgSpaceInterface< ImpTraits, domainDim, rangeDim, rangeDimCols >::local_dirichlet_DoFs (const EntityType &entity, const BoundaryInfoType &boundaryInfo) const
const GridViewType & Dune::GDT::SpaceInterface< Traits, domainDim, rangeDim, rangeDimCols >::grid_view () const
const BackendType & Dune::GDT::SpaceInterface< Traits, domainDim, rangeDim, rangeDimCols >::backend () const
const MapperType & Dune::GDT::SpaceInterface< Traits, domainDim, rangeDim, rangeDimCols >::mapper () const
BaseFunctionSetType Dune::GDT::SpaceInterface< Traits, domainDim, rangeDim, rangeDimCols >::base_function_set (const EntityType &entity) const
CommunicatorType & Dune::GDT::SpaceInterface< Traits, domainDim, rangeDim, rangeDimCols >::communicator () const
template<class S , size_t d, size_t r, size_t rC, class C >
void Dune::GDT::SpaceInterface< Traits, domainDim, rangeDim, rangeDimCols >::local_constraints (const SpaceInterface< S, d, r, rC > &ansatz_space, const EntityType &entity, ConstraintsInterface< C > &ret) const
Computes local constraints.
template<class C >
void Dune::GDT::SpaceInterface< Traits, domainDim, rangeDim, rangeDimCols >::local_constraints (const EntityType &entity, ConstraintsInterface< C > &ret) const
template<class G , class S , size_t d, size_t r, size_t rC>
PatternType Dune::GDT::SpaceInterface< Traits, domainDim, rangeDim, rangeDimCols >::compute_pattern (const GridView< G > &local_grid_view, const SpaceInterface< S, d, r, rC > &ansatz_space) const
Computes the appropriate sparsity pattern.
template<size_t ii>
const std::tuple_element< ii,
SpaceTupleType >::type & Dune::GDT::ProductSpaceInterface< Traits, domainDim, rangeDim, rangeDimCols >::factor () const
Dune::GDT::internal::is_space_helper< S >::DSC_has_typedef_initialize_once (Traits) DSC_has_static_member_initialize_once(dimDomain) DSC_has_static_member_initialize_once(dimRange) DSC_has_static_member_initialize_once(dimRangeCols) static const bool is_candidate
std::vector< size_t > Dune::GDT::RtSpaceInterface< ImpTraits, domainDim, rangeDim, rangeDimCols >::local_DoF_indices (const EntityType &entity) const
Computes a vector 'indices' of length entity.count< 1 >(), where 'indices[intersection.indexInInside()]' is the index of the basis function (aka the local DoF index) corresponding to the intersection.
Dune::GDT::internal::is_rt_space_helper< S >::DSC_has_typedef_initialize_once (Traits) DSC_has_static_member_initialize_once(dimDomain) DSC_has_static_member_initialize_once(dimRange) DSC_has_static_member_initialize_once(dimRangeCols) static const bool is_candidate
Detailed Description
Function Documentation
template<class Traits, size_t domainDim, size_t rangeDim, size_t rangeDimCols = 1> const BackendType& Dune::GDT::SpaceInterface< Traits, domainDim, rangeDim, rangeDimCols >::backend () const inline
Referenced by Dune::GDT::SpaceInterface< internal::DefaultProductSpaceTraits< SpaceImps...>, std::tuple_element< 0, std::tuple< SpaceImps...> >::type::dimDomain, GDT::BaseFunctionSet::internal::SumDimRange< SpaceImps...>::dimRange, 1 >::backend().
template<class Traits, size_t domainDim, size_t rangeDim, size_t rangeDimCols = 1> BaseFunctionSetType Dune::GDT::SpaceInterface< Traits, domainDim, rangeDim, rangeDimCols >::base_function_set (const EntityType & entity) const inline
Referenced by Dune::GDT::LocalVolumeTwoFormAssembler< LocalVolumeTwoFormType >::assemble(), Dune::GDT::LocalCouplingTwoFormAssembler< LocalCouplingTwoFormType >::assemble(), Dune::GDT::LocalBoundaryTwoFormAssembler< LocalBoundaryTwoFormType >::assemble(), Dune::GDT::LocalVolumeFunctionalAssembler< LocalFunctionalType >::assemble(), Dune::GDT::LocalFaceFunctionalAssembler< LocalFaceFunctionalType >::assemble(), Dune::GDT::SpaceInterface< internal::DefaultProductSpaceTraits< SpaceImps...>, std::tuple_element< 0, std::tuple< SpaceImps...> >::type::dimDomain, GDT::BaseFunctionSet::internal::SumDimRange< SpaceImps...>::dimRange, 1 >::base_function_set(), Dune::GDT::SpaceInterface< internal::DefaultProductSpaceTraits< SpaceImps...>, std::tuple_element< 0, std::tuple< SpaceImps...> >::type::dimDomain, GDT::BaseFunctionSet::internal::SumDimRange< SpaceImps...>::dimRange, 1 >::compute_face_and_volume_pattern(), Dune::GDT::SpaceInterface< internal::DefaultProductSpaceTraits< SpaceImps...>, std::tuple_element< 0, std::tuple< SpaceImps...> >::type::dimDomain, GDT::BaseFunctionSet::internal::SumDimRange< SpaceImps...>::dimRange, 1 >::compute_face_pattern(), and Dune::GDT::SpaceInterface< internal::DefaultProductSpaceTraits< SpaceImps...>, std::tuple_element< 0, std::tuple< SpaceImps...> >::type::dimDomain, GDT::BaseFunctionSet::internal::SumDimRange< SpaceImps...>::dimRange, 1 >::compute_volume_pattern().
template<class Traits, size_t domainDim, size_t rangeDim, size_t rangeDimCols = 1> CommunicatorType& Dune::GDT::SpaceInterface< Traits, domainDim, rangeDim, rangeDimCols >::communicator () const inline
Referenced by Dune::GDT::SpaceInterface< internal::DefaultProductSpaceTraits< SpaceImps...>, std::tuple_element< 0, std::tuple< SpaceImps...> >::type::dimDomain, GDT::BaseFunctionSet::internal::SumDimRange< SpaceImps...>::dimRange, 1 >::communicator().
template<class Traits, size_t domainDim, size_t rangeDim, size_t rangeDimCols = 1> template<class G , class S , size_t d, size_t r, size_t rC> PatternType Dune::GDT::SpaceInterface< Traits, domainDim, rangeDim, rangeDimCols >::compute_pattern (const GridView< G > & local_grid_view, const SpaceInterface< S, d, r, rC > & ansatz_space) const inline
Computes the appropriate sparsity pattern.
Note
This method can be implemented in a derived class by a forward to one of the methods provided by this class, namely compute_volume_pattern(), compute_face_pattern() or compute_face_and_volume_pattern().
template<class S > Dune::GDT::internal::is_rt_space_helper< S >::DSC_has_typedef_initialize_once (Traits) const
template<class S > Dune::GDT::internal::is_space_helper< S >::DSC_has_typedef_initialize_once (Traits) const
template<class Traits, size_t domainDim, size_t rangeDim, size_t rangeDimCols = 1> template<size_t ii> const std::tuple_element<ii, SpaceTupleType>::type& Dune::GDT::ProductSpaceInterface< Traits, domainDim, rangeDim, rangeDimCols >::factor () const inline
template<class Traits, size_t domainDim, size_t rangeDim, size_t rangeDimCols = 1> const GridViewType& Dune::GDT::SpaceInterface< Traits, domainDim, rangeDim, rangeDimCols >::grid_view () const inline
Referenced by Dune::GDT::begin(), Dune::GDT::SpaceInterface< internal::DefaultProductSpaceTraits< SpaceImps...>, std::tuple_element< 0, std::tuple< SpaceImps...> >::type::dimDomain, GDT::BaseFunctionSet::internal::SumDimRange< SpaceImps...>::dimRange, 1 >::compute_face_and_volume_pattern(), Dune::GDT::SpaceInterface< internal::DefaultProductSpaceTraits< SpaceImps...>, std::tuple_element< 0, std::tuple< SpaceImps...> >::type::dimDomain, GDT::BaseFunctionSet::internal::SumDimRange< SpaceImps...>::dimRange, 1 >::compute_face_pattern(), Dune::GDT::SpaceInterface< internal::DefaultProductSpaceTraits< SpaceImps...>, std::tuple_element< 0, std::tuple< SpaceImps...> >::type::dimDomain, GDT::BaseFunctionSet::internal::SumDimRange< SpaceImps...>::dimRange, 1 >::compute_pattern(), Dune::GDT::SpaceInterface< internal::DefaultProductSpaceTraits< SpaceImps...>, std::tuple_element< 0, std::tuple< SpaceImps...> >::type::dimDomain, GDT::BaseFunctionSet::internal::SumDimRange< SpaceImps...>::dimRange, 1 >::compute_volume_pattern(), Dune::GDT::end(), Dune::GDT::SpaceInterface< internal::DefaultProductSpaceTraits< SpaceImps...>, std::tuple_element< 0, std::tuple< SpaceImps...> >::type::dimDomain, GDT::BaseFunctionSet::internal::SumDimRange< SpaceImps...>::dimRange, 1 >::grid_view(), and Dune::GDT::SpaceInterface< internal::DefaultProductSpaceTraits< SpaceImps...>, std::tuple_element< 0, std::tuple< SpaceImps...> >::type::dimDomain, GDT::BaseFunctionSet::internal::SumDimRange< SpaceImps...>::dimRange, 1 >::visualize().
template<class ImpTraits , size_t domainDim, size_t rangeDim, size_t rangeDimCols = 1> std::vector<DomainType> Dune::GDT::CgSpaceInterface< ImpTraits, domainDim, rangeDim, rangeDimCols >::lagrange_points (const EntityType & entity) const inline
template<class Traits, size_t domainDim, size_t rangeDim, size_t rangeDimCols = 1> template<class S , size_t d, size_t r, size_t rC, class C > void Dune::GDT::SpaceInterface< Traits, domainDim, rangeDim, rangeDimCols >::local_constraints (const SpaceInterface< S, d, r, rC > & ansatz_space, const EntityType & entity, ConstraintsInterface< C > & ret) const inline
Computes local constraints.
Note
Any derived class has to implement this method, even if it does not support any kind of constraints! In that case just provide exactly the following method:
template< class S, size_t d, size_t r, size_t rC, class ConstraintsType >
void local_constraints(const SpaceInterface< S, d, r, rC > >&, const EntityType&, ConstraintsType&) const
{
  static_assert(AlwaysFalse< S >::value, "Not implemented for these constraints!");
}
Referenced by Dune::GDT::SpaceInterface< internal::DefaultProductSpaceTraits< SpaceImps...>, std::tuple_element< 0, std::tuple< SpaceImps...> >::type::dimDomain, GDT::BaseFunctionSet::internal::SumDimRange< SpaceImps...>::dimRange, 1 >::local_constraints().
template<class Traits, size_t domainDim, size_t rangeDim, size_t rangeDimCols = 1> template<class C > void Dune::GDT::SpaceInterface< Traits, domainDim, rangeDim, rangeDimCols >::local_constraints (const EntityType & entity, ConstraintsInterface< C > & ret) const inline
template<class ImpTraits , size_t domainDim, size_t rangeDim, size_t rangeDimCols = 1> std::set<size_t> Dune::GDT::CgSpaceInterface< ImpTraits, domainDim, rangeDim, rangeDimCols >::local_dirichlet_DoFs (const EntityType & entity, const BoundaryInfoType & boundaryInfo) const inline
Referenced by Dune::GDT::CgSpaceInterface< ImpTraits, domainDim, rangeDim, rangeDimCols >::local_constraints().
template<class ImpTraits , size_t domainDim, size_t rangeDim, size_t rangeDimCols = 1> std::vector<size_t> Dune::GDT::RtSpaceInterface< ImpTraits, domainDim, rangeDim, rangeDimCols >::local_DoF_indices (const EntityType & entity) const inline
Computes a vector 'indices' of length entity.count< 1 >(), where 'indices[intersection.indexInInside()]' is the index of the basis function (aka the local DoF index) corresponding to the intersection.
template<class Traits, size_t domainDim, size_t rangeDim, size_t rangeDimCols = 1> const MapperType& Dune::GDT::SpaceInterface< Traits, domainDim, rangeDim, rangeDimCols >::mapper () const inline
Referenced by Dune::GDT::LocalVolumeTwoFormAssembler< LocalVolumeTwoFormType >::assemble(), Dune::GDT::LocalCouplingTwoFormAssembler< LocalCouplingTwoFormType >::assemble(), Dune::GDT::LocalBoundaryTwoFormAssembler< LocalBoundaryTwoFormType >::assemble(), Dune::GDT::LocalVolumeFunctionalAssembler< LocalFunctionalType >::assemble(), Dune::GDT::LocalFaceFunctionalAssembler< LocalFaceFunctionalType >::assemble(), Dune::GDT::SpaceInterface< internal::DefaultProductSpaceTraits< SpaceImps...>, std::tuple_element< 0, std::tuple< SpaceImps...> >::type::dimDomain, GDT::BaseFunctionSet::internal::SumDimRange< SpaceImps...>::dimRange, 1 >::compute_face_and_volume_pattern(), Dune::GDT::SpaceInterface< internal::DefaultProductSpaceTraits< SpaceImps...>, std::tuple_element< 0, std::tuple< SpaceImps...> >::type::dimDomain, GDT::BaseFunctionSet::internal::SumDimRange< SpaceImps...>::dimRange, 1 >::compute_face_pattern(), Dune::GDT::SpaceInterface< internal::DefaultProductSpaceTraits< SpaceImps...>, std::tuple_element< 0, std::tuple< SpaceImps...> >::type::dimDomain, GDT::BaseFunctionSet::internal::SumDimRange< SpaceImps...>::dimRange, 1 >::compute_volume_pattern(), Dune::GDT::SpaceInterface< internal::DefaultProductSpaceTraits< SpaceImps...>, std::tuple_element< 0, std::tuple< SpaceImps...> >::type::dimDomain, GDT::BaseFunctionSet::internal::SumDimRange< SpaceImps...>::dimRange, 1 >::mapper(), and Dune::GDT::SpaceInterface< internal::DefaultProductSpaceTraits< SpaceImps...>, std::tuple_element< 0, std::tuple< SpaceImps...> >::type::dimDomain, GDT::BaseFunctionSet::internal::SumDimRange< SpaceImps...>::dimRange, 1 >::visualize().