Dune::GDT::LocalSipdgIntegrands::internal Namespace Reference
Dune::GDT::LocalSipdgIntegrands::internal Namespace Reference
Classes
class InnerTraits
class BoundaryLHSTraits
class BoundaryRHSTraits
Functions
static double default_beta (const size_t dimDomain)
static double inner_sigma (const size_t pol_order)
static double boundary_sigma (const size_t pol_order)
Function Documentation
static double Dune::GDT::LocalSipdgIntegrands::internal::boundary_sigma (const size_t pol_order) inline static
Note
see Epshteyn, Riviere, 2007
Referenced by Dune::GDT::LocalSipdgIntegrands::BoundaryLHS< LocalizableFunctionImp >::evaluate(), Dune::GDT::LocalSipdgIntegrands::BoundaryRHS< LocalizableDiffusionFunctionImp, LocalizableDirichletFunctionImp >::evaluate(), Dune::GDT::LocalEllipticIpdgIntegrands::BoundaryLHS< DiffusionFactorImp, DiffusionTensorImp, method >::evaluate(), and Dune::GDT::LocalEllipticIpdgIntegrands::BoundaryRHS< DirichletImp, DiffusionFactorImp, DiffusionTensorImp, method >::evaluate().
static double Dune::GDT::LocalSipdgIntegrands::internal::default_beta (const size_t dimDomain) inline static
Note
see Epshteyn, Riviere, 2007
static double Dune::GDT::LocalSipdgIntegrands::internal::inner_sigma (const size_t pol_order) inline static
Note
see Epshteyn, Riviere, 2007
Referenced by Dune::GDT::LocalSipdgIntegrands::Inner< LocalizableFunctionImp >::evaluate(), and Dune::GDT::LocalEllipticIpdgIntegrands::Inner< DiffusionFactorImp, DiffusionTensorImp, method >::evaluate().