Dune::XT::Functions::RandomEllipsoidsFunction< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols > Class Template Reference
Dune::XT::Functions::RandomEllipsoidsFunction< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols > Class Template Reference
#include <dune/xt/functions/random_ellipsoids.hh>
Classes
class Localfunction
Public Types
typedef BaseType::EntityType EntityType
typedef BaseType::LocalfunctionType LocalfunctionType
typedef BaseType::DomainFieldType DomainFieldType
typedef BaseType::RangeFieldType RangeFieldType
typedef BaseType::RangeType RangeType
typedef Ellipsoid< dimDomain,
DomainFieldType > EllipsoidType
typedef
LocalfunctionType::DomainType DomainType
typedef
LocalfunctionType::JacobianRangeType JacobianRangeType
typedef
Functions::DifferenceFunction
< ThisType, ThisType > DifferenceType
typedef Functions::SumFunction
< ThisType, ThisType > SumType
typedef
Functions::DivergenceFunction
< ThisType > DivergenceType
Public Member Functions
RandomEllipsoidsFunction (const Common::FieldVector< DomainFieldType, dimDomain > &lowerLeft, const Common::FieldVector< DomainFieldType, dimDomain > &upperRight, const Common::Configuration &ellipsoid_cfg, const std::string nm=static_id())
RandomEllipsoidsFunction (const ThisType &other)=default
ThisType & operator= (const ThisType &other)=delete
ThisType & operator= (ThisType &&source)=delete
virtual std::string type () const override
virtual std::string name () const override
void to_file (std::ostream &out) const
virtual std::unique_ptr
< LocalfunctionType > local_function (const EntityType &entity) const override
DifferenceType operator- (const ThisType &other) const
SumType operator+ (const ThisType &other) const
template<class OtherType >
std::enable_if
< is_localizable_function
< OtherType >::value,
Functions::ProductFunction
< ThisType, OtherType >
>::type operator* (const OtherType &other) const
DivergenceType divergence () const
template<class GridViewType >
void visualize (const GridViewType &grid_view, const std::string path, const bool subsampling=true, const VTK::OutputType vtk_output_type=VTK::appendedraw) const
virtual void report (std::ostream &out, const std::string prefix="") const
Static Public Member Functions
static std::string static_id ()
static Common::Configuration default_config (const std::string sub_name="")
static std::unique_ptr< ThisType > create (const Common::Configuration config=default_config(), const std::string sub_name=static_id())
Static Public Attributes
static const size_t dimDomain = BaseType::dimDomain
static const bool available = true
static const constexpr size_t dimRange = rangeDim
static const constexpr size_t dimRangeCols = rangeDimCols
Protected Types
typedef
LocalizableFunctionInterface
< EntityImp, DomainFieldImp,
domainDim, RangeFieldImp,
rangeDim, rangeDimCols > BaseType
typedef
RandomEllipsoidsFunction
< EntityImp, DomainFieldImp,
domainDim, RangeFieldImp,
rangeDim, rangeDimCols > ThisType
Member Typedef Documentation
template<class EntityImp , class DomainFieldImp , size_t domainDim, class RangeFieldImp , size_t rangeDim, size_t rangeDimCols = 1> typedef LocalizableFunctionInterface<EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols> Dune::XT::Functions::RandomEllipsoidsFunction< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::BaseType protected
template<class EntityImp, class DomainFieldImp, size_t domainDim, class RangeFieldImp, size_t rangeDim, size_t rangeDimCols = 1> typedef Functions::DifferenceFunction<ThisType, ThisType> Dune::XT::Functions::LocalizableFunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::DifferenceType inherited
template<class EntityImp, class DomainFieldImp, size_t domainDim, class RangeFieldImp, size_t rangeDim, size_t rangeDimCols = 1> typedef Functions::DivergenceFunction<ThisType> Dune::XT::Functions::LocalizableFunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::DivergenceType inherited
template<class EntityImp , class DomainFieldImp , size_t domainDim, class RangeFieldImp , size_t rangeDim, size_t rangeDimCols = 1> typedef BaseType::DomainFieldType Dune::XT::Functions::RandomEllipsoidsFunction< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::DomainFieldType
template<class EntityImp, class DomainFieldImp, size_t domainDim, class RangeFieldImp, size_t rangeDim, size_t rangeDimCols = 1> typedef LocalfunctionType::DomainType Dune::XT::Functions::LocalizableFunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::DomainType inherited
template<class EntityImp , class DomainFieldImp , size_t domainDim, class RangeFieldImp , size_t rangeDim, size_t rangeDimCols = 1> typedef Ellipsoid<dimDomain, DomainFieldType> Dune::XT::Functions::RandomEllipsoidsFunction< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::EllipsoidType
template<class EntityImp , class DomainFieldImp , size_t domainDim, class RangeFieldImp , size_t rangeDim, size_t rangeDimCols = 1> typedef BaseType::EntityType Dune::XT::Functions::RandomEllipsoidsFunction< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::EntityType
template<class EntityImp, class DomainFieldImp, size_t domainDim, class RangeFieldImp, size_t rangeDim, size_t rangeDimCols = 1> typedef LocalfunctionType::JacobianRangeType Dune::XT::Functions::LocalizableFunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::JacobianRangeType inherited
template<class EntityImp , class DomainFieldImp , size_t domainDim, class RangeFieldImp , size_t rangeDim, size_t rangeDimCols = 1> typedef BaseType::LocalfunctionType Dune::XT::Functions::RandomEllipsoidsFunction< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::LocalfunctionType
template<class EntityImp , class DomainFieldImp , size_t domainDim, class RangeFieldImp , size_t rangeDim, size_t rangeDimCols = 1> typedef BaseType::RangeFieldType Dune::XT::Functions::RandomEllipsoidsFunction< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::RangeFieldType
template<class EntityImp , class DomainFieldImp , size_t domainDim, class RangeFieldImp , size_t rangeDim, size_t rangeDimCols = 1> typedef BaseType::RangeType Dune::XT::Functions::RandomEllipsoidsFunction< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::RangeType
template<class EntityImp, class DomainFieldImp, size_t domainDim, class RangeFieldImp, size_t rangeDim, size_t rangeDimCols = 1> typedef Functions::SumFunction<ThisType, ThisType> Dune::XT::Functions::LocalizableFunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::SumType inherited
template<class EntityImp , class DomainFieldImp , size_t domainDim, class RangeFieldImp , size_t rangeDim, size_t rangeDimCols = 1> typedef RandomEllipsoidsFunction<EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols> Dune::XT::Functions::RandomEllipsoidsFunction< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::ThisType protected
Constructor & Destructor Documentation
template<class EntityImp , class DomainFieldImp , size_t domainDim, class RangeFieldImp , size_t rangeDim, size_t rangeDimCols = 1> Dune::XT::Functions::RandomEllipsoidsFunction< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::RandomEllipsoidsFunction (const Common::FieldVector< DomainFieldType, dimDomain > & lowerLeft, const Common::FieldVector< DomainFieldType, dimDomain > & upperRight, const Common::Configuration & ellipsoid_cfg, const std::string nm = static_id()) inline
References Dune::XT::Functions::Ellipsoid< dim, CoordType >::center, Dune::XT::Functions::Ellipsoid< dim, CoordType >::radii, and Dune::XT::Functions::RandomEllipsoidsFunction< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::to_file().
template<class EntityImp , class DomainFieldImp , size_t domainDim, class RangeFieldImp , size_t rangeDim, size_t rangeDimCols = 1> Dune::XT::Functions::RandomEllipsoidsFunction< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::RandomEllipsoidsFunction (const ThisType & other) default
Member Function Documentation
template<class EntityImp , class DomainFieldImp , size_t domainDim, class RangeFieldImp , size_t rangeDim, size_t rangeDimCols = 1> static std::unique_ptr<ThisType> Dune::XT::Functions::RandomEllipsoidsFunction< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::create (const Common::Configuration config = default_config(), const std::string sub_name = static_id()) inline static
References Dune::XT::Functions::RandomEllipsoidsFunction< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::default_config().
template<class EntityImp , class DomainFieldImp , size_t domainDim, class RangeFieldImp , size_t rangeDim, size_t rangeDimCols = 1> static Common::Configuration Dune::XT::Functions::RandomEllipsoidsFunction< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::default_config (const std::string sub_name = "") inline static
References Dune::XT::Functions::RandomEllipsoidsFunction< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::static_id().
Referenced by Dune::XT::Functions::RandomEllipsoidsFunction< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::create().
template<class EntityImp, class DomainFieldImp, size_t domainDim, class RangeFieldImp, size_t rangeDim, size_t rangeDimCols = 1> DivergenceType Dune::XT::Functions::LocalizableFunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::divergence () const inline inherited
template<class EntityImp , class DomainFieldImp , size_t domainDim, class RangeFieldImp , size_t rangeDim, size_t rangeDimCols = 1> virtual std::unique_ptr<LocalfunctionType> Dune::XT::Functions::RandomEllipsoidsFunction< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::local_function (const EntityType & entity) const inline override virtual
Implements Dune::XT::Functions::LocalizableFunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >.
template<class EntityImp , class DomainFieldImp , size_t domainDim, class RangeFieldImp , size_t rangeDim, size_t rangeDimCols = 1> virtual std::string Dune::XT::Functions::RandomEllipsoidsFunction< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::name () const inline override virtual
Reimplemented from Dune::XT::Functions::LocalizableFunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >.
template<class EntityImp, class DomainFieldImp, size_t domainDim, class RangeFieldImp, size_t rangeDim, size_t rangeDimCols = 1> template<class OtherType > std::enable_if<is_localizable_function<OtherType>::value, Functions::ProductFunction<ThisType, OtherType> >::type Dune::XT::Functions::LocalizableFunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::operator* (const OtherType & other) const inline inherited
template<class EntityImp, class DomainFieldImp, size_t domainDim, class RangeFieldImp, size_t rangeDim, size_t rangeDimCols = 1> SumType Dune::XT::Functions::LocalizableFunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::operator+ (const ThisType & other) const inline inherited
template<class EntityImp, class DomainFieldImp, size_t domainDim, class RangeFieldImp, size_t rangeDim, size_t rangeDimCols = 1> DifferenceType Dune::XT::Functions::LocalizableFunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::operator- (const ThisType & other) const inline inherited
template<class EntityImp , class DomainFieldImp , size_t domainDim, class RangeFieldImp , size_t rangeDim, size_t rangeDimCols = 1> ThisType& Dune::XT::Functions::RandomEllipsoidsFunction< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::operator= (const ThisType & other) delete
template<class EntityImp , class DomainFieldImp , size_t domainDim, class RangeFieldImp , size_t rangeDim, size_t rangeDimCols = 1> ThisType& Dune::XT::Functions::RandomEllipsoidsFunction< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::operator= (ThisType && source) delete
template<class EntityImp, class DomainFieldImp, size_t domainDim, class RangeFieldImp, size_t rangeDim, size_t rangeDimCols = 1> virtual void Dune::XT::Functions::LocalizableFunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::report (std::ostream & out, const std::string prefix = "") const inline virtual inherited
template<class EntityImp , class DomainFieldImp , size_t domainDim, class RangeFieldImp , size_t rangeDim, size_t rangeDimCols = 1> static std::string Dune::XT::Functions::RandomEllipsoidsFunction< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::static_id () inline static
References Dune::XT::Functions::LocalizableFunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::static_id().
Referenced by Dune::XT::Functions::RandomEllipsoidsFunction< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::default_config().
template<class EntityImp , class DomainFieldImp , size_t domainDim, class RangeFieldImp , size_t rangeDim, size_t rangeDimCols = 1> void Dune::XT::Functions::RandomEllipsoidsFunction< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::to_file (std::ostream & out) const inline
Referenced by Dune::XT::Functions::RandomEllipsoidsFunction< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::RandomEllipsoidsFunction().
template<class EntityImp , class DomainFieldImp , size_t domainDim, class RangeFieldImp , size_t rangeDim, size_t rangeDimCols = 1> virtual std::string Dune::XT::Functions::RandomEllipsoidsFunction< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::type () const inline override virtual
Reimplemented from Dune::XT::Functions::LocalizableFunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >.
References Dune::XT::Functions::LocalizableFunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::static_id().
template<class EntityImp, class DomainFieldImp, size_t domainDim, class RangeFieldImp, size_t rangeDim, size_t rangeDimCols = 1> template<class GridViewType > void Dune::XT::Functions::LocalizableFunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::visualize (const GridViewType & grid_view, const std::string path, const bool subsampling = true, const VTK::OutputType vtk_output_type = VTK::appendedraw) const inline inherited
Note
We use the SubsamplingVTKWriter (which is better for higher orders) by default. This means that the grid you see in the visualization is a refinement of the actual grid!
Member Data Documentation
template<class EntityImp , class DomainFieldImp , size_t domainDim, class RangeFieldImp , size_t rangeDim, size_t rangeDimCols = 1> const bool Dune::XT::Functions::RandomEllipsoidsFunction< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::available = true static
template<class EntityImp , class DomainFieldImp , size_t domainDim, class RangeFieldImp , size_t rangeDim, size_t rangeDimCols = 1> const size_t Dune::XT::Functions::RandomEllipsoidsFunction< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::dimDomain = BaseType::dimDomain static
template<class EntityImp, class DomainFieldImp, size_t domainDim, class RangeFieldImp, size_t rangeDim, size_t rangeDimCols = 1> const constexpr size_t Dune::XT::Functions::LocalizableFunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::dimRange = rangeDim static inherited
Referenced by Dune::XT::Functions::ExpressionFunction< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::evaluate(), and Dune::XT::Functions::ExpressionFunction< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::ExpressionFunction().
template<class EntityImp, class DomainFieldImp, size_t domainDim, class RangeFieldImp, size_t rangeDim, size_t rangeDimCols = 1> const constexpr size_t Dune::XT::Functions::LocalizableFunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::dimRangeCols = rangeDimCols static inherited
Referenced by Dune::XT::Functions::ExpressionFunction< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::create(), Dune::XT::Functions::ExpressionFunction< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::evaluate(), Dune::XT::Functions::ExpressionFunction< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::ExpressionFunction(), and Dune::XT::Functions::ExpressionFunction< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::jacobian().
The documentation for this class was generated from the following file:
random_ellipsoids.hh