Dune::XT::Functions::LocalfunctionSetInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols > Class Template Reference
Dune::XT::Functions::LocalfunctionSetInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols > Class Template Reference abstract
Interface for a set of globalvalued functions, which can be evaluated locally on one Entity.
#include <dune/xt/functions/interfaces.hh>
Public Types
typedef EntityImp EntityType
typedef DomainFieldImp DomainFieldType
typedef Dune::FieldVector
< DomainFieldType, dimDomain > DomainType
typedef RangeFieldImp RangeFieldType
typedef RangeTypeSelector
< RangeFieldType, dimRange,
dimRangeCols >::type RangeType
typedef
JacobianRangeTypeSelector
< dimDomain, RangeFieldType,
dimRange, dimRangeCols >::type JacobianRangeType
Public Member Functions
LocalfunctionSetInterface (const EntityType &ent)
virtual ~LocalfunctionSetInterface ()
virtual const EntityType & entity () const
virtual size_t size () const =0
virtual size_t order () const =0
virtual void evaluate (const DomainType &, std::vector< RangeType > &) const =0
virtual void jacobian (const DomainType &, std::vector< JacobianRangeType > &) const =0
std::vector< RangeType > evaluate (const DomainType &xx) const
std::vector< JacobianRangeType > jacobian (const DomainType &xx) const
Static Public Attributes
static const constexpr size_t dimDomain = domainDim
static const constexpr size_t dimRange = rangeDim
static const constexpr size_t dimRangeCols = rangeDimCols
Protected Member Functions
bool is_a_valid_point (const DomainType &xx) const
Protected Attributes
const EntityType & entity_
Detailed Description
template<class EntityImp, class DomainFieldImp, size_t domainDim, class RangeFieldImp, size_t rangeDim, size_t rangeDimCols = 1>
class Dune::XT::Functions::LocalfunctionSetInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >
Interface for a set of globalvalued functions, which can be evaluated locally on one Entity.
Member Typedef Documentation
template<class EntityImp, class DomainFieldImp, size_t domainDim, class RangeFieldImp, size_t rangeDim, size_t rangeDimCols = 1> typedef DomainFieldImp Dune::XT::Functions::LocalfunctionSetInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::DomainFieldType
template<class EntityImp, class DomainFieldImp, size_t domainDim, class RangeFieldImp, size_t rangeDim, size_t rangeDimCols = 1> typedef Dune::FieldVector<DomainFieldType, dimDomain> Dune::XT::Functions::LocalfunctionSetInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::DomainType
template<class EntityImp, class DomainFieldImp, size_t domainDim, class RangeFieldImp, size_t rangeDim, size_t rangeDimCols = 1> typedef EntityImp Dune::XT::Functions::LocalfunctionSetInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::EntityType
template<class EntityImp, class DomainFieldImp, size_t domainDim, class RangeFieldImp, size_t rangeDim, size_t rangeDimCols = 1> typedef JacobianRangeTypeSelector<dimDomain, RangeFieldType, dimRange, dimRangeCols>::type Dune::XT::Functions::LocalfunctionSetInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::JacobianRangeType
template<class EntityImp, class DomainFieldImp, size_t domainDim, class RangeFieldImp, size_t rangeDim, size_t rangeDimCols = 1> typedef RangeFieldImp Dune::XT::Functions::LocalfunctionSetInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::RangeFieldType
template<class EntityImp, class DomainFieldImp, size_t domainDim, class RangeFieldImp, size_t rangeDim, size_t rangeDimCols = 1> typedef RangeTypeSelector<RangeFieldType, dimRange, dimRangeCols>::type Dune::XT::Functions::LocalfunctionSetInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::RangeType
Constructor & Destructor Documentation
template<class EntityImp, class DomainFieldImp, size_t domainDim, class RangeFieldImp, size_t rangeDim, size_t rangeDimCols = 1> Dune::XT::Functions::LocalfunctionSetInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::LocalfunctionSetInterface (const EntityType & ent) inline
template<class EntityImp, class DomainFieldImp, size_t domainDim, class RangeFieldImp, size_t rangeDim, size_t rangeDimCols = 1> virtual Dune::XT::Functions::LocalfunctionSetInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::~LocalfunctionSetInterface () inline virtual
Member Function Documentation
template<class EntityImp, class DomainFieldImp, size_t domainDim, class RangeFieldImp, size_t rangeDim, size_t rangeDimCols = 1> virtual const EntityType& Dune::XT::Functions::LocalfunctionSetInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::entity () const inline virtual
Referenced by Dune::XT::Functions::LocalfunctionSetInterface< E_, D_, domainDim, R_, rangeDim, rangeDimCols >::is_a_valid_point().
template<class EntityImp, class DomainFieldImp, size_t domainDim, class RangeFieldImp, size_t rangeDim, size_t rangeDimCols = 1> bool Dune::XT::Functions::LocalfunctionSetInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::is_a_valid_point (const DomainType & xx) const inline protected
Referenced by Dune::XT::Functions::RandomEllipsoidsFunction< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::Localfunction::evaluate(), and Dune::XT::Functions::RandomEllipsoidsFunction< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::Localfunction::jacobian().
Member Data Documentation
template<class EntityImp, class DomainFieldImp, size_t domainDim, class RangeFieldImp, size_t rangeDim, size_t rangeDimCols = 1> const constexpr size_t Dune::XT::Functions::LocalfunctionSetInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::dimDomain = domainDim static
template<class EntityImp, class DomainFieldImp, size_t domainDim, class RangeFieldImp, size_t rangeDim, size_t rangeDimCols = 1> const constexpr size_t Dune::XT::Functions::LocalfunctionSetInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::dimRange = rangeDim static
template<class EntityImp, class DomainFieldImp, size_t domainDim, class RangeFieldImp, size_t rangeDim, size_t rangeDimCols = 1> const constexpr size_t Dune::XT::Functions::LocalfunctionSetInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::dimRangeCols = rangeDimCols static
template<class EntityImp, class DomainFieldImp, size_t domainDim, class RangeFieldImp, size_t rangeDim, size_t rangeDimCols = 1> const EntityType& Dune::XT::Functions::LocalfunctionSetInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::entity_ protected
Referenced by Dune::XT::Functions::LocalfunctionSetInterface< E_, D_, domainDim, R_, rangeDim, rangeDimCols >::entity().
The documentation for this class was generated from the following file:
interfaces.hh