Dune::XT::Functions::ExpressionFunction< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols > Class Template Reference
Dune::XT::Functions::ExpressionFunction< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols > Class Template Reference abstract
#include <dune/xt/functions/expression.hh>
Public Types
typedef std::vector
< std::vector< std::string > > ExpressionStringVectorType
typedef std::vector
< std::vector< std::vector
< std::string > > > GradientStringVectorType
typedef BaseType::DomainType DomainType
typedef BaseType::RangeType RangeType
typedef BaseType::JacobianRangeType JacobianRangeType
typedef BaseType::LocalfunctionType LocalfunctionType
typedef EntityImp EntityType
typedef DomainFieldImp DomainFieldType
typedef RangeFieldImp RangeFieldType
typedef
Functions::DifferenceFunction
< ThisType, ThisType > DifferenceType
typedef Functions::SumFunction
< ThisType, ThisType > SumType
typedef
Functions::DivergenceFunction
< ThisType > DivergenceType
Public Member Functions
ExpressionFunction (const std::string variable, const std::string expression, const size_t ord=0, const std::string nm=static_id(), const std::vector< std::string > gradient=std::vector< std::string >())
Creates an Expression function where every component is identical.
ExpressionFunction (const std::string variable, const std::vector< std::string > expressions, const size_t ord=default_config().template get< size_t >("order"), const std::string nm=static_id(), const std::vector< std::vector< std::string >> gradient_expressions=std::vector< std::vector< std::string >>())
Creates an Expression function with dimRangeCols = 1.
ExpressionFunction (const std::string variable, const ExpressionStringVectorType expressions, const size_t ord=0, const std::string nm=static_id(), const GradientStringVectorType gradient_expressions=GradientStringVectorType())
Creates an Expression function.
ExpressionFunction (const ThisType &other)=default
ThisType & operator= (const ThisType &other)
virtual std::string type () const overridefinal
virtual std::string name () const override
virtual size_t order () const override
virtual void evaluate (const DomainType &xx, RangeType &ret) const override
virtual void jacobian (const DomainType &xx, JacobianRangeType &ret) const override
virtual void evaluate (const DomainType &xx, RangeType &ret) const =0
virtual RangeType evaluate (const DomainType &xx) const
virtual void jacobian (const DomainType &, JacobianRangeType &) const
virtual JacobianRangeType jacobian (const DomainType &xx) const
virtual std::unique_ptr
< LocalfunctionType > local_function (const EntityImp &entity) const overridefinal
template<class OtherEntityImp >
Transfer< OtherEntityImp >::Type transfer () const
DifferenceType operator- (const ThisType &other) const
SumType operator+ (const ThisType &other) const
template<class OtherType >
std::enable_if
< is_localizable_function
< OtherType >::value,
Functions::ProductFunction
< ThisType, OtherType >
>::type operator* (const OtherType &other) const
DivergenceType divergence () const
template<class GridViewType >
void visualize (const GridViewType &grid_view, const std::string path, const bool subsampling=true, const VTK::OutputType vtk_output_type=VTK::appendedraw) const
virtual void report (std::ostream &out, const std::string prefix="") const
Static Public Member Functions
static std::string static_id ()
static Common::Configuration default_config (const std::string sub_name="")
static std::unique_ptr< ThisType > create (const Common::Configuration config=default_config(), const std::string sub_name=static_id())
Static Public Attributes
static const constexpr size_t dimDomain = domainDim
static const constexpr size_t dimRange = rangeDim
static const constexpr size_t dimRangeCols = rangeDimCols
static const bool available = false
Member Typedef Documentation
template<class EntityImp, class DomainFieldImp, size_t domainDim, class RangeFieldImp, size_t rangeDim, size_t rangeDimCols = 1> typedef Functions::DifferenceFunction<ThisType, ThisType> Dune::XT::Functions::LocalizableFunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::DifferenceType inherited
template<class EntityImp, class DomainFieldImp, size_t domainDim, class RangeFieldImp, size_t rangeDim, size_t rangeDimCols = 1> typedef Functions::DivergenceFunction<ThisType> Dune::XT::Functions::LocalizableFunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::DivergenceType inherited
template<class EntityImp, class DomainFieldImp, size_t domainDim, class RangeFieldImp, size_t rangeDim, size_t rangeDimCols = 1> typedef DomainFieldImp Dune::XT::Functions::LocalizableFunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::DomainFieldType inherited
template<class EntityImp , class DomainFieldImp , size_t domainDim, class RangeFieldImp , size_t rangeDim, size_t rangeDimCols = 1> typedef BaseType::DomainType Dune::XT::Functions::GlobalFunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::DomainType
template<class EntityImp, class DomainFieldImp, size_t domainDim, class RangeFieldImp, size_t rangeDim, size_t rangeDimCols = 1> typedef EntityImp Dune::XT::Functions::LocalizableFunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::EntityType inherited
template<class EntityImp , class DomainFieldImp , size_t domainDim, class RangeFieldImp , size_t rangeDim, size_t rangeDimCols = 1> typedef std::vector<std::vector<std::string> > Dune::XT::Functions::ExpressionFunction< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::ExpressionStringVectorType
template<class EntityImp , class DomainFieldImp , size_t domainDim, class RangeFieldImp , size_t rangeDim, size_t rangeDimCols = 1> typedef std::vector<std::vector<std::vector<std::string> > > Dune::XT::Functions::ExpressionFunction< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::GradientStringVectorType
template<class EntityImp , class DomainFieldImp , size_t domainDim, class RangeFieldImp , size_t rangeDim, size_t rangeDimCols = 1> typedef BaseType::JacobianRangeType Dune::XT::Functions::GlobalFunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::JacobianRangeType
template<class EntityImp, class DomainFieldImp, size_t domainDim, class RangeFieldImp, size_t rangeDim, size_t rangeDimCols = 1> typedef BaseType::LocalfunctionType Dune::XT::Functions::GlobalFunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::LocalfunctionType inherited
template<class EntityImp, class DomainFieldImp, size_t domainDim, class RangeFieldImp, size_t rangeDim, size_t rangeDimCols = 1> typedef RangeFieldImp Dune::XT::Functions::LocalizableFunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::RangeFieldType inherited
template<class EntityImp , class DomainFieldImp , size_t domainDim, class RangeFieldImp , size_t rangeDim, size_t rangeDimCols = 1> typedef BaseType::RangeType Dune::XT::Functions::GlobalFunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::RangeType
template<class EntityImp, class DomainFieldImp, size_t domainDim, class RangeFieldImp, size_t rangeDim, size_t rangeDimCols = 1> typedef Functions::SumFunction<ThisType, ThisType> Dune::XT::Functions::LocalizableFunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::SumType inherited
Constructor & Destructor Documentation
template<class EntityImp , class DomainFieldImp , size_t domainDim, class RangeFieldImp , size_t rangeDim, size_t rangeDimCols = 1> Dune::XT::Functions::ExpressionFunction< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::ExpressionFunction (const std::string variable, const std::string expression, const size_t ord = 0, const std::string nm = static_id(), const std::vector< std::string > gradient = std::vector<std::string>()) inline
Creates an Expression function where every component is identical.
For example, if dimDomain = dimRange = dimRangeCols = 2 and expression = "x[0]*x[1]", gradient should be ["x[1]" "x[0]"]. Then the resulting function is [x[0]*x[1] x[0]*x[1]; x[0]*x[1] x[0]*x[1]] and the gradient is [[x[1] x[0]; x[1] x[0]] [x[1] x[0] x[1] x[0]].
References Dune::XT::Functions::LocalizableFunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::dimRange, and Dune::XT::Functions::LocalizableFunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::dimRangeCols.
template<class EntityImp , class DomainFieldImp , size_t domainDim, class RangeFieldImp , size_t rangeDim, size_t rangeDimCols = 1> Dune::XT::Functions::ExpressionFunction< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::ExpressionFunction (const std::string variable, const std::vector< std::string > expressions, const size_t ord = default_config().template get<size_t>("order"), const std::string nm = static_id(), const std::vector< std::vector< std::string >> gradient_expressions = std::vector<std::vector<std::string>>()) inline
Creates an Expression function with dimRangeCols = 1.
This constructor just expands expressions and gradient_expressions from a std::vector< std::string > and std::vector< std::vector< std::string > to ExpressionStringVectorType and GradientStringVectorType, respectively.
References Dune::XT::Functions::LocalizableFunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::dimRangeCols.
template<class EntityImp , class DomainFieldImp , size_t domainDim, class RangeFieldImp , size_t rangeDim, size_t rangeDimCols = 1> Dune::XT::Functions::ExpressionFunction< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::ExpressionFunction (const std::string variable, const ExpressionStringVectorType expressions, const size_t ord = 0, const std::string nm = static_id(), const GradientStringVectorType gradient_expressions = GradientStringVectorType()) inline
Creates an Expression function.
Parameters
variable variable of the Expression function, e.g. "x"
expressions vector< vector< string > >, where the inner vectors are the rows of the Expression functions range, e.g. [[1 sin(x[0])] [2*x[0] x[1]]] gives the range [1 sin(x[0]); 2 x[1]]
ord order of the Expression function
nm name of the Expression function
gradient_expressions vector< vector< vector< string > > >, vector of the jacobian matrices (written as vector< vector< string > >, where the inner vectors are the rows) of the columns of the Expression function, e.g. [[[0 0] [2 0]] [[cos(x[0]) 0] [0 1]]] would be the gradient_expression corresponding to the expression above (if dimDomain = dimRange = dimRangeCols = 2)
template<class EntityImp , class DomainFieldImp , size_t domainDim, class RangeFieldImp , size_t rangeDim, size_t rangeDimCols = 1> Dune::XT::Functions::ExpressionFunction< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::ExpressionFunction (const ThisType & other) default
Member Function Documentation
template<class EntityImp , class DomainFieldImp , size_t domainDim, class RangeFieldImp , size_t rangeDim, size_t rangeDimCols = 1> static std::unique_ptr<ThisType> Dune::XT::Functions::ExpressionFunction< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::create (const Common::Configuration config = default_config(), const std::string sub_name = static_id()) inline static
References Dune::XT::Functions::ExpressionFunction< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::default_config(), and Dune::XT::Functions::LocalizableFunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::dimRangeCols.
template<class EntityImp , class DomainFieldImp , size_t domainDim, class RangeFieldImp , size_t rangeDim, size_t rangeDimCols = 1> static Common::Configuration Dune::XT::Functions::ExpressionFunction< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::default_config (const std::string sub_name = "") inline static
References Dune::XT::Functions::ExpressionFunction< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::static_id().
Referenced by Dune::XT::Functions::ExpressionFunction< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::create().
template<class EntityImp, class DomainFieldImp, size_t domainDim, class RangeFieldImp, size_t rangeDim, size_t rangeDimCols = 1> DivergenceType Dune::XT::Functions::LocalizableFunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::divergence () const inline inherited
template<class EntityImp , class DomainFieldImp , size_t domainDim, class RangeFieldImp , size_t rangeDim, size_t rangeDimCols = 1> virtual void Dune::XT::Functions::ExpressionFunction< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::evaluate (const DomainType & xx, RangeType & ret) const inline override virtual
References abs(), Dune::XT::Functions::LocalizableFunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::dimRange, Dune::XT::Functions::LocalizableFunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::dimRangeCols, and max().
template<class EntityImp, class DomainFieldImp, size_t domainDim, class RangeFieldImp, size_t rangeDim, size_t rangeDimCols = 1> virtual void Dune::XT::Functions::GlobalFunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::evaluate (const DomainType & xx, RangeType & ret) const pure virtual inherited
Referenced by Dune::XT::Functions::GlobalFunctionInterface< EntityImp, DomainFieldImp, 2, RangeFieldImp, 1, 1 >::evaluate(), and Dune::XT::Functions::GlobalFunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, 1 >::evaluate().
template<class EntityImp, class DomainFieldImp, size_t domainDim, class RangeFieldImp, size_t rangeDim, size_t rangeDimCols = 1> virtual RangeType Dune::XT::Functions::GlobalFunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::evaluate (const DomainType & xx) const inline virtual inherited
template<class EntityImp , class DomainFieldImp , size_t domainDim, class RangeFieldImp , size_t rangeDim, size_t rangeDimCols = 1> virtual void Dune::XT::Functions::ExpressionFunction< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::jacobian (const DomainType & xx, JacobianRangeType & ret) const inline override virtual
References Dune::XT::Functions::LocalizableFunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::dimRangeCols.
template<class EntityImp, class DomainFieldImp, size_t domainDim, class RangeFieldImp, size_t rangeDim, size_t rangeDimCols = 1> virtual void Dune::XT::Functions::GlobalFunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::jacobian (const DomainType & , JacobianRangeType &) const inline virtual inherited
Referenced by Dune::XT::Functions::GlobalFunctionInterface< EntityImp, DomainFieldImp, 2, RangeFieldImp, 1, 1 >::jacobian(), and Dune::XT::Functions::GlobalFunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, 1 >::jacobian().
template<class EntityImp, class DomainFieldImp, size_t domainDim, class RangeFieldImp, size_t rangeDim, size_t rangeDimCols = 1> virtual JacobianRangeType Dune::XT::Functions::GlobalFunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::jacobian (const DomainType & xx) const inline virtual inherited
template<class EntityImp, class DomainFieldImp, size_t domainDim, class RangeFieldImp, size_t rangeDim, size_t rangeDimCols = 1> virtual std::unique_ptr<LocalfunctionType> Dune::XT::Functions::GlobalFunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::local_function (const EntityImp & entity) const inline final override virtual inherited
Implements Dune::XT::Functions::LocalizableFunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >.
template<class EntityImp , class DomainFieldImp , size_t domainDim, class RangeFieldImp , size_t rangeDim, size_t rangeDimCols = 1> virtual std::string Dune::XT::Functions::ExpressionFunction< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::name () const inline override virtual
Reimplemented from Dune::XT::Functions::GlobalFunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >.
template<class EntityImp, class DomainFieldImp, size_t domainDim, class RangeFieldImp, size_t rangeDim, size_t rangeDimCols = 1> template<class OtherType > std::enable_if<is_localizable_function<OtherType>::value, Functions::ProductFunction<ThisType, OtherType> >::type Dune::XT::Functions::LocalizableFunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::operator* (const OtherType & other) const inline inherited
template<class EntityImp, class DomainFieldImp, size_t domainDim, class RangeFieldImp, size_t rangeDim, size_t rangeDimCols = 1> SumType Dune::XT::Functions::LocalizableFunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::operator+ (const ThisType & other) const inline inherited
template<class EntityImp, class DomainFieldImp, size_t domainDim, class RangeFieldImp, size_t rangeDim, size_t rangeDimCols = 1> DifferenceType Dune::XT::Functions::LocalizableFunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::operator- (const ThisType & other) const inline inherited
template<class EntityImp , class DomainFieldImp , size_t domainDim, class RangeFieldImp , size_t rangeDim, size_t rangeDimCols = 1> ThisType& Dune::XT::Functions::ExpressionFunction< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::operator= (const ThisType & other) inline
template<class EntityImp , class DomainFieldImp , size_t domainDim, class RangeFieldImp , size_t rangeDim, size_t rangeDimCols = 1> virtual size_t Dune::XT::Functions::ExpressionFunction< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::order () const inline override virtual
Implements Dune::XT::Functions::GlobalFunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >.
template<class EntityImp, class DomainFieldImp, size_t domainDim, class RangeFieldImp, size_t rangeDim, size_t rangeDimCols = 1> virtual void Dune::XT::Functions::LocalizableFunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::report (std::ostream & out, const std::string prefix = "") const inline virtual inherited
template<class EntityImp , class DomainFieldImp , size_t domainDim, class RangeFieldImp , size_t rangeDim, size_t rangeDimCols = 1> static std::string Dune::XT::Functions::ExpressionFunction< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::static_id () inline static
References Dune::XT::Functions::LocalizableFunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::static_id().
Referenced by Dune::XT::Functions::ExpressionFunction< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::default_config(), and Dune::XT::Functions::TimeDependentExpressionFunction< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols, TimeFieldImp >::static_id().
template<class EntityImp, class DomainFieldImp, size_t domainDim, class RangeFieldImp, size_t rangeDim, size_t rangeDimCols = 1> template<class OtherEntityImp > Transfer<OtherEntityImp>::Type Dune::XT::Functions::GlobalFunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::transfer () const inline inherited
template<class EntityImp , class DomainFieldImp , size_t domainDim, class RangeFieldImp , size_t rangeDim, size_t rangeDimCols = 1> virtual std::string Dune::XT::Functions::ExpressionFunction< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::type () const inline final override virtual
Reimplemented from Dune::XT::Functions::GlobalFunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >.
References Dune::XT::Functions::LocalizableFunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::static_id().
template<class EntityImp, class DomainFieldImp, size_t domainDim, class RangeFieldImp, size_t rangeDim, size_t rangeDimCols = 1> template<class GridViewType > void Dune::XT::Functions::LocalizableFunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::visualize (const GridViewType & grid_view, const std::string path, const bool subsampling = true, const VTK::OutputType vtk_output_type = VTK::appendedraw) const inline inherited
Note
We use the SubsamplingVTKWriter (which is better for higher orders) by default. This means that the grid you see in the visualization is a refinement of the actual grid!
Member Data Documentation
template<class EntityImp, class DomainFieldImp, size_t domainDim, class RangeFieldImp, size_t rangeDim, size_t rangeDimCols = 1> const bool Dune::XT::Functions::LocalizableFunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::available = false static inherited
template<class EntityImp, class DomainFieldImp, size_t domainDim, class RangeFieldImp, size_t rangeDim, size_t rangeDimCols = 1> const constexpr size_t Dune::XT::Functions::LocalizableFunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::dimDomain = domainDim static inherited
template<class EntityImp, class DomainFieldImp, size_t domainDim, class RangeFieldImp, size_t rangeDim, size_t rangeDimCols = 1> const constexpr size_t Dune::XT::Functions::LocalizableFunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::dimRange = rangeDim static inherited
Referenced by Dune::XT::Functions::ExpressionFunction< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::evaluate(), and Dune::XT::Functions::ExpressionFunction< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::ExpressionFunction().
template<class EntityImp, class DomainFieldImp, size_t domainDim, class RangeFieldImp, size_t rangeDim, size_t rangeDimCols = 1> const constexpr size_t Dune::XT::Functions::LocalizableFunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::dimRangeCols = rangeDimCols static inherited
Referenced by Dune::XT::Functions::ExpressionFunction< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::create(), Dune::XT::Functions::ExpressionFunction< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::evaluate(), Dune::XT::Functions::ExpressionFunction< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::ExpressionFunction(), and Dune::XT::Functions::ExpressionFunction< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::jacobian().
The documentation for this class was generated from the following file:
expression.hh