Dune::XT::LA::CommonDenseVector< ScalarImp > Class Template Reference
Dune::XT::LA::CommonDenseVector< ScalarImp > Class Template Reference
A dense vector implementation of VectorInterface using the Dune::DynamicVector.
#include <dune/xt/la/container/common.hh>
Public Types
typedef
internal::CommonDenseVectorTraits
< ScalarImp > Traits
typedef Traits::ScalarType ScalarType
typedef Traits::RealType RealType
typedef Traits::DataType DataType
typedef Traits::BackendType BackendType
typedef
internal::CommonDenseVectorTraits
< ScalarImp >::derived_type derived_type
typedef
internal::VectorInputIterator
< internal::CommonDenseVectorTraits
< ScalarImp >, ScalarType > const_iterator
typedef
internal::VectorOutputIterator
< internal::CommonDenseVectorTraits
< ScalarImp >, ScalarType > iterator
Public Member Functions
CommonDenseVector (const size_t ss=0, const ScalarType value=ScalarType(0))
CommonDenseVector (const std::vector< ScalarType > &other)
CommonDenseVector (const std::initializer_list< ScalarType > &other)
CommonDenseVector (const ThisType &other)
CommonDenseVector (const BackendType &other, const bool=false, const ScalarType=Common::FloatCmp::DefaultEpsilon< ScalarType >::value())
CommonDenseVector (BackendType *backend_ptr)
CommonDenseVector (std::shared_ptr< BackendType > backend_ptr)
ThisType & operator= (const ThisType &other)
ThisType & operator= (const ScalarType &value)
ThisType & operator= (const BackendType &other)
Required by the ProvidesBackend interface.
BackendType & backend ()
const BackendType & backend () const
Required by ProvidesDataAccess.
ScalarType * data ()
size_t data_size () const
Required by ContainerInterface.
ThisType copy () const
void scal (const ScalarType &alpha)
void axpy (const ScalarType &alpha, const ThisType &xx)
bool has_equal_shape (const ThisType &other) const
Have to be implemented by a derived class in addition to the ones required by ContainerInterface!
void add_to_entry (const size_t ii, const ScalarType &value)
Add a scalar to the iith entry.
void set_entry (const size_t ii, const ScalarType &value)
Set the iith entry to given scalar.
Provided by the interface for convenience!
Note
Those marked as virtual may be implemented more efficiently in a derived class!
virtual void set_all (const ScalarType &val)
virtual bool valid () const
size_t dim () const
The dimension of the vector.
virtual ScalarType mean () const
virtual std::pair< size_t,
RealType > amax () const
The maximum absolute value of the vector.
virtual bool almost_equal (const derived_type &other, const ScalarType epsilon=Common::FloatCmp::DefaultEpsilon< ScalarType >::value()) const
Check vectors for equality. Equality of two vectors is defined as in Dune::FloatCmp componentwise.
bool almost_equal (const VectorInterface< T > &other, const ScalarType epsilon=Common::FloatCmp::DefaultEpsilon< ScalarType >::value()) const
Check vectors for equality (variant for arbitrary derived combinations). Equality of two vectors is defined as in Dune::FloatCmp componentwise.
virtual ScalarType dot (const derived_type &other) const
Computes the scalar products between two vectors.
virtual ScalarType standard_deviation () const
virtual void add (const derived_type &other, derived_type &result) const
Adds two vectors.
virtual derived_type add (const derived_type &other) const
Adds two vectors.
virtual void iadd (const derived_type &other)
Inplace variant of add().
virtual void sub (const derived_type &other, derived_type &result) const
Subtracts two vectors.
virtual derived_type sub (const derived_type &other) const
Subtracts two vectors.
virtual void isub (const derived_type &other)
Inplace variant of sub().
virtual derived_type operator* (const ScalarType &alpha) const
Multiplies every component of this by a scalar.
virtual ScalarType operator* (const derived_type &other) const
Computes the scalar products between this and another vector.
virtual derived_type & operator+= (const derived_type &other)
Adds another vector to this, in-place variant.
virtual derived_type & operator+= (const ScalarType &scalar)
virtual derived_type & operator-= (const derived_type &other)
Subtracts another vector from this, in-place variant.
virtual derived_type & operator-= (const ScalarType &scalar)
virtual derived_type operator+ (const derived_type &other) const
Adds two vectors.
virtual derived_type operator- (const derived_type &other) const
Substracts two vectors.
virtual derived_type & operator/= (const ScalarType &scalar)
virtual bool operator== (const derived_type &other) const
Check vectors for equality (componentwise) using almost_equal()
virtual bool operator!= (const derived_type &other) const
Check vectors for inequality using !almost_equal()
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
operator std::vector< ScalarType > () const
Have to be implemented by a derived class!
void scal (const ScalarType &alpha)
BLAS SCAL operation (in-place sclar multiplication).
void axpy (const ScalarType &alpha, const derived_type &xx)
BLAS AXPY operation.
bool has_equal_shape (const derived_type &other) const
Test for equal sizes.
Static Public Attributes
static const constexpr Backends dense_matrix_type
static const constexpr Backends sparse_matrix_type
static const constexpr Backends backend_type
Required by VectorInterface.
size_t size () const
void add_to_entry (const size_t ii, const ScalarType &value)
void set_entry (const size_t ii, const ScalarType &value)
ScalarType get_entry (const size_t ii) const
ScalarType & operator[] (const size_t ii)
const ScalarType & operator[] (const size_t ii) const
ScalarType & get_entry_ref (const size_t ii)
const ScalarType & get_entry_ref (const size_t ii) const
These methods override default implementations from VectorInterface.
virtual ScalarType dot (const ThisType &other) const overridefinal
virtual RealType l1_norm () const overridefinal
The l1-norm of the vector.
virtual RealType l2_norm () const overridefinal
The l2-norm of the vector.
virtual RealType sup_norm () const overridefinal
The l-infintiy-norm of the vector.
virtual void iadd (const ThisType &other) overridefinal
virtual void isub (const ThisType &other) overridefinal
void ensure_uniqueness ()
Are provided by the interface for convenience!
Note
Those marked as virtual may be implemented more efficiently in a derived class!
virtual derived_type & operator*= (const ScalarType &alpha)
static std::string type_this ()
Detailed Description
template<class ScalarImp>
class Dune::XT::LA::CommonDenseVector< ScalarImp >
A dense vector implementation of VectorInterface using the Dune::DynamicVector.
Member Typedef Documentation
template<class ScalarImp> typedef Traits::BackendType Dune::XT::LA::CommonDenseVector< ScalarImp >::BackendType
typedef internal::VectorInputIterator<internal::CommonDenseVectorTraits< ScalarImp > , ScalarType> Dune::XT::LA::VectorInterface< internal::CommonDenseVectorTraits< ScalarImp > , ScalarImp >::const_iterator inherited
template<class ScalarImp> typedef Traits::DataType Dune::XT::LA::CommonDenseVector< ScalarImp >::DataType
typedef internal::CommonDenseVectorTraits< ScalarImp > ::derived_type Dune::XT::LA::VectorInterface< internal::CommonDenseVectorTraits< ScalarImp > , ScalarImp >::derived_type inherited
typedef internal::VectorOutputIterator<internal::CommonDenseVectorTraits< ScalarImp > , ScalarType> Dune::XT::LA::VectorInterface< internal::CommonDenseVectorTraits< ScalarImp > , ScalarImp >::iterator inherited
template<class ScalarImp> typedef Traits::RealType Dune::XT::LA::CommonDenseVector< ScalarImp >::RealType
template<class ScalarImp> typedef Traits::ScalarType Dune::XT::LA::CommonDenseVector< ScalarImp >::ScalarType
template<class ScalarImp> typedef internal::CommonDenseVectorTraits<ScalarImp> Dune::XT::LA::CommonDenseVector< ScalarImp >::Traits
Constructor & Destructor Documentation
template<class ScalarImp> Dune::XT::LA::CommonDenseVector< ScalarImp >::CommonDenseVector (const size_t ss = 0, const ScalarType value = ScalarType(0)) inline explicit
template<class ScalarImp> Dune::XT::LA::CommonDenseVector< ScalarImp >::CommonDenseVector (const std::vector< ScalarType > & other) inline explicit
template<class ScalarImp> Dune::XT::LA::CommonDenseVector< ScalarImp >::CommonDenseVector (const std::initializer_list< ScalarType > & other) inline explicit
template<class ScalarImp> Dune::XT::LA::CommonDenseVector< ScalarImp >::CommonDenseVector (const ThisType & other) inline
template<class ScalarImp> Dune::XT::LA::CommonDenseVector< ScalarImp >::CommonDenseVector (const BackendType & other, const bool = false, const ScalarType = Common::FloatCmp::DefaultEpsilon<ScalarType>::value()) inline explicit
template<class ScalarImp> Dune::XT::LA::CommonDenseVector< ScalarImp >::CommonDenseVector (BackendType * backend_ptr) inline explicit
Note
Takes ownership of backend_ptr in the sense that you must not delete it afterwards!
template<class ScalarImp> Dune::XT::LA::CommonDenseVector< ScalarImp >::CommonDenseVector (std::shared_ptr< BackendType > backend_ptr) inline explicit
Member Function Documentation
virtual void Dune::XT::LA::VectorInterface< internal::CommonDenseVectorTraits< ScalarImp > , ScalarImp >::add (const derived_type & other, derived_type & result) const inline virtual inherited
Adds two vectors.
Parameters
other The right summand.
result Vector to write the result of this + other to
Note
If you override this method please use exceptions instead of assertions (for the python bindings).
If you are looking for the old (now deprecated) add() method,
See Also
add_to_entry().
References Dune::XT::LA::VectorInterface< Traits, ScalarImp >::get_entry_ref(), Dune::XT::LA::CommonDenseVector< ScalarImp >::get_entry_ref(), Dune::XT::LA::CommonDenseVector< ScalarImp >::set_entry(), Dune::XT::LA::VectorInterface< Traits, ScalarImp >::size(), and Dune::XT::LA::CommonDenseVector< ScalarImp >::size().
virtual derived_type Dune::XT::LA::VectorInterface< internal::CommonDenseVectorTraits< ScalarImp > , ScalarImp >::add (const derived_type & other) const inline virtual inherited
Adds two vectors.
Parameters
other The right summand.
Returns
The sum of this and other.
Note
If you override this method please use exceptions instead of assertions (for the python bindings).
If you are looking for the old (now deprecated) add() method,
See Also
add_to_entry().
References Dune::XT::LA::ContainerInterface< Traits, ScalarImp >::copy(), and Dune::XT::LA::CommonDenseVector< ScalarImp >::iadd().
void Dune::XT::LA::VectorInterface< internal::CommonDenseVectorTraits< ScalarImp > , ScalarImp >::add_to_entry (const size_t ii, const ScalarType & value) inline inherited
Add a scalar to the iith entry.
References Dune::XT::LA::VectorInterface< Traits, ScalarImp >::add_to_entry().
template<class ScalarImp> void Dune::XT::LA::CommonDenseVector< ScalarImp >::add_to_entry (const size_t ii, const ScalarType & value) inline
References Dune::XT::LA::CommonDenseVector< ScalarImp >::backend(), and Dune::XT::LA::CommonDenseVector< ScalarImp >::size().
virtual bool Dune::XT::LA::VectorInterface< internal::CommonDenseVectorTraits< ScalarImp > , ScalarImp >::almost_equal (const derived_type & other, const ScalarType epsilon = Common::FloatCmp::DefaultEpsilon<ScalarType>::value()) const inline virtual inherited
Check vectors for equality. Equality of two vectors is defined as in Dune::FloatCmp componentwise.
Parameters
other A vector of same dimension to compare with.
epsilon See Dune::FloatCmp.
Returns
Truth value of the comparison.
See Also
Dune::XT::Common::FloatCmp
Note
If you override this method please use exceptions instead of assertions (for the python bindings).
References Dune::XT::LA::VectorInterface< Traits, ScalarImp >::size(), and Dune::XT::LA::CommonDenseVector< ScalarImp >::size().
bool Dune::XT::LA::VectorInterface< internal::CommonDenseVectorTraits< ScalarImp > , ScalarImp >::almost_equal (const VectorInterface< T > & other, const ScalarType epsilon = Common::FloatCmp::DefaultEpsilon<ScalarType>::value()) const inline inherited
Check vectors for equality (variant for arbitrary derived combinations). Equality of two vectors is defined as in Dune::FloatCmp componentwise.
Parameters
other A vector of same dimension to compare with.
epsilon See Dune::FloatCmp.
Returns
Truth value of the comparison.
See Also
Dune::XT::Common::FloatCmp
References Dune::XT::LA::VectorInterface< Traits, ScalarImp >::size().
virtual std::pair<size_t, RealType> Dune::XT::LA::VectorInterface< internal::CommonDenseVectorTraits< ScalarImp > , ScalarImp >::amax () const inline virtual inherited
The maximum absolute value of the vector.
Returns
A pair of the lowest index at which the maximum is attained and the absolute maximum value.
Note
If you override this method please use exceptions instead of assertions (for the python bindings).
References Dune::XT::LA::VectorInterface< Traits, ScalarImp >::get_entry_ref(), and Dune::XT::LA::VectorInterface< Traits, ScalarImp >::size().
void Dune::XT::LA::ContainerInterface< internal::CommonDenseVectorTraits< ScalarImp > , ScalarImp >::axpy (const ScalarType & alpha, const derived_type & xx) inline inherited
BLAS AXPY operation.
Parameters
alpha The scalar coefficient with which each element of the container is multiplied
xx Container that is to be elementwise added.
References Dune::XT::LA::ContainerInterface< Traits, ScalarImp >::axpy().
template<class ScalarImp> void Dune::XT::LA::CommonDenseVector< ScalarImp >::axpy (const ScalarType & alpha, const ThisType & xx) inline
References Dune::XT::LA::CommonDenseVector< ScalarImp >::backend(), and Dune::XT::LA::CommonDenseVector< ScalarImp >::size().
template<class ScalarImp> BackendType& Dune::XT::LA::CommonDenseVector< ScalarImp >::backend () inline
References Dune::XT::LA::CommonDenseVector< ScalarImp >::ensure_uniqueness().
Referenced by Dune::XT::LA::CommonDenseVector< ScalarImp >::add_to_entry(), Dune::XT::LA::CommonDenseMatrix< ScalarImp >::add_to_entry(), Dune::XT::LA::Solver< CommonDenseMatrix< S >, CommunicatorType >::apply(), Dune::XT::LA::CommonDenseVector< ScalarImp >::axpy(), Dune::XT::LA::CommonDenseMatrix< ScalarImp >::axpy(), Dune::XT::LA::CommonDenseMatrix< ScalarImp >::clear_col(), Dune::XT::LA::CommonDenseMatrix< ScalarImp >::clear_row(), Dune::XT::LA::CommonDenseMatrix< ScalarImp >::cols(), Dune::XT::LA::CommonDenseVector< ScalarImp >::data(), Dune::XT::LA::CommonDenseVector< ScalarImp >::dot(), Dune::XT::LA::CommonDenseVector< ScalarImp >::get_entry(), Dune::XT::LA::CommonDenseMatrix< ScalarImp >::get_entry(), Dune::XT::LA::CommonDenseVector< ScalarImp >::iadd(), Dune::XT::LA::CommonDenseVector< ScalarImp >::isub(), Dune::XT::LA::CommonDenseVector< ScalarImp >::l1_norm(), Dune::XT::LA::CommonDenseVector< ScalarImp >::l2_norm(), Dune::XT::LA::CommonDenseMatrix< ScalarImp >::mv(), Dune::XT::LA::CommonDenseVector< ScalarImp >::operator[](), Dune::XT::LA::CommonDenseMatrix< ScalarImp >::rows(), Dune::XT::LA::CommonDenseVector< ScalarImp >::scal(), Dune::XT::LA::CommonDenseMatrix< ScalarImp >::scal(), Dune::XT::LA::CommonDenseVector< ScalarImp >::set_entry(), Dune::XT::LA::CommonDenseMatrix< ScalarImp >::set_entry(), Dune::XT::LA::CommonDenseVector< ScalarImp >::sup_norm(), Dune::XT::LA::CommonDenseMatrix< ScalarImp >::unit_col(), Dune::XT::LA::CommonDenseMatrix< ScalarImp >::unit_row(), and Dune::XT::LA::CommonDenseMatrix< ScalarImp >::valid().
template<class ScalarImp> const BackendType& Dune::XT::LA::CommonDenseVector< ScalarImp >::backend () const inline
iterator Dune::XT::LA::VectorInterface< internal::CommonDenseVectorTraits< ScalarImp > , ScalarImp >::begin () inline inherited
const_iterator Dune::XT::LA::VectorInterface< internal::CommonDenseVectorTraits< ScalarImp > , ScalarImp >::begin () const inline inherited
template<class ScalarImp> ThisType Dune::XT::LA::CommonDenseVector< ScalarImp >::copy () const inline
Referenced by Dune::XT::LA::Solver< CommonDenseMatrix< S >, CommunicatorType >::apply().
template<class ScalarImp> ScalarType* Dune::XT::LA::CommonDenseVector< ScalarImp >::data () inline
Attention
This makes only sense for scalar data types, not for complex!
References Dune::XT::LA::CommonDenseVector< ScalarImp >::backend().
template<class ScalarImp> size_t Dune::XT::LA::CommonDenseVector< ScalarImp >::data_size () const inline
References Dune::XT::LA::CommonDenseVector< ScalarImp >::size().
size_t Dune::XT::LA::VectorInterface< internal::CommonDenseVectorTraits< ScalarImp > , ScalarImp >::dim () const inline inherited
The dimension of the vector.
Returns
The dimension of the vector.
See Also
size()
References Dune::XT::LA::VectorInterface< Traits, ScalarImp >::size().
virtual ScalarType Dune::XT::LA::VectorInterface< internal::CommonDenseVectorTraits< ScalarImp > , ScalarImp >::dot (const derived_type & other) const inline virtual inherited
Computes the scalar products between two vectors.
Parameters
other The second factor.
Returns
The scalar product.
Note
If you override this method please use exceptions instead of assertions (for the python bindings).
References Dune::XT::LA::VectorInterface< Traits, ScalarImp >::get_entry_ref(), Dune::XT::LA::CommonDenseVector< ScalarImp >::get_entry_ref(), Dune::XT::LA::VectorInterface< Traits, ScalarImp >::size(), and Dune::XT::LA::CommonDenseVector< ScalarImp >::size().
template<class ScalarImp> virtual ScalarType Dune::XT::LA::CommonDenseVector< ScalarImp >::dot (const ThisType & other) const inline final override virtual
References Dune::XT::LA::CommonDenseVector< ScalarImp >::backend(), and Dune::XT::LA::CommonDenseVector< ScalarImp >::size().
iterator Dune::XT::LA::VectorInterface< internal::CommonDenseVectorTraits< ScalarImp > , ScalarImp >::end () inline inherited
const_iterator Dune::XT::LA::VectorInterface< internal::CommonDenseVectorTraits< ScalarImp > , ScalarImp >::end () const inline inherited
template<class ScalarImp> void Dune::XT::LA::CommonDenseVector< ScalarImp >::ensure_uniqueness () inline protected
See Also
ContainerInterface
Referenced by Dune::XT::LA::CommonSparseMatrix< ScalarImp >::add_to_entry(), Dune::XT::LA::CommonSparseMatrix< ScalarImp >::axpy(), Dune::XT::LA::CommonDenseVector< ScalarImp >::backend(), Dune::XT::LA::CommonDenseMatrix< ScalarImp >::backend(), Dune::XT::LA::CommonSparseMatrix< ScalarImp >::clear_col(), Dune::XT::LA::CommonSparseMatrix< ScalarImp >::clear_row(), Dune::XT::LA::CommonDenseVector< ScalarImp >::operator=(), Dune::XT::LA::CommonSparseMatrix< ScalarImp >::scal(), Dune::XT::LA::CommonSparseMatrix< ScalarImp >::set_entry(), Dune::XT::LA::CommonSparseMatrix< ScalarImp >::unit_col(), and Dune::XT::LA::CommonSparseMatrix< ScalarImp >::unit_row().
template<class ScalarImp> ScalarType Dune::XT::LA::CommonDenseVector< ScalarImp >::get_entry (const size_t ii) const inline
References Dune::XT::LA::CommonDenseVector< ScalarImp >::backend(), and Dune::XT::LA::CommonDenseVector< ScalarImp >::size().
template<class ScalarImp> ScalarType& Dune::XT::LA::CommonDenseVector< ScalarImp >::get_entry_ref (const size_t ii) inline protected
Referenced by Dune::XT::LA::VectorInterface< internal::CommonDenseVectorTraits< ScalarImp >, ScalarImp >::add(), Dune::XT::LA::VectorInterface< internal::CommonDenseVectorTraits< ScalarImp >, ScalarImp >::dot(), Dune::XT::LA::VectorInterface< internal::CommonDenseVectorTraits< ScalarImp >, ScalarImp >::iadd(), Dune::XT::LA::VectorInterface< internal::CommonDenseVectorTraits< ScalarImp >, ScalarImp >::isub(), and Dune::XT::LA::VectorInterface< internal::CommonDenseVectorTraits< ScalarImp >, ScalarImp >::sub().
template<class ScalarImp> const ScalarType& Dune::XT::LA::CommonDenseVector< ScalarImp >::get_entry_ref (const size_t ii) const inline protected
bool Dune::XT::LA::ContainerInterface< internal::CommonDenseVectorTraits< ScalarImp > , ScalarImp >::has_equal_shape (const derived_type & other) const inline inherited
Test for equal sizes.
Parameters
other Container the sizes of which this is to be compared to.
References Dune::XT::LA::ContainerInterface< Traits, ScalarImp >::has_equal_shape().
template<class ScalarImp> bool Dune::XT::LA::CommonDenseVector< ScalarImp >::has_equal_shape (const ThisType & other) const inline
References Dune::XT::LA::CommonDenseVector< ScalarImp >::size().
Referenced by Dune::XT::LA::CommonDenseMatrix< ScalarImp >::axpy(), and Dune::XT::LA::CommonSparseMatrix< ScalarImp >::axpy().
virtual void Dune::XT::LA::VectorInterface< internal::CommonDenseVectorTraits< ScalarImp > , ScalarImp >::iadd (const derived_type & other) inline virtual inherited
Inplace variant of add().
Parameters
other The right summand.
Note
If you override this method please use exceptions instead of assertions (for the python bindings).
References Dune::XT::LA::VectorInterface< Traits, ScalarImp >::get_entry_ref(), Dune::XT::LA::CommonDenseVector< ScalarImp >::get_entry_ref(), Dune::XT::LA::VectorInterface< Traits, ScalarImp >::set_entry(), Dune::XT::LA::VectorInterface< Traits, ScalarImp >::size(), and Dune::XT::LA::CommonDenseVector< ScalarImp >::size().
template<class ScalarImp> virtual void Dune::XT::LA::CommonDenseVector< ScalarImp >::iadd (const ThisType & other) inline final override virtual
References Dune::XT::LA::CommonDenseVector< ScalarImp >::backend(), and Dune::XT::LA::CommonDenseVector< ScalarImp >::size().
Referenced by Dune::XT::LA::VectorInterface< internal::CommonDenseVectorTraits< ScalarImp >, ScalarImp >::add().
template<class ScalarImp> virtual void Dune::XT::LA::CommonDenseVector< ScalarImp >::isub (const ThisType & other) inline final override virtual
References Dune::XT::LA::CommonDenseVector< ScalarImp >::backend(), and Dune::XT::LA::CommonDenseVector< ScalarImp >::size().
Referenced by Dune::XT::LA::VectorInterface< internal::CommonDenseVectorTraits< ScalarImp >, ScalarImp >::sub().
virtual void Dune::XT::LA::VectorInterface< internal::CommonDenseVectorTraits< ScalarImp > , ScalarImp >::isub (const derived_type & other) inline virtual inherited
Inplace variant of sub().
Parameters
other The subtrahend.
Note
If you override this method please use exceptions instead of assertions (for the python bindings).
References Dune::XT::LA::VectorInterface< Traits, ScalarImp >::get_entry_ref(), Dune::XT::LA::CommonDenseVector< ScalarImp >::get_entry_ref(), Dune::XT::LA::VectorInterface< Traits, ScalarImp >::set_entry(), Dune::XT::LA::VectorInterface< Traits, ScalarImp >::size(), and Dune::XT::LA::CommonDenseVector< ScalarImp >::size().
template<class ScalarImp> virtual RealType Dune::XT::LA::CommonDenseVector< ScalarImp >::l1_norm () const inline final override virtual
The l1-norm of the vector.
Returns
The l1-norm of the vector.
Note
If you override this method please use exceptions instead of assertions (for the python bindings).
Reimplemented from Dune::XT::LA::VectorInterface< internal::CommonDenseVectorTraits< ScalarImp >, ScalarImp >.
References Dune::XT::LA::CommonDenseVector< ScalarImp >::backend().
template<class ScalarImp> virtual RealType Dune::XT::LA::CommonDenseVector< ScalarImp >::l2_norm () const inline final override virtual
The l2-norm of the vector.
Returns
The l2-norm of the vector.
Note
If you override this method please use exceptions instead of assertions (for the python bindings).
Reimplemented from Dune::XT::LA::VectorInterface< internal::CommonDenseVectorTraits< ScalarImp >, ScalarImp >.
References Dune::XT::LA::CommonDenseVector< ScalarImp >::backend().
virtual ScalarType Dune::XT::LA::VectorInterface< internal::CommonDenseVectorTraits< ScalarImp > , ScalarImp >::mean () const inline virtual inherited
References Dune::XT::LA::VectorInterface< Traits, ScalarImp >::size().
Dune::XT::LA::VectorInterface< internal::CommonDenseVectorTraits< ScalarImp > , ScalarImp >::operator std::vector< ScalarType > () const inline inherited
References Dune::XT::LA::VectorInterface< Traits, ScalarImp >::dim().
virtual bool Dune::XT::LA::VectorInterface< internal::CommonDenseVectorTraits< ScalarImp > , ScalarImp >::operator!= (const derived_type & other) const inline virtual inherited
Check vectors for inequality using !almost_equal()
Parameters
other A vector of same dimension to compare with.
Returns
Truth value of the comparison.
References Dune::XT::LA::VectorInterface< Traits, ScalarImp >::operator==().
virtual derived_type Dune::XT::LA::VectorInterface< internal::CommonDenseVectorTraits< ScalarImp > , ScalarImp >::operator* (const ScalarType & alpha) const inline virtual inherited
Multiplies every component of this by a scalar.
Parameters
alpha The scalar.
Returns
The scaled copy of this.
References Dune::XT::LA::ContainerInterface< Traits, ScalarImp >::copy().
virtual ScalarType Dune::XT::LA::VectorInterface< internal::CommonDenseVectorTraits< ScalarImp > , ScalarImp >::operator* (const derived_type & other) const inline virtual inherited
Computes the scalar products between this and another vector.
Parameters
other The second factor.
Returns
The scalar product.
See Also
dot()
References Dune::XT::LA::VectorInterface< Traits, ScalarImp >::dot().
virtual derived_type& Dune::XT::LA::ContainerInterface< internal::CommonDenseVectorTraits< ScalarImp > , ScalarImp >::operator*= (const ScalarType & alpha) inline virtual inherited
References Dune::XT::LA::ContainerInterface< Traits, ScalarImp >::scal().
virtual derived_type Dune::XT::LA::VectorInterface< internal::CommonDenseVectorTraits< ScalarImp > , ScalarImp >::operator+ (const derived_type & other) const inline virtual inherited
Adds two vectors.
Parameters
other The second summand.
Returns
The sum of the two vectors.
References Dune::XT::LA::VectorInterface< Traits, ScalarImp >::add().
virtual derived_type& Dune::XT::LA::VectorInterface< internal::CommonDenseVectorTraits< ScalarImp > , ScalarImp >::operator+= (const derived_type & other) inline virtual inherited
Adds another vector to this, in-place variant.
Parameters
other The second summand.
Returns
The sum of this and other.
References Dune::XT::LA::VectorInterface< Traits, ScalarImp >::iadd().
virtual derived_type& Dune::XT::LA::VectorInterface< internal::CommonDenseVectorTraits< ScalarImp > , ScalarImp >::operator+= (const ScalarType & scalar) inline virtual inherited
virtual derived_type Dune::XT::LA::VectorInterface< internal::CommonDenseVectorTraits< ScalarImp > , ScalarImp >::operator- (const derived_type & other) const inline virtual inherited
Substracts two vectors.
Parameters
other The subtrahend
Returns
The difference.
References Dune::XT::LA::VectorInterface< Traits, ScalarImp >::sub().
virtual derived_type& Dune::XT::LA::VectorInterface< internal::CommonDenseVectorTraits< ScalarImp > , ScalarImp >::operator-= (const derived_type & other) inline virtual inherited
Subtracts another vector from this, in-place variant.
Parameters
other The subtrahend.
Returns
The difference between this and other.
References Dune::XT::LA::VectorInterface< Traits, ScalarImp >::isub().
virtual derived_type& Dune::XT::LA::VectorInterface< internal::CommonDenseVectorTraits< ScalarImp > , ScalarImp >::operator-= (const ScalarType & scalar) inline virtual inherited
virtual derived_type& Dune::XT::LA::VectorInterface< internal::CommonDenseVectorTraits< ScalarImp > , ScalarImp >::operator/= (const ScalarType & scalar) inline virtual inherited
template<class ScalarImp> ThisType& Dune::XT::LA::CommonDenseVector< ScalarImp >::operator= (const ThisType & other) inline
template<class ScalarImp> ThisType& Dune::XT::LA::CommonDenseVector< ScalarImp >::operator= (const ScalarType & value) inline
References Dune::XT::LA::CommonDenseVector< ScalarImp >::ensure_uniqueness().
template<class ScalarImp> ThisType& Dune::XT::LA::CommonDenseVector< ScalarImp >::operator= (const BackendType & other) inline
Note
Does a deep copy.
virtual bool Dune::XT::LA::VectorInterface< internal::CommonDenseVectorTraits< ScalarImp > , ScalarImp >::operator== (const derived_type & other) const inline virtual inherited
Check vectors for equality (componentwise) using almost_equal()
Parameters
other A vector of same dimension to compare with.
Returns
Truth value of the comparison.
See Also
almost_equal()
References Dune::XT::LA::VectorInterface< Traits, ScalarImp >::almost_equal().
template<class ScalarImp> ScalarType& Dune::XT::LA::CommonDenseVector< ScalarImp >::operator[] (const size_t ii) inline
References Dune::XT::LA::CommonDenseVector< ScalarImp >::backend().
template<class ScalarImp> const ScalarType& Dune::XT::LA::CommonDenseVector< ScalarImp >::operator[] (const size_t ii) const inline
References Dune::XT::LA::CommonDenseVector< ScalarImp >::backend().
void Dune::XT::LA::ContainerInterface< internal::CommonDenseVectorTraits< ScalarImp > , ScalarImp >::scal (const ScalarType & alpha) inline inherited
BLAS SCAL operation (in-place sclar multiplication).
Parameters
alpha The scalar coefficient with which each element of the container is multiplied.
References Dune::XT::LA::ContainerInterface< Traits, ScalarImp >::scal().
template<class ScalarImp> void Dune::XT::LA::CommonDenseVector< ScalarImp >::scal (const ScalarType & alpha) inline
References Dune::XT::LA::CommonDenseVector< ScalarImp >::backend().
virtual void Dune::XT::LA::VectorInterface< internal::CommonDenseVectorTraits< ScalarImp > , ScalarImp >::set_all (const ScalarType & val) inline virtual inherited
void Dune::XT::LA::VectorInterface< internal::CommonDenseVectorTraits< ScalarImp > , ScalarImp >::set_entry (const size_t ii, const ScalarType & value) inline inherited
Set the iith entry to given scalar.
References Dune::XT::LA::VectorInterface< Traits, ScalarImp >::set_entry().
template<class ScalarImp> void Dune::XT::LA::CommonDenseVector< ScalarImp >::set_entry (const size_t ii, const ScalarType & value) inline
References Dune::XT::LA::CommonDenseVector< ScalarImp >::backend(), and Dune::XT::LA::CommonDenseVector< ScalarImp >::size().
Referenced by Dune::XT::LA::VectorInterface< internal::CommonDenseVectorTraits< ScalarImp >, ScalarImp >::add(), Dune::XT::LA::CommonDenseMatrix< ScalarImp >::CommonDenseMatrix(), Dune::XT::LA::VectorInterface< internal::CommonDenseVectorTraits< ScalarImp >, ScalarImp >::sub(), Dune::XT::LA::CommonSparseMatrix< ScalarImp >::unit_col(), and Dune::XT::LA::CommonSparseMatrix< ScalarImp >::unit_row().
template<class ScalarImp> size_t Dune::XT::LA::CommonDenseVector< ScalarImp >::size () const inline
Referenced by Dune::XT::LA::VectorInterface< internal::CommonDenseVectorTraits< ScalarImp >, ScalarImp >::add(), Dune::XT::LA::CommonDenseVector< ScalarImp >::add_to_entry(), Dune::XT::LA::VectorInterface< internal::CommonDenseVectorTraits< ScalarImp >, ScalarImp >::almost_equal(), Dune::XT::LA::CommonDenseVector< ScalarImp >::axpy(), Dune::XT::LA::CommonDenseVector< ScalarImp >::data_size(), Dune::XT::LA::VectorInterface< internal::CommonDenseVectorTraits< ScalarImp >, ScalarImp >::dot(), Dune::XT::LA::CommonDenseVector< ScalarImp >::dot(), Dune::XT::LA::CommonDenseVector< ScalarImp >::get_entry(), Dune::XT::LA::CommonDenseVector< ScalarImp >::has_equal_shape(), Dune::XT::LA::VectorInterface< internal::CommonDenseVectorTraits< ScalarImp >, ScalarImp >::iadd(), Dune::XT::LA::CommonDenseVector< ScalarImp >::iadd(), Dune::XT::LA::CommonDenseVector< ScalarImp >::isub(), Dune::XT::LA::VectorInterface< internal::CommonDenseVectorTraits< ScalarImp >, ScalarImp >::isub(), Dune::XT::LA::CommonDenseVector< ScalarImp >::set_entry(), and Dune::XT::LA::VectorInterface< internal::CommonDenseVectorTraits< ScalarImp >, ScalarImp >::sub().
virtual ScalarType Dune::XT::LA::VectorInterface< internal::CommonDenseVectorTraits< ScalarImp > , ScalarImp >::standard_deviation () const inline virtual inherited
References Dune::XT::LA::VectorInterface< Traits, ScalarImp >::mean(), and Dune::XT::LA::VectorInterface< Traits, ScalarImp >::size().
virtual void Dune::XT::LA::VectorInterface< internal::CommonDenseVectorTraits< ScalarImp > , ScalarImp >::sub (const derived_type & other, derived_type & result) const inline virtual inherited
Subtracts two vectors.
Parameters
other The subtrahend.
result The vectror to write the difference between this and other to.
Note
If you override this method please use exceptions instead of assertions (for the python bindings).
References Dune::XT::LA::VectorInterface< Traits, ScalarImp >::get_entry_ref(), Dune::XT::LA::CommonDenseVector< ScalarImp >::get_entry_ref(), Dune::XT::LA::CommonDenseVector< ScalarImp >::set_entry(), Dune::XT::LA::VectorInterface< Traits, ScalarImp >::size(), and Dune::XT::LA::CommonDenseVector< ScalarImp >::size().
virtual derived_type Dune::XT::LA::VectorInterface< internal::CommonDenseVectorTraits< ScalarImp > , ScalarImp >::sub (const derived_type & other) const inline virtual inherited
Subtracts two vectors.
Parameters
other The subtrahend.
Returns
The difference between this and other.
Note
If you override this method please use exceptions instead of assertions (for the python bindings).
References Dune::XT::LA::ContainerInterface< Traits, ScalarImp >::copy(), and Dune::XT::LA::CommonDenseVector< ScalarImp >::isub().
template<class ScalarImp> virtual RealType Dune::XT::LA::CommonDenseVector< ScalarImp >::sup_norm () const inline final override virtual
The l-infintiy-norm of the vector.
Returns
The l-infintiy-norm of the vector.
Note
If you override this method please use exceptions instead of assertions (for the python bindings).
Reimplemented from Dune::XT::LA::VectorInterface< internal::CommonDenseVectorTraits< ScalarImp >, ScalarImp >.
References Dune::XT::LA::CommonDenseVector< ScalarImp >::backend().
Referenced by Dune::XT::LA::Solver< CommonDenseMatrix< S >, CommunicatorType >::apply().
static std::string Dune::XT::LA::ContainerInterface< internal::CommonDenseVectorTraits< ScalarImp > , ScalarImp >::type_this () inline static inherited
virtual bool Dune::XT::LA::VectorInterface< internal::CommonDenseVectorTraits< ScalarImp > , ScalarImp >::valid () const inline virtual inherited
Member Data Documentation
const constexpr Backends Dune::XT::LA::ProvidesBackend< internal::CommonDenseVectorTraits< ScalarImp > >::backend_type static inherited
const constexpr Backends Dune::XT::LA::VectorInterface< internal::CommonDenseVectorTraits< ScalarImp > , ScalarImp >::dense_matrix_type static inherited
const constexpr Backends Dune::XT::LA::VectorInterface< internal::CommonDenseVectorTraits< ScalarImp > , ScalarImp >::sparse_matrix_type static inherited
The documentation for this class was generated from the following file:
container/common.hh