Dune::XT::LA::MatrixInterface< Traits, ScalarImp > Class Template Reference
Dune::XT::LA::MatrixInterface< Traits, ScalarImp > Class Template Reference
#include <dune/xt/la/container/matrix-interface.hh>
Public Types
typedef Traits::derived_type derived_type
typedef Dune::FieldTraits
< ScalarImp >::field_type ScalarType
typedef Dune::FieldTraits
< ScalarImp >::real_type RealType
Public Member Functions
virtual ~MatrixInterface ()
Have to be implemented by a derived class in addition to the ones required by ContainerInterface!
size_t rows () const
size_t cols () const
template<class XX , class YY >
void mv (const XX &xx, YY &yy) const
void add_to_entry (const size_t ii, const size_t jj, const ScalarType &value)
void set_entry (const size_t ii, const size_t jj, const ScalarType &value)
ScalarType get_entry (const size_t ii, const size_t jj) const
void clear_row (const size_t ii)
void clear_col (const size_t jj)
void unit_row (const size_t ii)
void unit_col (const size_t jj)
bool valid () const
Checks entries for inf or nan.
Static Public Attributes
static const constexpr Backends vector_type = Traits::vector_type
Have to be implemented by a derived class!
derived_type copy () const
Creates a (deep) copy of the underlying resource.
void scal (const ScalarType &alpha)
BLAS SCAL operation (in-place sclar multiplication).
void axpy (const ScalarType &alpha, const derived_type &xx)
BLAS AXPY operation.
bool has_equal_shape (const derived_type &other) const
Test for equal sizes.
void ensure_uniqueness ()
Are provided by the interface for convenience!
Note
Those marked as virtual may be implemented more efficiently in a derived class!
virtual derived_type & operator*= (const ScalarType &alpha)
static std::string type_this ()
Provided by the interface for convenience.
Note
Those marked with vitual should be overriden by any devired class that can do better.
template<class XX >
XX::derived_type operator* (const VectorInterface< XX, ScalarType > &xx) const
virtual RealType sup_norm () const
virtual size_t non_zeros () const
Returns the number of entries in the sparsity pattern of the matrix.
virtual SparsityPatternDefault pattern (const bool prune=false, const typename Common::FloatCmp::DefaultEpsilon< ScalarType >::Type eps=Common::FloatCmp::DefaultEpsilon< ScalarType >::value()) const
Computes the sparsity pattern of the matrix.
virtual derived_type pruned (const typename Common::FloatCmp::DefaultEpsilon< ScalarType >::Type eps=Common::FloatCmp::DefaultEpsilon< ScalarType >::value()) const
Returns a pruned variant of this matrix.
template<class T , class S >
std::ostream & operator<< (std::ostream &, const MatrixInterface< T, S > &)
Member Typedef Documentation
template<class Traits, class ScalarImp = typename Traits::ScalarType> typedef Traits::derived_type Dune::XT::LA::MatrixInterface< Traits, ScalarImp >::derived_type
template<class Traits, class ScalarImp = typename Traits::ScalarType> typedef Dune::FieldTraits<ScalarImp>::real_type Dune::XT::LA::MatrixInterface< Traits, ScalarImp >::RealType
template<class Traits, class ScalarImp = typename Traits::ScalarType> typedef Dune::FieldTraits<ScalarImp>::field_type Dune::XT::LA::MatrixInterface< Traits, ScalarImp >::ScalarType
Constructor & Destructor Documentation
template<class Traits, class ScalarImp = typename Traits::ScalarType> virtual Dune::XT::LA::MatrixInterface< Traits, ScalarImp >::~MatrixInterface () inline virtual
Member Function Documentation
template<class Traits, class ScalarImp = typename Traits::ScalarType> void Dune::XT::LA::MatrixInterface< Traits, ScalarImp >::add_to_entry (const size_t ii, const size_t jj, const ScalarType & value) inline
Referenced by Dune::XT::LA::MatrixInterface< internal::CommonDenseMatrixTraits< ScalarImp >, ScalarImp >::add_to_entry().
template<class Traits, class ScalarImp = typename Traits::ScalarType> void Dune::XT::LA::ContainerInterface< Traits, ScalarImp >::axpy (const ScalarType & alpha, const derived_type & xx) inline inherited
BLAS AXPY operation.
Parameters
alpha The scalar coefficient with which each element of the container is multiplied
xx Container that is to be elementwise added.
Referenced by Dune::XT::LA::ContainerInterface< internal::CommonDenseVectorTraits< ScalarImp >, ScalarImp >::axpy().
template<class Traits, class ScalarImp = typename Traits::ScalarType> void Dune::XT::LA::MatrixInterface< Traits, ScalarImp >::clear_col (const size_t jj) inline
Referenced by Dune::XT::LA::MatrixInterface< internal::CommonDenseMatrixTraits< ScalarImp >, ScalarImp >::clear_col().
template<class Traits, class ScalarImp = typename Traits::ScalarType> void Dune::XT::LA::MatrixInterface< Traits, ScalarImp >::clear_row (const size_t ii) inline
Referenced by Dune::XT::LA::MatrixInterface< internal::CommonDenseMatrixTraits< ScalarImp >, ScalarImp >::clear_row().
template<class Traits, class ScalarImp = typename Traits::ScalarType> size_t Dune::XT::LA::MatrixInterface< Traits, ScalarImp >::cols () const inline
Referenced by Dune::XT::LA::MatrixInterface< internal::CommonDenseMatrixTraits< ScalarImp >, ScalarImp >::cols(), Dune::XT::LA::MatrixInterface< internal::CommonDenseMatrixTraits< ScalarImp >, ScalarImp >::non_zeros(), Dune::XT::LA::MatrixInterface< internal::CommonDenseMatrixTraits< ScalarImp >, ScalarImp >::pattern(), Dune::XT::LA::MatrixInterface< internal::CommonDenseMatrixTraits< ScalarImp >, ScalarImp >::pruned(), and Dune::XT::LA::MatrixInterface< internal::CommonDenseMatrixTraits< ScalarImp >, ScalarImp >::sup_norm().
template<class Traits, class ScalarImp = typename Traits::ScalarType> derived_type Dune::XT::LA::ContainerInterface< Traits, ScalarImp >::copy () const inline inherited
Creates a (deep) copy of the underlying resource.
Returns
A new container
Referenced by Dune::XT::LA::VectorInterface< internal::CommonDenseVectorTraits< ScalarImp >, ScalarImp >::add(), Dune::XT::LA::ContainerInterface< internal::CommonDenseVectorTraits< ScalarImp >, ScalarImp >::copy(), Dune::XT::LA::VectorInterface< internal::CommonDenseVectorTraits< ScalarImp >, ScalarImp >::operator*(), and Dune::XT::LA::VectorInterface< internal::CommonDenseVectorTraits< ScalarImp >, ScalarImp >::sub().
template<class Traits, class ScalarImp = typename Traits::ScalarType> void Dune::XT::LA::ContainerInterface< Traits, ScalarImp >::ensure_uniqueness () inline protected inherited
Referenced by Dune::XT::LA::ContainerInterface< internal::CommonDenseVectorTraits< ScalarImp >, ScalarImp >::ensure_uniqueness().
template<class Traits, class ScalarImp = typename Traits::ScalarType> ScalarType Dune::XT::LA::MatrixInterface< Traits, ScalarImp >::get_entry (const size_t ii, const size_t jj) const inline
Referenced by Dune::XT::LA::MatrixInterface< internal::CommonDenseMatrixTraits< ScalarImp >, ScalarImp >::get_entry(), Dune::XT::LA::MatrixInterface< internal::CommonDenseMatrixTraits< ScalarImp >, ScalarImp >::pattern(), Dune::XT::LA::MatrixInterface< internal::CommonDenseMatrixTraits< ScalarImp >, ScalarImp >::pruned(), and Dune::XT::LA::MatrixInterface< internal::CommonDenseMatrixTraits< ScalarImp >, ScalarImp >::sup_norm().
template<class Traits, class ScalarImp = typename Traits::ScalarType> bool Dune::XT::LA::ContainerInterface< Traits, ScalarImp >::has_equal_shape (const derived_type & other) const inline inherited
Test for equal sizes.
Parameters
other Container the sizes of which this is to be compared to.
Referenced by Dune::XT::LA::ContainerInterface< internal::CommonDenseVectorTraits< ScalarImp >, ScalarImp >::has_equal_shape().
template<class Traits, class ScalarImp = typename Traits::ScalarType> template<class XX , class YY > void Dune::XT::LA::MatrixInterface< Traits, ScalarImp >::mv (const XX & xx, YY & yy) const inline
Referenced by Dune::XT::LA::MatrixInterface< internal::CommonDenseMatrixTraits< ScalarImp >, ScalarImp >::mv(), and Dune::XT::LA::MatrixInterface< internal::CommonDenseMatrixTraits< ScalarImp >, ScalarImp >::operator*().
template<class Traits, class ScalarImp = typename Traits::ScalarType> virtual size_t Dune::XT::LA::MatrixInterface< Traits, ScalarImp >::non_zeros () const inline virtual
Returns the number of entries in the sparsity pattern of the matrix.
This is mainly useful for sparse matrices and returns rows() times cols() for dense matrices.
Note
Some implementations do not report the correct number here, so use and interpret only if you know what you are doing!
Reimplemented in Dune::XT::LA::CommonSparseMatrix< ScalarImp >.
template<class Traits, class ScalarImp = typename Traits::ScalarType> template<class XX > XX::derived_type Dune::XT::LA::MatrixInterface< Traits, ScalarImp >::operator* (const VectorInterface< XX, ScalarType > & xx) const inline
template<class Traits, class ScalarImp = typename Traits::ScalarType> virtual derived_type& Dune::XT::LA::ContainerInterface< Traits, ScalarImp >::operator*= (const ScalarType & alpha) inline virtual inherited
template<class Traits, class ScalarImp = typename Traits::ScalarType> virtual SparsityPatternDefault Dune::XT::LA::MatrixInterface< Traits, ScalarImp >::pattern (const bool prune = false, const typename Common::FloatCmp::DefaultEpsilon< ScalarType >::Type eps = Common::FloatCmp::DefaultEpsilon<ScalarType>::value()) const inline virtual
Computes the sparsity pattern of the matrix.
This is mainly useful for sparse matrices and returns a full pattern for dense matrices
Parameters
prune If true, treats all entries smaller than eps as zero and does not include these indices in the returned pattern
Referenced by Dune::XT::LA::MatrixInterface< internal::CommonDenseMatrixTraits< ScalarImp >, ScalarImp >::pruned().
template<class Traits, class ScalarImp = typename Traits::ScalarType> virtual derived_type Dune::XT::LA::MatrixInterface< Traits, ScalarImp >::pruned (const typename Common::FloatCmp::DefaultEpsilon< ScalarType >::Type eps = Common::FloatCmp::DefaultEpsilon<ScalarType>::value()) const inline virtual
Returns a pruned variant of this matrix.
This is mainly useful for sparse matrices and returns a matrix that should be very close to this matrix, except for very small values, which are set to zero and the entries of which are removed from the sparsity pattern.
See Also
pattern
Parameters
eps Is forwarded to pattern(true, eps)
Referenced by Dune::XT::LA::CommonDenseMatrix< ScalarImp >::CommonDenseMatrix().
template<class Traits, class ScalarImp = typename Traits::ScalarType> size_t Dune::XT::LA::MatrixInterface< Traits, ScalarImp >::rows () const inline
Referenced by Dune::XT::LA::MatrixInterface< internal::CommonDenseMatrixTraits< ScalarImp >, ScalarImp >::non_zeros(), Dune::XT::LA::MatrixInterface< internal::CommonDenseMatrixTraits< ScalarImp >, ScalarImp >::operator*(), Dune::XT::LA::MatrixInterface< internal::CommonDenseMatrixTraits< ScalarImp >, ScalarImp >::pattern(), Dune::XT::LA::MatrixInterface< internal::CommonDenseMatrixTraits< ScalarImp >, ScalarImp >::pruned(), Dune::XT::LA::MatrixInterface< internal::CommonDenseMatrixTraits< ScalarImp >, ScalarImp >::rows(), and Dune::XT::LA::MatrixInterface< internal::CommonDenseMatrixTraits< ScalarImp >, ScalarImp >::sup_norm().
template<class Traits, class ScalarImp = typename Traits::ScalarType> void Dune::XT::LA::ContainerInterface< Traits, ScalarImp >::scal (const ScalarType & alpha) inline inherited
BLAS SCAL operation (in-place sclar multiplication).
Parameters
alpha The scalar coefficient with which each element of the container is multiplied.
Referenced by Dune::XT::LA::ContainerInterface< internal::CommonDenseVectorTraits< ScalarImp >, ScalarImp >::operator*=(), and Dune::XT::LA::ContainerInterface< internal::CommonDenseVectorTraits< ScalarImp >, ScalarImp >::scal().
template<class Traits, class ScalarImp = typename Traits::ScalarType> void Dune::XT::LA::MatrixInterface< Traits, ScalarImp >::set_entry (const size_t ii, const size_t jj, const ScalarType & value) inline
Referenced by Dune::XT::LA::MatrixInterface< internal::CommonDenseMatrixTraits< ScalarImp >, ScalarImp >::set_entry().
template<class Traits, class ScalarImp = typename Traits::ScalarType> virtual RealType Dune::XT::LA::MatrixInterface< Traits, ScalarImp >::sup_norm () const inline virtual
template<class Traits, class ScalarImp = typename Traits::ScalarType> static std::string Dune::XT::LA::ContainerInterface< Traits, ScalarImp >::type_this () inline static inherited
template<class Traits, class ScalarImp = typename Traits::ScalarType> void Dune::XT::LA::MatrixInterface< Traits, ScalarImp >::unit_col (const size_t jj) inline
Referenced by Dune::XT::LA::MatrixInterface< internal::CommonDenseMatrixTraits< ScalarImp >, ScalarImp >::unit_col().
template<class Traits, class ScalarImp = typename Traits::ScalarType> void Dune::XT::LA::MatrixInterface< Traits, ScalarImp >::unit_row (const size_t ii) inline
Referenced by Dune::XT::LA::MatrixInterface< internal::CommonDenseMatrixTraits< ScalarImp >, ScalarImp >::unit_row().
template<class Traits, class ScalarImp = typename Traits::ScalarType> bool Dune::XT::LA::MatrixInterface< Traits, ScalarImp >::valid () const inline
Checks entries for inf or nan.
Returns
false if any entry is inf or nan, else true
Referenced by Dune::XT::LA::MatrixInterface< internal::CommonDenseMatrixTraits< ScalarImp >, ScalarImp >::valid().
Friends And Related Function Documentation
template<class Traits, class ScalarImp = typename Traits::ScalarType> template<class T , class S > std::ostream& operator<< (std::ostream & out, const MatrixInterface< T, S > & matrix) friend
Member Data Documentation
template<class Traits, class ScalarImp = typename Traits::ScalarType> const constexpr Backends Dune::XT::LA::MatrixInterface< Traits, ScalarImp >::vector_type = Traits::vector_type static
The documentation for this class was generated from the following file:
matrix-interface.hh