Dune::XT::LA::CommonDenseMatrix< ScalarImp > Class Template Reference
Dune::XT::LA::CommonDenseMatrix< ScalarImp > Class Template Reference
A dense matrix implementation of MatrixInterface using the Dune::DynamicMatrix.
#include <dune/xt/la/container/common.hh>
Public Types
typedef
internal::CommonDenseMatrixTraits
< ScalarImp > Traits
typedef Traits::BackendType BackendType
typedef Traits::ScalarType ScalarType
typedef Traits::RealType RealType
typedef
internal::CommonDenseMatrixTraits
< ScalarImp >::derived_type derived_type
Public Member Functions
CommonDenseMatrix (const size_t rr=0, const size_t cc=0, const ScalarType value=ScalarType(0))
CommonDenseMatrix (const size_t rr, const size_t cc, const SparsityPatternDefault &)
This constructors ignores the given pattern and initializes the matrix with 0.
CommonDenseMatrix (const ThisType &other)
CommonDenseMatrix (const BackendType &other, const bool prune=false, const typename Common::FloatCmp::DefaultEpsilon< ScalarType >::Type eps=Common::FloatCmp::DefaultEpsilon< ScalarType >::value())
template<class T >
CommonDenseMatrix (const DenseMatrix< T > &other)
CommonDenseMatrix (BackendType *backend_ptr)
CommonDenseMatrix (std::shared_ptr< BackendType > backend_ptr)
ThisType & operator= (const ThisType &other)
ThisType & operator= (const BackendType &other)
Required by the ProvidesBackend interface.
BackendType & backend ()
const BackendType & backend () const
Required by ContainerInterface.
ThisType copy () const
void scal (const ScalarType &alpha)
void axpy (const ScalarType &alpha, const ThisType &xx)
bool has_equal_shape (const ThisType &other) const
Required by MatrixInterface.
size_t rows () const
size_t cols () const
void mv (const VectorInterface< internal::CommonDenseVectorTraits< ScalarType >, ScalarType > &xx, VectorInterface< internal::CommonDenseVectorTraits< ScalarType >, ScalarType > &yy) const
void mv (const CommonDenseVector< ScalarType > &xx, CommonDenseVector< ScalarType > &yy) const
void add_to_entry (const size_t ii, const size_t jj, const ScalarType &value)
void set_entry (const size_t ii, const size_t jj, const ScalarType &value)
ScalarType get_entry (const size_t ii, const size_t jj) const
void clear_row (const size_t ii)
void clear_col (const size_t jj)
void unit_row (const size_t ii)
void unit_col (const size_t jj)
bool valid () const
Have to be implemented by a derived class in addition to the ones required by ContainerInterface!
void mv (const XX &xx, YY &yy) const
void add_to_entry (const size_t ii, const size_t jj, const ScalarType &value)
void set_entry (const size_t ii, const size_t jj, const ScalarType &value)
Provided by the interface for convenience.
Note
Those marked with vitual should be overriden by any devired class that can do better.
XX::derived_type operator* (const VectorInterface< XX, ScalarType > &xx) const
virtual RealType sup_norm () const
virtual size_t non_zeros () const
Returns the number of entries in the sparsity pattern of the matrix.
virtual SparsityPatternDefault pattern (const bool prune=false, const typename Common::FloatCmp::DefaultEpsilon< ScalarType >::Type eps=Common::FloatCmp::DefaultEpsilon< ScalarType >::value()) const
Computes the sparsity pattern of the matrix.
virtual derived_type pruned (const typename Common::FloatCmp::DefaultEpsilon< ScalarType >::Type eps=Common::FloatCmp::DefaultEpsilon< ScalarType >::value()) const
Returns a pruned variant of this matrix.
Have to be implemented by a derived class!
void scal (const ScalarType &alpha)
BLAS SCAL operation (in-place sclar multiplication).
void axpy (const ScalarType &alpha, const derived_type &xx)
BLAS AXPY operation.
bool has_equal_shape (const derived_type &other) const
Test for equal sizes.
Static Public Attributes
static const constexpr Backends vector_type
static const constexpr Backends backend_type
Protected Member Functions
void ensure_uniqueness ()
Are provided by the interface for convenience!
Note
Those marked as virtual may be implemented more efficiently in a derived class!
virtual derived_type & operator*= (const ScalarType &alpha)
static std::string type_this ()
Detailed Description
template<class ScalarImp>
class Dune::XT::LA::CommonDenseMatrix< ScalarImp >
A dense matrix implementation of MatrixInterface using the Dune::DynamicMatrix.
Member Typedef Documentation
template<class ScalarImp > typedef Traits::BackendType Dune::XT::LA::CommonDenseMatrix< ScalarImp >::BackendType
typedef internal::CommonDenseMatrixTraits< ScalarImp > ::derived_type Dune::XT::LA::MatrixInterface< internal::CommonDenseMatrixTraits< ScalarImp > , ScalarImp >::derived_type inherited
template<class ScalarImp > typedef Traits::RealType Dune::XT::LA::CommonDenseMatrix< ScalarImp >::RealType
template<class ScalarImp > typedef Traits::ScalarType Dune::XT::LA::CommonDenseMatrix< ScalarImp >::ScalarType
template<class ScalarImp > typedef internal::CommonDenseMatrixTraits<ScalarImp> Dune::XT::LA::CommonDenseMatrix< ScalarImp >::Traits
Constructor & Destructor Documentation
template<class ScalarImp > Dune::XT::LA::CommonDenseMatrix< ScalarImp >::CommonDenseMatrix (const size_t rr = 0, const size_t cc = 0, const ScalarType value = ScalarType(0)) inline explicit
template<class ScalarImp > Dune::XT::LA::CommonDenseMatrix< ScalarImp >::CommonDenseMatrix (const size_t rr, const size_t cc, const SparsityPatternDefault &) inline
This constructors ignores the given pattern and initializes the matrix with 0.
template<class ScalarImp > Dune::XT::LA::CommonDenseMatrix< ScalarImp >::CommonDenseMatrix (const ThisType & other) inline
template<class ScalarImp > Dune::XT::LA::CommonDenseMatrix< ScalarImp >::CommonDenseMatrix (const BackendType & other, const bool prune = false, const typename Common::FloatCmp::DefaultEpsilon< ScalarType >::Type eps = Common::FloatCmp::DefaultEpsilon<ScalarType>::value()) inline explicit
Note
If prune == true, this implementation is not optimal!
References Dune::XT::LA::MatrixInterface< Traits, ScalarImp >::pruned().
template<class ScalarImp > template<class T > Dune::XT::LA::CommonDenseMatrix< ScalarImp >::CommonDenseMatrix (const DenseMatrix< T > & other) inline
References Dune::XT::LA::CommonDenseVector< ScalarImp >::set_entry().
template<class ScalarImp > Dune::XT::LA::CommonDenseMatrix< ScalarImp >::CommonDenseMatrix (BackendType * backend_ptr) inline explicit
Note
Takes ownership of backend_ptr in the sense that you must not delete it afterwards!
template<class ScalarImp > Dune::XT::LA::CommonDenseMatrix< ScalarImp >::CommonDenseMatrix (std::shared_ptr< BackendType > backend_ptr) inline explicit
Member Function Documentation
void Dune::XT::LA::MatrixInterface< internal::CommonDenseMatrixTraits< ScalarImp > , ScalarImp >::add_to_entry (const size_t ii, const size_t jj, const ScalarType & value) inline inherited
References Dune::XT::LA::MatrixInterface< Traits, ScalarImp >::add_to_entry().
template<class ScalarImp > void Dune::XT::LA::CommonDenseMatrix< ScalarImp >::add_to_entry (const size_t ii, const size_t jj, const ScalarType & value) inline
References Dune::XT::LA::CommonDenseVector< ScalarImp >::backend().
void Dune::XT::LA::ContainerInterface< internal::CommonDenseMatrixTraits< ScalarImp > , ScalarImp >::axpy (const ScalarType & alpha, const derived_type & xx) inline inherited
BLAS AXPY operation.
Parameters
alpha The scalar coefficient with which each element of the container is multiplied
xx Container that is to be elementwise added.
template<class ScalarImp > void Dune::XT::LA::CommonDenseMatrix< ScalarImp >::axpy (const ScalarType & alpha, const ThisType & xx) inline
References Dune::XT::LA::CommonDenseVector< ScalarImp >::backend(), Dune::XT::LA::CommonDenseMatrix< ScalarImp >::backend(), Dune::XT::LA::CommonDenseMatrix< ScalarImp >::cols(), Dune::XT::LA::CommonDenseVector< ScalarImp >::has_equal_shape(), and Dune::XT::LA::CommonDenseMatrix< ScalarImp >::rows().
template<class ScalarImp > BackendType& Dune::XT::LA::CommonDenseMatrix< ScalarImp >::backend () inline
References Dune::XT::LA::CommonDenseVector< ScalarImp >::ensure_uniqueness().
Referenced by Dune::XT::LA::CommonDenseMatrix< ScalarImp >::axpy().
template<class ScalarImp > const BackendType& Dune::XT::LA::CommonDenseMatrix< ScalarImp >::backend () const inline
template<class ScalarImp > void Dune::XT::LA::CommonDenseMatrix< ScalarImp >::clear_col (const size_t jj) inline
References Dune::XT::LA::CommonDenseVector< ScalarImp >::backend().
template<class ScalarImp > void Dune::XT::LA::CommonDenseMatrix< ScalarImp >::clear_row (const size_t ii) inline
References Dune::XT::LA::CommonDenseVector< ScalarImp >::backend().
template<class ScalarImp > size_t Dune::XT::LA::CommonDenseMatrix< ScalarImp >::cols () const inline
References Dune::XT::LA::CommonDenseVector< ScalarImp >::backend().
Referenced by Dune::XT::LA::CommonDenseMatrix< ScalarImp >::axpy(), and Dune::XT::LA::CommonDenseMatrix< ScalarImp >::has_equal_shape().
template<class ScalarImp > ThisType Dune::XT::LA::CommonDenseMatrix< ScalarImp >::copy () const inline
template<class ScalarImp > void Dune::XT::LA::CommonDenseMatrix< ScalarImp >::ensure_uniqueness () inline protected
See Also
ContainerInterface
template<class ScalarImp > ScalarType Dune::XT::LA::CommonDenseMatrix< ScalarImp >::get_entry (const size_t ii, const size_t jj) const inline
References Dune::XT::LA::CommonDenseVector< ScalarImp >::backend().
bool Dune::XT::LA::ContainerInterface< internal::CommonDenseMatrixTraits< ScalarImp > , ScalarImp >::has_equal_shape (const derived_type & other) const inline inherited
Test for equal sizes.
Parameters
other Container the sizes of which this is to be compared to.
template<class ScalarImp > bool Dune::XT::LA::CommonDenseMatrix< ScalarImp >::has_equal_shape (const ThisType & other) const inline
References Dune::XT::LA::CommonDenseMatrix< ScalarImp >::cols(), and Dune::XT::LA::CommonDenseMatrix< ScalarImp >::rows().
void Dune::XT::LA::MatrixInterface< internal::CommonDenseMatrixTraits< ScalarImp > , ScalarImp >::mv (const XX & xx, YY & yy) const inline inherited
References Dune::XT::LA::MatrixInterface< Traits, ScalarImp >::mv().
template<class ScalarImp > void Dune::XT::LA::CommonDenseMatrix< ScalarImp >::mv (const VectorInterface< internal::CommonDenseVectorTraits< ScalarType >, ScalarType > & xx, VectorInterface< internal::CommonDenseVectorTraits< ScalarType >, ScalarType > & yy) const inline
template<class ScalarImp > void Dune::XT::LA::CommonDenseMatrix< ScalarImp >::mv (const CommonDenseVector< ScalarType > & xx, CommonDenseVector< ScalarType > & yy) const inline
References Dune::XT::LA::CommonDenseVector< ScalarImp >::backend().
virtual size_t Dune::XT::LA::MatrixInterface< internal::CommonDenseMatrixTraits< ScalarImp > , ScalarImp >::non_zeros () const inline virtual inherited
Returns the number of entries in the sparsity pattern of the matrix.
This is mainly useful for sparse matrices and returns rows() times cols() for dense matrices.
Note
Some implementations do not report the correct number here, so use and interpret only if you know what you are doing!
References Dune::XT::LA::MatrixInterface< Traits, ScalarImp >::cols(), and Dune::XT::LA::MatrixInterface< Traits, ScalarImp >::rows().
XX::derived_type Dune::XT::LA::MatrixInterface< internal::CommonDenseMatrixTraits< ScalarImp > , ScalarImp >::operator* (const VectorInterface< XX, ScalarType > & xx) const inline inherited
References Dune::XT::LA::MatrixInterface< Traits, ScalarImp >::mv(), and Dune::XT::LA::MatrixInterface< Traits, ScalarImp >::rows().
virtual derived_type& Dune::XT::LA::ContainerInterface< internal::CommonDenseMatrixTraits< ScalarImp > , ScalarImp >::operator*= (const ScalarType & alpha) inline virtual inherited
template<class ScalarImp > ThisType& Dune::XT::LA::CommonDenseMatrix< ScalarImp >::operator= (const ThisType & other) inline
template<class ScalarImp > ThisType& Dune::XT::LA::CommonDenseMatrix< ScalarImp >::operator= (const BackendType & other) inline
Note
Does a deep copy.
virtual SparsityPatternDefault Dune::XT::LA::MatrixInterface< internal::CommonDenseMatrixTraits< ScalarImp > , ScalarImp >::pattern (const bool prune = false, const typename Common::FloatCmp::DefaultEpsilon< ScalarType >::Type eps = Common::FloatCmp::DefaultEpsilon<ScalarType>::value()) const inline virtual inherited
Computes the sparsity pattern of the matrix.
This is mainly useful for sparse matrices and returns a full pattern for dense matrices
Parameters
prune If true, treats all entries smaller than eps as zero and does not include these indices in the returned pattern
References Dune::XT::LA::MatrixInterface< Traits, ScalarImp >::cols(), Dune::XT::LA::MatrixInterface< Traits, ScalarImp >::get_entry(), Dune::XT::LA::SparsityPatternDefault::insert(), Dune::XT::LA::MatrixInterface< Traits, ScalarImp >::rows(), and Dune::XT::LA::SparsityPatternDefault::sort().
virtual derived_type Dune::XT::LA::MatrixInterface< internal::CommonDenseMatrixTraits< ScalarImp > , ScalarImp >::pruned (const typename Common::FloatCmp::DefaultEpsilon< ScalarType >::Type eps = Common::FloatCmp::DefaultEpsilon<ScalarType>::value()) const inline virtual inherited
Returns a pruned variant of this matrix.
This is mainly useful for sparse matrices and returns a matrix that should be very close to this matrix, except for very small values, which are set to zero and the entries of which are removed from the sparsity pattern.
See Also
pattern
Parameters
eps Is forwarded to pattern(true, eps)
References Dune::XT::LA::MatrixInterface< Traits, ScalarImp >::cols(), Dune::XT::LA::MatrixInterface< Traits, ScalarImp >::get_entry(), Dune::XT::LA::MatrixInterface< Traits, ScalarImp >::pattern(), Dune::XT::LA::MatrixInterface< Traits, ScalarImp >::rows(), and Dune::XT::LA::CommonDenseMatrix< ScalarImp >::set_entry().
template<class ScalarImp > size_t Dune::XT::LA::CommonDenseMatrix< ScalarImp >::rows () const inline
References Dune::XT::LA::CommonDenseVector< ScalarImp >::backend().
Referenced by Dune::XT::LA::CommonDenseMatrix< ScalarImp >::axpy(), and Dune::XT::LA::CommonDenseMatrix< ScalarImp >::has_equal_shape().
void Dune::XT::LA::ContainerInterface< internal::CommonDenseMatrixTraits< ScalarImp > , ScalarImp >::scal (const ScalarType & alpha) inline inherited
BLAS SCAL operation (in-place sclar multiplication).
Parameters
alpha The scalar coefficient with which each element of the container is multiplied.
template<class ScalarImp > void Dune::XT::LA::CommonDenseMatrix< ScalarImp >::scal (const ScalarType & alpha) inline
References Dune::XT::LA::CommonDenseVector< ScalarImp >::backend().
void Dune::XT::LA::MatrixInterface< internal::CommonDenseMatrixTraits< ScalarImp > , ScalarImp >::set_entry (const size_t ii, const size_t jj, const ScalarType & value) inline inherited
References Dune::XT::LA::MatrixInterface< Traits, ScalarImp >::set_entry().
template<class ScalarImp > void Dune::XT::LA::CommonDenseMatrix< ScalarImp >::set_entry (const size_t ii, const size_t jj, const ScalarType & value) inline
References Dune::XT::LA::CommonDenseVector< ScalarImp >::backend().
Referenced by Dune::XT::LA::MatrixInterface< internal::CommonDenseMatrixTraits< ScalarImp >, ScalarImp >::pruned().
virtual RealType Dune::XT::LA::MatrixInterface< internal::CommonDenseMatrixTraits< ScalarImp > , ScalarImp >::sup_norm () const inline virtual inherited
References Dune::XT::LA::MatrixInterface< Traits, ScalarImp >::cols(), Dune::XT::LA::MatrixInterface< Traits, ScalarImp >::get_entry(), and Dune::XT::LA::MatrixInterface< Traits, ScalarImp >::rows().
static std::string Dune::XT::LA::ContainerInterface< internal::CommonDenseMatrixTraits< ScalarImp > , ScalarImp >::type_this () inline static inherited
template<class ScalarImp > void Dune::XT::LA::CommonDenseMatrix< ScalarImp >::unit_col (const size_t jj) inline
References Dune::XT::LA::CommonDenseVector< ScalarImp >::backend().
template<class ScalarImp > void Dune::XT::LA::CommonDenseMatrix< ScalarImp >::unit_row (const size_t ii) inline
References Dune::XT::LA::CommonDenseVector< ScalarImp >::backend().
template<class ScalarImp > bool Dune::XT::LA::CommonDenseMatrix< ScalarImp >::valid () const inline
References Dune::XT::LA::CommonDenseVector< ScalarImp >::backend().
Member Data Documentation
const constexpr Backends Dune::XT::LA::ProvidesBackend< internal::CommonDenseMatrixTraits< ScalarImp > >::backend_type static inherited
const constexpr Backends Dune::XT::LA::MatrixInterface< internal::CommonDenseMatrixTraits< ScalarImp > , ScalarImp >::vector_type static inherited
The documentation for this class was generated from the following file:
container/common.hh