Dune::XT::Functions::ESV2007::Testcase1Force< EntityImp, DomainFieldImp, 2, RangeFieldImp, 1, 1 > Class Template Reference
Dune::XT::Functions::ESV2007::Testcase1Force< EntityImp, DomainFieldImp, 2, RangeFieldImp, 1, 1 > Class Template Reference abstract
#include <dune/xt/functions/ESV2007.hh>
Public Types
typedef BaseType::DomainType DomainType
typedef BaseType::RangeType RangeType
typedef BaseType::JacobianRangeType JacobianRangeType
typedef BaseType::LocalfunctionType LocalfunctionType
typedef EntityImp EntityType
typedef DomainFieldImp DomainFieldType
typedef RangeFieldImp RangeFieldType
typedef
Functions::DifferenceFunction
< ThisType, ThisType > DifferenceType
typedef Functions::SumFunction
< ThisType, ThisType > SumType
typedef
Functions::DivergenceFunction
< ThisType > DivergenceType
Public Member Functions
Testcase1Force (const size_t ord=default_config().template get< size_t >("integration_order"), const std::string nm=static_id())
Testcase1Force (const ThisType &)=default
ThisType & operator= (const ThisType &)=delete
virtual std::string type () const overridefinal
virtual std::string name () const overridefinal
virtual size_t order () const overridefinal
virtual void evaluate (const DomainType &xx, RangeType &ret) const overridefinal
"0.5 * pi * pi * cos(0.5 * pi * x[0]) * cos(0.5 * pi * x[1])"
virtual void jacobian (const DomainType &xx, JacobianRangeType &ret) const overridefinal
["-0.25 * pi * pi * pi * sin(0.5 * pi * x[0]) * cos(0.5 * pi * x[1])" "-0.25 * pi * pi * pi * cos(0.5 * pi * x[0]) * sin(0.5 * pi * x[1])"]
virtual void evaluate (const DomainType &xx, RangeType &ret) const =0
virtual RangeType evaluate (const DomainType &xx) const
virtual void jacobian (const DomainType &, JacobianRangeType &) const
virtual JacobianRangeType jacobian (const DomainType &xx) const
virtual std::unique_ptr
< LocalfunctionType > local_function (const EntityImp &entity) const overridefinal
Transfer< OtherEntityImp >::Type transfer () const
DifferenceType operator- (const ThisType &other) const
SumType operator+ (const ThisType &other) const
std::enable_if
< is_localizable_function
< OtherType >::value,
Functions::ProductFunction
< ThisType, OtherType >
>::type operator* (const OtherType &other) const
DivergenceType divergence () const
void visualize (const GridViewType &grid_view, const std::string path, const bool subsampling=true, const VTK::OutputType vtk_output_type=VTK::appendedraw) const
virtual void report (std::ostream &out, const std::string prefix="") const
Static Public Member Functions
static std::string static_id ()
static Common::Configuration default_config (const std::string sub_name="")
static std::unique_ptr< ThisType > create (const Common::Configuration config=default_config(), const std::string sub_name=static_id())
Static Public Attributes
static const bool available = true
static const size_t dimDomain
static const size_t dimRange
static const size_t dimRangeCols
Member Typedef Documentation
typedef Functions::DifferenceFunction<ThisType, ThisType> Dune::XT::Functions::LocalizableFunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::DifferenceType inherited
typedef Functions::DivergenceFunction<ThisType> Dune::XT::Functions::LocalizableFunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::DivergenceType inherited
typedef DomainFieldImp Dune::XT::Functions::LocalizableFunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::DomainFieldType inherited
template<class EntityImp , class DomainFieldImp , class RangeFieldImp > typedef BaseType::DomainType Dune::XT::Functions::GlobalFunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::DomainType
typedef EntityImp Dune::XT::Functions::LocalizableFunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::EntityType inherited
template<class EntityImp , class DomainFieldImp , class RangeFieldImp > typedef BaseType::JacobianRangeType Dune::XT::Functions::GlobalFunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::JacobianRangeType
typedef BaseType::LocalfunctionType Dune::XT::Functions::GlobalFunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, 1 >::LocalfunctionType inherited
typedef RangeFieldImp Dune::XT::Functions::LocalizableFunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::RangeFieldType inherited
template<class EntityImp , class DomainFieldImp , class RangeFieldImp > typedef BaseType::RangeType Dune::XT::Functions::GlobalFunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::RangeType
typedef Functions::SumFunction<ThisType, ThisType> Dune::XT::Functions::LocalizableFunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::SumType inherited
Constructor & Destructor Documentation
template<class EntityImp , class DomainFieldImp , class RangeFieldImp > Dune::XT::Functions::ESV2007::Testcase1Force< EntityImp, DomainFieldImp, 2, RangeFieldImp, 1, 1 >::Testcase1Force (const size_t ord = default_config().template get<size_t>("integration_order"), const std::string nm = static_id()) inline
template<class EntityImp , class DomainFieldImp , class RangeFieldImp > Dune::XT::Functions::ESV2007::Testcase1Force< EntityImp, DomainFieldImp, 2, RangeFieldImp, 1, 1 >::Testcase1Force (const ThisType &) default
Member Function Documentation
template<class EntityImp , class DomainFieldImp , class RangeFieldImp > static std::unique_ptr<ThisType> Dune::XT::Functions::ESV2007::Testcase1Force< EntityImp, DomainFieldImp, 2, RangeFieldImp, 1, 1 >::create (const Common::Configuration config = default_config(), const std::string sub_name = static_id()) inline static
template<class EntityImp , class DomainFieldImp , class RangeFieldImp > static Common::Configuration Dune::XT::Functions::ESV2007::Testcase1Force< EntityImp, DomainFieldImp, 2, RangeFieldImp, 1, 1 >::default_config (const std::string sub_name = "") inline static
References Dune::XT::Functions::LocalizableFunctionInterface< E, D, d, R, r, rC >::static_id().
DivergenceType Dune::XT::Functions::LocalizableFunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::divergence () const inline inherited
template<class EntityImp , class DomainFieldImp , class RangeFieldImp > virtual void Dune::XT::Functions::ESV2007::Testcase1Force< EntityImp, DomainFieldImp, 2, RangeFieldImp, 1, 1 >::evaluate (const DomainType & xx, RangeType & ret) const inline final override virtual
"0.5 * pi * pi * cos(0.5 * pi * x[0]) * cos(0.5 * pi * x[1])"
References cos().
virtual void Dune::XT::Functions::GlobalFunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, 1 >::evaluate (const DomainType & xx, RangeType & ret) const pure virtual inherited
virtual RangeType Dune::XT::Functions::GlobalFunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, 1 >::evaluate (const DomainType & xx) const inline virtual inherited
template<class EntityImp , class DomainFieldImp , class RangeFieldImp > virtual void Dune::XT::Functions::ESV2007::Testcase1Force< EntityImp, DomainFieldImp, 2, RangeFieldImp, 1, 1 >::jacobian (const DomainType & xx, JacobianRangeType & ret) const inline final override virtual
["-0.25 * pi * pi * pi * sin(0.5 * pi * x[0]) * cos(0.5 * pi * x[1])" "-0.25 * pi * pi * pi * cos(0.5 * pi * x[0]) * sin(0.5 * pi * x[1])"]
References cos(), and sin().
virtual void Dune::XT::Functions::GlobalFunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, 1 >::jacobian (const DomainType & , JacobianRangeType &) const inline virtual inherited
virtual JacobianRangeType Dune::XT::Functions::GlobalFunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, 1 >::jacobian (const DomainType & xx) const inline virtual inherited
virtual std::unique_ptr<LocalfunctionType> Dune::XT::Functions::GlobalFunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, 1 >::local_function (const EntityImp & entity) const inline final override virtual inherited
Implements Dune::XT::Functions::LocalizableFunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, 1 >.
template<class EntityImp , class DomainFieldImp , class RangeFieldImp > virtual std::string Dune::XT::Functions::ESV2007::Testcase1Force< EntityImp, DomainFieldImp, 2, RangeFieldImp, 1, 1 >::name () const inline final override virtual
Reimplemented from Dune::XT::Functions::GlobalFunctionInterface< EntityImp, DomainFieldImp, 2, RangeFieldImp, 1 >.
std::enable_if<is_localizable_function<OtherType>::value, Functions::ProductFunction<ThisType, OtherType> >::type Dune::XT::Functions::LocalizableFunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::operator* (const OtherType & other) const inline inherited
SumType Dune::XT::Functions::LocalizableFunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::operator+ (const ThisType & other) const inline inherited
DifferenceType Dune::XT::Functions::LocalizableFunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::operator- (const ThisType & other) const inline inherited
template<class EntityImp , class DomainFieldImp , class RangeFieldImp > ThisType& Dune::XT::Functions::ESV2007::Testcase1Force< EntityImp, DomainFieldImp, 2, RangeFieldImp, 1, 1 >::operator= (const ThisType &) delete
template<class EntityImp , class DomainFieldImp , class RangeFieldImp > virtual size_t Dune::XT::Functions::ESV2007::Testcase1Force< EntityImp, DomainFieldImp, 2, RangeFieldImp, 1, 1 >::order () const inline final override virtual
Implements Dune::XT::Functions::GlobalFunctionInterface< EntityImp, DomainFieldImp, 2, RangeFieldImp, 1 >.
virtual void Dune::XT::Functions::LocalizableFunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::report (std::ostream & out, const std::string prefix = "") const inline virtual inherited
template<class EntityImp , class DomainFieldImp , class RangeFieldImp > static std::string Dune::XT::Functions::ESV2007::Testcase1Force< EntityImp, DomainFieldImp, 2, RangeFieldImp, 1, 1 >::static_id () inline static
Transfer<OtherEntityImp>::Type Dune::XT::Functions::GlobalFunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, 1 >::transfer () const inline inherited
template<class EntityImp , class DomainFieldImp , class RangeFieldImp > virtual std::string Dune::XT::Functions::ESV2007::Testcase1Force< EntityImp, DomainFieldImp, 2, RangeFieldImp, 1, 1 >::type () const inline final override virtual
Reimplemented from Dune::XT::Functions::GlobalFunctionInterface< EntityImp, DomainFieldImp, 2, RangeFieldImp, 1 >.
void Dune::XT::Functions::LocalizableFunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::visualize (const GridViewType & grid_view, const std::string path, const bool subsampling = true, const VTK::OutputType vtk_output_type = VTK::appendedraw) const inline inherited
Note
We use the SubsamplingVTKWriter (which is better for higher orders) by default. This means that the grid you see in the visualization is a refinement of the actual grid!
Member Data Documentation
template<class EntityImp , class DomainFieldImp , class RangeFieldImp > const bool Dune::XT::Functions::ESV2007::Testcase1Force< EntityImp, DomainFieldImp, 2, RangeFieldImp, 1, 1 >::available = true static
const size_t Dune::XT::Functions::LocalizableFunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::dimDomain static inherited
const size_t Dune::XT::Functions::LocalizableFunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::dimRange static inherited
const size_t Dune::XT::Functions::LocalizableFunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::dimRangeCols static inherited
The documentation for this class was generated from the following file:
ESV2007.hh