Dune::XT::Functions::ESV2007::CutoffFunction< DiffusionFactorType, DiffusionTensorType > Class Template Reference
Dune::XT::Functions::ESV2007::CutoffFunction< DiffusionFactorType, DiffusionTensorType > Class Template Reference abstract
#include <dune/xt/functions/ESV2007.hh>
Public Types
typedef BaseType::EntityType EntityType
typedef BaseType::LocalfunctionType LocalfunctionType
typedef BaseType::DomainFieldType DomainFieldType
typedef BaseType::DomainType DomainType
typedef BaseType::RangeFieldType RangeFieldType
typedef BaseType::RangeType RangeType
typedef
LocalfunctionType::JacobianRangeType JacobianRangeType
typedef
Functions::DifferenceFunction
< ThisType, ThisType > DifferenceType
typedef Functions::SumFunction
< ThisType, ThisType > SumType
typedef
Functions::DivergenceFunction
< ThisType > DivergenceType
Public Member Functions
CutoffFunction (const DiffusionFactorType &diffusion_factor, const DiffusionTensorType &diffusion_tensor, const RangeFieldType poincare_constant=1.0/(M_PIl *M_PIl), const std::string nm=static_id())
CutoffFunction (const ThisType &other)=default
ThisType & operator= (const ThisType &other)=delete
virtual std::string name () const overridefinal
virtual std::unique_ptr
< LocalfunctionType > local_function (const EntityType &entity) const overridefinal
virtual std::unique_ptr
< LocalfunctionType > local_function (const EntityType &) const =0
virtual std::string type () const
DifferenceType operator- (const ThisType &other) const
SumType operator+ (const ThisType &other) const
std::enable_if
< is_localizable_function
< OtherType >::value,
Functions::ProductFunction
< ThisType, OtherType >
>::type operator* (const OtherType &other) const
DivergenceType divergence () const
void visualize (const GridViewType &grid_view, const std::string path, const bool subsampling=true, const VTK::OutputType vtk_output_type=VTK::appendedraw) const
virtual void report (std::ostream &out, const std::string prefix="") const
Static Public Member Functions
static std::string static_id ()
Static Public Attributes
static const size_t dimDomain = BaseType::dimDomain
static const size_t dimRange = BaseType::dimRange
static const size_t dimRangeCols = BaseType::dimRangeCols
static const bool available
Member Typedef Documentation
typedef Functions::DifferenceFunction<ThisType, ThisType> Dune::XT::Functions::LocalizableFunctionInterface< DiffusionFactorType::EntityType , DiffusionFactorType::DomainFieldType , domainDim, DiffusionFactorType::RangeFieldType , rangeDim, rangeDimCols >::DifferenceType inherited
typedef Functions::DivergenceFunction<ThisType> Dune::XT::Functions::LocalizableFunctionInterface< DiffusionFactorType::EntityType , DiffusionFactorType::DomainFieldType , domainDim, DiffusionFactorType::RangeFieldType , rangeDim, rangeDimCols >::DivergenceType inherited
template<class DiffusionFactorType , class DiffusionTensorType = void> typedef BaseType::DomainFieldType Dune::XT::Functions::ESV2007::CutoffFunction< DiffusionFactorType, DiffusionTensorType >::DomainFieldType
template<class DiffusionFactorType , class DiffusionTensorType = void> typedef BaseType::DomainType Dune::XT::Functions::ESV2007::CutoffFunction< DiffusionFactorType, DiffusionTensorType >::DomainType
template<class DiffusionFactorType , class DiffusionTensorType = void> typedef BaseType::EntityType Dune::XT::Functions::ESV2007::CutoffFunction< DiffusionFactorType, DiffusionTensorType >::EntityType
typedef LocalfunctionType::JacobianRangeType Dune::XT::Functions::LocalizableFunctionInterface< DiffusionFactorType::EntityType , DiffusionFactorType::DomainFieldType , domainDim, DiffusionFactorType::RangeFieldType , rangeDim, rangeDimCols >::JacobianRangeType inherited
template<class DiffusionFactorType , class DiffusionTensorType = void> typedef BaseType::LocalfunctionType Dune::XT::Functions::ESV2007::CutoffFunction< DiffusionFactorType, DiffusionTensorType >::LocalfunctionType
template<class DiffusionFactorType , class DiffusionTensorType = void> typedef BaseType::RangeFieldType Dune::XT::Functions::ESV2007::CutoffFunction< DiffusionFactorType, DiffusionTensorType >::RangeFieldType
template<class DiffusionFactorType , class DiffusionTensorType = void> typedef BaseType::RangeType Dune::XT::Functions::ESV2007::CutoffFunction< DiffusionFactorType, DiffusionTensorType >::RangeType
typedef Functions::SumFunction<ThisType, ThisType> Dune::XT::Functions::LocalizableFunctionInterface< DiffusionFactorType::EntityType , DiffusionFactorType::DomainFieldType , domainDim, DiffusionFactorType::RangeFieldType , rangeDim, rangeDimCols >::SumType inherited
Constructor & Destructor Documentation
template<class DiffusionFactorType , class DiffusionTensorType = void> Dune::XT::Functions::ESV2007::CutoffFunction< DiffusionFactorType, DiffusionTensorType >::CutoffFunction (const DiffusionFactorType & diffusion_factor, const DiffusionTensorType & diffusion_tensor, const RangeFieldType poincare_constant = 1.0 / (M_PIl * M_PIl), const std::string nm = static_id()) inline
template<class DiffusionFactorType , class DiffusionTensorType = void> Dune::XT::Functions::ESV2007::CutoffFunction< DiffusionFactorType, DiffusionTensorType >::CutoffFunction (const ThisType & other) default
Member Function Documentation
DivergenceType Dune::XT::Functions::LocalizableFunctionInterface< DiffusionFactorType::EntityType , DiffusionFactorType::DomainFieldType , domainDim, DiffusionFactorType::RangeFieldType , rangeDim, rangeDimCols >::divergence () const inline inherited
virtual std::unique_ptr<LocalfunctionType> Dune::XT::Functions::LocalizableFunctionInterface< DiffusionFactorType::EntityType , DiffusionFactorType::DomainFieldType , domainDim, DiffusionFactorType::RangeFieldType , rangeDim, rangeDimCols >::local_function (const EntityType &) const pure virtual inherited
template<class DiffusionFactorType , class DiffusionTensorType = void> virtual std::unique_ptr<LocalfunctionType> Dune::XT::Functions::ESV2007::CutoffFunction< DiffusionFactorType, DiffusionTensorType >::local_function (const EntityType & entity) const inline final override virtual
template<class DiffusionFactorType , class DiffusionTensorType = void> virtual std::string Dune::XT::Functions::ESV2007::CutoffFunction< DiffusionFactorType, DiffusionTensorType >::name () const inline final override virtual
Reimplemented from Dune::XT::Functions::LocalizableFunctionInterface< DiffusionFactorType::EntityType, DiffusionFactorType::DomainFieldType, DiffusionFactorType::dimDomain, DiffusionFactorType::RangeFieldType, 1, 1 >.
std::enable_if<is_localizable_function<OtherType>::value, Functions::ProductFunction<ThisType, OtherType> >::type Dune::XT::Functions::LocalizableFunctionInterface< DiffusionFactorType::EntityType , DiffusionFactorType::DomainFieldType , domainDim, DiffusionFactorType::RangeFieldType , rangeDim, rangeDimCols >::operator* (const OtherType & other) const inline inherited
SumType Dune::XT::Functions::LocalizableFunctionInterface< DiffusionFactorType::EntityType , DiffusionFactorType::DomainFieldType , domainDim, DiffusionFactorType::RangeFieldType , rangeDim, rangeDimCols >::operator+ (const ThisType & other) const inline inherited
DifferenceType Dune::XT::Functions::LocalizableFunctionInterface< DiffusionFactorType::EntityType , DiffusionFactorType::DomainFieldType , domainDim, DiffusionFactorType::RangeFieldType , rangeDim, rangeDimCols >::operator- (const ThisType & other) const inline inherited
template<class DiffusionFactorType , class DiffusionTensorType = void> ThisType& Dune::XT::Functions::ESV2007::CutoffFunction< DiffusionFactorType, DiffusionTensorType >::operator= (const ThisType & other) delete
virtual void Dune::XT::Functions::LocalizableFunctionInterface< DiffusionFactorType::EntityType , DiffusionFactorType::DomainFieldType , domainDim, DiffusionFactorType::RangeFieldType , rangeDim, rangeDimCols >::report (std::ostream & out, const std::string prefix = "") const inline virtual inherited
References Dune::XT::Functions::LocalizableFunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::name(), and Dune::XT::Functions::LocalizableFunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::type().
template<class DiffusionFactorType , class DiffusionTensorType = void> static std::string Dune::XT::Functions::ESV2007::CutoffFunction< DiffusionFactorType, DiffusionTensorType >::static_id () inline static
References Dune::XT::Functions::LocalizableFunctionInterface< EntityImp, DomainFieldImp, domainDim, RangeFieldImp, rangeDim, rangeDimCols >::static_id().
virtual std::string Dune::XT::Functions::LocalizableFunctionInterface< DiffusionFactorType::EntityType , DiffusionFactorType::DomainFieldType , domainDim, DiffusionFactorType::RangeFieldType , rangeDim, rangeDimCols >::type () const inline virtual inherited
void Dune::XT::Functions::LocalizableFunctionInterface< DiffusionFactorType::EntityType , DiffusionFactorType::DomainFieldType , domainDim, DiffusionFactorType::RangeFieldType , rangeDim, rangeDimCols >::visualize (const GridViewType & grid_view, const std::string path, const bool subsampling = true, const VTK::OutputType vtk_output_type = VTK::appendedraw) const inline inherited
Note
We use the SubsamplingVTKWriter (which is better for higher orders) by default. This means that the grid you see in the visualization is a refinement of the actual grid!
Member Data Documentation
const bool Dune::XT::Functions::LocalizableFunctionInterface< DiffusionFactorType::EntityType , DiffusionFactorType::DomainFieldType , domainDim, DiffusionFactorType::RangeFieldType , rangeDim, rangeDimCols >::available static inherited
template<class DiffusionFactorType , class DiffusionTensorType = void> const size_t Dune::XT::Functions::ESV2007::CutoffFunction< DiffusionFactorType, DiffusionTensorType >::dimDomain = BaseType::dimDomain static
template<class DiffusionFactorType , class DiffusionTensorType = void> const size_t Dune::XT::Functions::ESV2007::CutoffFunction< DiffusionFactorType, DiffusionTensorType >::dimRange = BaseType::dimRange static
template<class DiffusionFactorType , class DiffusionTensorType = void> const size_t Dune::XT::Functions::ESV2007::CutoffFunction< DiffusionFactorType, DiffusionTensorType >::dimRangeCols = BaseType::dimRangeCols static
The documentation for this class was generated from the following file:
ESV2007.hh