Dune::XT::Functions::internal::CombinedLocalFunction< LeftType, RightType, type > Class Template Reference
Dune::XT::Functions::internal::CombinedLocalFunction< LeftType, RightType, type > Class Template Reference abstract
Generic combined local function.
#include <dune/xt/functions/combined.hh>
Public Types
typedef BaseType::EntityType EntityType
typedef BaseType::DomainType DomainType
typedef BaseType::RangeType RangeType
typedef BaseType::JacobianRangeType JacobianRangeType
typedef BaseType::DomainFieldType DomainFieldType
typedef SelectCombined
< LeftType, RightType, type >
::R RangeFieldType
Public Member Functions
CombinedLocalFunction (const LeftType &left, const RightType &right, const EntityType &ent)
virtual size_t order () const overridefinal
virtual void evaluate (const DomainType &xx, RangeType &ret) const overridefinal
virtual void jacobian (const DomainType &xx, JacobianRangeType &ret) const overridefinal
virtual void evaluate (const DomainType &, RangeType &) const =0
virtual void evaluate (const DomainType &xx, std::vector< RangeType > &ret) const overridefinal
RangeType evaluate (const DomainType &xx) const
void evaluate (const Dune::QuadratureRule< DomainFieldType, dimDomain > &quadrature, std::vector< RangeType > &ret)
evaluate at N quadrature points into vector of size >= N
virtual void jacobian (const DomainType &, JacobianRangeType &) const =0
virtual void jacobian (const DomainType &xx, std::vector< JacobianRangeType > &ret) const overridefinal
JacobianRangeType jacobian (const DomainType &xx) const
void jacobian (const Dune::QuadratureRule< DomainFieldType, dimDomain > &quadrature, std::vector< JacobianRangeType > &ret)
jacobian at N quadrature points into vector of size >= N
virtual size_t size () const overridefinal
virtual const EntityType & entity () const
Static Public Attributes
static const size_t dimDomain
static const size_t dimRange
static const size_t dimRangeCols
Protected Member Functions
bool is_a_valid_point (const DomainType &xx) const
Protected Attributes
const EntityType & entity_
Detailed Description
template<class LeftType, class RightType, Combination type>
class Dune::XT::Functions::internal::CombinedLocalFunction< LeftType, RightType, type >
Generic combined local function.
Note
Most likely you do not want to use this class directly, but Combined.
Member Typedef Documentation
typedef BaseType::DomainFieldType Dune::XT::Functions::LocalfunctionInterface< SelectCombined< LeftType, RightType, type >::E , SelectCombined< LeftType, RightType, type >::D , domainDim, SelectCombined< LeftType, RightType, type >::R , rangeDim, rangeDimCols >::DomainFieldType inherited
template<class LeftType , class RightType , Combination type> typedef BaseType::DomainType Dune::XT::Functions::internal::CombinedLocalFunction< LeftType, RightType, type >::DomainType
template<class LeftType , class RightType , Combination type> typedef BaseType::EntityType Dune::XT::Functions::internal::CombinedLocalFunction< LeftType, RightType, type >::EntityType
template<class LeftType , class RightType , Combination type> typedef BaseType::JacobianRangeType Dune::XT::Functions::internal::CombinedLocalFunction< LeftType, RightType, type >::JacobianRangeType
typedef SelectCombined< LeftType, RightType, type >::R Dune::XT::Functions::LocalfunctionSetInterface< SelectCombined< LeftType, RightType, type >::E , SelectCombined< LeftType, RightType, type >::D , domainDim, SelectCombined< LeftType, RightType, type >::R , rangeDim, rangeDimCols >::RangeFieldType inherited
template<class LeftType , class RightType , Combination type> typedef BaseType::RangeType Dune::XT::Functions::internal::CombinedLocalFunction< LeftType, RightType, type >::RangeType
Constructor & Destructor Documentation
template<class LeftType , class RightType , Combination type> Dune::XT::Functions::internal::CombinedLocalFunction< LeftType, RightType, type >::CombinedLocalFunction (const LeftType & left, const RightType & right, const EntityType & ent) inline
Member Function Documentation
virtual const EntityType& Dune::XT::Functions::LocalfunctionSetInterface< SelectCombined< LeftType, RightType, type >::E , SelectCombined< LeftType, RightType, type >::D , domainDim, SelectCombined< LeftType, RightType, type >::R , rangeDim, rangeDimCols >::entity () const inline virtual inherited
virtual void Dune::XT::Functions::LocalfunctionInterface< SelectCombined< LeftType, RightType, type >::E , SelectCombined< LeftType, RightType, type >::D , domainDim, SelectCombined< LeftType, RightType, type >::R , rangeDim, rangeDimCols >::evaluate (const DomainType & , RangeType &) const pure virtual inherited
virtual void Dune::XT::Functions::LocalfunctionInterface< SelectCombined< LeftType, RightType, type >::E , SelectCombined< LeftType, RightType, type >::D , domainDim, SelectCombined< LeftType, RightType, type >::R , rangeDim, rangeDimCols >::evaluate (const DomainType & xx, std::vector< RangeType > & ret) const inline final override virtual inherited
Implements Dune::XT::Functions::LocalfunctionSetInterface< SelectCombined< LeftType, RightType, type >::E, SelectCombined< LeftType, RightType, type >::D, domainDim, SelectCombined< LeftType, RightType, type >::R, rangeDim, rangeDimCols >.
RangeType Dune::XT::Functions::LocalfunctionInterface< SelectCombined< LeftType, RightType, type >::E , SelectCombined< LeftType, RightType, type >::D , domainDim, SelectCombined< LeftType, RightType, type >::R , rangeDim, rangeDimCols >::evaluate (const DomainType & xx) const inline inherited
template<class LeftType , class RightType , Combination type> virtual void Dune::XT::Functions::internal::CombinedLocalFunction< LeftType, RightType, type >::evaluate (const DomainType & xx, RangeType & ret) const inline final override virtual
References Dune::XT::Functions::internal::SelectCombined< LeftType, RightType, comb >::evaluate().
void Dune::XT::Functions::LocalfunctionInterface< SelectCombined< LeftType, RightType, type >::E , SelectCombined< LeftType, RightType, type >::D , domainDim, SelectCombined< LeftType, RightType, type >::R , rangeDim, rangeDimCols >::evaluate (const Dune::QuadratureRule< DomainFieldType, dimDomain > & quadrature, std::vector< RangeType > & ret) inline inherited
evaluate at N quadrature points into vector of size >= N
bool Dune::XT::Functions::LocalfunctionSetInterface< SelectCombined< LeftType, RightType, type >::E , SelectCombined< LeftType, RightType, type >::D , domainDim, SelectCombined< LeftType, RightType, type >::R , rangeDim, rangeDimCols >::is_a_valid_point (const DomainType & xx) const inline protected inherited
virtual void Dune::XT::Functions::LocalfunctionInterface< SelectCombined< LeftType, RightType, type >::E , SelectCombined< LeftType, RightType, type >::D , domainDim, SelectCombined< LeftType, RightType, type >::R , rangeDim, rangeDimCols >::jacobian (const DomainType & , JacobianRangeType &) const pure virtual inherited
virtual void Dune::XT::Functions::LocalfunctionInterface< SelectCombined< LeftType, RightType, type >::E , SelectCombined< LeftType, RightType, type >::D , domainDim, SelectCombined< LeftType, RightType, type >::R , rangeDim, rangeDimCols >::jacobian (const DomainType & xx, std::vector< JacobianRangeType > & ret) const inline final override virtual inherited
Implements Dune::XT::Functions::LocalfunctionSetInterface< SelectCombined< LeftType, RightType, type >::E, SelectCombined< LeftType, RightType, type >::D, domainDim, SelectCombined< LeftType, RightType, type >::R, rangeDim, rangeDimCols >.
JacobianRangeType Dune::XT::Functions::LocalfunctionInterface< SelectCombined< LeftType, RightType, type >::E , SelectCombined< LeftType, RightType, type >::D , domainDim, SelectCombined< LeftType, RightType, type >::R , rangeDim, rangeDimCols >::jacobian (const DomainType & xx) const inline inherited
template<class LeftType , class RightType , Combination type> virtual void Dune::XT::Functions::internal::CombinedLocalFunction< LeftType, RightType, type >::jacobian (const DomainType & xx, JacobianRangeType & ret) const inline final override virtual
References Dune::XT::Functions::internal::SelectCombined< LeftType, RightType, comb >::jacobian().
void Dune::XT::Functions::LocalfunctionInterface< SelectCombined< LeftType, RightType, type >::E , SelectCombined< LeftType, RightType, type >::D , domainDim, SelectCombined< LeftType, RightType, type >::R , rangeDim, rangeDimCols >::jacobian (const Dune::QuadratureRule< DomainFieldType, dimDomain > & quadrature, std::vector< JacobianRangeType > & ret) inline inherited
jacobian at N quadrature points into vector of size >= N
template<class LeftType , class RightType , Combination type> virtual size_t Dune::XT::Functions::internal::CombinedLocalFunction< LeftType, RightType, type >::order () const inline final override virtual
Implements Dune::XT::Functions::LocalfunctionSetInterface< SelectCombined< LeftType, RightType, type >::E, SelectCombined< LeftType, RightType, type >::D, domainDim, SelectCombined< LeftType, RightType, type >::R, rangeDim, rangeDimCols >.
References Dune::XT::Functions::internal::SelectCombined< LeftType, RightType, comb >::order().
virtual size_t Dune::XT::Functions::LocalfunctionInterface< SelectCombined< LeftType, RightType, type >::E , SelectCombined< LeftType, RightType, type >::D , domainDim, SelectCombined< LeftType, RightType, type >::R , rangeDim, rangeDimCols >::size () const inline final override virtual inherited
Implements Dune::XT::Functions::LocalfunctionSetInterface< SelectCombined< LeftType, RightType, type >::E, SelectCombined< LeftType, RightType, type >::D, domainDim, SelectCombined< LeftType, RightType, type >::R, rangeDim, rangeDimCols >.
Member Data Documentation
const size_t Dune::XT::Functions::LocalfunctionInterface< SelectCombined< LeftType, RightType, type >::E , SelectCombined< LeftType, RightType, type >::D , domainDim, SelectCombined< LeftType, RightType, type >::R , rangeDim, rangeDimCols >::dimDomain static inherited
const size_t Dune::XT::Functions::LocalfunctionSetInterface< SelectCombined< LeftType, RightType, type >::E , SelectCombined< LeftType, RightType, type >::D , domainDim, SelectCombined< LeftType, RightType, type >::R , rangeDim, rangeDimCols >::dimRange static inherited
const size_t Dune::XT::Functions::LocalfunctionSetInterface< SelectCombined< LeftType, RightType, type >::E , SelectCombined< LeftType, RightType, type >::D , domainDim, SelectCombined< LeftType, RightType, type >::R , rangeDim, rangeDimCols >::dimRangeCols static inherited
const EntityType& Dune::XT::Functions::LocalfunctionSetInterface< SelectCombined< LeftType, RightType, type >::E , SelectCombined< LeftType, RightType, type >::D , domainDim, SelectCombined< LeftType, RightType, type >::R , rangeDim, rangeDimCols >::entity_ protected inherited
The documentation for this class was generated from the following file:
combined.hh